<?php
/**
 * XSL stylesheet for the translated sitemaps.
 *
 * Served as a PHP file so it can pick up the site's own colours and title
 * without a build step. Browsers apply it via the <?xml-stylesheet?>
 * instruction; crawlers ignore it entirely, so it cannot affect indexing.
 *
 * Without this a browser renders the raw XML tree, which is unreadable for a
 * client reviewing coverage and makes every <loc> unclickable.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

header( 'Content-Type: application/xslt+xml; charset=UTF-8' );
echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	exclude-result-prefixes="sm xhtml">

<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<meta name="robots" content="noindex,follow"/>
	<title>XML Sitemap</title>
	<style>
		:root { --ink:#101418; --muted:#5b6672; --line:#e4e8ec; --accent:#0b5fff; --bg:#f7f9fb; }
		* { box-sizing:border-box; }
		body { margin:0; padding:32px 20px 64px; background:var(--bg); color:var(--ink);
			font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
		.wrap { max-width:1100px; margin:0 auto; }
		h1 { margin:0 0 6px; font-size:24px; letter-spacing:-.01em; }
		.sub { color:var(--muted); margin:0 0 24px; font-size:14px; }
		.card { background:#fff; border:1px solid var(--line); border-radius:10px; overflow:hidden;
			box-shadow:0 1px 2px rgba(16,20,24,.04); }
		table { width:100%; border-collapse:collapse; }
		th { text-align:left; font-size:11px; letter-spacing:.06em; text-transform:uppercase;
			color:var(--muted); padding:12px 16px; border-bottom:1px solid var(--line); background:#fbfcfd;
			position:sticky; top:0; }
		td { padding:11px 16px; border-bottom:1px solid var(--line); vertical-align:top;
			word-break:break-word; }
		tr:last-child td { border-bottom:0; }
		tr:hover td { background:#f9fbff; }
		a { color:var(--accent); text-decoration:none; }
		a:hover { text-decoration:underline; }
		.num { color:var(--muted); font-variant-numeric:tabular-nums; width:56px; }
		.date { color:var(--muted); white-space:nowrap; font-variant-numeric:tabular-nums; }
		.tag { display:inline-block; padding:1px 7px; margin:1px 3px 1px 0; border-radius:4px;
			background:#eef2f7; color:#41505f; font-size:11px; font-weight:600; letter-spacing:.02em; }
		.tag.x { background:#fff3d6; color:#7a5a00; }
		.note { margin-top:18px; color:var(--muted); font-size:13px; }
	</style>
</head>
<body>
<div class="wrap">

	<xsl:if test="sm:sitemapindex">
		<h1>XML Sitemap Index</h1>
		<p class="sub">
			<xsl:value-of select="count(sm:sitemapindex/sm:sitemap)"/> sitemaps, one per language.
			This file is for search engines; the links below are browsable.
		</p>
		<div class="card">
			<table>
				<tr><th class="num">#</th><th>Sitemap</th><th>Last modified</th></tr>
				<xsl:for-each select="sm:sitemapindex/sm:sitemap">
					<tr>
						<td class="num"><xsl:value-of select="position()"/></td>
						<td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
						<td class="date"><xsl:value-of select="substring(sm:lastmod,1,10)"/></td>
					</tr>
				</xsl:for-each>
			</table>
		</div>
	</xsl:if>

	<xsl:if test="sm:urlset">
		<h1>XML Sitemap</h1>
		<p class="sub">
			<xsl:value-of select="count(sm:urlset/sm:url)"/> URLs.
			Each entry lists its language alternates (hreflang) for search engines.
		</p>
		<div class="card">
			<table>
				<tr><th class="num">#</th><th>URL</th><th>Alternates</th><th>Last modified</th></tr>
				<xsl:for-each select="sm:urlset/sm:url">
					<tr>
						<td class="num"><xsl:value-of select="position()"/></td>
						<td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
						<td>
							<xsl:for-each select="xhtml:link">
								<a href="{@href}">
									<xsl:attribute name="class">
										<xsl:choose>
											<xsl:when test="@hreflang='x-default'">tag x</xsl:when>
											<xsl:otherwise>tag</xsl:otherwise>
										</xsl:choose>
									</xsl:attribute>
									<xsl:value-of select="@hreflang"/>
								</a>
							</xsl:for-each>
						</td>
						<td class="date"><xsl:value-of select="substring(sm:lastmod,1,10)"/></td>
					</tr>
				</xsl:for-each>
			</table>
		</div>
	</xsl:if>

	<p class="note">Generated by amplifi.translate.</p>
</div>
</body>
</html>
</xsl:template>

</xsl:stylesheet>
