<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * Czech term base (en -> cs). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Built 2026-09-25 from the site concept list plus a live
 * sample of 12 /cs/ pages.
 */
return array(
	array( 'en' => '*', 'cs' => 'V celém textu platí formální vykání: čtenáře oslovujte druhou osobou množného čísla a přivlastňovacím „váš / vaše“, a to i v nadpisech, v metadatech, v alt textech a v zástupných textech formulářů. Neformální oslovení jednotlivce (2. osoba jednotného čísla) se na tomto webu nesmí vyskytnout nikde. Tam, kde je vlastníkem podmět věty, je povinné zvratné přivlastňovací zájmeno: „popište svůj požadavek“, nikoli „popište váš požadavek“. Akční tlačítka a výzvy k akci zachovávají sloveso anglického originálu v rozkazovacím způsobu množného čísla: „Kontaktujte nás“, „Vyžádejte si demo“, „Stáhněte si brožuru“, „Promluvte si s odborníkem“, „Odešlete servisní požadavek“. Čistě navigační, filtrovací a stavové ovládací prvky mají infinitiv: „Procházet katalog“, „Procházet všechny materiály“, „Zobrazit vše“, „Hledat“. Sloveso v popisku tlačítka nikdy neredukujte na holé podstatné jméno.', 'not' => array( 'tvůj', 'tvoje', 'tvého', 'tvému', 'tvým', 'tvými', 'tvých', 'tvoji', 'tvou', 'tvojí', 'tobě', 'tebe', 'tebou', 'můžeš', 'nemůžeš', 'chceš', 'nechceš', 'potřebuješ', 'nepotřebuješ', 'nemáš', 'budeš', 'nevíš', 'získáš', 'najdeš', 'uvidíš', 'ušetříš', 'dostaneš', 'zjisti', 'začni', 'stáhni', 'přečti', 'podívej', 'klikni', 'prohlédni', 'navštiv', 'požádej', 'zeptej', 'napiš', 'vyplň', 'pošli', 'rezervuj', 'přihlas', 'zaregistruj' ) ),
	array( 'en' => '20-high / six-high mill', 'cs' => 'dvacetiválcová / šestiválcová stolice', 'not' => array( 'dvacetivysoká stolice', 'šestivysoká stolice', 'válcovna s 20 válci' ) ),
	array( 'en' => '3-jaw chuck', 'cs' => 'tříčelisťové sklíčidlo', 'not' => array( 'tříčelisťový sklíčidlo', 'sklíčidlo se třemi čelistmi', 'tříbodové sklíčidlo' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'cs' => 'A DESIGN / B LOGO', 'not' => array( 'NÁVRH A', 'LOGO B' ) ),
	array( 'en' => 'active part probing', 'cs' => 'aktivní měření dílu', 'not' => array( 'aktivní sondování dílu', 'aktivní snímání součásti' ) ),
	array( 'en' => 'actuation systems', 'cs' => 'systémy akčních členů', 'not' => array( 'aktivační systémy', 'aktuační systémy', 'systémy pohonu' ) ),
	array( 'en' => 'adaptive speed control', 'cs' => 'adaptivní regulace otáček', 'not' => array( 'adaptivní kontrola rychlosti', 'adaptivní řízení rychlosti' ) ),
	array( 'en' => 'ADAS (advanced driver assistance systems)', 'cs' => 'pokročilé asistenční systémy řidiče (ADAS)', 'not' => array( 'ADAS systémy', 'systémy pokročilé asistence řidiče' ) ),
	array( 'en' => 'ADAS alignment', 'cs' => 'kalibrace ADAS', 'not' => array( 'zarovnání ADAS', 'vyrovnání ADAS', 'seřízení ADAS' ) ),
	array( 'en' => 'ADVANCING THE MACHINE (trademark)', 'cs' => 'ADVANCING THE MACHINE', 'not' => array( 'POSOUVÁME STROJ', 'VPŘED SE STROJEM' ) ),
	array( 'en' => 'air cycle machines', 'cs' => 'vzduchové turbochladiče', 'not' => array( 'stroje se vzduchovým cyklem', 'vzduchové cyklické stroje' ) ),
	array( 'en' => 'anchoring (machine foundation)', 'cs' => 'ukotvení', 'not' => array( 'zakotvení', 'kotvení do země' ) ),
	array( 'en' => 'aperture plate', 'cs' => 'clonová deska', 'not' => array( 'otvorová deska', 'deska s otvorem' ) ),
	array( 'en' => 'applications (use cases)', 'cs' => 'příklady aplikací', 'not' => array() ),
	array( 'en' => 'armature', 'cs' => 'kotva', 'not' => array( 'armatura', 'výztuž', 'elektrický rotor' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES (trademark)', 'cs' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL ZDRAVOTNICTVÍ A VĚDY O ŽIVOTĚ', 'Ascential – zdravotnictví' ) ),
	array( 'en' => 'Ascential Test & Measurement (Systems)', 'cs' => 'Ascential Test & Measurement (Systems)', 'not' => array( 'Ascential systémy pro testování a měření', 'divize testování a měření Ascential' ) ),
	array( 'en' => 'Ask Burke Porter (page name)', 'cs' => 'Ask Burke Porter', 'not' => array( 'Zeptejte se Burke Porter', 'Zeptej se Burke Portera' ) ),
	array( 'en' => 'associate attorney', 'cs' => 'spolupracující advokát', 'not' => array( 'asistent advokáta', 'přidružený právník' ) ),
	array( 'en' => 'audit stations', 'cs' => 'auditní stanoviště', 'not' => array( 'auditní stanice', 'kontrolní stanice', 'revizní stanoviště' ) ),
	array( 'en' => 'automated handling cells', 'cs' => 'automatizovaná manipulační pracoviště', 'not' => array( 'automatizované manipulační buňky', 'automatické manipulační cely' ) ),
	array( 'en' => 'backhoe', 'cs' => 'rýpadlo-nakladač', 'not' => array( 'zadní lopata', 'bagr' ) ),
	array( 'en' => 'baler', 'cs' => 'lis na balíky', 'not' => array( 'balírka', 'balíkovač', 'balička' ) ),
	array( 'en' => 'bead breaking', 'cs' => 'odtlačení patky pneumatiky', 'not' => array( 'rozbíjení korálků', 'lámání patky' ) ),
	array( 'en' => 'bearers (balancer supports)', 'cs' => 'podpěry', 'not' => array( 'nosiče', 'nositelé' ) ),
	array( 'en' => 'bearing center lines', 'cs' => 'osy ložisek', 'not' => array( 'středové čáry ložisek', 'osové linie ložisek' ) ),
	array( 'en' => 'bearing life', 'cs' => 'životnost ložisek', 'not' => array( 'život ložiska', 'trvanlivost ložisek' ) ),
	array( 'en' => 'blade (grader)', 'cs' => 'radlice', 'not' => array( 'čepel', 'nůž grejdru', 'ostří' ) ),
	array( 'en' => 'blank ECM', 'cs' => 'nenaprogramovaná řídicí jednotka motoru', 'not' => array( 'prázdná ECM', 'čistá řídicí jednotka' ) ),
	array( 'en' => 'blast furnace', 'cs' => 'vysoká pec', 'not' => array( 'výbuchová pec', 'tavicí pec' ) ),
	array( 'en' => 'blowers', 'cs' => 'dmychadla', 'not' => array( 'foukače', 'ventilátory dmychadla', 'fukary' ) ),
	array( 'en' => 'bore axis alignment', 'cs' => 'ustavení osy vrtání', 'not' => array( 'zarovnání osy otvoru', 'vyrovnání osy díry' ) ),
	array( 'en' => 'boreless compressor wheel', 'cs' => 'kompresorové kolo bez otvoru', 'not' => array( 'bezotvorové kompresorové kolo', 'kolo bez vrtání' ) ),
	array( 'en' => 'boring (machining)', 'cs' => 'vyvrtávání', 'not' => array( 'nudné obrábění', 'vrtání otvorů' ) ),
	array( 'en' => 'boring drill (HDD)', 'cs' => 'vrtná souprava pro řízené horizontální vrtání', 'not' => array( 'nudná vrtačka', 'vrtací vrták' ) ),
	array( 'en' => 'branch', 'cs' => 'pobočka', 'not' => array( 'větev', 'odnož', 'filiálka' ) ),
	array( 'en' => 'Bristol (city)', 'cs' => 'Bristol', 'not' => array( 'Bristolu města' ) ),
	array( 'en' => 'built to last', 'cs' => 'stavěno na dlouhou životnost', 'not' => array( 'postaveno, aby vydrželo', 'vyrobeno k vydržení' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'cs' => 'Burke E. Porter Machinery', 'not' => array( 'Burke E. Porter Strojírny', 'strojírny Burke E. Porter' ) ),
	array( 'en' => 'Burke Porter Group', 'cs' => 'Burke Porter Group', 'not' => array( 'Skupina Burke Porter', 'Burke Porter skupina' ) ),
	array( 'en' => 'burst proof protection', 'cs' => 'ochrana proti roztržení', 'not' => array( 'ochrana proti prasknutí', 'odolnost proti výbuchu' ) ),
	array( 'en' => 'calibration target', 'cs' => 'kalibrační terč', 'not' => array( 'kalibrační cíl', 'kalibrační tabule' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'cs' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Kalibrace jako služba™' ) ),
	array( 'en' => 'capital equipment', 'cs' => 'investiční zařízení', 'not' => array( 'kapitálové vybavení', 'kapitálové zařízení' ) ),
	array( 'en' => 'cargo loading systems', 'cs' => 'systémy nakládky nákladu', 'not' => array( 'systémy zavážení nákladu', 'nákladní nakládací systémy' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'cs' => 'válcový dynamometr pro dvě a čtyři kola', 'not' => array( 'podvozkový dynamometr', 'dynamometr šasi' ) ),
	array( 'en' => 'chip vacuum', 'cs' => 'odsávání třísek', 'not' => array( 'vysavač čipů', 'vakuum na třísky' ) ),
	array( 'en' => 'clay gun', 'cs' => 'ucpávací stroj', 'not' => array( 'jílová pistole', 'hliněné dělo' ) ),
	array( 'en' => 'CMT-TR Polimer (model code)', 'cs' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR Polymer', 'CMT-TR pro polymery' ) ),
	array( 'en' => 'cold pilger mill', 'cs' => 'poutnická stolice za studena', 'not' => array( 'studená pilgrová válcovna', 'chladný pilger' ) ),
	array( 'en' => 'collet chuck', 'cs' => 'kleštinové sklíčidlo', 'not' => array( 'kleštinový upínač', 'objímkové sklíčidlo' ) ),
	array( 'en' => 'combine (harvester)', 'cs' => 'sklízecí mlátička', 'not' => array( 'kombajn kombinovaný', 'kombinace' ) ),
	array( 'en' => 'commercial vehicle', 'cs' => 'užitkové vozidlo', 'not' => array( 'komerční vozidlo', 'obchodní vozidlo' ) ),
	array( 'en' => 'commissioning', 'cs' => 'uvedení do provozu', 'not' => array( 'pověření', 'zadávání', 'komisionování' ) ),
	array( 'en' => 'Connect on LinkedIn', 'cs' => 'Spojte se na LinkedInu', 'not' => array( 'Připojte se na LinkedIn', 'Spojit se na LinkedIn', 'Kontakt na LinkedIn' ) ),
	array( 'en' => 'control (of a process)', 'cs' => 'řízení', 'not' => array( 'kontrola procesu', 'ovládání procesu' ) ),
	array( 'en' => 'control module', 'cs' => 'řídicí jednotka', 'not' => array( 'kontrolní modul', 'modul kontroly', 'řídící modul' ) ),
	array( 'en' => 'controls (control systems)', 'cs' => 'řídicí systémy', 'not' => array( 'kontrolní systémy', 'systémy kontroly', 'řídící systémy' ) ),
	array( 'en' => 'Core / Plus / Elite (service tiers)', 'cs' => 'Core / Plus / Elite', 'not' => array( 'Jádro / Plus / Elitní', 'Základ / Plus / Elita' ) ),
	array( 'en' => 'Corporate Roles', 'cs' => 'Firemní role', 'not' => array( 'Korporátní role', 'Podnikové pozice' ) ),
	array( 'en' => 'correction (of unbalance)', 'cs' => 'korekce nevyváženosti', 'not' => array( 'oprava nevyváženosti', 'korekce nevyvážení' ) ),
	array( 'en' => 'crankshaft lathe', 'cs' => 'soustruh na klikové hřídele', 'not' => array( 'klikový soustruh', 'soustruh klikovky' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'cs' => 'Crossroads Bank for Enterprises', 'not' => array( 'Křižovatková banka pro podniky', 'Banka na křižovatce' ) ),
	array( 'en' => 'cushion testing', 'cs' => 'zkouška tlumení', 'not' => array( 'testování polštáře', 'zkouška polštářování' ) ),
	array( 'en' => 'custom fixturing', 'cs' => 'zákaznické upínací přípravky', 'not' => array( 'vlastní fixace', 'zakázkové uchycení' ) ),
	array( 'en' => 'customer journey', 'cs' => 'zákaznická cesta', 'not' => array( 'cesta zákazníka po webu', 'zákaznický výlet' ) ),
	array( 'en' => 'Date: (signature block)', 'cs' => 'Datum:', 'not' => array( 'Termín:', 'Datum podpisu:' ) ),
	array( 'en' => 'deep hole drilling', 'cs' => 'hluboké vrtání', 'not' => array( 'vrtání hlubokých děr', 'hlubinné vrtání' ) ),
	array( 'en' => 'defensible (results)', 'cs' => 'obhajitelný', 'not' => array( 'obranný', 'bránitelný', 'defenzivní' ) ),
	array( 'en' => 'Deliverables', 'cs' => 'Výstupy plnění', 'not' => array( 'Dodávky', 'Doručitelné položky', 'Plnění dodávek' ) ),
	array( 'en' => 'deployment', 'cs' => 'nasazení', 'not' => array( 'rozmístění', 'rozvinutí', 'deployment' ) ),
	array( 'en' => 'design (of a machine)', 'cs' => 'konstrukce', 'not' => array( 'projekt stroje', 'návrhářství', 'dizajn' ) ),
	array( 'en' => 'dial indicator', 'cs' => 'číselníkový úchylkoměr', 'not' => array( 'ciferníkový indikátor', 'číselníkový indikátor' ) ),
	array( 'en' => 'disability insurance', 'cs' => 'pojištění invalidity', 'not' => array( 'invalidní pojistka', 'pojištění postižení' ) ),
	array( 'en' => 'discrete industries', 'cs' => 'diskrétní výroba', 'not' => array( 'diskrétní odvětví', 'oddělená odvětví' ) ),
	array( 'en' => 'draper header', 'cs' => 'pásová žací lišta', 'not' => array( 'draperový adaptér', 'závěsová hlava' ) ),
	array( 'en' => 'drift (cylinder)', 'cs' => 'samovolný pokles', 'not' => array( 'drift', 'unášení', 'samovolné unášení' ) ),
	array( 'en' => 'drivability', 'cs' => 'jízdní vlastnosti', 'not' => array( 'řiditelnost', 'pojízdnost', 'ovladatelnost' ) ),
	array( 'en' => 'dual mass flywheel', 'cs' => 'dvouhmotový setrvačník', 'not' => array( 'dvojhmotné setrvačníkové kolo', 'dvouhmotné kolo' ) ),
	array( 'en' => 'dynamometer', 'cs' => 'dynamometr', 'not' => array( 'dynamometrie', 'silomer', 'brzdová stolice' ) ),
	array( 'en' => 'eddy current technology', 'cs' => 'technologie vířivých proudů', 'not' => array( 'technologie vírových proudů', 'vířivá technologie' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'cs' => 'elektroerozivní texturování (EDT)', 'not' => array( 'technologie elektrického výboje', 'elektrovýbojové texturování', 'EDT texturování' ) ),
	array( 'en' => 'Email Disclosure (page name)', 'cs' => 'Prohlášení k e-mailové komunikaci', 'not' => array( 'Zveřejnění e-mailu', 'E-mailové odhalení' ) ),
	array( 'en' => 'EMC darkroom', 'cs' => 'bezodrazová komora EMC', 'not' => array( 'EMC temná komora', 'tmavá komora EMC' ) ),
	array( 'en' => 'end of line testing', 'cs' => 'testování na konci výrobní linky', 'not' => array( 'testování na konci linky', 'koncové testování', 'testování EOL' ) ),
	array( 'en' => 'energy recuperation', 'cs' => 'rekuperace energie', 'not' => array( 'obnova energie', 'zpětné získávání energie' ) ),
	array( 'en' => 'engine software loaders', 'cs' => 'zavaděče softwaru motoru', 'not' => array( 'nakladače softwaru motoru', 'loadery softwaru' ) ),
	array( 'en' => 'eRotor (product line)', 'cs' => 'eRotor', 'not' => array( 'e-rotor', 'elektrický rotor eRotor' ) ),
	array( 'en' => 'events & conferences', 'cs' => 'Akce a konference', 'not' => array( 'Události a konference', 'Eventy a konference' ) ),
	array( 'en' => 'excavator', 'cs' => 'rýpadlo', 'not' => array( 'exkavátor', 'bagr pásový', 'vykopávač' ) ),
	array( 'en' => 'exhaust extraction', 'cs' => 'odsávání výfukových plynů', 'not' => array( 'extrakce výfuku', 'odtah výfuku' ) ),
	array( 'en' => 'factory floor', 'cs' => 'výrobní hala', 'not' => array( 'tovární podlaha', 'podlaha závodu', 'dílenská podlaha' ) ),
	array( 'en' => 'failure rates (calibration)', 'cs' => 'míra poruchovosti', 'not' => array( 'sazby selhání', 'poměr selhání' ) ),
	array( 'en' => 'features', 'cs' => 'Funkce', 'not' => array( 'Rysy', 'Featury', 'Charakteristiky' ) ),
	array( 'en' => 'Featuring: <Brand>', 'cs' => 'Představujeme: <Brand>', 'not' => array( 'S účastí: <Brand>', 'Hlavní role: <Brand>' ) ),
	array( 'en' => 'field agents', 'cs' => 'terénní technici', 'not' => array( 'polní agenti', 'terénní agenti', 'agenti v poli' ) ),
	array( 'en' => 'field balancing', 'cs' => 'provozní vyvažování', 'not' => array( 'polní vyvažování', 'vyvažování v terénu' ) ),
	array( 'en' => 'filler', 'cs' => 'plnicí zařízení', 'not' => array( 'plnidlo', 'výplň', 'naplňovač' ) ),
	array( 'en' => 'filler gun', 'cs' => 'plnicí pistole', 'not' => array( 'plnicí zbraň', 'výplňová pistole' ) ),
	array( 'en' => 'final discharge', 'cs' => 'konečné vypuštění', 'not' => array( 'finální výboj', 'poslední vybití' ) ),
	array( 'en' => 'fine leak', 'cs' => 'jemný únik', 'not' => array( 'jemná netěsnost', 'malý průsak' ) ),
	array( 'en' => 'flexplate', 'cs' => 'pružná unášecí deska', 'not' => array( 'flexibilní deska', 'ohebná destička' ) ),
	array( 'en' => 'fluid power', 'cs' => 'hydraulika a pneumatika', 'not' => array( 'tekutinová energie', 'síla kapalin', 'kapalinová energie' ) ),
	array( 'en' => 'flywheel', 'cs' => 'setrvačník', 'not' => array( 'létající kolo', 'setrvačné kolo' ) ),
	array( 'en' => 'footprint (floor area)', 'cs' => 'zastavěná plocha', 'not' => array( 'stopa', 'otisk nohy', 'půdorysná stopa' ) ),
	array( 'en' => 'For Immediate Release', 'cs' => 'K okamžitému zveřejnění', 'not' => array( 'Pro okamžité vydání', 'K okamžitému vydání' ) ),
	array( 'en' => 'forged rolls', 'cs' => 'kované válce', 'not' => array( 'kované role', 'kované válečky' ) ),
	array( 'en' => 'front strut (suspension)', 'cs' => 'přední tlumičová vzpěra', 'not' => array( 'přední vzpěra zavěšení', 'přední podpěra' ) ),
	array( 'en' => 'gantry', 'cs' => 'portál', 'not' => array( 'brána', 'šibenice', 'rám portálu' ) ),
	array( 'en' => 'GDPR', 'cs' => 'GDPR', 'not' => array( 'nařízení o ochraně dat GDPR' ) ),
	array( 'en' => 'gear shift calibration', 'cs' => 'kalibrace řazení', 'not' => array( 'kalibrace převodovky', 'kalibrace řadicí páky' ) ),
	array( 'en' => 'grinding wheel', 'cs' => 'brusný kotouč', 'not' => array( 'mlecí kolo', 'brousicí kolo', 'brusné kolo' ) ),
	array( 'en' => 'gross leak test', 'cs' => 'zkouška hrubého úniku', 'not' => array( 'hrubý test netěsnosti', 'test velkého úniku' ) ),
	array( 'en' => 'gundrill', 'cs' => 'hlavňový vrták', 'not' => array( 'dělový vrták', 'pistolový vrták', 'gundrill' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'cs' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht a spol.', 'společnost Kleinknecht GmbH s r.o.' ) ),
	array( 'en' => 'half case (RDU/PTU)', 'cs' => 'poloviční skříň RDU/PTU', 'not' => array( 'půlka pouzdra', 'poloviční případ' ) ),
	array( 'en' => 'hay mower', 'cs' => 'žací stroj', 'not' => array( 'sekačka na seno', 'senová sekačka' ) ),
	array( 'en' => 'hazardous area', 'cs' => 'prostor s nebezpečím výbuchu', 'not' => array( 'nebezpečná oblast', 'riziková zóna' ) ),
	array( 'en' => 'health checks', 'cs' => 'kontroly technického stavu', 'not' => array( 'zdravotní kontroly', 'zdravotní prohlídky' ) ),
	array( 'en' => 'high production / high-volume production', 'cs' => 'velkosériová výroba', 'not' => array( 'vysoká výroba', 'vysokoobjemová produkce' ) ),
	array( 'en' => 'high-mix, low-volume', 'cs' => 'malosériová výroba s vysokou variabilitou', 'not' => array( 'vysoký mix, nízký objem', 'smíšená malá výroba' ) ),
	array( 'en' => 'high-performance teams', 'cs' => 'vysoce výkonné týmy', 'not' => array( 'vysokovýkonné týmy', 'týmy s vysokým výkonem' ) ),
	array( 'en' => 'higher-level control system', 'cs' => 'nadřazený řídicí systém', 'not' => array( 'vyšší řídicí systém', 'systém vyšší úrovně' ) ),
	array( 'en' => 'HMU/FMU', 'cs' => 'HMU/FMU', 'not' => array( 'jednotka HMU a FMU' ) ),
	array( 'en' => 'idle duration', 'cs' => 'doba volnoběhu', 'not' => array( 'doba nečinnosti', 'prostoj naprázdno' ) ),
	array( 'en' => 'implements', 'cs' => 'pracovní nářadí', 'not' => array( 'implementy', 'nástroje implementace', 'náčiní' ) ),
	array( 'en' => 'Imprint', 'cs' => 'Právní údaje', 'not' => array( 'Otisk', 'Tiráž', 'Impresum' ) ),
	array( 'en' => 'in a single clamping', 'cs' => 'na jedno upnutí', 'not' => array( 'v jednom sevření', 'při jednom uchycení' ) ),
	array( 'en' => 'infeed (grinding)', 'cs' => 'přísuv', 'not' => array( 'přívod', 'vstup materiálu', 'nájezd' ) ),
	array( 'en' => 'infinitely variable', 'cs' => 'plynule regulovatelný', 'not' => array( 'nekonečně proměnný', 'nekonečně variabilní' ) ),
	array( 'en' => 'inline crankshaft', 'cs' => 'řadový klikový hřídel', 'not' => array( 'inline kliková hřídel', 'vestavěná klikovka' ) ),
	array( 'en' => 'inline dyno', 'cs' => 'linkový dynamometr', 'not' => array( 'inline dynamometr', 'vestavěný dynamometr' ) ),
	array( 'en' => 'insights', 'cs' => 'Poznatky', 'not' => array( 'Insighty', 'Vhledy', 'Náhledy' ) ),
	array( 'en' => 'instrument cluster', 'cs' => 'sdružený přístroj', 'not' => array( 'shluk přístrojů', 'přístrojový klastr' ) ),
	array( 'en' => 'keg finger holes', 'cs' => 'úchopové otvory sudu', 'not' => array( 'prstové otvory', 'otvory na prsty' ) ),
	array( 'en' => 'kinetostatics', 'cs' => 'kinetostatika', 'not' => array( 'kineticko-statická analýza' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'cs' => 'KvK (Kamer van Koophandel)', 'not' => array( 'Obchodní komora KvK' ) ),
	array( 'en' => 'Labour & Travel', 'cs' => 'Práce a cestovné', 'not' => array( 'Pracovní síla a cestování', 'Mzda a doprava' ) ),
	array( 'en' => 'landed cost model', 'cs' => 'model celkových dovozních nákladů', 'not' => array( 'model přistávacích nákladů', 'model vyložené ceny' ) ),
	array( 'en' => 'landing gear systems', 'cs' => 'podvozkové systémy letadel', 'not' => array( 'přistávací zařízení', 'systémy přistávacího podvozku' ) ),
	array( 'en' => 'leak detection', 'cs' => 'detekce úniků', 'not' => array( 'detekce netěsností', 'zjišťování netěsností', 'odhalování průsaků' ) ),
	array( 'en' => 'learning management system (LMS)', 'cs' => 'systém pro řízení výuky (LMS)', 'not' => array( 'systém managementu učení', 'LMS systém' ) ),
	array( 'en' => 'like-minded companies', 'cs' => 'podobně smýšlející firmy', 'not' => array( 'stejně smýšlející společnosti', 'firmy s podobnou myslí' ) ),
	array( 'en' => 'load capacity', 'cs' => 'únosnost', 'not' => array( 'kapacita zatížení', 'nakládací kapacita' ) ),
	array( 'en' => 'LPM (litres per minute)', 'cs' => 'l/min', 'not' => array( 'LPM litrů za minutu', 'litry na minutu LPM' ) ),
	array( 'en' => 'lube & scavenge pumps', 'cs' => 'mazací a odsávací čerpadla', 'not' => array( 'mazací a vyplachovací pumpy', 'lubrikační a sběrná čerpadla' ) ),
	array( 'en' => 'lubrication', 'cs' => 'mazání', 'not' => array( 'lubrikace', 'promazávání' ) ),
	array( 'en' => 'machine tools', 'cs' => 'obráběcí stroje', 'not' => array( 'strojní nástroje', 'stroje a nářadí' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'cs' => 'směrnice o strojních zařízeních 2006/42/ES', 'not' => array( 'směrnice o strojích 2006/42/EC', 'strojní směrnice 2006/42/EC' ) ),
	array( 'en' => 'machining cell', 'cs' => 'obráběcí pracoviště', 'not' => array( 'obráběcí buňka', 'strojní cela' ) ),
	array( 'en' => 'machinist', 'cs' => 'obráběč', 'not' => array( 'strojník', 'mechanik obrábění' ) ),
	array( 'en' => 'maintenance contracts', 'cs' => 'smlouvy o údržbě', 'not' => array( 'údržbové kontrakty', 'servisní kontrakty údržby' ) ),
	array( 'en' => 'marine (sector)', 'cs' => 'lodní průmysl', 'not' => array( 'mořský sektor', 'námořnictvo', 'marina' ) ),
	array( 'en' => 'maximum rotor diameter', 'cs' => 'maximální průměr rotoru', 'not' => array( 'největší rotorový průměr', 'max. rotorový průměr' ) ),
	array( 'en' => 'mental health care', 'cs' => 'péče o duševní zdraví', 'not' => array( 'mentální zdravotní péče', 'vzdálená zdravotní péče' ) ),
	array( 'en' => 'mill roll', 'cs' => 'válcovací válec', 'not' => array( 'mlýnský válec', 'role mlýna', 'válec mlýna' ) ),
	array( 'en' => 'misalignment (sensors)', 'cs' => 'nesouosost', 'not' => array( 'špatné zarovnání', 'nesprávné vyrovnání' ) ),
	array( 'en' => 'motor grader', 'cs' => 'grejdr', 'not' => array( 'motorový srovnávač', 'kopírovací stroj', 'srovnávač terénu' ) ),
	array( 'en' => 'motorized clamping', 'cs' => 'motorické upínání', 'not' => array( 'motorizované svěrání', 'poháněné sevření' ) ),
	array( 'en' => 'MRO', 'cs' => 'MRO', 'not' => array( 'údržba, opravy a provoz MRO' ) ),
	array( 'en' => 'mudding system (HDD)', 'cs' => 'systém výplachu', 'not' => array( 'bahnový systém', 'zablácený systém' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'cs' => 'naamloze vennootschap (NV)', 'not' => array( 'akciová společnost NV' ) ),
	array( 'en' => 'Name: (signature block)', 'cs' => 'Jméno a příjmení:', 'not' => array( 'Název:', 'Jméno:' ) ),
	array( 'en' => 'Netherlands (statutory)', 'cs' => 'Nizozemsko', 'not' => array( 'Holandsko', 'Nizozemí' ) ),
	array( 'en' => 'non-rotating balancing machine', 'cs' => 'nerotační vyvažovací stroj', 'not' => array( 'vyvažovací stroj bez rotoru', 'nerotující vyvažovačka', 'statický vyvažovací stroj' ) ),
	array( 'en' => 'obsolescence management', 'cs' => 'řízení zastarávání', 'not' => array( 'management zastarání', 'správa obsolescence' ) ),
	array( 'en' => 'off-highway', 'cs' => 'nesilniční technika', 'not' => array( 'mimo dálnici', 'mimosilniční', 'technika mimo silniční provoz' ) ),
	array( 'en' => 'oil drain', 'cs' => 'odtok oleje', 'not' => array( 'odpad oleje', 'olejová výpusť', 'otvor odpouštění oleje' ) ),
	array( 'en' => 'operations', 'cs' => 'provoz', 'not' => array( 'operace', 'chirurgie', 'operační činnosti' ) ),
	array( 'en' => 'opportunities', 'cs' => 'příležitosti', 'not' => array( 'oportunisté', 'možnosti oportunit' ) ),
	array( 'en' => 'patented', 'cs' => 'patentovaný', 'not' => array( 'zapatentovaný', 'chráněný patentem' ) ),
	array( 'en' => 'pedestals', 'cs' => 'stojany', 'not' => array( 'podstavce', 'piedestaly', 'sokly' ) ),
	array( 'en' => 'peers', 'cs' => 'srovnatelné společnosti', 'not' => array( 'vrstevníci', 'kolegové', 'peers' ) ),
	array( 'en' => 'performance', 'cs' => 'výkon', 'not' => array( 'představení', 'výkonnost stroje', 'performanci' ) ),
	array( 'en' => 'personal information / personal data', 'cs' => 'osobní údaje', 'not' => array( 'osobní informace', 'soukromá data' ) ),
	array( 'en' => 'pinches & bruises', 'cs' => 'skřípnutí a otlaky', 'not' => array( 'štípance a modřiny', 'sevření a pohmožděniny' ) ),
	array( 'en' => 'pinion gear', 'cs' => 'pastorek', 'not' => array( 'pastorkové kolo', 'ozubený pastorek', 'pignon' ) ),
	array( 'en' => 'pins (on pedestals)', 'cs' => 'čepy', 'not' => array( 'špendlíky', 'kolíky na stojanech', 'piny' ) ),
	array( 'en' => 'power drive units', 'cs' => 'pohonné jednotky', 'not' => array( 'jednotky napájení', 'silové pohony PDU' ) ),
	array( 'en' => 'Powered by', 'cs' => 'Využívá technologii', 'not' => array( 'Poháněno', 'Napájeno', 'Poháněno technologií' ) ),
	array( 'en' => 'President (of a company)', 'cs' => 'prezident', 'not' => array( 'předseda vlády', 'prezident republiky' ) ),
	array( 'en' => 'pressurization', 'cs' => 'natlakování', 'not' => array( 'přetlakování', 'pressurizace', 'natlakovávání' ) ),
	array( 'en' => 'probe alignment', 'cs' => 'ustavení sondy', 'not' => array( 'zarovnání sondy', 'vyrovnání sondy' ) ),
	array( 'en' => 'process recipe', 'cs' => 'výrobní receptura', 'not' => array( 'recept procesu', 'procesní recept' ) ),
	array( 'en' => 'propulsion & powertrain', 'cs' => 'pohon a hnací ústrojí', 'not' => array( 'propulze a powertrain', 'pohon a převodovka' ) ),
	array( 'en' => 'PTO (power take-off)', 'cs' => 'vývodový hřídel', 'not' => array( 'odběr výkonu PTO', 'hřídel odběru síly' ) ),
	array( 'en' => 'pulley', 'cs' => 'řemenice', 'not' => array( 'kladka', 'kolo řemenu', 'šejv' ) ),
	array( 'en' => 'punching (mass correction)', 'cs' => 'děrování', 'not' => array( 'proražení', 'punching', 'razítkování' ) ),
	array( 'en' => 'push and pull (thrust/pullback)', 'cs' => 'tlak a tah', 'not' => array( 'tlačení a tahání', 'strkání a tahání' ) ),
	array( 'en' => 'reconditioning (rolls)', 'cs' => 'renovace válců', 'not' => array( 'rekondice válců', 'přepracování válců' ) ),
	array( 'en' => 'refrigerant', 'cs' => 'chladivo', 'not' => array( 'chladicí kapalina', 'chladicí prostředek', 'mrazivo' ) ),
	array( 'en' => 'refrigerant charging', 'cs' => 'plnění chladivem', 'not' => array( 'nabíjení chladiva', 'ládování chladiva', 'napouštění chladiva', 'plnění chladiva' ) ),
	array( 'en' => 'refrigeration (sector)', 'cs' => 'chladicí technika', 'not' => array( 'mrazírenství', 'chladicí technologie', 'chladírenství' ) ),
	array( 'en' => 'Register (a legal register)', 'cs' => 'rejstřík', 'not' => array( 'registr osob', 'zápisník' ) ),
	array( 'en' => 'Registered office', 'cs' => 'Sídlo', 'not' => array( 'Registrovaná kancelář', 'Zapsaná kancelář' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'cs' => 'renovátoři a repasovny', 'not' => array( 'přestavitelé a rekonstruktéři', 'výrobci repasovaní' ) ),
	array( 'en' => 'remarketers', 'cs' => 'prodejci repasované techniky', 'not' => array( 'remarketéři', 'přeprodejci trhu' ) ),
	array( 'en' => 'reportable', 'cs' => 'vykazatelný', 'not' => array( 'nahlásitelný', 'reportovatelný' ) ),
	array( 'en' => 'represent (model a process)', 'cs' => 'modelovat', 'not' => array( 'reprezentovat', 'zastupovat', 'představovat' ) ),
	array( 'en' => 'residual unbalance', 'cs' => 'zbytková nevyváženost', 'not' => array( 'zbytkové nevyvážení', 'reziduální nerovnováha', 'zbytková nerovnováha' ) ),
	array( 'en' => 'responsive', 'cs' => 'pohotový', 'not' => array( 'responzivní', 'reagující na dotyk', 'odezvový' ) ),
	array( 'en' => 'restbus simulation', 'cs' => 'simulace zbytkové sběrnice', 'not' => array( 'simulace odpočinkové sběrnice', 'restbus simulace' ) ),
	array( 'en' => 'retaining rollers', 'cs' => 'přidržovací válce', 'not' => array( 'zádržné válečky', 'retenční válce', 'zadržovací rolny' ) ),
	array( 'en' => 'right-shoring', 'cs' => 'right-shoring', 'not' => array( 'správné pobřeží', 'pravé břehování' ) ),
	array( 'en' => 'roll inspection', 'cs' => 'kontrola válců', 'not' => array( 'inspekce válců', 'revize rolí' ) ),
	array( 'en' => 'Roll Shop Technologies (page title)', 'cs' => 'Technologie brusíren válců', 'not' => array( 'Technologie válcovny', 'Technologie dílny válců' ) ),
	array( 'en' => 'roller (brake tester)', 'cs' => 'válec', 'not' => array( 'váleček', 'rolna', 'kolečko' ) ),
	array( 'en' => 'roller brake tester', 'cs' => 'válcová zkušebna brzd', 'not' => array( 'válečkový tester brzd', 'rolnový brzdový tester' ) ),
	array( 'en' => 'rolling torque', 'cs' => 'moment valivého odporu', 'not' => array( 'valivý točivý moment', 'moment kutálení' ) ),
	array( 'en' => 'rotary diamond dressing', 'cs' => 'orovnávání rotačním diamantem', 'not' => array( 'rotační diamantové oblékání', 'diamantové rotační zdobení' ) ),
	array( 'en' => 'rotor wing aircraft', 'cs' => 'rotorová letadla', 'not' => array( 'letadla s rotorovým křídlem', 'vrtulníková křídla' ) ),
	array( 'en' => 'sealed assembly', 'cs' => 'hermeticky uzavřená sestava', 'not' => array( 'zapečetěná montáž', 'utěsněné shromáždění' ) ),
	array( 'en' => 'seamless link', 'cs' => 'plynulé propojení', 'not' => array( 'bezešvé spojení', 'bezešvý odkaz' ) ),
	array( 'en' => 'service professional', 'cs' => 'servisní odborník', 'not' => array( 'profesionál služeb', 'odborník na služby' ) ),
	array( 'en' => 'setup cycles', 'cs' => 'seřizovací cykly', 'not' => array( 'nastavovací cykly', 'setup cykly' ) ),
	array( 'en' => 'single bay', 'cs' => 'jedno pracoviště', 'not' => array( 'jedna zátoka', 'jednotlivé stání' ) ),
	array( 'en' => 'single cylinder crankshaft', 'cs' => 'jednoválcový klikový hřídel', 'not' => array( 'klikovka jednoho válce', 'hřídel s jedním válcem' ) ),
	array( 'en' => 'single station / multi station', 'cs' => 'jednostaniční / vícestaniční', 'not' => array( 'jedna stanice / více stanic', 'jednomístný / vícemístný' ) ),
	array( 'en' => 'site visit', 'cs' => 'návštěva na místě', 'not' => array( 'návštěva stránek', 'návštěva lokality', 'výjezd na web' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'cs' => 'čichací sonda', 'not' => array( 'čenichací kleště', 'nasávací kleště', 'šňupací sonda' ) ),
	array( 'en' => 'snubber', 'cs' => 'tlumič rázů', 'not' => array( 'snubber', 'ztlumovač', 'přítlak' ) ),
	array( 'en' => 'soak time', 'cs' => 'doba výdrže', 'not' => array( 'doba máčení', 'doba namáčení', 'čas nasáknutí' ) ),
	array( 'en' => 'spalls', 'cs' => 'odloupnutí povrchu', 'not' => array( 'odštěpky', 'spally', 'loupání' ) ),
	array( 'en' => 'special test facilities', 'cs' => 'speciální zkušebny', 'not' => array( 'speciální testovací zařízení', 'zvláštní testovací provozy' ) ),
	array( 'en' => 'spin testing machine', 'cs' => 'stroj pro roztáčecí zkoušky', 'not' => array( 'otáčecí zkušební stroj', 'spinovací tester' ) ),
	array( 'en' => 'sprayers', 'cs' => 'postřikovače', 'not' => array( 'rozprašovače', 'stříkačky', 'spreje' ) ),
	array( 'en' => 'squeak & rattle testing', 'cs' => 'zkoušky vrzání a chrastění', 'not' => array( 'testování skřípání a chrastítek', 'zkoušky pískání a rachotu' ) ),
	array( 'en' => 'stand-alone machine', 'cs' => 'samostatně stojící stroj', 'not' => array( 'stand-alone stroj', 'osamocený stroj' ) ),
	array( 'en' => 'Standardization at scale', 'cs' => 'Standardizace ve velkém měřítku', 'not' => array( 'Standardizace na váze', 'Standardizace v měřítku' ) ),
	array( 'en' => 'strip', 'cs' => 'pás', 'not' => array( 'proužek', 'pruh plechu', 'pásek' ) ),
	array( 'en' => 'Strip Lines', 'cs' => 'Linky pro zpracování pásu', 'not' => array( 'Pásové linky', 'Proužkové linky' ) ),
	array( 'en' => 'superabrasives', 'cs' => 'supertvrdá brusiva', 'not' => array( 'superabraziva', 'super brusné materiály' ) ),
	array( 'en' => 'surface separations', 'cs' => 'oddělení povrchové vrstvy', 'not' => array( 'povrchové separace', 'odloučení povrchu' ) ),
	array( 'en' => 'tap hole', 'cs' => 'odpichový otvor', 'not' => array( 'klepací otvor', 'otvor kohoutku' ) ),
	array( 'en' => 'tapered roller bearing', 'cs' => 'kuželíkové ložisko', 'not' => array( 'kuželové válečkové ložisko', 'zúžené válečkové ložisko' ) ),
	array( 'en' => 'tariffs', 'cs' => 'cla', 'not' => array( 'tarify', 'sazebníky', 'celní tarify' ) ),
	array( 'en' => 'tension (mechanical)', 'cs' => 'tahové napětí', 'not' => array( 'tenze', 'napínání pásu', 'napjatost' ) ),
	array( 'en' => 'third member', 'cs' => 'skříň rozvodovky', 'not' => array( 'třetí člen', 'třetí díl' ) ),
	array( 'en' => 'tin plating', 'cs' => 'cínování', 'not' => array( 'pocínování plechu', 'plátování cínem' ) ),
	array( 'en' => 'TIR / radial run-out', 'cs' => 'TIR / radiální házivost', 'not' => array( 'celková indikovaná odchylka', 'radiální výběh' ) ),
	array( 'en' => 'tire inflator', 'cs' => 'plnička pneumatik', 'not' => array( 'nafukovač pneumatik', 'huštič gum' ) ),
	array( 'en' => 'torque vectoring', 'cs' => 'vektorování točivého momentu', 'not' => array( 'torque vectoring', 'vektorizace momentu' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS (trademark)', 'cs' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'CELKOVÁ KOMERCIALIZAČNÍ ŘEŠENÍ' ) ),
	array( 'en' => 'traceable tests', 'cs' => 'dohledatelné zkoušky', 'not' => array( 'sledovatelné testy', 'stopovatelné zkoušky' ) ),
	array( 'en' => 'tracer gas', 'cs' => 'stopovací plyn', 'not' => array( 'sledovací plyn', 'tracerový plyn' ) ),
	array( 'en' => 'traction battery (BMS)', 'cs' => 'trakční baterie', 'not' => array( 'tažná baterie', 'tahová baterie' ) ),
	array( 'en' => 'transmission / gearbox', 'cs' => 'převodovka', 'not' => array( 'transmise', 'přenos', 'převodová skříň motoru' ) ),
	array( 'en' => 'turbo calibration', 'cs' => 'kalibrace turbodmychadla', 'not' => array( 'turbo kalibrace', 'kalibrace turba' ) ),
	array( 'en' => 'turbocharger flow bench', 'cs' => 'průtoková zkušební stolice turbodmychadel', 'not' => array( 'průtoková lavice', 'stanoviště průtoku', 'průtoková stolice' ) ),
	array( 'en' => 'turbocharger frame size', 'cs' => 'velikostní řada turbodmychadla', 'not' => array( 'velikost rámu turba', 'rámová velikost turbodmychadla' ) ),
	array( 'en' => 'turnkey', 'cs' => 'na klíč', 'not' => array( 'otočením klíče', 'klíčové řešení turnkey', 'turnkey' ) ),
	array( 'en' => 'turret-style wheel head', 'cs' => 'revolverová brusná hlava', 'not' => array( 'věžová hlava kola', 'turretová hlava' ) ),
	array( 'en' => 'two-wheel drive', 'cs' => 'pohon dvou kol', 'not' => array( 'dvoukolový pohon', 'pohon na dvě kola' ) ),
	array( 'en' => 'ultra-stable design', 'cs' => 'mimořádně stabilní konstrukce', 'not' => array( 'ultrastabilní design', 'velmi stabilní projekt' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'cs' => 'ultrazvuková čistička trysek', 'not' => array( 'ultrazvukový čistič nozzlů', 'ultrazvukové mytí dýz' ) ),
	array( 'en' => 'unbalance', 'cs' => 'nevyváženost', 'not' => array( 'nevyvážení', 'nerovnováha', 'nevyrovnanost', 'disbalance' ) ),
	array( 'en' => 'unbeatable deals', 'cs' => 'bezkonkurenční nabídky', 'not' => array( 'neporazitelné obchody', 'nepřekonatelné dohody' ) ),
	array( 'en' => 'Universal Balancing', 'cs' => 'Universal Balancing', 'not' => array( 'Univerzální vyvažování', 'univerzální balancování' ) ),
	array( 'en' => 'uptime across systems', 'cs' => 'dostupnost systémů', 'not' => array( 'provozuschopnost napříč systémy', 'uptime systémů' ) ),
	array( 'en' => 'v-block support', 'cs' => 'prizmatická podpěra', 'not' => array( 'podpora v-bloku', 'V-blok podpěra' ) ),
	array( 'en' => 'vacuum evacuation', 'cs' => 'vakuování', 'not' => array( 'evakuace', 'vakuová evakuace', 'odsátí evakuací' ) ),
	array( 'en' => 'validate performance', 'cs' => 'ověřit výkon', 'not' => array( 'validovat performance', 'potvrdit představení' ) ),
	array( 'en' => 'valve body unit', 'cs' => 'ventilový blok', 'not' => array( 'těleso ventilu jednotky', 'jednotka těla ventilu' ) ),
	array( 'en' => 'vibration', 'cs' => 'vibrace', 'not' => array( 'chvění', 'kmitání stroje', 'vibrování' ) ),
	array( 'en' => 'volume flexibility', 'cs' => 'flexibilita objemu výroby', 'not' => array( 'objemová pružnost', 'flexibilita hlasitosti' ) ),
	array( 'en' => 'walking beam system', 'cs' => 'systém krokového posuvu', 'not' => array( 'chodící nosník', 'kráčející trám' ) ),
	array( 'en' => 'warranty coverage', 'cs' => 'rozsah záruky', 'not' => array( 'záruční pojištění', 'pokrytí záruky' ) ),
	array( 'en' => 'water meter', 'cs' => 'vodoměr', 'not' => array( 'měřič vody', 'vodní metr' ) ),
	array( 'en' => 'water-cooled', 'cs' => 'chlazený vodou', 'not' => array( 'chladicí vodou', 'vodou chladící' ) ),
	array( 'en' => 'WCAG four principles', 'cs' => 'čtyři principy WCAG', 'not' => array( 'WCAG čtyři principy', 'čtyři zásady WCAG' ) ),
	array( 'en' => 'wheel aligner', 'cs' => 'stroj pro geometrii kol', 'not' => array( 'zarovnávač kol', 'vyrovnávač kol' ) ),
	array( 'en' => 'wheel alignment', 'cs' => 'geometrie kol', 'not' => array( 'zarovnání kol', 'vyrovnání kol', 'srovnání kol' ) ),
	array( 'en' => 'WHEREAS (recital)', 'cs' => 'VZHLEDEM K TOMU, ŽE', 'not' => array( 'ZATÍMCO', 'KDEŽTO', 'ZATÍM CO' ) ),
	array( 'en' => 'whistle (turbo)', 'cs' => 'pískání', 'not' => array( 'píšťalka', 'hvizd', 'píšťala' ) ),
	array( 'en' => 'Work Product (defined term)', 'cs' => 'Dílo', 'not' => array( 'Pracovní produkt', 'Výsledek práce' ) ),
	array( 'en' => 'XL Machine', 'cs' => 'XL Machine', 'not' => array( 'Stroj XL', 'XL stroj' ) ),
	array( 'en' => 'Marketplace', 'cs' => 'Tržiště', 'not' => array( 'Marketplace', 'Tržní místo' ) ),
	array( 'en' => 'Medical', 'cs' => 'Medical', 'not' => array( 'Zdravotnictví', 'Lékařství', 'Medicínský' ) ),
	array( 'en' => 'Non-Rotate Systems', 'cs' => 'Nerotační systémy', 'not' => array( 'Systémy bez otáčení', 'Non-Rotate systémy' ) ),
	array( 'en' => 'Spin Testing', 'cs' => 'Roztáčecí zkoušky', 'not' => array( 'Spin testování', 'Zkoušky otáčení' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'cs' => 'Dopravníkové a papírenské válce', 'not' => array( 'Dopravník a papírové role', 'Dopravníkové a papírové role' ) ),
	array( 'en' => 'stem stickiness', 'cs' => 'zadírání dříku', 'not' => array( 'lepivost dříku', 'viskozita dříku', 'ulpívání stopky' ) ),
	array( 'en' => 'hydraulic pilot', 'cs' => 'pilotní hydraulické ovládání', 'not' => array( 'hydraulický pilot', 'hydraulický pilotní' ) ),
	array( 'en' => 'load sense signal', 'cs' => 'signál LS', 'not' => array( 'signál snímání zátěže', 'load sense signál' ) ),
	array( 'en' => 'debonding', 'cs' => 'odlepení', 'not' => array( 'debonding', 'rozlepování', 'odpojení lepidla' ) ),
	array( 'en' => 'movable cradle', 'cs' => 'pohyblivá kolébka', 'not' => array( 'pohyblivý držák', 'posuvná kolíbka' ) ),
	array( 'en' => 'thrust force / pullback force', 'cs' => 'tlačná síla / tažná síla', 'not' => array( 'tahová síla / zpětná síla', 'síla tlaku / síla stažení' ) ),
	array( 'en' => 'ring gears', 'cs' => 'ozubené věnce', 'not' => array( 'prstencová kola', 'kroužková ozubení' ) ),
	array( 'en' => 'blade timing', 'cs' => 'časování nožů', 'not' => array( 'načasování čepele', 'timing listů' ) ),
	array( 'en' => 'heavy-duty', 'cs' => 'pro těžký provoz', 'not' => array( 'těžkotonážní', 'silně zatížený', 'heavy-duty' ) ),
	array( 'en' => 'life sciences', 'cs' => 'vědy o živé přírodě', 'not' => array( 'životní vědy', 'vědy o životě' ) ),
	array( 'en' => 'First Alert Monitoring System', 'cs' => 'systém včasné výstrahy First Alert', 'not' => array( 'První výstražný monitorovací systém', 'systém monitorování První výstrahy' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'cs' => 'Turbo Test Duo Expert', 'not' => array( 'Expert Turbo Test Duo', 'Odborník Turbo Test Duo' ) ),
	array( 'en' => 'Board Member', 'cs' => 'člen představenstva', 'not' => array( 'člen rady', 'člen desky', 'boardový člen' ) ),
	array( 'en' => 'Principal', 'cs' => 'Principal', 'not' => array( 'Zásada', 'Hlavní', 'Ředitel školy' ) ),
	array( 'en' => 'Leadership', 'cs' => 'Vedení společnosti', 'not' => array( 'Vůdcovství', 'Leadership', 'Vedoucí pozice' ) ),
	array( 'en' => 'Introducing', 'cs' => 'Představujeme', 'not' => array( 'Uvádíme', 'Zavádíme', 'Introdukce' ) ),
	array( 'en' => 'flammable gases', 'cs' => 'hořlavé plyny', 'not' => array( 'zápalné plyny', 'vznětlivé plyny' ) ),
	array( 'en' => 'Electronic hung mass', 'cs' => 'elektronická zavěšená hmota', 'not' => array( 'elektronická visící hmotnost', 'elektronicky zavěšená váha' ) ),
	array( 'en' => 'Detection Focus', 'cs' => 'Zaměření detekce', 'not' => array( 'Detekční fokus', 'Ohnisko detekce' ) ),
	array( 'en' => 'weight capacity', 'cs' => 'nosnost', 'not' => array( 'váhová kapacita', 'kapacita hmotnosti' ) ),
	array( 'en' => 'vacuum', 'cs' => 'vakuum', 'not' => array( 'podtlak', 'prázdnota', 'vysavač' ) ),
	array( 'en' => 'vacuum rise test', 'cs' => 'zkouška nárůstu vakua', 'not' => array( 'test vzestupu podtlaku', 'zkouška růstu podtlaku' ) ),
	array( 'en' => 'fixed stations', 'cs' => 'pevná stanoviště', 'not' => array( 'fixní stanice', 'pevné stanice' ) ),
	array( 'en' => 'mobile carousels', 'cs' => 'mobilní karusely', 'not' => array( 'pohyblivé kolotoče', 'mobilní kolotoče' ) ),
	array( 'en' => 'cooling units', 'cs' => 'chladicí jednotky', 'not' => array( 'chladící jednotky', 'ochlazovací jednotky' ) ),
	array( 'en' => 'e-axle', 'cs' => 'elektrická náprava', 'not' => array( 'e-osa', 'elektrická osa' ) ),
	array( 'en' => 'keg', 'cs' => 'sud', 'not' => array( 'soudek piva', 'barel', 'kega' ) ),
	array( 'en' => 'horizontal boring machine', 'cs' => 'horizontální vyvrtávačka', 'not' => array( 'vodorovný nudný stroj', 'horizontální vrtačka' ) ),
	array( 'en' => 'test benches / test stands', 'cs' => 'zkušební stolice', 'not' => array( 'testovací lavice', 'zkušební stojany', 'testovací stánky' ) ),
	array( 'en' => 'testing', 'cs' => 'testování', 'not' => array( 'zkoušení kvality', 'testace' ) ),
	array( 'en' => 'Aerospace & industrials', 'cs' => 'Letectví, kosmonautika a průmysl', 'not' => array( 'Letecko-kosmický průmysl a průmyslové aplikace', 'Letectví a průmysl', 'Sektor letecko-kosmický a průmyslový', 'Letecký a průmyslový sektor' ) ),
	array( 'en' => 'Exhibit', 'cs' => 'Příloha', 'not' => array( 'Exponát', 'Výstava', 'Exhibit' ) ),
	array( 'en' => 'Section', 'cs' => 'Článek', 'not' => array( 'Sekce', 'Oddíl', 'Paragraf' ) ),
	array( 'en' => 'RECITALS', 'cs' => 'PREAMBULE', 'not' => array( 'RECITÁLY', 'ÚVODNÍ USTANOVENÍ RECITÁLY' ) ),
	array( 'en' => 'Products', 'cs' => 'Produkty', 'not' => array( 'Výrobky', 'Zboží', 'Produkce' ) ),
	array( 'en' => 'Ascential Indemnity', 'cs' => 'Odškodnění ze strany společnosti Ascential', 'not' => array( 'Ascential odškodnění', 'Ascential Indemnity' ) ),
	array( 'en' => 'England', 'cs' => 'Anglie', 'not' => array( 'England', 'Velká Británie Anglie' ) ),
	array( 'en' => 'West Flanders', 'cs' => 'Západní Flandry', 'not' => array( 'West Flanders', 'Západní Flanderska' ) ),
	array( 'en' => 'Poland', 'cs' => 'Polsko', 'not' => array( 'Poland', 'Polská republika Poland' ) ),
	array( 'en' => 'Play', 'cs' => 'Přehrát', 'not' => array( 'Hrát si', 'Zahrát si', 'Spustit hru' ) ),
	array( 'en' => 'Listen to this article', 'cs' => 'Poslechněte si tento článek', 'not' => array( 'Poslouchat tento článek', 'Naslouchejte článku' ) ),
	array( 'en' => 'Read the article', 'cs' => 'Přečtěte si článek', 'not' => array( 'Číst článek', 'Přečíst si článek', 'Číst dále' ) ),
	array( 'en' => 'N chapters', 'cs' => 'kapitol', 'not' => array( 'kapitoly N', 'oddílů' ) ),
	array( 'en' => 'Share / Copy link / Email', 'cs' => 'Sdílet / Kopírovat odkaz / E-mail', 'not' => array( 'Sdílení / Kopie odkazu / Mail', 'Podíl / Zkopírovat link / Email' ) ),
	array( 'en' => '<Model> Refrigerant Charging Brochure', 'cs' => 'Brožura plnění chladivem <Model>', 'not' => array( 'Brožura nabíjení chladiva <Model>', '<Model> brožura plnění chladiva' ) ),
	array( 'en' => 'Titan <Application> System', 'cs' => 'systém Titan <Application>', 'not' => array( 'Titan <Application> systém', 'Titánový systém <Application>' ) ),
	array( 'en' => 'Explore', 'cs' => 'Prozkoumat', 'not' => array( 'Objevit', 'Prozkoumejte to', 'Prozkoumávat' ) ),
	array( 'en' => 'Browse catalog', 'cs' => 'Procházet katalog', 'not' => array( 'Katalog produktů ke stažení', 'Prohlížení katalogu', 'Katalogu' ) ),
	array( 'en' => 'Browse all resources', 'cs' => 'Procházet všechny materiály', 'not' => array( 'Všechny zdroje', 'Prohlížet zdroje', 'Materiály ke stažení' ) ),
	array( 'en' => 'Explore the Catalog', 'cs' => 'Prozkoumat katalog', 'not' => array( 'Objevit katalog', 'Prozkoumat katalogu' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'cs' => 'Jste připraveni modernizovat svou infrastrukturu?', 'not' => array( 'Připraven na modernizaci infrastruktury?', 'Jste připraven modernizovat vaši infrastrukturu?' ) ),
	array( 'en' => 'gantry milling', 'cs' => 'portálové frézování', 'not' => array( 'frézování portálem', 'brána frézování' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'cs' => 'Kombinovaný vysokootáčkový a nízkootáčkový vyvažovací stroj jader', 'not' => array( 'Kombinovaný rychlý a pomalý vyvažovací stroj', 'Kombinovaná vyvažovačka jader' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'cs' => 'Dynamická průtoková zkušební stolice turbodmychadel', 'not' => array( 'Dynamická průtoková lavice', 'Dynamické stanoviště průtoku turba' ) ),
	array( 'en' => 'actionable insights', 'cs' => 'využitelné poznatky', 'not' => array( 'akční poznatky', 'akceschopné vhledy', 'actionable insighty' ) ),
	array( 'en' => 'expert insights', 'cs' => 'odborné poznatky', 'not' => array( 'expertní insighty', 'znalecké vhledy' ) ),
	array( 'en' => 'fully loaded test', 'cs' => 'zkouška při plném zatížení', 'not' => array( 'plně naložený test', 'test s plným nákladem' ) ),
	array( 'en' => 'Addresses', 'cs' => 'Řeší', 'not' => array( 'Eliminuje', 'Odstraňuje', 'Adresuje' ) ),
	array( 'en' => 'is now', 'cs' => 'nyní', 'not' => array( 'je teď', 'je nyní nově' ) ),
	array( 'en' => 'sales inquiry', 'cs' => 'obchodní poptávka', 'not' => array( 'dotaz na prodej', 'prodejní dotaz', 'obchodní dotaz' ) ),
	array( 'en' => 'Priority 1/2/3', 'cs' => 'Priorita 1/2/3', 'not' => array( 'Přednost 1/2/3', 'Prioritní 1/2/3' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'cs' => 'Vyhledávání na ascentialtech.com', 'not' => array( 'Hledání ascentialtech.com', 'Prohledávám ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'cs' => 'Zobrazení kalendáře není dostupné', 'not' => array( 'Kalendářní pohled nedostupný', 'Náhled kalendáře nedostupný' ) ),
	array( 'en' => 'hazardous areas', 'cs' => 'prostory s nebezpečím výbuchu', 'not' => array( 'nebezpečné oblasti', 'rizikové zóny' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'cs' => 'Pracovní nářadí – konec výrobní linky', 'not' => array( 'Implementy - konec linky', 'Nářadí - End-Of-Line' ) ),
	array( 'en' => 'Ascential Technologies', 'cs' => 'Ascential Technologies', 'not' => array( 'Technologie Ascential', 'společnost Ascentialu' ) ),
	array( 'en' => 'Ascential Care', 'cs' => 'Ascential Care', 'not' => array( 'Péče Ascential', 'Ascential péče', 'Ascential Péče' ) ),
	array( 'en' => 'Ascentialytics', 'cs' => 'Ascentialytics', 'not' => array( 'Ascential analytika', 'Ascentialytika' ) ),
	array( 'en' => 'Burke Porter', 'cs' => 'Burke Porter', 'not' => array( 'Burke Portera firma', 'Společnost Burkeho Portera' ) ),
	array( 'en' => 'Cimat', 'cs' => 'Cimat', 'not' => array( 'Cimatu značka', 'Cimatovy stroje' ) ),
	array( 'en' => 'Galileo', 'cs' => 'Galileo', 'not' => array( 'Galileovy systémy', 'Galilei' ) ),
	array( 'en' => 'Kleinknecht', 'cs' => 'Kleinknecht', 'not' => array( 'Kleinknechtovy systémy', 'Malý sluha' ) ),
	array( 'en' => 'Lismar', 'cs' => 'Lismar', 'not' => array( 'Lismaru značka', 'Lismarovy systémy' ) ),
	array( 'en' => 'Titan', 'cs' => 'Titan', 'not' => array( 'Titánový', 'Titán', 'Titanový systém' ) ),
	array( 'en' => 'Bauer', 'cs' => 'Bauer', 'not' => array( 'Bauerovy stolice', 'Sedlák' ) ),
	array( 'en' => 'Sentia', 'cs' => 'Sentia', 'not' => array( 'Sentie značka', 'Sentiovy funkce' ) ),
	array( 'en' => 'WinterPark', 'cs' => 'WinterPark', 'not' => array( 'Zimní park', 'Winter Park park' ) ),
	array( 'en' => 'Winbal', 'cs' => 'Winbal', 'not' => array( 'Winbalu software', 'Vyvažovací software Winbal' ) ),
	array( 'en' => 'UNI-64', 'cs' => 'UNI-64', 'not' => array( 'UNI 64 systém', 'Uni-64 měřidlo' ) ),
	array( 'en' => 'Cerberus X1', 'cs' => 'Cerberus X1', 'not' => array( 'Kerberos X1', 'Cerberos X1' ) ),
	array( 'en' => 'ADAS Garage', 'cs' => 'ADAS Garage', 'not' => array( 'Garáž ADAS', 'ADAS garáž' ) ),
	array( 'en' => 'Impossible? Done.', 'cs' => 'Impossible? Done.', 'not' => array( 'Nemožné? Hotovo.', 'Nemožné? Splněno.' ) ),
	array( 'en' => 'Ask Burke', 'cs' => 'Ask Burke', 'not' => array( 'Zeptejte se Burkeho', 'Zeptej se Burke' ) ),
	array( 'en' => 'Automotive Industry Balancers', 'cs' => 'Vyvažovací stroje pro automobilový průmysl', 'not' => array( 'Vyvažovače automobilového průmyslu', 'Balancéry pro autoprůmysl' ) ),
	array( 'en' => 'Brushing and Polishing Machines', 'cs' => 'Kartáčovací a lešticí stroje', 'not' => array( 'Brusky a leštičky', 'Brousicí a leštící stroje', 'Kartáčovací a leštící stroje' ) ),
	array( 'en' => 'Leak Detection & Refrigeration', 'cs' => 'Detekce úniků a chladicí technika', 'not' => array( 'Detekce netěsností a chladicí technika', 'Detekce netěsností a chlazení' ) ),
	array( 'en' => 'Gas Management & Refrigeration', 'cs' => 'Správa plynů a chladicí technika', 'not' => array( 'Chladicí technika a správa plynů', 'Řízení plynů a chlazení' ) ),
	array( 'en' => 'Evacuation', 'cs' => 'Vakuování', 'not' => array( 'Evakuace', 'Odsávání evakuací' ) ),
	array( 'en' => 'Retrofit and Modernization', 'cs' => 'Retrofity a modernizace', 'not' => array( 'Modernizace a obnova', 'Dovybavení a modernizace' ) ),
	array( 'en' => 'Robot Applications', 'cs' => 'Robotické aplikace', 'not' => array( 'Aplikace robotů', 'Robotí aplikace' ) ),
	array( 'en' => 'Horizontal', 'cs' => 'Horizontální stroje', 'not' => array( 'Horizontálně', 'Vodorovný' ) ),
	array( 'en' => 'Vertical', 'cs' => 'Vertikální stroje', 'not' => array( 'Vertikálně', 'Svislý' ) ),
	array( 'en' => 'Industrial Balancing Machine', 'cs' => 'Průmyslové vyvažovací stroje', 'not' => array( 'Průmyslová vyvažovačka', 'Industriální vyvažovací stroj' ) ),
	array( 'en' => 'Balancing Machines', 'cs' => 'Vyvažovací stroje', 'not' => array( 'Stroje na vyvažování', 'Balancovací stroje', 'Vyvažovačky' ) ),
	array( 'en' => 'Rotor balancing machines', 'cs' => 'Vyvažovací stroje rotorů', 'not' => array( 'Stroje na vyvažování rotorů', 'Rotorové vyvažovačky' ) ),
	array( 'en' => 'Driveshaft balancing machine', 'cs' => 'Vyvažovací stroj hnacích hřídelů', 'not' => array( 'Stroje na vyvažování hřídelů', 'Vyvažovačka kardanů' ) ),
	array( 'en' => 'Dynamic balancing machines', 'cs' => 'Dynamické vyvažovací stroje', 'not' => array( 'Stroje na dynamické vyvažování', 'Dynamické vyvažovačky' ) ),
	array( 'en' => 'Propeller balancers', 'cs' => 'Vyvažovací stroje vrtulí', 'not' => array( 'Vyvažovače vrtulí', 'Balancéry vrtulí' ) ),
	array( 'en' => 'Calibration & Testing', 'cs' => 'Kalibrace a zkoušení', 'not' => array( 'Kalibrace a testování kvality', 'Kalibrování a testy' ) ),
	array( 'en' => 'maintenance inspections', 'cs' => 'kontroly v rámci údržby', 'not' => array( 'inspekce údržby', 'údržbové inspekce', 'plánované inspekce' ) ),
	array( 'en' => 'inspection', 'cs' => 'kontrola', 'not' => array( 'inspekce', 'revizní inspekce' ) ),
	array( 'en' => 'defect', 'cs' => 'vada', 'not' => array( 'defekt', 'závada povrchu defekt' ) ),
	array( 'en' => 'technicians', 'cs' => 'servisní technici', 'not' => array( 'naše nejlepší techniky', 'technikáři' ) ),
	array( 'en' => 'RPM', 'cs' => 'otáčky za minutu', 'not' => array( 'rychlost RPM', 'provozní rychlost RPM', 'otáčky rychlosti' ) ),
	array( 'en' => 'operating speed', 'cs' => 'provozní otáčky', 'not' => array( 'provozní rychlost', 'pracovní rychlost' ) ),
	array( 'en' => 'Ebooks', 'cs' => 'E-knihy', 'not' => array( 'E-booky', 'Elektronické knihy', 'Ebooky' ) ),
	array( 'en' => 'Case Study', 'cs' => 'Případová studie', 'not' => array( 'Studie případu', 'Case study', 'Kazuistika' ) ),
	array( 'en' => 'Technical Papers', 'cs' => 'Odborné studie', 'not' => array( 'Technické papíry', 'Odborné zprávy', 'Technické dokumenty' ) ),
	array( 'en' => 'whitepaper', 'cs' => 'odborná studie', 'not' => array( 'odborná zpráva', 'bílá kniha', 'bílý papír' ) ),
	array( 'en' => 'Certifications', 'cs' => 'Certifikace', 'not' => array( 'Certifikáty osvědčení', 'Osvědčování' ) ),
	array( 'en' => 'Press Announcements', 'cs' => 'Tiskové zprávy', 'not' => array( 'Tisková oznámení', 'Oznámení pro tisk' ) ),
	array( 'en' => 'Webinars', 'cs' => 'Webináře', 'not' => array( 'Webové semináře', 'Web semináře' ) ),
	array( 'en' => 'Videos', 'cs' => 'Videa', 'not' => array( 'Videozáznamy', 'Filmy' ) ),
	array( 'en' => 'Blog', 'cs' => 'Blog', 'not' => array( 'Blogový příspěvek', 'Deníček' ) ),
	array( 'en' => 'Resources', 'cs' => 'Informační materiály', 'not' => array( 'Materiály ke stažení', 'Zdroje', 'Ke stažení', 'Zdroje informací' ) ),
	array( 'en' => 'Resource Type', 'cs' => 'Typ materiálu', 'not' => array( 'Typ zdroje', 'Druh zdroje' ) ),
	array( 'en' => 'Resource Topic', 'cs' => 'Téma materiálu', 'not' => array( 'Téma zdroje', 'Tematika zdrojů' ) ),
	array( 'en' => 'Business Unit', 'cs' => 'Divize', 'not' => array( 'Obchodní jednotka', 'Byznys jednotka' ) ),
	array( 'en' => 'Product Category', 'cs' => 'Kategorie produktů', 'not' => array( 'Produktová kategorie', 'Kategorie výrobku' ) ),
	array( 'en' => 'Schedule a Meeting', 'cs' => 'Domluvte si schůzku', 'not' => array( 'Naplánovat setkání', 'Rezervace schůzky', 'Naplánujte si meeting' ) ),
	array( 'en' => 'Speak to an expert', 'cs' => 'Promluvte si s odborníkem', 'not' => array( 'Hovořit s odborníkem', 'Mluvte s expertem', 'Hovořte s odborníkem' ) ),
	array( 'en' => 'Speak with a solutions expert', 'cs' => 'Promluvte si s odborníkem na naše řešení', 'not' => array( 'Promluvte si s odborníkem na řešení', 'Mluvte s expertem na řešení' ) ),
	array( 'en' => 'Speak with a service professional', 'cs' => 'Promluvte si se servisním odborníkem', 'not' => array( 'Promluvte si s profesionálem služeb', 'Hovořte s odborníkem na služby' ) ),
	array( 'en' => 'Get a quote', 'cs' => 'Získat nabídku', 'not' => array( 'Získejte cenovou nabídku', 'Poptat cenu', 'Nabídka ceny' ) ),
	array( 'en' => 'Get a service quote', 'cs' => 'Získat nabídku servisu', 'not' => array( 'Získejte servisní nabídku', 'Nabídka služeb ceny' ) ),
	array( 'en' => 'Request a quote', 'cs' => 'Vyžádejte si nabídku', 'not' => array( 'Žádost o nabídku', 'Požadavek na nabídku', 'Poptávka nabídky' ) ),
	array( 'en' => 'Request a demo', 'cs' => 'Vyžádejte si demo', 'not' => array( 'Žádost o demo', 'Požádat o ukázku', 'Prosba o demonstraci' ) ),
	array( 'en' => 'Download brochure', 'cs' => 'Stáhněte si brožuru', 'not' => array( 'Stažení brožury', 'Brožura ke stažení', 'Stáhnout brožuru' ) ),
	array( 'en' => 'Download', 'cs' => 'Stáhnout', 'not' => array( 'Ke stažení soubor', 'Stahování souboru' ) ),
	array( 'en' => 'Learn more', 'cs' => 'Zjistěte více', 'not' => array( 'Naučte se více', 'Zjistit více', 'Dozvědět se více' ) ),
	array( 'en' => 'Read more', 'cs' => 'Přečtěte si více', 'not' => array( 'Číst dále', 'Čtěte více', 'Více čtení' ) ),
	array( 'en' => 'Contact us', 'cs' => 'Kontaktujte nás', 'not' => array( 'Kontakt na nás', 'Spojte se s námi', 'Napište nám zprávu' ) ),
	array( 'en' => 'See our Solutions', 'cs' => 'Prohlédněte si naše řešení', 'not' => array( 'Viz naše řešení', 'Podívejte se na řešení naše' ) ),
	array( 'en' => 'View all press releases', 'cs' => 'Všechny tiskové zprávy', 'not' => array( 'Zobrazit veškeré tiskové zprávy', 'Prohlédnout tiskové zprávy' ) ),
	array( 'en' => 'View all events', 'cs' => 'Všechny akce', 'not' => array( 'Zobrazit veškeré akce', 'Prohlédnout události' ) ),
	array( 'en' => 'Register', 'cs' => 'Zaregistrujte se', 'not' => array( 'Registrovat se', 'Registrace na akci' ) ),
	array( 'en' => 'View full details', 'cs' => 'Zobrazit úplné údaje', 'not' => array( 'Zobrazit celé detaily', 'Prohlédnout plné podrobnosti' ) ),
	array( 'en' => 'Plan Levels', 'cs' => 'Úrovně plánu', 'not' => array( 'Plánovací úrovně', 'Úrovně plánování' ) ),
	array( 'en' => 'Response time', 'cs' => 'Doba odezvy', 'not' => array( 'Reakční čas', 'Čas odpovědi' ) ),
	array( 'en' => 'Intervention time (in business hours)', 'cs' => 'Doba zásahu (v pracovních hodinách)', 'not' => array( 'Intervenční čas', 'Doba intervence' ) ),
	array( 'en' => 'Onsite emergency response and coverage', 'cs' => 'Havarijní zásah na místě a jeho rozsah', 'not' => array( 'Nouzová odezva na místě a pokrytí', 'Pohotovostní reakce na místě' ) ),
	array( 'en' => 'Preventive maintenance', 'cs' => 'Preventivní údržba', 'not' => array( 'Prevenční údržba', 'Preventivní údržbová prohlídka' ) ),
	array( 'en' => 'System health check', 'cs' => 'Kontrola technického stavu systému', 'not' => array( 'Zdravotní kontrola systému', 'Prověrka zdraví systému' ) ),
	array( 'en' => 'Customer portal', 'cs' => 'Zákaznický portál', 'not' => array( 'Portál zákazníka', 'Klientský portál' ) ),
	array( 'en' => 'Instructor-led training', 'cs' => 'Školení vedené lektorem', 'not' => array( 'Trénink vedený instruktorem', 'Výuka s instruktorem' ) ),
	array( 'en' => 'Train the trainer (provided at start-up)', 'cs' => 'Školení školitelů (poskytováno při spuštění)', 'not' => array( 'Vycvič trenéra', 'Trénuj trenéra' ) ),
	array( 'en' => 'Self-service training material', 'cs' => 'Samoobslužné školicí materiály', 'not' => array( 'Samoobslužný tréninkový materiál', 'Školící materiály samoobsluhy' ) ),
	array( 'en' => 'Performance analysis', 'cs' => 'Analýza výkonu', 'not' => array( 'Analýza performance', 'Rozbor výkonnosti stroje' ) ),
	array( 'en' => 'Material / parts', 'cs' => 'Materiál a díly', 'not' => array( 'Materiál / části', 'Materiály / součástky' ) ),
	array( 'en' => 'Remote support', 'cs' => 'Vzdálená podpora', 'not' => array( 'Dálková podpora', 'Podpora na dálku vzdálená' ) ),
	array( 'en' => 'Standard rate', 'cs' => 'standardní sazba', 'not' => array( 'standardní tarif', 'běžná rychlost' ) ),
	array( 'en' => 'Discounted rate', 'cs' => 'zvýhodněná sazba', 'not' => array( 'slevněná sazba', 'diskontovaná rychlost' ) ),
	array( 'en' => 'Preferred rate', 'cs' => 'preferenční sazba', 'not' => array( 'upřednostněná rychlost', 'oblíbená sazba' ) ),
	array( 'en' => 'Next day', 'cs' => 'následující pracovní den', 'not' => array( 'další den', 'příští den' ) ),
	array( 'en' => 'Overview', 'cs' => 'Přehled', 'not' => array( 'Přehledně', 'Souhrnný pohled' ) ),
	array( 'en' => 'Specifications', 'cs' => 'Specifikace', 'not' => array( 'Technické údaje specifikace', 'Parametry specifikace' ) ),
	array( 'en' => 'Gallery', 'cs' => 'Galerie', 'not' => array( 'Obrázková galerie', 'Fotogalerie snímků' ) ),
	array( 'en' => 'Frequently asked questions', 'cs' => 'Často kladené otázky', 'not' => array( 'Časté dotazy otázky', 'Nejčastější otázky kladené' ) ),
	array( 'en' => 'Key features', 'cs' => 'Klíčové funkce', 'not' => array( 'Klíčové vlastnosti', 'Hlavní rysy' ) ),
	array( 'en' => 'Tests & Measurements', 'cs' => 'Testování a měření', 'not' => array( 'Testy a míry', 'Zkoušky a měřidla' ) ),
	array( 'en' => 'Related products', 'cs' => 'Související produkty', 'not' => array( 'Příbuzné produkty', 'Spojené výrobky' ) ),
	array( 'en' => 'Related resources', 'cs' => 'Související materiály', 'not' => array( 'Příbuzné zdroje', 'Související zdroje' ) ),
	array( 'en' => 'Trending Products', 'cs' => 'Oblíbené produkty', 'not' => array( 'Trendující produkty', 'Trendové výrobky' ) ),
	array( 'en' => 'Featured Solutions', 'cs' => 'Vybraná řešení', 'not' => array( 'Doporučená řešení nabízená', 'Význačná řešení' ) ),
	array( 'en' => 'Latest Press Releases', 'cs' => 'Nejnovější tiskové zprávy', 'not' => array( 'Poslední tiskové zprávy', 'Nejnovější novinky tiskové' ) ),
	array( 'en' => 'Upcoming Events', 'cs' => 'Nadcházející akce', 'not' => array( 'Připravované události', 'Budoucí akce' ) ),
	array( 'en' => 'In the news', 'cs' => 'V médiích', 'not' => array( 'V novinkách', 'Ve zprávách médií' ) ),
	array( 'en' => 'Sort by:', 'cs' => 'Seřadit podle:', 'not' => array( 'Třídit dle:', 'Setřídit podle:' ) ),
	array( 'en' => 'Clear all filters', 'cs' => 'Zrušit všechny filtry', 'not' => array( 'Vymazat všechny filtry', 'Vyčistit filtry' ) ),
	array( 'en' => 'Filter by category', 'cs' => 'Filtrovat podle kategorie', 'not' => array( 'Filtr dle kategorie', 'Třídit podle kategorie' ) ),
	array( 'en' => 'Expand all', 'cs' => 'Rozbalit vše', 'not' => array( 'Rozšířit vše', 'Roztáhnout všechny' ) ),
	array( 'en' => 'All products', 'cs' => 'Všechny produkty', 'not' => array( 'Veškeré produkty', 'Všechny výrobky zboží' ) ),
	array( 'en' => 'Loading products...', 'cs' => 'Načítání produktů…', 'not' => array( 'Nahrávání produktů', 'Zavádění výrobků' ) ),
	array( 'en' => 'Reset chat', 'cs' => 'Vymazat konverzaci', 'not' => array( 'Resetovat chat', 'Restartovat povídání' ) ),
	array( 'en' => 'Skip to content', 'cs' => 'Přejít na obsah', 'not' => array( 'Přeskočit na obsah', 'Skočit k obsahu' ) ),
	array( 'en' => 'Search', 'cs' => 'Hledat', 'not' => array( 'Vyhledat', 'Prohledat', 'Hledání' ) ),
	array( 'en' => 'Locations', 'cs' => 'Pobočky', 'not' => array( 'Lokality', 'Umístění', 'Místa' ) ),
	array( 'en' => 'Industries served', 'cs' => 'Odvětví, ve kterých působíme', 'not' => array( 'Odvětví, kterým sloužíme', 'Obsluhovaná odvětví', 'Odvětví, která obsluhujeme' ) ),
	array( 'en' => 'About', 'cs' => 'O nás', 'not' => array( 'O společnosti', 'Kdo jsme my' ) ),
	array( 'en' => 'Who we are', 'cs' => 'Kdo jsme', 'not' => array( 'Kdo my jsme', 'O nás samotných' ) ),
	array( 'en' => 'Company', 'cs' => 'Společnost', 'not' => array( 'Firma', 'Kompanie' ) ),
	array( 'en' => 'Careers', 'cs' => 'Kariéra', 'not' => array( 'Kariéry', 'Pracovní kariéra', 'Zaměstnání kariéra' ) ),
	array( 'en' => 'History & brands', 'cs' => 'Historie a značky', 'not' => array( 'Dějiny a značky', 'Historie a brandy' ) ),
	array( 'en' => 'Affiliates', 'cs' => 'Přidružené společnosti', 'not' => array( 'Partneři', 'Afiláty', 'Pobočné firmy' ) ),
	array( 'en' => 'Supplier portal', 'cs' => 'Portál pro dodavatele', 'not' => array( 'Dodavatelský portál', 'Portál dodavatele' ) ),
	array( 'en' => 'Trademarks', 'cs' => 'Ochranné známky', 'not' => array( 'Obchodní značky', 'Trademarky' ) ),
	array( 'en' => 'Accessibility Statement', 'cs' => 'Prohlášení o přístupnosti', 'not' => array( 'Prohlášení o dostupnosti', 'Přístupnostní prohlášení' ) ),
	array( 'en' => 'Terms', 'cs' => 'Podmínky', 'not' => array( 'Termíny', 'Podmínky užití termíny' ) ),
	array( 'en' => 'Privacy Policy', 'cs' => 'Zásady ochrany osobních údajů', 'not' => array( 'Politika soukromí', 'Zásady soukromí' ) ),
	array( 'en' => 'Unsubscribe', 'cs' => 'Odhlásit se z odběru', 'not' => array( 'Zrušit odběr odhlášením', 'Odhlásit odběr novinek' ) ),
	array( 'en' => 'Cookie settings', 'cs' => 'Nastavení cookies', 'not' => array( 'Nastavení sušenek', 'Cookie nastavení' ) ),
	array( 'en' => 'Support', 'cs' => 'Podpora', 'not' => array( 'Podporování', 'Podpůrná činnost' ) ),
	array( 'en' => 'Support Services', 'cs' => 'Služby podpory', 'not' => array( 'Servisní služby', 'Podpůrné služby servisu' ) ),
	array( 'en' => 'Service & Support Products', 'cs' => 'Produkty pro servis a podporu', 'not' => array( 'Produkty služeb a podpory', 'Výrobky servisu a podpory' ) ),
	array( 'en' => 'Training', 'cs' => 'Školení', 'not' => array( 'Trénink', 'Výcvik', 'Tréninky' ) ),
	array( 'en' => 'Training courses', 'cs' => 'Školicí kurzy', 'not' => array( 'Školící kurzy', 'Tréninkové kurzy', 'Vzdělávací tréninky' ) ),
	array( 'en' => 'Spare Parts Marketplace', 'cs' => 'Tržiště náhradních dílů', 'not' => array( 'Marketplace náhradních dílů', 'Trh s náhradními díly' ) ),
	array( 'en' => 'Become a support partner', 'cs' => 'Staňte se partnerem podpory', 'not' => array( 'Stát se partnerem podpory', 'Staň se podpůrným partnerem' ) ),
	array( 'en' => 'Need support now?', 'cs' => 'Potřebujete podporu ihned?', 'not' => array( 'Potřebujete podporu hned teď?', 'Potřebujete podporu teď?' ) ),
	array( 'en' => 'Submit a service request', 'cs' => 'Odešlete servisní požadavek', 'not' => array( 'Založte servisní požadavek', 'Podat servisní žádost', 'Odeslat servisní požadavek' ) ),
	array( 'en' => 'Attach files (optional)', 'cs' => 'Připojte soubory (volitelné)', 'not' => array( 'Přiložit soubory (nepovinné)', 'Připojení souborů volitelné' ) ),
	array( 'en' => 'Contact name', 'cs' => 'Kontaktní osoba', 'not' => array( 'Jméno kontaktu', 'Kontaktní jméno' ) ),
	array( 'en' => 'Contact email', 'cs' => 'E-mail kontaktní osoby', 'not' => array( 'E-mail kontaktu', 'Kontaktní email adresa' ) ),
	array( 'en' => 'Equipment model number or type', 'cs' => 'Číslo modelu nebo typ zařízení', 'not' => array( 'Číslo modelu zařízení nebo typ', 'Modelové číslo či typ vybavení' ) ),
	array( 'en' => 'Select your support team', 'cs' => 'Vyberte svůj tým podpory', 'not' => array( 'Vyberte váš tým podpory', 'Zvolte si podpůrný tým' ) ),
	array( 'en' => 'Select an option', 'cs' => 'Vyberte možnost', 'not' => array( 'Zvolte volbu', 'Vyberte si opci' ) ),
	array( 'en' => 'Country', 'cs' => 'Země', 'not' => array( 'Stát', 'Krajina' ) ),
	array( 'en' => 'Climate & energy', 'cs' => 'Klimatizace a energetika', 'not' => array( 'Klima a energie', 'Podnebí a energetika' ) ),
	array( 'en' => 'Transportation', 'cs' => 'Dopravní technika', 'not' => array( 'Doprava', 'Přeprava', 'Transport' ) ),
	array( 'en' => 'Metals automation & systems integrations', 'cs' => 'Automatizace zpracování kovů a integrace systémů', 'not' => array( 'Kovová automatizace a systémové integrace', 'Automatizace kovů a integrace' ) ),
	array( 'en' => 'Precision Machining', 'cs' => 'Přesné obrábění', 'not' => array( 'Precizní strojírenství', 'Přesné strojní obrábění' ) ),
	array( 'en' => 'Non-destructive testing', 'cs' => 'Nedestruktivní zkoušení (NDT)', 'not' => array( 'NDT testování', 'Nedestruktivní testování', 'NDT zkoušky' ) ),
	array( 'en' => 'Engineering consulting', 'cs' => 'Technické poradenství', 'not' => array( 'Poradenství v oblasti inženýrství', 'Inženýrské poradenství', 'Poradenství v oblasti techniky' ) ),
	array( 'en' => 'Engineering and OBD consulting', 'cs' => 'Technické a OBD poradenství', 'not' => array( 'Technické poradenství a poradenství OBD', 'Poradenství v oblasti techniky a OBD', 'OBD a technické konzultace' ) ),
	array( 'en' => 'OBD consulting and training', 'cs' => 'Poradenství a školení OBD', 'not' => array( 'Konzultace a trénink OBD', 'OBD poradenství a školení' ) ),
	array( 'en' => 'Roll shop', 'cs' => 'brusírna válců', 'not' => array( 'válcovna', 'dílna válců' ) ),
	array( 'en' => 'vapor compression cooling', 'cs' => 'kompresorové chlazení', 'not' => array( 'parní kompresní chlazení', 'chlazení parní kompresí' ) ),
	array( 'en' => 'air handling unit', 'cs' => 'vzduchotechnická jednotka (VZT)', 'not' => array( 'jednotka pro manipulaci se vzduchem', 'vzduchová manipulační jednotka' ) ),
	array( 'en' => 'turbocharger', 'cs' => 'turbodmychadlo', 'not' => array( 'turbokompresor', 'turbo nabíječ', 'přeplňovač turbo' ) ),
	array( 'en' => 'machine health', 'cs' => 'technický stav stroje', 'not' => array( 'zdravotní stav stroje', 'zdraví stroje' ) ),
	array( 'en' => 'asset serial number', 'cs' => 'sériové číslo zařízení', 'not' => array( 'sériové číslo majetku', 'výrobní číslo aktiva' ) ),
	array( 'en' => 'aftermarket', 'cs' => 'aftermarket', 'not' => array( 'náhradní díly trh', 'poprodejní trh', 'sekundární trh' ) ),
	array( 'en' => 'Balancing as-a-service (BaaS)', 'cs' => 'Vyvažování jako služba (BaaS)', 'not' => array( 'Vyvažování jako servis', 'BaaS vyvažovací služba' ) ),
	array( 'en' => 'Contract balancing as-a-service (BaaS)', 'cs' => 'Smluvní vyvažování jako služba (BaaS)', 'not' => array( 'Vyvažování na zakázku jako služba', 'Kontraktní vyvažování jako služba' ) ),
	array( 'en' => 'The Americas', 'cs' => 'Severní a Jižní Amerika', 'not' => array( 'Ameriky', 'v Amerikách', 'Amerikách' ) ),
	array( 'en' => 'Senior Vice President', 'cs' => 'senior viceprezident', 'not' => array( 'vedoucí viceprezident', 'starší viceprezident', 'seniorský viceprezident' ) ),
	array( 'en' => 'Executive Vice President', 'cs' => 'výkonný viceprezident', 'not' => array( 'exekutivní viceprezident', 'vedoucí výkonný viceprezident' ) ),
	array( 'en' => 'Chief Technology Officer', 'cs' => 'technický ředitel', 'not' => array( 'hlavní technologický důstojník', 'šéf technologií' ) ),
	array( 'en' => 'General Manager', 'cs' => 'vedoucí pobočky', 'not' => array( 'generální manažer', 'hlavní manažer' ) ),
	array( 'en' => 'Vice President of Sales', 'cs' => 'viceprezident pro prodej', 'not' => array( 'viceprezident prodeje', 'viceprezident obchodu' ) ),
	array( 'en' => 'Hires <Name> as <Title>', 'cs' => 'přijímá <Name> do pozice <Title>', 'not' => array( 'najímá <Name> jako <Title>', 'zaměstnává <Name> na pozici' ) ),
	array( 'en' => 'Board of Directors', 'cs' => 'představenstvo', 'not' => array( 'rada ředitelů', 'správní rada ředitelů' ) ),
	array( 'en' => 'press release', 'cs' => 'tisková zpráva', 'not' => array( 'tiskové oznámení', 'zpráva pro tisk' ) ),
	array( 'en' => 'mission-critical', 'cs' => 'kriticky důležitý', 'not' => array( 'kritický', 'misijně kritický' ) ),
	array( 'en' => 'challenges', 'cs' => 'výzvy', 'not' => array( 'náročné úkoly výzvy', 'challenge výzvy' ) ),
	array( 'en' => 'initiatives', 'cs' => 'projekty', 'not' => array( 'iniciativy', 'podněty' ) ),
	array( 'en' => 'capabilities', 'cs' => 'možnosti', 'not' => array( 'kapacity', 'schopnostní kapacity' ) ),
	array( 'en' => 'business model', 'cs' => 'obchodní model', 'not' => array( 'model podnikání', 'podnikatelský model' ) ),
	array( 'en' => 'embedded inspection', 'cs' => 'integrovaná kontrola', 'not' => array( 'vestavěné kontroly', 'zabudovaná inspekce' ) ),
	array( 'en' => 'end of line', 'cs' => 'konec výrobní linky', 'not' => array( 'konec linky', 'konečná kontrola' ) ),
	array( 'en' => 'shortly', 'cs' => 'v nejbližší době', 'not' => array( 'během několika minut', 'do několika minut', 'brzy' ) ),
	array( 'en' => 'promptly', 'cs' => 'obratem', 'not' => array( 'brzy pohotově', 'rychle brzy' ) ),
	array( 'en' => 'truck', 'cs' => 'nákladní vozidlo', 'not' => array( 'nákladní sektor', 'kamionová doprava' ) ),
);
