<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * German term base (en -> de). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Source: PL100 root causes + live /de/ sampling 2026-09-25.
 */
return array(
	array( 'en' => '*', 'de' => 'The whole site addresses the reader with the formal Sie, in every slot: body copy, headings, eyebrows, ALL-CAPS bands, form labels, placeholders, alt and aria text, the <title>, the meta description, og: tags and JSON-LD. Sie, Ihr, Ihre, Ihnen are capitalised whenever they address the reader; a du or ihr form never appears anywhere, at any length, including short CTAs and metadata. All nouns are capitalised and compounds are written as one word or fully hyphenated through a proper name. BUTTONS AND LINK LABELS follow German web-UI convention: they keep the verb of the English and take the bare infinitive or a noun phrase, never a du-imperative and never a conjugated sentence: „Browse catalog“ is Katalog durchsuchen, „Download“ is Herunterladen, „Request a demo“ is Demo vereinbaren, „Read the article“ is Artikel lesen, „Log in to Ascentialytics“ is Bei Ascentialytics anmelden. Never flatten a verb label into a bare noun (Katalog, Download, Demo-Anfrage are wrong for those), and never put a possessive in a label (Schutzen Sie Ihre Investition is wrong; Investition schutzen is right). The single established Sie-imperative exception the site already uses sitewide is the contact CTA Kontaktieren Sie uns and Mit einem Experten sprechen. Everything that is not a control label — prose, headings, questions, metadata — addresses the reader only as Sie.', 'not' => array( 'Du', 'Dein', 'Deine', 'Deinen', 'Deinem', 'Deiner', 'Deines', 'dein', 'deine', 'deinen', 'deinem', 'deiner', 'dich', 'dir', 'Dich', 'Dir', 'euch', 'Euch', 'euer', 'Euer', 'eure', 'Eure', 'euren', 'eurem', 'eurer', 'hast', 'kannst', 'willst', 'musst', 'bist', 'brauchst', 'möchtest', 'weisst', 'weißt', 'habt', 'könnt', 'wollt', 'müsst', 'seid', 'wisst', 'Entdecke', 'Erfahre', 'Kontaktiere', 'Melde', 'Fordere', 'Klicke', 'Sieh', 'Buche', 'Vereinbare', 'Suche dir' ) ),
	array( 'en' => '20-high mill', 'de' => 'Zwanzigwalzen-Walzwerk', 'not' => array( '20er-Walzwerk', 'zwanzigseitiges Walzwerk' ) ),
	array( 'en' => 'six-high mill', 'de' => 'Sechswalzen-Walzwerk', 'not' => array( 'Sechser-Walzwerk', 'sechsseitiges Walzwerk' ) ),
	array( 'en' => '3-jaw chuck', 'de' => 'Dreibackenfutter', 'not' => array( 'Dreiklauenfutter', 'dreiteiliges Futter' ) ),
	array( 'en' => 'A DESIGN', 'de' => 'A DESIGN', 'not' => array( 'DESIGN A', 'ENTWURF A' ) ),
	array( 'en' => 'B LOGO', 'de' => 'B LOGO', 'not' => array( 'LOGO B', 'B-Zeichen' ) ),
	array( 'en' => 'active part probing', 'de' => 'aktive Werkstückmessung', 'not' => array( 'aktives Sondieren', 'aktive Teileabtastung' ) ),
	array( 'en' => 'actuation systems', 'de' => 'Aktuatoriksysteme', 'not' => array( 'Betätigungssysteme', 'Aktivierungssysteme' ) ),
	array( 'en' => 'adaptive speed control', 'de' => 'adaptive Drehzahlregelung', 'not' => array( 'adaptive Geschwindigkeitskontrolle', 'adaptive Geschwindigkeitsregelung' ) ),
	array( 'en' => 'advanced driver assistance systems (ADAS)', 'de' => 'Fahrerassistenzsysteme (ADAS)', 'not' => array( 'fortschrittliche Fahrerunterstützungssysteme', 'erweiterte Fahrerassistenzsysteme' ) ),
	array( 'en' => 'ADAS alignment', 'de' => 'ADAS-Kalibrierung', 'not' => array( 'ADAS-Ausrichtung', 'ADAS-Vermessung' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'de' => 'ADVANCING THE MACHINE', 'not' => array( 'DIE MASCHINE VORANBRINGEN', 'FORTSCHRITT DER MASCHINE' ) ),
	array( 'en' => 'air cycle machines', 'de' => 'Luftkältemaschinen', 'not' => array( 'Luftzyklusmaschinen', 'Luftkreislaufmaschinen' ) ),
	array( 'en' => 'anchoring', 'de' => 'Verankerung', 'not' => array( 'Ankerung' ) ),
	array( 'en' => 'aperture plate', 'de' => 'Blendenplatte', 'not' => array( 'Öffnungsplatte', 'Aperturplatte' ) ),
	array( 'en' => 'applications', 'de' => 'Anwendungen', 'not' => array( 'Applikationen', 'Einsatzapplikationen' ) ),
	array( 'en' => 'armature', 'de' => 'Anker', 'not' => array( 'Armatur' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'de' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDIZIN & LEBENSWISSENSCHAFTEN', 'ASCENTIAL MEDIZINTECHNIK & LIFE SCIENCES' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'de' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Prüf- und Messtechnik', 'Ascential Test- und Messtechnik' ) ),
	array( 'en' => 'Ask Burke Porter', 'de' => 'Ask Burke Porter', 'not' => array( 'Fragen Sie Burke Porter', 'Frag Burke Porter' ) ),
	array( 'en' => 'associate attorney', 'de' => 'angestellter Rechtsanwalt', 'not' => array( 'Rechtsanwaltsgehilfe', 'Anwaltsassistent' ) ),
	array( 'en' => 'audit stations', 'de' => 'Auditstationen', 'not' => array( 'Kontrollstationen', 'Revisionsstationen' ) ),
	array( 'en' => 'automated handling cells', 'de' => 'automatisierte Handhabungszellen', 'not' => array( 'automatisierte Umschlagzellen', 'Handlingzellen' ) ),
	array( 'en' => 'backhoe', 'de' => 'Baggerlader', 'not' => array( 'Heckbagger', 'Baggerlastwagen' ) ),
	array( 'en' => 'baler', 'de' => 'Ballenpresse', 'not' => array( 'Presswerk', 'Ballenmaschine' ) ),
	array( 'en' => 'round baler', 'de' => 'Rundballenpresse', 'not' => array(  ) ),
	array( 'en' => 'square baler', 'de' => 'Quaderballenpresse', 'not' => array( 'Quadratballenpresse', 'quadratische Ballenpresse' ) ),
	array( 'en' => 'bead breaking', 'de' => 'Wulstabdrücken', 'not' => array( 'Perlenbrechen', 'Reifenwulstbruch' ) ),
	array( 'en' => 'bearers', 'de' => 'Lagerböcke', 'not' => array( 'Träger', 'Auflagebänder', 'Auflagerollen', 'Auflager', 'Auflagerrollen' ) ),
	array( 'en' => 'bearing center lines', 'de' => 'Lagermittellinien', 'not' => array( 'Lagerzentrierlinien', 'Zapfenachsen' ) ),
	array( 'en' => 'bearing life', 'de' => 'Lagerlebensdauer', 'not' => array( 'Lagerlaufzeit' ) ),
	array( 'en' => 'blade', 'de' => 'Schaufel', 'not' => array( 'Klinge', 'Messerbalken', 'Schar' ) ),
	array( 'en' => 'blank ECM', 'de' => 'unprogrammiertes ECM', 'not' => array( 'leeres ECM', 'blankes ECM' ) ),
	array( 'en' => 'blast furnace', 'de' => 'Hochofen', 'not' => array( 'Schmelzofen', 'Gebläseofen' ) ),
	array( 'en' => 'blowers', 'de' => 'Gebläse', 'not' => array(  ) ),
	array( 'en' => 'fan', 'de' => 'Lüfter', 'not' => array( 'Windrad', 'Flügelrad' ) ),
	array( 'en' => 'bore axis alignment', 'de' => 'Bohrachsenausrichtung', 'not' => array( 'Bohrungsachsen-Justage' ) ),
	array( 'en' => 'boreless compressor wheel', 'de' => 'Verdichterrad ohne Zentralbohrung', 'not' => array( 'borelloses Verdichterrad', 'borellose Verdichterlaufräder' ) ),
	array( 'en' => 'boring', 'de' => 'Ausdrehen', 'not' => array(  ) ),
	array( 'en' => 'boring drill', 'de' => 'Horizontalbohrgerät', 'not' => array( 'Bohrbohrer', 'Bohrmaschine' ) ),
	array( 'en' => 'branch', 'de' => 'Bereich', 'not' => array( 'Filiale', 'Zweigstelle' ) ),
	array( 'en' => 'Bristol', 'de' => 'Bristol', 'not' => array(  ) ),
	array( 'en' => 'built to last', 'de' => 'auf Langlebigkeit ausgelegt', 'not' => array( 'gebaut um zu halten', 'für die Ewigkeit gebaut' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'de' => 'Burke E. Porter Machinery', 'not' => array( 'Burke E. Porter Maschinenbau', 'Burke Porter Maschinen' ) ),
	array( 'en' => 'Burke Porter Group', 'de' => 'Burke Porter Group', 'not' => array( 'Burke-Porter-Gruppe', 'Gruppe Burke Porter' ) ),
	array( 'en' => 'burst proof protection', 'de' => 'Berstschutz', 'not' => array( 'Druckentlastungsschutz', 'Explosionsschutz', 'berstsicherer Schutz' ) ),
	array( 'en' => 'calibration target', 'de' => 'Kalibriertafel', 'not' => array( 'Kalibrierungsziel', 'Zieltafelhalter' ) ),
	array( 'en' => 'Calibration-as-a-Service™', 'de' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Kalibrierung als Service™', 'Kalibrierung-als-Dienstleistung™' ) ),
	array( 'en' => 'capital equipment', 'de' => 'Investitionsgüter', 'not' => array( 'Kapitalausrüstung', 'Kapitalgüterausrüstung' ) ),
	array( 'en' => 'cargo loading systems', 'de' => 'Frachtladesysteme', 'not' => array( 'Ladungssysteme', 'Cargo-Lade-Systeme' ) ),
	array( 'en' => 'chassis dynamometer', 'de' => 'Rollenprüfstand', 'not' => array( 'Fahrwerksprüfstand', 'Fahrwerks-Leistungsprüfstand', 'Chassis-Dynamometer' ) ),
	array( 'en' => 'chip vacuum', 'de' => 'Spanabsaugung', 'not' => array( 'Späne-Staubsauger', 'Chipsauger' ) ),
	array( 'en' => 'clay gun', 'de' => 'Stichlochstopfmaschine', 'not' => array( 'Tonerdichtung', 'Tonpistole', 'Maschine zum Formen von Lehm' ) ),
	array( 'en' => 'CMT-TR Polimer', 'de' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR Polymer', 'Polymer-Rotor-Auswuchtmaschine' ) ),
	array( 'en' => 'cold pilger mill', 'de' => 'Kaltpilgerwalzwerk', 'not' => array( 'Kaltpilgermühle', 'kalte Pilgerwalze' ) ),
	array( 'en' => 'collet chuck', 'de' => 'Spannzangenfutter', 'not' => array( 'Klemmfutter', 'Kollettfutter' ) ),
	array( 'en' => 'combine', 'de' => 'Mähdrescher', 'not' => array( 'Kombinierer', 'Erntekombination' ) ),
	array( 'en' => 'commercial vehicle', 'de' => 'Nutzfahrzeug', 'not' => array( 'Handelsfahrzeug', 'Geschäftsfahrzeug' ) ),
	array( 'en' => 'commissioning', 'de' => 'Inbetriebnahme', 'not' => array( 'Kommissionierung', 'Beauftragung' ) ),
	array( 'en' => 'Connect on LinkedIn', 'de' => 'Auf LinkedIn vernetzen', 'not' => array( 'Connect on LinkedIn', 'Verbinden auf LinkedIn' ) ),
	array( 'en' => 'control', 'de' => 'Steuerung', 'not' => array( 'Kontrolle' ) ),
	array( 'en' => 'control module', 'de' => 'Steuergerät', 'not' => array( 'Kontrollmodul', 'Regelbaustein', 'Steuermodul', 'Steuerungsmodul' ) ),
	array( 'en' => 'controls', 'de' => 'Steuerungstechnik', 'not' => array( 'Kontrollen', 'Kontrollsysteme' ) ),
	array( 'en' => 'Core / Plus / Elite', 'de' => 'Core / Plus / Elite', 'not' => array( 'Basis, Plus, Elite', 'Standard, Plus, Elite' ) ),
	array( 'en' => 'Corporate Roles', 'de' => 'Unternehmensfunktionen', 'not' => array( 'Konzernrollen', 'Firmenrollen' ) ),
	array( 'en' => 'correction', 'de' => 'Ausgleich', 'not' => array( 'Berichtigung', 'Korrektur', 'Massenkorrektur' ) ),
	array( 'en' => 'correction point', 'de' => 'Ausgleichsstelle', 'not' => array( 'Korrektionspunkt', 'Korrekturpunkt', 'Korrekturstelle' ) ),
	array( 'en' => 'crankshaft lathe', 'de' => 'Kurbelwellendrehmaschine', 'not' => array( 'Pleueldrehmaschine' ) ),
	array( 'en' => 'Kamer van Koophandel (KvK)', 'de' => 'Handelskammer (KvK)', 'not' => array( 'Handelsregisterkammer', 'Industrie- und Handelskammer (KvK)' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'de' => 'Kruispuntbank van Ondernemingen', 'not' => array( 'Zentrale Unternehmensdatenbank', 'Unternehmensregister' ) ),
	array( 'en' => 'cushion testing', 'de' => 'Endlagendämpfungsprüfung', 'not' => array( 'Kissenprüfung', 'Polsterprüfung' ) ),
	array( 'en' => 'custom fixturing', 'de' => 'kundenspezifische Spannvorrichtungen', 'not' => array( 'Sonderbefestigungen', 'maßgeschneiderte Fixierung' ) ),
	array( 'en' => 'customer journey', 'de' => 'Customer Journey', 'not' => array( 'Kundenreise', 'Reise des Kunden', 'Stufen ihrer Reise' ) ),
	array( 'en' => 'Date:', 'de' => 'Datum:', 'not' => array( 'Daten:', 'Termin:' ) ),
	array( 'en' => 'deep hole drilling', 'de' => 'Tiefbohren', 'not' => array(  ) ),
	array( 'en' => 'defensible', 'de' => 'auditsicher', 'not' => array( 'verteidigungsfähig', 'vertretbar' ) ),
	array( 'en' => 'Deliverables', 'de' => 'Liefergegenstände', 'not' => array( 'Lieferbare', 'Lieferbares', 'Deliverables' ) ),
	array( 'en' => 'deployment', 'de' => 'Einführung', 'not' => array( 'Entfaltung', 'Truppenverlegung' ) ),
	array( 'en' => 'design', 'de' => 'Konstruktion', 'not' => array( 'Entwurf' ) ),
	array( 'en' => 'dial indicator', 'de' => 'Messuhr', 'not' => array( 'Zifferblattanzeiger', 'Skalenanzeiger' ) ),
	array( 'en' => 'disability insurance', 'de' => 'Berufsunfähigkeitsversicherung', 'not' => array( 'Invalidenrente', 'Behindertenversicherung' ) ),
	array( 'en' => 'discrete industries', 'de' => 'diskrete Fertigungsbranchen', 'not' => array( 'diskrete Industrien', 'einzelne Branchen' ) ),
	array( 'en' => 'draper header', 'de' => 'Bandschneidwerk', 'not' => array( 'Drapierschneidwerk', 'Vorhangschneidwerk' ) ),
	array( 'en' => 'drift', 'de' => 'Drift', 'not' => array( 'Abdrift', 'Driften', 'Absinken' ) ),
	array( 'en' => 'drivability', 'de' => 'Fahrbarkeit', 'not' => array( 'Lenkbarkeit', 'Fahrtüchtigkeit' ) ),
	array( 'en' => 'dual mass flywheel', 'de' => 'Zweimassenschwungrad', 'not' => array( 'Doppelmassenschwungrad', 'Zweimassenkupplung' ) ),
	array( 'en' => 'dynamometer', 'de' => 'Leistungsprüfstand', 'not' => array( 'Dynamometer', 'Kraftmesser' ) ),
	array( 'en' => 'eddy current technology', 'de' => 'Wirbelstromtechnik', 'not' => array( 'Strudelstromtechnik', 'aktuelle Technologie' ) ),
	array( 'en' => 'electrical discharge texturing', 'de' => 'Funkenerosions-Texturierung (EDT)', 'not' => array( 'elektrische Entladungstexturierung', 'EDT-Aufrauung' ) ),
	array( 'en' => 'Email Disclosure', 'de' => 'E-Mail-Haftungsausschluss', 'not' => array( 'E-Mail-Offenlegung', 'E-Mail-Bekanntgabe' ) ),
	array( 'en' => 'EMC darkroom', 'de' => 'EMV-Absorberhalle', 'not' => array( 'EMV-Dunkelkammer', 'EMC-Dunkelraum' ) ),
	array( 'en' => 'end of line testing', 'de' => 'End-of-Line-Prüfung', 'not' => array( 'Endlinienprüfung', 'Prüfung am Bandende' ) ),
	array( 'en' => 'energy recuperation', 'de' => 'Energierückgewinnung', 'not' => array( 'Energierekuperation', 'Energieregeneration' ) ),
	array( 'en' => 'engine software loaders', 'de' => 'Programmiergeräte für Motorsoftware', 'not' => array( 'Motorsoftware-Lader', 'Motorenlader' ) ),
	array( 'en' => 'eRotor', 'de' => 'E-Motor-Rotor', 'not' => array( 'E-Rotor', 'Elektrorotor', 'eRotor', 'Automotive-eRotor' ) ),
	array( 'en' => 'events & conferences', 'de' => 'Veranstaltungen & Konferenzen', 'not' => array( 'Ereignisse und Konferenzen', 'Events und Tagungen' ) ),
	array( 'en' => 'excavator', 'de' => 'Bagger', 'not' => array( 'Aushubmaschine', 'Ausgräber' ) ),
	array( 'en' => 'exhaust extraction', 'de' => 'Abgasabsaugung', 'not' => array( 'Abgasextraktion', 'Auspuffabsaugung' ) ),
	array( 'en' => 'factory floor', 'de' => 'Produktionshalle', 'not' => array( 'Fabrikboden', 'Fabrikfußboden' ) ),
	array( 'en' => 'failure rates', 'de' => 'Fehlerquoten', 'not' => array( 'Versagensquoten', 'Misserfolgsraten' ) ),
	array( 'en' => 'features', 'de' => 'Leistungsmerkmale', 'not' => array( 'Features', 'Funktionalitäten', 'Funktionen' ) ),
	array( 'en' => 'Featuring:', 'de' => 'Im Fokus:', 'not' => array( 'Featuring:', 'Mit dabei:' ) ),
	array( 'en' => 'field agents', 'de' => 'Außendiensttechniker', 'not' => array( 'Feldagenten', 'Vertreter' ) ),
	array( 'en' => 'field balancing', 'de' => 'Auswuchten am Einbauort', 'not' => array( 'Feldauswuchten', 'Auswuchten im Feld' ) ),
	array( 'en' => 'filler', 'de' => 'Füllstation', 'not' => array( 'Abfüller' ) ),
	array( 'en' => 'filler gun', 'de' => 'Füllpistole', 'not' => array( 'Füllerpistole', 'Dosierpistölchen' ) ),
	array( 'en' => 'final discharge', 'de' => 'Endentleerung', 'not' => array( 'Endabgabe', 'endgültige Entladung' ) ),
	array( 'en' => 'fine leak', 'de' => 'Feinleck', 'not' => array( 'feine Leckage', 'Feinundichtigkeit' ) ),
	array( 'en' => 'flexplate', 'de' => 'Mitnehmerscheibe', 'not' => array( 'Flexplatte', 'Flexscheibe' ) ),
	array( 'en' => 'fluid power', 'de' => 'Fluidtechnik', 'not' => array( 'Flüssigkeitskraft', 'Fluidkraft' ) ),
	array( 'en' => 'flywheel', 'de' => 'Schwungrad', 'not' => array( 'Schwungscheibe', 'Trägheitsrad' ) ),
	array( 'en' => 'footprint', 'de' => 'Stellfläche', 'not' => array( 'Fußabdruck', 'Platzbedarfsgröße' ) ),
	array( 'en' => 'For Immediate Release', 'de' => 'Zur sofortigen Veröffentlichung', 'not' => array( 'Für sofortige Freigabe', 'Zur sofortigen Freigabe' ) ),
	array( 'en' => 'forged rolls', 'de' => 'geschmiedete Walzen', 'not' => array( 'gegossene Walzen', 'Schmiedewalzen' ) ),
	array( 'en' => 'front strut', 'de' => 'Federbein', 'not' => array( 'Frontstrebe', 'vorderer Pfosten', 'vorderer Bremssattel' ) ),
	array( 'en' => 'gantry', 'de' => 'Portal', 'not' => array( 'Galgen', 'Brückengerüst' ) ),
	array( 'en' => 'gantry milling', 'de' => 'Portalfräsen', 'not' => array( 'Brückenfräsen', 'Torfräsen' ) ),
	array( 'en' => 'GDPR', 'de' => 'DSGVO', 'not' => array( 'GDPR', 'EU-Datenschutzgesetz' ) ),
	array( 'en' => 'gear shift calibration', 'de' => 'Schaltkalibrierung', 'not' => array( 'Getriebeverschiebungskalibrierung', 'Gangwechsel-Kalibration' ) ),
	array( 'en' => 'grinding wheel', 'de' => 'Schleifscheibe', 'not' => array( 'Mahlscheibe', 'Schleifrad' ) ),
	array( 'en' => 'gross leak test', 'de' => 'Grobleckprüfung', 'not' => array( 'Bruttoleckprüfung', 'Grobleckagetest' ) ),
	array( 'en' => 'gundrill', 'de' => 'Einlippenbohrer', 'not' => array( 'Gundrill', 'Gewehrbohrer' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'de' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Co. AG', 'H. Kleinknecht & Co. KG' ) ),
	array( 'en' => 'half case', 'de' => 'Halbgehäuse', 'not' => array( 'Halbschale', 'halber Fall' ) ),
	array( 'en' => 'hay mower', 'de' => 'Heumähwerk', 'not' => array( 'Heuschneider' ) ),
	array( 'en' => 'hazardous area', 'de' => 'explosionsgefährdeter Bereich', 'not' => array( 'Gefahrenbereich', 'gefährlicher Bereich' ) ),
	array( 'en' => 'health checks', 'de' => 'Zustandsprüfungen', 'not' => array( 'Gesundheitschecks', 'Gesundheitsprüfungen' ) ),
	array( 'en' => 'high production', 'de' => 'Großserienproduktion', 'not' => array( 'Hochproduktion', 'hohe Produktion' ) ),
	array( 'en' => 'high-volume production', 'de' => 'Großserienproduktion', 'not' => array( 'Hochvolumen-Fertigung', 'Großmengenproduktion', 'Hochvolumenproduktion' ) ),
	array( 'en' => 'high-mix, low-volume', 'de' => 'variantenreiche Kleinserienfertigung', 'not' => array( 'hoher Mix, geringes Volumen', 'Hochmix-Niedrigvolumen' ) ),
	array( 'en' => 'high-performance teams', 'de' => 'leistungsstarke Teams', 'not' => array( 'Teams mit hoher Leistung', 'Hochleistungsmannschaften' ) ),
	array( 'en' => 'higher-level control system', 'de' => 'übergeordnetes Steuerungssystem', 'not' => array( 'höheres Kontrollsystem', 'Leitsystem höherer Ebene' ) ),
	array( 'en' => 'HMU/FMU', 'de' => 'HMU/FMU', 'not' => array( 'hydraulische und pneumatische Geräte', 'Kraftstoffdosiereinheiten' ) ),
	array( 'en' => 'idle duration', 'de' => 'Leerlaufdauer', 'not' => array( 'Stillstandsdauer', 'Untätigkeitsdauer' ) ),
	array( 'en' => 'implements', 'de' => 'Anbaugeräte', 'not' => array( 'Implemente', 'Gerätschaften', 'Mobilgeräte' ) ),
	array( 'en' => 'mobile equipment', 'de' => 'mobile Arbeitsmaschinen', 'not' => array( 'Mobilgeräte', 'Mobilausrüstung' ) ),
	array( 'en' => 'Imprint', 'de' => 'Impressum', 'not' => array( 'Aufdruck', 'Prägung' ) ),
	array( 'en' => 'in a single clamping', 'de' => 'in einer Aufspannung', 'not' => array( 'in einer Klemmung', 'in einem Spannvorgang' ) ),
	array( 'en' => 'infeed', 'de' => 'Zustellung', 'not' => array( 'Einzug', 'Infeed', 'Vorschub' ) ),
	array( 'en' => 'infinitely variable', 'de' => 'stufenlos verstellbar', 'not' => array( 'unendlich variabel', 'endlos regelbar' ) ),
	array( 'en' => 'inline crankshaft', 'de' => 'Reihenkurbelwelle', 'not' => array( 'Inline-Kurbelwelle', 'Viertakt-Kurbelwelle' ) ),
	array( 'en' => 'inline dyno', 'de' => 'Inline-Leistungsprüfstand', 'not' => array( 'eingebauter Leistungsprüfstand', 'Reihenprüfstand' ) ),
	array( 'en' => 'insights', 'de' => 'Erkenntnisse', 'not' => array( 'Einblicke', 'Einsichten' ) ),
	array( 'en' => 'actionable insights', 'de' => 'verwertbare Erkenntnisse', 'not' => array( 'umsetzbare Einblicke', 'handlungsfähige Erkenntnisse' ) ),
	array( 'en' => 'expert insights', 'de' => 'Experteneinschätzungen', 'not' => array( 'Experteneinblicke', 'fachliche Einblicke' ) ),
	array( 'en' => 'instrument cluster', 'de' => 'Kombiinstrument', 'not' => array( 'Instrumentencluster', 'Armaturenbrett' ) ),
	array( 'en' => 'keg', 'de' => 'Fass', 'not' => array( 'Fässchen', 'Bierfaß' ) ),
	array( 'en' => 'keg finger holes', 'de' => 'Grifflöcher', 'not' => array( 'Fingerlöcher', 'Fasslöcher' ) ),
	array( 'en' => 'kinetostatics', 'de' => 'Kinetostatik', 'not' => array( 'Kinematik' ) ),
	array( 'en' => 'Labour & Travel', 'de' => 'Arbeitszeit & Reisekosten', 'not' => array( 'Arbeit und Reisen', 'Lohn und Fahrt' ) ),
	array( 'en' => 'landed cost model', 'de' => 'Landed-Cost-Modell', 'not' => array( 'Modell der gelandeten Kosten', 'Anlieferkostenmodell' ) ),
	array( 'en' => 'landing gear systems', 'de' => 'Fahrwerksysteme', 'not' => array( 'Landegestellsysteme', 'Landefahrwerksysteme' ) ),
	array( 'en' => 'leak detection', 'de' => 'Lecksuche', 'not' => array( 'Leckerkennung', 'Leckageerkennung', 'Leckagetestverfahren' ) ),
	array( 'en' => 'learning management system (LMS)', 'de' => 'Lernmanagementsystem (LMS)', 'not' => array( 'Lernverwaltungssystem', 'Lehrverwaltungssystem' ) ),
	array( 'en' => 'like-minded companies', 'de' => 'gleichgesinnte Unternehmen', 'not' => array( 'ähnlich denkende Firmen', 'Firmen mit ähnlichen Ansichten' ) ),
	array( 'en' => 'load capacity', 'de' => 'Tragfähigkeit', 'not' => array( 'Ladekapazität', 'Belastungskapazität' ) ),
	array( 'en' => 'LPM', 'de' => 'l/min', 'not' => array(  ) ),
	array( 'en' => 'lube & scavenge pumps', 'de' => 'Schmier- und Absaugpumpen', 'not' => array( 'Schmier- und Entlüftungspumpen', 'Spülpumpen' ) ),
	array( 'en' => 'lubrication', 'de' => 'Schmierung', 'not' => array( 'Ölwechsel', 'Einölung' ) ),
	array( 'en' => 'machine tools', 'de' => 'Werkzeugmaschinen', 'not' => array( 'Maschinenwerkzeuge', 'Bearbeitungsmaschinen' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'de' => 'Maschinenrichtlinie 2006/42/EG', 'not' => array( 'Maschinendirektive 2006/42/EG' ) ),
	array( 'en' => 'machining cell', 'de' => 'Bearbeitungszelle', 'not' => array( 'Maschinenzelle', 'Zerspanzelle' ) ),
	array( 'en' => 'machinist', 'de' => 'Zerspanungsmechaniker', 'not' => array( 'Maschinist', 'Maschinenführer' ) ),
	array( 'en' => 'maintenance contracts', 'de' => 'Wartungsverträge', 'not' => array( 'Instandhaltungskontrakte', 'Pflegeverträge' ) ),
	array( 'en' => 'marine', 'de' => 'Schifffahrt', 'not' => array( 'Marine', 'Meeresindustrie' ) ),
	array( 'en' => 'maximum rotor diameter', 'de' => 'maximaler Rotordurchmesser', 'not' => array( 'maximale Rotorgröße', 'größter Rotordurchmesser' ) ),
	array( 'en' => 'mental health care', 'de' => 'psychische Gesundheitsversorgung', 'not' => array( 'geistige Gesundheitspflege', 'Fernbetreuung' ) ),
	array( 'en' => 'mill roll', 'de' => 'Walze', 'not' => array( 'Mühlenwalze' ) ),
	array( 'en' => 'misalignment', 'de' => 'Fehlausrichtung', 'not' => array( 'Missausrichtung', 'Ausrichtungsmangel' ) ),
	array( 'en' => 'motor grader', 'de' => 'Motorgrader', 'not' => array( 'Straßenhobel', 'Bodenkopierer' ) ),
	array( 'en' => 'motorized clamping', 'de' => 'motorisches Spannen', 'not' => array( 'motorisierte Klemmung', 'Motorspannung' ) ),
	array( 'en' => 'MRO', 'de' => 'MRO', 'not' => array(  ) ),
	array( 'en' => 'mudding system', 'de' => 'Bohrspülungssystem', 'not' => array( 'Schlammsystem', 'Matschsystem' ) ),
	array( 'en' => 'naamloze vennootschap', 'de' => 'naamloze vennootschap', 'not' => array( 'Aktiengesellschaft', 'niederländische AG' ) ),
	array( 'en' => 'Name:', 'de' => 'Name:', 'not' => array(  ) ),
	array( 'en' => 'Netherlands', 'de' => 'Niederlande', 'not' => array( 'Holland' ) ),
	array( 'en' => 'non-rotating balancing machine', 'de' => 'nicht rotierende Auswuchtmaschine', 'not' => array( 'Auswuchtmaschine ohne Rotor', 'rotationsfreie Auswuchtmaschine', 'Auswuchtmaschine ohne Rotation' ) ),
	array( 'en' => 'Non-Rotate Systems', 'de' => 'Nicht rotierende Systeme', 'not' => array( 'Nicht-Rotier-Systeme', 'Rotationsfreie Systeme', 'Nicht-Rotations-Systeme' ) ),
	array( 'en' => 'obsolescence management', 'de' => 'Obsoleszenzmanagement', 'not' => array( 'Veralterungsmanagement', 'Überalterungsmanagement' ) ),
	array( 'en' => 'off-highway', 'de' => 'Off-Highway', 'not' => array( 'Straßenverkehr', 'Geländeeinsatz' ) ),
	array( 'en' => 'oil drain', 'de' => 'Ölablass', 'not' => array( 'Entlüftungsöffnung', 'Ölabfluss' ) ),
	array( 'en' => 'operations', 'de' => 'Betriebsabläufe', 'not' => array( 'Operationen' ) ),
	array( 'en' => 'opportunities', 'de' => 'Chancen', 'not' => array( 'Opportunitäten', 'Gelegenheiten' ) ),
	array( 'en' => 'patented', 'de' => 'patentiert', 'not' => array( 'zum Patent angemeldet', 'patentwirksam' ) ),
	array( 'en' => 'pedestals', 'de' => 'Lagerböcke', 'not' => array( 'Podeste', 'Sockel' ) ),
	array( 'en' => 'peers', 'de' => 'Fachkollegen', 'not' => array( 'Gleichaltrige', 'Ebenbürtige' ) ),
	array( 'en' => 'performance', 'de' => 'Leistung', 'not' => array( 'Performanz', 'Durchführung' ) ),
	array( 'en' => 'personal information', 'de' => 'personenbezogene Daten', 'not' => array( 'persönliche Informationen', 'persönliche Daten' ) ),
	array( 'en' => 'personal data', 'de' => 'personenbezogene Daten', 'not' => array( 'persönliche Daten', 'Personendaten' ) ),
	array( 'en' => 'pinches & bruises', 'de' => 'Quetschungen & Druckstellen', 'not' => array( 'Kneifen und Blutergüsse', 'Prellungen und Quetschungen' ) ),
	array( 'en' => 'pinion gear', 'de' => 'Ritzel', 'not' => array( 'Zapfen', 'Stirnrad' ) ),
	array( 'en' => 'pins', 'de' => 'Stifte', 'not' => array( 'Zapfen', 'Nadeln' ) ),
	array( 'en' => 'power drive units', 'de' => 'Antriebseinheiten (PDU)', 'not' => array( 'Kraftantriebseinheiten', 'Leistungsantriebe' ) ),
	array( 'en' => 'Powered by', 'de' => 'Auf Basis von', 'not' => array( 'Angetrieben von', 'Angetrieben durch', 'Bereitgestellt von' ) ),
	array( 'en' => 'President', 'de' => 'President', 'not' => array( 'Präsident', 'Vorsitzender' ) ),
	array( 'en' => 'Board of Directors', 'de' => 'Board of Directors', 'not' => array( 'Vorstand', 'Verwaltungsrat' ) ),
	array( 'en' => 'Board Member', 'de' => 'Mitglied des Board of Directors', 'not' => array( 'Vorstandsmitglied', 'Aufsichtsratsmitglied' ) ),
	array( 'en' => 'Principal', 'de' => 'Principal', 'not' => array( 'Prinzipal', 'Hauptverantwortlicher' ) ),
	array( 'en' => 'Leadership', 'de' => 'Führungsteam', 'not' => array( 'Leiterschaft', 'Oberste Führungsebene' ) ),
	array( 'en' => 'pressurization', 'de' => 'Druckbeaufschlagung', 'not' => array( 'Pressurisierung', 'Druckbelüftung' ) ),
	array( 'en' => 'probe', 'de' => 'Prüfkopf', 'not' => array( 'Sonde', 'Messfühler', 'Probe' ) ),
	array( 'en' => 'probe alignment', 'de' => 'Prüfkopfausrichtung', 'not' => array( 'Sondenausrichtung', 'Sondenjustierung' ) ),
	array( 'en' => 'process recipe', 'de' => 'Prozessrezept', 'not' => array( 'Verfahrensrezeptur', 'Kochrezept' ) ),
	array( 'en' => 'propulsion & powertrain', 'de' => 'Antrieb & Antriebsstrang', 'not' => array( 'Antrieb und Antrieb', 'Vortrieb und Antriebsstrang' ) ),
	array( 'en' => 'power take-off', 'de' => 'Zapfwelle (PTO)', 'not' => array( 'Kraftabnahme', 'Leistungsabnahmewelle' ) ),
	array( 'en' => 'pulley', 'de' => 'Riemenscheibe', 'not' => array( 'Flaschenzug', 'Keilriemen' ) ),
	array( 'en' => 'pump impeller', 'de' => 'Pumpenlaufrad', 'not' => array( 'Pumpenrad', 'Pumpenläufer' ) ),
	array( 'en' => 'punching', 'de' => 'Stanzen', 'not' => array( 'Lochen', 'Durchstoßen' ) ),
	array( 'en' => 'push and pull', 'de' => 'Vorschub und Rückzug', 'not' => array( 'Druck und Zug', 'Schieben und Ziehen' ) ),
	array( 'en' => 'thrust force', 'de' => 'Vorschubkraft', 'not' => array( 'Axialkraft', 'Druckkraft' ) ),
	array( 'en' => 'pullback force', 'de' => 'Rückzugskraft', 'not' => array( 'Zurückziehkraft', 'Rückholkraft' ) ),
	array( 'en' => 'reconditioning', 'de' => 'Aufarbeitung', 'not' => array( 'Renovierung', 'Sanierung' ) ),
	array( 'en' => 'refrigerant', 'de' => 'Kältemittel', 'not' => array( 'Kühlmittel', 'Kühlflüssigkeit', 'Frostschutzmittel' ) ),
	array( 'en' => 'refrigerant charging', 'de' => 'Kältemittelbefüllung', 'not' => array( 'Kältemittelladung', 'Kältemittelbeladung', 'Kältemittelaufladung' ) ),
	array( 'en' => 'refrigeration', 'de' => 'Kältetechnik', 'not' => array( 'Kühlung', 'Refrigeration' ) ),
	array( 'en' => 'Register', 'de' => 'Register', 'not' => array( 'Jetzt registrieren', 'Registrieren' ) ),
	array( 'en' => 'Registered office', 'de' => 'Sitz der Gesellschaft', 'not' => array( 'Eingetragenes Büro', 'registriertes Büro' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'de' => 'Aufarbeitungs- und Instandsetzungsbetriebe', 'not' => array( 'Wiederhersteller und Umbauer', 'Remanufakturbetriebe' ) ),
	array( 'en' => 'remarketers', 'de' => 'Flottenvermarkter', 'not' => array( 'Remarketer', 'Wiederverkäufer' ) ),
	array( 'en' => 'reportable', 'de' => 'belegbar', 'not' => array( 'berichtbar', 'reportierbar' ) ),
	array( 'en' => 'represent', 'de' => 'abbilden', 'not' => array( 'repräsentieren', 'vertreten' ) ),
	array( 'en' => 'residual unbalance', 'de' => 'Restunwucht', 'not' => array( 'Restungleichgewicht', 'verbleibende Unwucht', 'Restunbalance' ) ),
	array( 'en' => 'responsive', 'de' => 'reaktionsschnell', 'not' => array( 'responsiv', 'ansprechbar' ) ),
	array( 'en' => 'restbus simulation', 'de' => 'Restbussimulation', 'not' => array( 'Rest-Bus-Simulation', 'Residualbussimulation' ) ),
	array( 'en' => 'retaining rollers', 'de' => 'Niederhalterollen', 'not' => array( 'Rückhaltewalzen', 'Retentionsrollen' ) ),
	array( 'en' => 'right-shoring', 'de' => 'Right-Shoring', 'not' => array( 'Richtiges Shoring', 'Standortoptimierung' ) ),
	array( 'en' => 'roll inspection', 'de' => 'Walzenprüfung', 'not' => array( 'Rollenprüfung', 'Rollenkontrolle' ) ),
	array( 'en' => 'Roll Shop Technologies', 'de' => 'Walzenschleiferei-Technologien', 'not' => array( 'Roll Shop Technologies', 'Walzwerkstatt-Technologien' ) ),
	array( 'en' => 'roll grinder', 'de' => 'Walzenschleifmaschine', 'not' => array( 'Altschleifen' ) ),
	array( 'en' => 'rollers', 'de' => 'Rollen', 'not' => array(  ) ),
	array( 'en' => 'roller brake tester', 'de' => 'Rollenbremsprüfstand', 'not' => array( 'Walzenbremsprüfstand', 'Rollenbremsentester' ) ),
	array( 'en' => 'rolling torque', 'de' => 'Rollmoment', 'not' => array( 'Walzmoment', 'Wellendrehmoment' ) ),
	array( 'en' => 'rotary diamond dressing', 'de' => 'Abrichten mit Diamantrolle', 'not' => array( 'Diamantdressieren', 'rotierendes Diamantdressing' ) ),
	array( 'en' => 'rotor wing aircraft', 'de' => 'Drehflügler', 'not' => array( 'Propellerflugzeuge', 'Rotorflügelflugzeuge' ) ),
	array( 'en' => 'sealed assembly', 'de' => 'dichte Baugruppe', 'not' => array( 'versiegelte Baugruppe', 'abgedichtete Montage' ) ),
	array( 'en' => 'seamless link', 'de' => 'nahtlose Verknüpfung', 'not' => array( 'unnahtbare Verbindung', 'direkter Verbinder' ) ),
	array( 'en' => 'service professional', 'de' => 'Servicespezialist', 'not' => array( 'Service-Fachmann', 'Serviceprofi' ) ),
	array( 'en' => 'setup cycles', 'de' => 'Einrichtzyklen', 'not' => array( 'Aufbauzyklen', 'Montagezyklen' ) ),
	array( 'en' => 'single bay', 'de' => 'Einzelplatz', 'not' => array( 'Einzelkammer', 'eine Bucht' ) ),
	array( 'en' => 'single cylinder crankshaft', 'de' => 'Einzylinder-Kurbelwelle', 'not' => array( 'Einspur-Kurbelwelle', 'Einspurwelle' ) ),
	array( 'en' => 'single station', 'de' => 'Einzelstation', 'not' => array( 'Einkammer', 'Einzelbucht' ) ),
	array( 'en' => 'multi station', 'de' => 'Mehrstationen', 'not' => array( 'Multistation', 'Mehrkammer' ) ),
	array( 'en' => 'site visit', 'de' => 'Vor-Ort-Besuch', 'not' => array( 'Baustellenbesuch', 'Geländebesuch' ) ),
	array( 'en' => 'sniffing pliers', 'de' => 'Schnüffelsonde', 'not' => array( 'Schnüffelzange', 'Riechzange' ) ),
	array( 'en' => 'sniffer', 'de' => 'Schnüffelsonde', 'not' => array( 'Sniffer', 'Riecher' ) ),
	array( 'en' => 'snubber', 'de' => 'Hydraulikdämpfer', 'not' => array( 'Schnubber', 'Drosselelement' ) ),
	array( 'en' => 'soak time', 'de' => 'Konditionierzeit', 'not' => array( 'Einweichzeit', 'Tränkzeit' ) ),
	array( 'en' => 'spalls', 'de' => 'Ausbrüche', 'not' => array( 'Abblätterungen', 'Spallierungen' ) ),
	array( 'en' => 'special test facilities', 'de' => 'Sonderprüfstände', 'not' => array( 'spezielle Testeinrichtungen', 'Spezialtestanlagen' ) ),
	array( 'en' => 'spin testing machine', 'de' => 'Schleuderprüfmaschine', 'not' => array( 'Spinnprüfmaschine', 'Drehprüfmaschine' ) ),
	array( 'en' => 'spin tester', 'de' => 'Schleuderprüfstand', 'not' => array( 'Spin-Tester', 'Spinnprüfstand' ) ),
	array( 'en' => 'Spin Testing', 'de' => 'Schleuderprüfung', 'not' => array( 'Spinnprüfung', 'Spin-Testing' ) ),
	array( 'en' => 'sprayers', 'de' => 'Feldspritzen', 'not' => array( 'Zerstäuber', 'Sprüher', 'Spritzpistolen' ) ),
	array( 'en' => 'squeak & rattle testing', 'de' => 'Knarz- und Klapperprüfung', 'not' => array( 'Quietsch- und Rassel-Test', 'Knirsch- und Rattertest' ) ),
	array( 'en' => 'stand-alone machine', 'de' => 'Einzelmaschine', 'not' => array( 'Stand-alone-Maschine', 'autarke Maschine' ) ),
	array( 'en' => 'Standardization at scale', 'de' => 'Standardisierung im großen Maßstab', 'not' => array( 'Standardisierung in Größe', 'Skalierte Normierung' ) ),
	array( 'en' => 'strip', 'de' => 'Band', 'not' => array( 'Blech', 'Streifen' ) ),
	array( 'en' => 'Strip Lines', 'de' => 'Bandanlagen', 'not' => array( 'Streifenlinien', 'Bandstreifenlinien', 'Bandlinien' ) ),
	array( 'en' => 'superabrasives', 'de' => 'Superhartstoffe', 'not' => array( 'Superabrasive', 'Superschleifmittel' ) ),
	array( 'en' => 'surface separations', 'de' => 'Oberflächenablösungen', 'not' => array( 'Oberflächentrennungen', 'Oberflächenabtrennungen' ) ),
	array( 'en' => 'subsurface defects', 'de' => 'Fehler unter der Oberfläche', 'not' => array( 'Subsurface-Fehler', 'oberflächennahe Fehler', 'unterflächige Fehler', 'Unterflächenfehler' ) ),
	array( 'en' => 'tap hole', 'de' => 'Stichloch', 'not' => array(  ) ),
	array( 'en' => 'tapered roller bearing', 'de' => 'Kegelrollenlager', 'not' => array( 'Zylinderrollenlager', 'konisches Rollenlager' ) ),
	array( 'en' => 'tariffs', 'de' => 'Zölle', 'not' => array( 'Tarife', 'Gebührenordnungen' ) ),
	array( 'en' => 'tension', 'de' => 'Zugkraft', 'not' => array( 'Verspannung', 'Spannkraftwert' ) ),
	array( 'en' => 'third member', 'de' => 'Achsmittelstück', 'not' => array( 'dritter Teil', 'drittes Glied' ) ),
	array( 'en' => 'tin plating', 'de' => 'Verzinnung', 'not' => array( 'Verzinkung', 'Zinnauftrag' ) ),
	array( 'en' => 'TIR / radial run-out', 'de' => 'Rundlaufabweichung (TIR)', 'not' => array( 'TIR-Lauf', 'radialer Auslauf' ) ),
	array( 'en' => 'tire inflator', 'de' => 'Reifenfüllstation', 'not' => array( 'Reifenpumpe', 'Reifenaufpumper' ) ),
	array( 'en' => 'torque vectoring', 'de' => 'Torque Vectoring', 'not' => array( 'Drehmomentvektorisierung', 'Momentenvektorisierung' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'de' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'GESAMTLÖSUNGEN FÜR DIE KOMMERZIALISIERUNG', 'KOMPLETTE VERMARKTUNGSLÖSUNGEN' ) ),
	array( 'en' => 'traceable tests', 'de' => 'rückführbare Prüfungen', 'not' => array( 'nachverfolgbare Tests', 'verfolgbare Prüfungen' ) ),
	array( 'en' => 'tracer gas', 'de' => 'Prüfgas', 'not' => array( 'Spurgas', 'Markergas' ) ),
	array( 'en' => 'traction battery', 'de' => 'Traktionsbatterie', 'not' => array( 'Zugbatterie', 'Antriebsakku' ) ),
	array( 'en' => 'transmission', 'de' => 'Getriebe', 'not' => array( 'Übertragung', 'Transmission' ) ),
	array( 'en' => 'gearbox', 'de' => 'Getriebe', 'not' => array( 'Schaltkasten' ) ),
	array( 'en' => 'turbo calibration', 'de' => 'Turbolader-Kalibrierung', 'not' => array( 'Turboauswuchten', 'Turbo-Abstimmung' ) ),
	array( 'en' => 'turbocharger flow bench', 'de' => 'Turbolader-Strömungsprüfstand', 'not' => array( 'Durchflussprüfanlage', 'Durchsatzprüfbank', 'Strömungsprüfbank', 'Durchsatzprüfstand' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'de' => 'Dynamischer Turbolader-Strömungsprüfstand', 'not' => array( 'Dynamische Turbolader-Durchflussprüfanlage' ) ),
	array( 'en' => 'turbocharger frame size', 'de' => 'Baugröße', 'not' => array( 'Rahmengröße', 'Gestellgröße' ) ),
	array( 'en' => 'core', 'de' => 'Turbolader-Rumpfgruppe', 'not' => array( 'Kernauswuchten', 'Kernauswuchtmaschine', 'Kernauswuchtmaschinen', 'Rotorkern', 'Rumpfgruppe (Core)', 'Turboladerkern', 'Rumpfgruppe' ) ),
	array( 'en' => 'core balancing', 'de' => 'Rumpfgruppenauswuchten', 'not' => array( 'Kernauswuchten', 'Kern-Auswuchten' ) ),
	array( 'en' => 'core balancing machine', 'de' => 'Auswuchtmaschine für Turbolader-Rumpfgruppen', 'not' => array( 'Kernauswuchtmaschine', 'Kernauswuchtmaschinen', 'Auswuchtmaschine für Rotorkerne', 'Auswuchtmaschine für Rumpfgruppen (Core)', 'Auswuchtmaschine für Rumpfgruppen' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'de' => 'Kombinierte Hochdrehzahl- und Niederdrehzahl-Auswuchtmaschine für Turbolader-Rumpfgruppen', 'not' => array( 'Kombinierte Hochgeschwindigkeits- und Niedergeschwindigkeits-Kernauswuchtmaschine', 'Kombinierte Hochgeschwindigkeits- und Niedergeschwindigkeits-Kernauswuchtmaschinen', 'Kombinierte Hochdrehzahl- und Niederdrehzahl-Auswuchtmaschine für Rumpfgruppen' ) ),
	array( 'en' => 'High-Speed', 'de' => 'Hochdrehzahl', 'not' => array( 'Hochgeschwindigkeit', 'Hochgeschwindigkeits' ) ),
	array( 'en' => 'Low-Speed', 'de' => 'Niederdrehzahl', 'not' => array( 'Niedergeschwindigkeit', 'Niedergeschwindigkeits' ) ),
	array( 'en' => 'turnkey', 'de' => 'schlüsselfertig', 'not' => array( 'Turnkey', 'turnkey-fertig' ) ),
	array( 'en' => 'turret-style wheel head', 'de' => 'Revolver-Schleifkopf', 'not' => array( 'Türmchen-Schleifkopf', 'Turm-Radkopf' ) ),
	array( 'en' => 'two-wheel drive', 'de' => 'Zweiradantrieb', 'not' => array( 'Zweiradfahrzeuge', 'Antrieb auf zwei Rädern' ) ),
	array( 'en' => 'ultra-stable design', 'de' => 'hochstabile Konstruktion', 'not' => array( 'ultrastabiles Design', 'extrem stabiler Entwurf' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'de' => 'Ultraschall-Düsenreiniger', 'not' => array( 'ultrasonischer Düsenputzer', 'Ultraschalldüsenwäscher' ) ),
	array( 'en' => 'unbalance', 'de' => 'Unwucht', 'not' => array( 'Ungleichgewicht', 'Unbalance', 'Unausgeglichenheit' ) ),
	array( 'en' => 'unbeatable deals', 'de' => 'unschlagbare Angebote', 'not' => array( 'unbesiegbare Deals', 'nicht abgeschlossene Angebote' ) ),
	array( 'en' => 'Universal Balancing', 'de' => 'Universal Balancing', 'not' => array( 'Universelles Auswuchten', 'Universal-Auswuchten' ) ),
	array( 'en' => 'uptime across systems', 'de' => 'Verfügbarkeit über Ihren gesamten Anlagenpark hinweg', 'not' => array( 'Betriebszeit über Systeme', 'Laufzeit aller Systeme' ) ),
	array( 'en' => 'v-block support', 'de' => 'Prismenauflage', 'not' => array( 'V-Block-Stütze', 'V-Block-Auflage' ) ),
	array( 'en' => 'vacuum', 'de' => 'Vakuum', 'not' => array( 'Unterdruck', 'Leere', 'Luftleere' ) ),
	array( 'en' => 'vacuum evacuation', 'de' => 'Evakuieren', 'not' => array( 'Vakuumevakuierung', 'Vakuumräumung' ) ),
	array( 'en' => 'vacuum rise test', 'de' => 'Vakuumanstiegsprüfung', 'not' => array( 'Unterdruckanstiegstest', 'Vakuumsteigtest' ) ),
	array( 'en' => 'validate performance', 'de' => 'Leistung validieren', 'not' => array( 'Wirkung überprüfen', 'Performance verifizieren' ) ),
	array( 'en' => 'valve body unit', 'de' => 'Ventilblock', 'not' => array( 'Ventilkörper-Einheit', 'Ventilgehäuseeinheit' ) ),
	array( 'en' => 'vibration', 'de' => 'Schwingungen', 'not' => array( 'Vibrationen', 'Vibrierungen' ) ),
	array( 'en' => 'volume flexibility', 'de' => 'Mengenflexibilität', 'not' => array( 'Volumenflexibilität', 'Stückzahlvariabilität' ) ),
	array( 'en' => 'walking beam system', 'de' => 'Hubbalkensystem', 'not' => array( 'Wanderbalken-System', 'Gehbalkensystem' ) ),
	array( 'en' => 'warranty coverage', 'de' => 'Garantieumfang', 'not' => array( 'Garantieversicherung', 'Gewährleistungsversicherung' ) ),
	array( 'en' => 'water meter', 'de' => 'Wasserzähler', 'not' => array( 'Wassermesser', 'Wasseruhr' ) ),
	array( 'en' => 'water-cooled', 'de' => 'wassergekühlt', 'not' => array( 'wasserkühlend', 'wasserkühlt' ) ),
	array( 'en' => 'Perceivable', 'de' => 'Wahrnehmbar', 'not' => array( 'Erkennbar', 'Sichtbar' ) ),
	array( 'en' => 'Operable', 'de' => 'Bedienbar', 'not' => array( 'Betriebsfähig', 'Handhabbar' ) ),
	array( 'en' => 'Understandable', 'de' => 'Verständlich', 'not' => array( 'Begreiflich', 'Nachvollziehbar' ) ),
	array( 'en' => 'Robust', 'de' => 'Robust', 'not' => array( 'Zuverlässig', 'Widerstandsfähig' ) ),
	array( 'en' => 'wheel aligner', 'de' => 'Achsmessgerät', 'not' => array( 'Radausrichter', 'Radjustiergerät' ) ),
	array( 'en' => 'wheel alignment', 'de' => 'Achsvermessung', 'not' => array( 'Radausrichtung', 'Radjustierung' ) ),
	array( 'en' => 'WHEREAS', 'de' => 'IN DER ERWÄGUNG, DASS', 'not' => array( 'WÄHREND', 'WOHINGEGEN' ) ),
	array( 'en' => 'whistle', 'de' => 'Pfeifen', 'not' => array( 'Pfiff', 'Zischen' ) ),
	array( 'en' => 'Work Product', 'de' => 'Arbeitsergebnis', 'not' => array( 'Arbeitsprodukt', 'Werkprodukt' ) ),
	array( 'en' => 'XL Machine', 'de' => 'XL Machine', 'not' => array( 'XL-Maschine', 'Maschine XL' ) ),
	array( 'en' => 'Marketplace', 'de' => 'Marktplatz', 'not' => array( 'Börse' ) ),
	array( 'en' => 'Medical', 'de' => 'Medizintechnik', 'not' => array( 'Medizinisch', 'Medizinische', 'Medizinwesen' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'de' => 'Förderband- und Papierwalzen', 'not' => array( 'Förderer und Papierrollen', 'Transportband- und Papierrollen' ) ),
	array( 'en' => 'stem stickiness', 'de' => 'Klemmen des Ventilschiebers', 'not' => array( 'Schaftviskosität', 'Stängelhaftung' ) ),
	array( 'en' => 'hydraulic pilot', 'de' => 'hydraulische Vorsteuerung', 'not' => array( 'Hydraulikpilot', 'hydraulischer Pilot' ) ),
	array( 'en' => 'load sense signal', 'de' => 'Load-Sensing-Signal', 'not' => array( 'Lastsensorsignal', 'Lastfühlersignal' ) ),
	array( 'en' => 'debonding', 'de' => 'Ablösung', 'not' => array( 'Delaminierung', 'Entbindung' ) ),
	array( 'en' => 'movable cradle', 'de' => 'verfahrbare Wiege', 'not' => array( 'bewegliche Basis', 'fahrbarer Rahmen' ) ),
	array( 'en' => 'ring gears', 'de' => 'Hohlräder', 'not' => array( 'Ringzahnräder', 'Kranzräder' ) ),
	array( 'en' => 'blade timing', 'de' => 'Schar-Taktzeit', 'not' => array( 'Klingentiming', 'Schaufelzeit' ) ),
	array( 'en' => 'heavy-duty', 'de' => 'schwer', 'not' => array( 'lastintensiv' ) ),
	array( 'en' => 'life sciences', 'de' => 'Life Sciences', 'not' => array( 'Lebenswissenschaften', 'Biowissenschaften' ) ),
	array( 'en' => 'First Alert Monitoring System', 'de' => 'First Alert Monitoring System', 'not' => array( 'Frühwarnsystem First Alert', 'Erstalarm-Überwachungssystem' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'de' => 'Turbo Test Duo Expert', 'not' => array( 'Experte Turbo Test Duo', 'TURBO TEST DUO Experte' ) ),
	array( 'en' => 'Introducing', 'de' => 'Wir stellen vor:', 'not' => array( 'Neuheit', 'Vorstellung' ) ),
	array( 'en' => 'flammable gases', 'de' => 'brennbare Gase', 'not' => array( 'entflammbare Gase', 'leicht entzündliche Gase' ) ),
	array( 'en' => 'Electronic hung mass', 'de' => 'elektronische Kompensation der aufgehängten Masse', 'not' => array( 'Elektronische Hängemasse', 'elektronische aufgehängte Masse' ) ),
	array( 'en' => 'Detection Focus', 'de' => 'Erkennbare Fehlerarten', 'not' => array( 'Erkennungsfokus', 'Detektionsschwerpunkt' ) ),
	array( 'en' => 'weight capacity', 'de' => 'Tragfähigkeit', 'not' => array( 'Gewichtskapazität', 'Gewichtsvermögen' ) ),
	array( 'en' => 'fixed stations', 'de' => 'feste Stationen', 'not' => array( 'stationäre Bahnhöfe', 'Feststationen' ) ),
	array( 'en' => 'mobile carousels', 'de' => 'mobile Karussells', 'not' => array( 'bewegliche Karussells', 'fahrbare Rundläufer' ) ),
	array( 'en' => 'cooling units', 'de' => 'Kälteaggregate', 'not' => array( 'Kühleinheiten', 'Kühlungsgeräte' ) ),
	array( 'en' => 'e-axle', 'de' => 'E-Achse', 'not' => array( 'Elektroachse', 'e-axle' ) ),
	array( 'en' => 'horizontal boring machine', 'de' => 'Horizontalbohrwerk', 'not' => array( 'horizontale Bohrmaschine', 'Waagerecht-Bohrgerät' ) ),
	array( 'en' => 'test benches', 'de' => 'Prüfstände', 'not' => array( 'Testbänke', 'Prüfbänke' ) ),
	array( 'en' => 'test stands', 'de' => 'Prüfstände', 'not' => array( 'Teststände', 'Testständer' ) ),
	array( 'en' => 'testing', 'de' => 'Prüfung', 'not' => array( 'Testen', 'Testung' ) ),
	array( 'en' => 'Aerospace & industrials', 'de' => 'Luft- und Raumfahrt sowie Industrie', 'not' => array( 'Luftfahrt und Industrie', 'Luft- und Raumfahrtindustrie', 'Aerospace & Industrie' ) ),
	array( 'en' => 'Exhibit', 'de' => 'Anlage', 'not' => array( 'Ausstellung', 'Exponat' ) ),
	array( 'en' => 'Section', 'de' => 'Abschnitt', 'not' => array( 'Sektion', 'Paragraf' ) ),
	array( 'en' => 'RECITALS', 'de' => 'PRÄAMBEL', 'not' => array( 'ERWÄGUNGEN', 'VORBEMERKUNGEN' ) ),
	array( 'en' => 'Products', 'de' => 'Produkte', 'not' => array(  ) ),
	array( 'en' => 'Ascential Indemnity', 'de' => 'Freistellung durch Ascential', 'not' => array( 'Ascential Indemnity', 'Ascential-Entschädigung' ) ),
	array( 'en' => 'England', 'de' => 'England', 'not' => array(  ) ),
	array( 'en' => 'West Flanders', 'de' => 'Westflandern', 'not' => array( 'West-Flandern', 'West Flanders' ) ),
	array( 'en' => 'Poland', 'de' => 'Polen', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Play', 'de' => 'Abspielen', 'not' => array( 'Play', 'Spielen', 'Spiel starten' ) ),
	array( 'en' => 'Listen to this article', 'de' => 'Diesen Artikel anhören', 'not' => array( 'Listen to this article', 'Hören Sie diesen Artikel' ) ),
	array( 'en' => 'Read the article', 'de' => 'Artikel lesen', 'not' => array( 'Read the article', 'Den Artikel lesen' ) ),
	array( 'en' => 'Read More', 'de' => 'Weiterlesen', 'not' => array( 'Mehr lesen', 'Weiter lesen' ) ),
	array( 'en' => 'News', 'de' => 'Aktuelles', 'not' => array( 'Nachrichten', 'Neuigkeiten' ) ),
	array( 'en' => 'chapters', 'de' => 'Kapitel', 'not' => array( 'chapters', 'Abschnitte' ) ),
	array( 'en' => 'Share', 'de' => 'Teilen', 'not' => array( 'Share', 'Freigeben' ) ),
	array( 'en' => 'Copy link', 'de' => 'Link kopieren', 'not' => array( 'Copy link', 'Link-Kopie' ) ),
	array( 'en' => 'Email', 'de' => 'E-Mail', 'not' => array( 'Email', 'Emaille' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'de' => 'Broschüre zur Kältemittelbefüllung', 'not' => array( 'Refrigerant Charging Brochure', 'Kältemittel-Lade-Broschüre', 'Broschüre Kältemittelbefüllung', 'Kältemittelbefüllungs-Broschüre' ) ),
	array( 'en' => 'Explore', 'de' => 'Entdecken', 'not' => array( 'Erkunden', 'Mehr Infos' ) ),
	array( 'en' => 'Browse catalog', 'de' => 'Katalog durchsuchen', 'not' => array( 'Katalog', 'Katalog blättern' ) ),
	array( 'en' => 'Browse all resources', 'de' => 'Alle Ressourcen durchsuchen', 'not' => array( 'Alle Ressourcen', 'Ressourcen ansehen' ) ),
	array( 'en' => 'Explore the Catalog', 'de' => 'Katalog durchsuchen', 'not' => array( 'Katalog erkunden', 'Den Katalog entdecken' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'de' => 'Sie möchten Ihre Anlagen modernisieren?', 'not' => array( 'Bereit für ein Infrastruktur-Upgrade?', 'Sind Sie bereit, Ihre Infrastruktur aufzurüsten?', 'Bereit, Ihre Infrastruktur zu modernisieren?' ) ),
	array( 'en' => 'Talk to an expert', 'de' => 'Mit einem Experten sprechen', 'not' => array( 'Sprich mit einem Experten', 'Expertengespräch' ) ),
	array( 'en' => 'fully loaded test', 'de' => 'Prüfung unter Volllast', 'not' => array( 'vollbeladener Test', 'umfassender Test' ) ),
	array( 'en' => 'Addresses', 'de' => 'Behandelt', 'not' => array( 'Eliminiert', 'Beseitigt' ) ),
	array( 'en' => 'is now', 'de' => 'ist jetzt', 'not' => array( 'wird nun', 'heißt nunmehr' ) ),
	array( 'en' => 'sales inquiry', 'de' => 'Vertriebsanfrage', 'not' => array( 'Verkaufsanfrage', 'Handelsanfrage' ) ),
	array( 'en' => 'Priority 1', 'de' => 'Priorität 1: hoch', 'not' => array( 'Priorität 1: Hohe Priorität', 'Priorität Eins' ) ),
	array( 'en' => 'Priority 2', 'de' => 'Priorität 2: mittel', 'not' => array( 'Priorität 2: Mittlere Priorität', 'Priorität Zwei' ) ),
	array( 'en' => 'Priority 3', 'de' => 'Priorität 3: niedrig', 'not' => array( 'Priorität 3: Niedrige Priorität', 'Priorität Drei' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'de' => 'ascentialtech.com durchsuchen', 'not' => array( 'Searching ascentialtech.com', 'Suche ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'de' => 'Kalenderansicht nicht verfügbar', 'not' => array( 'Calendar View Unavailable', 'Kalender-Ansicht unverfügbar' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'de' => 'Anbaugeräte – End-of-Line', 'not' => array( 'Implemente – End-Of-Line', 'Mobilgeräte-Anbaugeräte' ) ),
	array( 'en' => 'equipment', 'de' => 'Anlagen', 'not' => array( 'Ausrüstung', 'Vermögenswerte' ) ),
	array( 'en' => 'Transportation', 'de' => 'Fahrzeugtechnik', 'not' => array( 'Verkehrstechnik', 'Transportwesen' ) ),
	array( 'en' => 'Industries served', 'de' => 'Betreute Branchen', 'not' => array( 'Bediente Branchen', 'Branchen, die wir bedienen' ) ),
	array( 'en' => 'remote monitoring', 'de' => 'Fernüberwachung', 'not' => array( 'ferngesteuerte Überwachung', 'Remote-Monitoring' ) ),
	array( 'en' => 'deep expertise', 'de' => 'fundierte Expertise', 'not' => array( 'tiefe Expertise', 'tiefes Verständnis' ) ),
	array( 'en' => 'preventive maintenance', 'de' => 'vorbeugende Wartung', 'not' => array( 'präventive Wartung', 'Präventivwartung' ) ),
	array( 'en' => 'intervention time', 'de' => 'Eingriffszeit', 'not' => array(  ) ),
	array( 'en' => 'response time', 'de' => 'Reaktionszeit', 'not' => array(  ) ),
	array( 'en' => 'loading', 'de' => 'Beschickung', 'not' => array( 'Beladung', 'Beladen' ) ),
	array( 'en' => 'robotic loading', 'de' => 'Roboterbeschickung', 'not' => array( 'Roboterbeladung', 'robotische Beladung' ) ),
	array( 'en' => 'balancing machines', 'de' => 'Auswuchtmaschinen', 'not' => array( 'balancing machines', 'Wuchtmaschinen', 'Ausgleichmaschinen', 'Ausgleichsmaschinen' ) ),
	array( 'en' => 'clutch and flywheel balancer', 'de' => 'Kupplungs- und Schwungrad-Auswuchtmaschine', 'not' => array(  ) ),
	array( 'en' => 'differential case', 'de' => 'Differenzialgehäuse', 'not' => array( 'Differentialgehäuse', 'Ausgleichsgehäuse' ) ),
	array( 'en' => 'axle balancing machine', 'de' => 'Achsauswuchtmaschine', 'not' => array( 'Achsenauswuchtmaschine', 'Achsen-Auswuchtmaschine' ) ),
	array( 'en' => 'Chief Technology Officer of Transportation', 'de' => 'Chief Technology Officer of Transportation', 'not' => array( 'Technischer Vorstand Fahrzeugtechnik', 'Technikvorstand Fahrzeugtechnik' ) ),

	// round 2 (de)
	array( 'en' => '- Image 1', 'de' => '– Bild 1', 'not' => array( '- Image 1', '– Image 1', '- Bild 1' ) ),
	array( 'en' => '- Image 2', 'de' => '– Bild 2', 'not' => array( '- Image 2', '– Image 2', '- Bild 2' ) ),
	array( 'en' => 'driveshaft', 'de' => 'Gelenkwelle', 'not' => array( 'Kardanwelle', 'Gelenkwellen-Auswuchtmaschine', 'Antriebswellen-Auswuchtmaschine', 'Antriebswelle' ) ),
	array( 'en' => 'propshaft', 'de' => 'Gelenkwelle', 'not' => array( 'Vortriebswelle', 'Propellerwelle' ) ),
	array( 'en' => 'core business', 'de' => 'Kerngeschäft', 'not' => array( 'Rumpfgruppen-Geschäft' ) ),
	array( 'en' => 'core expertise', 'de' => 'Kernkompetenz', 'not' => array( 'Rumpfgruppen-Kernkompetenz', 'Rumpfgruppenkompetenz' ) ),
	array( 'en' => 'Core Components', 'de' => 'Kernkomponenten', 'not' => array( 'Rumpfgruppe Komponenten', 'Rumpfgruppen-Komponenten' ) ),
	array( 'en' => 'Core Features', 'de' => 'Kernfunktionen', 'not' => array( 'Rumpfgruppen-Funktionen', 'Rumpfgruppenfunktionen' ) ),
	array( 'en' => 'HFC', 'de' => 'HFKW', 'not' => array( 'HFC-Kältemittel', 'FKW-Kältemittel', 'FKW mit niedrigem Dampfdruck' ) ),
	array( 'en' => 'HCFC', 'de' => 'HFCKW', 'not' => array( 'HCFC-Kältemittel', 'HCFC-Familie' ) ),
	array( 'en' => 'CFC', 'de' => 'FCKW', 'not' => array( 'CFC-Kältemittel', 'CFC-Gase' ) ),
	array( 'en' => 'Grinder Revamp Brochure', 'de' => 'Broschüre zur Modernisierung von Schleifmaschinen', 'not' => array( 'Schleifer-Revamp-Broschüre', 'Schleifmaschinen-Revamp-Broschüre' ) ),
	array( 'en' => 'Balancing Textbook', 'de' => 'Balancing Textbook', 'not' => array( 'Auswucht-Lehrbuch', 'Auswuchtlehrbuch', 'Lehrbuch des Auswuchtens' ) ),
	array( 'en' => 'Precision Machining', 'de' => 'Präzisionsbearbeitung', 'not' => array( 'Präzisionsfertigung', 'Präzisionszerspanung' ) ),
	array( 'en' => 'automatic changeover', 'de' => 'automatische Umrüstung', 'not' => array( 'automatischer Wechsel', 'automatischer Umbau', 'automatische Umrüstfunktion', 'automatischer Rüstwechsel' ) ),
	array( 'en' => 'automatic grinder control', 'de' => 'automatische Schleifmaschinensteuerung', 'not' => array( 'Schleifmaschinenregler', 'automatischer Schleifmaschinenregler', 'Schleifmaschinen-Steuerung' ) ),
	array( 'en' => 'Hay baler – round & square', 'de' => 'Heuballenpresse – Rund- und Quaderballen', 'not' => array( 'Heuballen-Ballenpresse', 'Rund & Eckig', 'Rund- und Quaderballenpressen' ) ),
	array( 'en' => 'Combine Belt', 'de' => 'Mähdrescherband', 'not' => array( 'Mähdrescher-Gurt', 'Mähdreschergurt', 'Mähdrescher-Gurtsystem' ) ),
	array( 'en' => 'Engine cooling fan', 'de' => 'Motorkühllüfter', 'not' => array( 'Kühlgebläse', 'Motorkühlerlüfter', 'Motorlüfter' ) ),
	array( 'en' => '3-axis gantry milling system', 'de' => '3-Achs-Portalfrässystem', 'not' => array( '3-Achs-Portalfräsen', '3-Achsen-Portalfräsen' ) ),
	array( 'en' => 'Electric armature balancing machine', 'de' => 'Auswuchtmaschine für elektrische Anker', 'not' => array( 'Elektrische Anker-Auswuchtmaschine', 'Elektroanker-Auswuchtmaschine' ) ),
	array( 'en' => 'multi-language keyboard', 'de' => 'mehrsprachige Tastatur', 'not' => array( 'Mehrsprachentastatur', 'Mehrsprachen-Tastatur' ) ),
	array( 'en' => 'Gas managed', 'de' => 'Gasart', 'not' => array( 'Verwaltetes Gas', 'Gasbetrieben', 'Verwaltete Gase', 'Behandelte Gase' ) ),
	array( 'en' => 'ECM (Engine Control Module)', 'de' => 'ECM (Motorsteuergerät)', 'not' => array( 'ECM (Engine Control Module)', 'ECM (Motorsteuermodul)' ) ),
	array( 'en' => 'ECM software revision', 'de' => 'ECM-Softwareversion', 'not' => array( 'ECM-Software-Revision', 'ECM-Softwarerevision' ) ),
	array( 'en' => 'programming of blank ECMs', 'de' => 'Programmierung unprogrammierter Steuergeräte', 'not' => array( 'Programmierung von unbeschriebenen ECMs', 'Programmierung leerer Steuergeräte' ) ),
	array( 'en' => 'Lighting functionality', 'de' => 'Beleuchtungsfunktionen', 'not' => array( 'Beleuchtungsfunktion', 'Beleuchtungsfunktionalität' ) ),
	array( 'en' => 'end-of-line', 'de' => 'End-of-Line', 'not' => array( 'Bandende', 'Linienende', 'Ende der Fertigungslinie' ) ),
	array( 'en' => 'vision systems', 'de' => 'Bildverarbeitungssysteme', 'not' => array( 'Kamerasysteme', 'Sichtsysteme', 'Visionssysteme' ) ),
	array( 'en' => 'chassis dynamometers', 'de' => 'Rollenprüfstände', 'not' => array( 'Fahrgestelldynamometer', 'Fahrleistungsprüfstände', 'Chassis-Dynamometer' ) ),
	array( 'en' => 'Compact Balancers', 'de' => 'kompakte Auswuchtmaschinen', 'not' => array( 'Compact Balancers', 'Kompaktauswuchter', 'Compact-Balancer' ) ),
	array( 'en' => 'twin roller', 'de' => 'Doppelrolle', 'not' => array( 'Zwillingsrolle', 'Zwillingswalze' ) ),
	array( 'en' => 'expansion sleeve', 'de' => 'Spreizhülse', 'not' => array( 'Dehnspannhülse', 'Spreizspannhülse', 'Expansionshülse' ) ),
	array( 'en' => 'compensation', 'de' => 'Kompensation', 'not' => array( 'Ausgleichung', 'Entschädigung' ) ),
	array( 'en' => 'quality control', 'de' => 'Qualitätskontrolle', 'not' => array( 'Qualitätssteuerung', 'Qualitätsregelung' ) ),
	array( 'en' => 'subsurface', 'de' => 'unter der Oberfläche', 'not' => array( 'oberflächennah', 'unterflächig', 'Unterfläche' ) ),
	array( 'en' => 'Noise, vibration & harshness', 'de' => 'Geräusch, Vibration & Rauigkeit', 'not' => array( 'Geräusche, Schwingungen & Rauheit', 'Geräusch-Schwingungs-Rauigkeit', 'Lärm, Vibration und Härte' ) ),
	array( 'en' => 'pump balancers', 'de' => 'Pumpenauswuchtmaschinen', 'not' => array( 'Pumpenwuchtmaschinen', 'Pumpen-Wuchtmaschinen' ) ),
	array( 'en' => 'Legislative Diagnostic Documentation Review', 'de' => 'Überprüfung gesetzlicher Diagnosedokumentation', 'not' => array( 'Gesetzlich vorgeschriebene Überprüfung von Diagnosedokumentation', 'Prüfung gesetzlicher Diagnosedokumentation' ) ),
	array( 'en' => 'dosing cylinder', 'de' => 'Dosierzylinder', 'not' => array( 'Messzylinder', 'Dosierungszylinder' ) ),
	array( 'en' => 'technological shaft', 'de' => 'Hilfswelle', 'not' => array( 'Technologieschaft', 'technologischer Schaft', 'Technologiewelle', 'technologische Welle' ) ),
	array( 'en' => 'Hydrostatic Transmission (HST) Test', 'de' => 'Prüfsystem für hydrostatische Getriebe (HST)', 'not' => array( 'Hydrostatisches Getriebe (HST) – Prüfung', 'HST-Getriebeprüfung' ) ),
	array( 'en' => 'ultrasonic technology', 'de' => 'Ultraschalltechnik', 'not' => array( 'Ultraschalltechnologie' ) ),
	array( 'en' => 'SW tester', 'de' => 'SW-Tester', 'not' => array( 'SW-Prüfgerät', 'SW-Prüfer' ) ),
	array( 'en' => 'UT tester', 'de' => 'UT-Tester', 'not' => array( 'UT-Prüfgerät', 'UT-Prüfer' ) ),
	array( 'en' => 'Former President', 'de' => 'Ehemaliger Präsident', 'not' => array( 'Ehemaliger President', 'Früherer President' ) ),
	array( 'en' => 'wind turbines', 'de' => 'Windkraftanlagen', 'not' => array( 'Windturbinen', 'Windräder' ) ),
	array( 'en' => 'Transmission Drop Box', 'de' => 'Getriebe-Drop-Box', 'not' => array( 'Transmission Drop Box', 'Getriebeabsetzkasten' ) ),
	array( 'en' => 'heavy-duty vehicles', 'de' => 'schwere Nutzfahrzeuge', 'not' => array( 'Schwerlastfahrzeuge', 'Schwere Fahrzeuge', 'Hochleistungsfahrzeuge' ) ),
	array( 'en' => 'off-road equipment', 'de' => 'Off-Road-Maschinen', 'not' => array( 'Geländefahrzeuge', 'geländegängige Anlagen', 'Off-Highway-Anlagen' ) ),
	array( 'en' => 'chassis harness', 'de' => 'Chassis-Kabelbaum', 'not' => array( 'Fahrgestellkabelbaum', 'Fahrgestell-Kabelbaum' ) ),
	array( 'en' => 'electrical control panel', 'de' => 'Elektro-Schaltschrank', 'not' => array( 'elektrisches Steuerungspanel', 'Elektrosteuerungspanel' ) ),
	array( 'en' => 'aligning systems', 'de' => 'Achsmesssysteme', 'not' => array( 'Ausrichtsysteme', 'Ausrichtungssysteme' ) ),
	array( 'en' => 'Audit balancer', 'de' => 'Kontrollauswuchtmaschine', 'not' => array( 'Audit-Auswuchtmaschine', 'Prüfauswuchtmaschine' ) ),
	array( 'en' => 'Universal CNC Grinder', 'de' => 'CNC-Universalschleifmaschine', 'not' => array( 'Universal-CNC-Schleifer', 'Universal-CNC-Schleifgerät' ) ),
	array( 'en' => 'discrete wiring', 'de' => 'Einzelleitungen', 'not' => array( 'diskrete Verdrahtung', 'diskrete Leitungen' ) ),
	array( 'en' => 'high volume production', 'de' => 'Großserienproduktion', 'not' => array( 'Hochvolumenproduktion', 'Hochvolumenfertigung' ) ),
	array( 'en' => 'test-track environment', 'de' => 'Teststreckenumgebung', 'not' => array( 'Teststreckensituation', 'Teststreckensimulation' ) ),
	array( 'en' => 'twin roller machines', 'de' => 'Doppelrollenmaschinen', 'not' => array( 'Zwillingsrollenmaschinen', 'Doppelwalzenmaschinen' ) ),
	array( 'en' => 'strut', 'de' => 'Federbein', 'not' => array( 'Strut', 'Stütze', 'Strebe' ) ),
	array( 'en' => 'HVAC', 'de' => 'HLK', 'not' => array( 'HVAC', 'Heizung-Lüftung-Klima' ) ),
	array( 'en' => 'review', 'de' => 'Überprüfung', 'not' => array( 'Rezension', 'Begutachtung' ) ),
	array( 'en' => 'correction methods', 'de' => 'Ausgleichsverfahren', 'not' => array( 'Korrektionsmethoden', 'Korrektumethoden', 'Korrekturmethoden', 'Korrekturverfahren' ) ),
	array( 'en' => 'refrigerant charging machine', 'de' => 'Kältemittelbefüllmaschine', 'not' => array( 'Kältemittelbefüllungsmaschine', 'Kältemittel-Lademaschine' ) ),
	array( 'en' => 'compressor station', 'de' => 'Verdichterstation', 'not' => array( 'Gaskompressorstation', 'Kompressorstation' ) ),
	array( 'en' => 'Advanced driver-assistance systems', 'de' => 'Fortschrittliche Fahrerassistenzsysteme', 'not' => array( 'Erweiterte Fahrerassistenzsysteme', 'Fortgeschrittene Fahrerassistenzsysteme' ) ),
	array( 'en' => 'Spin testers', 'de' => 'Schleuderprüfstände', 'not' => array( 'Auslaufprüfstände', 'Spin-Tester' ) ),
	array( 'en' => 'bearing supports', 'de' => 'Lagerböcke', 'not' => array( 'Lagerträger', 'Lagerstützen' ) ),
	array( 'en' => 'journal', 'de' => 'Lagerzapfen', 'not' => array( 'Zapfen', 'Lagerstelle' ) ),
	array( 'en' => 'runout', 'de' => 'Rundlauf', 'not' => array( 'Auslauf', 'Ausschlag' ) ),
	array( 'en' => 'transverse runout', 'de' => 'Planlauf', 'not' => array( 'Querschlag', 'Querlauf' ) ),
	array( 'en' => 'static balancers', 'de' => 'statische Auswuchtmaschinen', 'not' => array( 'Statik-Auswuchtmaschinen', 'statische Wuchtmaschinen' ) ),
	array( 'en' => 'stiff-pivot', 'de' => 'mit steifem Drehpunkt', 'not' => array( 'steifgelenkig', 'starrgelenkig' ) ),
	array( 'en' => 'Regenerative Power', 'de' => 'Energierückspeisung', 'not' => array( 'Regenerative Leistung', 'Regenerativleistung' ) ),
	array( 'en' => 'External Charge System', 'de' => 'Externes Speisesystem', 'not' => array( 'Externes Ladesystem', 'Externes Aufladesystem' ) ),
	array( 'en' => 'Holset Programmer', 'de' => 'Holset-Programmiergerät', 'not' => array( 'Holset-Programmierer', 'Holset Programmer' ) ),
	array( 'en' => 'standard inspection', 'de' => 'Standardprüfung', 'not' => array( 'Standardinspektion', 'Regelinspektion' ) ),
	array( 'en' => 'Manual & automated transmissions', 'de' => 'Schalt- & Automatikgetriebe', 'not' => array( 'Manuelle und automatische Getriebe', 'Handschalt- und Automatikgetriebe' ) ),
	array( 'en' => 'Single and dual-plane balancing', 'de' => 'Auswuchten in einer und in zwei Ebenen', 'not' => array( 'Einebenen- und Zweiebenenwuchten', 'Ein- und Zweiebenenwuchten' ) ),
	array( 'en' => 'emission controls', 'de' => 'Emissionsminderungssysteme', 'not' => array( 'Emissionssteuerungssysteme', 'Emissionskontrollen' ) ),
	array( 'en' => 'glass replacement', 'de' => 'Autoglasaustausch', 'not' => array( 'Glasersatz', 'Glasaustausch' ) ),
	array( 'en' => 'roll shop equipment', 'de' => 'Anlagen der Walzenschleiferei', 'not' => array( 'Walzenwerkstatt-Anlagen', 'Walzwerkstatt-Anlagen' ) ),
	array( 'en' => 'refrigeration systems', 'de' => 'Kälteanlagen', 'not' => array( 'Kältetechniksysteme', 'Kühlsysteme' ) ),

	// round pro (de)
	array( 'en' => 'balancing machine', 'de' => 'Auswuchtmaschine', 'not' => array( 'Ausgleichmaschine', 'Ausgleichsmaschine', 'Balanciermaschine' ) ),
	array( 'en' => 'balancing', 'de' => 'Auswuchten', 'not' => array( 'Balancieren', 'Ausbalancieren' ) ),
	array( 'en' => 'balancer', 'de' => 'Auswuchtmaschine', 'not' => array( 'Balanciermaschine', 'Turbolader-Auswuchter' ) ),
	array( 'en' => 'vertical balancing machine', 'de' => 'vertikale Auswuchtmaschine', 'not' => array( 'Vertikalachsen-Auswuchtmaschine', 'Vertikalauswuchter' ) ),
	array( 'en' => 'horizontal balancing machine', 'de' => 'horizontale Auswuchtmaschine', 'not' => array( 'Horizontalachsen-Auswuchtmaschine', 'Horizontalauswuchter' ) ),
	array( 'en' => 'vertical balancing', 'de' => 'vertikales Auswuchten', 'not' => array( 'vertikale Auswuchtung', 'Vertikalbalancierung' ) ),
	array( 'en' => 'horizontal balancing', 'de' => 'horizontales Auswuchten', 'not' => array( 'horizontale Auswuchtung', 'Horizontalbalancierung' ) ),
	array( 'en' => 'dynamic balancing', 'de' => 'dynamisches Auswuchten', 'not' => array( 'dynamische Auswuchtung', 'dynamisches Balancieren' ) ),
	array( 'en' => 'rotor balancing', 'de' => 'Rotorauswuchten', 'not' => array( 'Rotorauswuchtung', 'Rotorbalancierung' ) ),
	array( 'en' => 'tool holder', 'de' => 'Werkzeugaufnahme', 'not' => array( 'Werkzeughalter', 'Werkzeughalterung' ) ),
	array( 'en' => 'unbalanced tools', 'de' => 'Werkzeuge mit Unwucht', 'not' => array( 'unwuchtige Werkzeuge', 'unausgeglichene Werkzeuge' ) ),
	array( 'en' => 'unbalanced', 'de' => 'unwuchtbehaftet', 'not' => array( 'unwuchtige', 'unausgeglichen', 'unbalanciert' ) ),
	array( 'en' => 'imbalance', 'de' => 'Unwucht', 'not' => array( 'Ungleichgewicht', 'Imbalance', 'Unausgeglichenheit' ) ),
	array( 'en' => 'unbalance measurement', 'de' => 'Unwuchtmessung', 'not' => array( 'Ungleichgewichtsmessung', 'Unbalancemessung' ) ),
	array( 'en' => 'unbalance correction', 'de' => 'Unwuchtausgleich', 'not' => array( 'Unwuchtkorrektur', 'Unwucht-Korrektur' ) ),
	array( 'en' => 'mass correction', 'de' => 'Unwuchtausgleich', 'not' => array( 'Massenkorrektur', 'Massekorrektur' ) ),
	array( 'en' => 'correction on the machine', 'de' => 'Ausgleich auf der Maschine', 'not' => array( 'Korrektur an der Maschine', 'Korrektur auf der Maschine' ) ),
	array( 'en' => 'drilling correction', 'de' => 'Ausgleich durch Bohren', 'not' => array( 'Bohrkorrektur', 'Bohrungskorrektur' ) ),
	array( 'en' => 'correction plane', 'de' => 'Ausgleichsebene', 'not' => array( 'Korrekturebene', 'Korrektionsebene' ) ),
	array( 'en' => 'correction weight', 'de' => 'Ausgleichsgewicht', 'not' => array( 'Korrekturgewicht', 'Korrektturgewicht' ) ),
	array( 'en' => 'correction radius', 'de' => 'Ausgleichsradius', 'not' => array( 'Korrekturradius' ) ),
	array( 'en' => 'correction method', 'de' => 'Ausgleichsverfahren', 'not' => array( 'Korrekturverfahren', 'Korrekturmethode', 'Korrektionsmethode' ) ),
	array( 'en' => 'methods of correction', 'de' => 'Ausgleichsverfahren', 'not' => array( 'Korrekturverfahren', 'Korrekturmethoden', 'Korrektionsmethoden' ) ),
	array( 'en' => 'automatic correction point calculation', 'de' => 'automatische Berechnung der Ausgleichsstelle', 'not' => array( 'automatische Korrekturpunktberechnung', 'automatische Berechnung des Korrekturpunkts', 'automatische Korrektionspunkt-Berechnung' ) ),
	array( 'en' => 'integrated correction', 'de' => 'integrierter Unwuchtausgleich', 'not' => array( 'integrierte Korrektur' ) ),
	array( 'en' => 'automatic correction', 'de' => 'automatischer Unwuchtausgleich', 'not' => array( 'automatische Korrektur', 'automatische Unwuchtkorrektur' ) ),
	array( 'en' => 'balancing weight', 'de' => 'Auswuchtgewicht', 'not' => array( 'Balanciergewicht', 'Ausbalanciergewicht' ) ),
	array( 'en' => 'balance quality grade', 'de' => 'Auswuchtgütestufe', 'not' => array( 'Auswuchtqualitätsgrad', 'Auswuchtqualitätsstufe', 'Balancierqualität' ) ),
	array( 'en' => 'minimum achievable residual unbalance', 'de' => 'kleinste erreichbare Restunwucht', 'not' => array( 'Mindestrestunwucht', 'minimales erreichbares Restungleichgewicht' ) ),
	array( 'en' => 'unbalance reduction ratio', 'de' => 'Unwuchtreduzierverhältnis', 'not' => array( 'Untersetzungsverhältnis', 'Reduktionsverhältnis' ) ),
	array( 'en' => 'ISO 2953 Reduction Ratio', 'de' => 'Unwuchtreduzierverhältnis nach ISO 2953', 'not' => array( 'ISO 2953 Untersetzungsverhältnis', 'ISO 2953 Reduktionsverhältnis' ) ),
	array( 'en' => 'gyroscope rotor', 'de' => 'Kreiselrotor', 'not' => array( 'Gyroskop-Rotor', 'Gyroskoprotor' ) ),
	array( 'en' => 'measuring and control unit', 'de' => 'Mess- und Steuereinheit', 'not' => array( 'Mess- und Steuerungseinheit', 'Mess- und Kontrolleinheit' ) ),
	array( 'en' => 'control unit', 'de' => 'Steuereinheit', 'not' => array( 'Steuerungseinheit', 'Kontrolleinheit' ) ),
	array( 'en' => 'measuring system', 'de' => 'Messsystem', 'not' => array( 'Messungssystem', 'Mess-System' ) ),
	array( 'en' => 'measurement system', 'de' => 'Messsystem', 'not' => array( 'Messungssystem', 'Mess-System' ) ),
	array( 'en' => 'end drive', 'de' => 'Gelenkwellenantrieb', 'not' => array( 'Endantrieb', 'Stirnantrieb' ) ),
	array( 'en' => 'belt drive', 'de' => 'Riemenantrieb', 'not' => array( 'Bandantrieb', 'Gurtantrieb' ) ),
	array( 'en' => 'journal diameter', 'de' => 'Lagerzapfendurchmesser', 'not' => array( 'Journaldurchmesser', 'Zapfenbereich' ) ),
	array( 'en' => 'bearing', 'de' => 'Lager', 'not' => array( 'Peilung' ) ),
	array( 'en' => 'impeller', 'de' => 'Laufrad', 'not' => array( 'Impeller' ) ),
	array( 'en' => 'clamping', 'de' => 'Spannen', 'not' => array( 'Klemmung', 'Einklemmen' ) ),
	array( 'en' => 'small footprint', 'de' => 'geringer Platzbedarf', 'not' => array( 'kleiner Fußabdruck', 'kleine Grundfläche' ) ),
	array( 'en' => 'V-block', 'de' => 'Prisma', 'not' => array( 'V-Block', 'V-Blöcke' ) ),
	array( 'en' => 'fixture', 'de' => 'Vorrichtung', 'not' => array( 'Fixture', 'Fixierung' ) ),
	array( 'en' => 'field balancer', 'de' => 'mobiles Auswuchtgerät', 'not' => array( 'Feldauswuchter', 'Feld-Auswuchtmaschine' ) ),
	array( 'en' => 'driveshaft balancer', 'de' => 'Gelenkwellen-Auswuchtmaschine', 'not' => array( 'Antriebswellen-Auswuchtmaschine', 'Kardanwellen-Auswuchtmaschine' ) ),
	array( 'en' => 'turbocharger balancing machine', 'de' => 'Turbolader-Auswuchtmaschine', 'not' => array( 'Turbo-Ausgleichsmaschine', 'Turbolader-Ausgleichmaschine' ) ),
	array( 'en' => 'gantry loading', 'de' => 'Portalladerbeschickung', 'not' => array( 'Portalbefestigung', 'Portalbeladung' ) ),
	array( 'en' => 'turbocharger core', 'de' => 'Turbolader-Rumpfgruppe', 'not' => array( 'Turboladerkern', 'Turbolader-Kern', 'Rotorkern' ) ),
	array( 'en' => 'high-speed core balancing', 'de' => 'Hochdrehzahl-Rumpfgruppenauswuchten', 'not' => array( 'Hochgeschwindigkeits-Kernauswuchten', 'Hochdrehzahl-Kernauswuchten', 'Rumpfgruppenauswuchten mit hoher Drehzahl' ) ),
	array( 'en' => 'low-speed core balancing', 'de' => 'Niederdrehzahl-Rumpfgruppenauswuchten', 'not' => array( 'Niedergeschwindigkeits-Kernauswuchten', 'Niederdrehzahl-Kernauswuchten' ) ),
	array( 'en' => 'turbocharger balancing', 'de' => 'Turboladerauswuchten', 'not' => array( 'Turbolader-Balancierung', 'Turboausgleich' ) ),
	array( 'en' => 'automotive eRotor', 'de' => 'E-Motor-Rotor für die Automobilindustrie', 'not' => array( 'Automotive-eRotor', 'Automotive-E-Rotor' ) ),
	array( 'en' => 'compressor wheel', 'de' => 'Verdichterrad', 'not' => array( 'Kompressorrad', 'Kompressorlaufrad' ) ),
	array( 'en' => 'supercharger', 'de' => 'mechanischer Lader', 'not' => array( 'Superlader', 'Superladers' ) ),
	array( 'en' => 'flow bench', 'de' => 'Strömungsprüfstand', 'not' => array( 'Durchflussprüfanlage', 'Durchsatzprüfstand', 'Strömungsprüfbank' ) ),
	array( 'en' => 'mass air flow', 'de' => 'Luftmassenstrom', 'not' => array( 'Massenluftstrom', 'Massenluftstromstärke' ) ),
	array( 'en' => 'spin test', 'de' => 'Schleuderprüfung', 'not' => array( 'Spinnprüfung', 'Spin-Test', 'Spintest' ) ),
	array( 'en' => 'test stand', 'de' => 'Prüfstand', 'not' => array( 'Teststand', 'Testständer' ) ),
	array( 'en' => 'test bench', 'de' => 'Prüfstand', 'not' => array( 'Testbank', 'Testbench' ) ),
	array( 'en' => 'test system', 'de' => 'Prüfsystem', 'not' => array( 'Testsystem' ) ),
	array( 'en' => 'test station', 'de' => 'Prüfstation', 'not' => array( 'Teststation' ) ),
	array( 'en' => 'Test Type', 'de' => 'Prüfart', 'not' => array( 'Prüfungstyp', 'Testtyp' ) ),
	array( 'en' => 'end-of-line testing', 'de' => 'End-of-Line-Prüfung', 'not' => array( 'Bandendeprüfung', 'Prüfung am Bandende', 'End-of-Line-Test' ) ),
	array( 'en' => 'functional test', 'de' => 'Funktionsprüfung', 'not' => array( 'funktionaler Test', 'Funktionalitätstest' ) ),
	array( 'en' => 'leak test', 'de' => 'Dichtheitsprüfung', 'not' => array( 'Lecktest', 'Leckprüfung', 'Undichtigkeitstest' ) ),
	array( 'en' => 'leak testing', 'de' => 'Dichtheitsprüfung', 'not' => array( 'Lecktest', 'Leckprüfung', 'Lecktesten' ) ),
	array( 'en' => 'transmission test', 'de' => 'Getriebeprüfung', 'not' => array( 'Getriebetest', 'Übertragungstest' ) ),
	array( 'en' => 'valve test', 'de' => 'Ventilprüfung', 'not' => array( 'Ventiltest' ) ),
	array( 'en' => 'valve test system', 'de' => 'Ventilprüfstand', 'not' => array( 'Ventiltestsystem', 'Ventiltest-System' ) ),
	array( 'en' => 'pump test', 'de' => 'Pumpenprüfung', 'not' => array( 'Pumpentest' ) ),
	array( 'en' => 'gear pump', 'de' => 'Zahnradpumpe', 'not' => array( 'Getriebepumpe', 'Zahnpumpe' ) ),
	array( 'en' => 'ADAS calibration', 'de' => 'ADAS-Kalibrierung', 'not' => array( 'ADAS-Kalibration', 'ADAS-Eichung' ) ),
	array( 'en' => 'data acquisition', 'de' => 'Datenerfassung', 'not' => array( 'Datenakquisition', 'Datenakquise', 'Datenbeschaffung' ) ),
	array( 'en' => 'sophisticated data acquisition software', 'de' => 'leistungsfähige Datenerfassungssoftware', 'not' => array( 'ausgeklügelte Datenerfassungssoftware', 'anspruchsvolle Datenerfassungssoftware', 'hochentwickelte Datenerfassungssoftware' ) ),
	array( 'en' => 'assembly errors', 'de' => 'Montagefehler', 'not' => array( 'Baugruppenfehler', 'Zusammenbaufehler' ) ),
	array( 'en' => 'before shipping', 'de' => 'vor der Auslieferung', 'not' => array( 'vor dem Verschiffen', 'vor dem Shipping' ) ),
	array( 'en' => 'cycle time', 'de' => 'Taktzeit', 'not' => array( 'Zykluszeit', 'Zyklenzeit' ) ),
	array( 'en' => 'part-to-part cycle time', 'de' => 'Taktzeit von Teil zu Teil', 'not' => array( 'Teile-zu-Teile-Taktzeit', 'Takt-zu-Takt-Zykluszeit' ) ),
	array( 'en' => 'changeover', 'de' => 'Umrüstung', 'not' => array( 'Umbau', 'Umstellung' ) ),
	array( 'en' => 'part type', 'de' => 'Werkstücktyp', 'not' => array( 'Teiltyp', 'Teiletyp' ) ),
	array( 'en' => 'repeatability', 'de' => 'Wiederholgenauigkeit', 'not' => array( 'Repetierbarkeit', 'Wiederholungsfähigkeit' ) ),
	array( 'en' => 'accuracy and repeatability', 'de' => 'Genauigkeit und Wiederholgenauigkeit', 'not' => array( 'Genauigkeit und Wiederholbarkeit', 'Präzision und Wiederholbarkeit' ) ),
	array( 'en' => 'vibration analysis', 'de' => 'Schwingungsanalyse', 'not' => array( 'Vibrationsanalyse' ) ),
	array( 'en' => 'operator', 'de' => 'Bediener', 'not' => array( 'Operatoren', 'Maschinenoperator' ) ),
	array( 'en' => 'operator-free', 'de' => 'bedienerlos', 'not' => array( 'bedienerfrei', 'bedienungsfrei' ) ),
	array( 'en' => 'minimal operator interaction', 'de' => 'minimaler Bedieneraufwand', 'not' => array( 'minimale Bedienerinteraktion', 'minimale Interaktion des Bedieners' ) ),
	array( 'en' => 'automatic loading', 'de' => 'automatische Beschickung', 'not' => array( 'automatisches Laden', 'automatische Beladung' ) ),
	array( 'en' => 'fully automated', 'de' => 'vollautomatisch', 'not' => array( 'voll automatisiert', 'komplett automatisiert' ) ),
	array( 'en' => 'accept a wide range of products', 'de' => 'für ein breites Spektrum an Produkten und Modellen ausgelegt', 'not' => array( 'akzeptieren eine breite Palette', 'akzeptieren ein breites Spektrum', 'nehmen eine breite Palette' ) ),
	array( 'en' => 'almost completely automated', 'de' => 'nahezu vollautomatisch', 'not' => array( 'fast vollständig automatisiert', 'beinahe komplett automatisiert' ) ),
	array( 'en' => 'production line', 'de' => 'Fertigungslinie', 'not' => array( 'Herstellungslinie', 'Produktionsleitung' ) ),
	array( 'en' => 'assembly and test', 'de' => 'Montage und Prüfung', 'not' => array( 'Montage und Test', 'Baugruppe und Test' ) ),
	array( 'en' => 'eddy current', 'de' => 'Wirbelstrom', 'not' => array( 'Strudelstrom', 'Wirbelströmung' ) ),
	array( 'en' => 'eddy current testing', 'de' => 'Wirbelstromprüfung', 'not' => array( 'Wirbelstromtest', 'Wirbelstromtesten' ) ),
	array( 'en' => 'ultrasonic testing', 'de' => 'Ultraschallprüfung', 'not' => array( 'Ultraschalltest', 'Ultraschalltesten' ) ),
	array( 'en' => 'surface wave', 'de' => 'Oberflächenwelle', 'not' => array( 'Surface-Wave', 'Flächenwelle' ) ),
	array( 'en' => 'demagnetizing unit', 'de' => 'Entmagnetisierungsgerät', 'not' => array( 'Entmagnetisierungseinheit', 'Demagnetisierungseinheit' ) ),
	array( 'en' => 'industrial roll', 'de' => 'Industriewalze', 'not' => array( 'Industrierolle' ) ),
	array( 'en' => 'paper roll', 'de' => 'Papierwalze', 'not' => array( 'Papierrolle' ) ),
	array( 'en' => 'refrigerant recovery', 'de' => 'Kältemittelrückgewinnung', 'not' => array( 'Kältemittelwiederherstellung', 'Kältemittelbergung' ) ),
	array( 'en' => 'helium recovery', 'de' => 'Heliumrückgewinnung', 'not' => array( 'Heliumwiederherstellung', 'Heliumbergung' ) ),
	array( 'en' => 'recovery rate', 'de' => 'Absaugleistung', 'not' => array( 'Rückgewinnungsrate', 'Wiederherstellungsrate' ) ),
	array( 'en' => 'evacuation', 'de' => 'Evakuierung', 'not' => array( 'Räumung', 'Evakuation' ) ),
	array( 'en' => 'air handling unit', 'de' => 'RLT-Gerät', 'not' => array( 'Luftbehandlungseinheit', 'Luftaufbereitungseinheit' ) ),
	array( 'en' => 'Technical Specifications', 'de' => 'Technische Daten', 'not' => array( 'Technische Spezifikationen', 'Technische Angaben' ) ),
	array( 'en' => 'Not applicable', 'de' => '–', 'not' => array( 'Nicht zutreffend' ) ),
	array( 'en' => 'power requirement', 'de' => 'Anschlussleistung', 'not' => array( 'Stromanschluss', 'Strombedarf' ) ),
	array( 'en' => 'working pressure', 'de' => 'Arbeitsdruck', 'not' => array( 'Arbeitsdruckwert', 'Betriebsdruckwert' ) ),
	array( 'en' => 'flow rate', 'de' => 'Volumenstrom', 'not' => array( 'Flussrate', 'Fließrate' ) ),
	array( 'en' => 'rotational speed', 'de' => 'Drehzahl', 'not' => array( 'Rotationsgeschwindigkeit', 'Drehgeschwindigkeit' ) ),
	array( 'en' => 'spindle speed', 'de' => 'Spindeldrehzahl', 'not' => array( 'Spindelgeschwindigkeit' ) ),
	array( 'en' => 'motor speed', 'de' => 'Motordrehzahl', 'not' => array( 'Motorgeschwindigkeit' ) ),
	array( 'en' => 'engine RPM', 'de' => 'Motordrehzahl', 'not' => array( 'Motor-U/min', 'Motor-Drehzahl' ) ),
	array( 'en' => 'rpm', 'de' => 'U/min', 'not' => array( 'obr/min', 'Umdrehungen/Minute' ) ),
	array( 'en' => 'MPa', 'de' => 'bar', 'not' => array( 'Megapascal' ) ),
	array( 'en' => 'passenger car', 'de' => 'Pkw', 'not' => array( 'Passagierauto', 'Passagierfahrzeug', 'Personenauto' ) ),
	array( 'en' => 'powertrain', 'de' => 'Antriebsstrang', 'not' => array( 'Powertrain', 'Leistungsstrang' ) ),
	array( 'en' => 'e-drive', 'de' => 'E-Antrieb', 'not' => array( 'E-Drive', 'Elektro-Drive' ) ),
	array( 'en' => 'pulp and paper', 'de' => 'Zellstoff- und Papierindustrie', 'not' => array( 'Pulpe und Papier', 'Brei und Papier' ) ),
	array( 'en' => 'field service', 'de' => 'Vor-Ort-Service', 'not' => array( 'Feldservice', 'Felddienst' ) ),
	array( 'en' => 'remote diagnostics', 'de' => 'Ferndiagnose', 'not' => array( 'Remote-Diagnose', 'Remote-Diagnostik' ) ),
	array( 'en' => 'spare parts', 'de' => 'Ersatzteile', 'not' => array( 'Reserveteile', 'Ersatzkomponenten' ) ),
	array( 'en' => 'machine health', 'de' => 'Maschinenzustand', 'not' => array( 'Maschinengesundheit' ) ),
	array( 'en' => 'predictive maintenance', 'de' => 'vorausschauende Instandhaltung', 'not' => array( 'prädiktive Wartung', 'prädiktive Instandhaltung' ) ),
	array( 'en' => 'business unit', 'de' => 'Geschäftsbereich', 'not' => array( 'Geschäftseinheit', 'Business Unit' ) ),
	array( 'en' => 'improve performance, profitability, and quality', 'de' => 'Leistung, Wirtschaftlichkeit und Qualität steigern', 'not' => array( 'Performance, Profitabilität und Qualität verbessern', 'Leistung, Profitabilität und Qualität verbessern' ) ),
	array( 'en' => 'automated diagnostic, inspection, assembly and test systems', 'de' => 'automatisierte Diagnose-, Inspektions-, Montage- und Prüfsysteme', 'not' => array( 'automatisierte diagnostische', 'Montage- und Testsysteme' ) ),
	array( 'en' => 'leading global provider', 'de' => 'einer der weltweit führenden Anbieter', 'not' => array( 'ein führender globaler Anbieter', 'globaler Marktführer' ) ),
	array( 'en' => 'across a wide range of industries', 'de' => 'in zahlreichen Branchen', 'not' => array( 'über eine breite Palette von Branchen', 'in einem breiten Spektrum von Industrien' ) ),
	array( 'en' => 'designed and built', 'de' => 'konstruiert und gefertigt', 'not' => array( 'entworfen und gebaut', 'designt und gebaut' ) ),
	array( 'en' => 'custom-built', 'de' => 'kundenspezifisch gefertigt', 'not' => array( 'maßgeschneidert gebaut', 'individuell gebaut' ) ),
	array( 'en' => 'second to none', 'de' => 'erstklassig', 'not' => array( 'unübertroffen', 'unerreicht', 'keinem anderen nachstehend' ) ),
	array( 'en' => 'unmatched', 'de' => 'herausragend', 'not' => array( 'unübertroffen', 'unerreicht', 'unvergleichlich' ) ),
	array( 'en' => 'industry-leading', 'de' => 'erstklassig', 'not' => array( 'branchenführend', 'branchenweit führend' ) ),
	array( 'en' => 'industry-leading cycle times', 'de' => 'besonders kurze Taktzeiten', 'not' => array( 'branchenführende Taktzeiten', 'branchenführende Zykluszeiten' ) ),
	array( 'en' => 'Key Features', 'de' => 'Leistungsmerkmale', 'not' => array( 'Wichtige Funktionen', 'Wichtigste Funktionen', 'Hauptfunktionen' ) ),
	array( 'en' => 'key features include', 'de' => 'Zu den Leistungsmerkmalen zählen', 'not' => array( 'Zu den wichtigsten Funktionen zählen', 'Zu den Hauptfunktionen zählen', 'Wichtige Funktionen umfassen' ) ),
	array( 'en' => 'What are the key features of', 'de' => 'Was zeichnet … aus?', 'not' => array( 'Was sind die wichtigsten Funktionen', 'Was sind die Hauptfunktionen', 'Welche Funktionen bietet' ) ),
	array( 'en' => 'Selected Capabilities', 'de' => 'Highlights', 'not' => array( 'Ausgewählte Kompetenzen', 'Ausgewählte Fähigkeiten' ) ),
	array( 'en' => 'Overview', 'de' => 'Übersicht', 'not' => array( 'Überschau', 'Gesamtansicht' ) ),
	array( 'en' => 'Frequently Asked Questions', 'de' => 'Häufig gestellte Fragen', 'not' => array( 'Oft gestellte Fragen', 'Häufig gefragte Fragen' ) ),
	array( 'en' => 'Related Products', 'de' => 'Ähnliche Produkte', 'not' => array( 'Verwandte Produkte', 'Zugehörige Produkte' ) ),
	array( 'en' => 'Related Resources', 'de' => 'Weitere Ressourcen', 'not' => array( 'Verwandte Ressourcen' ) ),
	array( 'en' => 'Request a quote', 'de' => 'Angebot anfordern', 'not' => array( 'Zitat anfordern', 'Kostenvoranschlag anfordern' ) ),
	array( 'en' => 'Contact our engineering team for a custom quote or technical consultation regarding', 'de' => 'Für ein individuelles Angebot oder eine technische Beratung zu … wenden Sie sich an unser Ingenieurteam', 'not' => array( 'Kontaktieren Sie unser Engineering-Team', 'benutzerdefiniertes Angebot' ) ),
	array( 'en' => 'engineering team', 'de' => 'Ingenieurteam', 'not' => array( 'Engineering-Team', 'Technikteam' ) ),
	array( 'en' => 'At CIMAT, we offer', 'de' => 'CIMAT bietet', 'not' => array( 'Bei CIMAT bieten wir', 'Bei CIMAT bieten wir Ihnen' ) ),
	array( 'en' => 'At CIMAT, we manufacture', 'de' => 'CIMAT fertigt', 'not' => array( 'Bei CIMAT fertigen wir', 'Bei CIMAT fertigen und liefern wir' ) ),
);
