<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * German term base (en -> de). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Source: PL100 root causes + live /de/ sampling 2026-09-25.
 */
return array(
	array( 'en' => '*', 'de' => 'The whole site addresses the reader with the formal Sie, in every slot: body copy, headings, eyebrows, ALL-CAPS bands, form labels, placeholders, alt and aria text, the <title>, the meta description, og: tags and JSON-LD. Sie, Ihr, Ihre, Ihnen are capitalised whenever they address the reader; a du or ihr form never appears anywhere, at any length, including short CTAs and metadata. All nouns are capitalised and compounds are written as one word or fully hyphenated through a proper name. BUTTONS AND LINK LABELS follow German web-UI convention: they keep the verb of the English and take the bare infinitive or a noun phrase, never a du-imperative and never a conjugated sentence: „Browse catalog“ is Katalog durchsuchen, „Download“ is Herunterladen, „Request a demo“ is Demo vereinbaren, „Read the article“ is Artikel lesen, „Log in to Ascentialytics“ is Bei Ascentialytics anmelden. Never flatten a verb label into a bare noun (Katalog, Download, Demo-Anfrage are wrong for those), and never put a possessive in a label (Schutzen Sie Ihre Investition is wrong; Investition schutzen is right). The single established Sie-imperative exception the site already uses sitewide is the contact CTA Kontaktieren Sie uns and Mit einem Experten sprechen. Everything that is not a control label — prose, headings, questions, metadata — addresses the reader only as Sie.', 'not' => array( 'Du', 'Dein', 'Deine', 'Deinen', 'Deinem', 'Deiner', 'Deines', 'dein', 'deine', 'deinen', 'deinem', 'deiner', 'dich', 'dir', 'Dich', 'Dir', 'euch', 'Euch', 'euer', 'Euer', 'eure', 'Eure', 'euren', 'eurem', 'eurer', 'hast', 'kannst', 'willst', 'musst', 'bist', 'brauchst', 'möchtest', 'weisst', 'weißt', 'habt', 'könnt', 'wollt', 'müsst', 'seid', 'wisst', 'Entdecke', 'Erfahre', 'Kontaktiere', 'Melde', 'Fordere', 'Klicke', 'Sieh', 'Buche', 'Vereinbare', 'Suche dir' ) ),
	array( 'en' => '20-high mill', 'de' => 'Zwanzigwalzen-Walzwerk', 'not' => array( '20er-Walzwerk', 'zwanzigseitiges Walzwerk' ) ),
	array( 'en' => 'six-high mill', 'de' => 'Sechswalzen-Walzwerk', 'not' => array( 'Sechser-Walzwerk', 'sechsseitiges Walzwerk' ) ),
	array( 'en' => '3-jaw chuck', 'de' => 'Dreibackenfutter', 'not' => array( 'Dreiklauenfutter', 'dreiteiliges Futter' ) ),
	array( 'en' => 'A DESIGN', 'de' => 'A DESIGN', 'not' => array( 'DESIGN A', 'ENTWURF A' ) ),
	array( 'en' => 'B LOGO', 'de' => 'B LOGO', 'not' => array( 'LOGO B', 'B-Zeichen' ) ),
	array( 'en' => 'active part probing', 'de' => 'aktive Werkstückmessung', 'not' => array( 'aktives Sondieren', 'aktive Teileabtastung' ) ),
	array( 'en' => 'actuation systems', 'de' => 'Aktuatoriksysteme', 'not' => array( 'Betätigungssysteme', 'Aktivierungssysteme' ) ),
	array( 'en' => 'adaptive speed control', 'de' => 'adaptive Drehzahlregelung', 'not' => array( 'adaptive Geschwindigkeitskontrolle', 'adaptive Geschwindigkeitsregelung' ) ),
	array( 'en' => 'advanced driver assistance systems (ADAS)', 'de' => 'Fahrerassistenzsysteme (ADAS)', 'not' => array( 'fortschrittliche Fahrerunterstützungssysteme', 'erweiterte Fahrerassistenzsysteme' ) ),
	array( 'en' => 'ADAS alignment', 'de' => 'ADAS-Kalibrierung', 'not' => array( 'ADAS-Ausrichtung', 'ADAS-Vermessung' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'de' => 'ADVANCING THE MACHINE', 'not' => array( 'DIE MASCHINE VORANBRINGEN', 'FORTSCHRITT DER MASCHINE' ) ),
	array( 'en' => 'air cycle machines', 'de' => 'Luftkältemaschinen', 'not' => array( 'Luftzyklusmaschinen', 'Luftkreislaufmaschinen' ) ),
	array( 'en' => 'anchoring', 'de' => 'Verankerung', 'not' => array( 'Ankerung' ) ),
	array( 'en' => 'aperture plate', 'de' => 'Blendenplatte', 'not' => array( 'Öffnungsplatte', 'Aperturplatte' ) ),
	array( 'en' => 'applications', 'de' => 'Anwendungen', 'not' => array( 'Applikationen', 'Einsatzapplikationen' ) ),
	array( 'en' => 'armature', 'de' => 'Anker', 'not' => array( 'Armatur' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'de' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDIZIN & LEBENSWISSENSCHAFTEN', 'ASCENTIAL MEDIZINTECHNIK & LIFE SCIENCES' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'de' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Prüf- und Messtechnik', 'Ascential Test- und Messtechnik' ) ),
	array( 'en' => 'Ask Burke Porter', 'de' => 'Ask Burke Porter', 'not' => array( 'Fragen Sie Burke Porter', 'Frag Burke Porter' ) ),
	array( 'en' => 'associate attorney', 'de' => 'angestellter Rechtsanwalt', 'not' => array( 'Rechtsanwaltsgehilfe', 'Anwaltsassistent' ) ),
	array( 'en' => 'audit stations', 'de' => 'Auditstationen', 'not' => array( 'Kontrollstationen', 'Revisionsstationen' ) ),
	array( 'en' => 'automated handling cells', 'de' => 'automatisierte Handhabungszellen', 'not' => array( 'automatisierte Umschlagzellen', 'Handlingzellen' ) ),
	array( 'en' => 'backhoe', 'de' => 'Baggerlader', 'not' => array( 'Heckbagger', 'Baggerlastwagen' ) ),
	array( 'en' => 'baler', 'de' => 'Ballenpresse', 'not' => array( 'Presswerk', 'Ballenmaschine' ) ),
	array( 'en' => 'round baler', 'de' => 'Rundballenpresse', 'not' => array(  ) ),
	array( 'en' => 'square baler', 'de' => 'Quaderballenpresse', 'not' => array( 'Quadratballenpresse', 'quadratische Ballenpresse' ) ),
	array( 'en' => 'bead breaking', 'de' => 'Wulstabdrücken', 'not' => array( 'Perlenbrechen', 'Reifenwulstbruch' ) ),
	array( 'en' => 'bearers', 'de' => 'Auflagerollen', 'not' => array( 'Träger', 'Auflagebänder' ) ),
	array( 'en' => 'bearing center lines', 'de' => 'Lagermittellinien', 'not' => array( 'Lagerzentrierlinien', 'Zapfenachsen' ) ),
	array( 'en' => 'bearing life', 'de' => 'Lagerlebensdauer', 'not' => array( 'Lagerlaufzeit' ) ),
	array( 'en' => 'blade', 'de' => 'Schar', 'not' => array( 'Klinge', 'Messerbalken' ) ),
	array( 'en' => 'blank ECM', 'de' => 'unprogrammiertes ECM', 'not' => array( 'leeres ECM', 'blankes ECM' ) ),
	array( 'en' => 'blast furnace', 'de' => 'Hochofen', 'not' => array( 'Schmelzofen', 'Gebläseofen' ) ),
	array( 'en' => 'blowers', 'de' => 'Gebläse', 'not' => array(  ) ),
	array( 'en' => 'fan', 'de' => 'Lüfter', 'not' => array( 'Windrad', 'Flügelrad' ) ),
	array( 'en' => 'bore axis alignment', 'de' => 'Bohrachsenausrichtung', 'not' => array( 'Bohrungsachsen-Justage' ) ),
	array( 'en' => 'boreless compressor wheel', 'de' => 'Verdichterrad ohne Zentralbohrung', 'not' => array( 'borelloses Verdichterrad', 'borellose Verdichterlaufräder' ) ),
	array( 'en' => 'boring', 'de' => 'Ausdrehen', 'not' => array(  ) ),
	array( 'en' => 'boring drill', 'de' => 'Horizontalbohrgerät', 'not' => array( 'Bohrbohrer', 'Bohrmaschine' ) ),
	array( 'en' => 'branch', 'de' => 'Bereich', 'not' => array( 'Filiale', 'Zweigstelle' ) ),
	array( 'en' => 'Bristol', 'de' => 'Bristol', 'not' => array(  ) ),
	array( 'en' => 'built to last', 'de' => 'auf Langlebigkeit ausgelegt', 'not' => array( 'gebaut um zu halten', 'für die Ewigkeit gebaut' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'de' => 'Burke E. Porter Machinery', 'not' => array( 'Burke E. Porter Maschinenbau', 'Burke Porter Maschinen' ) ),
	array( 'en' => 'Burke Porter Group', 'de' => 'Burke Porter Group', 'not' => array( 'Burke-Porter-Gruppe', 'Gruppe Burke Porter' ) ),
	array( 'en' => 'burst proof protection', 'de' => 'Berstschutz', 'not' => array( 'Druckentlastungsschutz', 'Explosionsschutz', 'berstsicherer Schutz' ) ),
	array( 'en' => 'calibration target', 'de' => 'Kalibriertafel', 'not' => array( 'Kalibrierungsziel', 'Zieltafelhalter' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'de' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Kalibrierung als Service™', 'Kalibrierung-als-Dienstleistung™' ) ),
	array( 'en' => 'capital equipment', 'de' => 'Investitionsgüter', 'not' => array( 'Kapitalausrüstung', 'Kapitalgüterausrüstung' ) ),
	array( 'en' => 'cargo loading systems', 'de' => 'Frachtladesysteme', 'not' => array( 'Ladungssysteme', 'Cargo-Lade-Systeme' ) ),
	array( 'en' => 'chassis dynamometer', 'de' => 'Rollenprüfstand', 'not' => array( 'Fahrwerksprüfstand', 'Fahrwerks-Leistungsprüfstand', 'Chassis-Dynamometer' ) ),
	array( 'en' => 'chip vacuum', 'de' => 'Spanabsaugung', 'not' => array( 'Späne-Staubsauger', 'Chipsauger' ) ),
	array( 'en' => 'clay gun', 'de' => 'Stichlochstopfmaschine', 'not' => array( 'Tonerdichtung', 'Tonpistole', 'Maschine zum Formen von Lehm' ) ),
	array( 'en' => 'CMT-TR Polimer', 'de' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR Polymer', 'Polymer-Rotor-Auswuchtmaschine' ) ),
	array( 'en' => 'cold pilger mill', 'de' => 'Kaltpilgerwalzwerk', 'not' => array( 'Kaltpilgermühle', 'kalte Pilgerwalze' ) ),
	array( 'en' => 'collet chuck', 'de' => 'Spannzangenfutter', 'not' => array( 'Klemmfutter', 'Kollettfutter' ) ),
	array( 'en' => 'combine', 'de' => 'Mähdrescher', 'not' => array( 'Kombinierer', 'Erntekombination' ) ),
	array( 'en' => 'commercial vehicle', 'de' => 'Nutzfahrzeug', 'not' => array( 'Handelsfahrzeug', 'Geschäftsfahrzeug' ) ),
	array( 'en' => 'commissioning', 'de' => 'Inbetriebnahme', 'not' => array( 'Kommissionierung', 'Beauftragung' ) ),
	array( 'en' => 'Connect on LinkedIn', 'de' => 'Auf LinkedIn vernetzen', 'not' => array( 'Connect on LinkedIn', 'Verbinden auf LinkedIn' ) ),
	array( 'en' => 'control', 'de' => 'Steuerung', 'not' => array( 'Kontrolle' ) ),
	array( 'en' => 'control module', 'de' => 'Steuermodul', 'not' => array( 'Kontrollmodul', 'Regelbaustein' ) ),
	array( 'en' => 'controls', 'de' => 'Steuerungstechnik', 'not' => array( 'Kontrollen', 'Kontrollsysteme' ) ),
	array( 'en' => 'Core / Plus / Elite', 'de' => 'Core / Plus / Elite', 'not' => array( 'Basis, Plus, Elite', 'Standard, Plus, Elite' ) ),
	array( 'en' => 'Corporate Roles', 'de' => 'Unternehmensfunktionen', 'not' => array( 'Konzernrollen', 'Firmenrollen' ) ),
	array( 'en' => 'correction', 'de' => 'Korrektur', 'not' => array( 'Berichtigung' ) ),
	array( 'en' => 'correction point', 'de' => 'Korrekturpunkt', 'not' => array( 'Korrektionspunkt' ) ),
	array( 'en' => 'crankshaft lathe', 'de' => 'Kurbelwellendrehmaschine', 'not' => array( 'Pleueldrehmaschine' ) ),
	array( 'en' => 'Kamer van Koophandel (KvK)', 'de' => 'Handelskammer (KvK)', 'not' => array( 'Handelsregisterkammer', 'Industrie- und Handelskammer (KvK)' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'de' => 'Kruispuntbank van Ondernemingen', 'not' => array( 'Zentrale Unternehmensdatenbank', 'Unternehmensregister' ) ),
	array( 'en' => 'cushion testing', 'de' => 'Endlagendämpfungsprüfung', 'not' => array( 'Kissenprüfung', 'Polsterprüfung' ) ),
	array( 'en' => 'custom fixturing', 'de' => 'kundenspezifische Spannvorrichtungen', 'not' => array( 'Sonderbefestigungen', 'maßgeschneiderte Fixierung' ) ),
	array( 'en' => 'customer journey', 'de' => 'Customer Journey', 'not' => array( 'Kundenreise', 'Reise des Kunden', 'Stufen ihrer Reise' ) ),
	array( 'en' => 'Date:', 'de' => 'Datum:', 'not' => array( 'Daten:', 'Termin:' ) ),
	array( 'en' => 'deep hole drilling', 'de' => 'Tiefbohren', 'not' => array(  ) ),
	array( 'en' => 'defensible', 'de' => 'auditsicher', 'not' => array( 'verteidigungsfähig', 'vertretbar' ) ),
	array( 'en' => 'Deliverables', 'de' => 'Liefergegenstände', 'not' => array( 'Lieferbare', 'Lieferbares', 'Deliverables' ) ),
	array( 'en' => 'deployment', 'de' => 'Einführung', 'not' => array( 'Entfaltung', 'Truppenverlegung' ) ),
	array( 'en' => 'design', 'de' => 'Konstruktion', 'not' => array( 'Entwurf' ) ),
	array( 'en' => 'dial indicator', 'de' => 'Messuhr', 'not' => array( 'Zifferblattanzeiger', 'Skalenanzeiger' ) ),
	array( 'en' => 'disability insurance', 'de' => 'Berufsunfähigkeitsversicherung', 'not' => array( 'Invalidenrente', 'Behindertenversicherung' ) ),
	array( 'en' => 'discrete industries', 'de' => 'diskrete Fertigungsbranchen', 'not' => array( 'diskrete Industrien', 'einzelne Branchen' ) ),
	array( 'en' => 'draper header', 'de' => 'Bandschneidwerk', 'not' => array( 'Drapierschneidwerk', 'Vorhangschneidwerk' ) ),
	array( 'en' => 'drift', 'de' => 'Absinken', 'not' => array( 'Abdrift', 'Driften' ) ),
	array( 'en' => 'drivability', 'de' => 'Fahrbarkeit', 'not' => array( 'Lenkbarkeit', 'Fahrtüchtigkeit' ) ),
	array( 'en' => 'dual mass flywheel', 'de' => 'Zweimassenschwungrad', 'not' => array( 'Doppelmassenschwungrad', 'Zweimassenkupplung' ) ),
	array( 'en' => 'dynamometer', 'de' => 'Leistungsprüfstand', 'not' => array( 'Dynamometer', 'Kraftmesser' ) ),
	array( 'en' => 'eddy current technology', 'de' => 'Wirbelstromtechnik', 'not' => array( 'Strudelstromtechnik', 'aktuelle Technologie' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'de' => 'Funkenerosions-Texturierung (EDT)', 'not' => array( 'elektrische Entladungstexturierung', 'EDT-Aufrauung' ) ),
	array( 'en' => 'Email Disclosure', 'de' => 'E-Mail-Haftungsausschluss', 'not' => array( 'E-Mail-Offenlegung', 'E-Mail-Bekanntgabe' ) ),
	array( 'en' => 'EMC darkroom', 'de' => 'EMV-Absorberhalle', 'not' => array( 'EMV-Dunkelkammer', 'EMC-Dunkelraum' ) ),
	array( 'en' => 'end of line testing', 'de' => 'End-of-Line-Prüfung', 'not' => array( 'Endlinienprüfung', 'Prüfung am Bandende' ) ),
	array( 'en' => 'energy recuperation', 'de' => 'Energierückgewinnung', 'not' => array( 'Energierekuperation', 'Energieregeneration' ) ),
	array( 'en' => 'engine software loaders', 'de' => 'Programmiergeräte für Motorsoftware', 'not' => array( 'Motorsoftware-Lader', 'Motorenlader' ) ),
	array( 'en' => 'eRotor', 'de' => 'eRotor', 'not' => array( 'E-Rotor', 'Elektrorotor' ) ),
	array( 'en' => 'events & conferences', 'de' => 'Veranstaltungen & Konferenzen', 'not' => array( 'Ereignisse und Konferenzen', 'Events und Tagungen' ) ),
	array( 'en' => 'excavator', 'de' => 'Bagger', 'not' => array( 'Aushubmaschine', 'Ausgräber' ) ),
	array( 'en' => 'exhaust extraction', 'de' => 'Abgasabsaugung', 'not' => array( 'Abgasextraktion', 'Auspuffabsaugung' ) ),
	array( 'en' => 'factory floor', 'de' => 'Produktionshalle', 'not' => array( 'Fabrikboden', 'Fabrikfußboden' ) ),
	array( 'en' => 'failure rates', 'de' => 'Fehlerquoten', 'not' => array( 'Versagensquoten', 'Misserfolgsraten' ) ),
	array( 'en' => 'features', 'de' => 'Funktionen', 'not' => array( 'Features' ) ),
	array( 'en' => 'Featuring:', 'de' => 'Im Fokus:', 'not' => array( 'Featuring:', 'Mit dabei:' ) ),
	array( 'en' => 'field agents', 'de' => 'Außendiensttechniker', 'not' => array( 'Feldagenten', 'Vertreter' ) ),
	array( 'en' => 'field balancing', 'de' => 'Auswuchten am Einbauort', 'not' => array( 'Feldauswuchten', 'Auswuchten im Feld' ) ),
	array( 'en' => 'filler', 'de' => 'Füllstation', 'not' => array( 'Abfüller' ) ),
	array( 'en' => 'filler gun', 'de' => 'Füllpistole', 'not' => array( 'Füllerpistole', 'Dosierpistölchen' ) ),
	array( 'en' => 'final discharge', 'de' => 'Endentleerung', 'not' => array( 'Endabgabe', 'endgültige Entladung' ) ),
	array( 'en' => 'fine leak', 'de' => 'Feinleck', 'not' => array( 'feine Leckage', 'Feinundichtigkeit' ) ),
	array( 'en' => 'flexplate', 'de' => 'Mitnehmerscheibe', 'not' => array( 'Flexplatte', 'Flexscheibe' ) ),
	array( 'en' => 'fluid power', 'de' => 'Fluidtechnik', 'not' => array( 'Flüssigkeitskraft', 'Fluidkraft' ) ),
	array( 'en' => 'flywheel', 'de' => 'Schwungrad', 'not' => array( 'Schwungscheibe', 'Trägheitsrad' ) ),
	array( 'en' => 'footprint', 'de' => 'Stellfläche', 'not' => array( 'Fußabdruck', 'Platzbedarfsgröße' ) ),
	array( 'en' => 'For Immediate Release', 'de' => 'Zur sofortigen Veröffentlichung', 'not' => array( 'Für sofortige Freigabe', 'Zur sofortigen Freigabe' ) ),
	array( 'en' => 'forged rolls', 'de' => 'geschmiedete Walzen', 'not' => array( 'gegossene Walzen', 'Schmiedewalzen' ) ),
	array( 'en' => 'front strut', 'de' => 'Federbein', 'not' => array( 'Frontstrebe', 'vorderer Pfosten', 'vorderer Bremssattel' ) ),
	array( 'en' => 'gantry', 'de' => 'Portal', 'not' => array( 'Galgen', 'Brückengerüst' ) ),
	array( 'en' => 'gantry milling', 'de' => 'Portalfräsen', 'not' => array( 'Brückenfräsen', 'Torfräsen' ) ),
	array( 'en' => 'GDPR', 'de' => 'DSGVO', 'not' => array( 'GDPR', 'EU-Datenschutzgesetz' ) ),
	array( 'en' => 'gear shift calibration', 'de' => 'Schaltkalibrierung', 'not' => array( 'Getriebeverschiebungskalibrierung', 'Gangwechsel-Kalibration' ) ),
	array( 'en' => 'grinding wheel', 'de' => 'Schleifscheibe', 'not' => array( 'Mahlscheibe', 'Schleifrad' ) ),
	array( 'en' => 'gross leak test', 'de' => 'Grobleckprüfung', 'not' => array( 'Bruttoleckprüfung', 'Grobleckagetest' ) ),
	array( 'en' => 'gundrill', 'de' => 'Einlippenbohrer', 'not' => array( 'Gundrill', 'Gewehrbohrer' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'de' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Co. AG', 'H. Kleinknecht & Co. KG' ) ),
	array( 'en' => 'half case', 'de' => 'Halbgehäuse', 'not' => array( 'Halbschale', 'halber Fall' ) ),
	array( 'en' => 'hay mower', 'de' => 'Heumähwerk', 'not' => array( 'Heuschneider' ) ),
	array( 'en' => 'hazardous area', 'de' => 'explosionsgefährdeter Bereich', 'not' => array( 'Gefahrenbereich', 'gefährlicher Bereich' ) ),
	array( 'en' => 'health checks', 'de' => 'Zustandsprüfungen', 'not' => array( 'Gesundheitschecks', 'Gesundheitsprüfungen' ) ),
	array( 'en' => 'high production', 'de' => 'Großserienproduktion', 'not' => array( 'Hochproduktion', 'hohe Produktion' ) ),
	array( 'en' => 'high-volume production', 'de' => 'Großserienproduktion', 'not' => array( 'Hochvolumen-Fertigung', 'Großmengenproduktion', 'Hochvolumenproduktion' ) ),
	array( 'en' => 'high-mix, low-volume', 'de' => 'variantenreiche Kleinserienfertigung', 'not' => array( 'hoher Mix, geringes Volumen', 'Hochmix-Niedrigvolumen' ) ),
	array( 'en' => 'high-performance teams', 'de' => 'leistungsstarke Teams', 'not' => array( 'Teams mit hoher Leistung', 'Hochleistungsmannschaften' ) ),
	array( 'en' => 'higher-level control system', 'de' => 'übergeordnetes Steuerungssystem', 'not' => array( 'höheres Kontrollsystem', 'Leitsystem höherer Ebene' ) ),
	array( 'en' => 'HMU/FMU', 'de' => 'HMU/FMU', 'not' => array( 'hydraulische und pneumatische Geräte', 'Kraftstoffdosiereinheiten' ) ),
	array( 'en' => 'idle duration', 'de' => 'Leerlaufdauer', 'not' => array( 'Stillstandsdauer', 'Untätigkeitsdauer' ) ),
	array( 'en' => 'implements', 'de' => 'Anbaugeräte', 'not' => array( 'Implemente', 'Gerätschaften', 'Mobilgeräte' ) ),
	array( 'en' => 'mobile equipment', 'de' => 'mobile Arbeitsmaschinen', 'not' => array( 'Mobilgeräte', 'Mobilausrüstung' ) ),
	array( 'en' => 'Imprint', 'de' => 'Impressum', 'not' => array( 'Aufdruck', 'Prägung' ) ),
	array( 'en' => 'in a single clamping', 'de' => 'in einer Aufspannung', 'not' => array( 'in einer Klemmung', 'in einem Spannvorgang' ) ),
	array( 'en' => 'infeed', 'de' => 'Vorschub', 'not' => array( 'Einzug', 'Infeed' ) ),
	array( 'en' => 'infinitely variable', 'de' => 'stufenlos verstellbar', 'not' => array( 'unendlich variabel', 'endlos regelbar' ) ),
	array( 'en' => 'inline crankshaft', 'de' => 'Reihenkurbelwelle', 'not' => array( 'Inline-Kurbelwelle', 'Viertakt-Kurbelwelle' ) ),
	array( 'en' => 'inline dyno', 'de' => 'Inline-Leistungsprüfstand', 'not' => array( 'eingebauter Leistungsprüfstand', 'Reihenprüfstand' ) ),
	array( 'en' => 'insights', 'de' => 'Erkenntnisse', 'not' => array( 'Einblicke', 'Einsichten' ) ),
	array( 'en' => 'actionable insights', 'de' => 'verwertbare Erkenntnisse', 'not' => array( 'umsetzbare Einblicke', 'handlungsfähige Erkenntnisse' ) ),
	array( 'en' => 'expert insights', 'de' => 'Experteneinschätzungen', 'not' => array( 'Experteneinblicke', 'fachliche Einblicke' ) ),
	array( 'en' => 'instrument cluster', 'de' => 'Kombiinstrument', 'not' => array( 'Instrumentencluster', 'Armaturenbrett' ) ),
	array( 'en' => 'keg', 'de' => 'Fass', 'not' => array( 'Fässchen', 'Bierfaß' ) ),
	array( 'en' => 'keg finger holes', 'de' => 'Grifflöcher', 'not' => array( 'Fingerlöcher', 'Fasslöcher' ) ),
	array( 'en' => 'kinetostatics', 'de' => 'Kinetostatik', 'not' => array( 'Kinematik' ) ),
	array( 'en' => 'Labour & Travel', 'de' => 'Arbeitszeit & Reisekosten', 'not' => array( 'Arbeit und Reisen', 'Lohn und Fahrt' ) ),
	array( 'en' => 'landed cost model', 'de' => 'Landed-Cost-Modell', 'not' => array( 'Modell der gelandeten Kosten', 'Anlieferkostenmodell' ) ),
	array( 'en' => 'landing gear systems', 'de' => 'Fahrwerksysteme', 'not' => array( 'Landegestellsysteme', 'Landefahrwerksysteme' ) ),
	array( 'en' => 'leak detection', 'de' => 'Lecksuche', 'not' => array( 'Leckerkennung', 'Leckageerkennung', 'Leckagetestverfahren' ) ),
	array( 'en' => 'learning management system (LMS)', 'de' => 'Lernmanagementsystem (LMS)', 'not' => array( 'Lernverwaltungssystem', 'Lehrverwaltungssystem' ) ),
	array( 'en' => 'like-minded companies', 'de' => 'gleichgesinnte Unternehmen', 'not' => array( 'ähnlich denkende Firmen', 'Firmen mit ähnlichen Ansichten' ) ),
	array( 'en' => 'load capacity', 'de' => 'Tragfähigkeit', 'not' => array( 'Ladekapazität', 'Belastungskapazität' ) ),
	array( 'en' => 'LPM', 'de' => 'l/min', 'not' => array(  ) ),
	array( 'en' => 'lube & scavenge pumps', 'de' => 'Schmier- und Absaugpumpen', 'not' => array( 'Schmier- und Entlüftungspumpen', 'Spülpumpen' ) ),
	array( 'en' => 'lubrication', 'de' => 'Schmierung', 'not' => array( 'Ölwechsel', 'Einölung' ) ),
	array( 'en' => 'machine tools', 'de' => 'Werkzeugmaschinen', 'not' => array( 'Maschinenwerkzeuge', 'Bearbeitungsmaschinen' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'de' => 'Maschinenrichtlinie 2006/42/EG', 'not' => array( 'Maschinendirektive 2006/42/EG' ) ),
	array( 'en' => 'machining cell', 'de' => 'Bearbeitungszelle', 'not' => array( 'Maschinenzelle', 'Zerspanzelle' ) ),
	array( 'en' => 'machinist', 'de' => 'Zerspanungsmechaniker', 'not' => array( 'Maschinist', 'Maschinenführer' ) ),
	array( 'en' => 'maintenance contracts', 'de' => 'Wartungsverträge', 'not' => array( 'Instandhaltungskontrakte', 'Pflegeverträge' ) ),
	array( 'en' => 'marine', 'de' => 'Schifffahrt', 'not' => array( 'Marine', 'Meeresindustrie' ) ),
	array( 'en' => 'maximum rotor diameter', 'de' => 'maximaler Rotordurchmesser', 'not' => array( 'maximale Rotorgröße', 'größter Rotordurchmesser' ) ),
	array( 'en' => 'mental health care', 'de' => 'psychische Gesundheitsversorgung', 'not' => array( 'geistige Gesundheitspflege', 'Fernbetreuung' ) ),
	array( 'en' => 'mill roll', 'de' => 'Walze', 'not' => array( 'Mühlenwalze' ) ),
	array( 'en' => 'misalignment', 'de' => 'Fehlausrichtung', 'not' => array( 'Missausrichtung', 'Ausrichtungsmangel' ) ),
	array( 'en' => 'motor grader', 'de' => 'Motorgrader', 'not' => array( 'Straßenhobel', 'Bodenkopierer' ) ),
	array( 'en' => 'motorized clamping', 'de' => 'motorisches Spannen', 'not' => array( 'motorisierte Klemmung', 'Motorspannung' ) ),
	array( 'en' => 'MRO', 'de' => 'MRO', 'not' => array(  ) ),
	array( 'en' => 'mudding system', 'de' => 'Bohrspülungssystem', 'not' => array( 'Schlammsystem', 'Matschsystem' ) ),
	array( 'en' => 'naamloze vennootschap', 'de' => 'naamloze vennootschap', 'not' => array( 'Aktiengesellschaft', 'niederländische AG' ) ),
	array( 'en' => 'Name:', 'de' => 'Name:', 'not' => array(  ) ),
	array( 'en' => 'Netherlands', 'de' => 'Niederlande', 'not' => array( 'Holland' ) ),
	array( 'en' => 'non-rotating balancing machine', 'de' => 'nicht rotierende Auswuchtmaschine', 'not' => array( 'Auswuchtmaschine ohne Rotor', 'rotationsfreie Auswuchtmaschine' ) ),
	array( 'en' => 'Non-Rotate Systems', 'de' => 'Nicht rotierende Systeme', 'not' => array( 'Nicht-Rotier-Systeme', 'Rotationsfreie Systeme' ) ),
	array( 'en' => 'obsolescence management', 'de' => 'Obsoleszenzmanagement', 'not' => array( 'Veralterungsmanagement', 'Überalterungsmanagement' ) ),
	array( 'en' => 'off-highway', 'de' => 'Off-Highway', 'not' => array( 'Straßenverkehr', 'Geländeeinsatz' ) ),
	array( 'en' => 'oil drain', 'de' => 'Ölablass', 'not' => array( 'Entlüftungsöffnung', 'Ölabfluss' ) ),
	array( 'en' => 'operations', 'de' => 'Betriebsabläufe', 'not' => array( 'Operationen' ) ),
	array( 'en' => 'opportunities', 'de' => 'Chancen', 'not' => array( 'Opportunitäten', 'Gelegenheiten' ) ),
	array( 'en' => 'patented', 'de' => 'patentiert', 'not' => array( 'zum Patent angemeldet', 'patentwirksam' ) ),
	array( 'en' => 'pedestals', 'de' => 'Lagerböcke', 'not' => array( 'Podeste', 'Sockel' ) ),
	array( 'en' => 'peers', 'de' => 'Fachkollegen', 'not' => array( 'Gleichaltrige', 'Ebenbürtige' ) ),
	array( 'en' => 'performance', 'de' => 'Leistung', 'not' => array( 'Performanz', 'Durchführung' ) ),
	array( 'en' => 'personal information', 'de' => 'personenbezogene Daten', 'not' => array( 'persönliche Informationen', 'persönliche Daten' ) ),
	array( 'en' => 'personal data', 'de' => 'personenbezogene Daten', 'not' => array( 'persönliche Daten', 'Personendaten' ) ),
	array( 'en' => 'pinches & bruises', 'de' => 'Quetschungen & Druckstellen', 'not' => array( 'Kneifen und Blutergüsse', 'Prellungen und Quetschungen' ) ),
	array( 'en' => 'pinion gear', 'de' => 'Ritzel', 'not' => array( 'Zapfen', 'Stirnrad' ) ),
	array( 'en' => 'pins', 'de' => 'Stifte', 'not' => array( 'Zapfen', 'Nadeln' ) ),
	array( 'en' => 'power drive units', 'de' => 'Antriebseinheiten (PDU)', 'not' => array( 'Kraftantriebseinheiten', 'Leistungsantriebe' ) ),
	array( 'en' => 'Powered by', 'de' => 'Auf Basis von', 'not' => array( 'Angetrieben von', 'Angetrieben durch', 'Bereitgestellt von' ) ),
	array( 'en' => 'President', 'de' => 'President', 'not' => array( 'Präsident', 'Vorsitzender' ) ),
	array( 'en' => 'Board of Directors', 'de' => 'Board of Directors', 'not' => array( 'Vorstand', 'Verwaltungsrat' ) ),
	array( 'en' => 'Board Member', 'de' => 'Mitglied des Board of Directors', 'not' => array( 'Vorstandsmitglied', 'Aufsichtsratsmitglied' ) ),
	array( 'en' => 'Principal', 'de' => 'Principal', 'not' => array( 'Prinzipal', 'Hauptverantwortlicher' ) ),
	array( 'en' => 'Leadership', 'de' => 'Führungsteam', 'not' => array( 'Leiterschaft', 'Oberste Führungsebene' ) ),
	array( 'en' => 'pressurization', 'de' => 'Druckbeaufschlagung', 'not' => array( 'Pressurisierung', 'Druckbelüftung' ) ),
	array( 'en' => 'probe', 'de' => 'Prüfkopf', 'not' => array( 'Sonde', 'Messfühler' ) ),
	array( 'en' => 'probe alignment', 'de' => 'Prüfkopfausrichtung', 'not' => array( 'Sondenausrichtung', 'Sondenjustierung' ) ),
	array( 'en' => 'process recipe', 'de' => 'Prozessrezept', 'not' => array( 'Verfahrensrezeptur', 'Kochrezept' ) ),
	array( 'en' => 'propulsion & powertrain', 'de' => 'Antrieb & Antriebsstrang', 'not' => array( 'Antrieb und Antrieb', 'Vortrieb und Antriebsstrang' ) ),
	array( 'en' => 'power take-off (PTO)', 'de' => 'Zapfwelle (PTO)', 'not' => array( 'Kraftabnahme', 'Leistungsabnahmewelle' ) ),
	array( 'en' => 'pulley', 'de' => 'Riemenscheibe', 'not' => array( 'Flaschenzug', 'Keilriemen' ) ),
	array( 'en' => 'pump impeller', 'de' => 'Pumpenlaufrad', 'not' => array( 'Pumpenrad', 'Pumpenläufer' ) ),
	array( 'en' => 'punching', 'de' => 'Stanzen', 'not' => array( 'Lochen', 'Durchstoßen' ) ),
	array( 'en' => 'push and pull', 'de' => 'Vorschub und Rückzug', 'not' => array( 'Druck und Zug', 'Schieben und Ziehen' ) ),
	array( 'en' => 'thrust force', 'de' => 'Vorschubkraft', 'not' => array( 'Axialkraft', 'Druckkraft' ) ),
	array( 'en' => 'pullback force', 'de' => 'Rückzugskraft', 'not' => array( 'Zurückziehkraft', 'Rückholkraft' ) ),
	array( 'en' => 'reconditioning', 'de' => 'Aufarbeitung', 'not' => array( 'Renovierung', 'Sanierung' ) ),
	array( 'en' => 'refrigerant', 'de' => 'Kältemittel', 'not' => array( 'Kühlmittel', 'Kühlflüssigkeit', 'Frostschutzmittel' ) ),
	array( 'en' => 'refrigerant charging', 'de' => 'Kältemittelbefüllung', 'not' => array( 'Kältemittelladung', 'Kältemittelbeladung', 'Kältemittelaufladung' ) ),
	array( 'en' => 'refrigeration', 'de' => 'Kältetechnik', 'not' => array( 'Kühlung', 'Refrigeration' ) ),
	array( 'en' => 'Register', 'de' => 'Register', 'not' => array( 'Jetzt registrieren', 'Registrieren' ) ),
	array( 'en' => 'Registered office', 'de' => 'Sitz der Gesellschaft', 'not' => array( 'Eingetragenes Büro', 'registriertes Büro' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'de' => 'Aufarbeitungs- und Instandsetzungsbetriebe', 'not' => array( 'Wiederhersteller und Umbauer', 'Remanufakturbetriebe' ) ),
	array( 'en' => 'remarketers', 'de' => 'Flottenvermarkter', 'not' => array( 'Remarketer', 'Wiederverkäufer' ) ),
	array( 'en' => 'reportable', 'de' => 'belegbar', 'not' => array( 'berichtbar', 'reportierbar' ) ),
	array( 'en' => 'represent', 'de' => 'abbilden', 'not' => array( 'repräsentieren', 'vertreten' ) ),
	array( 'en' => 'residual unbalance', 'de' => 'Restunwucht', 'not' => array( 'Restungleichgewicht', 'verbleibende Unwucht', 'Restunbalance' ) ),
	array( 'en' => 'responsive', 'de' => 'reaktionsschnell', 'not' => array( 'responsiv', 'ansprechbar' ) ),
	array( 'en' => 'restbus simulation', 'de' => 'Restbussimulation', 'not' => array( 'Rest-Bus-Simulation', 'Residualbussimulation' ) ),
	array( 'en' => 'retaining rollers', 'de' => 'Niederhalterollen', 'not' => array( 'Rückhaltewalzen', 'Retentionsrollen' ) ),
	array( 'en' => 'right-shoring', 'de' => 'Right-Shoring', 'not' => array( 'Richtiges Shoring', 'Standortoptimierung' ) ),
	array( 'en' => 'roll inspection', 'de' => 'Walzenprüfung', 'not' => array( 'Rollenprüfung', 'Rollenkontrolle' ) ),
	array( 'en' => 'Roll Shop Technologies', 'de' => 'Walzenschleiferei-Technologien', 'not' => array( 'Roll Shop Technologies', 'Walzwerkstatt-Technologien' ) ),
	array( 'en' => 'roll grinder', 'de' => 'Walzenschleifmaschine', 'not' => array( 'Altschleifen' ) ),
	array( 'en' => 'rollers', 'de' => 'Rollen', 'not' => array(  ) ),
	array( 'en' => 'roller brake tester', 'de' => 'Rollenbremsprüfstand', 'not' => array( 'Walzenbremsprüfstand', 'Rollenbremsentester' ) ),
	array( 'en' => 'rolling torque', 'de' => 'Rollmoment', 'not' => array( 'Walzmoment', 'Wellendrehmoment' ) ),
	array( 'en' => 'rotary diamond dressing', 'de' => 'Abrichten mit Diamantrolle', 'not' => array( 'Diamantdressieren', 'rotierendes Diamantdressing' ) ),
	array( 'en' => 'rotor wing aircraft', 'de' => 'Drehflügler', 'not' => array( 'Propellerflugzeuge', 'Rotorflügelflugzeuge' ) ),
	array( 'en' => 'sealed assembly', 'de' => 'dichte Baugruppe', 'not' => array( 'versiegelte Baugruppe', 'abgedichtete Montage' ) ),
	array( 'en' => 'seamless link', 'de' => 'nahtlose Verknüpfung', 'not' => array( 'unnahtbare Verbindung', 'direkter Verbinder' ) ),
	array( 'en' => 'service professional', 'de' => 'Servicespezialist', 'not' => array( 'Service-Fachmann', 'Serviceprofi' ) ),
	array( 'en' => 'setup cycles', 'de' => 'Einrichtzyklen', 'not' => array( 'Aufbauzyklen', 'Montagezyklen' ) ),
	array( 'en' => 'single bay', 'de' => 'Einzelplatz', 'not' => array( 'Einzelkammer', 'eine Bucht' ) ),
	array( 'en' => 'single cylinder crankshaft', 'de' => 'Einzylinder-Kurbelwelle', 'not' => array( 'Einspur-Kurbelwelle', 'Einspurwelle' ) ),
	array( 'en' => 'single station', 'de' => 'Einzelstation', 'not' => array( 'Einkammer', 'Einzelbucht' ) ),
	array( 'en' => 'multi station', 'de' => 'Mehrstationen', 'not' => array( 'Multistation', 'Mehrkammer' ) ),
	array( 'en' => 'site visit', 'de' => 'Vor-Ort-Besuch', 'not' => array( 'Baustellenbesuch', 'Geländebesuch' ) ),
	array( 'en' => 'sniffing pliers', 'de' => 'Schnüffelsonde', 'not' => array( 'Schnüffelzange', 'Riechzange' ) ),
	array( 'en' => 'sniffer', 'de' => 'Schnüffelsonde', 'not' => array( 'Sniffer', 'Riecher' ) ),
	array( 'en' => 'snubber', 'de' => 'Hydraulikdämpfer', 'not' => array( 'Schnubber', 'Drosselelement' ) ),
	array( 'en' => 'soak time', 'de' => 'Konditionierzeit', 'not' => array( 'Einweichzeit', 'Tränkzeit' ) ),
	array( 'en' => 'spalls', 'de' => 'Ausbrüche', 'not' => array( 'Abblätterungen', 'Spallierungen' ) ),
	array( 'en' => 'special test facilities', 'de' => 'Sonderprüfstände', 'not' => array( 'spezielle Testeinrichtungen', 'Spezialtestanlagen' ) ),
	array( 'en' => 'spin testing machine', 'de' => 'Schleuderprüfmaschine', 'not' => array( 'Spinnprüfmaschine', 'Drehprüfmaschine' ) ),
	array( 'en' => 'spin tester', 'de' => 'Schleuderprüfstand', 'not' => array( 'Spin-Tester', 'Spinnprüfstand' ) ),
	array( 'en' => 'Spin Testing', 'de' => 'Schleuderprüfung', 'not' => array( 'Spinnprüfung', 'Spin-Testing' ) ),
	array( 'en' => 'sprayers', 'de' => 'Feldspritzen', 'not' => array( 'Zerstäuber', 'Sprüher', 'Spritzpistolen' ) ),
	array( 'en' => 'squeak & rattle testing', 'de' => 'Knarz- und Klapperprüfung', 'not' => array( 'Quietsch- und Rassel-Test', 'Knirsch- und Rattertest' ) ),
	array( 'en' => 'stand-alone machine', 'de' => 'Einzelmaschine', 'not' => array( 'Stand-alone-Maschine', 'autarke Maschine' ) ),
	array( 'en' => 'Standardization at scale', 'de' => 'Standardisierung im großen Maßstab', 'not' => array( 'Standardisierung in Größe', 'Skalierte Normierung' ) ),
	array( 'en' => 'strip', 'de' => 'Band', 'not' => array( 'Blech', 'Streifen' ) ),
	array( 'en' => 'Strip Lines', 'de' => 'Bandlinien', 'not' => array( 'Streifenlinien', 'Bandstreifenlinien' ) ),
	array( 'en' => 'superabrasives', 'de' => 'Superhartstoffe', 'not' => array( 'Superabrasive', 'Superschleifmittel' ) ),
	array( 'en' => 'surface separations', 'de' => 'Oberflächenablösungen', 'not' => array( 'Oberflächentrennungen', 'Oberflächenabtrennungen' ) ),
	array( 'en' => 'subsurface defects', 'de' => 'oberflächennahe Fehler', 'not' => array( 'Unterflächenfehler', 'Subsurface-Fehler' ) ),
	array( 'en' => 'tap hole', 'de' => 'Stichloch', 'not' => array(  ) ),
	array( 'en' => 'tapered roller bearing', 'de' => 'Kegelrollenlager', 'not' => array( 'Zylinderrollenlager', 'konisches Rollenlager' ) ),
	array( 'en' => 'tariffs', 'de' => 'Zölle', 'not' => array( 'Tarife', 'Gebührenordnungen' ) ),
	array( 'en' => 'tension', 'de' => 'Zugkraft', 'not' => array( 'Verspannung', 'Spannkraftwert' ) ),
	array( 'en' => 'third member', 'de' => 'Achsmittelstück', 'not' => array( 'dritter Teil', 'drittes Glied' ) ),
	array( 'en' => 'tin plating', 'de' => 'Verzinnung', 'not' => array( 'Verzinkung', 'Zinnauftrag' ) ),
	array( 'en' => 'TIR / radial run-out', 'de' => 'Rundlaufabweichung (TIR)', 'not' => array( 'TIR-Lauf', 'radialer Auslauf' ) ),
	array( 'en' => 'tire inflator', 'de' => 'Reifenfüllstation', 'not' => array( 'Reifenpumpe', 'Reifenaufpumper' ) ),
	array( 'en' => 'torque vectoring', 'de' => 'Torque Vectoring', 'not' => array( 'Drehmomentvektorisierung', 'Momentenvektorisierung' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'de' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'GESAMTLÖSUNGEN FÜR DIE KOMMERZIALISIERUNG', 'KOMPLETTE VERMARKTUNGSLÖSUNGEN' ) ),
	array( 'en' => 'traceable tests', 'de' => 'rückführbare Prüfungen', 'not' => array( 'nachverfolgbare Tests', 'verfolgbare Prüfungen' ) ),
	array( 'en' => 'tracer gas', 'de' => 'Prüfgas', 'not' => array( 'Spurgas', 'Markergas' ) ),
	array( 'en' => 'traction battery', 'de' => 'Traktionsbatterie', 'not' => array( 'Zugbatterie', 'Antriebsakku' ) ),
	array( 'en' => 'transmission', 'de' => 'Getriebe', 'not' => array( 'Übertragung', 'Transmission' ) ),
	array( 'en' => 'gearbox', 'de' => 'Getriebe', 'not' => array( 'Schaltkasten' ) ),
	array( 'en' => 'turbo calibration', 'de' => 'Turbolader-Kalibrierung', 'not' => array( 'Turboauswuchten', 'Turbo-Abstimmung' ) ),
	array( 'en' => 'turbocharger flow bench', 'de' => 'Turbolader-Strömungsprüfstand', 'not' => array( 'Durchflussprüfanlage', 'Durchsatzprüfbank', 'Strömungsprüfbank' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'de' => 'Dynamischer Turbolader-Strömungsprüfstand', 'not' => array( 'Dynamische Turbolader-Durchflussprüfanlage' ) ),
	array( 'en' => 'turbocharger frame size', 'de' => 'Baugröße', 'not' => array( 'Rahmengröße', 'Gestellgröße' ) ),
	array( 'en' => 'core', 'de' => 'Rumpfgruppe', 'not' => array( 'Kernauswuchten', 'Kernauswuchtmaschine', 'Kernauswuchtmaschinen' ) ),
	array( 'en' => 'core balancing', 'de' => 'Rumpfgruppenauswuchten', 'not' => array( 'Kernauswuchten', 'Kern-Auswuchten' ) ),
	array( 'en' => 'core balancing machine', 'de' => 'Auswuchtmaschine für Rumpfgruppen', 'not' => array( 'Kernauswuchtmaschine', 'Kernauswuchtmaschinen' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'de' => 'Kombinierte Hochdrehzahl- und Niederdrehzahl-Auswuchtmaschine für Rumpfgruppen', 'not' => array( 'Kombinierte Hochgeschwindigkeits- und Niedergeschwindigkeits-Kernauswuchtmaschine' ) ),
	array( 'en' => 'High-Speed', 'de' => 'Hochdrehzahl', 'not' => array( 'Hochgeschwindigkeit', 'Hochgeschwindigkeits' ) ),
	array( 'en' => 'Low-Speed', 'de' => 'Niederdrehzahl', 'not' => array( 'Niedergeschwindigkeit', 'Niedergeschwindigkeits' ) ),
	array( 'en' => 'turnkey', 'de' => 'schlüsselfertig', 'not' => array( 'Turnkey', 'turnkey-fertig' ) ),
	array( 'en' => 'turret-style wheel head', 'de' => 'Revolver-Schleifkopf', 'not' => array( 'Türmchen-Schleifkopf', 'Turm-Radkopf' ) ),
	array( 'en' => 'two-wheel drive', 'de' => 'Zweiradantrieb', 'not' => array( 'Zweiradfahrzeuge', 'Antrieb auf zwei Rädern' ) ),
	array( 'en' => 'ultra-stable design', 'de' => 'hochstabile Konstruktion', 'not' => array( 'ultrastabiles Design', 'extrem stabiler Entwurf' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'de' => 'Ultraschall-Düsenreiniger', 'not' => array( 'ultrasonischer Düsenputzer', 'Ultraschalldüsenwäscher' ) ),
	array( 'en' => 'unbalance', 'de' => 'Unwucht', 'not' => array( 'Ungleichgewicht', 'Unbalance', 'Unausgeglichenheit' ) ),
	array( 'en' => 'unbeatable deals', 'de' => 'unschlagbare Angebote', 'not' => array( 'unbesiegbare Deals', 'nicht abgeschlossene Angebote' ) ),
	array( 'en' => 'Universal Balancing', 'de' => 'Universal Balancing', 'not' => array( 'Universelles Auswuchten', 'Universal-Auswuchten' ) ),
	array( 'en' => 'uptime across systems', 'de' => 'Verfügbarkeit über Ihren gesamten Anlagenpark hinweg', 'not' => array( 'Betriebszeit über Systeme', 'Laufzeit aller Systeme' ) ),
	array( 'en' => 'v-block support', 'de' => 'Prismenauflage', 'not' => array( 'V-Block-Stütze', 'V-Block-Auflage' ) ),
	array( 'en' => 'vacuum', 'de' => 'Vakuum', 'not' => array( 'Unterdruck', 'Leere' ) ),
	array( 'en' => 'vacuum evacuation', 'de' => 'Evakuieren', 'not' => array( 'Vakuumevakuierung', 'Vakuumräumung' ) ),
	array( 'en' => 'vacuum rise test', 'de' => 'Vakuumanstiegsprüfung', 'not' => array( 'Unterdruckanstiegstest', 'Vakuumsteigtest' ) ),
	array( 'en' => 'validate performance', 'de' => 'Leistung validieren', 'not' => array( 'Wirkung überprüfen', 'Performance verifizieren' ) ),
	array( 'en' => 'valve body unit', 'de' => 'Ventilblock', 'not' => array( 'Ventilkörper-Einheit', 'Ventilgehäuseeinheit' ) ),
	array( 'en' => 'vibration', 'de' => 'Schwingungen', 'not' => array( 'Vibrationen', 'Vibrierungen' ) ),
	array( 'en' => 'volume flexibility', 'de' => 'Mengenflexibilität', 'not' => array( 'Volumenflexibilität', 'Stückzahlvariabilität' ) ),
	array( 'en' => 'walking beam system', 'de' => 'Hubbalkensystem', 'not' => array( 'Wanderbalken-System', 'Gehbalkensystem' ) ),
	array( 'en' => 'warranty coverage', 'de' => 'Garantieumfang', 'not' => array( 'Garantieversicherung', 'Gewährleistungsversicherung' ) ),
	array( 'en' => 'water meter', 'de' => 'Wasserzähler', 'not' => array( 'Wassermesser', 'Wasseruhr' ) ),
	array( 'en' => 'water-cooled', 'de' => 'wassergekühlt', 'not' => array( 'wasserkühlend', 'wasserkühlt' ) ),
	array( 'en' => 'Perceivable', 'de' => 'Wahrnehmbar', 'not' => array( 'Erkennbar', 'Sichtbar' ) ),
	array( 'en' => 'Operable', 'de' => 'Bedienbar', 'not' => array( 'Betriebsfähig', 'Handhabbar' ) ),
	array( 'en' => 'Understandable', 'de' => 'Verständlich', 'not' => array( 'Begreiflich', 'Nachvollziehbar' ) ),
	array( 'en' => 'Robust', 'de' => 'Robust', 'not' => array( 'Zuverlässig', 'Widerstandsfähig' ) ),
	array( 'en' => 'wheel aligner', 'de' => 'Achsmessgerät', 'not' => array( 'Radausrichter', 'Radjustiergerät' ) ),
	array( 'en' => 'wheel alignment', 'de' => 'Achsvermessung', 'not' => array( 'Radausrichtung', 'Radjustierung' ) ),
	array( 'en' => 'WHEREAS', 'de' => 'IN DER ERWÄGUNG, DASS', 'not' => array( 'WÄHREND', 'WOHINGEGEN' ) ),
	array( 'en' => 'whistle', 'de' => 'Pfeifen', 'not' => array( 'Pfiff', 'Zischen' ) ),
	array( 'en' => 'Work Product', 'de' => 'Arbeitsergebnis', 'not' => array( 'Arbeitsprodukt', 'Werkprodukt' ) ),
	array( 'en' => 'XL Machine', 'de' => 'XL Machine', 'not' => array( 'XL-Maschine', 'Maschine XL' ) ),
	array( 'en' => 'Marketplace', 'de' => 'Marktplatz', 'not' => array( 'Börse' ) ),
	array( 'en' => 'Medical', 'de' => 'Medizintechnik', 'not' => array( 'Medizinisch', 'Medizinische' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'de' => 'Förderband- und Papierwalzen', 'not' => array( 'Förderer und Papierrollen', 'Transportband- und Papierrollen' ) ),
	array( 'en' => 'stem stickiness', 'de' => 'Klemmen des Ventilschiebers', 'not' => array( 'Schaftviskosität', 'Stängelhaftung' ) ),
	array( 'en' => 'hydraulic pilot', 'de' => 'hydraulische Vorsteuerung', 'not' => array( 'Hydraulikpilot', 'hydraulischer Pilot' ) ),
	array( 'en' => 'load sense signal', 'de' => 'Load-Sensing-Signal', 'not' => array( 'Lastsensorsignal', 'Lastfühlersignal' ) ),
	array( 'en' => 'debonding', 'de' => 'Ablösung', 'not' => array( 'Delaminierung', 'Entbindung' ) ),
	array( 'en' => 'movable cradle', 'de' => 'verfahrbare Wiege', 'not' => array( 'bewegliche Basis', 'fahrbarer Rahmen' ) ),
	array( 'en' => 'ring gears', 'de' => 'Hohlräder', 'not' => array( 'Ringzahnräder', 'Kranzräder' ) ),
	array( 'en' => 'blade timing', 'de' => 'Schar-Taktzeit', 'not' => array( 'Klingentiming', 'Schaufelzeit' ) ),
	array( 'en' => 'heavy-duty', 'de' => 'schwer', 'not' => array( 'lastintensiv' ) ),
	array( 'en' => 'life sciences', 'de' => 'Life Sciences', 'not' => array( 'Lebenswissenschaften', 'Biowissenschaften' ) ),
	array( 'en' => 'First Alert Monitoring System', 'de' => 'First Alert Monitoring System', 'not' => array( 'Frühwarnsystem First Alert', 'Erstalarm-Überwachungssystem' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'de' => 'Turbo Test Duo Expert', 'not' => array( 'Experte Turbo Test Duo', 'TURBO TEST DUO Experte' ) ),
	array( 'en' => 'Introducing', 'de' => 'Wir stellen vor:', 'not' => array( 'Neuheit', 'Vorstellung' ) ),
	array( 'en' => 'flammable gases', 'de' => 'brennbare Gase', 'not' => array( 'entflammbare Gase', 'leicht entzündliche Gase' ) ),
	array( 'en' => 'Electronic hung mass', 'de' => 'elektronische Kompensation der aufgehängten Masse', 'not' => array( 'Elektronische Hängemasse', 'elektronische aufgehängte Masse' ) ),
	array( 'en' => 'Detection Focus', 'de' => 'Erkennbare Fehlerarten', 'not' => array( 'Erkennungsfokus', 'Detektionsschwerpunkt' ) ),
	array( 'en' => 'weight capacity', 'de' => 'Tragfähigkeit', 'not' => array( 'Gewichtskapazität', 'Gewichtsvermögen' ) ),
	array( 'en' => 'fixed stations', 'de' => 'feste Stationen', 'not' => array( 'stationäre Bahnhöfe', 'Feststationen' ) ),
	array( 'en' => 'mobile carousels', 'de' => 'mobile Karussells', 'not' => array( 'bewegliche Karussells', 'fahrbare Rundläufer' ) ),
	array( 'en' => 'cooling units', 'de' => 'Kälteaggregate', 'not' => array( 'Kühleinheiten', 'Kühlungsgeräte' ) ),
	array( 'en' => 'e-axle', 'de' => 'E-Achse', 'not' => array( 'Elektroachse', 'e-axle' ) ),
	array( 'en' => 'horizontal boring machine', 'de' => 'Horizontalbohrwerk', 'not' => array( 'horizontale Bohrmaschine', 'Waagerecht-Bohrgerät' ) ),
	array( 'en' => 'test benches', 'de' => 'Prüfstände', 'not' => array( 'Testbänke', 'Prüfbänke' ) ),
	array( 'en' => 'test stands', 'de' => 'Prüfstände', 'not' => array( 'Teststände', 'Testständer' ) ),
	array( 'en' => 'testing', 'de' => 'Prüfung', 'not' => array( 'Testen', 'Testung' ) ),
	array( 'en' => 'Aerospace & industrials', 'de' => 'Luft- und Raumfahrt sowie Industrie', 'not' => array( 'Luftfahrt und Industrie', 'Luft- und Raumfahrtindustrie', 'Aerospace & Industrie' ) ),
	array( 'en' => 'Exhibit', 'de' => 'Anlage', 'not' => array( 'Ausstellung', 'Exponat' ) ),
	array( 'en' => 'Section', 'de' => 'Abschnitt', 'not' => array( 'Sektion', 'Paragraf' ) ),
	array( 'en' => 'RECITALS', 'de' => 'PRÄAMBEL', 'not' => array( 'ERWÄGUNGEN', 'VORBEMERKUNGEN' ) ),
	array( 'en' => 'Products', 'de' => 'Produkte', 'not' => array(  ) ),
	array( 'en' => 'Ascential Indemnity', 'de' => 'Freistellung durch Ascential', 'not' => array( 'Ascential Indemnity', 'Ascential-Entschädigung' ) ),
	array( 'en' => 'England', 'de' => 'England', 'not' => array(  ) ),
	array( 'en' => 'West Flanders', 'de' => 'Westflandern', 'not' => array( 'West-Flandern', 'West Flanders' ) ),
	array( 'en' => 'Poland', 'de' => 'Polen', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Play', 'de' => 'Abspielen', 'not' => array( 'Play', 'Spielen' ) ),
	array( 'en' => 'Listen to this article', 'de' => 'Diesen Artikel anhören', 'not' => array( 'Listen to this article', 'Hören Sie diesen Artikel' ) ),
	array( 'en' => 'Read the article', 'de' => 'Artikel lesen', 'not' => array( 'Read the article', 'Den Artikel lesen' ) ),
	array( 'en' => 'Read More', 'de' => 'Weiterlesen', 'not' => array( 'Mehr lesen', 'Weiter lesen' ) ),
	array( 'en' => 'News', 'de' => 'Aktuelles', 'not' => array( 'Nachrichten', 'Neuigkeiten' ) ),
	array( 'en' => 'chapters', 'de' => 'Kapitel', 'not' => array( 'chapters', 'Abschnitte' ) ),
	array( 'en' => 'Share', 'de' => 'Teilen', 'not' => array( 'Share', 'Freigeben' ) ),
	array( 'en' => 'Copy link', 'de' => 'Link kopieren', 'not' => array( 'Copy link', 'Link-Kopie' ) ),
	array( 'en' => 'Email', 'de' => 'E-Mail', 'not' => array( 'Email', 'Emaille' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'de' => 'Broschüre Kältemittelbefüllung', 'not' => array( 'Refrigerant Charging Brochure', 'Kältemittel-Lade-Broschüre' ) ),
	array( 'en' => 'Explore', 'de' => 'Entdecken', 'not' => array( 'Erkunden', 'Mehr Infos' ) ),
	array( 'en' => 'Browse catalog', 'de' => 'Katalog durchsuchen', 'not' => array( 'Katalog', 'Katalog blättern' ) ),
	array( 'en' => 'Browse all resources', 'de' => 'Alle Ressourcen durchsuchen', 'not' => array( 'Alle Ressourcen', 'Ressourcen ansehen' ) ),
	array( 'en' => 'Explore the Catalog', 'de' => 'Katalog durchsuchen', 'not' => array( 'Katalog erkunden', 'Den Katalog entdecken' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'de' => 'Bereit, Ihre Infrastruktur zu modernisieren?', 'not' => array( 'Bereit für ein Infrastruktur-Upgrade?', 'Sind Sie bereit, Ihre Infrastruktur aufzurüsten?' ) ),
	array( 'en' => 'Talk to an expert', 'de' => 'Mit einem Experten sprechen', 'not' => array( 'Sprich mit einem Experten', 'Expertengespräch' ) ),
	array( 'en' => 'fully loaded test', 'de' => 'Prüfung unter Volllast', 'not' => array( 'vollbeladener Test', 'umfassender Test' ) ),
	array( 'en' => 'Addresses', 'de' => 'Behandelt', 'not' => array( 'Eliminiert', 'Beseitigt' ) ),
	array( 'en' => 'is now', 'de' => 'ist jetzt', 'not' => array( 'wird nun', 'heißt nunmehr' ) ),
	array( 'en' => 'sales inquiry', 'de' => 'Vertriebsanfrage', 'not' => array( 'Verkaufsanfrage', 'Handelsanfrage' ) ),
	array( 'en' => 'Priority 1', 'de' => 'Priorität 1: hoch', 'not' => array( 'Priorität 1: Hohe Priorität', 'Priorität Eins' ) ),
	array( 'en' => 'Priority 2', 'de' => 'Priorität 2: mittel', 'not' => array( 'Priorität 2: Mittlere Priorität', 'Priorität Zwei' ) ),
	array( 'en' => 'Priority 3', 'de' => 'Priorität 3: niedrig', 'not' => array( 'Priorität 3: Niedrige Priorität', 'Priorität Drei' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'de' => 'ascentialtech.com durchsuchen', 'not' => array( 'Searching ascentialtech.com', 'Suche ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'de' => 'Kalenderansicht nicht verfügbar', 'not' => array( 'Calendar View Unavailable', 'Kalender-Ansicht unverfügbar' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'de' => 'Anbaugeräte – End-of-Line', 'not' => array( 'Implemente – End-Of-Line', 'Mobilgeräte-Anbaugeräte' ) ),
	array( 'en' => 'equipment', 'de' => 'Anlagen', 'not' => array( 'Ausrüstung', 'Vermögenswerte' ) ),
	array( 'en' => 'Transportation', 'de' => 'Fahrzeugtechnik', 'not' => array( 'Verkehrstechnik', 'Transportwesen' ) ),
	array( 'en' => 'Industries served', 'de' => 'Betreute Branchen', 'not' => array( 'Bediente Branchen', 'Branchen, die wir bedienen' ) ),
	array( 'en' => 'remote monitoring', 'de' => 'Fernüberwachung', 'not' => array( 'ferngesteuerte Überwachung', 'Remote-Monitoring' ) ),
	array( 'en' => 'deep expertise', 'de' => 'fundierte Expertise', 'not' => array( 'tiefe Expertise', 'tiefes Verständnis' ) ),
	array( 'en' => 'preventive maintenance', 'de' => 'vorbeugende Wartung', 'not' => array( 'präventive Wartung', 'Präventivwartung' ) ),
	array( 'en' => 'intervention time', 'de' => 'Eingriffszeit', 'not' => array(  ) ),
	array( 'en' => 'response time', 'de' => 'Reaktionszeit', 'not' => array(  ) ),
	array( 'en' => 'loading', 'de' => 'Beschickung', 'not' => array( 'Beladung', 'Beladen' ) ),
	array( 'en' => 'robotic loading', 'de' => 'Roboterbeschickung', 'not' => array( 'Roboterbeladung', 'robotische Beladung' ) ),
	array( 'en' => 'balancing machines', 'de' => 'Auswuchtmaschinen', 'not' => array( 'balancing machines', 'Wuchtmaschinen' ) ),
	array( 'en' => 'clutch and flywheel balancer', 'de' => 'Kupplungs- und Schwungrad-Auswuchtmaschine', 'not' => array(  ) ),
	array( 'en' => 'differential case', 'de' => 'Differenzialgehäuse', 'not' => array( 'Differentialgehäuse', 'Ausgleichsgehäuse' ) ),
	array( 'en' => 'axle balancing machine', 'de' => 'Achsauswuchtmaschine', 'not' => array( 'Achsenauswuchtmaschine', 'Achsen-Auswuchtmaschine' ) ),
	array( 'en' => 'Chief Technology Officer of Transportation', 'de' => 'Chief Technology Officer of Transportation', 'not' => array( 'Technischer Vorstand Fahrzeugtechnik', 'Technikvorstand Fahrzeugtechnik' ) ),
);
