<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * Spanish term base (en -> es). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Built 2026-09-25 from the site concept list plus a live
 * sample of /es/ catalog, transportation, care, resource-hub and
 * aerospace-industrials pages.
 */
return array(
	array( 'en' => '*', 'es' => 'The whole site is formal peninsular Spanish and addresses the reader as usted (plural ustedes) in every string and every slot: body copy, headings, eyebrows, all-caps bands, form labels, placeholders, alt and aria text, the <title>, the meta description, og: tags and JSON-LD. Register is a property of the PAGE, not of the segment, so a tu-form in a meta description contradicts the usted body it ships with. Buttons, card CTAs and link labels keep the verb of the English and take the imperative-usted, which is this site\'s established web-UI convention: "Browse catalog" is "Explore el catálogo", "Request a demo" is "Solicite una demostración", "Download" is "Descargue el folleto", "Contact us" is "Contáctenos", "Read the article" is "Lea el artículo", "Speak with an expert" is "Hable con un experto". Never flatten a verb label into a bare noun ("Catálogo", "Descarga", "Solicitud de demostración" are wrong for those) and never mix the infinitive into a group where the siblings are imperative. Never address the reader with tú or vosotros anywhere, at any length, including short CTAs, headlines and metadata.', 'not' => array( 'tuyo', 'tuya', 'tuyos', 'tuyas', 'vosotros', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'puedes', 'podéis', 'necesitas', 'necesitáis', 'tienes', 'tenéis', 'quieres', 'queréis', 'estás', 'estáis', 'sabes', 'sabéis', 'debes', 'debéis', 'haces', 'hacéis', 'buscas', 'buscáis', 'contáctanos', 'regístrate', 'suscríbete', 'inscríbete', 'descárgalo', 'descárgala', 'conócenos', 'llámanos', 'escríbenos', 'cuéntanos', 'únete', 'tu empresa', 'tu equipo', 'tu negocio', 'tu inversión', 'tus equipos', 'tus necesidades', 'tus datos' ) ),

	// --- Brands, entities, trademarks and model codes: never translated ---
	array( 'en' => 'Ascential Technologies', 'es' => 'Ascential Technologies', 'not' => array( 'Tecnologías Ascential' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'es' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Ensayo y Medida', 'Ascential de Ensayo y Medida', 'Ascential Sistemas de Ensayo y Medida' ) ),
	array( 'en' => 'Ascential Care', 'es' => 'Ascential Care', 'not' => array( 'Atención Ascential', 'Cuidado Ascential' ) ),
	array( 'en' => 'Ascentialytics', 'es' => 'Ascentialytics', 'not' => array( 'Analítica Ascential' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'es' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDICINA Y CIENCIAS DE LA VIDA', 'Ascential Medicina y Ciencias de la Vida', 'Ciencias de la Salud y de la Vida' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'es' => 'Burke E. Porter Machinery', 'not' => array( 'Maquinaria Burke E. Porter', 'Burke E. Porter Maquinaria' ) ),
	array( 'en' => 'Burke Porter Group', 'es' => 'Burke Porter Group', 'not' => array( 'Grupo Burke Porter' ) ),
	array( 'en' => 'Universal Balancing', 'es' => 'Universal Balancing', 'not' => array( 'Equilibrado universal', 'Equilibrado Universal', 'Equilibrados universales' ) ),
	array( 'en' => 'XL Machine', 'es' => 'XL Machine', 'not' => array( 'Máquina XL', 'Máquinas XL' ) ),
	array( 'en' => 'WinterPark Engineering', 'es' => 'WinterPark Engineering', 'not' => array( 'Ingeniería WinterPark', 'WinterPark Ingeniería' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'es' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Cía. S.L.', 'H. Kleinknecht y Compañía' ) ),
	array( 'en' => 'Kleinknecht Testing Technology', 'es' => 'Tecnología de ensayo de Kleinknecht', 'not' => array( 'Kleinknecht Tecnología de ensayo', 'Tecnología de ensayo Kleinknecht' ) ),
	array( 'en' => 'Bauer', 'es' => 'Bauer', 'not' => array( 'Bauer, S.A.' ) ),
	array( 'en' => 'Cimat', 'es' => 'Cimat', 'not' => array( 'CIMAT Equilibrado' ) ),
	array( 'en' => 'Titan', 'es' => 'Titan', 'not' => array( 'Titán' ) ),
	array( 'en' => 'Sentia', 'es' => 'Sentia', 'not' => array( 'Sencia' ) ),
	array( 'en' => 'Marketplace', 'es' => 'Marketplace', 'not' => array( 'Mercado', 'Tienda', 'Lonja' ) ),
	array( 'en' => 'ADAS Garage', 'es' => 'ADAS Garage', 'not' => array( 'Taller ADAS', 'Garaje ADAS' ) ),
	array( 'en' => 'Ask Burke Porter', 'es' => 'Ask Burke Porter', 'not' => array( 'Pregunte a Burke Porter', 'Pregunta a Burke Porter' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'es' => 'ADVANCING THE MACHINE', 'not' => array( 'HACIENDO AVANZAR LA MÁQUINA', 'IMPULSANDO LA MÁQUINA' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'es' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'SOLUCIONES INTEGRALES DE COMERCIALIZACIÓN' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'es' => 'A DESIGN / B LOGO', 'not' => array( 'DISEÑO A', 'LOGOTIPO B' ) ),
	array( 'en' => 'Impossible? Done.', 'es' => 'Impossible? Done.', 'not' => array( '¿Imposible? Hecho.', 'Imposible. Hecho.' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'es' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Calibración como servicio™', 'Calibración como Servicio™' ) ),
	array( 'en' => 'Balancing as a Service (BaaS)', 'es' => 'Balancing as a Service (BaaS)', 'not' => array( 'Equilibrado por contrato como servicio (BaaS)', 'equilibrado como servicio (BaaS)' ) ),
	array( 'en' => 'CMT-TR Polimer', 'es' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR de polímero', 'equilibradora de rotores de polímero CMT-TR', 'Máquina equilibradora de rotores de polímero CMT-TR' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'es' => 'Turbo Test Duo Expert', 'not' => array( 'Experto Turbo Test Duo', 'TURBO TEST DUO Experto' ) ),
	array( 'en' => 'First Alert Monitoring System', 'es' => 'sistema de monitorización First Alert', 'not' => array( 'sistema de alerta temprana', 'sistema de monitorización de primera alerta' ) ),
	array( 'en' => 'eRotor', 'es' => 'eRotor', 'not' => array( 'rotor eléctrico', 'rotor-e' ) ),
	array( 'en' => 'Cerberus X1', 'es' => 'Cerberus X1', 'not' => array( 'Cerbero X1' ) ),
	array( 'en' => 'Connect on LinkedIn', 'es' => 'Perfil en LinkedIn', 'not' => array( 'Connect on LinkedIn', 'Conecta en LinkedIn', 'Conéctese en LinkedIn' ) ),

	// --- Balancing and rotating machinery ---
	array( 'en' => 'unbalance', 'es' => 'desequilibrio', 'not' => array( 'desbalance', 'desbalanceo', 'desequilibrado', 'falta de equilibrio' ) ),
	array( 'en' => 'residual unbalance', 'es' => 'desequilibrio residual', 'not' => array( 'desbalance residual', 'desequilibrio remanente' ) ),
	array( 'en' => 'balancing', 'es' => 'equilibrado', 'not' => array( 'balanceo', 'balanceado', 'equilibración' ) ),
	array( 'en' => 'balancing machine', 'es' => 'equilibradora', 'not' => array( 'máquina de balanceo', 'balanceadora' ) ),
	array( 'en' => 'Balancing Machines', 'es' => 'Máquinas equilibradoras', 'not' => array( 'Máquinas de balanceo', 'Balanceadoras' ) ),
	array( 'en' => 'Automotive Industry Balancers', 'es' => 'Equilibradoras para la industria del automóvil', 'not' => array( 'Equilibradores para la industria del automóvil', 'Balanceadores para automoción' ) ),
	array( 'en' => 'Industrial Balancing Machine', 'es' => 'Máquinas equilibradoras industriales', 'not' => array( 'Máquina equilibradora industrial', 'Balanceadora industrial' ) ),
	array( 'en' => 'non-rotating balancing machine', 'es' => 'equilibradora sin rotación', 'not' => array( 'equilibradora sin rotor', 'equilibradora no giratoria', 'máquina de equilibrado sin rotor' ) ),
	array( 'en' => 'Non-Rotate Systems', 'es' => 'Sistemas sin rotación', 'not' => array( 'Sistemas no rotativos', 'Sistemas sin giro' ) ),
	array( 'en' => 'Spin Testing', 'es' => 'Ensayos de rotación', 'not' => array( 'Pruebas de giro', 'Ensayos de hilado' ) ),
	array( 'en' => 'spin testing machine', 'es' => 'máquina de ensayos de rotación', 'not' => array( 'máquina de pruebas de giro' ) ),
	array( 'en' => 'field balancing', 'es' => 'equilibrado in situ', 'not' => array( 'equilibrado de campo', 'equilibrado en el terreno' ) ),
	array( 'en' => 'Field Balancers', 'es' => 'Equilibradoras portátiles', 'not' => array( 'Equilibradores de campo' ) ),
	array( 'en' => 'correction (of unbalance)', 'es' => 'corrección', 'not' => array( 'rectificación del desequilibrio' ) ),
	array( 'en' => 'punching', 'es' => 'punzonado', 'not' => array( 'troquelado' ) ),
	array( 'en' => 'bearers', 'es' => 'apoyos', 'not' => array( 'rodamientos', 'portadores' ) ),
	array( 'en' => 'pedestals', 'es' => 'caballetes', 'not' => array( 'pedestales', 'columnas' ) ),
	array( 'en' => 'pins', 'es' => 'pasadores', 'not' => array( 'muñones', 'alfileres', 'clavijas' ) ),
	array( 'en' => 'bearing center lines', 'es' => 'ejes de los cojinetes', 'not' => array( 'líneas centrales de rodamiento', 'ejes de los muñones' ) ),
	array( 'en' => 'bearing life', 'es' => 'vida útil del cojinete', 'not' => array( 'vida del rodamiento', 'duración del rodamiento' ) ),
	array( 'en' => 'tapered roller bearing', 'es' => 'rodamiento de rodillos cónicos', 'not' => array( 'rodamiento de rodillos cilíndricos' ) ),
	array( 'en' => 'v-block support', 'es' => 'apoyo en bloque en V', 'not' => array( 'soporte de bloque V', 'bloques V' ) ),
	array( 'en' => 'burst proof protection', 'es' => 'protección contra estallido del rotor', 'not' => array( 'protección antiexplosión', 'protección a prueba de explosión' ) ),
	array( 'en' => 'maximum rotor diameter', 'es' => 'diámetro máximo del rotor', 'not' => array( 'tamaño máximo del rotor' ) ),
	array( 'en' => 'armature', 'es' => 'inducido', 'not' => array( 'armadura', 'rotor eléctrico' ) ),
	array( 'en' => 'Horizontal Manual - Electric Armatures', 'es' => 'Horizontal manual: inducidos eléctricos', 'not' => array( 'Manual horizontal: armaduras eléctricas' ) ),
	array( 'en' => 'pulley', 'es' => 'polea', 'not' => array( 'correa' ) ),
	array( 'en' => 'flywheel', 'es' => 'volante de inercia', 'not' => array( 'volante motor', 'rueda volante' ) ),
	array( 'en' => 'dual mass flywheel', 'es' => 'volante bimasa', 'not' => array( 'volante de doble masa', 'embrague bimasa', 'volante de inercia de doble masa' ) ),
	array( 'en' => 'flexplate', 'es' => 'placa flexible de arrastre', 'not' => array( 'placa flexible de embrague' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'es' => 'cilindros de transportador y cilindros papeleros', 'not' => array( 'rodillos de papel', 'transportador y rodillos de papel' ) ),
	array( 'en' => 'Turbocharger Balancers', 'es' => 'Equilibradoras de turbocompresores', 'not' => array( 'Equilibradora de turbos', 'Balanceadoras de turbo' ) ),
	array( 'en' => 'Turbo Balancing Machine', 'es' => 'Equilibradora de turbocompresores', 'not' => array( 'Equilibradora de turbos', 'Máquina de balanceo de turbos' ) ),
	array( 'en' => 'Rotor Balancing Machine', 'es' => 'Equilibradora de rotores', 'not' => array( 'Máquina de equilibrado de rotores', 'Máquina equilibradora de rotor' ) ),
	array( 'en' => 'High-Speed Core Balancing Machine', 'es' => 'Equilibradora de núcleos a alta velocidad', 'not' => array( 'Máquina equilibradora de núcleo de alta velocidad' ) ),
	array( 'en' => 'Low-Speed Core Balancing Machine', 'es' => 'Equilibradora de núcleos a baja velocidad', 'not' => array( 'Máquina equilibradora de núcleo de baja velocidad' ) ),
	array( 'en' => 'Combined Core and Rotor Balancing Machine', 'es' => 'Equilibradora combinada de núcleos y rotores', 'not' => array( 'Máquina equilibradora combinada de núcleo y rotor' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'es' => 'Equilibradora combinada de núcleos a alta y baja velocidad', 'not' => array( 'Máquina equilibradora de núcleo de alta y baja velocidad combinadas' ) ),
	array( 'en' => 'turbocharger flow bench', 'es' => 'banco de flujo para turbocompresores', 'not' => array( 'banco de ensayo de flujo', 'dinamómetro de turbocompresores' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'es' => 'banco de flujo dinámico para turbocompresores', 'not' => array(  ) ),
	array( 'en' => 'turbocharger frame size', 'es' => 'tamaño de carcasa del turbocompresor', 'not' => array( 'tamaño de bastidor', 'tamaño del marco' ) ),
	array( 'en' => 'turbo calibration', 'es' => 'calibración de turbocompresores', 'not' => array( 'equilibrado de turbocompresores' ) ),
	array( 'en' => 'boreless compressor wheel', 'es' => 'rueda de compresor sin taladro central', 'not' => array( 'turbocompresor sin cojinetes', 'rueda de compresor sin agujero' ) ),
	array( 'en' => 'whistle', 'es' => 'silbido', 'not' => array( 'zumbido', 'pitido' ) ),
	array( 'en' => 'vibration', 'es' => 'vibración', 'not' => array( 'oscilación', 'temblor' ) ),
	array( 'en' => 'kinetostatics', 'es' => 'cinetostática', 'not' => array( 'cinética' ) ),
	array( 'en' => 'Electronic hung mass', 'es' => 'compensación electrónica de masa suspendida', 'not' => array( 'masa colgada electrónica', 'masa suspendida electrónica' ) ),
	array( 'en' => 'in a single clamping', 'es' => 'en una sola fijación', 'not' => array( 'en una sola pinza', 'en un solo apriete' ) ),
	array( 'en' => 'single station / multi station', 'es' => 'de una estación / de varias estaciones', 'not' => array( 'de una cámara', 'monocámara', 'multicámara' ) ),
	array( 'en' => 'single bay', 'es' => 'de un solo puesto', 'not' => array( 'de una sola bahía', 'monocámara' ) ),
	array( 'en' => 'walking beam system', 'es' => 'sistema de viga transportadora', 'not' => array( 'sistema de viga caminante', 'sistema de viga andante' ) ),
	array( 'en' => 'motorized clamping', 'es' => 'amarre motorizado', 'not' => array( 'sujeción a motor', 'apriete motorizado' ) ),
	array( 'en' => 'custom fixturing', 'es' => 'utillaje a medida', 'not' => array( 'accesorios personalizados', 'fijaciones a medida' ) ),
	array( 'en' => 'setup cycles', 'es' => 'ciclos de preparación de pieza', 'not' => array( 'ciclos de montaje', 'ciclos de configuración' ) ),
	array( 'en' => 'active part probing', 'es' => 'palpado activo de la pieza', 'not' => array( 'sondeo activo de piezas' ) ),
	array( 'en' => 'aperture plate', 'es' => 'placa de apertura', 'not' => array( 'placa de abertura óptica' ) ),
	array( 'en' => 'anchoring', 'es' => 'anclaje', 'not' => array( 'amarre al suelo' ) ),

	// --- Automotive, powertrain, EOL and ADAS ---
	array( 'en' => 'transmission / gearbox', 'es' => 'caja de cambios', 'not' => array( 'transmisión automática de señal' ) ),
	array( 'en' => 'Powertrain', 'es' => 'Grupo motopropulsor', 'not' => array( 'Tren motriz', 'Tren de potencia', 'Cadena cinemática' ) ),
	array( 'en' => 'propulsion & powertrain', 'es' => 'propulsión y grupo motopropulsor', 'not' => array( 'propulsión y tren motriz', 'propulsión y transmisión' ) ),
	array( 'en' => 'driveshaft', 'es' => 'árbol de transmisión', 'not' => array( 'eje motriz', 'flecha de transmisión' ) ),
	array( 'en' => 'crankshaft', 'es' => 'cigüeñal', 'not' => array( 'árbol de manivelas', 'eje cigüeñal' ) ),
	array( 'en' => 'inline crankshaft', 'es' => 'cigüeñal en línea', 'not' => array( 'cigüeñal de cuatro tiempos' ) ),
	array( 'en' => 'single cylinder crankshaft', 'es' => 'cigüeñal monocilíndrico', 'not' => array( 'cigüeñal de una sola vía', 'cigüeñal unicilíndrico' ) ),
	array( 'en' => 'crankshaft lathe', 'es' => 'torno para cigüeñales', 'not' => array( 'torno para bielas' ) ),
	array( 'en' => 'dynamometer', 'es' => 'dinamómetro', 'not' => array( 'banco de potencia', 'freno dinamométrico' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'es' => 'dinamómetro de chasis de 2 y 4 ruedas', 'not' => array( 'dinamómetro de chasis de 2 y 4 ejes' ) ),
	array( 'en' => 'inline dyno', 'es' => 'dinamómetro en línea', 'not' => array( 'dinamómetro integrado' ) ),
	array( 'en' => 'steerable dyno', 'es' => 'dinamómetro para ruedas directrices', 'not' => array( 'dinamómetro direccional', 'dinamómetro orientable' ) ),
	array( 'en' => 'roller brake tester', 'es' => 'frenómetro de rodillos', 'not' => array( 'probador de frenos de rodillos', 'banco de frenos de rodillos' ) ),
	array( 'en' => 'roller (brake tester)', 'es' => 'rodillo', 'not' => array( 'cilindro de frenado' ) ),
	array( 'en' => 'retaining rollers', 'es' => 'rodillos de retención', 'not' => array( 'cilindros de retención', 'rodillos retenedores' ) ),
	array( 'en' => 'end of line testing', 'es' => 'ensayos de fin de línea', 'not' => array( 'pruebas de final de línea', 'ensayos al final de la línea', 'End of Line Testing' ) ),
	array( 'en' => 'Vehicles End-of-Line', 'es' => 'Fin de línea de vehículos', 'not' => array( 'Vehículos al final de línea', 'Vehículos de fin de línea' ) ),
	array( 'en' => 'ADAS', 'es' => 'ADAS', 'not' => array( 'sistemas avanzados de apoyo al conductor' ) ),
	array( 'en' => 'ADAS alignment', 'es' => 'calibración ADAS', 'not' => array( 'alineación ADAS', 'alineado ADAS' ) ),
	array( 'en' => 'calibration target', 'es' => 'panel de calibración', 'not' => array( 'objetivo de calibración', 'diana de calibración' ) ),
	array( 'en' => 'probe alignment', 'es' => 'ajuste de la sonda', 'not' => array( 'alineación de la sonda' ) ),
	array( 'en' => 'bore axis alignment', 'es' => 'alineación del eje de puntería', 'not' => array( 'alineación del eje del taladro' ) ),
	array( 'en' => 'misalignment', 'es' => 'desalineación', 'not' => array( 'mala alineación', 'desajuste de alineado' ) ),
	array( 'en' => 'wheel alignment', 'es' => 'alineación de dirección', 'not' => array( 'alineación de ruedas', 'equilibrado de ruedas' ) ),
	array( 'en' => 'wheel aligner', 'es' => 'alineador de dirección', 'not' => array( 'alineadora de ruedas', 'máquina de alineación de ruedas' ) ),
	array( 'en' => 'instrument cluster', 'es' => 'cuadro de instrumentos', 'not' => array( 'grupo de instrumentos', 'clúster de instrumentos' ) ),
	array( 'en' => 'control module', 'es' => 'módulo de control', 'not' => array( 'módulo de mando' ) ),
	array( 'en' => 'blank ECM', 'es' => 'ECM sin programar', 'not' => array( 'ECM en blanco', 'ECM vacío' ) ),
	array( 'en' => 'engine software loaders', 'es' => 'equipos de carga de software de motor', 'not' => array( 'cargadores de motores', 'programas de carga de motores' ) ),
	array( 'en' => 'gear shift calibration', 'es' => 'calibración del cambio de marchas', 'not' => array( 'calibración del desplazamiento de marchas' ) ),
	array( 'en' => 'drivability', 'es' => 'comportamiento dinámico', 'not' => array( 'conducibilidad', 'manejabilidad' ) ),
	array( 'en' => 'restbus simulation', 'es' => 'simulación de bus restante', 'not' => array( 'simulación de bus residual', 'simulación restbus' ) ),
	array( 'en' => 'traction battery', 'es' => 'batería de tracción', 'not' => array( 'pila de tracción', 'acumulador de tracción' ) ),
	array( 'en' => 'e-axle', 'es' => 'eje eléctrico', 'not' => array( 'e-axle', 'eje-e' ) ),
	array( 'en' => 'torque vectoring', 'es' => 'vectorización del par', 'not' => array( 'reparto del par', 'vectorización de torque' ) ),
	array( 'en' => 'rolling torque', 'es' => 'par de rodadura', 'not' => array( 'par de giro del eje', 'torque de rodadura' ) ),
	array( 'en' => 'two-wheel drive', 'es' => 'tracción a dos ruedas', 'not' => array( 'tracción de dos ruedas', 'impulso a dos ruedas' ) ),
	array( 'en' => 'third member', 'es' => 'grupo diferencial', 'not' => array( 'tercer miembro', 'tercer elemento' ) ),
	array( 'en' => 'half case (RDU/PTU)', 'es' => 'carcasa partida', 'not' => array( 'medio cárter', 'media caja' ) ),
	array( 'en' => 'pinion gear', 'es' => 'piñón', 'not' => array( 'muñón', 'engranaje de piñón cónico' ) ),
	array( 'en' => 'ring gears', 'es' => 'coronas dentadas', 'not' => array( 'engranajes anulares', 'coronas de anillo' ) ),
	array( 'en' => 'front strut', 'es' => 'amortiguador delantero tipo McPherson', 'not' => array( 'montante delantero', 'pilar delantero', 'pinza delantera' ) ),
	array( 'en' => 'commercial vehicle', 'es' => 'vehículo industrial', 'not' => array( 'vehículo comercial', 'vehículo de comercio' ) ),
	array( 'en' => 'squeak & rattle testing', 'es' => 'ensayos de ruidos y vibraciones parásitas', 'not' => array( 'ensayo de chirridos y traqueteos', 'pruebas de crujidos' ) ),
	array( 'en' => 'NVH Testing', 'es' => 'Ensayos NVH (ruido, vibración y aspereza)', 'not' => array( 'Ensayos NVH (ruido y vibración)', 'Pruebas NVH' ) ),
	array( 'en' => 'OBD & Emissions Testing', 'es' => 'Ensayos OBD y de emisiones', 'not' => array( 'Pruebas OBD y de emisiones' ) ),
	array( 'en' => 'compliance testing', 'es' => 'ensayos de conformidad', 'not' => array( 'pruebas de cumplimiento', 'ensayos de cumplimiento' ) ),
	array( 'en' => 'tire inflator', 'es' => 'estación de inflado de neumáticos', 'not' => array( 'inflador de neumáticos', 'bomba de neumáticos' ) ),
	array( 'en' => 'bead breaking', 'es' => 'destalonado', 'not' => array( 'rotura del talón', 'rotura de la banda' ) ),
	array( 'en' => 'Balancers for Rims', 'es' => 'Equilibradoras para llantas', 'not' => array( 'Equilibradores para llantas' ) ),
	array( 'en' => 'Balancers for Clutches', 'es' => 'Equilibradoras para embragues', 'not' => array( 'Equilibradores para embragues' ) ),

	// --- Refrigeration, gas management and leak detection ---
	array( 'en' => 'refrigerant', 'es' => 'refrigerante', 'not' => array( 'líquido de refrigeración', 'anticongelante', 'fluido frigorífico' ) ),
	array( 'en' => 'refrigerant charging', 'es' => 'carga de refrigerante', 'not' => array( 'llenado de refrigerante', 'recarga de refrigerante', 'carga de líquido refrigerante' ) ),
	array( 'en' => 'refrigeration', 'es' => 'refrigeración', 'not' => array( 'enfriamiento industrial' ) ),
	array( 'en' => 'Leak Detection & Refrigeration', 'es' => 'Detección de fugas y refrigeración', 'not' => array( 'Refrigeración y detección de fugas', 'Detección de escapes y refrigeración' ) ),
	array( 'en' => 'Leak Detection & Gas Management', 'es' => 'Detección de fugas y gestión de gases', 'not' => array( 'Refrigeración y gestión de gases', 'Gestión de gases y detección de fugas' ) ),
	array( 'en' => 'leak detection', 'es' => 'detección de fugas', 'not' => array( 'detección de escapes', 'detección de pérdidas', 'ensayo de estanqueidad' ) ),
	array( 'en' => 'gross leak test', 'es' => 'ensayo de fuga gruesa', 'not' => array( 'ensayo de fuga bruta', 'prueba de fuga gruesa' ) ),
	array( 'en' => 'fine leak', 'es' => 'microfuga', 'not' => array( 'fuga fina', 'fuga delicada' ) ),
	array( 'en' => 'tracer gas', 'es' => 'gas trazador', 'not' => array( 'gas rastreador', 'gas de seguimiento' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'es' => 'sonda de olfateo', 'not' => array( 'pinzas olfateadoras', 'alicates de olfateo' ) ),
	array( 'en' => 'vacuum', 'es' => 'vacío', 'not' => array( 'depresión', 'presión negativa' ) ),
	array( 'en' => 'vacuum evacuation', 'es' => 'evacuación al vacío', 'not' => array( 'extracción de vacío', 'vaciado de la depresión' ) ),
	array( 'en' => 'vacuum rise test', 'es' => 'ensayo de subida de vacío', 'not' => array( 'ensayo de subida de depresión', 'prueba de aumento de vacío' ) ),
	array( 'en' => 'pressurization', 'es' => 'presurización', 'not' => array( 'puesta a presión', 'presionado' ) ),
	array( 'en' => 'final discharge', 'es' => 'descarga final del gas', 'not' => array( 'vertido final', 'descargo final' ) ),
	array( 'en' => 'filler', 'es' => 'estación de llenado', 'not' => array( 'llenadora', 'rellenador' ) ),
	array( 'en' => 'filler gun', 'es' => 'pistola de llenado', 'not' => array( 'pistolita dosificadora', 'pistola dosificadora de relleno' ) ),
	array( 'en' => 'flammable gases', 'es' => 'gases inflamables', 'not' => array( 'gases combustibles', 'gases flamables' ) ),
	array( 'en' => 'hazardous area', 'es' => 'zona con riesgo de explosión', 'not' => array( 'área peligrosa', 'zona de peligro' ) ),
	array( 'en' => 'sealed assembly', 'es' => 'conjunto estanco', 'not' => array( 'conjunto sellado', 'montaje precintado' ) ),
	array( 'en' => 'cooling units', 'es' => 'unidades de refrigeración', 'not' => array( 'unidades enfriadoras', 'equipos de enfriado' ) ),
	array( 'en' => 'air cycle machines', 'es' => 'máquinas de ciclo de aire', 'not' => array( 'máquinas de ciclado de aire' ) ),
	array( 'en' => 'blowers', 'es' => 'soplantes', 'not' => array( 'sopladores', 'ventiladores centrífugos' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'es' => 'limpiador ultrasónico de boquillas', 'not' => array( 'limpiadora ultrasonido de toberas' ) ),
	array( 'en' => 'Ultrasonic Welding Systems', 'es' => 'Sistemas de soldadura por ultrasonidos', 'not' => array( 'Sistemas de soldadura ultrasónica' ) ),

	// --- Metals, roll shop and NDT ---
	array( 'en' => 'mill roll', 'es' => 'cilindro de laminación', 'not' => array( 'rodillo de molino', 'rollo de laminación' ) ),
	array( 'en' => 'Roll Inspection', 'es' => 'Inspección de cilindros', 'not' => array( 'Inspección de rodillos', 'Control de rodillos' ) ),
	array( 'en' => 'Roll Grinding Machines', 'es' => 'Rectificadoras de cilindros', 'not' => array( 'Máquinas de rectificado de rodillos', 'Amoladoras de cilindros' ) ),
	array( 'en' => 'Roll Shop Technologies', 'es' => 'Tecnologías para el taller de cilindros', 'not' => array( 'Roll Shop Technologies', 'Tecnologías de taller de rodillos' ) ),
	array( 'en' => 'reconditioning (rolls)', 'es' => 'reacondicionamiento de cilindros', 'not' => array( 'renovación de rodillos' ) ),
	array( 'en' => 'forged rolls', 'es' => 'cilindros forjados', 'not' => array( 'rodillos forjados' ) ),
	array( 'en' => '20-high / six-high mill', 'es' => 'laminador de 20 cilindros / de 6 cilindros', 'not' => array( 'laminador veinteavo', 'molino de 20 alturas' ) ),
	array( 'en' => 'cold pilger mill', 'es' => 'laminador peregrino en frío', 'not' => array( 'molino pilger en frío', 'laminador pilger frío' ) ),
	array( 'en' => 'Cold & Hot Rolling Mills', 'es' => 'Laminadores en frío y en caliente', 'not' => array( 'Molinos de laminación fría y caliente' ) ),
	array( 'en' => 'strip', 'es' => 'banda', 'not' => array( 'tira de acero', 'cinta de acero' ) ),
	array( 'en' => 'Strip Lines', 'es' => 'Líneas de banda', 'not' => array( 'Líneas de decapado', 'Líneas de tiras' ) ),
	array( 'en' => 'blast furnace', 'es' => 'alto horno', 'not' => array( 'horno de explosión', 'horno alto de fundición' ) ),
	array( 'en' => 'tap hole', 'es' => 'piquera', 'not' => array( 'agujero de colada', 'orificio de grifo' ) ),
	array( 'en' => 'clay gun', 'es' => 'tapadora de piquera', 'not' => array( 'pistola de arcilla', 'máquina de moldeo de arcilla' ) ),
	array( 'en' => 'tin plating', 'es' => 'estañado', 'not' => array( 'galvanizado', 'cincado', 'zincado' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'es' => 'texturizado por electroerosión (EDT)', 'not' => array( 'tecnología de descarga eléctrica', 'texturado por descarga eléctrica' ) ),
	array( 'en' => 'eddy current technology', 'es' => 'tecnología de corrientes de Foucault', 'not' => array( 'corrientes parásitas', 'corrientes de remolino', 'tecnología de corriente actual' ) ),
	array( 'en' => 'non-destructive testing (NDT)', 'es' => 'ensayos no destructivos (END)', 'not' => array( 'pruebas no destructivas', 'testeo no destructivo' ) ),
	array( 'en' => 'spalls', 'es' => 'desconchados', 'not' => array( 'astillados', 'escamaduras' ) ),
	array( 'en' => 'surface separations', 'es' => 'desprendimientos superficiales', 'not' => array( 'separaciones de superficie' ) ),
	array( 'en' => 'pinches & bruises', 'es' => 'marcas de pinzado y golpes', 'not' => array( 'pellizcos y moratones', 'pinzamientos y contusiones' ) ),
	array( 'en' => 'debonding', 'es' => 'despegue entre capa y núcleo', 'not' => array( 'delaminación', 'desunión' ) ),
	array( 'en' => 'Detection Focus', 'es' => 'Defectos detectados', 'not' => array( 'Enfoque de detección', 'Foco de detección' ) ),
	array( 'en' => 'Furnace & Blast Furnace Technology', 'es' => 'Tecnología de hornos y altos hornos', 'not' => array( 'Tecnología de hornos y hornos de explosión' ) ),
	array( 'en' => 'Handling Machines & Manipulators', 'es' => 'Máquinas de manipulación y manipuladores', 'not' => array( 'Máquinas de manejo y manipuladores' ) ),
	array( 'en' => 'Pipe Manufacturing', 'es' => 'Fabricación de tubos', 'not' => array( 'Fabricación de tuberías', 'Manufactura de tubos' ) ),
	array( 'en' => 'Press Technology & Hydroforming', 'es' => 'Tecnología de prensas e hidroconformado', 'not' => array( 'Tecnología de prensa y hidroformado' ) ),
	array( 'en' => 'Metals automation', 'es' => 'Automatización para la industria del metal', 'not' => array( 'Automatización de metales', 'Automatización metálica' ) ),

	// --- Machine tools, machining and grinding ---
	array( 'en' => 'machine tools', 'es' => 'máquinas herramienta', 'not' => array( 'máquinas herramientas', 'herramientas de máquina', 'máquinas tecnológicas' ) ),
	array( 'en' => 'Machine Tools and Special Machines', 'es' => 'Máquinas herramienta y máquinas especiales', 'not' => array( 'Máquinas herramientas y máquinas especiales' ) ),
	array( 'en' => 'machining cell', 'es' => 'célula de mecanizado', 'not' => array( 'celda de mecanizado', 'gabinete de mecanizado' ) ),
	array( 'en' => 'machinist', 'es' => 'operario de máquina herramienta', 'not' => array( 'maquinista', 'mecánico de máquinas' ) ),
	array( 'en' => 'boring (machining)', 'es' => 'mandrinado', 'not' => array(  ) ),
	array( 'en' => 'horizontal boring machine', 'es' => 'mandrinadora horizontal', 'not' => array( 'taladradora horizontal' ) ),
	array( 'en' => 'deep hole drilling', 'es' => 'taladrado profundo', 'not' => array( 'perforación de agujeros profundos' ) ),
	array( 'en' => 'gundrill', 'es' => 'broca de cañón', 'not' => array( 'taladro de pistola', 'broca gundrill' ) ),
	array( 'en' => 'grinding wheel', 'es' => 'muela abrasiva', 'not' => array( 'rueda de esmerilar', 'disco de rectificado' ) ),
	array( 'en' => 'rotary diamond dressing', 'es' => 'diamantado con rodillo rotativo', 'not' => array( 'acabado rotativo con diamante', 'dressing rotativo' ) ),
	array( 'en' => 'superabrasives', 'es' => 'superabrasivos', 'not' => array( 'súper abrasivos' ) ),
	array( 'en' => 'infeed (grinding)', 'es' => 'avance de penetración', 'not' => array( 'alimentación interna' ) ),
	array( 'en' => 'turret-style wheel head', 'es' => 'cabezal portamuelas de torreta', 'not' => array( 'cabezal de torrecilla' ) ),
	array( 'en' => '3-jaw chuck', 'es' => 'plato de tres garras', 'not' => array( 'mandril de tres piezas', 'portabrocas de tres mordazas' ) ),
	array( 'en' => 'collet chuck', 'es' => 'portapinzas', 'not' => array( 'mandril neumático', 'portabrocas de pinza' ) ),
	array( 'en' => 'chip vacuum', 'es' => 'aspiración de virutas', 'not' => array( 'aspiradora de virutas' ) ),
	array( 'en' => 'dial indicator', 'es' => 'comparador de reloj', 'not' => array( 'indicador de dial', 'medidor de carátula' ) ),
	array( 'en' => 'TIR / radial run-out', 'es' => 'excentricidad radial (TIR)', 'not' => array( 'salida radial', 'carrera radial' ) ),
	array( 'en' => 'gantry', 'es' => 'pórtico', 'not' => array( 'grúa portal', 'estructura de puente' ) ),
	array( 'en' => 'gantry milling', 'es' => 'fresado en pórtico', 'not' => array( 'fresado de puente', 'fresado de pórtico móvil' ) ),
	array( 'en' => 'Brushing & Polishing Machines', 'es' => 'Máquinas de cepillado y pulido', 'not' => array( 'Máquinas de cepillo y brillo' ) ),
	array( 'en' => 'Retrofit & Modernization', 'es' => 'Retrofit y modernización', 'not' => array( 'Reacondicionamiento y renovación', 'Modernización y renovación' ) ),
	array( 'en' => 'Precision Machining', 'es' => 'Mecanizado de precisión', 'not' => array( 'Maquinado de precisión' ) ),

	// --- Fluid power, hydraulics and industrial systems ---
	array( 'en' => 'fluid power', 'es' => 'potencia fluida', 'not' => array( 'potencia de fluidos', 'energía fluida', 'poder fluido' ) ),
	array( 'en' => 'Linear Motion', 'es' => 'Movimiento lineal', 'not' => array( 'Moción lineal', 'Desplazamiento lineal' ) ),
	array( 'en' => 'Rotary Motion', 'es' => 'Movimiento rotativo', 'not' => array( 'Moción rotatoria' ) ),
	array( 'en' => 'valve body unit', 'es' => 'cuerpo de válvulas', 'not' => array( 'conjunto de válvulas', 'unidad del cuerpo de válvula' ) ),
	array( 'en' => 'hydraulic pilot', 'es' => 'pilotaje hidráulico', 'not' => array( 'piloto hidráulico', 'mando hidráulico piloto' ) ),
	array( 'en' => 'load sense signal', 'es' => 'señal load-sense (LS)', 'not' => array( 'señal del sensor de carga', 'señal de detección de carga' ) ),
	array( 'en' => 'stem stickiness', 'es' => 'agarrotamiento del vástago', 'not' => array( 'viscosidad del vástago', 'pegajosidad del vástago' ) ),
	array( 'en' => 'drift (cylinder)', 'es' => 'deriva del cilindro', 'not' => array( 'deriva a la deriva', 'desplazamiento involuntario' ) ),
	array( 'en' => 'cushion testing', 'es' => 'ensayo de amortiguación de final de carrera', 'not' => array( 'ensayo del cojín', 'prueba de almohadilla' ) ),
	array( 'en' => 'snubber', 'es' => 'amortiguador de golpe de ariete', 'not' => array( 'supresor', 'amortiguador simple' ) ),
	array( 'en' => 'push and pull', 'es' => 'empuje y tracción', 'not' => array( 'presión y estiramiento' ) ),
	array( 'en' => 'thrust force / pullback force', 'es' => 'fuerza de empuje / fuerza de tracción', 'not' => array( 'fuerza axial' ) ),
	array( 'en' => 'tension (mechanical)', 'es' => 'fuerza de tensado', 'not' => array( 'voltaje', 'tirantez' ) ),
	array( 'en' => 'actuation systems', 'es' => 'sistemas de actuación', 'not' => array( 'sistemas de activación', 'sistemas de accionado' ) ),
	array( 'en' => 'controls (control systems)', 'es' => 'sistemas de control', 'not' => array( 'controladores', 'mandos de control' ) ),
	array( 'en' => 'higher-level control system', 'es' => 'sistema de control de nivel superior', 'not' => array( 'sistema de control más alto' ) ),
	array( 'en' => 'adaptive speed control', 'es' => 'regulación adaptativa de velocidad', 'not' => array( 'control de velocidad adaptable' ) ),
	array( 'en' => 'infinitely variable', 'es' => 'de regulación continua', 'not' => array( 'infinitamente variable' ) ),
	array( 'en' => 'automated handling cells', 'es' => 'células automatizadas de manipulación', 'not' => array( 'celdas de manejo automatizado' ) ),
	array( 'en' => 'stand-alone machine', 'es' => 'máquina autónoma', 'not' => array( 'máquina independiente', 'máquina de pie solo' ) ),
	array( 'en' => 'test benches / test stands', 'es' => 'bancos de ensayo', 'not' => array( 'bancos de pruebas', 'bancadas de prueba' ) ),
	array( 'en' => 'Test Bay Erection and Modernization', 'es' => 'Montaje y modernización de bancos de ensayo', 'not' => array( 'Erección y modernización de salas de prueba' ) ),
	array( 'en' => 'special test facilities', 'es' => 'instalaciones de ensayo especiales', 'not' => array( 'instalaciones de prueba especializadas' ) ),
	array( 'en' => 'testing', 'es' => 'ensayos', 'not' => array( 'testeo', 'testado' ) ),
	array( 'en' => 'EMC darkroom', 'es' => 'cámara anecoica de CEM', 'not' => array( 'cuarto oscuro CEM', 'cámara oscura de compatibilidad' ) ),
	array( 'en' => 'exhaust extraction', 'es' => 'extracción de gases de escape', 'not' => array( 'extracción de escape', 'evacuación de humos' ) ),
	array( 'en' => 'audit stations', 'es' => 'estaciones de auditoría', 'not' => array( 'puestos de control', 'estaciones de inspección' ) ),
	array( 'en' => 'fixed stations', 'es' => 'estaciones fijas', 'not' => array( 'estaciones estacionarias' ) ),
	array( 'en' => 'mobile carousels', 'es' => 'carruseles móviles', 'not' => array( 'carruseles portátiles' ) ),
	array( 'en' => 'movable cradle', 'es' => 'cuna móvil', 'not' => array( 'base móvil', 'soporte desplazable' ) ),
	array( 'en' => 'Vibration Absorbing Cast', 'es' => 'Fundición absorbente de vibraciones', 'not' => array( 'Fundición amortiguadora de vibraciones' ) ),
	array( 'en' => 'Magnetizing System for Permanent Magnets', 'es' => 'Sistema de magnetización para imanes permanentes', 'not' => array( 'Sistema magnetizador de imanes fijos' ) ),

	// --- Aerospace ---
	array( 'en' => 'Aerospace & industrials', 'es' => 'Aeroespacial e industrial', 'not' => array( 'Aeronáutica e industria', 'Sector aeroespacial e industrias', 'Aviación e industrial' ) ),
	array( 'en' => 'rotor wing aircraft', 'es' => 'aeronaves de ala rotatoria', 'not' => array( 'aviones de hélice', 'aeronaves de hélice' ) ),
	array( 'en' => 'landing gear systems', 'es' => 'sistemas de tren de aterrizaje', 'not' => array( 'sistemas de engranaje de aterrizaje' ) ),
	array( 'en' => 'HMU/FMU', 'es' => 'unidades HMU/FMU', 'not' => array( 'unidades hidráulicas y neumáticas' ) ),
	array( 'en' => 'lube & scavenge pumps', 'es' => 'bombas de lubricación y recuperación de aceite', 'not' => array( 'bombas de lubricación y purga', 'bombas de engrase y venteo' ) ),
	array( 'en' => 'cargo loading systems', 'es' => 'sistemas de carga de mercancías', 'not' => array( 'sistemas de carga de cargamento' ) ),
	array( 'en' => 'power drive units', 'es' => 'unidades motrices (PDU)', 'not' => array( 'unidades de accionamiento de potencia' ) ),
	array( 'en' => 'MRO', 'es' => 'organizaciones MRO', 'not' => array( 'servicio y repuestos', 'mantenimiento y reparación general' ) ),
	array( 'en' => 'oil drain', 'es' => 'drenaje de aceite', 'not' => array( 'orificio de ventilación', 'purga de aire' ) ),

	// --- Agricultural, construction and mobile equipment ---
	array( 'en' => 'off-highway', 'es' => 'maquinaria fuera de carretera', 'not' => array( 'vehículos especiales', 'maquinaria de obra', 'fuera de autopista' ) ),
	array( 'en' => 'implements', 'es' => 'aperos', 'not' => array( 'implementos', 'utensilios' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'es' => 'Aperos: fin de línea', 'not' => array( 'Implementos: fin de línea' ) ),
	array( 'en' => 'motor grader', 'es' => 'motoniveladora', 'not' => array( 'niveladora a motor', 'raspadora' ) ),
	array( 'en' => 'excavator', 'es' => 'excavadora', 'not' => array(  ) ),
	array( 'en' => 'backhoe', 'es' => 'retroexcavadora mixta', 'not' => array( 'excavadora trasera' ) ),
	array( 'en' => 'baler', 'es' => 'empacadora', 'not' => array( 'prensadora', 'enfardadora de chatarra' ) ),
	array( 'en' => 'combine (harvester)', 'es' => 'cosechadora', 'not' => array( 'empacadora de cosecha' ) ),
	array( 'en' => 'draper header', 'es' => 'cabezal de cinta', 'not' => array( 'cabezal cortina', 'esparcidor' ) ),
	array( 'en' => 'hay mower', 'es' => 'segadora', 'not' => array( 'cortacésped de heno', 'guadañadora de forraje' ) ),
	array( 'en' => 'sprayers', 'es' => 'pulverizadores', 'not' => array( 'rociadores', 'atomizadores agrícolas' ) ),
	array( 'en' => 'blade (grader)', 'es' => 'hoja niveladora', 'not' => array( 'cuchilla de afeitar', 'aspa' ) ),
	array( 'en' => 'blade timing', 'es' => 'tiempo de ciclo de la hoja', 'not' => array( 'sincronización de la cuchilla' ) ),
	array( 'en' => 'PTO (power take-off)', 'es' => 'toma de fuerza (TDF)', 'not' => array( 'toma de poder', 'eje receptor de potencia' ) ),
	array( 'en' => 'boring drill (HDD)', 'es' => 'perforadora horizontal dirigida', 'not' => array( 'broca perforadora', 'taladro de barrenado' ) ),
	array( 'en' => 'mudding system (HDD)', 'es' => 'sistema de lodos de perforación', 'not' => array( 'sistema de barro', 'sistema de fango' ) ),
	array( 'en' => 'keg', 'es' => 'barril', 'not' => array( 'tonel pequeño' ) ),
	array( 'en' => 'keg finger holes', 'es' => 'asas embutidas del barril', 'not' => array( 'agujeros de dedo', 'orificios digitales' ) ),
	array( 'en' => 'water meter', 'es' => 'contador de agua', 'not' => array( 'medidor de agua', 'caudalímetro doméstico' ) ),
	array( 'en' => 'heavy-duty', 'es' => 'de servicio pesado', 'not' => array( 'de trabajo duro' ) ),

	// --- Manufacturing, operations and commercial vocabulary ---
	array( 'en' => 'throughput', 'es' => 'productividad de la línea', 'not' => array( 'caudal de producción', 'rendimiento de paso', 'flujo de salida' ) ),
	array( 'en' => 'high production / high-volume production', 'es' => 'producción de gran serie', 'not' => array( 'producción de alto volumen', 'producción de alta tasa' ) ),
	array( 'en' => 'high-mix, low-volume', 'es' => 'gran variedad y series cortas', 'not' => array( 'alta mezcla y bajo volumen' ) ),
	array( 'en' => 'volume flexibility', 'es' => 'flexibilidad de volumen de serie', 'not' => array( 'flexibilidad de volúmenes' ) ),
	array( 'en' => 'factory floor', 'es' => 'planta de producción', 'not' => array( 'suelo de fábrica', 'piso de planta' ) ),
	array( 'en' => 'capital equipment', 'es' => 'bienes de equipo', 'not' => array( 'equipos de capital', 'equipamiento capital' ) ),
	array( 'en' => 'machine health', 'es' => 'estado de las máquinas', 'not' => array( 'salud de la máquina', 'salud de los equipos' ) ),
	array( 'en' => 'health checks', 'es' => 'revisiones del estado técnico', 'not' => array( 'chequeos de salud', 'controles sanitarios' ) ),
	array( 'en' => 'commissioning', 'es' => 'puesta en marcha', 'not' => array( 'comisionamiento', 'encargo de la instalación' ) ),
	array( 'en' => 'deployment', 'es' => 'puesta en servicio', 'not' => array( 'despliegue', 'implantación técnica' ) ),
	array( 'en' => 'design (of a machine)', 'es' => 'diseño constructivo', 'not' => array( 'proyecto de la máquina' ) ),
	array( 'en' => 'footprint (floor area)', 'es' => 'superficie ocupada', 'not' => array( 'huella', 'pisada' ) ),
	array( 'en' => 'load capacity', 'es' => 'capacidad de carga', 'not' => array( 'capacidad volumétrica' ) ),
	array( 'en' => 'weight capacity', 'es' => 'capacidad de peso', 'not' => array( 'capacidad de levantamiento' ) ),
	array( 'en' => 'idle duration', 'es' => 'tiempo a ralentí', 'not' => array( 'duración de inactividad', 'tiempo ocioso' ) ),
	array( 'en' => 'soak time', 'es' => 'tiempo de estabilización térmica', 'not' => array( 'tiempo de remojo', 'tiempo de empapado' ) ),
	array( 'en' => 'process recipe', 'es' => 'receta de proceso', 'not' => array( 'prescripción de proceso' ) ),
	array( 'en' => 'lubrication', 'es' => 'lubricación', 'not' => array( 'cambio de aceite', 'engrase periódico' ) ),
	array( 'en' => 'energy recuperation', 'es' => 'recuperación de energía', 'not' => array( 'regeneración de energía' ) ),
	array( 'en' => 'water-cooled', 'es' => 'refrigerado por agua', 'not' => array( 'enfriador de agua', 'que enfría el agua' ) ),
	array( 'en' => 'obsolescence management', 'es' => 'gestión de la obsolescencia', 'not' => array( 'gestión de lo obsoleto' ) ),
	array( 'en' => 'maintenance contracts', 'es' => 'contratos de mantenimiento', 'not' => array( 'contratos de conservación' ) ),
	array( 'en' => 'warranty coverage', 'es' => 'cobertura de la garantía', 'not' => array( 'seguro de garantía', 'póliza de garantía' ) ),
	array( 'en' => 'failure rates', 'es' => 'tasa de calibraciones no conformes', 'not' => array( 'tasas de avería', 'índices de fracaso' ) ),
	array( 'en' => 'reportable', 'es' => 'documentable', 'not' => array( 'reportable', 'informable' ) ),
	array( 'en' => 'traceable tests', 'es' => 'ensayos trazables', 'not' => array( 'pruebas rastreables', 'ensayos seguibles' ) ),
	array( 'en' => 'defensible (results)', 'es' => 'defendibles ante una auditoría', 'not' => array( 'defendibles sin más' ) ),
	array( 'en' => 'validate performance', 'es' => 'validar el rendimiento', 'not' => array( 'verificar la productividad' ) ),
	array( 'en' => 'performance', 'es' => 'rendimiento', 'not' => array( 'desempeño' ) ),
	array( 'en' => 'features', 'es' => 'características', 'not' => array( 'rasgos', 'prestaciones adicionales' ) ),
	array( 'en' => 'applications (use cases)', 'es' => 'aplicaciones', 'not' => array( 'solicitudes', 'apps' ) ),
	array( 'en' => 'operations', 'es' => 'actividad', 'not' => array( 'operaciones quirúrgicas' ) ),
	array( 'en' => 'insights', 'es' => 'análisis', 'not' => array( 'perspicacias', 'insights', 'entendimientos' ) ),
	array( 'en' => 'actionable insights', 'es' => 'conclusiones prácticas', 'not' => array( 'información accionable', 'conocimientos accionables' ) ),
	array( 'en' => 'expert insights', 'es' => 'análisis de nuestros expertos', 'not' => array( 'perspicacias expertas' ) ),
	array( 'en' => 'fully loaded test', 'es' => 'ensayo a plena carga', 'not' => array( 'ensayo completo', 'prueba totalmente cargada' ) ),
	array( 'en' => 'Addresses', 'es' => 'Corrige', 'not' => array( 'Elimina', 'Erradica', 'Suprime' ) ),
	array( 'en' => 'discrete industries', 'es' => 'sectores de fabricación discreta', 'not' => array( 'industrias discretas', 'sectores discretos' ) ),
	array( 'en' => 'marine (sector)', 'es' => 'sector naval', 'not' => array( 'sector marino', 'navegación' ) ),
	array( 'en' => 'life sciences', 'es' => 'ciencias de la vida', 'not' => array( 'ciencias naturales', 'ciencias de la salud' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'es' => 'talleres de remanufactura y reconstrucción', 'not' => array( 'refabricantes y reconstructores' ) ),
	array( 'en' => 'remarketers', 'es' => 'comercializadores de flotas de segunda mano', 'not' => array( 'remarketers', 'revendedores secundarios' ) ),
	array( 'en' => 'right-shoring', 'es' => 'right-shoring', 'not' => array( 'deslocalización óptima', 'relocalización adecuada' ) ),
	array( 'en' => 'landed cost model', 'es' => 'modelo de coste puesto en destino', 'not' => array( 'modelo de coste de envío', 'modelo de coste aterrizado' ) ),
	array( 'en' => 'tariffs', 'es' => 'aranceles', 'not' => array( 'tarifas', 'tasas de precio' ) ),
	array( 'en' => 'customer journey', 'es' => 'etapas de la colaboración', 'not' => array( 'viaje del cliente', 'recorrido del cliente' ) ),
	array( 'en' => 'site visit', 'es' => 'visita a las instalaciones', 'not' => array( 'visita al sitio', 'visita del terreno' ) ),
	array( 'en' => 'field agents', 'es' => 'técnicos de campo', 'not' => array( 'agentes de campo', 'agentes comerciales' ) ),
	array( 'en' => 'service professional', 'es' => 'especialista de servicio', 'not' => array( 'profesional del servicio' ) ),
	array( 'en' => 'high-performance teams', 'es' => 'equipos de alto rendimiento', 'not' => array( 'equipos de alta performance' ) ),
	array( 'en' => 'like-minded companies', 'es' => 'empresas con una visión afín', 'not' => array( 'empresas de mentalidad similar', 'empresas con ideas afines' ) ),
	array( 'en' => 'peers', 'es' => 'otros profesionales del sector', 'not' => array( 'pares', 'iguales', 'compañeros de edad' ) ),
	array( 'en' => 'opportunities', 'es' => 'oportunidades', 'not' => array( 'oportunidades (posibilidades)', 'chances' ) ),
	array( 'en' => 'responsive', 'es' => 'de respuesta rápida', 'not' => array( 'responsivo', 'adaptable a pantalla' ) ),
	array( 'en' => 'seamless link', 'es' => 'enlace fluido', 'not' => array( 'vínculo sin costuras', 'conector directo' ) ),
	array( 'en' => 'turnkey', 'es' => 'llave en mano', 'not' => array( 'turnkey', 'de llave y mano' ) ),
	array( 'en' => 'built to last', 'es' => 'diseñado para durar', 'not' => array( 'construido a lo largo', 'hecho para largo' ) ),
	array( 'en' => 'ultra-stable design', 'es' => 'construcción extraordinariamente estable', 'not' => array( 'diseño ultraduradero' ) ),
	array( 'en' => 'Standardization at scale', 'es' => 'Estandarización a gran escala', 'not' => array( 'Estandarización a escala' ) ),
	array( 'en' => 'uptime across systems', 'es' => 'disponibilidad de los sistemas', 'not' => array( 'tiempo activo en todos los sistemas' ) ),
	array( 'en' => 'unbeatable deals', 'es' => 'ofertas inmejorables', 'not' => array( 'tratos imbatibles', 'ofertas no concluidas' ) ),
	array( 'en' => 'learning management system (LMS)', 'es' => 'sistema de gestión de la formación (LMS)', 'not' => array( 'sistema de gestión del aprendizaje' ) ),
	array( 'en' => 'branch', 'es' => 'espacio del LMS', 'not' => array( 'sucursal' ) ),
	array( 'en' => 'mental health care', 'es' => 'atención de salud mental', 'not' => array( 'atención sanitaria remota', 'cuidado mental a distancia' ) ),
	array( 'en' => 'disability insurance', 'es' => 'seguro de incapacidad laboral', 'not' => array( 'pensión de invalidez', 'seguro de discapacidad' ) ),
	array( 'en' => 'Careers', 'es' => 'Empleo', 'not' => array( 'Carreras', 'Trayectorias profesionales' ) ),
	array( 'en' => 'Leadership', 'es' => 'Equipo directivo', 'not' => array( 'Liderazgo', 'Dirección superior', 'Alta gerencia' ) ),
	array( 'en' => 'Corporate Roles', 'es' => 'Dirección corporativa', 'not' => array( 'Funciones corporativas', 'Roles corporativos' ) ),
	array( 'en' => 'President (of a company)', 'es' => 'presidente', 'not' => array( 'jefe del Estado' ) ),
	array( 'en' => 'Board Member', 'es' => 'miembro del consejo de administración', 'not' => array( 'miembro de la junta directiva', 'consejero delegado' ) ),
	array( 'en' => 'Principal', 'es' => 'Principal', 'not' => array( 'Director principal de inversiones', 'Jefe principal' ) ),
	array( 'en' => 'associate attorney', 'es' => 'abogado asociado', 'not' => array( 'ayudante de abogado', 'pasante jurídico' ) ),
	array( 'en' => 'events & conferences', 'es' => 'eventos y congresos', 'not' => array( 'fiestas y conferencias' ) ),
	array( 'en' => 'Introducing', 'es' => 'Presentamos', 'not' => array( 'Novedad', 'Introduciendo' ) ),
	array( 'en' => 'is now', 'es' => 'ahora es', 'not' => array( 'es ahora mismo' ) ),
	array( 'en' => 'Featuring: <Brand>', 'es' => 'Con tecnología de <Brand>', 'not' => array( 'Presentando:', 'Con la participación de' ) ),
	array( 'en' => 'Powered by', 'es' => 'Con tecnología de', 'not' => array( 'Alimentado por', 'Energizado por' ) ),
	array( 'en' => 'patented', 'es' => 'patentado', 'not' => array( 'con patente pendiente' ) ),
	array( 'en' => 'represent (model a process)', 'es' => 'reproducir', 'not' => array( 'representar' ) ),

	// --- Legal, contractual and corporate-information strings ---
	array( 'en' => 'Imprint', 'es' => 'Aviso legal', 'not' => array( 'Imprint', 'Pie de imprenta', 'Impresión' ) ),
	array( 'en' => 'Terms', 'es' => 'Términos y condiciones', 'not' => array(  ) ),
	array( 'en' => 'Email Disclosure', 'es' => 'Cláusula de confidencialidad del correo electrónico', 'not' => array( 'Divulgación de correo electrónico', 'Revelación del correo' ) ),
	array( 'en' => 'personal information / personal data', 'es' => 'datos personales', 'not' => array( 'información personal', 'informaciones privadas' ) ),
	array( 'en' => 'GDPR', 'es' => 'RGPD', 'not' => array( 'GDPR', 'GPDR' ) ),
	array( 'en' => 'Register (a legal register)', 'es' => 'Registro', 'not' => array(  ) ),
	array( 'en' => 'Registered office', 'es' => 'Domicilio social', 'not' => array( 'Oficina registrada', 'Sede registrada' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'es' => 'Kruispuntbank van Ondernemingen', 'not' => array( 'Banco de Cruce de Empresas', 'Registro Mercantil belga' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'es' => 'Cámara de Comercio (KvK)', 'not' => array( 'Cámara de Comercio e Industria (KvK)' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'es' => 'naamloze vennootschap', 'not' => array( 'sociedad anónima neerlandesa' ) ),
	array( 'en' => 'Netherlands (statutory)', 'es' => 'Países Bajos', 'not' => array( 'Holanda' ) ),
	array( 'en' => 'England', 'es' => 'Inglaterra', 'not' => array( 'England' ) ),
	array( 'en' => 'West Flanders', 'es' => 'Flandes Occidental', 'not' => array( 'West Flanders', 'Flandes del Oeste' ) ),
	array( 'en' => 'Poland', 'es' => 'Polonia', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Bristol', 'es' => 'Bristol', 'not' => array( 'Brístol' ) ),
	array( 'en' => 'Jordan (country)', 'es' => 'Jordania', 'not' => array(  ) ),
	array( 'en' => 'WHEREAS (recital)', 'es' => 'CONSIDERANDO QUE', 'not' => array( 'MIENTRAS QUE', 'EN TANTO QUE' ) ),
	array( 'en' => 'RECITALS', 'es' => 'ANTECEDENTES', 'not' => array( 'RECITALES', 'CONSIDERANDOS PREVIOS' ) ),
	array( 'en' => 'Deliverables', 'es' => 'Entregables', 'not' => array( 'Resultados a entregar', 'Prestaciones entregables', 'Productos de entrega' ) ),
	array( 'en' => 'Work Product', 'es' => 'Producto del Trabajo', 'not' => array( 'Resultado Laboral', 'Obra de Trabajo' ) ),
	array( 'en' => 'Exhibit', 'es' => 'Anexo', 'not' => array( 'Exhibición', 'Apéndice numerado' ) ),
	array( 'en' => 'Section', 'es' => 'Cláusula', 'not' => array( 'Sección' ) ),
	array( 'en' => 'Ascential Indemnity', 'es' => 'Indemnización de Ascential', 'not' => array( 'Ascential Indemnity' ) ),
	array( 'en' => 'Name: (signature block)', 'es' => 'Nombre y apellidos:', 'not' => array( 'Denominación:', 'Razón social:' ) ),
	array( 'en' => 'Date: (signature block)', 'es' => 'Fecha:', 'not' => array( 'Datos:' ) ),
	array( 'en' => 'Labour & Travel', 'es' => 'Mano de obra y desplazamientos', 'not' => array( 'Trabajo y viajes', 'Labor y viaje' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'es' => 'Directiva de máquinas 2006/42/CE', 'not' => array( 'Directiva de maquinaria 2006/42/EC' ) ),
	array( 'en' => 'For Immediate Release', 'es' => 'Nota de prensa para publicación inmediata', 'not' => array( 'Para difusión inmediata inmediata' ) ),
	array( 'en' => 'WCAG four principles', 'es' => 'Perceptible, operable, comprensible y robusto', 'not' => array( 'Percibible, Operable, Entendible, Fuerte' ) ),

	// --- UI, navigation and CTA labels ---
	array( 'en' => 'Explore', 'es' => 'Explore los recursos', 'not' => array( 'Explorar los recursos' ) ),
	array( 'en' => 'Explore the Catalog', 'es' => 'Explore el catálogo', 'not' => array( 'Explorar el catálogo', 'Consultar catálogo' ) ),
	array( 'en' => 'Browse catalog', 'es' => 'Explore el catálogo', 'not' => array( 'Explorar el catálogo', 'Consultar catálogo', 'Ver catálogo' ) ),
	array( 'en' => 'Browse full catalog', 'es' => 'Explore el catálogo completo', 'not' => array( 'Explorar el catálogo completo', 'Ver todo el catálogo' ) ),
	array( 'en' => 'Browse all resources', 'es' => 'Explore todos los recursos', 'not' => array( 'Explorar todos los recursos', 'Todos los recursos' ) ),
	array( 'en' => 'View all resources', 'es' => 'Vea todos los recursos', 'not' => array( 'Ver todos los recursos' ) ),
	array( 'en' => 'View all press releases', 'es' => 'Vea todos los comunicados', 'not' => array( 'Ver todos los comunicados', 'Ver todas las notas' ) ),
	array( 'en' => 'View all events', 'es' => 'Vea todos los eventos', 'not' => array( 'Ver todos los eventos' ) ),
	array( 'en' => 'Read more', 'es' => 'Lea más', 'not' => array( 'Leer más', 'Ver más' ) ),
	array( 'en' => 'Read the article', 'es' => 'Lea el artículo', 'not' => array( 'Leer el artículo', 'Leer artículo' ) ),
	array( 'en' => 'Read the announcement', 'es' => 'Lea el anuncio', 'not' => array( 'Leer el anuncio' ) ),
	array( 'en' => 'Request a quote', 'es' => 'Solicite un presupuesto', 'not' => array( 'Solicitar un presupuesto', 'Pedir presupuesto', 'Solicitud de presupuesto' ) ),
	array( 'en' => 'Get a quote', 'es' => 'Solicite un presupuesto', 'not' => array( 'Obtenga una cotización', 'Consiga presupuesto' ) ),
	array( 'en' => 'Request a demo', 'es' => 'Solicite una demostración', 'not' => array( 'Solicitar una demostración', 'Pedir demo', 'Solicitud de demostración' ) ),
	array( 'en' => 'Speak with an Expert', 'es' => 'Hable con un experto', 'not' => array( 'Hablar con un experto', 'Contacte a un experto' ) ),
	array( 'en' => 'Download', 'es' => 'Descargue el folleto', 'not' => array( 'Bajar el folleto', 'Descarga del folleto' ) ),
	array( 'en' => 'Register (event CTA)', 'es' => 'Regístrese', 'not' => array( 'Registrarse' ) ),
	array( 'en' => 'Schedule a Meeting', 'es' => 'Concierte una reunión', 'not' => array( 'Programar una reunión', 'Agendar una cita' ) ),
	array( 'en' => 'Contact us', 'es' => 'Contáctenos', 'not' => array( 'Contactar', 'Póngase en contacto con nosotros' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'es' => '¿Listo para modernizar su infraestructura?', 'not' => array( '¿Preparado para actualizar tu infraestructura?' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'es' => 'Buscar en ascentialtech.com', 'not' => array( 'Searching ascentialtech.com', 'Buscando en ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'es' => 'Vista de calendario no disponible', 'not' => array( 'Calendar View Unavailable' ) ),
	array( 'en' => 'Play', 'es' => 'Reproducir', 'not' => array( 'Play', 'Jugar' ) ),
	array( 'en' => 'Listen to this article', 'es' => 'Escuche este artículo', 'not' => array( 'Listen to this article', 'Escuchar este artículo' ) ),
	array( 'en' => 'N chapters', 'es' => 'N capítulos', 'not' => array( 'chapters' ) ),
	array( 'en' => 'Share / Copy link / Email', 'es' => 'Compartir / Copiar enlace / Enviar por correo', 'not' => array( 'Copy link', 'Compartir / Copiar link' ) ),
	array( 'en' => 'Products', 'es' => 'Productos', 'not' => array( 'Producto s' ) ),
	array( 'en' => 'Product Catalog', 'es' => 'Catálogo de productos', 'not' => array(  ) ),
	array( 'en' => 'Resource Type', 'es' => 'Tipo de recurso', 'not' => array( 'Resource Type' ) ),
	array( 'en' => 'Resource Topic', 'es' => 'Tema del recurso', 'not' => array( 'Resource Topic' ) ),
	array( 'en' => 'Brand', 'es' => 'Marca', 'not' => array(  ) ),
	array( 'en' => 'Case Study', 'es' => 'Caso de éxito', 'not' => array( 'Case Study', 'Estudio de caso' ) ),
	array( 'en' => 'Technical Papers', 'es' => 'Documentos técnicos', 'not' => array( 'Technical Papers', 'Papeles técnicos' ) ),
	array( 'en' => 'Whitepapers', 'es' => 'Informes técnicos', 'not' => array( 'Libros blancos', 'Informes solos' ) ),
	array( 'en' => 'Press Announcements', 'es' => 'Notas de prensa', 'not' => array( 'Press Announcements', 'Anuncios de prensa' ) ),
	array( 'en' => 'Ebooks', 'es' => 'Libros electrónicos', 'not' => array( 'Ebooks', 'E-libros' ) ),
	array( 'en' => 'Webinars', 'es' => 'Seminarios web', 'not' => array( 'Webinarios', 'Webinars' ) ),
	array( 'en' => 'Blog', 'es' => 'Blog', 'not' => array( 'Bitácora' ) ),
	array( 'en' => 'Supply Chain', 'es' => 'Cadena de suministro', 'not' => array( 'Supply Chain', 'Cadena de abastecimiento' ) ),
	array( 'en' => 'Global Supply Chain Requirements', 'es' => 'Requisitos de la cadena de suministro global', 'not' => array( 'Global Supply Chain Requirements' ) ),
	array( 'en' => 'Support Services', 'es' => 'Servicios de asistencia', 'not' => array( 'Support Services', 'Servicios de soporte' ) ),
	array( 'en' => 'support', 'es' => 'asistencia', 'not' => array( 'soporte', 'soporte técnico' ) ),
	array( 'en' => 'Machine Analytics', 'es' => 'Análisis de máquinas', 'not' => array( 'Machine Analytics', 'Analítica de máquina' ) ),
	array( 'en' => 'Engineering Services', 'es' => 'Servicios de ingeniería', 'not' => array( 'Engineering Services' ) ),
	array( 'en' => 'Electrical Testing', 'es' => 'Ensayos eléctricos', 'not' => array( 'Electrical Testing', 'Pruebas eléctricas' ) ),
	array( 'en' => 'Assembly', 'es' => 'Montaje', 'not' => array( 'Ensamblaje', 'Ensamble' ) ),
	array( 'en' => 'Core / Plus / Elite (service tiers)', 'es' => 'Core, Plus, Elite', 'not' => array( 'Básico, Plus, Elite', 'Núcleo, Plus, Élite' ) ),
	array( 'en' => 'Priority 1/2/3', 'es' => 'Prioridad 1: alta / Prioridad 2: media / Prioridad 3: baja', 'not' => array( 'Prioridad alta de prioridad' ) ),
	array( 'en' => 'sales inquiry', 'es' => 'consulta de ventas', 'not' => array( 'consulta comercial', 'indagación de ventas' ) ),
	array( 'en' => 'Marketplace (spare parts)', 'es' => 'Marketplace de piezas de repuesto', 'not' => array( 'Mercado de repuestos', 'Tienda de recambios' ) ),
	array( 'en' => 'Medical', 'es' => 'Medicina', 'not' => array( 'Médico', 'Médica' ) ),
	array( 'en' => '<Model> Refrigerant Charging Brochure', 'es' => 'Folleto <Model>: carga de refrigerante', 'not' => array( 'Folleto de recarga de refrigerante' ) ),
	array( 'en' => 'Titan <Application> System', 'es' => 'Sistema Titan para <aplicación>', 'not' => array( 'Titan System' ) ),
	array( 'en' => 'Reload stylesheet', 'es' => 'Recargar hoja de estilos', 'not' => array( 'Recargar estilo' ) ),
	array( 'en' => 'LPM (litres per minute)', 'es' => 'l/min', 'not' => array(  ) ),
);
