<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * Spanish term base (en -> es). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Built 2026-09-25 from the site concept list plus a live
 * sample of /es/ catalog, transportation, care, resource-hub and
 * aerospace-industrials pages.
 */
return array(
	array( 'en' => '*', 'es' => 'The whole site is formal peninsular Spanish and addresses the reader as usted (plural ustedes) in every string and every slot: body copy, headings, eyebrows, all-caps bands, form labels, placeholders, alt and aria text, the <title>, the meta description, og: tags and JSON-LD. Register is a property of the PAGE, not of the segment, so a tu-form in a meta description contradicts the usted body it ships with. Buttons, card CTAs and link labels keep the verb of the English and take the imperative-usted, which is this site\'s established web-UI convention: "Browse catalog" is "Explore el catálogo", "Request a demo" is "Solicite una demostración", "Download" is "Descargue el folleto", "Contact us" is "Contáctenos", "Read the article" is "Lea el artículo", "Speak with an expert" is "Hable con un experto". Never flatten a verb label into a bare noun ("Catálogo", "Descarga", "Solicitud de demostración" are wrong for those) and never mix the infinitive into a group where the siblings are imperative. Never address the reader with tú or vosotros anywhere, at any length, including short CTAs, headlines and metadata.', 'not' => array( 'tuyo', 'tuya', 'tuyos', 'tuyas', 'vosotros', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'puedes', 'podéis', 'necesitas', 'necesitáis', 'tienes', 'tenéis', 'quieres', 'queréis', 'estás', 'estáis', 'sabes', 'sabéis', 'debes', 'debéis', 'haces', 'hacéis', 'buscas', 'buscáis', 'contáctanos', 'regístrate', 'suscríbete', 'inscríbete', 'descárgalo', 'descárgala', 'conócenos', 'llámanos', 'escríbenos', 'cuéntanos', 'únete', 'tu empresa', 'tu equipo', 'tu negocio', 'tu inversión', 'tus equipos', 'tus necesidades', 'tus datos' ) ),

	// --- Brands, entities, trademarks and model codes: never translated ---
	array( 'en' => 'Ascential Technologies', 'es' => 'Ascential Technologies', 'not' => array( 'Tecnologías Ascential' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'es' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Ensayo y Medida', 'Ascential de Ensayo y Medida', 'Ascential Sistemas de Ensayo y Medida' ) ),
	array( 'en' => 'Ascential Care', 'es' => 'Ascential Care', 'not' => array( 'Atención Ascential', 'Cuidado Ascential' ) ),
	array( 'en' => 'Ascentialytics', 'es' => 'Ascentialytics', 'not' => array( 'Analítica Ascential' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'es' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDICINA Y CIENCIAS DE LA VIDA', 'Ascential Medicina y Ciencias de la Vida', 'Ciencias de la Salud y de la Vida' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'es' => 'Burke E. Porter Machinery', 'not' => array( 'Maquinaria Burke E. Porter', 'Burke E. Porter Maquinaria' ) ),
	array( 'en' => 'Burke Porter Group', 'es' => 'Burke Porter Group', 'not' => array( 'Grupo Burke Porter' ) ),
	array( 'en' => 'Universal Balancing', 'es' => 'Universal Balancing', 'not' => array( 'Equilibrado universal', 'Equilibrado Universal', 'Equilibrados universales' ) ),
	array( 'en' => 'XL Machine', 'es' => 'XL Machine', 'not' => array( 'Máquina XL', 'Máquinas XL' ) ),
	array( 'en' => 'WinterPark Engineering', 'es' => 'WinterPark Engineering', 'not' => array( 'Ingeniería WinterPark', 'WinterPark Ingeniería' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'es' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Cía. S.L.', 'H. Kleinknecht y Compañía' ) ),
	array( 'en' => 'Kleinknecht Testing Technology', 'es' => 'Tecnología de ensayo de Kleinknecht', 'not' => array( 'Kleinknecht Tecnología de ensayo', 'Tecnología de ensayo Kleinknecht' ) ),
	array( 'en' => 'Bauer', 'es' => 'Bauer', 'not' => array( 'Bauer, S.A.' ) ),
	array( 'en' => 'Cimat', 'es' => 'Cimat', 'not' => array( 'CIMAT Equilibrado' ) ),
	array( 'en' => 'Titan', 'es' => 'Titan', 'not' => array( 'Titán' ) ),
	array( 'en' => 'Sentia', 'es' => 'Sentia', 'not' => array( 'Sencia' ) ),
	array( 'en' => 'Marketplace', 'es' => 'Marketplace de piezas de repuesto', 'not' => array( 'Mercado', 'Tienda', 'Lonja', 'Mercado de repuestos', 'Tienda de recambios', 'Marketplace' ) ),
	array( 'en' => 'ADAS Garage', 'es' => 'ADAS Garage', 'not' => array( 'Taller ADAS', 'Garaje ADAS' ) ),
	array( 'en' => 'Ask Burke Porter', 'es' => 'Ask Burke Porter', 'not' => array( 'Pregunte a Burke Porter', 'Pregunta a Burke Porter' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'es' => 'ADVANCING THE MACHINE', 'not' => array( 'HACIENDO AVANZAR LA MÁQUINA', 'IMPULSANDO LA MÁQUINA' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'es' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'SOLUCIONES INTEGRALES DE COMERCIALIZACIÓN' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'es' => 'A DESIGN / B LOGO', 'not' => array( 'DISEÑO A', 'LOGOTIPO B' ) ),
	array( 'en' => 'Impossible? Done.', 'es' => 'Impossible? Done.', 'not' => array( '¿Imposible? Hecho.', 'Imposible. Hecho.' ) ),
	array( 'en' => 'Calibration-as-a-Service™', 'es' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Calibración como servicio™', 'Calibración como Servicio™' ) ),
	array( 'en' => 'Balancing as a Service (BaaS)', 'es' => 'Balancing as a Service (BaaS)', 'not' => array( 'Equilibrado por contrato como servicio (BaaS)', 'equilibrado como servicio (BaaS)' ) ),
	array( 'en' => 'CMT-TR Polimer', 'es' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR de polímero', 'equilibradora de rotores de polímero CMT-TR', 'Máquina equilibradora de rotores de polímero CMT-TR' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'es' => 'Turbo Test Duo Expert', 'not' => array( 'Experto Turbo Test Duo', 'TURBO TEST DUO Experto' ) ),
	array( 'en' => 'First Alert Monitoring System', 'es' => 'sistema de monitorización First Alert', 'not' => array( 'sistema de alerta temprana', 'sistema de monitorización de primera alerta' ) ),
	array( 'en' => 'eRotor', 'es' => 'eRotor', 'not' => array( 'rotor eléctrico', 'rotor-e' ) ),
	array( 'en' => 'Cerberus X1', 'es' => 'Cerberus X1', 'not' => array( 'Cerbero X1' ) ),
	array( 'en' => 'Connect on LinkedIn', 'es' => 'Perfil en LinkedIn', 'not' => array( 'Connect on LinkedIn', 'Conecta en LinkedIn', 'Conéctese en LinkedIn' ) ),

	// --- Balancing and rotating machinery ---
	array( 'en' => 'unbalance', 'es' => 'desequilibrio', 'not' => array( 'desbalance', 'desbalanceo', 'falta de equilibrio' ) ),
	array( 'en' => 'residual unbalance', 'es' => 'desequilibrio residual', 'not' => array( 'desbalance residual', 'desequilibrio remanente' ) ),
	array( 'en' => 'balancing', 'es' => 'equilibrado', 'not' => array( 'balanceo', 'balanceado' ) ),
	array( 'en' => 'balancing machine', 'es' => 'equilibradora', 'not' => array( 'máquina de balanceo', 'balanceadora', 'máquina de equilibrado' ) ),
	array( 'en' => 'Balancing Machines', 'es' => 'Máquinas equilibradoras', 'not' => array( 'Máquinas de balanceo', 'Balanceadoras' ) ),
	array( 'en' => 'Automotive Industry Balancers', 'es' => 'Equilibradoras para la industria del automóvil', 'not' => array( 'Balanceadores para automoción' ) ),
	array( 'en' => 'Industrial Balancing Machine', 'es' => 'Equilibradora industrial', 'not' => array( 'Balanceadora industrial', 'Máquina de balanceo industrial', 'Máquinas equilibradoras industriales' ) ),
	array( 'en' => 'non-rotating balancing machine', 'es' => 'equilibradora sin rotación', 'not' => array( 'equilibradora sin rotor', 'equilibradora no giratoria', 'máquina de equilibrado sin rotor', 'equilibradora no rotativa' ) ),
	array( 'en' => 'Non-Rotate Systems', 'es' => 'Sistemas sin rotación', 'not' => array( 'Sistemas no rotativos', 'Sistemas sin giro' ) ),
	array( 'en' => 'Spin Testing', 'es' => 'Ensayos de centrifugado', 'not' => array( 'Pruebas de giro', 'Ensayos de hilado', 'Ensayos de rotación' ) ),
	array( 'en' => 'spin testing machine', 'es' => 'máquina de ensayos de centrifugado', 'not' => array( 'máquina de pruebas de giro', 'máquina de ensayos de rotación' ) ),
	array( 'en' => 'field balancing', 'es' => 'equilibrado in situ', 'not' => array( 'equilibrado de campo', 'equilibrado en el terreno' ) ),
	array( 'en' => 'Field Balancers', 'es' => 'Equipos de equilibrado in situ', 'not' => array( 'Equilibradores de campo', 'Equilibradoras de campo', 'Equilibradoras portátiles' ) ),
	array( 'en' => 'correction', 'es' => 'corrección', 'not' => array( 'rectificación del desequilibrio' ) ),
	array( 'en' => 'punching', 'es' => 'punzonado', 'not' => array( 'troquelado' ) ),
	array( 'en' => 'bearers', 'es' => 'apoyos', 'not' => array( 'rodamientos', 'portadores' ) ),
	array( 'en' => 'pedestals', 'es' => 'caballetes', 'not' => array( 'pedestales', 'columnas' ) ),
	array( 'en' => 'pins', 'es' => 'pasadores', 'not' => array( 'muñones', 'alfileres', 'clavijas' ) ),
	array( 'en' => 'bearing center lines', 'es' => 'ejes de los cojinetes', 'not' => array( 'líneas centrales de rodamiento', 'ejes de los muñones' ) ),
	array( 'en' => 'bearing life', 'es' => 'vida útil de los rodamientos', 'not' => array( 'vida del rodamiento', 'duración del rodamiento', 'vida útil del cojinete' ) ),
	array( 'en' => 'tapered roller bearing', 'es' => 'rodamiento de rodillos cónicos', 'not' => array( 'rodamiento de rodillos cilíndricos' ) ),
	array( 'en' => 'v-block support', 'es' => 'apoyo en bloque en V', 'not' => array( 'soporte de bloque V', 'bloques V' ) ),
	array( 'en' => 'burst proof protection', 'es' => 'protección contra estallido del rotor', 'not' => array( 'protección antiexplosión', 'protección a prueba de explosión' ) ),
	array( 'en' => 'maximum rotor diameter', 'es' => 'diámetro máximo del rotor', 'not' => array( 'tamaño máximo del rotor' ) ),
	array( 'en' => 'armature', 'es' => 'inducido', 'not' => array( 'armadura', 'rotor eléctrico' ) ),
	array( 'en' => 'Horizontal Manual - Electric Armatures', 'es' => 'Horizontal manual: inducidos eléctricos', 'not' => array( 'Manual horizontal: armaduras eléctricas' ) ),
	array( 'en' => 'pulley', 'es' => 'polea', 'not' => array( 'correa' ) ),
	array( 'en' => 'flywheel', 'es' => 'volante de inercia', 'not' => array( 'volante motor', 'rueda volante' ) ),
	array( 'en' => 'dual mass flywheel', 'es' => 'volante bimasa', 'not' => array( 'volante de doble masa', 'embrague bimasa', 'volante de inercia de doble masa' ) ),
	array( 'en' => 'flexplate', 'es' => 'placa flexible de arrastre', 'not' => array( 'placa flexible de embrague' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'es' => 'cilindros de transportador y cilindros papeleros', 'not' => array( 'rodillos de papel', 'transportador y rodillos de papel' ) ),
	array( 'en' => 'Turbocharger Balancers', 'es' => 'Equilibradoras de turbocompresores', 'not' => array( 'Balanceadoras de turbo' ) ),
	array( 'en' => 'Turbo Balancing Machine', 'es' => 'Equilibradora de turbocompresores', 'not' => array( 'Máquina de balanceo de turbos' ) ),
	array( 'en' => 'Rotor Balancing Machine', 'es' => 'Equilibradora de rotores', 'not' => array( 'Máquina de equilibrado de rotores', 'Máquina equilibradora de rotor' ) ),
	array( 'en' => 'High-Speed Core Balancing Machine', 'es' => 'Equilibradora de cartuchos a alta velocidad', 'not' => array( 'Máquina equilibradora de núcleo de alta velocidad', 'Equilibradora de núcleos a alta velocidad' ) ),
	array( 'en' => 'Low-Speed Core Balancing Machine', 'es' => 'Equilibradora de cartuchos a baja velocidad', 'not' => array( 'Máquina equilibradora de núcleo de baja velocidad', 'Equilibradora de núcleos a baja velocidad' ) ),
	array( 'en' => 'Combined Core and Rotor Balancing Machine', 'es' => 'Equilibradora combinada de cartuchos y rotores', 'not' => array( 'Máquina equilibradora combinada de núcleo y rotor', 'Equilibradora combinada de núcleos y rotores' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'es' => 'Equilibradora combinada de cartuchos a alta y baja velocidad', 'not' => array( 'Máquina equilibradora de núcleo de alta y baja velocidad combinadas', 'Equilibradora combinada de núcleos a alta y baja velocidad' ) ),
	array( 'en' => 'turbocharger flow bench', 'es' => 'banco de flujo para turbocompresores', 'not' => array( 'banco de ensayo de flujo', 'dinamómetro de turbocompresores' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'es' => 'banco de flujo dinámico para turbocompresores', 'not' => array(  ) ),
	array( 'en' => 'turbocharger frame size', 'es' => 'tamaño de carcasa del turbocompresor', 'not' => array( 'tamaño de bastidor', 'tamaño del marco' ) ),
	array( 'en' => 'turbo calibration', 'es' => 'calibración de turbocompresores', 'not' => array( 'equilibrado de turbocompresores' ) ),
	array( 'en' => 'boreless compressor wheel', 'es' => 'rueda de compresor sin taladro central', 'not' => array( 'turbocompresor sin cojinetes', 'rueda de compresor sin agujero' ) ),
	array( 'en' => 'whistle', 'es' => 'silbido', 'not' => array( 'zumbido', 'pitido' ) ),
	array( 'en' => 'vibration', 'es' => 'vibración', 'not' => array( 'oscilación', 'temblor' ) ),
	array( 'en' => 'kinetostatics', 'es' => 'cinetostática', 'not' => array( 'cinética' ) ),
	array( 'en' => 'Electronic hung mass', 'es' => 'compensación electrónica de masa suspendida', 'not' => array( 'masa colgada electrónica', 'masa suspendida electrónica' ) ),
	array( 'en' => 'in a single clamping', 'es' => 'en un solo amarre', 'not' => array( 'en una sola pinza', 'en un solo apriete', 'en una sola fijación' ) ),
	array( 'en' => 'single station / multi station', 'es' => 'de una estación / de varias estaciones', 'not' => array( 'de una cámara', 'monocámara', 'multicámara' ) ),
	array( 'en' => 'single bay', 'es' => 'de un solo puesto', 'not' => array( 'de una sola bahía', 'monocámara' ) ),
	array( 'en' => 'walking beam system', 'es' => 'sistema de vigas galopantes', 'not' => array( 'sistema de viga caminante', 'sistema de viga andante', 'sistema de viga transportadora' ) ),
	array( 'en' => 'motorized clamping', 'es' => 'amarre motorizado', 'not' => array( 'sujeción a motor', 'apriete motorizado' ) ),
	array( 'en' => 'custom fixturing', 'es' => 'utillaje a medida', 'not' => array( 'accesorios personalizados', 'fijaciones a medida' ) ),
	array( 'en' => 'setup cycles', 'es' => 'ciclos de preparación de pieza', 'not' => array( 'ciclos de montaje', 'ciclos de configuración' ) ),
	array( 'en' => 'active part probing', 'es' => 'palpado activo de la pieza', 'not' => array( 'sondeo activo de piezas' ) ),
	array( 'en' => 'aperture plate', 'es' => 'placa de apertura', 'not' => array( 'placa de abertura óptica' ) ),
	array( 'en' => 'anchoring', 'es' => 'anclaje', 'not' => array( 'amarre al suelo' ) ),

	// --- Automotive, powertrain, EOL and ADAS ---
	array( 'en' => 'transmission / gearbox', 'es' => 'caja de cambios', 'not' => array( 'transmisión automática de señal' ) ),
	array( 'en' => 'Powertrain', 'es' => 'Grupo motopropulsor', 'not' => array( 'Tren motriz', 'Tren de potencia', 'Cadena cinemática' ) ),
	array( 'en' => 'propulsion & powertrain', 'es' => 'propulsión y grupo motopropulsor', 'not' => array( 'propulsión y tren motriz', 'propulsión y transmisión' ) ),
	array( 'en' => 'driveshaft', 'es' => 'árbol de transmisión', 'not' => array( 'eje motriz', 'flecha de transmisión' ) ),
	array( 'en' => 'crankshaft', 'es' => 'cigüeñal', 'not' => array( 'árbol de manivelas', 'eje cigüeñal' ) ),
	array( 'en' => 'inline crankshaft', 'es' => 'cigüeñal en línea', 'not' => array( 'cigüeñal de cuatro tiempos' ) ),
	array( 'en' => 'single cylinder crankshaft', 'es' => 'cigüeñal monocilíndrico', 'not' => array( 'cigüeñal de una sola vía', 'cigüeñal unicilíndrico' ) ),
	array( 'en' => 'crankshaft lathe', 'es' => 'torno para cigüeñales', 'not' => array( 'torno para bielas' ) ),
	array( 'en' => 'dynamometer', 'es' => 'dinamómetro', 'not' => array( 'banco de potencia', 'freno dinamométrico' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'es' => 'dinamómetro de chasis de 2 y 4 ruedas', 'not' => array( 'dinamómetro de chasis de 2 y 4 ejes' ) ),
	array( 'en' => 'inline dyno', 'es' => 'dinamómetro en línea', 'not' => array( 'dinamómetro integrado' ) ),
	array( 'en' => 'steerable dyno', 'es' => 'dinamómetro para ruedas directrices', 'not' => array( 'dinamómetro direccional', 'dinamómetro orientable' ) ),
	array( 'en' => 'roller brake tester', 'es' => 'frenómetro de rodillos', 'not' => array( 'probador de frenos de rodillos', 'banco de frenos de rodillos' ) ),
	array( 'en' => 'roller', 'es' => 'rodillo', 'not' => array( 'cilindro de frenado' ) ),
	array( 'en' => 'retaining rollers', 'es' => 'rodillos de retención', 'not' => array( 'cilindros de retención', 'rodillos retenedores' ) ),
	array( 'en' => 'end of line testing', 'es' => 'ensayos de fin de línea', 'not' => array( 'pruebas de final de línea', 'ensayos al final de la línea', 'End of Line Testing' ) ),
	array( 'en' => 'Vehicles End-of-Line', 'es' => 'Fin de línea de vehículos', 'not' => array( 'Vehículos al final de línea', 'Vehículos de fin de línea', 'Final de línea de vehículos' ) ),
	array( 'en' => 'ADAS', 'es' => 'ADAS', 'not' => array( 'sistemas avanzados de apoyo al conductor' ) ),
	array( 'en' => 'ADAS alignment', 'es' => 'calibración ADAS', 'not' => array( 'alineación ADAS', 'alineado ADAS' ) ),
	array( 'en' => 'calibration target', 'es' => 'panel de calibración', 'not' => array( 'objetivo de calibración', 'diana de calibración' ) ),
	array( 'en' => 'probe alignment', 'es' => 'ajuste de la sonda', 'not' => array( 'alineación de la sonda' ) ),
	array( 'en' => 'bore axis alignment', 'es' => 'alineación del eje de puntería', 'not' => array( 'alineación del eje del taladro' ) ),
	array( 'en' => 'misalignment', 'es' => 'desalineación', 'not' => array( 'mala alineación', 'desajuste de alineado' ) ),
	array( 'en' => 'wheel alignment', 'es' => 'alineación de ruedas', 'not' => array( 'equilibrado de ruedas', 'alineación de dirección' ) ),
	array( 'en' => 'wheel aligner', 'es' => 'alineador de ruedas', 'not' => array( 'alineadora de ruedas', 'máquina de alineación de ruedas', 'alineador de dirección' ) ),
	array( 'en' => 'instrument cluster', 'es' => 'cuadro de instrumentos', 'not' => array( 'grupo de instrumentos', 'clúster de instrumentos' ) ),
	array( 'en' => 'control module', 'es' => 'módulo de control', 'not' => array( 'módulo de mando' ) ),
	array( 'en' => 'blank ECM', 'es' => 'ECM sin programar', 'not' => array( 'ECM en blanco', 'ECM vacío' ) ),
	array( 'en' => 'engine software loaders', 'es' => 'equipos de carga de software de motor', 'not' => array( 'cargadores de motores', 'programas de carga de motores' ) ),
	array( 'en' => 'gear shift calibration', 'es' => 'calibración del cambio de marchas', 'not' => array( 'calibración del desplazamiento de marchas' ) ),
	array( 'en' => 'drivability', 'es' => 'agrado de conducción', 'not' => array( 'conducibilidad', 'manejabilidad', 'comportamiento dinámico' ) ),
	array( 'en' => 'restbus simulation', 'es' => 'simulación del resto del bus', 'not' => array( 'simulación de bus residual', 'simulación restbus', 'simulación de bus restante' ) ),
	array( 'en' => 'traction battery', 'es' => 'batería de tracción', 'not' => array( 'pila de tracción', 'acumulador de tracción' ) ),
	array( 'en' => 'e-axle', 'es' => 'eje eléctrico', 'not' => array( 'e-axle', 'eje-e' ) ),
	array( 'en' => 'torque vectoring', 'es' => 'vectorización del par', 'not' => array( 'reparto del par', 'vectorización de torque' ) ),
	array( 'en' => 'rolling torque', 'es' => 'par de rodadura', 'not' => array( 'par de giro del eje', 'torque de rodadura' ) ),
	array( 'en' => 'two-wheel drive', 'es' => 'tracción a dos ruedas', 'not' => array( 'tracción de dos ruedas', 'impulso a dos ruedas' ) ),
	array( 'en' => 'third member', 'es' => 'grupo diferencial', 'not' => array( 'tercer miembro', 'tercer elemento' ) ),
	array( 'en' => 'half case', 'es' => 'carcasa partida', 'not' => array( 'medio cárter', 'media caja' ) ),
	array( 'en' => 'pinion gear', 'es' => 'piñón', 'not' => array( 'muñón', 'engranaje de piñón cónico' ) ),
	array( 'en' => 'ring gears', 'es' => 'coronas dentadas', 'not' => array( 'engranajes anulares', 'coronas de anillo' ) ),
	array( 'en' => 'front strut', 'es' => 'puntal delantero', 'not' => array( 'montante delantero', 'pilar delantero', 'pinza delantera', 'amortiguador delantero tipo McPherson', 'amortiguador delantero' ) ),
	array( 'en' => 'commercial vehicle', 'es' => 'vehículo industrial', 'not' => array( 'vehículo comercial', 'vehículo de comercio' ) ),
	array( 'en' => 'squeak & rattle testing', 'es' => 'ensayos de ruidos y vibraciones parásitas', 'not' => array( 'ensayo de chirridos y traqueteos', 'pruebas de crujidos' ) ),
	array( 'en' => 'NVH Testing', 'es' => 'Ensayos NVH', 'not' => array( 'Ensayos NVH (ruido y vibración)', 'Pruebas NVH', 'Ensayos NVH (ruido, vibración y aspereza)' ) ),
	array( 'en' => 'OBD & Emissions Testing', 'es' => 'Ensayos OBD y de emisiones', 'not' => array( 'Pruebas OBD y de emisiones' ) ),
	array( 'en' => 'compliance testing', 'es' => 'ensayos de conformidad', 'not' => array( 'pruebas de cumplimiento', 'ensayos de cumplimiento' ) ),
	array( 'en' => 'tire inflator', 'es' => 'estación de inflado de neumáticos', 'not' => array( 'inflador de neumáticos', 'bomba de neumáticos' ) ),
	array( 'en' => 'bead breaking', 'es' => 'destalonado', 'not' => array( 'rotura del talón', 'rotura de la banda' ) ),
	array( 'en' => 'Balancers for Rims', 'es' => 'Equilibradoras para llantas', 'not' => array(  ) ),
	array( 'en' => 'Balancers for Clutches', 'es' => 'Equilibradoras para embragues', 'not' => array(  ) ),

	// --- Refrigeration, gas management and leak detection ---
	array( 'en' => 'refrigerant', 'es' => 'refrigerante', 'not' => array( 'líquido de refrigeración', 'anticongelante', 'fluido frigorífico' ) ),
	array( 'en' => 'refrigerant charging', 'es' => 'carga de refrigerante', 'not' => array( 'llenado de refrigerante', 'recarga de refrigerante', 'carga de líquido refrigerante' ) ),
	array( 'en' => 'refrigeration', 'es' => 'refrigeración', 'not' => array( 'enfriamiento industrial' ) ),
	array( 'en' => 'Leak Detection & Refrigeration', 'es' => 'Detección de fugas y refrigeración', 'not' => array( 'Refrigeración y detección de fugas', 'Detección de escapes y refrigeración' ) ),
	array( 'en' => 'Leak Detection & Gas Management', 'es' => 'Detección de fugas y gestión de gases', 'not' => array( 'Refrigeración y gestión de gases', 'Gestión de gases y detección de fugas' ) ),
	array( 'en' => 'leak detection', 'es' => 'detección de fugas', 'not' => array( 'detección de escapes', 'detección de pérdidas', 'ensayo de estanqueidad' ) ),
	array( 'en' => 'gross leak test', 'es' => 'ensayo de fuga gruesa', 'not' => array( 'ensayo de fuga bruta', 'prueba de fuga gruesa' ) ),
	array( 'en' => 'fine leak', 'es' => 'microfuga', 'not' => array( 'fuga fina', 'fuga delicada' ) ),
	array( 'en' => 'tracer gas', 'es' => 'gas trazador', 'not' => array( 'gas rastreador', 'gas de seguimiento' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'es' => 'pinzas de aspiración / sonda de aspiración', 'not' => array( 'pinzas olfateadoras', 'alicates de olfateo', 'sonda de olfateo' ) ),
	array( 'en' => 'vacuum', 'es' => 'vacío', 'not' => array( 'depresión', 'presión negativa' ) ),
	array( 'en' => 'vacuum evacuation', 'es' => 'evacuación al vacío', 'not' => array( 'extracción de vacío', 'vaciado de la depresión' ) ),
	array( 'en' => 'vacuum rise test', 'es' => 'ensayo de aumento de presión en vacío', 'not' => array( 'ensayo de subida de depresión', 'prueba de aumento de vacío', 'ensayo de subida de vacío' ) ),
	array( 'en' => 'pressurization', 'es' => 'presurización', 'not' => array( 'puesta a presión', 'presionado' ) ),
	array( 'en' => 'final discharge', 'es' => 'descarga final del gas', 'not' => array( 'vertido final', 'descargo final' ) ),
	array( 'en' => 'filler', 'es' => 'equipo de carga', 'not' => array( 'llenadora', 'rellenador', 'estación de llenado' ) ),
	array( 'en' => 'filler gun', 'es' => 'pistola de carga', 'not' => array( 'pistolita dosificadora', 'pistola dosificadora de relleno', 'pistola de llenado' ) ),
	array( 'en' => 'flammable gases', 'es' => 'gases inflamables', 'not' => array( 'gases combustibles', 'gases flamables' ) ),
	array( 'en' => 'hazardous area', 'es' => 'zona con riesgo de explosión', 'not' => array( 'área peligrosa', 'zona de peligro' ) ),
	array( 'en' => 'sealed assembly', 'es' => 'conjunto estanco', 'not' => array( 'conjunto sellado', 'montaje precintado' ) ),
	array( 'en' => 'cooling units', 'es' => 'unidades de refrigeración', 'not' => array( 'unidades enfriadoras', 'equipos de enfriado' ) ),
	array( 'en' => 'air cycle machines', 'es' => 'máquinas de ciclo de aire', 'not' => array(  ) ),
	array( 'en' => 'blowers', 'es' => 'soplantes', 'not' => array( 'sopladores', 'ventiladores centrífugos' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'es' => 'limpiador ultrasónico de boquillas', 'not' => array( 'limpiadora ultrasonido de toberas' ) ),
	array( 'en' => 'Ultrasonic Welding Systems', 'es' => 'Sistemas de soldadura por ultrasonidos', 'not' => array( 'Sistemas de soldadura ultrasónica' ) ),

	// --- Metals, roll shop and NDT ---
	array( 'en' => 'mill roll', 'es' => 'cilindro de laminación', 'not' => array( 'rodillo de molino', 'rollo de laminación' ) ),
	array( 'en' => 'Roll Inspection', 'es' => 'Inspección de cilindros', 'not' => array( 'Inspección de rodillos', 'Control de rodillos' ) ),
	array( 'en' => 'Roll Grinding Machines', 'es' => 'Rectificadoras de cilindros', 'not' => array( 'Máquinas de rectificado de rodillos', 'Amoladoras de cilindros' ) ),
	array( 'en' => 'Roll Shop Technologies', 'es' => 'Tecnologías para el taller de cilindros', 'not' => array( 'Roll Shop Technologies', 'Tecnologías de taller de rodillos' ) ),
	array( 'en' => 'reconditioning', 'es' => 'reacondicionamiento', 'not' => array( 'renovación de rodillos', 'reacondicionamiento de cilindros', 'renovación' ) ),
	array( 'en' => 'forged rolls', 'es' => 'cilindros forjados', 'not' => array( 'rodillos forjados' ) ),
	array( 'en' => '20-high / six-high mill', 'es' => 'laminador de 20 cilindros / de 6 cilindros', 'not' => array( 'laminador veinteavo', 'molino de 20 alturas' ) ),
	array( 'en' => 'cold pilger mill', 'es' => 'laminador peregrino en frío', 'not' => array( 'molino pilger en frío', 'laminador pilger frío' ) ),
	array( 'en' => 'Cold & Hot Rolling Mills', 'es' => 'Laminadores en frío y en caliente', 'not' => array( 'Molinos de laminación fría y caliente' ) ),
	array( 'en' => 'strip', 'es' => 'banda', 'not' => array( 'tira de acero', 'cinta de acero' ) ),
	array( 'en' => 'Strip Lines', 'es' => 'Líneas de banda', 'not' => array( 'Líneas de decapado', 'Líneas de tiras' ) ),
	array( 'en' => 'blast furnace', 'es' => 'alto horno', 'not' => array( 'horno de explosión', 'horno alto de fundición' ) ),
	array( 'en' => 'tap hole', 'es' => 'piquera', 'not' => array( 'agujero de colada', 'orificio de grifo' ) ),
	array( 'en' => 'clay gun', 'es' => 'tapadora de piquera', 'not' => array( 'pistola de arcilla', 'máquina de moldeo de arcilla' ) ),
	array( 'en' => 'tin plating', 'es' => 'estañado', 'not' => array( 'galvanizado', 'cincado', 'zincado' ) ),
	array( 'en' => 'electrical discharge texturing', 'es' => 'texturizado por electroerosión (EDT)', 'not' => array( 'tecnología de descarga eléctrica', 'texturado por descarga eléctrica' ) ),
	array( 'en' => 'eddy current technology', 'es' => 'tecnología de corrientes inducidas', 'not' => array( 'corrientes parásitas', 'corrientes de remolino', 'tecnología de corriente actual', 'tecnología de corrientes de Foucault' ) ),
	array( 'en' => 'non-destructive testing (NDT)', 'es' => 'ensayos no destructivos (END)', 'not' => array( 'pruebas no destructivas', 'testeo no destructivo' ) ),
	array( 'en' => 'spalls', 'es' => 'desconchados', 'not' => array( 'astillados', 'escamaduras' ) ),
	array( 'en' => 'surface separations', 'es' => 'desprendimientos superficiales', 'not' => array( 'separaciones de superficie' ) ),
	array( 'en' => 'pinches & bruises', 'es' => 'marcas de pinzado y golpes', 'not' => array( 'pellizcos y moratones', 'pinzamientos y contusiones' ) ),
	array( 'en' => 'debonding', 'es' => 'despegue entre capa y núcleo', 'not' => array( 'delaminación', 'desunión' ) ),
	array( 'en' => 'Detection Focus', 'es' => 'Defectos detectados', 'not' => array( 'Enfoque de detección', 'Foco de detección' ) ),
	array( 'en' => 'Furnace & Blast Furnace Technology', 'es' => 'Tecnología de hornos y altos hornos', 'not' => array( 'Tecnología de hornos y hornos de explosión' ) ),
	array( 'en' => 'Handling Machines & Manipulators', 'es' => 'Máquinas de manipulación y manipuladores', 'not' => array( 'Máquinas de manejo y manipuladores' ) ),
	array( 'en' => 'Pipe Manufacturing', 'es' => 'Fabricación de tubos', 'not' => array( 'Fabricación de tuberías', 'Manufactura de tubos' ) ),
	array( 'en' => 'Press Technology & Hydroforming', 'es' => 'Tecnología de prensas e hidroconformado', 'not' => array( 'Tecnología de prensa y hidroformado' ) ),
	array( 'en' => 'Metals automation', 'es' => 'Automatización para la industria del metal', 'not' => array( 'Automatización de metales', 'Automatización metálica' ) ),

	// --- Machine tools, machining and grinding ---
	array( 'en' => 'machine tools', 'es' => 'máquinas herramienta', 'not' => array( 'herramientas de máquina', 'máquinas tecnológicas' ) ),
	array( 'en' => 'Machine Tools and Special Machines', 'es' => 'Máquinas herramienta y máquinas especiales', 'not' => array(  ) ),
	array( 'en' => 'machining cell', 'es' => 'célula de mecanizado', 'not' => array( 'celda de mecanizado', 'gabinete de mecanizado' ) ),
	array( 'en' => 'machinist', 'es' => 'operario de máquina herramienta', 'not' => array( 'maquinista', 'mecánico de máquinas' ) ),
	array( 'en' => 'boring', 'es' => 'mandrinado', 'not' => array(  ) ),
	array( 'en' => 'horizontal boring machine', 'es' => 'mandrinadora horizontal', 'not' => array( 'taladradora horizontal' ) ),
	array( 'en' => 'deep hole drilling', 'es' => 'taladrado profundo', 'not' => array( 'perforación de agujeros profundos' ) ),
	array( 'en' => 'gundrill', 'es' => 'broca de cañón', 'not' => array( 'taladro de pistola', 'broca gundrill' ) ),
	array( 'en' => 'grinding wheel', 'es' => 'muela abrasiva', 'not' => array( 'rueda de esmerilar', 'disco de rectificado' ) ),
	array( 'en' => 'rotary diamond dressing', 'es' => 'diamantado con rodillo rotativo', 'not' => array( 'acabado rotativo con diamante', 'dressing rotativo' ) ),
	array( 'en' => 'superabrasives', 'es' => 'superabrasivos', 'not' => array( 'súper abrasivos' ) ),
	array( 'en' => 'infeed', 'es' => 'avance de penetración', 'not' => array( 'alimentación interna' ) ),
	array( 'en' => 'turret-style wheel head', 'es' => 'cabezal portamuelas de torreta', 'not' => array( 'cabezal de torrecilla' ) ),
	array( 'en' => '3-jaw chuck', 'es' => 'plato de tres garras', 'not' => array( 'mandril de tres piezas', 'portabrocas de tres mordazas' ) ),
	array( 'en' => 'collet chuck', 'es' => 'portapinzas', 'not' => array( 'mandril neumático', 'portabrocas de pinza' ) ),
	array( 'en' => 'chip vacuum', 'es' => 'aspiración de viruta', 'not' => array( 'aspiradora de virutas', 'aspiración de virutas' ) ),
	array( 'en' => 'dial indicator', 'es' => 'comparador de reloj', 'not' => array( 'indicador de dial', 'medidor de carátula' ) ),
	array( 'en' => 'TIR / radial run-out', 'es' => 'excentricidad radial (TIR)', 'not' => array( 'salida radial', 'carrera radial' ) ),
	array( 'en' => 'gantry', 'es' => 'pórtico', 'not' => array( 'grúa portal', 'estructura de puente' ) ),
	array( 'en' => 'gantry milling', 'es' => 'fresado en pórtico', 'not' => array( 'fresado de puente', 'fresado de pórtico móvil' ) ),
	array( 'en' => 'Brushing & Polishing Machines', 'es' => 'Máquinas de cepillado y pulido', 'not' => array( 'Máquinas de cepillo y brillo' ) ),
	array( 'en' => 'Retrofit & Modernization', 'es' => 'Retrofit y modernización', 'not' => array( 'Reacondicionamiento y renovación', 'Modernización y renovación' ) ),
	array( 'en' => 'Precision Machining', 'es' => 'Mecanizado de precisión', 'not' => array( 'Maquinado de precisión' ) ),

	// --- Fluid power, hydraulics and industrial systems ---
	array( 'en' => 'fluid power', 'es' => 'hidráulica y neumática', 'not' => array( 'potencia de fluidos', 'energía fluida', 'poder fluido', 'potencia fluida' ) ),
	array( 'en' => 'Linear Motion', 'es' => 'Movimiento lineal', 'not' => array( 'Moción lineal', 'Desplazamiento lineal' ) ),
	array( 'en' => 'Rotary Motion', 'es' => 'Movimiento rotativo', 'not' => array( 'Moción rotatoria' ) ),
	array( 'en' => 'valve body unit', 'es' => 'cuerpo de válvulas', 'not' => array( 'conjunto de válvulas', 'unidad del cuerpo de válvula' ) ),
	array( 'en' => 'hydraulic pilot', 'es' => 'pilotaje hidráulico', 'not' => array( 'mando hidráulico piloto' ) ),
	array( 'en' => 'load sense signal', 'es' => 'señal load-sense (LS)', 'not' => array( 'señal del sensor de carga', 'señal de detección de carga' ) ),
	array( 'en' => 'stem stickiness', 'es' => 'agarrotamiento del vástago', 'not' => array( 'viscosidad del vástago', 'pegajosidad del vástago' ) ),
	array( 'en' => 'drift', 'es' => 'deriva', 'not' => array( 'deriva a la deriva', 'desplazamiento involuntario', 'deriva del cilindro' ) ),
	array( 'en' => 'cushion testing', 'es' => 'ensayo de amortiguación de final de carrera', 'not' => array( 'ensayo del cojín', 'prueba de almohadilla' ) ),
	array( 'en' => 'snubber', 'es' => 'amortiguador de golpe de ariete', 'not' => array( 'supresor', 'amortiguador simple' ) ),
	array( 'en' => 'push and pull', 'es' => 'empuje y tracción', 'not' => array( 'presión y estiramiento' ) ),
	array( 'en' => 'thrust force / pullback force', 'es' => 'fuerza de empuje / fuerza de tracción', 'not' => array( 'fuerza axial' ) ),
	array( 'en' => 'tension', 'es' => 'fuerza de tensado', 'not' => array( 'voltaje', 'tirantez' ) ),
	array( 'en' => 'actuation systems', 'es' => 'sistemas de actuación', 'not' => array( 'sistemas de activación', 'sistemas de accionado' ) ),
	array( 'en' => 'controls', 'es' => 'sistemas de control', 'not' => array( 'controladores', 'mandos de control' ) ),
	array( 'en' => 'higher-level control system', 'es' => 'sistema de control de nivel superior', 'not' => array( 'sistema de control más alto' ) ),
	array( 'en' => 'adaptive speed control', 'es' => 'regulación adaptativa de velocidad', 'not' => array( 'control de velocidad adaptable' ) ),
	array( 'en' => 'infinitely variable', 'es' => 'de regulación continua', 'not' => array( 'infinitamente variable' ) ),
	array( 'en' => 'automated handling cells', 'es' => 'células automatizadas de manipulación', 'not' => array( 'celdas de manejo automatizado' ) ),
	array( 'en' => 'stand-alone machine', 'es' => 'máquina autónoma', 'not' => array( 'máquina independiente', 'máquina de pie solo' ) ),
	array( 'en' => 'test benches / test stands', 'es' => 'bancos de ensayo', 'not' => array( 'bancos de pruebas', 'bancadas de prueba' ) ),
	array( 'en' => 'Test Bay Erection and Modernization', 'es' => 'Montaje y modernización de salas de ensayo', 'not' => array( 'Erección y modernización de salas de prueba', 'Montaje y modernización de bancos de ensayo' ) ),
	array( 'en' => 'special test facilities', 'es' => 'instalaciones de ensayo especiales', 'not' => array( 'instalaciones de prueba especializadas' ) ),
	array( 'en' => 'testing', 'es' => 'ensayos', 'not' => array( 'testeo', 'testado' ) ),
	array( 'en' => 'EMC darkroom', 'es' => 'cámara anecoica de CEM', 'not' => array( 'cuarto oscuro CEM', 'cámara oscura de compatibilidad' ) ),
	array( 'en' => 'exhaust extraction', 'es' => 'extracción de gases de escape', 'not' => array( 'extracción de escape', 'evacuación de humos' ) ),
	array( 'en' => 'audit stations', 'es' => 'estaciones de auditoría', 'not' => array( 'puestos de control', 'estaciones de inspección' ) ),
	array( 'en' => 'fixed stations', 'es' => 'estaciones fijas', 'not' => array( 'estaciones estacionarias' ) ),
	array( 'en' => 'mobile carousels', 'es' => 'carruseles móviles', 'not' => array( 'carruseles portátiles' ) ),
	array( 'en' => 'movable cradle', 'es' => 'cuna móvil', 'not' => array( 'base móvil', 'soporte desplazable' ) ),
	array( 'en' => 'Vibration Absorbing Cast', 'es' => 'Fundición absorbente de vibraciones', 'not' => array( 'Fundición amortiguadora de vibraciones' ) ),
	array( 'en' => 'Magnetizing System for Permanent Magnets', 'es' => 'Sistema de magnetización para imanes permanentes', 'not' => array( 'Sistema magnetizador de imanes fijos' ) ),

	// --- Aerospace ---
	array( 'en' => 'Aerospace & industrials', 'es' => 'Aeroespacial e industrial', 'not' => array( 'Aeronáutica e industria', 'Sector aeroespacial e industrias', 'Aviación e industrial' ) ),
	array( 'en' => 'rotor wing aircraft', 'es' => 'aeronaves de ala rotatoria', 'not' => array( 'aviones de hélice', 'aeronaves de hélice' ) ),
	array( 'en' => 'landing gear systems', 'es' => 'sistemas de tren de aterrizaje', 'not' => array( 'sistemas de engranaje de aterrizaje' ) ),
	array( 'en' => 'HMU/FMU', 'es' => 'unidades HMU/FMU', 'not' => array( 'unidades hidráulicas y neumáticas' ) ),
	array( 'en' => 'lube & scavenge pumps', 'es' => 'bombas de lubricación y recuperación de aceite', 'not' => array( 'bombas de lubricación y purga', 'bombas de engrase y venteo' ) ),
	array( 'en' => 'cargo loading systems', 'es' => 'sistemas de carga de mercancías', 'not' => array( 'sistemas de carga de cargamento' ) ),
	array( 'en' => 'power drive units', 'es' => 'unidades motrices (PDU)', 'not' => array( 'unidades de accionamiento de potencia' ) ),
	array( 'en' => 'MRO', 'es' => 'MRO', 'not' => array( 'servicio y repuestos', 'mantenimiento y reparación general', 'organizaciones MRO' ) ),
	array( 'en' => 'oil drain', 'es' => 'drenaje de aceite', 'not' => array( 'orificio de ventilación', 'purga de aire' ) ),

	// --- Agricultural, construction and mobile equipment ---
	array( 'en' => 'off-highway', 'es' => 'maquinaria fuera de carretera', 'not' => array( 'vehículos especiales', 'maquinaria de obra', 'fuera de autopista' ) ),
	array( 'en' => 'implements', 'es' => 'aperos', 'not' => array( 'implementos', 'utensilios' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'es' => 'Aperos - fin de línea', 'not' => array( 'Implementos: fin de línea', 'Aperos: fin de línea' ) ),
	array( 'en' => 'motor grader', 'es' => 'motoniveladora', 'not' => array( 'niveladora a motor', 'raspadora' ) ),
	array( 'en' => 'excavator', 'es' => 'excavadora', 'not' => array(  ) ),
	array( 'en' => 'backhoe', 'es' => 'retroexcavadora mixta', 'not' => array( 'excavadora trasera' ) ),
	array( 'en' => 'baler', 'es' => 'empacadora', 'not' => array( 'prensadora', 'enfardadora de chatarra' ) ),
	array( 'en' => 'combine', 'es' => 'cosechadora', 'not' => array( 'empacadora de cosecha', 'transmisión combinada', 'combinada' ) ),
	array( 'en' => 'draper header', 'es' => 'cabezal de cinta', 'not' => array( 'cabezal cortina', 'esparcidor' ) ),
	array( 'en' => 'hay mower', 'es' => 'segadora de heno', 'not' => array( 'cortacésped de heno', 'guadañadora de forraje', 'segadora' ) ),
	array( 'en' => 'sprayers', 'es' => 'pulverizadores', 'not' => array( 'rociadores', 'atomizadores agrícolas' ) ),
	array( 'en' => 'blade', 'es' => 'hoja', 'not' => array( 'cuchilla de afeitar', 'aspa', 'hoja niveladora' ) ),
	array( 'en' => 'blade timing', 'es' => 'tiempo de ciclo de la hoja', 'not' => array( 'sincronización de la cuchilla' ) ),
	array( 'en' => 'PTO', 'es' => 'toma de fuerza (TDF)', 'not' => array( 'toma de poder', 'eje receptor de potencia' ) ),
	array( 'en' => 'boring drill', 'es' => 'perforadora horizontal dirigida', 'not' => array( 'broca perforadora', 'taladro de barrenado' ) ),
	array( 'en' => 'mudding system', 'es' => 'sistema de lodos de perforación', 'not' => array( 'sistema de barro', 'sistema de fango' ) ),
	array( 'en' => 'keg', 'es' => 'barril', 'not' => array( 'tonel pequeño' ) ),
	array( 'en' => 'keg finger holes', 'es' => 'asas embutidas del barril', 'not' => array( 'agujeros de dedo', 'orificios digitales' ) ),
	array( 'en' => 'water meter', 'es' => 'contador de agua', 'not' => array( 'medidor de agua', 'caudalímetro doméstico' ) ),
	array( 'en' => 'heavy-duty', 'es' => 'de servicio pesado', 'not' => array( 'de trabajo duro', 'de alta resistencia', 'de uso rudo' ) ),

	// --- Manufacturing, operations and commercial vocabulary ---
	array( 'en' => 'throughput', 'es' => 'rendimiento de producción', 'not' => array( 'caudal de producción', 'rendimiento de paso', 'flujo de salida', 'productividad de la línea' ) ),
	array( 'en' => 'high production / high-volume production', 'es' => 'producción de gran serie', 'not' => array( 'producción de alto volumen', 'producción de alta tasa' ) ),
	array( 'en' => 'high-mix, low-volume', 'es' => 'gran variedad y series cortas', 'not' => array( 'alta mezcla y bajo volumen' ) ),
	array( 'en' => 'volume flexibility', 'es' => 'flexibilidad de volumen de serie', 'not' => array( 'flexibilidad de volúmenes' ) ),
	array( 'en' => 'factory floor', 'es' => 'planta de producción', 'not' => array( 'suelo de fábrica', 'piso de planta' ) ),
	array( 'en' => 'capital equipment', 'es' => 'bienes de equipo', 'not' => array( 'equipos de capital', 'equipamiento capital' ) ),
	array( 'en' => 'machine health', 'es' => 'estado de las máquinas', 'not' => array( 'salud de la máquina', 'salud de los equipos' ) ),
	array( 'en' => 'health checks', 'es' => 'revisiones del estado técnico', 'not' => array( 'chequeos de salud', 'controles sanitarios' ) ),
	array( 'en' => 'commissioning', 'es' => 'puesta en marcha', 'not' => array( 'comisionamiento', 'encargo de la instalación' ) ),
	array( 'en' => 'deployment', 'es' => 'puesta en servicio', 'not' => array( 'despliegue', 'implantación técnica' ) ),
	array( 'en' => 'design', 'es' => 'diseño', 'not' => array( 'proyecto de la máquina', 'diseño constructivo' ) ),
	array( 'en' => 'footprint', 'es' => 'superficie ocupada', 'not' => array( 'huella', 'pisada' ) ),
	array( 'en' => 'load capacity', 'es' => 'capacidad de carga', 'not' => array( 'capacidad volumétrica' ) ),
	array( 'en' => 'weight capacity', 'es' => 'peso máximo admisible', 'not' => array( 'capacidad de levantamiento', 'capacidad de peso' ) ),
	array( 'en' => 'idle duration', 'es' => 'tiempo a ralentí', 'not' => array( 'duración de inactividad', 'tiempo ocioso' ) ),
	array( 'en' => 'soak time', 'es' => 'tiempo de estabilización térmica', 'not' => array( 'tiempo de remojo', 'tiempo de empapado' ) ),
	array( 'en' => 'process recipe', 'es' => 'receta de proceso', 'not' => array( 'prescripción de proceso' ) ),
	array( 'en' => 'lubrication', 'es' => 'lubricación', 'not' => array( 'cambio de aceite', 'engrase periódico' ) ),
	array( 'en' => 'energy recuperation', 'es' => 'recuperación de energía', 'not' => array( 'regeneración de energía' ) ),
	array( 'en' => 'water-cooled', 'es' => 'refrigerado por agua', 'not' => array( 'enfriador de agua', 'que enfría el agua' ) ),
	array( 'en' => 'obsolescence management', 'es' => 'gestión de la obsolescencia', 'not' => array( 'gestión de lo obsoleto' ) ),
	array( 'en' => 'maintenance contracts', 'es' => 'contratos de mantenimiento', 'not' => array( 'contratos de conservación' ) ),
	array( 'en' => 'warranty coverage', 'es' => 'cobertura de la garantía', 'not' => array( 'seguro de garantía', 'póliza de garantía' ) ),
	array( 'en' => 'failure rates', 'es' => 'tasa de fallos', 'not' => array( 'tasas de avería', 'índices de fracaso', 'tasa de calibraciones no conformes', 'tasa de fallas' ) ),
	array( 'en' => 'reportable', 'es' => 'documentable', 'not' => array( 'reportable', 'informable' ) ),
	array( 'en' => 'traceable tests', 'es' => 'ensayos trazables', 'not' => array( 'pruebas rastreables', 'ensayos seguibles' ) ),
	array( 'en' => 'defensible', 'es' => 'defendibles ante una auditoría', 'not' => array( 'defendibles sin más' ) ),
	array( 'en' => 'validate performance', 'es' => 'validar el rendimiento', 'not' => array( 'verificar la productividad' ) ),
	array( 'en' => 'performance', 'es' => 'rendimiento', 'not' => array( 'desempeño' ) ),
	array( 'en' => 'features', 'es' => 'características', 'not' => array( 'rasgos', 'prestaciones adicionales' ) ),
	array( 'en' => 'applications', 'es' => 'aplicaciones', 'not' => array( 'solicitudes', 'apps' ) ),
	array( 'en' => 'operations', 'es' => 'operaciones', 'not' => array( 'operaciones quirúrgicas', 'actividad' ) ),
	array( 'en' => 'insights', 'es' => 'análisis', 'not' => array( 'perspicacias', 'insights', 'entendimientos' ) ),
	array( 'en' => 'actionable insights', 'es' => 'conclusiones prácticas', 'not' => array( 'información accionable', 'conocimientos accionables' ) ),
	array( 'en' => 'expert insights', 'es' => 'análisis de nuestros expertos', 'not' => array( 'perspicacias expertas' ) ),
	array( 'en' => 'fully loaded test', 'es' => 'ensayo a plena carga', 'not' => array( 'ensayo completo', 'prueba totalmente cargada' ) ),
	array( 'en' => 'Addresses', 'es' => 'Corrige', 'not' => array( 'Elimina', 'Erradica', 'Suprime' ) ),
	array( 'en' => 'discrete industries', 'es' => 'sectores de fabricación discreta', 'not' => array( 'industrias discretas', 'sectores discretos' ) ),
	array( 'en' => 'marine', 'es' => 'sector naval', 'not' => array( 'sector marino', 'navegación' ) ),
	array( 'en' => 'life sciences', 'es' => 'ciencias de la vida', 'not' => array( 'ciencias naturales', 'ciencias de la salud' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'es' => 'talleres de remanufactura y reconstrucción', 'not' => array( 'refabricantes y reconstructores' ) ),
	array( 'en' => 'remarketers', 'es' => 'comercializadores de flotas de segunda mano', 'not' => array( 'remarketers', 'revendedores secundarios' ) ),
	array( 'en' => 'right-shoring', 'es' => 'right-shoring', 'not' => array( 'deslocalización óptima', 'relocalización adecuada' ) ),
	array( 'en' => 'landed cost model', 'es' => 'modelo de coste puesto en destino', 'not' => array( 'modelo de coste de envío', 'modelo de coste aterrizado' ) ),
	array( 'en' => 'tariffs', 'es' => 'aranceles', 'not' => array( 'tarifas', 'tasas de precio' ) ),
	array( 'en' => 'customer journey', 'es' => 'etapas de la colaboración', 'not' => array( 'viaje del cliente', 'recorrido del cliente' ) ),
	array( 'en' => 'site visit', 'es' => 'visita a las instalaciones', 'not' => array( 'visita al sitio', 'visita del terreno' ) ),
	array( 'en' => 'field agents', 'es' => 'técnicos de campo', 'not' => array( 'agentes de campo', 'agentes comerciales' ) ),
	array( 'en' => 'service professional', 'es' => 'especialista de servicio', 'not' => array( 'profesional del servicio' ) ),
	array( 'en' => 'high-performance teams', 'es' => 'equipos de alto rendimiento', 'not' => array( 'equipos de alta performance' ) ),
	array( 'en' => 'like-minded companies', 'es' => 'empresas con una visión afín', 'not' => array( 'empresas de mentalidad similar', 'empresas con ideas afines' ) ),
	array( 'en' => 'peers', 'es' => 'otros profesionales del sector', 'not' => array( 'pares', 'iguales', 'compañeros de edad' ) ),
	array( 'en' => 'opportunities', 'es' => 'oportunidades', 'not' => array( 'oportunidades (posibilidades)', 'chances' ) ),
	array( 'en' => 'responsive', 'es' => 'de respuesta rápida', 'not' => array( 'responsivo', 'adaptable a pantalla' ) ),
	array( 'en' => 'seamless link', 'es' => 'enlace fluido', 'not' => array( 'vínculo sin costuras', 'conector directo' ) ),
	array( 'en' => 'turnkey', 'es' => 'llave en mano', 'not' => array( 'turnkey', 'de llave y mano' ) ),
	array( 'en' => 'built to last', 'es' => 'diseñado para durar', 'not' => array( 'construido a lo largo', 'hecho para largo' ) ),
	array( 'en' => 'ultra-stable design', 'es' => 'construcción extraordinariamente estable', 'not' => array( 'diseño ultraduradero' ) ),
	array( 'en' => 'Standardization at scale', 'es' => 'Estandarización a gran escala', 'not' => array( 'Estandarización a escala' ) ),
	array( 'en' => 'uptime across systems', 'es' => 'disponibilidad de los sistemas', 'not' => array( 'tiempo activo en todos los sistemas' ) ),
	array( 'en' => 'unbeatable deals', 'es' => 'ofertas inmejorables', 'not' => array( 'tratos imbatibles', 'ofertas no concluidas' ) ),
	array( 'en' => 'learning management system (LMS)', 'es' => 'sistema de gestión de la formación (LMS)', 'not' => array( 'sistema de gestión del aprendizaje' ) ),
	array( 'en' => 'branch', 'es' => 'espacio del LMS', 'not' => array( 'sucursal' ) ),
	array( 'en' => 'mental health care', 'es' => 'atención de salud mental', 'not' => array( 'atención sanitaria remota', 'cuidado mental a distancia' ) ),
	array( 'en' => 'disability insurance', 'es' => 'seguro de incapacidad laboral', 'not' => array( 'pensión de invalidez', 'seguro de discapacidad' ) ),
	array( 'en' => 'Careers', 'es' => 'Empleo', 'not' => array( 'Carreras', 'Trayectorias profesionales' ) ),
	array( 'en' => 'Leadership', 'es' => 'Equipo directivo', 'not' => array( 'Liderazgo', 'Dirección superior', 'Alta gerencia' ) ),
	array( 'en' => 'Corporate Roles', 'es' => 'Dirección corporativa', 'not' => array( 'Funciones corporativas', 'Roles corporativos' ) ),
	array( 'en' => 'President', 'es' => 'presidente', 'not' => array( 'jefe del Estado' ) ),
	array( 'en' => 'Board Member', 'es' => 'miembro del consejo de administración', 'not' => array( 'miembro de la junta directiva', 'consejero delegado' ) ),
	array( 'en' => 'Principal', 'es' => 'Principal', 'not' => array( 'Director principal de inversiones', 'Jefe principal' ) ),
	array( 'en' => 'associate attorney', 'es' => 'abogado asociado', 'not' => array( 'ayudante de abogado', 'pasante jurídico' ) ),
	array( 'en' => 'events & conferences', 'es' => 'eventos y congresos', 'not' => array( 'fiestas y conferencias' ) ),
	array( 'en' => 'Introducing', 'es' => 'Presentamos', 'not' => array( 'Novedad', 'Introduciendo' ) ),
	array( 'en' => 'is now', 'es' => 'ahora es', 'not' => array( 'es ahora mismo' ) ),
	array( 'en' => 'Featuring: <Brand>', 'es' => 'Con tecnología de <Brand>', 'not' => array( 'Presentando:', 'Con la participación de' ) ),
	array( 'en' => 'Powered by', 'es' => 'Impulsado por', 'not' => array( 'Alimentado por', 'Energizado por', 'Con tecnología de' ) ),
	array( 'en' => 'patented', 'es' => 'patentado', 'not' => array( 'con patente pendiente' ) ),
	array( 'en' => 'represent', 'es' => 'representar', 'not' => array( 'reproducir' ) ),

	// --- Legal, contractual and corporate-information strings ---
	array( 'en' => 'Imprint', 'es' => 'Aviso legal', 'not' => array( 'Imprint', 'Pie de imprenta', 'Impresión' ) ),
	array( 'en' => 'Terms', 'es' => 'Términos y condiciones', 'not' => array(  ) ),
	array( 'en' => 'Email Disclosure', 'es' => 'Cláusula de confidencialidad del correo electrónico', 'not' => array( 'Divulgación de correo electrónico', 'Revelación del correo' ) ),
	array( 'en' => 'personal information / personal data', 'es' => 'datos personales', 'not' => array( 'información personal', 'informaciones privadas' ) ),
	array( 'en' => 'GDPR', 'es' => 'RGPD', 'not' => array( 'GDPR', 'GPDR' ) ),
	array( 'en' => 'Register (a legal register)', 'es' => 'Registro', 'not' => array(  ) ),
	array( 'en' => 'Registered office', 'es' => 'Domicilio social', 'not' => array( 'Oficina registrada', 'Sede registrada' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'es' => 'Kruispuntbank van Ondernemingen', 'not' => array( 'Banco de Cruce de Empresas', 'Registro Mercantil belga' ) ),
	array( 'en' => 'KvK', 'es' => 'Cámara de Comercio (KvK)', 'not' => array( 'Cámara de Comercio e Industria (KvK)' ) ),
	array( 'en' => 'naamloze vennootschap', 'es' => 'naamloze vennootschap', 'not' => array( 'sociedad anónima neerlandesa' ) ),
	array( 'en' => 'Netherlands', 'es' => 'Países Bajos', 'not' => array( 'Holanda' ) ),
	array( 'en' => 'England', 'es' => 'Inglaterra', 'not' => array( 'England' ) ),
	array( 'en' => 'West Flanders', 'es' => 'Flandes Occidental', 'not' => array( 'West Flanders', 'Flandes del Oeste' ) ),
	array( 'en' => 'Poland', 'es' => 'Polonia', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Bristol', 'es' => 'Bristol', 'not' => array( 'Brístol' ) ),
	array( 'en' => 'Jordan', 'es' => 'Jordania', 'not' => array(  ) ),
	array( 'en' => 'WHEREAS', 'es' => 'CONSIDERANDO QUE', 'not' => array( 'MIENTRAS QUE', 'EN TANTO QUE' ) ),
	array( 'en' => 'RECITALS', 'es' => 'ANTECEDENTES', 'not' => array( 'RECITALES', 'CONSIDERANDOS PREVIOS' ) ),
	array( 'en' => 'Deliverables', 'es' => 'Entregables', 'not' => array( 'Resultados a entregar', 'Prestaciones entregables', 'Productos de entrega' ) ),
	array( 'en' => 'Work Product', 'es' => 'Producto del Trabajo', 'not' => array( 'Resultado Laboral', 'Obra de Trabajo' ) ),
	array( 'en' => 'Exhibit', 'es' => 'Anexo', 'not' => array( 'Exhibición', 'Apéndice numerado' ) ),
	array( 'en' => 'Ascential Indemnity', 'es' => 'Indemnización de Ascential', 'not' => array( 'Ascential Indemnity' ) ),
	array( 'en' => 'Name:', 'es' => 'Nombre y apellidos:', 'not' => array( 'Denominación:', 'Razón social:' ) ),
	array( 'en' => 'Date:', 'es' => 'Fecha:', 'not' => array( 'Datos:' ) ),
	array( 'en' => 'Labour & Travel', 'es' => 'Mano de obra y desplazamientos', 'not' => array( 'Trabajo y viajes', 'Labor y viaje' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'es' => 'Directiva de máquinas 2006/42/CE', 'not' => array( 'Directiva de maquinaria 2006/42/EC' ) ),
	array( 'en' => 'For Immediate Release', 'es' => 'Para publicación inmediata', 'not' => array( 'Para difusión inmediata inmediata', 'Nota de prensa para publicación inmediata' ) ),
	array( 'en' => 'WCAG four principles', 'es' => 'Perceptible, operable, comprensible y robusto', 'not' => array( 'Percibible, Operable, Entendible, Fuerte' ) ),

	// --- UI, navigation and CTA labels ---
	array( 'en' => 'Explore', 'es' => 'Explore', 'not' => array( 'Explore los recursos de', 'Explore los recursos' ) ),
	array( 'en' => 'Explore the Catalog', 'es' => 'Explore el catálogo', 'not' => array( 'Consultar catálogo' ) ),
	array( 'en' => 'Browse catalog', 'es' => 'Explore el catálogo', 'not' => array( 'Consultar catálogo', 'Ver catálogo' ) ),
	array( 'en' => 'Browse full catalog', 'es' => 'Explore el catálogo completo', 'not' => array( 'Ver todo el catálogo' ) ),
	array( 'en' => 'Browse all resources', 'es' => 'Explore todos los recursos', 'not' => array( 'Todos los recursos' ) ),
	array( 'en' => 'View all resources', 'es' => 'Vea todos los recursos', 'not' => array( 'Ver todos los recursos' ) ),
	array( 'en' => 'View all press releases', 'es' => 'Vea todas las notas de prensa', 'not' => array( 'Ver todos los comunicados', 'Ver todas las notas', 'Vea todos los comunicados' ) ),
	array( 'en' => 'View all events', 'es' => 'Vea todos los eventos', 'not' => array( 'Ver todos los eventos' ) ),
	array( 'en' => 'Read more', 'es' => 'Lea más', 'not' => array( 'Leer más', 'Ver más' ) ),
	array( 'en' => 'Read the article', 'es' => 'Lea el artículo', 'not' => array( 'Leer el artículo', 'Leer artículo' ) ),
	array( 'en' => 'Read the announcement', 'es' => 'Lea el anuncio', 'not' => array( 'Leer el anuncio' ) ),
	array( 'en' => 'Request a quote', 'es' => 'Solicite un presupuesto', 'not' => array( 'Pedir presupuesto', 'Solicitud de presupuesto' ) ),
	array( 'en' => 'Get a quote', 'es' => 'Solicite un presupuesto', 'not' => array( 'Obtenga una cotización', 'Consiga presupuesto' ) ),
	array( 'en' => 'Request a demo', 'es' => 'Solicite una demostración', 'not' => array( 'Pedir demo', 'Solicitud de demostración' ) ),
	array( 'en' => 'Speak with an Expert', 'es' => 'Hable con un experto', 'not' => array( 'Contacte a un experto' ) ),
	array( 'en' => 'Download', 'es' => 'Descargue el folleto', 'not' => array( 'Bajar el folleto', 'Descarga del folleto' ) ),
	array( 'en' => 'Register (event CTA)', 'es' => 'Regístrese', 'not' => array( 'Registrarse' ) ),
	array( 'en' => 'Schedule a Meeting', 'es' => 'Concierte una reunión', 'not' => array( 'Programar una reunión', 'Agendar una cita' ) ),
	array( 'en' => 'Contact us', 'es' => 'Contáctenos', 'not' => array( 'Contactar', 'Póngase en contacto con nosotros' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'es' => '¿Listo para modernizar su infraestructura?', 'not' => array( '¿Preparado para actualizar tu infraestructura?' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'es' => 'Buscar en ascentialtech.com', 'not' => array( 'Searching ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'es' => 'Vista de calendario no disponible', 'not' => array( 'Calendar View Unavailable' ) ),
	array( 'en' => 'Play', 'es' => 'Reproducir', 'not' => array( 'Play', 'Jugar' ) ),
	array( 'en' => 'Listen to this article', 'es' => 'Escuche este artículo', 'not' => array( 'Listen to this article' ) ),
	array( 'en' => 'N chapters', 'es' => 'N capítulos', 'not' => array( 'chapters' ) ),
	array( 'en' => 'Share / Copy link / Email', 'es' => 'Compartir / Copiar enlace / Enviar por correo', 'not' => array( 'Copy link', 'Compartir / Copiar link' ) ),
	array( 'en' => 'Products', 'es' => 'Productos', 'not' => array( 'Producto s' ) ),
	array( 'en' => 'Product Catalog', 'es' => 'Catálogo de productos', 'not' => array(  ) ),
	array( 'en' => 'Resource Type', 'es' => 'Tipo de recurso', 'not' => array( 'Resource Type' ) ),
	array( 'en' => 'Resource Topic', 'es' => 'Tema del recurso', 'not' => array( 'Resource Topic' ) ),
	array( 'en' => 'Brand', 'es' => 'Marca', 'not' => array(  ) ),
	array( 'en' => 'Case Study', 'es' => 'Caso de éxito', 'not' => array( 'Case Study', 'Estudio de caso' ) ),
	array( 'en' => 'Technical Papers', 'es' => 'Documentos técnicos', 'not' => array( 'Technical Papers', 'Papeles técnicos' ) ),
	array( 'en' => 'Whitepapers', 'es' => 'Informes técnicos', 'not' => array( 'Libros blancos', 'Informes solos' ) ),
	array( 'en' => 'Press Announcements', 'es' => 'Notas de prensa', 'not' => array( 'Press Announcements', 'Anuncios de prensa' ) ),
	array( 'en' => 'Ebooks', 'es' => 'Libros electrónicos', 'not' => array( 'Ebooks', 'E-libros' ) ),
	array( 'en' => 'Webinars', 'es' => 'Seminarios web', 'not' => array( 'Webinarios', 'Webinars' ) ),
	array( 'en' => 'Blog', 'es' => 'Blog', 'not' => array( 'Bitácora' ) ),
	array( 'en' => 'Supply Chain', 'es' => 'Cadena de suministro', 'not' => array( 'Supply Chain', 'Cadena de abastecimiento' ) ),
	array( 'en' => 'Global Supply Chain Requirements', 'es' => 'Requisitos de la cadena de suministro global', 'not' => array( 'Global Supply Chain Requirements' ) ),
	array( 'en' => 'Support Services', 'es' => 'Servicios de asistencia', 'not' => array( 'Support Services', 'Servicios de soporte' ) ),
	array( 'en' => 'support', 'es' => 'asistencia', 'not' => array( 'soporte', 'soporte técnico' ) ),
	array( 'en' => 'Machine Analytics', 'es' => 'Análisis de máquinas', 'not' => array( 'Machine Analytics', 'Analítica de máquina' ) ),
	array( 'en' => 'Engineering Services', 'es' => 'Servicios de ingeniería', 'not' => array( 'Engineering Services' ) ),
	array( 'en' => 'Electrical Testing', 'es' => 'Ensayos eléctricos', 'not' => array( 'Electrical Testing', 'Pruebas eléctricas' ) ),
	array( 'en' => 'Assembly', 'es' => 'Montaje', 'not' => array( 'Ensamblaje', 'Ensamble' ) ),
	array( 'en' => 'Core / Plus / Elite (service tiers)', 'es' => 'Core, Plus, Elite', 'not' => array( 'Básico, Plus, Elite', 'Núcleo, Plus, Élite' ) ),
	array( 'en' => 'Priority 1/2/3', 'es' => 'Prioridad 1: alta / Prioridad 2: media / Prioridad 3: baja', 'not' => array( 'Prioridad alta de prioridad' ) ),
	array( 'en' => 'sales inquiry', 'es' => 'consulta comercial', 'not' => array( 'indagación de ventas', 'consulta de ventas' ) ),
	array( 'en' => 'Medical', 'es' => 'Medicina', 'not' => array( 'Médico', 'Médica' ) ),
	array( 'en' => '<Model> Refrigerant Charging Brochure', 'es' => 'Folleto <Model>: carga de refrigerante', 'not' => array( 'Folleto de recarga de refrigerante' ) ),
	array( 'en' => 'Titan <Application> System', 'es' => 'Sistema Titan para <aplicación>', 'not' => array( 'Titan System' ) ),
	array( 'en' => 'Reload stylesheet', 'es' => 'Recargar hoja de estilos', 'not' => array( 'Recargar estilo' ) ),
	array( 'en' => 'LPM', 'es' => 'l/min', 'not' => array(  ) ),

	// round 2 (es)
	array( 'en' => 'Image', 'es' => 'Imagen', 'not' => array( 'Image' ) ),
	array( 'en' => 'an array of sensors', 'es' => 'un conjunto de sensores', 'not' => array( 'una amplia gama de sensores', 'una amplia variedad de sensores' ) ),
	array( 'en' => 'powered by sophisticated data acquisition software', 'es' => 'gestionados por un sofisticado software de adquisición de datos', 'not' => array( 'con tecnología de sofisticado software de adquisición de datos' ) ),
	array( 'en' => 'wireless barcode scanner', 'es' => 'lector inalámbrico de códigos de barras', 'not' => array( 'escáner de códigos de barras inalámbrico', 'escáner de código de barras inalámbrico' ) ),
	array( 'en' => 'multi-section', 'es' => 'multisección', 'not' => array( 'de múltiples cláusulas', 'múltiples cláusulas', 'multietapa', 'de varias secciones' ) ),
	array( 'en' => 'rear strut', 'es' => 'puntal trasero', 'not' => array( 'amortiguador trasero' ) ),
	array( 'en' => 'e-mobility', 'es' => 'movilidad eléctrica', 'not' => array( 'electromovilidad' ) ),
	array( 'en' => 'blower', 'es' => 'soplante', 'not' => array( 'soplador', 'sopladores' ) ),
	array( 'en' => 'retrofit', 'es' => 'retrofit', 'not' => array( 'modernización de máquinas existentes', 'soluciones de modernización', 'actualizaciones eléctricas' ) ),
	array( 'en' => 'second to none', 'es' => 'insuperables', 'not' => array( 'de primer nivel', 'son de primer nivel' ) ),
	array( 'en' => 'high-specification', 'es' => 'de altas prestaciones', 'not' => array( 'de alta especificación', 'alta especificación' ) ),
	array( 'en' => 'technological shaft', 'es' => 'eje tecnológico', 'not' => array( 'árbol tecnológico' ) ),
	array( 'en' => 'tooling', 'es' => 'utillaje', 'not' => array( 'accesorio', 'dispositivo de fijación', 'bancada' ) ),
	array( 'en' => 'fixture', 'es' => 'utillaje', 'not' => array( 'accesorio', 'dispositivo de fijación', 'bancada' ) ),
	array( 'en' => 'key features', 'es' => 'características principales', 'not' => array( 'principales características', 'características clave', 'rasgos clave', 'funciones clave' ) ),
	array( 'en' => 'runout', 'es' => 'descentramiento', 'not' => array( 'batimiento' ) ),
	array( 'en' => 'expansion sleeve', 'es' => 'casquillo expansor', 'not' => array( 'manguito de expansión', 'casquillo expansible' ) ),
	array( 'en' => 'roll surface', 'es' => 'superficie del cilindro', 'not' => array( 'superficie del rodillo' ) ),
	array( 'en' => 'leak test', 'es' => 'ensayo de estanqueidad', 'not' => array( 'prueba de fugas', 'ensayo de fugas' ) ),
	array( 'en' => 'Quality Grade', 'es' => 'Grado de calidad', 'not' => array( 'Categoría de calidad' ) ),
	array( 'en' => 'ECM software', 'es' => 'software del ECM', 'not' => array( 'software ECM', 'software de la ECM' ) ),
	array( 'en' => 'controller module', 'es' => 'módulo controlador', 'not' => array( 'módulo de control del', 'del módulo de control' ) ),
	array( 'en' => 'amperage draw', 'es' => 'consumo de corriente', 'not' => array( 'consumo de intensidad', 'intensidad consumida', 'intensidad de corriente', 'consumo de amperaje', 'amperaje consumido' ) ),
	array( 'en' => 'finger hole', 'es' => 'orificio de agarre', 'not' => array( 'orificio de dedo', 'agujero de dedo' ) ),
	array( 'en' => 'erection', 'es' => 'montaje', 'not' => array( 'construcción' ) ),
	array( 'en' => 'capital goods', 'es' => 'bienes de equipo', 'not' => array( 'bienes de capital' ) ),
	array( 'en' => 'Combine Transmission Assembly', 'es' => 'Montaje de transmisión de cosechadora', 'not' => array( 'Montaje de transmisión combinada' ) ),
	array( 'en' => 'Combine Draper Header', 'es' => 'cabezal de cinta de cosechadora', 'not' => array( 'cabezal de cinta para cosechadoras' ) ),
	array( 'en' => 'brake rotor', 'es' => 'disco de freno', 'not' => array( 'rotor de freno' ) ),
	array( 'en' => 'wet brakes', 'es' => 'frenos en baño de aceite', 'not' => array( 'frenos húmedos', 'frenos en húmedo' ) ),
	array( 'en' => 'Buzz-Squeak-Rattle', 'es' => 'ruidos, chirridos y traqueteos', 'not' => array( 'ruidos, chirridos y vibraciones' ) ),
	array( 'en' => 'Auto Toe Set', 'es' => 'Auto Toe Set', 'not' => array( 'ajuste automático de convergencia' ) ),
	array( 'en' => '2WD EPA chassis dynamometers', 'es' => 'dinamómetros de chasis EPA para tracción a dos ruedas', 'not' => array( 'dinamómetros de chasis 2WD', 'chasis EPA de tracción a dos ruedas', 'dinamómetros de chasis EPA para tracción en dos ruedas' ) ),
	array( 'en' => '4WD EPA chassis dynamometers', 'es' => 'dinamómetros de chasis EPA para tracción a las cuatro ruedas', 'not' => array( 'dinamómetros de chasis 4WD', 'chasis EPA de tracción a cuatro ruedas' ) ),
	array( 'en' => 'Propulsion and Powertrain', 'es' => 'Propulsión y grupo motopropulsor', 'not' => array( 'Grupo motopropulsor y propulsión' ) ),
	array( 'en' => 'Refrigeration & Gas Management', 'es' => 'Refrigeración y gestión de gases', 'not' => array(  ) ),
	array( 'en' => 'end-of-line', 'es' => 'fin de línea', 'not' => array( 'final de línea', 'final de la línea' ) ),
	array( 'en' => 'See what we do here', 'es' => 'Vea lo que hacemos aquí', 'not' => array( 'Lo que hacemos aquí', 'Descubra nuestra actividad' ) ),
	array( 'en' => 'Industry 4.0', 'es' => 'Industria 4.0', 'not' => array( 'Industry 4.0' ) ),
	array( 'en' => 'hard bearing', 'es' => 'apoyos rígidos', 'not' => array( 'rodamiento rígido', 'rodamientos rígidos', 'cojinete rígido' ) ),
	array( 'en' => 'soft bearing', 'es' => 'apoyos blandos', 'not' => array( 'rodamiento blando', 'rodamientos blandos', 'cojinete blando' ) ),
	array( 'en' => 'vacuum gauge', 'es' => 'vacuómetro', 'not' => array( 'manómetro de vacío', 'Manómetros' ) ),
	array( 'en' => 'Americas', 'es' => 'las Américas', 'not' => array( 'América' ) ),
	array( 'en' => 'headlight aiming', 'es' => 'reglaje de faros', 'not' => array( 'orientación de faros' ) ),
	array( 'en' => 'locations', 'es' => 'ubicaciones', 'not' => array( 'instalaciones' ) ),
	array( 'en' => 'Leakage', 'es' => 'Fugas', 'not' => array( 'Estanqueidad' ) ),
	array( 'en' => 'Launching resource', 'es' => 'Abriendo el recurso', 'not' => array( 'Cargando el recurso' ) ),
	array( 'en' => 'mass flow', 'es' => 'caudal másico', 'not' => array( 'flujo másico', 'caudal de masa' ) ),
	array( 'en' => 'flow metering', 'es' => 'medición de caudal', 'not' => array( 'medición por caudal', 'medición de flujo' ) ),
	array( 'en' => 'mission-critical', 'es' => 'de misión crítica', 'not' => array( 'crítico', 'críticos' ) ),
	array( 'en' => 'blank ECMs', 'es' => 'ECM sin programar', 'not' => array( 'ECM en blanco', 'ECM vírgenes' ) ),
	array( 'en' => 'Balancing Textbook', 'es' => 'Manual de equilibrado', 'not' => array( 'libro de texto sobre equilibrado' ) ),
	array( 'en' => 'Turbine Section', 'es' => 'sección de la turbina', 'not' => array( 'cláusula de la turbina' ) ),
	array( 'en' => 'multilingual test prompts', 'es' => 'instrucciones de ensayo multilingües', 'not' => array( 'mensajes de ensayo multilingües' ) ),
	array( 'en' => 'service routines', 'es' => 'rutinas de servicio', 'not' => array( 'rutinas de mantenimiento' ) ),
	array( 'en' => 'Custom-engineered test stands', 'es' => 'Bancos de ensayo a medida', 'not' => array( 'Bancos de ensayo diseñados a medida', 'Bancos de ensayo de diseño personalizado' ) ),
	array( 'en' => 'grinding machine modernization', 'es' => 'modernización de rectificadoras', 'not' => array( 'actualización de rectificadoras' ) ),

	// round pro (es)
	array( 'en' => 'balancer', 'es' => 'equilibradora', 'not' => array( 'balanceadora', 'equilibrador', 'máquina de balanceo' ) ),
	array( 'en' => 'imbalance', 'es' => 'desequilibrio', 'not' => array( 'desbalance', 'desbalanceo', 'imbalance' ) ),
	array( 'en' => 'dynamic balancing', 'es' => 'equilibrado dinámico', 'not' => array( 'balanceo dinámico', 'balanceado dinámico' ) ),
	array( 'en' => 'static balancing', 'es' => 'equilibrado estático', 'not' => array( 'balanceo estático' ) ),
	array( 'en' => 'vertical balancing machine', 'es' => 'equilibradora vertical', 'not' => array( 'máquina de equilibrado vertical', 'balanceadora vertical' ) ),
	array( 'en' => 'horizontal balancing machine', 'es' => 'equilibradora horizontal', 'not' => array( 'máquina de equilibrado horizontal', 'balanceadora horizontal' ) ),
	array( 'en' => 'rotor balancing', 'es' => 'equilibrado de rotores', 'not' => array( 'balanceo de rotores', 'equilibrado del rotor' ) ),
	array( 'en' => 'core balancing', 'es' => 'equilibrado de cartuchos', 'not' => array( 'equilibrado de núcleos', 'equilibrado del núcleo', 'balanceo de núcleos' ) ),
	array( 'en' => 'high-speed core balancing', 'es' => 'equilibrado de cartuchos a alta velocidad', 'not' => array( 'equilibrado de núcleos a alta velocidad', 'equilibrado de núcleo de alta velocidad' ) ),
	array( 'en' => 'low-speed core balancing', 'es' => 'equilibrado de cartuchos a baja velocidad', 'not' => array( 'equilibrado de núcleos a baja velocidad', 'equilibrado de núcleo de baja velocidad' ) ),
	array( 'en' => 'turbocharger core', 'es' => 'cartucho del turbocompresor', 'not' => array( 'núcleo del turbocompresor', 'conjunto de núcleo de turbocompresor' ) ),
	array( 'en' => 'single-plane balancing', 'es' => 'equilibrado en un plano', 'not' => array( 'balanceo de un plano', 'equilibrado de plano único' ) ),
	array( 'en' => 'correction plane', 'es' => 'plano de corrección', 'not' => array( 'plano correctivo' ) ),
	array( 'en' => 'unbalance correction', 'es' => 'corrección del desequilibrio', 'not' => array( 'corrección del desbalance', 'rectificación del desequilibrio' ) ),
	array( 'en' => 'balancing speed', 'es' => 'velocidad de equilibrado', 'not' => array( 'velocidad de balanceo' ) ),
	array( 'en' => 'balancing weight', 'es' => 'masa de equilibrado', 'not' => array( 'peso de balanceo', 'pesa de balanceo' ) ),
	array( 'en' => 'balance quality grade', 'es' => 'grado de calidad de equilibrado', 'not' => array( 'grado de calidad del balanceo', 'grado de calidad de balance' ) ),
	array( 'en' => 'unbalance reduction ratio', 'es' => 'relación de reducción del desequilibrio', 'not' => array( 'tasa de reducción de desequilibrio', 'ratio de reducción del desbalance' ) ),
	array( 'en' => 'minimum achievable residual unbalance', 'es' => 'desequilibrio residual mínimo alcanzable', 'not' => array( 'desbalance residual mínimo alcanzable', 'desequilibrio residual mínimo conseguible' ) ),
	array( 'en' => 'measuring system', 'es' => 'sistema de medición', 'not' => array( 'sistema medidor', 'sistema de medir' ) ),
	array( 'en' => 'measuring and control unit', 'es' => 'unidad de medición y control', 'not' => array( 'unidad medidora y de control' ) ),
	array( 'en' => 'mass centering', 'es' => 'centrado de masas', 'not' => array( 'centrado másico', 'centraje de masa' ) ),
	array( 'en' => 'workholding', 'es' => 'utillaje de sujeción', 'not' => array( 'sujeción de trabajo', 'retención de trabajo' ) ),
	array( 'en' => 'zero clearance', 'es' => 'holgura cero', 'not' => array( 'juego cero', 'espacio cero' ) ),
	array( 'en' => 'crankshaft balancing machine', 'es' => 'equilibradora de cigüeñales', 'not' => array( 'máquina de equilibrado de cigüeñales', 'balanceadora de cigüeñales' ) ),
	array( 'en' => 'driveshaft balancer', 'es' => 'equilibradora de árboles de transmisión', 'not' => array( 'equilibradora de semiejes', 'equilibradora de ejes motrices' ) ),
	array( 'en' => 'fan balancer', 'es' => 'equilibradora de ventiladores', 'not' => array( 'máquina equilibradora de ventiladores', 'balanceadora de ventiladores' ) ),
	array( 'en' => 'flow bench', 'es' => 'banco de flujo', 'not' => array( 'mesa de flujo', 'bancada de flujo' ) ),
	array( 'en' => 'compressor wheel', 'es' => 'rueda de compresor', 'not' => array( 'rueda compresora', 'disco del compresor' ) ),
	array( 'en' => 'turbine wheel', 'es' => 'rueda de turbina', 'not' => array( 'rueda turbina', 'disco de turbina' ) ),
	array( 'en' => 'turbocharger', 'es' => 'turbocompresor', 'not' => array( 'turbocargador', 'turbo cargador' ) ),
	array( 'en' => 'supercharger', 'es' => 'compresor volumétrico', 'not' => array( 'supercargador', 'sobrealimentador' ) ),
	array( 'en' => 'journal diameter', 'es' => 'diámetro del muñón', 'not' => array( 'diámetro del diario', 'diámetro de la revista' ) ),
	array( 'en' => 'rotational speed', 'es' => 'velocidad de rotación', 'not' => array( 'velocidad rotacional', 'rapidez de giro' ) ),
	array( 'en' => 'self-learning', 'es' => 'autoaprendizaje', 'not' => array( 'autoaprendiente', 'aprendizaje propio' ) ),
	array( 'en' => 'spindle', 'es' => 'husillo', 'not' => array( 'huso', 'mandril' ) ),
	array( 'en' => 'impeller', 'es' => 'rodete', 'not' => array( 'impulsor', 'impeledor' ) ),
	array( 'en' => 'pump impeller', 'es' => 'rodete de bomba', 'not' => array( 'impulsor de bomba', 'impulsor de la bomba' ) ),
	array( 'en' => 'saw blade', 'es' => 'hoja de sierra', 'not' => array( 'cuchilla de sierra', 'lámina de sierra' ) ),
	array( 'en' => 'wind turbine', 'es' => 'aerogenerador', 'not' => array( 'turbina eólica', 'turbina de viento' ) ),
	array( 'en' => 'propeller', 'es' => 'hélice', 'not' => array( 'propela', 'propulsor de hélice' ) ),
	array( 'en' => 'inertial navigation', 'es' => 'navegación inercial', 'not' => array( 'navegación por inercia', 'navegación inercia' ) ),
	array( 'en' => 'guidance and navigation', 'es' => 'guiado y navegación', 'not' => array( 'guía y navegación', 'orientación y navegación' ) ),
	array( 'en' => 'defense manufacturing', 'es' => 'fabricación para defensa', 'not' => array( 'fabricación de defensa', 'manufactura de defensa' ) ),
	array( 'en' => 'passenger car', 'es' => 'turismo', 'not' => array( 'coche de pasajeros', 'automóvil de pasajeros', 'carro de pasajeros' ) ),
	array( 'en' => 'light-duty vehicle', 'es' => 'vehículo ligero', 'not' => array( 'vehículo de servicio ligero', 'vehículo de trabajo ligero' ) ),
	array( 'en' => 'heavy-duty truck', 'es' => 'camión pesado', 'not' => array( 'camión de alta resistencia', 'camión para trabajo pesado' ) ),
	array( 'en' => 'mining truck', 'es' => 'camión minero', 'not' => array( 'camión de minería', 'camión de mina' ) ),
	array( 'en' => 'skid loader', 'es' => 'minicargadora', 'not' => array( 'minicargadora de ruedas', 'cargadora deslizante' ) ),
	array( 'en' => 'wheel loader', 'es' => 'cargadora de ruedas', 'not' => array( 'cargador de ruedas', 'cargador frontal de ruedas' ) ),
	array( 'en' => 'mobile equipment', 'es' => 'maquinaria móvil', 'not' => array( 'equipos móviles', 'equipo móvil' ) ),
	array( 'en' => 'chassis dynamometer', 'es' => 'dinamómetro de chasis', 'not' => array( 'banco de chasis', 'dinamómetro de bastidor' ) ),
	array( 'en' => 'mileage accumulator', 'es' => 'banco de acumulación de kilometraje', 'not' => array( 'acumulador de millaje' ) ),
	array( 'en' => 'transmission test', 'es' => 'ensayo de transmisiones', 'not' => array( 'prueba de transmisión', 'test de transmisión' ) ),
	array( 'en' => 'dual clutch transmission', 'es' => 'cambio de doble embrague', 'not' => array( 'transmisión de embrague dual' ) ),
	array( 'en' => 'wet clutch', 'es' => 'embrague en baño de aceite', 'not' => array( 'embrague mojado' ) ),
	array( 'en' => 'electric drive', 'es' => 'accionamiento eléctrico', 'not' => array( 'unidad eléctrica', 'manejo eléctrico' ) ),
	array( 'en' => 'electric drive gearbox', 'es' => 'reductor del accionamiento eléctrico', 'not' => array( 'caja de cambios de accionamiento eléctrico', 'caja de engranajes de accionamiento eléctrico' ) ),
	array( 'en' => 'axle shaft', 'es' => 'semieje', 'not' => array( 'árbol del eje', 'eje del eje' ) ),
	array( 'en' => 'beam axle', 'es' => 'eje rígido', 'not' => array( 'eje de viga', 'eje de haz' ) ),
	array( 'en' => 'torque', 'es' => 'par', 'not' => array( 'torque', 'torsión' ) ),
	array( 'en' => 'toe set', 'es' => 'ajuste de la convergencia', 'not' => array( 'ajuste del dedo', 'ajuste de punta' ) ),
	array( 'en' => 'camber', 'es' => 'caída', 'not' => array( 'combadura', 'camber', 'inclinación de rueda' ) ),
	array( 'en' => 'test track', 'es' => 'pista de ensayos', 'not' => array( 'circuito de pruebas', 'pista de prueba' ) ),
	array( 'en' => 'e-motor', 'es' => 'motor eléctrico', 'not' => array( 'e-motor', 'motor-e' ) ),
	array( 'en' => 'fuel cell', 'es' => 'pila de combustible', 'not' => array( 'celda de combustible', 'célula de combustible' ) ),
	array( 'en' => 'aftermarket', 'es' => 'posventa', 'not' => array( 'mercado de accesorios', 'mercado secundario' ) ),
	array( 'en' => 'fluid power test stand', 'es' => 'banco de ensayo hidráulico', 'not' => array( 'banco de ensayo de potencia fluida', 'banco de pruebas de potencia de fluidos' ) ),
	array( 'en' => 'fluid power test system', 'es' => 'sistema de ensayo hidráulico', 'not' => array( 'sistema de ensayo de potencia fluida', 'sistema de pruebas de potencia de fluidos' ) ),
	array( 'en' => 'gear pump', 'es' => 'bomba de engranajes', 'not' => array( 'bomba de engranaje', 'bomba de piñones' ) ),
	array( 'en' => 'piston pump', 'es' => 'bomba de pistones', 'not' => array( 'bomba de émbolos', 'bomba a pistón' ) ),
	array( 'en' => 'axial piston pump', 'es' => 'bomba de pistones axiales', 'not' => array( 'bomba de pistón axial', 'bomba axial de pistón' ) ),
	array( 'en' => 'valve test', 'es' => 'ensayo de válvulas', 'not' => array( 'prueba de válvulas', 'test de válvulas' ) ),
	array( 'en' => 'cartridge valve', 'es' => 'válvula de cartucho', 'not' => array( 'válvula cartucho', 'cartucho de válvula' ) ),
	array( 'en' => 'check valve', 'es' => 'válvula antirretorno', 'not' => array( 'válvula check', 'válvula de chequeo' ) ),
	array( 'en' => 'pressure relief setting', 'es' => 'tarado de la presión de alivio', 'not' => array( 'configuración del alivio de presión' ) ),
	array( 'en' => 'case drain', 'es' => 'drenaje de carcasa', 'not' => array( 'drenaje de caja', 'drenaje del estuche' ) ),
	array( 'en' => 'flow rate', 'es' => 'caudal', 'not' => array( 'tasa de flujo', 'velocidad de flujo', 'rata de flujo' ) ),
	array( 'en' => 'pressure decay', 'es' => 'caída de presión', 'not' => array( 'decaimiento de presión', 'decadencia de presión' ) ),
	array( 'en' => 'helium leak detection', 'es' => 'detección de fugas con helio', 'not' => array( 'detección de fugas de helio', 'detección de escapes de helio' ) ),
	array( 'en' => 'helium recovery', 'es' => 'recuperación de helio', 'not' => array( 'recobro de helio', 'reciclaje de helio' ) ),
	array( 'en' => 'sniffer', 'es' => 'sonda de aspiración', 'not' => array( 'sonda de olfateo', 'olfateador', 'sniffer' ) ),
	array( 'en' => 'white goods', 'es' => 'electrodomésticos de línea blanca', 'not' => array( 'bienes blancos', 'productos blancos', 'línea blanca de bienes' ) ),
	array( 'en' => 'HVAC', 'es' => 'climatización', 'not' => array( 'CVAA' ) ),
	array( 'en' => 'eddy current', 'es' => 'corrientes inducidas', 'not' => array( 'corrientes de Foucault', 'corrientes parásitas', 'corrientes de remolino' ) ),
	array( 'en' => 'ultrasonic testing', 'es' => 'ensayo por ultrasonidos', 'not' => array( 'prueba ultrasónica', 'testeo ultrasónico' ) ),
	array( 'en' => 'ultrasonic inspection', 'es' => 'inspección por ultrasonidos', 'not' => array( 'inspección de ultrasonido', 'inspección ultrasonido' ) ),
	array( 'en' => 'surface wave', 'es' => 'ondas superficiales', 'not' => array( 'olas superficiales' ) ),
	array( 'en' => 'subsurface defect', 'es' => 'defecto subsuperficial', 'not' => array( 'defecto del subsuelo', 'defecto bajo superficie' ) ),
	array( 'en' => 'crack', 'es' => 'grieta', 'not' => array( 'rajadura', 'quiebre' ) ),
	array( 'en' => 'roll grinding', 'es' => 'rectificado de cilindros', 'not' => array( 'rectificado de rodillos', 'amolado de cilindros' ) ),
	array( 'en' => 'roll grinder', 'es' => 'rectificadora de cilindros', 'not' => array( 'amoladora de rodillos', 'rectificadora de rodillos' ) ),
	array( 'en' => 'grinding machine', 'es' => 'rectificadora', 'not' => array( 'máquina de rectificar', 'amoladora', 'esmeriladora' ) ),
	array( 'en' => 'roll shop', 'es' => 'taller de cilindros', 'not' => array( 'taller de rodillos', 'tienda de rodillos' ) ),
	array( 'en' => 'roll texturing', 'es' => 'texturizado de cilindros', 'not' => array( 'texturizado de rodillos', 'texturado de rollos' ) ),
	array( 'en' => 'surface roughening', 'es' => 'texturizado superficial', 'not' => array( 'rugosidad superficial', 'raspado superficial' ) ),
	array( 'en' => 'rolling mill', 'es' => 'laminador', 'not' => array( 'molino de laminación', 'molino laminador' ) ),
	array( 'en' => 'six-high', 'es' => 'de seis cilindros', 'not' => array( 'de seis alturas', 'séxtuple' ) ),
	array( 'en' => 'steel mill', 'es' => 'acería', 'not' => array( 'molino de acero', 'fábrica de acero' ) ),
	array( 'en' => 'milling', 'es' => 'fresado', 'not' => array( 'molienda', 'molido' ) ),
	array( 'en' => 'machining center', 'es' => 'centro de mecanizado', 'not' => array( 'centro de maquinado', 'centro de mecanización' ) ),
	array( 'en' => 'chip extraction', 'es' => 'extracción de viruta', 'not' => array( 'eliminación de chips', 'extracción de astillas' ) ),
	array( 'en' => 'tool holder', 'es' => 'portaherramientas', 'not' => array( 'soporte de herramienta', 'sujetaherramientas' ) ),
	array( 'en' => 'shim', 'es' => 'calza', 'not' => array( 'calzo', 'calzos' ) ),
	array( 'en' => 'press-fit', 'es' => 'montaje a presión', 'not' => array( 'ajuste de prensa', 'encaje de prensa' ) ),
	array( 'en' => 'fastener', 'es' => 'elemento de fijación', 'not' => array( 'sujetador', 'sujetadores' ) ),
	array( 'en' => 'turnover station', 'es' => 'estación de volteo', 'not' => array( 'estación de vuelco' ) ),
	array( 'en' => 'conveyor', 'es' => 'transportador', 'not' => array( 'convoyer', 'conveyor' ) ),
	array( 'en' => 'PLC', 'es' => 'PLC', 'not' => array( 'controlador lógico programable' ) ),
	array( 'en' => 'control cabinet', 'es' => 'armario eléctrico', 'not' => array( 'gabinete de control', 'gabinete eléctrico' ) ),
	array( 'en' => 'drive system', 'es' => 'sistema de accionamiento', 'not' => array( 'sistema de conducción', 'sistema de manejo' ) ),
	array( 'en' => 'switchgear', 'es' => 'aparamenta', 'not' => array( 'conmutadores', 'equipo de conmutación' ) ),
	array( 'en' => 'vision system', 'es' => 'sistema de visión artificial', 'not' => array( 'sistema de visión de máquina', 'sistema de visionado' ) ),
	array( 'en' => 'safety guarding', 'es' => 'resguardos de seguridad', 'not' => array( 'guardas de seguridad', 'guardias de seguridad' ) ),
	array( 'en' => 'guard locking', 'es' => 'bloqueo del resguardo', 'not' => array( 'bloqueo de guarda', 'bloqueo de la guardia' ) ),
	array( 'en' => 'interlock', 'es' => 'enclavamiento', 'not' => array( 'interbloqueo', 'entrecierre' ) ),
	array( 'en' => 'touchscreen', 'es' => 'pantalla táctil', 'not' => array( 'pantalla de toque', 'touchscreen' ) ),
	array( 'en' => 'data acquisition', 'es' => 'adquisición de datos', 'not' => array( 'captura de datos' ) ),
	array( 'en' => 'traceability', 'es' => 'trazabilidad', 'not' => array( 'rastreabilidad', 'seguibilidad' ) ),
	array( 'en' => 'repeatability', 'es' => 'repetibilidad', 'not' => array( 'repetitividad', 'reproducibilidad' ) ),
	array( 'en' => 'accuracy and repeatability', 'es' => 'precisión y repetibilidad', 'not' => array( 'exactitud y repetitividad', 'precisión y repetitividad' ) ),
	array( 'en' => 'assembly error', 'es' => 'error de montaje', 'not' => array( 'error de ensamblaje', 'error de ensamble' ) ),
	array( 'en' => 'verification and validation', 'es' => 'verificación y validación', 'not' => array( 'verificación y convalidación' ) ),
	array( 'en' => 'test stand', 'es' => 'banco de ensayo', 'not' => array( 'banco de pruebas', 'soporte de ensayo' ) ),
	array( 'en' => 'test bench', 'es' => 'banco de ensayo', 'not' => array( 'banco de pruebas', 'bancada de prueba' ) ),
	array( 'en' => 'test system', 'es' => 'sistema de ensayo', 'not' => array( 'sistema de prueba', 'sistema de pruebas' ) ),
	array( 'en' => 'test cell', 'es' => 'celda de ensayo', 'not' => array( 'celda de prueba', 'célula de prueba' ) ),
	array( 'en' => 'cycle time', 'es' => 'tiempo de ciclo', 'not' => array( 'duración del ciclo', 'tiempo de ciclado' ) ),
	array( 'en' => 'changeover', 'es' => 'cambio de referencia', 'not' => array( 'conmutación', 'changeover' ) ),
	array( 'en' => 'floor space', 'es' => 'espacio en planta', 'not' => array( 'espacio de suelo', 'espacio de piso' ) ),
	array( 'en' => 'small footprint', 'es' => 'superficie ocupada reducida', 'not' => array( 'huella pequeña', 'pequeña huella' ) ),
	array( 'en' => 'global footprint', 'es' => 'presencia global', 'not' => array( 'huella global', 'huella mundial' ) ),
	array( 'en' => 'downtime', 'es' => 'tiempo de parada', 'not' => array( 'tiempo caído', 'downtime' ) ),
	array( 'en' => 'unplanned downtime', 'es' => 'paradas no planificadas', 'not' => array( 'tiempo muerto no planeado', 'tiempo caído no planificado' ) ),
	array( 'en' => 'uptime', 'es' => 'disponibilidad', 'not' => array( 'tiempo de actividad', 'tiempo arriba' ) ),
	array( 'en' => 'predictive maintenance', 'es' => 'mantenimiento predictivo', 'not' => array( 'mantención predictiva' ) ),
	array( 'en' => 'remote support', 'es' => 'asistencia remota', 'not' => array( 'soporte remoto', 'apoyo remoto' ) ),
	array( 'en' => 'technical support', 'es' => 'asistencia técnica', 'not' => array( 'soporte técnico', 'apoyo técnico' ) ),
	array( 'en' => 'installation and commissioning', 'es' => 'instalación y puesta en marcha', 'not' => array( 'instalación y comisionamiento' ) ),
	array( 'en' => 'operator training', 'es' => 'formación de operarios', 'not' => array( 'entrenamiento de operadores', 'capacitación de operadores' ) ),
	array( 'en' => 'minimal operator interaction', 'es' => 'mínima intervención del operario', 'not' => array( 'interacción mínima del operador', 'mínima interacción del operador' ) ),
	array( 'en' => 'service engineer', 'es' => 'técnico de servicio', 'not' => array( 'ingeniero de servicio' ) ),
	array( 'en' => 'on-site', 'es' => 'in situ', 'not' => array( 'en sitio', 'on-site' ) ),
	array( 'en' => 'spare parts', 'es' => 'piezas de repuesto', 'not' => array( 'partes de repuesto', 'refacciones' ) ),
	array( 'en' => 'lead time', 'es' => 'plazo de entrega', 'not' => array( 'tiempo de espera', 'lead time' ) ),
	array( 'en' => 'high-volume production', 'es' => 'producción en gran serie', 'not' => array( 'producción de alto volumen', 'producción en alto volumen' ) ),
	array( 'en' => 'end user', 'es' => 'usuario final', 'not' => array( 'usuario terminal' ) ),
	array( 'en' => 'designed and built', 'es' => 'diseñado y fabricado', 'not' => array( 'diseñado y construido', 'diseñado y hecho' ) ),
	array( 'en' => 'custom-built', 'es' => 'a medida', 'not' => array( 'hecho a la medida', 'fabricado por encargo' ) ),
	array( 'en' => 'almost completely automated', 'es' => 'casi totalmente automatizado', 'not' => array( 'prácticamente automatizado en su totalidad', 'con un grado de automatización casi total' ) ),
	array( 'en' => 'wide range of products', 'es' => 'amplia gama de productos', 'not' => array( 'amplio rango de productos' ) ),
	array( 'en' => 'leading global provider', 'es' => 'proveedor líder mundial', 'not' => array( 'proveedor global líder', 'líder proveedor global' ) ),
	array( 'en' => 'industry-leading', 'es' => 'líder en el sector', 'not' => array( 'líder en la industria', 'líder de la industria' ) ),
	array( 'en' => 'state-of-the-art', 'es' => 'de última generación', 'not' => array( 'estado del arte', 'del estado del arte' ) ),
	array( 'en' => 'best practices', 'es' => 'buenas prácticas', 'not' => array( 'mejores prácticas', 'prácticas óptimas' ) ),
	array( 'en' => 'business unit', 'es' => 'unidad de negocio', 'not' => array( 'unidad de negocios', 'unidad comercial' ) ),
	array( 'en' => 'headquartered in', 'es' => 'con sede en', 'not' => array( 'con cuartel general en' ) ),
	array( 'en' => 'as standard', 'es' => 'de serie', 'not' => array( 'como estándar', 'de manera estándar' ) ),
	array( 'en' => 'Selected Capabilities', 'es' => 'Capacidades destacadas', 'not' => array( 'Capacidades seleccionadas', 'Capacidades selectas' ) ),
	array( 'en' => 'Overview', 'es' => 'Descripción general', 'not' => array( 'Visión general', 'Resumen general', 'Sinopsis' ) ),
	array( 'en' => 'FAQ', 'es' => 'Preguntas frecuentes', 'not' => array( 'Preguntas más frecuentes' ) ),
	array( 'en' => 'Frequently Asked Questions', 'es' => 'Preguntas frecuentes', 'not' => array( 'Preguntas hechas frecuentemente', 'Preguntas más frecuentes' ) ),
	array( 'en' => 'Technical Specifications', 'es' => 'Especificaciones técnicas', 'not' => array( 'Especificaciones de técnica', 'Specs técnicas' ) ),
	array( 'en' => 'Related Products', 'es' => 'Productos relacionados', 'not' => array( 'Productos relativos', 'Productos vinculados' ) ),
	array( 'en' => 'Contact our engineering team', 'es' => 'Póngase en contacto con nuestro equipo de ingeniería', 'not' => array( 'Contacte a nuestro equipo de ingeniería', 'Contacta con nuestro equipo de ingeniería', 'Contacte con nuestro equipo de ingeniería' ) ),
	array( 'en' => 'custom quote', 'es' => 'presupuesto personalizado', 'not' => array( 'cotización personalizada', 'cotización a medida' ) ),
	array( 'en' => 'technical consultation', 'es' => 'consulta técnica', 'not' => array( 'consultoría técnica' ) ),
	array( 'en' => 'Get in touch', 'es' => 'Póngase en contacto con nosotros', 'not' => array( 'Entre en contacto', 'Ponte en contacto' ) ),
	array( 'en' => 'Learn more', 'es' => 'Descubra más', 'not' => array( 'Aprenda más', 'Aprende más', 'Saber más' ) ),
	array( 'en' => 'Watch Demo', 'es' => 'Vea la demostración', 'not' => array( 'Ver demostración', 'Mire la demo', 'Watch Demo' ) ),
	array( 'en' => 'Back to Blog', 'es' => 'Volver al blog', 'not' => array( 'Regresar al blog', 'Atrás al blog' ) ),
	array( 'en' => 'Upcoming event', 'es' => 'Próximo evento', 'not' => array( 'Evento próximo', 'Evento venidero' ) ),
	array( 'en' => 'Event details', 'es' => 'Detalles del evento', 'not' => array( 'Detalles de evento', 'Event details' ) ),
	array( 'en' => 'Editorial Contacts', 'es' => 'Contactos para medios', 'not' => array( 'Contactos editoriales', 'Editorial Contacts' ) ),
	array( 'en' => 'press release', 'es' => 'nota de prensa', 'not' => array( 'comunicado de prensa', 'lanzamiento de prensa' ) ),
	array( 'en' => 'brochure', 'es' => 'folleto', 'not' => array( 'brochure', 'prospecto' ) ),
	array( 'en' => 'flyer', 'es' => 'folleto', 'not' => array( 'volante', 'flyer' ) ),
	array( 'en' => 'video', 'es' => 'vídeo', 'not' => array( 'video' ) ),
	array( 'en' => 'rpm', 'es' => 'rpm', 'not' => array( 'r.p.m.', 'rpms' ) ),
	array( 'en' => 'GPM', 'es' => 'gal/min', 'not' => array( 'galones por minuto' ) ),
	array( 'en' => 'HP', 'es' => 'hp', 'not' => array(  ) ),
	array( 'en' => 'two-plane', 'es' => 'en dos planos', 'not' => array( 'de dos planos', 'biplano' ) ),
	array( 'en' => 'bob-weight', 'es' => 'masa de simulación', 'not' => array( 'peso bob', 'pesa bob' ) ),
	array( 'en' => 'leading edge', 'es' => 'de vanguardia', 'not' => array( 'de filo', 'borde principal' ) ),
	array( 'en' => 'drilling correction', 'es' => 'corrección por taladrado', 'not' => array( 'corrección por perforación', 'corrección de perforación' ) ),
	array( 'en' => 'drivetrain', 'es' => 'cadena cinemática', 'not' => array( 'tren motriz', 'tren de transmisión' ) ),
	array( 'en' => 'data acquisition software', 'es' => 'software de adquisición de datos', 'not' => array( 'software de captura de datos' ) ),
	array( 'en' => 'automated diagnostic inspection', 'es' => 'inspección de diagnóstico automatizada', 'not' => array( 'inspección diagnóstica automatizada', 'inspección automatizada diagnóstica' ) ),
	array( 'en' => 'validation testing', 'es' => 'ensayos de validación', 'not' => array( 'pruebas de validación', 'testeo de validación' ) ),
	array( 'en' => 'control system', 'es' => 'sistema de control', 'not' => array( 'sistema de controles', 'sistema controlador' ) ),
	array( 'en' => 'fully automated', 'es' => 'totalmente automatizado', 'not' => array( 'full automatizado', 'plenamente automático' ) ),
);
