<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

return array(
	array( 'en' => '*', 'fr' => 'Le site s’adresse au lecteur au vouvoiement professionnel, dans TOUTES les chaînes et tous les emplacements : corps de texte, titres, surtitres, bandeaux en capitales, boutons, libellés et textes d’aide de formulaire, textes alternatifs et aria, balise <title>, méta-description, balises og: et JSON-LD. Le registre est une propriété de la PAGE, pas du segment : un tutoiement dans une méta-description contredit le corps de page vouvoyé livré avec elle. Le possessif adressé au lecteur est « votre / vos », jamais « ton / ta / tes », et l’adjectif ou le participe qui s’accorde avec le lecteur reste au masculin singulier de politesse (« Prêt à moderniser votre infrastructure ? »). Le ton est celui de l’écrit technique B2B français : phrases complètes, pas d’exclamations, pas d’argot, pas de familiarité. LES BOUTONS ET LIBELLÉS DE LIEN suivent la convention française du web : l’infinitif pour les entrées de navigation et les boutons autonomes — « Browse catalog » est « Parcourir le catalogue », « Download » est « Télécharger », « Request a demo » est « Demander une démo », « Contact us » est « Nous contacter » — et l’impératif vouvoyé pour les incitations rédigées et les libellés à l’intérieur d’un formulaire : « Speak with an expert » est « Échangez avec un expert », « Select your support team » est « Sélectionnez votre équipe d’assistance ». Le verbe anglais est toujours conservé : ne jamais aplatir un libellé verbal en simple nom (« Catalogue » pour « Browse catalog », « Téléchargement » pour « Download », « Demande de démo » pour « Request a demo » sont fautifs), et ne jamais mélanger infinitif et impératif dans un même formulaire ou un même groupe de boutons.', 'not' => array( 'tu', 'toi', 'tes', 'tien', 'tienne', 'tiens', 'tiennes', 'toi-même', 'peux-tu', 'veux-tu', 'as-tu', 'es-tu', 'sais-tu', 'inscris-toi', 'connecte-toi', 'abonne-toi', 'Découvre', 'Télécharge', 'Inscris-toi', 'Contacte-nous', 'Parle', 'Regarde', 'Clique' ) ),
	array( 'en' => 'unbalance', 'fr' => 'balourd', 'not' => array( 'déséquilibre', 'non-équilibre', 'déséquilibrage', 'désiquilibre' ) ),
	array( 'en' => 'residual unbalance', 'fr' => 'balourd résiduel', 'not' => array( 'déséquilibre résiduel', 'déséquilibre restant' ) ),
	array( 'en' => 'balancing', 'fr' => 'équilibrage', 'not' => array( 'balancement', 'rectification', 'pondération' ) ),
	array( 'en' => 'balancer', 'fr' => 'équilibreuse', 'not' => array( 'balancier', 'balanceur' ) ),
	array( 'en' => 'balancing machine', 'fr' => 'machine d’équilibrage', 'not' => array( 'machine de balancement', 'équilibreur' ) ),
	array( 'en' => 'correction', 'fr' => 'correction', 'not' => array(  ) ),
	array( 'en' => 'rotor', 'fr' => 'rotor', 'not' => array(  ) ),
	array( 'en' => 'maximum rotor diameter', 'fr' => 'diamètre maximal du rotor', 'not' => array(  ) ),
	array( 'en' => 'non-rotating balancing machine', 'fr' => 'machine d’équilibrage sans rotation', 'not' => array( 'équilibreuse sans rotor', 'machine d’équilibrage non rotative', 'équilibreuse non tournante' ) ),
	array( 'en' => 'Non-Rotate Systems', 'fr' => 'Systèmes sans rotation', 'not' => array( 'Systèmes non rotatifs', 'Systèmes de non-rotation', 'Systèmes sans rotor' ) ),
	array( 'en' => 'field balancing', 'fr' => 'équilibrage sur site', 'not' => array( 'équilibrage de terrain', 'équilibrage en champ', 'équilibrage portable' ) ),
	array( 'en' => 'Field Balancers', 'fr' => 'équilibreuses de chantier', 'not' => array( 'Équilibreuses portables', 'Équilibreurs de terrain' ) ),
	array( 'en' => 'spin testing machine', 'fr' => 'machine d’essai en survitesse', 'not' => array( 'machine d’essai de rotation', 'machine de test de filage', 'machine de rotation' ) ),
	array( 'en' => 'Spin Testing', 'fr' => 'Essais en survitesse', 'not' => array( 'Essai de rotation', 'Test de filage', 'Essais de rotation' ) ),
	array( 'en' => 'burst proof protection', 'fr' => 'protection contre l’éclatement', 'not' => array( 'protection anti-explosion', 'protection contre l’explosion' ) ),
	array( 'en' => 'audit stations', 'fr' => 'postes de mesure', 'not' => array( 'stations d’audit', 'postes d’audit', 'postes de vérification comptable' ) ),
	array( 'en' => 'single and multi-station', 'fr' => 'mono-poste et multiposte', 'not' => array( 'station unique et stations multiples', 'monochambre et multichambre', 'une et plusieurs chambres' ) ),
	array( 'en' => 'bearers', 'fr' => 'galets de support', 'not' => array( 'roulements', 'porteurs', 'brancards' ) ),
	array( 'en' => 'pedestals', 'fr' => 'paliers supports', 'not' => array( 'piédestaux', 'socles', 'estrades' ) ),
	array( 'en' => 'pins', 'fr' => 'axes', 'not' => array( 'épingles', 'goupilles', 'chevilles' ) ),
	array( 'en' => 'bearing center lines', 'fr' => 'axes des paliers', 'not' => array( 'lignes centrales de roulement', 'lignes médianes des roulements' ) ),
	array( 'en' => 'bearing life', 'fr' => 'durée de vie des roulements', 'not' => array( 'vie du roulement', 'longévité de palier' ) ),
	array( 'en' => 'v-block support', 'fr' => 'support en V', 'not' => array( 'soutien de bloc en V', 'bloc en V de soutien' ) ),
	array( 'en' => 'punching', 'fr' => 'poinçonnage', 'not' => array( 'frappe', 'poinçonnement', 'perforation par coup' ) ),
	array( 'en' => 'Electronic hung mass', 'fr' => 'masse suspendue électronique', 'not' => array( 'masse pendue électronique', 'masse accrochée électronique' ) ),
	array( 'en' => 'vibration', 'fr' => 'vibrations', 'not' => array(  ) ),
	array( 'en' => 'kinetostatics', 'fr' => 'cinétostatique', 'not' => array(  ) ),
	array( 'en' => 'TIR', 'fr' => 'faux-rond radial', 'not' => array( 'déviation radiale', 'voilage radial', 'indication totale de lecture' ) ),
	array( 'en' => 'radial run-out', 'fr' => 'faux-rond radial', 'not' => array( 'course radiale', 'sortie radiale' ) ),
	array( 'en' => 'Propeller Balancers', 'fr' => 'équilibreuses d’hélices', 'not' => array( 'équilibreuses de propulseurs' ) ),
	array( 'en' => 'Balancers for Clutches', 'fr' => 'équilibreuses pour embrayages', 'not' => array(  ) ),
	array( 'en' => 'Balancers for Rims', 'fr' => 'équilibreuses pour jantes', 'not' => array( 'équilibreuses pour bords' ) ),
	array( 'en' => 'Turbo Balancing Machine', 'fr' => 'machine d’équilibrage de turbocompresseurs', 'not' => array( 'machine d’équilibrage turbo' ) ),
	array( 'en' => 'Industrial Balancing Machine', 'fr' => 'machine d’équilibrage industrielle', 'not' => array( 'machine industrielle d’équilibrage' ) ),
	array( 'en' => 'Balancers for Dual Mass Flywheels', 'fr' => 'équilibreuses pour volants moteurs bimasses', 'not' => array( 'équilibreuses pour volants d’inertie à double masse' ) ),
	array( 'en' => 'Automated Balancers for Rotors of Superchargers', 'fr' => 'équilibreuses automatiques pour rotors de compresseurs de suralimentation', 'not' => array( 'équilibreuses automatiques pour rotors de compresseurs' ) ),
	array( 'en' => 'Balancers for ECFA and HVAC Blowers', 'fr' => 'équilibreuses pour soufflantes ECFA et CVC', 'not' => array( 'équilibreuses pour ventilateurs ECFA et CVC' ) ),
	array( 'en' => 'Vertical Manual - Fans', 'fr' => 'Manuel vertical – Ventilateurs', 'not' => array( 'Ventilateurs verticaux manuels' ) ),
	array( 'en' => 'Horizontal Manual - Wheel Sets', 'fr' => 'Manuel horizontal – Essieux montés', 'not' => array( 'Manuel horizontal – Essieux', 'Manuel horizontal – Jeux de roues' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'fr' => 'rouleaux de convoyeur et cylindres de machine à papier', 'not' => array( 'cylindres de convoyeur et de papier', 'rouleaux de convoyeur et de papier' ) ),
	array( 'en' => 'core', 'fr' => 'cartouche', 'not' => array( 'noyau', 'noyaux', 'coeur' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'fr' => 'machine d’équilibrage de cartouches combinée haute et basse vitesse', 'not' => array( 'machine d’équilibrage de noyaux combinée haute et basse vitesse' ) ),
	array( 'en' => 'High-Speed Core Balancing Machine', 'fr' => 'machine d’équilibrage de cartouches haute vitesse', 'not' => array( 'machine d’équilibrage de noyaux haute vitesse' ) ),
	array( 'en' => 'Low-Speed Core Balancing Machine', 'fr' => 'machine d’équilibrage de cartouches basse vitesse', 'not' => array( 'machine d’équilibrage de noyaux basse vitesse' ) ),
	array( 'en' => 'turbocharger', 'fr' => 'turbocompresseur', 'not' => array( 'turbo-chargeur', 'suralimenteur' ) ),
	array( 'en' => 'turbocharger flow bench', 'fr' => 'banc de mesure de débit pour turbocompresseurs', 'not' => array( 'banc d’essai de turbocompresseurs', 'banc de flux turbocompresseur', 'banc d’écoulement de turbo' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'fr' => 'banc de mesure de débit dynamique pour turbocompresseurs', 'not' => array( 'banc de flux turbocompresseur dynamique', 'banc d’essai dynamique de turbocompresseur' ) ),
	array( 'en' => 'turbocharger frame size', 'fr' => 'taille de carter de turbocompresseur', 'not' => array( 'taille de cadre de turbo', 'dimension du châssis de turbo' ) ),
	array( 'en' => 'turbo calibration', 'fr' => 'étalonnage de turbocompresseur', 'not' => array( 'calibrage turbo', 'calibration de turbo' ) ),
	array( 'en' => 'whistle', 'fr' => 'sifflement', 'not' => array( 'coup de sifflet' ) ),
	array( 'en' => 'boreless compressor wheel', 'fr' => 'roue de compresseur sans alésage', 'not' => array( 'roue de compresseur sans trou' ) ),
	array( 'en' => 'oil drain', 'fr' => 'orifice de vidange d’huile', 'not' => array( 'évent', 'orifice de mise à l’air', 'purge d’air', 'drain de pétrole' ) ),
	array( 'en' => 'transmission', 'fr' => 'transmission', 'not' => array(  ) ),
	array( 'en' => 'gearbox', 'fr' => 'boîte de vitesses', 'not' => array( 'boîte d’engrenages', 'engrenage', 'transmission de diffusion' ) ),
	array( 'en' => 'propulsion & powertrain', 'fr' => 'propulsion et groupe motopropulseur', 'not' => array( 'propulsion et chaîne cinématique', 'propulsion et transmission' ) ),
	array( 'en' => 'Powertrain', 'fr' => 'groupe motopropulseur', 'not' => array( 'chaîne cinématique', 'train de puissance', 'chaîne de traction' ) ),
	array( 'en' => 'crankshaft', 'fr' => 'vilebrequin', 'not' => array( 'arbre à came', 'manivelle' ) ),
	array( 'en' => 'crankshaft lathe', 'fr' => 'tour à vilebrequins', 'not' => array( 'tournage de vilebrequin', 'tour de manivelle' ) ),
	array( 'en' => 'inline crankshaft', 'fr' => 'vilebrequin en ligne', 'not' => array( 'vilebrequin à quatre temps', 'vilebrequin aligné' ) ),
	array( 'en' => 'single cylinder crankshaft', 'fr' => 'vilebrequin monocylindre', 'not' => array( 'vilebrequin à voie unique', 'vilebrequin monotrace' ) ),
	array( 'en' => 'flywheel', 'fr' => 'volant moteur', 'not' => array( 'roue volante', 'volant d’inertie', 'roue libre' ) ),
	array( 'en' => 'dual mass flywheel', 'fr' => 'volant moteur bimasse', 'not' => array( 'volant d’inertie à double masse', 'volant à double masse', 'roue d’inertie bimasse' ) ),
	array( 'en' => 'flexplate', 'fr' => 'plateau d’entraînement', 'not' => array( 'volant bimasse' ) ),
	array( 'en' => 'driveshaft', 'fr' => 'arbre de transmission', 'not' => array( 'arbre moteur', 'arbre d’entraînement de roue' ) ),
	array( 'en' => 'pinion gear', 'fr' => 'pignon d’attaque', 'not' => array( 'engrenage à pignon', 'tourillon', 'roue dentée pignon' ) ),
	array( 'en' => 'ring gears', 'fr' => 'couronnes dentées', 'not' => array( 'engrenages annulaires', 'roues à anneau', 'couronnes d’engrenage' ) ),
	array( 'en' => 'third member', 'fr' => 'pont central', 'not' => array( 'troisième membre', 'tierce partie', 'troisième élément' ) ),
	array( 'en' => 'half case', 'fr' => 'demi-carter', 'not' => array( 'demi-boîtier', 'demi-caisse' ) ),
	array( 'en' => 'valve body unit', 'fr' => 'bloc hydraulique', 'not' => array( 'unité de corps de soupape', 'bloc de vannes de boîte' ) ),
	array( 'en' => 'front strut', 'fr' => 'jambe de suspension avant', 'not' => array( 'montant avant', 'entretoise avant', 'étrier avant', 'poteau avant' ) ),
	array( 'en' => 'e-axle', 'fr' => 'e-axle', 'not' => array( 'axe électrique', 'essieu électronique', 'e-essieu' ) ),
	array( 'en' => 'traction battery', 'fr' => 'batterie de traction', 'not' => array( 'pile de traction', 'accumulateur jetable' ) ),
	array( 'en' => 'control module', 'fr' => 'calculateur', 'not' => array( 'module de contrôle', 'module de vérification' ) ),
	array( 'en' => 'blank ECM', 'fr' => 'ECM vierge', 'not' => array( 'ECM blanc', 'ECM vide', 'calculateur blanc' ) ),
	array( 'en' => 'restbus simulation', 'fr' => 'simulation de bus résiduel', 'not' => array( 'simulation de reste de bus', 'simulation du bus restant' ) ),
	array( 'en' => 'instrument cluster', 'fr' => 'combiné d’instruments', 'not' => array( 'groupe d’instruments', 'grappe d’instruments' ) ),
	array( 'en' => 'drivability', 'fr' => 'agrément de conduite', 'not' => array( 'conduisibilité', 'pilotabilité', 'conductibilité' ) ),
	array( 'en' => 'gear shift calibration', 'fr' => 'étalonnage du passage des rapports', 'not' => array( 'calibration de changement de vitesse', 'étalonnage de changement d’engrenage' ) ),
	array( 'en' => 'torque vectoring', 'fr' => 'vectorisation du couple', 'not' => array( 'répartition vectorielle', 'vecteur de couple' ) ),
	array( 'en' => 'two-wheel drive', 'fr' => 'deux roues motrices', 'not' => array( 'traction à deux roues', 'entraînement à deux roues', 'conduite à deux roues' ) ),
	array( 'en' => 'wheel aligner', 'fr' => 'banc de géométrie', 'not' => array( 'aligneur de roues', 'machine d’alignement de roues' ) ),
	array( 'en' => 'wheel alignment', 'fr' => 'géométrie des trains roulants', 'not' => array( 'alignement de roue', 'alignement des roues avant' ) ),
	array( 'en' => 'roller brake tester', 'fr' => 'banc de freinage à rouleaux', 'not' => array( 'testeur de frein à rouleaux', 'banc d’essai de freins à cylindres' ) ),
	array( 'en' => 'roller', 'fr' => 'rouleau', 'not' => array( 'cylindre de frein', 'galet de frein' ) ),
	array( 'en' => 'retaining rollers', 'fr' => 'galets de retenue', 'not' => array( 'rouleaux de rétention', 'rouleaux de maintien' ) ),
	array( 'en' => 'chassis dynamometer', 'fr' => 'banc dynamométrique à rouleaux', 'not' => array( 'dynamomètre de châssis', 'banc dynamométrique d’essieux' ) ),
	array( 'en' => 'dynamometer', 'fr' => 'banc dynamométrique', 'not' => array( 'dynamomètre', 'dynamo', 'banc de puissance' ) ),
	array( 'en' => 'inline dyno', 'fr' => 'banc dynamométrique en ligne', 'not' => array( 'dyno en ligne', 'dynamomètre aligné' ) ),
	array( 'en' => 'squeak & rattle testing', 'fr' => 'essais de grincements et de craquements', 'not' => array( 'essais de couinement et de hochet', 'test de grincement et de cliquetis' ) ),
	array( 'en' => 'end of line testing', 'fr' => 'essais de fin de ligne', 'not' => array( 'tests de bout de ligne', 'essais en fin de chaîne' ) ),
	array( 'en' => 'Vehicles End-of-Line', 'fr' => 'Fin de ligne pour véhicules', 'not' => array( 'Fin de ligne véhicules', 'Véhicules fin de ligne' ) ),
	array( 'en' => 'ADAS', 'fr' => 'ADAS', 'not' => array( 'SAAC', 'systèmes de support au conducteur' ) ),
	array( 'en' => 'advanced driver assistance systems', 'fr' => 'systèmes avancés d’aide à la conduite', 'not' => array( 'systèmes avancés d’assistance au conducteur', 'systèmes de support avancé au conducteur' ) ),
	array( 'en' => 'ADAS alignment', 'fr' => 'étalonnage ADAS', 'not' => array( 'alignement ADAS', 'ajustement ADAS' ) ),
	array( 'en' => 'calibration target', 'fr' => 'mire d’étalonnage', 'not' => array( 'cible de calibration', 'objectif d’étalonnage' ) ),
	array( 'en' => 'probe alignment', 'fr' => 'alignement du palpeur', 'not' => array(  ) ),
	array( 'en' => 'misalignment', 'fr' => 'désalignement', 'not' => array( 'mauvais alignement', 'désalignage' ) ),
	array( 'en' => 'energy recuperation', 'fr' => 'récupération d’énergie', 'not' => array( 'récupération énergétique de freinage' ) ),
	array( 'en' => 'tire inflator', 'fr' => 'gonfleur de pneus', 'not' => array( 'inflateur de pneu', 'gonfleur pneumatique' ) ),
	array( 'en' => 'commercial vehicle', 'fr' => 'véhicule utilitaire', 'not' => array( 'véhicule commercial', 'voiture commerciale' ) ),
	array( 'en' => 'heavy-duty', 'fr' => 'pour service intensif', 'not' => array( 'service lourd', 'devoir lourd', 'à haute résistance' ) ),
	array( 'en' => 'failure rates', 'fr' => 'taux de défaillance', 'not' => array( 'taux d’échec', 'taux de faillite' ) ),
	array( 'en' => 'refrigerant', 'fr' => 'fluide frigorigène', 'not' => array( 'réfrigérant', 'liquide de refroidissement', 'fluide réfrigérant', 'agent réfrigérant' ) ),
	array( 'en' => 'refrigerant charging', 'fr' => 'charge en fluide frigorigène', 'not' => array( 'charge de réfrigérant', 'remplissage de réfrigérant', 'chargement de réfrigérant', 'recharge de réfrigérant' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'fr' => 'Brochure de charge en fluide frigorigène', 'not' => array( 'Brochure de charge de fluide frigorigène', 'Brochure de charge de réfrigérant' ) ),
	array( 'en' => 'Refrigerant Charging Machine Accessories', 'fr' => 'accessoires de machine de charge en fluide frigorigène', 'not' => array( 'accessoires de machine de charge de réfrigérant' ) ),
	array( 'en' => 'Refrigerant Fluid & Gas Charging Machines', 'fr' => 'machines de charge en fluide frigorigène et en gaz', 'not' => array( 'machines de charge de fluide réfrigérant et de gaz' ) ),
	array( 'en' => 'refrigeration', 'fr' => 'réfrigération', 'not' => array( 'refroidissement', 'climatisation' ) ),
	array( 'en' => 'Leak Detection & Refrigeration', 'fr' => 'Détection de fuites et réfrigération', 'not' => array( 'Détection de fuites et fluide frigorigène' ) ),
	array( 'en' => 'Atmosphere – Refrigerants', 'fr' => 'Atmosphère – Fluides frigorigènes', 'not' => array( 'Atmosphère – Réfrigérants' ) ),
	array( 'en' => 'leak detection', 'fr' => 'détection de fuites', 'not' => array( 'détection d’étanchéité', 'détection de fuite d’air', 'dépistage de fuites' ) ),
	array( 'en' => 'gross leak test', 'fr' => 'essai de fuite grossière', 'not' => array( 'test de fuite brute', 'essai de grosse fuite', 'essai de fuite bruto' ) ),
	array( 'en' => 'fine leak', 'fr' => 'fuite fine', 'not' => array( 'petite fuite', 'fuite amende', 'micro-fuite légère' ) ),
	array( 'en' => 'sniffer', 'fr' => 'sonde renifleuse', 'not' => array( 'pinces renifleuses', 'renifleur à pince', 'pince à renifler' ) ),
	array( 'en' => 'tracer gas', 'fr' => 'gaz traceur', 'not' => array( 'gaz de traçage', 'gaz de suivi' ) ),
	array( 'en' => 'vacuum', 'fr' => 'vide', 'not' => array( 'aspirateur', 'dépression atmosphérique' ) ),
	array( 'en' => 'vacuum evacuation', 'fr' => 'tirage au vide', 'not' => array( 'évacuation sous vide', 'évacuation du vide', 'vidange du vide' ) ),
	array( 'en' => 'Evacuation', 'fr' => 'Tirage au vide', 'not' => array( 'Évacuation', 'Vidange' ) ),
	array( 'en' => 'vacuum rise test', 'fr' => 'essai de remontée de vide', 'not' => array( 'test de montée sous vide', 'essai de hausse de vide' ) ),
	array( 'en' => 'pressurization', 'fr' => 'mise sous pression', 'not' => array( 'pressurisation', 'pressurisation à l’azote' ) ),
	array( 'en' => 'sealed assembly', 'fr' => 'ensemble étanche', 'not' => array( 'assemblage scellé', 'montage cacheté' ) ),
	array( 'en' => 'filler', 'fr' => 'remplisseuse', 'not' => array( 'bouche-trou', 'mastic' ) ),
	array( 'en' => 'filler gun', 'fr' => 'pistolet de remplissage', 'not' => array( 'pistolet obturateur', 'pistolet de mastic' ) ),
	array( 'en' => 'final discharge', 'fr' => 'décharge finale', 'not' => array( 'dernier renvoi' ) ),
	array( 'en' => 'flammable gases', 'fr' => 'gaz inflammables', 'not' => array( 'gaz flammables', 'gaz enflammables' ) ),
	array( 'en' => 'cooling units', 'fr' => 'groupes de refroidissement', 'not' => array( 'unités de refroidissement', 'unités frigorifiques' ) ),
	array( 'en' => 'soak time', 'fr' => 'temps de stabilisation', 'not' => array( 'temps de trempage', 'durée d’imprégnation' ) ),
	array( 'en' => 'hazardous area', 'fr' => 'zone à atmosphère explosible', 'not' => array( 'zone hasardeuse', 'zone risquée', 'secteur dangereux' ) ),
	array( 'en' => 'LPM', 'fr' => 'l/min', 'not' => array( 'litres par minutes' ) ),
	array( 'en' => 'water-cooled', 'fr' => 'refroidi par eau', 'not' => array( 'refroidissant à l’eau', 'à refroidissement d’eau' ) ),
	array( 'en' => 'air cycle machines', 'fr' => 'machines à cycle d’air', 'not' => array( 'machines à cycle aérien', 'machines de cycle atmosphérique' ) ),
	array( 'en' => 'mill roll', 'fr' => 'cylindre de laminoir', 'not' => array( 'rouleau de moulin', 'rouleau de laminoir', 'rouleau d’usine' ) ),
	array( 'en' => 'forged rolls', 'fr' => 'cylindres forgés', 'not' => array( 'rouleaux forgés', 'cylindres de forge' ) ),
	array( 'en' => 'roll inspection', 'fr' => 'contrôle des cylindres', 'not' => array( 'inspection de cylindres', 'contrôle des rouleaux', 'inspection des rouleaux' ) ),
	array( 'en' => 'Roll Shop Technologies', 'fr' => 'Technologies d’atelier de cylindres', 'not' => array( 'Technologies de magasin de rouleaux', 'Technologies de rouleaux' ) ),
	array( 'en' => 'Roll Grinding Machines', 'fr' => 'rectifieuses de cylindres', 'not' => array( 'broyeurs de rouleaux', 'meuleuses de cylindres', 'machines à moudre les rouleaux' ) ),
	array( 'en' => 'reconditioning', 'fr' => 'reconditionnement', 'not' => array( 'recyclage', 'remise à neuf de surface' ) ),
	array( 'en' => '20-high / six-high mill', 'fr' => 'laminoir à vingt cylindres / laminoir sexto', 'not' => array( '20-haut', 'six-haut', 'laminoir à 20 hauteurs' ) ),
	array( 'en' => 'cold pilger mill', 'fr' => 'laminoir à pas de pèlerin à froid', 'not' => array( 'laminoir à pilage à froid', 'laminoir pilger froid', 'broyeur pilger' ) ),
	array( 'en' => 'blast furnace', 'fr' => 'haut fourneau', 'not' => array( 'four à explosion', 'fourneau de soufflage', 'four de souffle' ) ),
	array( 'en' => 'tap hole', 'fr' => 'trou de coulée', 'not' => array( 'trou de robinet', 'orifice de prise', 'trou de tapotement' ) ),
	array( 'en' => 'clay gun', 'fr' => 'boucheuse à argile', 'not' => array( 'canon d’argile', 'pistolet à argile', 'machine à canon d’argile' ) ),
	array( 'en' => 'strip', 'fr' => 'bande', 'not' => array( 'décapage', 'lanière' ) ),
	array( 'en' => 'Strip Lines', 'fr' => 'Lignes de traitement de bande', 'not' => array( 'Lignes de décapage', 'Lignes de bandelettes', 'Lignes de dépouillement' ) ),
	array( 'en' => 'tin plating', 'fr' => 'étamage', 'not' => array( 'galvanisation', 'zingage', 'placage d’étain' ) ),
	array( 'en' => 'electrical discharge texturing', 'fr' => 'texturation par électroérosion', 'not' => array( 'technologie de décharge électrique', 'texturation par décharge électrique' ) ),
	array( 'en' => 'spalls', 'fr' => 'écaillages', 'not' => array( 'écaillures', 'effritements', 'éclatements de surface' ) ),
	array( 'en' => 'surface separations', 'fr' => 'décohésions de surface', 'not' => array( 'séparations de surface', 'divisions superficielles' ) ),
	array( 'en' => 'pinches & bruises', 'fr' => 'pincements et matages', 'not' => array( 'pincements et contusions', 'pinces et bleus', 'pincements et ecchymoses' ) ),
	array( 'en' => 'eddy current technology', 'fr' => 'technologie à courants de Foucault', 'not' => array( 'technologie de courant actuel', 'technologie actuelle', 'courant de tourbillon' ) ),
	array( 'en' => 'non-destructive testing', 'fr' => 'contrôle non destructif', 'not' => array( 'test non destructif', 'essai non-destructeur' ) ),
	array( 'en' => 'walking beam system', 'fr' => 'système à poutre marchante', 'not' => array( 'système de poutre ambulante', 'système de faisceau marcheur' ) ),
	array( 'en' => 'Handling Machines & Manipulators', 'fr' => 'machines de manutention et manipulateurs', 'not' => array( 'machines de gestion et manipulateurs' ) ),
	array( 'en' => 'Vibration Absorbing Cast', 'fr' => 'fonte amortissant les vibrations', 'not' => array( 'coulée absorbant les vibrations' ) ),
	array( 'en' => 'Test Bay Erection and Modernization', 'fr' => 'montage et modernisation de bancs d’essai', 'not' => array( 'érection et modernisation de bancs d’essai', 'construction et modernisation de baies d’essai' ) ),
	array( 'en' => 'machine tools', 'fr' => 'machines-outils', 'not' => array( 'outils de machine', 'machines technologiques', 'outils machines' ) ),
	array( 'en' => 'Machine Tools and Special Machines', 'fr' => 'machines-outils et machines spéciales', 'not' => array( 'outils de machine et machines spéciales' ) ),
	array( 'en' => 'boring', 'fr' => 'alésage', 'not' => array( 'perçage', 'forage', 'ennui' ) ),
	array( 'en' => 'horizontal boring machine', 'fr' => 'aléseuse horizontale', 'not' => array( 'machine de perçage horizontal', 'perceuse horizontale', 'machine à aléser horizontale' ) ),
	array( 'en' => 'deep hole drilling', 'fr' => 'perçage profond', 'not' => array( 'forage de trou profond', 'perçage de trous profonds à canon' ) ),
	array( 'en' => 'gundrill', 'fr' => 'foret canon', 'not' => array( 'perceuse à canon', 'forage au pistolet', 'mèche à fusil' ) ),
	array( 'en' => 'boring drill', 'fr' => 'foreuse', 'not' => array( 'perceuse ennuyeuse', 'foreuse ennuyante' ) ),
	array( 'en' => 'mudding system', 'fr' => 'système d’injection de boue', 'not' => array( 'système de boue', 'système de bouillie' ) ),
	array( 'en' => 'grinding wheel', 'fr' => 'meule', 'not' => array( 'roue de meulage', 'roue abrasive', 'disque de rectification' ) ),
	array( 'en' => 'rotary diamond dressing', 'fr' => 'dressage par molette diamantée', 'not' => array( 'habillage au diamant rotatif', 'parage diamant rotatif' ) ),
	array( 'en' => 'infeed', 'fr' => 'avance de plongée', 'not' => array( 'alimentation', 'entrée de matière' ) ),
	array( 'en' => 'superabrasives', 'fr' => 'superabrasifs', 'not' => array( 'super-abrasives', 'abrasifs supérieurs' ) ),
	array( 'en' => 'grinder', 'fr' => 'rectifieuse', 'not' => array( 'meuleuse', 'broyeur', 'moulin' ) ),
	array( 'en' => 'Automatic Grinder Control', 'fr' => 'commande automatique de rectifieuse', 'not' => array( 'contrôle automatique de rectification', 'contrôle automatique de meuleuse', 'commande automatique de meuleuse' ) ),
	array( 'en' => 'Profile Grinder Control', 'fr' => 'commande de rectifieuse de profil', 'not' => array( 'contrôle de rectifieuse de profil' ) ),
	array( 'en' => '3-jaw chuck', 'fr' => 'mandrin à trois mors', 'not' => array( 'mandrin à 3 mâchoires', 'pince à trois mors' ) ),
	array( 'en' => 'collet chuck', 'fr' => 'mandrin à pince', 'not' => array( 'mandrin à collet', 'mandrin à collier' ) ),
	array( 'en' => 'in a single clamping', 'fr' => 'en une seule prise de pièce', 'not' => array( 'en un seul serrage', 'en une seule pince', 'dans un seul étau' ) ),
	array( 'en' => 'motorized clamping', 'fr' => 'bridage motorisé', 'not' => array( 'pinçage motorisé', 'agrafage motorisé' ) ),
	array( 'en' => 'custom fixturing', 'fr' => 'outillage sur mesure', 'not' => array( 'fixation personnalisée', 'montage personnalisé' ) ),
	array( 'en' => 'machining cell', 'fr' => 'îlot d’usinage', 'not' => array( 'cellule de machine', 'case d’usinage' ) ),
	array( 'en' => 'machinist', 'fr' => 'usineur', 'not' => array( 'machiniste', 'mécanicien de machine' ) ),
	array( 'en' => 'chip vacuum', 'fr' => 'aspiration des copeaux', 'not' => array( 'vide de copeaux', 'aspirateur à puces' ) ),
	array( 'en' => 'turret-style wheel head', 'fr' => 'poupée porte-meule à tourelle', 'not' => array( 'tête de roue à tourelle', 'tête de roue tourelle' ) ),
	array( 'en' => 'gantry', 'fr' => 'portique', 'not' => array( 'potence', 'grue à portique' ) ),
	array( 'en' => 'gantry milling', 'fr' => 'fraisage sur portique', 'not' => array( 'fraisage à portail', 'fraisage de portique' ) ),
	array( 'en' => 'dial indicator', 'fr' => 'comparateur à cadran', 'not' => array( 'indicateur à cadran', 'jauge à cadran' ) ),
	array( 'en' => 'active part probing', 'fr' => 'palpage actif de la pièce', 'not' => array( 'sondage actif', 'sonde de pièce active' ) ),
	array( 'en' => 'aperture plate', 'fr' => 'plaque perforée', 'not' => array(  ) ),
	array( 'en' => 'bore axis alignment', 'fr' => 'alignement de l’axe d’alésage', 'not' => array(  ) ),
	array( 'en' => 'anchoring', 'fr' => 'ancrage', 'not' => array( 'amarrage', 'arrimage', 'mouillage' ) ),
	array( 'en' => 'footprint', 'fr' => 'encombrement au sol', 'not' => array( 'empreinte', 'empreinte au sol', 'trace au sol' ) ),
	array( 'en' => 'stand-alone machine', 'fr' => 'machine autonome', 'not' => array( 'machine seule', 'machine debout seule' ) ),
	array( 'en' => 'ultra-stable design', 'fr' => 'conception ultra-stable', 'not' => array(  ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'fr' => 'nettoyeur de buses à ultrasons', 'not' => array( 'nettoyeur ultrasonique de buse' ) ),
	array( 'en' => 'Ultrasonic Welding Systems', 'fr' => 'systèmes de soudage par ultrasons', 'not' => array( 'systèmes de soudure ultrasonique' ) ),
	array( 'en' => 'brushing & polishing machines', 'fr' => 'machines de brossage et de polissage', 'not' => array( 'machines à brosser et à cirer' ) ),
	array( 'en' => 'keg', 'fr' => 'fût', 'not' => array( 'tonnelet', 'baril', 'fût de bière en métal' ) ),
	array( 'en' => 'keg finger holes', 'fr' => 'trous de préhension de fût', 'not' => array( 'trous de doigt', 'orifices digitaux' ) ),
	array( 'en' => 'debonding', 'fr' => 'décollement', 'not' => array( 'dé-collage', 'déliaison', 'décollage adhésif' ) ),
	array( 'en' => 'fluid power', 'fr' => 'hydraulique et pneumatique', 'not' => array( 'puissance fluide', 'puissance des fluides', 'énergie fluide', 'Puissance fluide', 'Puissance des fluides' ) ),
	array( 'en' => 'Linear Motion', 'fr' => 'Mouvement linéaire', 'not' => array( 'Linear Motion', 'Motion linéaire' ) ),
	array( 'en' => 'Rotary Motion', 'fr' => 'Mouvement rotatif', 'not' => array( 'Motion rotative', 'Mouvement tournant' ) ),
	array( 'en' => 'hydraulic pilot', 'fr' => 'pilote hydraulique', 'not' => array( 'conducteur hydraulique', 'pilotage hydrolique' ) ),
	array( 'en' => 'load sense signal', 'fr' => 'signal de détection de charge', 'not' => array( 'signal de sens de charge', 'signal du sens de la charge' ) ),
	array( 'en' => 'drift', 'fr' => 'dérive', 'not' => array( 'déviation involontaire', 'glissement de vérin' ) ),
	array( 'en' => 'cushion testing', 'fr' => 'essai des coussins', 'not' => array(  ) ),
	array( 'en' => 'snubber', 'fr' => 'amortisseur', 'not' => array( 'étrangleur', 'amortisseur de choc électrique' ) ),
	array( 'en' => 'thrust force / pullback force', 'fr' => 'force de poussée / force de traction', 'not' => array( 'force de recul', 'force de retrait arrière' ) ),
	array( 'en' => 'push and pull', 'fr' => 'poussée et traction', 'not' => array( 'pousser et tirer', 'poussée et tirage' ) ),
	array( 'en' => 'tapered roller bearing', 'fr' => 'roulement à rouleaux coniques', 'not' => array( 'roulement conique à galets', 'palier conique à rouleaux' ) ),
	array( 'en' => 'rolling torque', 'fr' => 'couple de roulement', 'not' => array( 'couple de laminage', 'couple roulant' ) ),
	array( 'en' => 'infinitely variable', 'fr' => 'à variation continue', 'not' => array( 'infiniment variable', 'indéfiniment variable' ) ),
	array( 'en' => 'tension', 'fr' => 'tension', 'not' => array( 'traction mécanique' ) ),
	array( 'en' => 'load capacity', 'fr' => 'capacité de charge', 'not' => array(  ) ),
	array( 'en' => 'weight capacity', 'fr' => 'capacité en poids', 'not' => array(  ) ),
	array( 'en' => 'movable cradle', 'fr' => 'berceau mobile', 'not' => array( 'support mobile', 'berceau amovible' ) ),
	array( 'en' => 'lubrication', 'fr' => 'lubrification', 'not' => array(  ) ),
	array( 'en' => 'lube & scavenge pumps', 'fr' => 'pompes de lubrification et de récupération d’huile', 'not' => array( 'pompes de lubrification et de ventilation', 'pompes de graissage et de balayage' ) ),
	array( 'en' => 'blade timing', 'fr' => 'calage des pales', 'not' => array( 'synchronisation de lame', 'minutage des pales' ) ),
	array( 'en' => 'motor grader', 'fr' => 'niveleuse', 'not' => array( 'grader à moteur', 'décapeuse', 'niveleuse à moteur' ) ),
	array( 'en' => 'Motor Graders', 'fr' => 'Niveleuses', 'not' => array( 'Motor Graders', 'Graders', 'Décapeuses' ) ),
	array( 'en' => 'sprayers', 'fr' => 'pulvérisateurs', 'not' => array( 'Sprayers', 'vaporisateurs', 'atomiseurs', 'arroseurs' ) ),
	array( 'en' => 'backhoe', 'fr' => 'tractopelle', 'not' => array( 'pelle arrière', 'excavatrice arrière', 'rétro-pelle' ) ),
	array( 'en' => 'excavator', 'fr' => 'pelle hydraulique', 'not' => array( 'creuseuse', 'excavateur', 'pelleteuse à godet' ) ),
	array( 'en' => 'baler', 'fr' => 'presse à balles', 'not' => array( 'emballeuse', 'conditionneuse', 'ballonneuse' ) ),
	array( 'en' => 'combine', 'fr' => 'moissonneuse-batteuse', 'not' => array( 'combiné', 'combine', 'moissonneuse seule' ) ),
	array( 'en' => 'draper header', 'fr' => 'barre de coupe à tapis', 'not' => array( 'tête de drapier', 'en-tête de draper', 'rideau de coupe' ) ),
	array( 'en' => 'hay mower', 'fr' => 'faucheuse', 'not' => array( 'tondeuse à foin', 'coupe-foin', 'tondeuse de foin' ) ),
	array( 'en' => 'implements', 'fr' => 'outils portés', 'not' => array( 'implémentations', 'mises en œuvre', 'ustensiles' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'fr' => 'Outils portés – fin de ligne', 'not' => array( 'Outils – Fin de ligne', 'Implémentations – fin de ligne' ) ),
	array( 'en' => 'PTO', 'fr' => 'prise de force', 'not' => array( 'sortie de puissance', 'prise de courant', 'arbre PTO' ) ),
	array( 'en' => 'blade', 'fr' => 'lame', 'not' => array( 'pale', 'couteau de coupe' ) ),
	array( 'en' => 'off-highway', 'fr' => 'engins hors route', 'not' => array( 'hors autoroute', 'tout-terrain routier' ) ),
	array( 'en' => 'cargo loading systems', 'fr' => 'systèmes de chargement de fret', 'not' => array( 'systèmes de chargement de cargaison' ) ),
	array( 'en' => 'exhaust extraction', 'fr' => 'extraction des gaz d’échappement', 'not' => array( 'extraction d’échappement', 'aspiration d’épuisement' ) ),
	array( 'en' => 'Aerospace & industrials', 'fr' => 'Aérospatial et secteurs industriels', 'not' => array( 'Aéronautique et secteurs industriels', 'Aérospatiale et industries', 'Aéronautique et industriel' ) ),
	array( 'en' => 'rotor wing aircraft', 'fr' => 'aéronefs à voilure tournante', 'not' => array( 'avions à hélices', 'aéronefs à ailes rotatives', 'avions rotatifs' ) ),
	array( 'en' => 'HMU/FMU', 'fr' => 'HMU/FMU', 'not' => array( 'unités hydrauliques/pneumatiques', 'UHM/UFM' ) ),
	array( 'en' => 'engine software loaders', 'fr' => 'chargeurs de logiciel moteur', 'not' => array( 'programmes de chargement de moteurs', 'chargeurs de moteurs' ) ),
	array( 'en' => 'landing gear systems', 'fr' => 'systèmes de train d’atterrissage', 'not' => array( 'systèmes d’engrenage d’atterrissage', 'systèmes de roulement d’atterrissage' ) ),
	array( 'en' => 'power drive units', 'fr' => 'unités d’entraînement', 'not' => array( 'unités de conduite de puissance' ) ),
	array( 'en' => 'actuation systems', 'fr' => 'systèmes d’actionnement', 'not' => array( 'systèmes d’actuation', 'systèmes d’activation' ) ),
	array( 'en' => 'armature', 'fr' => 'induit', 'not' => array( 'armature', 'ancre', 'charpente' ) ),
	array( 'en' => 'bead breaking', 'fr' => 'décollement du talon', 'not' => array( 'bris de perle', 'rupture de perle', 'cassage de bourrelet' ) ),
	array( 'en' => 'EMC darkroom', 'fr' => 'chambre anéchoïque CEM', 'not' => array( 'chambre noire CEM', 'salle sombre CEM' ) ),
	array( 'en' => 'special test facilities', 'fr' => 'moyens d’essai spéciaux', 'not' => array( 'installations spéciales de test' ) ),
	array( 'en' => 'fully loaded test', 'fr' => 'essai en pleine charge', 'not' => array( 'test entièrement chargé', 'essai complètement chargé' ) ),
	array( 'en' => 'traceable tests', 'fr' => 'essais traçables', 'not' => array( 'tests traçables', 'essais retraçables' ) ),
	array( 'en' => 'adaptive speed control', 'fr' => 'régulation adaptative de la vitesse', 'not' => array( 'contrôle adaptatif de vitesse' ) ),
	array( 'en' => 'idle duration', 'fr' => 'durée de ralenti', 'not' => array( 'durée d’inactivité', 'temps oisif' ) ),
	array( 'en' => 'higher-level control system', 'fr' => 'système de conduite de niveau supérieur', 'not' => array( 'système de contrôle de niveau supérieur' ) ),
	array( 'en' => 'process recipe', 'fr' => 'recette de procédé', 'not' => array( 'recette de processus', 'ordonnance de procédé' ) ),
	array( 'en' => 'single bay', 'fr' => 'travée unique', 'not' => array( 'baie unique', 'compartiment unique' ) ),
	array( 'en' => 'fixed stations', 'fr' => 'postes fixes', 'not' => array( 'stations fixes', 'gares fixes' ) ),
	array( 'en' => 'mobile carousels', 'fr' => 'carrousels mobiles', 'not' => array(  ) ),
	array( 'en' => 'setup cycles', 'fr' => 'cycles de réglage', 'not' => array( 'cycles d’installation' ) ),
	array( 'en' => 'automated handling cells', 'fr' => 'cellules de manutention automatisées', 'not' => array( 'cellules de gestion automatisées' ) ),
	array( 'en' => 'water meter', 'fr' => 'compteur d’eau', 'not' => array( 'compteur à eau', 'débitmètre d’eau' ) ),
	array( 'en' => 'Detection Focus', 'fr' => 'Cible de détection', 'not' => array(  ) ),
	array( 'en' => 'stem stickiness', 'fr' => 'collage de tige', 'not' => array( 'viscosité de tige', 'adhérence collante du tronc' ) ),
	array( 'en' => 'Ascential', 'fr' => 'Ascential', 'not' => array( 'Ascensionnel', 'Ascentiel' ) ),
	array( 'en' => 'Ascential Technologies', 'fr' => 'Ascential Technologies', 'not' => array( 'Technologies Ascential', 'Ascential Technologie' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'fr' => 'Ascential Test & Measurement', 'not' => array( 'Ascential essais et mesures', 'Essais et mesures Ascential', 'Ascential Systèmes de mesure' ) ),
	array( 'en' => 'Ascential Care', 'fr' => 'Ascential Care', 'not' => array( 'Soins Ascential', 'Ascential Soin', 'Assistance Ascential' ) ),
	array( 'en' => 'Ascentialytics', 'fr' => 'Ascentialytics', 'not' => array( 'Analytique Ascential', 'Ascentialytique' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'fr' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MÉDICAL ET SCIENCES DE LA VIE' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'fr' => 'ADVANCING THE MACHINE', 'not' => array( 'FAIRE AVANCER LA MACHINE', 'LA MACHINE EN AVANT', 'PROGRESSER LA MACHINE' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'fr' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'SOLUTIONS DE COMMERCIALISATION TOTALE', 'SOLUTIONS TOTALES DE COMMERCIALISATION' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'fr' => 'A DESIGN / B LOGO', 'not' => array( 'UN DESSIN / LOGO B', 'CONCEPTION A / LOGO B' ) ),
	array( 'en' => 'Impossible? Done.', 'fr' => 'Impossible? Done.', 'not' => array( 'Impossible ? Fait.', 'Impossible ? Terminé.' ) ),
	array( 'en' => 'Calibration-as-a-Service™', 'fr' => 'Calibration-as-a-Service™', 'not' => array( 'Étalonnage en tant que service™', 'Calibrage en tant que service™' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'fr' => 'Burke E. Porter Machinery', 'not' => array( 'Machinerie Burke E. Porter', 'Burke Porter – Machines', 'Burke E. Porter Machines' ) ),
	array( 'en' => 'Burke Porter Group', 'fr' => 'Burke Porter Group', 'not' => array( 'Groupe Burke Porter', 'le groupe Burke Porter' ) ),
	array( 'en' => 'Burke Porter', 'fr' => 'Burke Porter', 'not' => array( 'Porter de Burke' ) ),
	array( 'en' => 'Universal Balancing', 'fr' => 'Universal Balancing', 'not' => array( 'Équilibrage universel', 'Équilibrage Universel', 'Balancement universel' ) ),
	array( 'en' => 'XL Machine', 'fr' => 'XL Machine', 'not' => array( 'Machine XL', 'machines XL', 'Machine extra-large' ) ),
	array( 'en' => 'WinterPark Engineering', 'fr' => 'WinterPark Engineering', 'not' => array( 'Ingénierie WinterPark', 'Parc d’hiver Engineering' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'fr' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht et Cie SARL', 'H. Kleinknecht & Co. SARL' ) ),
	array( 'en' => 'Kleinknecht', 'fr' => 'Kleinknecht', 'not' => array( 'Petit valet' ) ),
	array( 'en' => 'Cimat', 'fr' => 'Cimat', 'not' => array( 'Ciment' ) ),
	array( 'en' => 'Lismar', 'fr' => 'Lismar', 'not' => array(  ) ),
	array( 'en' => 'Titan', 'fr' => 'Titan', 'not' => array( 'Titane' ) ),
	array( 'en' => 'Galileo', 'fr' => 'Galileo', 'not' => array( 'Galilée' ) ),
	array( 'en' => 'Sentia', 'fr' => 'Sentia', 'not' => array(  ) ),
	array( 'en' => 'Bauer', 'fr' => 'Bauer', 'not' => array( 'Paysan' ) ),
	array( 'en' => 'CMT-TR Polimer', 'fr' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR Polymère', 'CMT-TR polymère', 'Polymère CMT-TR' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'fr' => 'Turbo Test Duo Expert', 'not' => array( 'Expert Turbo Test Duo', 'Expert TURBO TEST DUO' ) ),
	array( 'en' => 'First Alert Monitoring System', 'fr' => 'First Alert Monitoring System', 'not' => array( 'Système de surveillance Première Alerte', 'Système d’alerte précoce' ) ),
	array( 'en' => 'eRotor', 'fr' => 'eRotor', 'not' => array( 'Rotor électronique', 'e-Rotor', 'eRotateur' ) ),
	array( 'en' => 'Cerberus X1', 'fr' => 'Cerberus X1', 'not' => array( 'Cerbère X1' ) ),
	array( 'en' => 'ProbHe', 'fr' => 'ProbHe', 'not' => array( 'Sonde He', 'ProbHé' ) ),
	array( 'en' => 'Kairos', 'fr' => 'Kairos', 'not' => array( 'Caïros' ) ),
	array( 'en' => 'DATAMES', 'fr' => 'DATAMES', 'not' => array( 'Datames ultrason' ) ),
	array( 'en' => 'Marketplace', 'fr' => 'Place de marché', 'not' => array( 'Marché', 'Marketplace des pièces détachées', 'Place du marché' ) ),
	array( 'en' => 'Medical', 'fr' => 'Médical', 'not' => array(  ) ),
	array( 'en' => 'life sciences', 'fr' => 'sciences de la vie', 'not' => array( 'sciences vivantes', 'biosciences vitales' ) ),
	array( 'en' => 'President', 'fr' => 'président', 'not' => array( 'président de la République' ) ),
	array( 'en' => 'Board Member', 'fr' => 'administrateur', 'not' => array( 'membre du bureau', 'membre du panneau' ) ),
	array( 'en' => 'Principal', 'fr' => 'directeur', 'not' => array( 'principal d’école', 'proviseur' ) ),
	array( 'en' => 'Leadership', 'fr' => 'Direction', 'not' => array( 'Leadership', 'Dirigeance', 'Chefferie' ) ),
	array( 'en' => 'Corporate Roles', 'fr' => 'Fonctions support', 'not' => array( 'Rôles corporatifs', 'Rôles d’entreprise' ) ),
	array( 'en' => 'associate attorney', 'fr' => 'avocat collaborateur', 'not' => array( 'avocat associé', 'procureur associé' ) ),
	array( 'en' => 'field agents', 'fr' => 'techniciens itinérants', 'not' => array( 'agents de terrain', 'agents sur le terrain', 'agents champêtres' ) ),
	array( 'en' => 'service professional', 'fr' => 'professionnel du service', 'not' => array( 'professionnel de service à la clientèle' ) ),
	array( 'en' => 'peers', 'fr' => 'pairs', 'not' => array(  ) ),
	array( 'en' => 'high-performance teams', 'fr' => 'équipes performantes', 'not' => array( 'équipes à haute performance', 'équipes de haute performance' ) ),
	array( 'en' => 'like-minded companies', 'fr' => 'entreprises partageant la même vision', 'not' => array( 'entreprises aux idées similaires', 'sociétés de même esprit' ) ),
	array( 'en' => 'For Immediate Release', 'fr' => 'Pour diffusion immédiate', 'not' => array( 'Pour libération immédiate', 'Communiqué immédiat', 'Pour publication immédiate' ) ),
	array( 'en' => 'Introducing', 'fr' => 'Présentation de', 'not' => array( 'Introduire', 'Introduction de', 'En introduisant' ) ),
	array( 'en' => 'is now', 'fr' => 'devient', 'not' => array( 'est maintenant', 'est désormais devenu' ) ),
	array( 'en' => 'Featuring:', 'fr' => 'Signé :', 'not' => array( 'Vedette :', 'Mettant en vedette :', 'Équipé de :' ) ),
	array( 'en' => 'Powered by', 'fr' => 'Animé par', 'not' => array( 'Alimenté par', 'Soutenu par', 'Motorisé par' ) ),
	array( 'en' => 'Connect on LinkedIn', 'fr' => 'Entrer en relation sur LinkedIn', 'not' => array( 'Connectez-vous sur LinkedIn', 'Connexion sur LinkedIn', 'Se connecter à LinkedIn' ) ),
	array( 'en' => 'events & conferences', 'fr' => 'événements et conférences', 'not' => array(  ) ),
	array( 'en' => 'mental health care', 'fr' => 'soutien en santé mentale', 'not' => array( 'soins de santé à distance', 'santé mentale virtuelle', 'soins mentaux' ) ),
	array( 'en' => 'disability insurance', 'fr' => 'prévoyance invalidité', 'not' => array( 'assurance handicap', 'assurance d’incapacité' ) ),
	array( 'en' => 'right-shoring', 'fr' => 'rightshoring', 'not' => array( 'bon rivage', 'rive droite', 'relocalisation à droite' ) ),
	array( 'en' => 'tariffs', 'fr' => 'droits de douane', 'not' => array( 'tarifs', 'tarification douanière' ) ),
	array( 'en' => 'landed cost model', 'fr' => 'modèle de coût de revient rendu', 'not' => array( 'modèle de coût atterri', 'coût débarqué' ) ),
	array( 'en' => 'capital equipment', 'fr' => 'biens d’équipement', 'not' => array( 'équipement capital', 'matériel de capital' ) ),
	array( 'en' => 'discrete industries', 'fr' => 'industrie manufacturière discrète', 'not' => array( 'industries discrètes', 'secteurs discrets' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'fr' => 'remanufacturiers et reconstructeurs', 'not' => array( 'refabricants et rebâtisseurs' ) ),
	array( 'en' => 'remarketers', 'fr' => 'revendeurs spécialisés', 'not' => array( 'remarketeurs', 'remercialisateurs' ) ),
	array( 'en' => 'MRO', 'fr' => 'MRO', 'not' => array( 'maintenance réparation opérations' ) ),
	array( 'en' => 'obsolescence management', 'fr' => 'gestion de l’obsolescence', 'not' => array( 'gestion de la désuétude' ) ),
	array( 'en' => 'maintenance contracts', 'fr' => 'contrats de maintenance', 'not' => array( 'contrats d’entretien ménager' ) ),
	array( 'en' => 'warranty coverage', 'fr' => 'couverture de garantie', 'not' => array( 'assurance de garantie', 'assurance garantie' ) ),
	array( 'en' => 'Core / Plus / Elite', 'fr' => 'Core / Plus / Elite', 'not' => array( 'Noyau / Plus / Élite', 'Essentiel / Plus / Élite' ) ),
	array( 'en' => 'health checks', 'fr' => 'contrôles de l’état des machines', 'not' => array( 'bilans de santé', 'vérifications de santé', 'examens de santé' ) ),
	array( 'en' => 'site visit', 'fr' => 'intervention sur site', 'not' => array( 'visite de site', 'visite du chantier' ) ),
	array( 'en' => 'Labour & Travel', 'fr' => 'Main-d’œuvre et déplacements', 'not' => array( 'Travail et voyage', 'Labeur et voyages' ) ),
	array( 'en' => 'deployment', 'fr' => 'déploiement', 'not' => array(  ) ),
	array( 'en' => 'commissioning', 'fr' => 'mise en service', 'not' => array( 'commissionnement', 'mise en commission' ) ),
	array( 'en' => 'turnkey', 'fr' => 'clé en main', 'not' => array( 'tournant la clé', 'prêt à l’emploi' ) ),
	array( 'en' => 'uptime across systems', 'fr' => 'disponibilité de l’ensemble des systèmes', 'not' => array( 'temps de disponibilité des systèmes', 'temps de fonctionnement croisé' ) ),
	array( 'en' => 'high production', 'fr' => 'grande série', 'not' => array( 'haute production', 'production élevée' ) ),
	array( 'en' => 'high-mix, low-volume', 'fr' => 'petites séries multiréférences', 'not' => array( 'mélange élevé, faible volume', 'haut mélange faible volume' ) ),
	array( 'en' => 'volume flexibility', 'fr' => 'flexibilité des volumes', 'not' => array(  ) ),
	array( 'en' => 'Standardization at scale', 'fr' => 'Normalisation à grande échelle', 'not' => array( 'Standardisation à l’échelle', 'Standardisation à grande échelle' ) ),
	array( 'en' => 'factory floor', 'fr' => 'atelier de production', 'not' => array( 'plancher d’usine', 'sol d’usine', 'étage de l’usine' ) ),
	array( 'en' => 'operations', 'fr' => 'activités', 'not' => array( 'opérations commerciales', 'vos opérations', 'opérations de production' ) ),
	array( 'en' => 'applications', 'fr' => 'applications', 'not' => array(  ) ),
	array( 'en' => 'customer journey', 'fr' => 'parcours client', 'not' => array( 'voyage client', 'trajet du client' ) ),
	array( 'en' => 'insights', 'fr' => 'informations', 'not' => array( 'enseignements', 'aperçus', 'perspicacités' ) ),
	array( 'en' => 'actionable insights', 'fr' => 'informations exploitables', 'not' => array( 'enseignements exploitables', 'aperçus exploitables', 'idées actionnables' ) ),
	array( 'en' => 'expert insights', 'fr' => 'analyses d’experts', 'not' => array( 'enseignements d’experts', 'aperçus d’experts' ) ),
	array( 'en' => 'performance', 'fr' => 'performances', 'not' => array(  ) ),
	array( 'en' => 'validate performance', 'fr' => 'valider les performances', 'not' => array(  ) ),
	array( 'en' => 'defensible', 'fr' => 'défendable', 'not' => array( 'défensif', 'défensable' ) ),
	array( 'en' => 'represent', 'fr' => 'modéliser', 'not' => array(  ) ),
	array( 'en' => 'opportunities', 'fr' => 'possibilités', 'not' => array( 'occasions d’affaires', 'opportunistes', 'opportunités (chances)' ) ),
	array( 'en' => 'patented', 'fr' => 'breveté', 'not' => array( 'patenté', 'breveté et patenté' ) ),
	array( 'en' => 'responsive', 'fr' => 'réactif', 'not' => array( 'responsive', 'réceptif', 'sensible' ) ),
	array( 'en' => 'seamless link', 'fr' => 'liaison fluide', 'not' => array( 'lien sans couture', 'liaison sans soudure', 'connexion transparente' ) ),
	array( 'en' => 'built to last', 'fr' => 'conçu pour durer', 'not' => array( 'construit pour durer', 'bâti pour durer', 'fabriqué pour la durée' ) ),
	array( 'en' => 'design', 'fr' => 'conception', 'not' => array( 'dessin', 'projet' ) ),
	array( 'en' => 'features', 'fr' => 'fonctionnalités', 'not' => array(  ) ),
	array( 'en' => 'Key Features', 'fr' => 'caractéristiques principales', 'not' => array( 'fonctionnalités clés', 'traits principaux' ) ),
	array( 'en' => 'learning management system', 'fr' => 'plateforme de formation en ligne', 'not' => array( 'système de gestion d’apprentissage', 'système de management de l’apprentissage' ) ),
	array( 'en' => 'reportable', 'fr' => 'à déclarer', 'not' => array( 'rapportable', 'reportable' ) ),
	array( 'en' => 'personal information', 'fr' => 'données à caractère personnel', 'not' => array( 'informations personnelles', 'renseignements personnels' ) ),
	array( 'en' => 'GDPR', 'fr' => 'RGPD', 'not' => array( 'GDPR', 'RGDP' ) ),
	array( 'en' => 'WCAG', 'fr' => 'WCAG', 'not' => array( 'RGAA WCAG' ) ),
	array( 'en' => 'marine', 'fr' => 'secteur naval', 'not' => array( 'marin', 'marine militaire' ) ),
	array( 'en' => 'sales inquiry', 'fr' => 'demande commerciale', 'not' => array( 'enquête de vente', 'demande de vente', 'requête commerciale' ) ),
	array( 'en' => 'Priority 1', 'fr' => 'Priorité 1', 'not' => array(  ) ),
	array( 'en' => 'Searching ascentialtech.com', 'fr' => 'Recherche sur ascentialtech.com', 'not' => array( 'Recherche ascentialtech.com en cours' ) ),
	array( 'en' => 'Calendar View Unavailable', 'fr' => 'Vue calendrier indisponible', 'not' => array( 'Affichage du calendrier non disponible', 'Vue de calendrier indisponible' ) ),
	array( 'en' => 'Addresses', 'fr' => 'Remédie à', 'not' => array( 'Élimine', 'Supprime', 'Résout définitivement' ) ),
	array( 'en' => 'WHEREAS', 'fr' => 'ATTENDU QUE', 'not' => array( 'TANDIS QUE', 'ALORS QUE', 'PENDANT QUE' ) ),
	array( 'en' => 'RECITALS', 'fr' => 'PRÉAMBULE', 'not' => array( 'RÉCITALS', 'RÉCITS', 'NARRATIONS' ) ),
	array( 'en' => 'Exhibit', 'fr' => 'Annexe', 'not' => array( 'Exposition', 'Pièce exposée' ) ),
	array( 'en' => 'Section', 'fr' => 'Article', 'not' => array( 'Rubrique', 'Tronçon' ) ),
	array( 'en' => 'Deliverables', 'fr' => 'Livrables', 'not' => array( 'Éléments livrables', 'Produits à livrer', 'Livraisons' ) ),
	array( 'en' => 'Work Product', 'fr' => 'Résultats des Travaux', 'not' => array( 'Produit du Travail', 'Produit de travail', 'Œuvre de travail' ) ),
	array( 'en' => 'Ascential Indemnity', 'fr' => 'Indemnisation par Ascential', 'not' => array( 'Indemnité Ascential', 'Indemnisation Ascential' ) ),
	array( 'en' => 'Products', 'fr' => 'Produits', 'not' => array(  ) ),
	array( 'en' => 'Name:', 'fr' => 'Nom :', 'not' => array( 'Dénomination :', 'Appellation :', 'Raison sociale :' ) ),
	array( 'en' => 'Date:', 'fr' => 'Date :', 'not' => array( 'Données :', 'Rendez-vous :' ) ),
	array( 'en' => 'Register', 'fr' => 'Registre', 'not' => array( 'S’inscrire', 'Enregistrement', 'Inscription' ) ),
	array( 'en' => 'Registered office', 'fr' => 'Siège social', 'not' => array( 'Bureau enregistré', 'Siège enregistré', 'Bureau immatriculé' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'fr' => 'Banque-Carrefour des Entreprises', 'not' => array( 'Banque des carrefours pour entreprises' ) ),
	array( 'en' => 'KvK', 'fr' => 'KvK', 'not' => array( 'Chambre de commerce néerlandaise' ) ),
	array( 'en' => 'naamloze vennootschap', 'fr' => 'naamloze vennootschap', 'not' => array( 'société anonyme' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'fr' => 'directive Machines 2006/42/CE', 'not' => array( 'directive sur les machines 2006/42/EC' ) ),
	array( 'en' => 'Imprint', 'fr' => 'Mentions légales', 'not' => array( 'Empreinte', 'Impression', 'Imprimé' ) ),
	array( 'en' => 'Email Disclosure', 'fr' => 'Avertissement relatif aux e-mails', 'not' => array( 'Divulgation par e-mail', 'Révélation de courriel' ) ),
	array( 'en' => 'Netherlands', 'fr' => 'Pays-Bas', 'not' => array( 'Néerlande', 'Hollande' ) ),
	array( 'en' => 'England', 'fr' => 'Angleterre', 'not' => array( 'England', 'Anglais' ) ),
	array( 'en' => 'West Flanders', 'fr' => 'Flandre-Occidentale', 'not' => array( 'West Flanders', 'Flandre de l’Ouest' ) ),
	array( 'en' => 'Poland', 'fr' => 'Pologne', 'not' => array( 'Poland', 'Polande' ) ),
	array( 'en' => 'Bristol', 'fr' => 'Bristol', 'not' => array( 'Bristol carton' ) ),
	array( 'en' => 'branch', 'fr' => 'succursale', 'not' => array( 'branche', 'ramification' ) ),
	array( 'en' => 'unbeatable deals', 'fr' => 'offres imbattables', 'not' => array( 'affaires non conclues', 'marchés imbattables', 'contrats imbattables' ) ),
	array( 'en' => 'Browse catalog', 'fr' => 'Parcourir le catalogue', 'not' => array( 'Catalogue', 'Navigation dans le catalogue', 'Naviguer catalogue' ) ),
	array( 'en' => 'Explore the Catalog', 'fr' => 'Explorer le catalogue', 'not' => array( 'Catalogue', 'Découverte du catalogue' ) ),
	array( 'en' => 'Browse all resources', 'fr' => 'Parcourir toutes les ressources', 'not' => array( 'Toutes les ressources', 'Ressources', 'Navigation des ressources' ) ),
	array( 'en' => 'Explore', 'fr' => 'Découvrir', 'not' => array( 'Exploration', 'Plus d’informations' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'fr' => 'Prêt à moderniser votre infrastructure ?', 'not' => array( 'Prêt à améliorer votre infrastructure ?', 'Prêt pour la mise à niveau ?' ) ),
	array( 'en' => 'Speak with an expert', 'fr' => 'Échangez avec un expert', 'not' => array( 'Parlez avec un expert', 'Discutez avec un expert' ) ),
	array( 'en' => 'Play', 'fr' => 'Lecture', 'not' => array( 'Jouer', 'Jeu vidéo' ) ),
	array( 'en' => 'Listen to this article', 'fr' => 'Écouter cet article', 'not' => array( 'Entendre cet article', 'Écoute de cet article' ) ),
	array( 'en' => 'Read the article', 'fr' => 'Lire l’article', 'not' => array( 'Lisez l’article', 'Lecture de l’article' ) ),
	array( 'en' => 'chapters', 'fr' => 'chapitres', 'not' => array(  ) ),
	array( 'en' => 'Share / Copy link / Email', 'fr' => 'Partager / Copier le lien / E-mail', 'not' => array( 'Partage / Lien de copie / Courrier', 'Partager / Copier lien / Courriel' ) ),
	array( 'en' => 'test benches / test stands', 'fr' => 'bancs d’essai', 'not' => array( 'bancs de test', 'stands d’essai', 'supports de test' ) ),
	array( 'en' => 'testing', 'fr' => 'essais', 'not' => array( 'testage', 'tests' ) ),
	array( 'en' => 'controls', 'fr' => 'automatismes', 'not' => array( 'contrôles', 'systèmes de contrôle', 'contrôle-commande' ) ),
	array( 'en' => 'control', 'fr' => 'commande', 'not' => array( 'contrôle de processus', 'contrôle du procédé', 'vérification' ) ),
);
