<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

return array(
	array( 'en' => '*', 'it' => 'Address the reader with the formal Lei everywhere and in every slot — body copy, headings, eyebrows, ALL-CAPS bands, buttons, form labels, placeholders, alt and aria text, the <title>, the meta description, og: tags and JSON-LD — because register is a property of the PAGE, not of the segment: imperatives become third-person singular (Scopra, Legga, Richieda, Apra, Invii, Compili, Selezioni, Scelga, Sfogli, Parli, Visiti, Resti, Preveda, Riduca, Segnali, Esplori), reader pronouns and possessives become -La, Le, Suo, Sua, Suoi, Sue (aiutarLa, Le risponderemo, i Suoi impianti, la Sua struttura), and the copula English elides is restored (Ready to upgrade your infrastructure? → È pronto ad aggiornare la Sua infrastruttura?). Buttons and link labels keep the verb of the English in that same Lei imperative, which is this site’s own web-UI convention: Browse catalog → Sfogli il catalogo, Request a demo → Richieda una demo, Download → Scarichi, Contact us → Ci contatti, Speak with an expert → Parli con un esperto; never flatten a verb label into a bare noun (Catalogo, Download, Richiesta demo are wrong for those) and never put a possessive in a control label. Generic card and listing CTAs may take the impersonal form (Read More → Per saperne di più); media transport controls and their aria-labels keep the standard Italian player words (Riproduci, Pausa); consent, privacy and CCPA labels are written in the user’s own voice and keep the bare infinitive (Non vendere né condividere i miei dati personali). Nothing else on the site addresses the reader as tu or voi, at any length.', 'not' => array( 'tu', 'ti', 'te', 'voi', 'tuo', 'tua', 'tuoi', 'tue', 'Tuo', 'Tua', 'Tuoi', 'Tue', 'Voi', 'vostro', 'vostra', 'vostri', 'vostre', 'Vostro', 'Vostra', 'Vostri', 'Vostre', 'Scopri', 'scopri', 'Leggi', 'leggi', 'Richiedi', 'richiedi', 'Scegli', 'scegli', 'Esplora', 'esplora', 'Contattaci', 'contattaci', 'Seguici', 'seguici', 'Iscriviti', 'iscriviti', 'Registrati', 'Condividi', 'condividi', 'Prenota', 'prenota', 'Provalo', 'Disdici', 'Clicca', 'clicca', 'aiutarti', 'aiutarvi', 'aiutarLe', 'potete', 'dovete', 'avete', 'siete', 'otterrete', 'vorrete', 'sapete', 'Scoprite', 'Leggete', 'Visitate', 'Considerate', 'Compilate', 'Selezionate', 'Richiedete', 'Scegliete', 'Guardate', 'Contattateci', 'Scaricate', 'Inserite', 'Provate' ) ),
	array( 'en' => 'Ascential Technologies', 'it' => 'Ascential Technologies', 'not' => array( 'Tecnologie Ascential' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'it' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Prova e Misura', 'Ascential Test e Misura' ) ),
	array( 'en' => 'Ascential Care', 'it' => 'Ascential Care', 'not' => array( 'Assistenza Ascential', 'Cura Ascential' ) ),
	array( 'en' => 'Ascentialytics', 'it' => 'Ascentialytics', 'not' => array( 'Analitiche Ascential' ) ),
	array( 'en' => 'Burke Porter', 'it' => 'Burke Porter', 'not' => array( 'Porter di Burke' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'it' => 'Burke E. Porter Machinery', 'not' => array( 'Macchinari Burke E. Porter' ) ),
	array( 'en' => 'Burke Porter Group', 'it' => 'Burke Porter Group', 'not' => array( 'Gruppo Burke Porter' ) ),
	array( 'en' => 'Burke Porter automotive', 'it' => 'Burke Porter Automotive', 'not' => array( 'Automotive Burke Porter', 'Burke Porter automobilistico' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'it' => 'H. Kleinknecht & Co. GmbH', 'not' => array() ),
	array( 'en' => 'Kleinknecht', 'it' => 'Kleinknecht', 'not' => array() ),
	array( 'en' => 'Cimat', 'it' => 'Cimat', 'not' => array() ),
	array( 'en' => 'Lismar', 'it' => 'Lismar', 'not' => array() ),
	array( 'en' => 'Titan', 'it' => 'Titan', 'not' => array( 'Titano' ) ),
	array( 'en' => 'Galileo', 'it' => 'Galileo', 'not' => array() ),
	array( 'en' => 'Sentia', 'it' => 'Sentia', 'not' => array() ),
	array( 'en' => 'WinterPark Engineering', 'it' => 'WinterPark Engineering', 'not' => array( 'Ingegneria WinterPark', 'WinterPark Ingegneria' ) ),
	array( 'en' => 'XL Machine', 'it' => 'XL Machine', 'not' => array( 'Macchina XL', 'Macchine XL' ) ),
	array( 'en' => 'Bauer', 'it' => 'Bauer', 'not' => array() ),
	array( 'en' => 'Universal Balancing', 'it' => 'Universal Balancing', 'not' => array( 'Equilibratura universale', 'Bilanciamento universale', 'Equilibratrice universale' ) ),
	array( 'en' => 'CMT-TR Polimer', 'it' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR Polimero', 'CMT-TR in polimero' ) ),
	array( 'en' => 'CMT-VSR', 'it' => 'CMT-VSR', 'not' => array() ),
	array( 'en' => 'eRotor', 'it' => 'eRotor', 'not' => array( 'e-Rotore', 'Rotore elettrico' ) ),
	array( 'en' => 'Kairos Rec', 'it' => 'Kairos Rec', 'not' => array( 'Kairos Registrazione' ) ),
	array( 'en' => 'First Alert Monitoring System', 'it' => 'First Alert Monitoring System', 'not' => array( 'Sistema di primo allarme', 'Sistema di monitoraggio Primo Allarme' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'it' => 'Turbo Test Duo Expert', 'not' => array( 'Esperto Turbo Test Duo' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'it' => 'ADVANCING THE MACHINE', 'not' => array( 'FAR AVANZARE LA MACCHINA', 'FAR PROGREDIRE LA MACCHINA' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'it' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDICALE E SCIENZE DELLA VITA' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'it' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'SOLUZIONI DI COMMERCIALIZZAZIONE TOTALE' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'it' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Calibrazione come servizio', 'Taratura come servizio' ) ),
	array( 'en' => 'Impossible? Done.', 'it' => 'Impossible? Done.', 'not' => array( 'Impossibile? Fatto.' ) ),
	array( 'en' => 'Ask Burke Porter', 'it' => 'Ask Burke Porter', 'not' => array( 'Chiedi a Burke Porter', 'Domanda a Burke Porter' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'it' => 'A DESIGN / B LOGO', 'not' => array() ),
	array( 'en' => 'Core / Plus / Elite', 'it' => 'Core / Plus / Elite', 'not' => array( 'Nucleo / Plus / Elite', 'Base / Plus / Elite' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'it' => 'Crossroads Bank for Enterprises', 'not' => array( 'Banca degli incroci per le imprese' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'it' => 'KvK (Kamer van Koophandel)', 'not' => array() ),
	array( 'en' => 'naamloze vennootschap (NV)', 'it' => 'naamloze vennootschap (NV)', 'not' => array( 'società anonima (NV)' ) ),
	array( 'en' => 'Marketplace', 'it' => 'Marketplace', 'not' => array( 'Mercato', 'Piazza di mercato' ) ),
	array( 'en' => 'GDPR', 'it' => 'GDPR', 'not' => array( 'RGPD' ) ),
	array( 'en' => 'MRO', 'it' => 'MRO', 'not' => array( 'manutenzione, riparazione e revisione' ) ),
	array( 'en' => 'HMU/FMU', 'it' => 'HMU/FMU', 'not' => array() ),
	array( 'en' => 'e-axle', 'it' => 'e-axle', 'not' => array( 'asse elettrico', 'assale elettrico' ) ),
	array( 'en' => 'flexplate', 'it' => 'flexplate', 'not' => array( 'piastra flessibile' ) ),
	array( 'en' => 'torque vectoring', 'it' => 'torque vectoring', 'not' => array( 'vettorizzazione di coppia' ) ),
	array( 'en' => 'right-shoring', 'it' => 'right-shoring', 'not' => array( 'ricollocazione', 'delocalizzazione' ) ),
	array( 'en' => 'restbus simulation', 'it' => 'simulazione restbus', 'not' => array( 'simulazione del bus di riposo', 'simulazione a bus residuo' ) ),
	array( 'en' => 'customer journey', 'it' => 'customer journey', 'not' => array( 'viaggio del cliente' ) ),
	array( 'en' => 'life sciences', 'it' => 'life sciences', 'not' => array( 'scienze vitali' ) ),
	array( 'en' => 'whitepaper', 'it' => 'whitepaper', 'not' => array( 'libro bianco', 'carta bianca' ) ),
	array( 'en' => 'unbalance', 'it' => 'squilibrio', 'not' => array( 'sbilanciamento', 'disequilibrio', 'non bilanciamento' ) ),
	array( 'en' => 'residual unbalance', 'it' => 'squilibrio residuo', 'not' => array( 'sbilanciamento residuo', 'squilibratura residua' ) ),
	array( 'en' => 'correction', 'it' => 'correzione', 'not' => array( 'rettifica dello squilibrio' ) ),
	array( 'en' => 'balancing', 'it' => 'equilibratura', 'not' => array( 'bilanciamento', 'equilibrazione', 'messa in equilibrio' ) ),
	array( 'en' => 'balancing machine', 'it' => 'equilibratrice', 'not' => array( 'bilanciatrice', 'macchina bilanciatrice', 'equilibratore' ) ),
	array( 'en' => 'Balancing Machines', 'it' => 'Equilibratrici', 'not' => array( 'Macchine equilibratrici', 'Macchine bilanciatrici', 'Bilanciatrici' ) ),
	array( 'en' => 'balancing systems', 'it' => 'sistemi di equilibratura', 'not' => array( 'sistemi di bilanciamento' ) ),
	array( 'en' => 'Balancing as a Service (BaaS)', 'it' => 'Equilibratura conto terzi as-a-service (BaaS)', 'not' => array( 'Equilibratura come servizio', 'Bilanciamento as-a-service', 'Equilibratura contrattuale' ) ),
	array( 'en' => 'Contract balancing as-a-service (BaaS)', 'it' => 'Equilibratura conto terzi as-a-service (BaaS)', 'not' => array( 'Equilibratura as-a-service (BaaS)', 'Equilibratura contrattuale as-a-service' ) ),
	array( 'en' => 'non-rotating balancing machine', 'it' => 'equilibratrice non rotante', 'not' => array( 'equilibratrice senza rotazione', 'bilanciatrice statica', 'equilibratrice non girevole' ) ),
	array( 'en' => 'Non-Rotate Systems', 'it' => 'Sistemi non rotanti', 'not' => array( 'Sistemi di non rotazione', 'Sistemi senza rotazione' ) ),
	array( 'en' => 'field balancing', 'it' => 'equilibratura in loco', 'not' => array( 'equilibratura sul campo', 'bilanciamento in campo' ) ),
	array( 'en' => 'Field Balancers', 'it' => 'Equilibratrici portatili', 'not' => array( 'Bilanciatori portatili', 'Bilanciatori da campo', 'Equilibratori da campo' ) ),
	array( 'en' => 'spin testing machine', 'it' => 'macchina per prove di rotazione', 'not' => array( 'macchina per prove di filatura' ) ),
	array( 'en' => 'Spin Testing', 'it' => 'Prove di rotazione', 'not' => array( 'Prova di filatura', 'Collaudo di filatura' ) ),
	array( 'en' => 'core balancing', 'it' => 'equilibratura cartucce', 'not' => array( 'equilibratura del nucleo', 'bilanciamento del nucleo', 'equilibratura a nucleo' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'it' => 'Equilibratrice combinata per cartucce ad alta e bassa velocità', 'not' => array( 'Macchina di equilibratura a nucleo ad alta e bassa velocità combinata', 'Equilibratrice a nucleo combinata' ) ),
	array( 'en' => 'CMT-TR Low-Speed Core Balancing Machine', 'it' => 'Equilibratrice per cartucce a bassa velocità CMT-TR', 'not' => array( 'Macchina di equilibratura a nucleo a bassa velocità CMT-TR' ) ),
	array( 'en' => 'CMT-VSR High-Speed Core Balancing Machine', 'it' => 'Equilibratrice per cartucce ad alta velocità CMT-VSR', 'not' => array( 'Macchina di equilibratura a nucleo ad alta velocità CMT-VSR' ) ),
	array( 'en' => 'CMT-TR Polimer Rotor Balancing Machine', 'it' => 'Equilibratrice per rotori CMT-TR Polimer', 'not' => array( 'Macchina di equilibratura rotori in polimero CMT-TR', 'Equilibratrice per rotori in polimero CMT-TR' ) ),
	array( 'en' => 'Turbo Balancing Machine', 'it' => 'Equilibratrice per turbocompressori', 'not' => array( 'Macchina di equilibratura turbo', 'Bilanciatrice turbo' ) ),
	array( 'en' => 'turbo balancing systems', 'it' => 'sistemi di equilibratura turbo', 'not' => array( 'sistemi di bilanciamento turbo' ) ),
	array( 'en' => 'Balancers for Clutches', 'it' => 'Equilibratrici per frizioni', 'not' => array( 'Equilibratori per frizioni', 'Bilanciatori per frizioni' ) ),
	array( 'en' => 'Balancers for Crankshafts', 'it' => 'Equilibratrici per alberi motore', 'not' => array( 'Equilibratori per alberi motore', 'Bilanciatori per alberi a gomiti' ) ),
	array( 'en' => 'Balancers for Driveshafts', 'it' => 'Equilibratrici per alberi di trasmissione', 'not' => array( 'Equilibratori per alberi di trasmissione' ) ),
	array( 'en' => 'Balancers for Dual Mass Flywheels', 'it' => 'Equilibratrici per volani bimassa', 'not' => array( 'Equilibratrici per volani a doppia massa', 'Equilibratori per volani bimassa' ) ),
	array( 'en' => 'Balancers for Rims', 'it' => 'Equilibratrici per cerchi', 'not' => array( 'Equilibratori per cerchioni' ) ),
	array( 'en' => 'Balancers for ECFA and HVAC Blowers', 'it' => 'Equilibratrici per soffianti ECFA e HVAC', 'not' => array( 'Equilibratrici per ventilatori ECFA e HVAC', 'Equilibratori per soffianti' ) ),
	array( 'en' => 'Automated Balancers for Brake Discs and Drums', 'it' => 'Equilibratrici automatiche per dischi e tamburi freno', 'not' => array( 'Equilibratori automatici per dischi e tamburi' ) ),
	array( 'en' => 'Automated Balancers for Rotors of Superchargers', 'it' => 'Equilibratrici automatiche per rotori di compressori volumetrici', 'not' => array( 'Equilibratrici automatiche per rotori di sovralimentatori', 'Equilibratori per rotori di compressori' ) ),
	array( 'en' => 'Automatic Balancers for Alternators', 'it' => 'Equilibratrici automatiche per alternatori', 'not' => array( 'Equilibratori automatici per alternatori' ) ),
	array( 'en' => 'Automatic Balancers for Disc-Shaped Rotors', 'it' => 'Equilibratrici automatiche per rotori a disco', 'not' => array( 'Equilibratrici automatiche per rotori a forma di disco' ) ),
	array( 'en' => 'Automotive Industry Balancers', 'it' => 'Equilibratrici per l’industria automobilistica', 'not' => array( 'Equilibratori per l’industria automobilistica', 'Bilanciatrici automobilistiche' ) ),
	array( 'en' => 'Industrial Balancing Machine', 'it' => 'Equilibratrice industriale', 'not' => array( 'Macchina di equilibratura industriale', 'Bilanciatrice industriale' ) ),
	array( 'en' => 'Propeller balancers', 'it' => 'Equilibratrici per eliche', 'not' => array( 'Equilibratori per eliche', 'Bilanciatrici per eliche' ) ),
	array( 'en' => 'Fan balancer', 'it' => 'Equilibratrice per ventilatori', 'not' => array( 'Bilanciatore per ventole', 'Equilibratore per ventilatori' ) ),
	array( 'en' => 'Brake rotor balancer', 'it' => 'Equilibratrice per dischi freno', 'not' => array( 'Equilibratore per rotori freno', 'Bilanciatrice per rotori del freno' ) ),
	array( 'en' => 'Clutch and flywheel balancer', 'it' => 'Equilibratrice per frizioni e volani', 'not' => array( 'Equilibratore per frizione e volano' ) ),
	array( 'en' => 'Differential case balancer', 'it' => 'Equilibratrice per scatole differenziale', 'not' => array( 'Equilibratrice per carter differenziale', 'Equilibratore del differenziale' ) ),
	array( 'en' => 'Pulley balancer', 'it' => 'Equilibratrice per pulegge', 'not' => array( 'Equilibratore per pulegge', 'Bilanciatrice per carrucole' ) ),
	array( 'en' => 'Electric motor balancer', 'it' => 'Equilibratrice per motori elettrici', 'not' => array( 'Equilibratore per motori elettrici' ) ),
	array( 'en' => 'Turbine component balancer', 'it' => 'Equilibratrice per componenti di turbina', 'not' => array( 'Equilibratore per componenti turbina' ) ),
	array( 'en' => 'Transmission component balancer', 'it' => 'Equilibratrice per componenti del cambio', 'not' => array( 'Equilibratore per componenti di trasmissione' ) ),
	array( 'en' => 'Axle balancing machines', 'it' => 'Equilibratrici per assali', 'not' => array( 'Macchine di equilibratura per assi' ) ),
	array( 'en' => 'Crankshaft balancing machines', 'it' => 'Equilibratrici per alberi motore', 'not' => array( 'Macchine di equilibratura per alberi a gomiti' ) ),
	array( 'en' => 'Driveshaft balancing machines', 'it' => 'Equilibratrici per alberi di trasmissione', 'not' => array( 'Macchine di equilibratura per alberi di trasmissione' ) ),
	array( 'en' => 'eRotor balancing machine', 'it' => 'Equilibratrice per eRotor', 'not' => array( 'Macchina per l’equilibratura eRotor', 'Bilanciatrice eRotor' ) ),
	array( 'en' => 'bearers', 'it' => 'supporti', 'not' => array( 'portatori', 'latori', 'traverse' ) ),
	array( 'en' => 'pedestals', 'it' => 'supporti', 'not' => array( 'piedistalli', 'colonnine' ) ),
	array( 'en' => 'pins', 'it' => 'perni', 'not' => array( 'spilli', 'chiodi' ) ),
	array( 'en' => 'v-block support', 'it' => 'supporto a V', 'not' => array( 'supporto a blocco V', 'appoggio a V' ) ),
	array( 'en' => 'retaining rollers', 'it' => 'rulli di ritegno', 'not' => array( 'rulli di trattenimento', 'rulli di ritenzione' ) ),
	array( 'en' => 'movable cradle', 'it' => 'culla mobile', 'not' => array( 'cuna mobile', 'supporto mobile a culla' ) ),
	array( 'en' => 'maximum rotor diameter', 'it' => 'diametro massimo del rotore', 'not' => array( 'diametro rotore massimale' ) ),
	array( 'en' => 'bearing center lines', 'it' => 'assi dei cuscinetti', 'not' => array( 'linee centrali dei cuscinetti' ) ),
	array( 'en' => 'bearing life', 'it' => 'durata dei cuscinetti', 'not' => array( 'vita del portamento' ) ),
	array( 'en' => 'punching', 'it' => 'punzonatura', 'not' => array( 'perforazione', 'pugnatura' ) ),
	array( 'en' => 'Electronic hung mass', 'it' => 'massa appesa elettronica', 'not' => array( 'massa sospesa elettronica', 'peso elettronico appeso' ) ),
	array( 'en' => 'kinetostatics', 'it' => 'cinetostatica', 'not' => array( 'chinetostatica', 'cinetostatico' ) ),
	array( 'en' => 'TIR / radial run-out', 'it' => 'TIR / eccentricità radiale', 'not' => array( 'TIR / scentratura radiale' ) ),
	array( 'en' => 'weight capacity', 'it' => 'portata', 'not' => array( 'capacità di peso' ) ),
	array( 'en' => 'load capacity', 'it' => 'portata', 'not' => array( 'capacità del carico' ) ),
	array( 'en' => 'vibration', 'it' => 'vibrazioni', 'not' => array( 'vibrazione meccanica' ) ),
	array( 'en' => 'rotor wing aircraft', 'it' => 'aeromobili ad ala rotante', 'not' => array( 'aerei ad ala rotante', 'velivoli ad ala girevole' ) ),
	array( 'en' => 'blade timing', 'it' => 'fasatura delle pale', 'not' => array( 'temporizzazione delle lame', 'sincronizzazione delle lame' ) ),
	array( 'en' => 'ring gears', 'it' => 'corone dentate', 'not' => array( 'ingranaggi ad anello', 'ruote ad anello' ) ),
	array( 'en' => 'turbocharger', 'it' => 'turbocompressore', 'not' => array( 'turbocaricatore', 'turbo compressore' ) ),
	array( 'en' => 'turbocharger flow bench', 'it' => 'banco di flussaggio per turbocompressori', 'not' => array( 'banco di prova per turbocompressori', 'banco di flusso per turbocompressori' ) ),
	array( 'en' => 'Turbocharger Flow Benches', 'it' => 'Banchi di flussaggio per turbocompressori', 'not' => array( 'Banchi di prova per turbocompressori', 'Banchi di flusso per turbocompressori' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'it' => 'Banco di flussaggio dinamico per turbocompressori', 'not' => array( 'Banco di flusso dinamico', 'Banco di prova dinamico per turbocompressori' ) ),
	array( 'en' => 'turbocharger frame size', 'it' => 'taglia del turbocompressore', 'not' => array( 'dimensione del telaio del turbocompressore' ) ),
	array( 'en' => 'turbo calibration', 'it' => 'calibrazione del turbocompressore', 'not' => array( 'taratura della turbina' ) ),
	array( 'en' => 'diesel turbocharger balancing', 'it' => 'equilibratura di turbocompressori diesel', 'not' => array( 'equilibratura di turbocompressori', 'bilanciamento turbo diesel' ) ),
	array( 'en' => 'whistle', 'it' => 'fischio', 'not' => array( 'fischietto', 'zufolo' ) ),
	array( 'en' => 'boreless compressor wheel', 'it' => 'girante del compressore senza foro', 'not' => array( 'ruota del compressore senza alesaggio' ) ),
	array( 'en' => 'reconditioning', 'it' => 'ricondizionamento', 'not' => array( 'ricondizionatura', 'rimessa a nuovo' ) ),
	array( 'en' => 'Transportation', 'it' => 'Trasporti', 'not' => array( 'Trasporto', 'Trasportazione' ) ),
	array( 'en' => 'Powertrain', 'it' => 'gruppo motopropulsore', 'not' => array( 'gruppo propulsore', 'catena cinematica', 'trasmissione meccanica' ) ),
	array( 'en' => 'propulsion & powertrain', 'it' => 'propulsione e gruppo motopropulsore', 'not' => array( 'propulsione e trasmissione', 'propulsione e gruppo propulsore' ) ),
	array( 'en' => 'Propulsion and Powertrain', 'it' => 'Propulsione e gruppo motopropulsore', 'not' => array( 'Propulsione e gruppo propulsore', 'Propulsione e trasmissione' ) ),
	array( 'en' => 'transmission / gearbox', 'it' => 'cambio', 'not' => array( 'riduttore', 'ingranaggio' ) ),
	array( 'en' => 'Transmission', 'it' => 'Trasmissione', 'not' => array( 'Cambio di velocità' ) ),
	array( 'en' => 'Transmission drop box', 'it' => 'Scatola di rinvio del cambio', 'not' => array( 'Scatola di riduzione trasmissione', 'Cassetta di caduta' ) ),
	array( 'en' => 'CVT transmission front cover', 'it' => 'Coperchio anteriore del cambio CVT', 'not' => array( 'Copertura frontale della trasmissione CVT' ) ),
	array( 'en' => 'Wet clutch', 'it' => 'Frizione in bagno d’olio', 'not' => array( 'Frizione bagnata', 'Frizione umida' ) ),
	array( 'en' => 'Wet brakes test', 'it' => 'Prova dei freni in bagno d’olio', 'not' => array( 'Prova di freni bagnati', 'Test dei freni umidi' ) ),
	array( 'en' => 'dual mass flywheel', 'it' => 'volano bimassa', 'not' => array( 'volano a doppia massa', 'volano di doppia massa' ) ),
	array( 'en' => 'flywheel', 'it' => 'volano', 'not' => array( 'ruota volante', 'volante d’inerzia' ) ),
	array( 'en' => 'crankshaft', 'it' => 'albero motore', 'not' => array( 'albero a gomiti', 'manovella' ) ),
	array( 'en' => 'inline crankshaft', 'it' => 'albero motore in linea', 'not' => array( 'manovella in linea' ) ),
	array( 'en' => 'single cylinder crankshaft', 'it' => 'albero motore monocilindrico', 'not' => array( 'manovella a cilindro singolo' ) ),
	array( 'en' => 'crankshaft lathe', 'it' => 'tornio per alberi motore', 'not' => array( 'tornio per manovelle' ) ),
	array( 'en' => 'driveshaft', 'it' => 'albero di trasmissione', 'not' => array( 'asse motore', 'albero motore di trasmissione' ) ),
	array( 'en' => 'axle', 'it' => 'assale', 'not' => array( 'ascia', 'asse stradale' ) ),
	array( 'en' => 'Axles', 'it' => 'Assali', 'not' => array( 'Assi stradali' ) ),
	array( 'en' => 'third member', 'it' => 'gruppo differenziale', 'not' => array( 'terzo membro', 'terzo elemento' ) ),
	array( 'en' => 'half case', 'it' => 'semiscatola', 'not' => array( 'mezza cassa', 'metà caso' ) ),
	array( 'en' => 'pinion gear', 'it' => 'pignone', 'not' => array( 'ingranaggio del pignone', 'ruota dentata pignone' ) ),
	array( 'en' => 'valve body unit', 'it' => 'corpo valvole', 'not' => array( 'unità del corpo valvola', 'gruppo corpo della valvola' ) ),
	array( 'en' => 'armature', 'it' => 'indotto', 'not' => array( 'armatura', 'corazza' ) ),
	array( 'en' => 'control module', 'it' => 'centralina', 'not' => array( 'modulo di controllo', 'modulo di comando' ) ),
	array( 'en' => 'blank ECM', 'it' => 'ECM vergine', 'not' => array( 'ECM in bianco', 'ECM vuoto' ) ),
	array( 'en' => 'instrument cluster', 'it' => 'quadro strumenti', 'not' => array( 'cluster di strumenti', 'grappolo strumenti' ) ),
	array( 'en' => 'traction battery', 'it' => 'batteria di trazione', 'not' => array( 'batteria a trazione', 'accumulatore di trazione' ) ),
	array( 'en' => 'drivability', 'it' => 'guidabilità', 'not' => array( 'drivability', 'conducibilità' ) ),
	array( 'en' => 'gear shift calibration', 'it' => 'calibrazione del cambio marcia', 'not' => array( 'calibrazione dell’ingranaggio' ) ),
	array( 'en' => 'rolling torque', 'it' => 'coppia di rotolamento', 'not' => array( 'coppia di laminazione', 'momento di rotolamento' ) ),
	array( 'en' => 'two-wheel drive', 'it' => 'trazione a due ruote', 'not' => array( 'guida a due ruote' ) ),
	array( 'en' => 'commercial vehicle', 'it' => 'veicolo industriale', 'not' => array( 'camion', 'veicolo di commercio' ) ),
	array( 'en' => 'truck', 'it' => 'veicoli industriali', 'not' => array( 'camion', 'autocarri da trasporto' ) ),
	array( 'en' => 'heavy-duty', 'it' => 'per impieghi gravosi', 'not' => array( 'a servizio pesante', 'di lavoro pesante' ) ),
	array( 'en' => 'dynamometer', 'it' => 'dinamometro', 'not' => array( 'misuratore di forza', 'dinamometrico' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'it' => 'banco a rulli a 2 e 4 ruote', 'not' => array( 'dinamometro per telaio', 'dinamometro del telaio a 2 e 4 ruote' ) ),
	array( 'en' => 'Chassis, hub & steerable dyno', 'it' => 'Banchi a rulli, dinamometri per mozzo e per ruote sterzanti', 'not' => array( 'Dinamometri per telaio, mozzo e sterzo' ) ),
	array( 'en' => 'inline dyno', 'it' => 'dinamometro in linea', 'not' => array( 'dinamometro di linea' ) ),
	array( 'en' => 'roller brake tester', 'it' => 'banco prova freni a rulli', 'not' => array( 'tester dei freni a rullo', 'provafreni a rulli' ) ),
	array( 'en' => 'roller', 'it' => 'rullo', 'not' => array( 'rotella', 'rullino' ) ),
	array( 'en' => 'wheel alignment', 'it' => 'assetto ruote', 'not' => array( 'allineamento delle ruote', 'allineamento ruote' ) ),
	array( 'en' => 'wheel aligner', 'it' => 'banco assetto ruote', 'not' => array( 'allineatore di ruote', 'allineatore ruote' ) ),
	array( 'en' => 'Non-contact wheel alignment', 'it' => 'Assetto ruote senza contatto', 'not' => array( 'Allineamento ruote non a contatto' ) ),
	array( 'en' => 'ADAS (advanced driver assistance systems)', 'it' => 'ADAS (sistemi avanzati di assistenza alla guida)', 'not' => array( 'ADAS (sistemi avanzati di assistenza al conducente)' ) ),
	array( 'en' => 'ADAS alignment', 'it' => 'allineamento ADAS', 'not' => array( 'assetto ADAS', 'allineamento delle ruote ADAS' ) ),
	array( 'en' => 'ADAS calibration aftermarket systems', 'it' => 'Sistemi di calibrazione ADAS aftermarket', 'not' => array( 'Sistemi ADAS di taratura del mercato dei ricambi' ) ),
	array( 'en' => 'calibration target', 'it' => 'target di calibrazione', 'not' => array( 'obiettivo di calibrazione', 'bersaglio di calibrazione' ) ),
	array( 'en' => 'probe alignment', 'it' => 'allineamento del tastatore', 'not' => array( 'allineamento della sonda di misura' ) ),
	array( 'en' => 'active part probing', 'it' => 'tastatura attiva del pezzo', 'not' => array( 'sondaggio attivo della parte' ) ),
	array( 'en' => 'misalignment', 'it' => 'disallineamento', 'not' => array( 'cattivo allineamento', 'allineamento errato' ) ),
	array( 'en' => 'bead breaking', 'it' => 'stallonatura', 'not' => array( 'rottura del tallone', 'spaccatura del bordo' ) ),
	array( 'en' => 'tire inflator', 'it' => 'gonfiatore per pneumatici', 'not' => array( 'gonfia gomme', 'gonfiatore di gomme' ) ),
	array( 'en' => 'squeak & rattle testing', 'it' => 'prove squeak & rattle', 'not' => array( 'prove di cigolii e sonagli', 'test di scricchiolio e sferragliamento' ) ),
	array( 'en' => 'end of line testing', 'it' => 'collaudo di fine linea', 'not' => array( 'test di fine riga', 'prova a fine della linea' ) ),
	array( 'en' => 'Vehicle end-of-line solutions', 'it' => 'Soluzioni di fine linea per veicoli', 'not' => array( 'Soluzioni di fine riga per veicoli' ) ),
	array( 'en' => 'engine software loaders', 'it' => 'sistemi di caricamento del software motore', 'not' => array( 'caricatori del software del motore' ) ),
	array( 'en' => 'idle duration', 'it' => 'durata del minimo', 'not' => array( 'durata di inattività', 'durata dell’ozio' ) ),
	array( 'en' => 'exhaust extraction', 'it' => 'aspirazione dei gas di scarico', 'not' => array( 'estrazione di scarico', 'estrazione dei gas esausti' ) ),
	array( 'en' => 'energy recuperation', 'it' => 'recupero di energia', 'not' => array( 'recuperazione energetica' ) ),
	array( 'en' => 'torque', 'it' => 'coppia', 'not' => array( 'torsione', 'momento torcente' ) ),
	array( 'en' => 'refrigerant', 'it' => 'refrigerante', 'not' => array( 'liquido di raffreddamento', 'fluido frigorigeno di raffreddamento' ) ),
	array( 'en' => 'refrigerant charging', 'it' => 'carica del refrigerante', 'not' => array( 'ricarica refrigerante', 'caricamento del refrigerante' ) ),
	array( 'en' => 'refrigerant charging & leak detection', 'it' => 'carica del refrigerante e rilevamento delle perdite', 'not' => array( 'carica refrigerante e rilevamento perdite' ) ),
	array( 'en' => 'Refrigerant Fluid & Gas Charging Machines', 'it' => 'Macchine di carica per fluidi e gas refrigeranti', 'not' => array( 'Macchine di carica refrigerante fluido e gas' ) ),
	array( 'en' => 'Refrigerant Charging Machine Accessories', 'it' => 'Accessori per macchine di carica del refrigerante', 'not' => array( 'Accessori per macchine di carica refrigerante' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'it' => 'Brochure sulla carica del refrigerante', 'not' => array( 'Brochure carica refrigerante' ) ),
	array( 'en' => 'refrigeration', 'it' => 'refrigerazione', 'not' => array( 'raffreddamento industriale' ) ),
	array( 'en' => 'leak detection', 'it' => 'rilevamento delle perdite', 'not' => array( 'rilevazione di fughe', 'individuazione delle fughe' ) ),
	array( 'en' => 'Leak Detection Systems', 'it' => 'Sistemi di rilevamento delle perdite', 'not' => array( 'Sistemi di rilevamento perdite', 'Sistemi di fuga' ) ),
	array( 'en' => 'leak detection & refrigeration', 'it' => 'rilevamento delle perdite e refrigerazione', 'not' => array( 'rilevamento perdite e refrigerazione' ) ),
	array( 'en' => 'Leak Detection & Gas Management', 'it' => 'Rilevamento delle perdite e gestione dei gas', 'not' => array( 'Rilevamento perdite e gestione gas' ) ),
	array( 'en' => 'fine leak', 'it' => 'microperdita', 'not' => array( 'perdita fine', 'fuga fine' ) ),
	array( 'en' => 'gross leak test', 'it' => 'prova di macroperdite', 'not' => array( 'test di perdita lorda', 'prova di fuga grossolana' ) ),
	array( 'en' => 'tracer gas', 'it' => 'gas tracciante', 'not' => array( 'gas traccia', 'gas di tracciamento' ) ),
	array( 'en' => 'flammable gases', 'it' => 'gas infiammabili', 'not' => array( 'gas fiammabili' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'it' => 'pinza sniffer / sniffer', 'not' => array( 'pinza annusatrice / annusatore' ) ),
	array( 'en' => 'Helium Recovery Systems', 'it' => 'Sistemi di recupero dell’elio', 'not' => array( 'Sistemi di ricupero elio' ) ),
	array( 'en' => 'vacuum', 'it' => 'vuoto', 'not' => array( 'aspirapolvere', 'vacuo' ) ),
	array( 'en' => 'vacuum evacuation', 'it' => 'evacuazione sotto vuoto', 'not' => array( 'svuotamento del vacuo' ) ),
	array( 'en' => 'vacuum rise test', 'it' => 'prova di risalita del vuoto', 'not' => array( 'test di aumento del vuoto' ) ),
	array( 'en' => 'Vacuum Chamber', 'it' => 'Camera da vuoto', 'not' => array( 'Camera a vuoto' ) ),
	array( 'en' => 'Vacuum Gauge and Instruments', 'it' => 'Vacuometri e strumenti', 'not' => array( 'Manometri per vuoto e strumenti', 'Calibri per vuoto' ) ),
	array( 'en' => 'Rotary Vacuum Pumps', 'it' => 'Pompe per vuoto rotative', 'not' => array( 'Pompe a vuoto girevoli' ) ),
	array( 'en' => 'Transfer Pumps & Storage', 'it' => 'Pompe di travaso e stoccaggio', 'not' => array( 'Pompe di trasferimento e magazzinaggio' ) ),
	array( 'en' => 'pressurization', 'it' => 'pressurizzazione', 'not' => array( 'messa in pressione forzata' ) ),
	array( 'en' => 'soak time', 'it' => 'tempo di stabilizzazione', 'not' => array( 'tempo di ammollo', 'tempo di immersione' ) ),
	array( 'en' => 'final discharge', 'it' => 'scarico finale', 'not' => array( 'scarica finale' ) ),
	array( 'en' => 'oil drain', 'it' => 'scarico dell’olio', 'not' => array( 'drenaggio dell’olio' ) ),
	array( 'en' => 'filler gun', 'it' => 'pistola di riempimento', 'not' => array( 'pistola riempitrice', 'fucile di riempimento' ) ),
	array( 'en' => 'sealed assembly', 'it' => 'gruppo sigillato', 'not' => array( 'assemblaggio sigillato', 'montaggio ermetico' ) ),
	array( 'en' => 'cooling units', 'it' => 'unità di raffreddamento', 'not' => array( 'gruppi di raffredamento' ) ),
	array( 'en' => 'vapor compression cooling', 'it' => 'raffreddamento a compressione di vapore', 'not' => array( 'raffreddamento per compressione del vapore' ) ),
	array( 'en' => 'cab HVAC & refrigerated trailers', 'it' => 'HVAC per cabine e rimorchi refrigerati', 'not' => array( 'HVAC di cabina e rimorchi frigoriferi' ) ),
	array( 'en' => 'HVAC fan & blower balancing', 'it' => 'equilibratura di ventilatori e soffianti HVAC', 'not' => array( 'bilanciamento di ventole e soffiatori HVAC' ) ),
	array( 'en' => 'blowers', 'it' => 'soffianti', 'not' => array( 'soffiatori', 'ventole soffianti' ) ),
	array( 'en' => 'air cycle machines', 'it' => 'macchine a ciclo ad aria', 'not' => array( 'macchine del ciclo aereo' ) ),
	array( 'en' => 'keg', 'it' => 'fusto', 'not' => array( 'barile', 'botte' ) ),
	array( 'en' => 'keg finger holes', 'it' => 'fori di presa del fusto', 'not' => array( 'fori per le dita del barile' ) ),
	array( 'en' => 'Ultrasonic Welding Systems', 'it' => 'Sistemi di saldatura a ultrasuoni', 'not' => array( 'Sistemi di saldatura ultrasonica', 'Sistemi di saldatura ultrasuonica' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'it' => 'pulitore a ultrasuoni per ugelli', 'not' => array( 'pulitrice ultrasonica degli ugelli' ) ),
	array( 'en' => 'Electrical Safety Test', 'it' => 'Prova di sicurezza elettrica', 'not' => array( 'Test di sicurezza elettrico' ) ),
	array( 'en' => 'Performance Test Systems', 'it' => 'Sistemi di prova delle prestazioni', 'not' => array( 'Sistemi di test di performance' ) ),
	array( 'en' => 'Data Acquisition Systems', 'it' => 'Sistemi di acquisizione dati', 'not' => array( 'Sistemi di acquisizione di dati' ) ),
	array( 'en' => 'Evacuation', 'it' => 'Evacuazione', 'not' => array( 'Sgombero' ) ),
	array( 'en' => 'Recovery Systems', 'it' => 'Sistemi di recupero', 'not' => array( 'Sistemi di ricupero' ) ),
	array( 'en' => 'Atmosphere – Refrigerants', 'it' => 'Atmosfera – Refrigeranti', 'not' => array( 'Atmosfera - Refrigeranti' ) ),
	array( 'en' => 'Atmosphere – Tracer Gases', 'it' => 'Atmosfera – Gas traccianti', 'not' => array( 'Atmosfera - Gas traccianti' ) ),
	array( 'en' => 'HC (Hydrocarbons)', 'it' => 'HC (idrocarburi)', 'not' => array( 'HC (Idrocarburi)' ) ),
	array( 'en' => 'HFC (Non-Flammable)', 'it' => 'HFC (non infiammabili)', 'not' => array( 'HFC (non infiammabile)' ) ),
	array( 'en' => 'Gas Industry & Compressor Stations', 'it' => 'Industria del gas e stazioni di compressione', 'not' => array( 'Industria di gas e stazioni compressori' ) ),
	array( 'en' => 'Water & Wastewater Systems', 'it' => 'Sistemi per acqua e acque reflue', 'not' => array( 'Sistemi di acqua e acque reflue' ) ),
	array( 'en' => 'water meter', 'it' => 'contatore d’acqua', 'not' => array( 'misuratore dell’acqua', 'metro dell’acqua' ) ),
	array( 'en' => 'water-cooled', 'it' => 'raffreddato ad acqua', 'not' => array( 'raffreddato con acqua' ) ),
	array( 'en' => 'metals automation and systems integration', 'it' => 'automazione per l’industria metallurgica e integrazione di sistemi', 'not' => array( 'automazione metalli e integrazione sistemi' ) ),
	array( 'en' => 'Roll Shop Technologies', 'it' => 'Tecnologie per officine cilindri', 'not' => array( 'Tecnologie officine rulli', 'Tecnologie per officine di laminazione' ) ),
	array( 'en' => 'roll shop', 'it' => 'officina cilindri', 'not' => array( 'officina rulli', 'officina di laminazione' ) ),
	array( 'en' => 'mill roll', 'it' => 'cilindro di laminazione', 'not' => array( 'rullo del mulino', 'rulli di laminazione' ) ),
	array( 'en' => 'forged rolls', 'it' => 'cilindri forgiati', 'not' => array( 'rulli forgiati', 'rulli fucinati' ) ),
	array( 'en' => 'roll grinding', 'it' => 'rettifica dei cilindri', 'not' => array( 'rettifica rulli', 'molatura dei rulli' ) ),
	array( 'en' => 'roll grinding machines', 'it' => 'rettificatrici per cilindri', 'not' => array( 'macchine per rettifica rulli', 'molatrici per rulli' ) ),
	array( 'en' => 'roll inspection', 'it' => 'controllo dei cilindri', 'not' => array( 'ispezione di rulli', 'ispezione dei rulli', 'Ispezione di rulli', 'Ispezione rulli' ) ),
	array( 'en' => 'reconditioning (rolls)', 'it' => 'ricondizionamento dei cilindri', 'not' => array( 'rigenerazione dei rulli' ) ),
	array( 'en' => 'roll grinding, texturing & controls', 'it' => 'rettifica dei cilindri, testurizzazione e sistemi di controllo', 'not' => array( 'rettifica rulli, testurizzazione e controlli' ) ),
	array( 'en' => 'Grinding Technology', 'it' => 'Tecnologia di rettifica', 'not' => array( 'Tecnologia di rettificatura', 'Tecnologia di molatura' ) ),
	array( 'en' => 'grinding wheel', 'it' => 'mola', 'not' => array( 'ruota abrasiva', 'ruota di rettifica' ) ),
	array( 'en' => 'infeed', 'it' => 'avanzamento in profondità', 'not' => array( 'alimentazione in ingresso' ) ),
	array( 'en' => 'rotary diamond dressing', 'it' => 'ravvivatura con diamante rotante', 'not' => array( 'medicazione al diamante rotante', 'vestizione diamantata' ) ),
	array( 'en' => 'superabrasives', 'it' => 'superabrasivi', 'not' => array( 'abrasivi superiori' ) ),
	array( 'en' => 'turret-style wheel head', 'it' => 'testa portamola a torretta', 'not' => array( 'testa della ruota a torretta' ) ),
	array( 'en' => 'Automatic Grinder Control LGC30XX', 'it' => 'Controllo automatico della rettificatrice LGC30XX', 'not' => array( 'Controllo automatico del molatore LGC30XX' ) ),
	array( 'en' => 'Profile Grinder Control PGC9400', 'it' => 'Controllo della rettificatrice per profili PGC9400', 'not' => array( 'Controllo rettificatrice di profilo PGC9400', 'Controllo rettificatrice profili PGC9400' ) ),
	array( 'en' => 'spalls', 'it' => 'scheggiature', 'not' => array( 'spalle', 'sfogliature' ) ),
	array( 'en' => 'surface separations', 'it' => 'distacchi superficiali', 'not' => array( 'separazioni di superficie' ) ),
	array( 'en' => 'blast furnace', 'it' => 'altoforno', 'not' => array( 'forno a scoppio', 'forno a pozzo', 'forno di esplosione' ) ),
	array( 'en' => 'Furnace & Blast Furnace Technology', 'it' => 'Tecnologia dei forni e degli altiforni', 'not' => array( 'Tecnologia di forni a fusione e forni a pozzo', 'Tecnologia del forno e dell’altoforno' ) ),
	array( 'en' => 'blast furnace automation', 'it' => 'automazione dell’altoforno', 'not' => array( 'automazione del forno a pozzo' ) ),
	array( 'en' => 'tap hole', 'it' => 'foro di colata', 'not' => array( 'foro del rubinetto', 'buco di spillatura' ) ),
	array( 'en' => 'clay gun', 'it' => 'cannone otturatore', 'not' => array( 'pistola di argilla', 'fucile per argilla' ) ),
	array( 'en' => 'strip', 'it' => 'nastro', 'not' => array( 'striscia', 'banda metallica' ) ),
	array( 'en' => 'Strip Lines', 'it' => 'Linee per nastri', 'not' => array( 'Linee di spellatura', 'Linee a strisce' ) ),
	array( 'en' => 'Cold & Hot Rolling Mills', 'it' => 'Laminatoi a freddo e a caldo', 'not' => array( 'Mulini di laminazione a freddo e a caldo' ) ),
	array( 'en' => '20-high / six-high mill', 'it' => 'laminatoio a 20 cilindri / a sei cilindri', 'not' => array( 'mulino a 20 cilindri', 'laminatoio a 20 alti' ) ),
	array( 'en' => 'cold pilger mill', 'it' => 'laminatoio a passo di pellegrino a freddo', 'not' => array( 'mulino pellegrino a freddo' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'it' => 'testurizzazione a scarica elettrica (EDT)', 'not' => array( 'texture a scarica elettrica' ) ),
	array( 'en' => 'texturing', 'it' => 'testurizzazione', 'not' => array( 'texture', 'strutturazione superficiale' ) ),
	array( 'en' => 'tin plating', 'it' => 'stagnatura', 'not' => array( 'placcatura di latta', 'stagnazione' ) ),
	array( 'en' => 'Press Technology & Hydroforming', 'it' => 'Tecnologia delle presse e idroformatura', 'not' => array( 'Tecnologia di pressatura e idroformatura' ) ),
	array( 'en' => 'Pipe Manufacturing', 'it' => 'Produzione di tubi', 'not' => array( 'Fabbricazione di tubature' ) ),
	array( 'en' => 'Paper & Plastic Industry', 'it' => 'Industria della carta e della plastica', 'not' => array( 'Industria cartaria e plastica' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'it' => 'Rulli per trasportatori e per cartiere', 'not' => array( 'Nastri trasportatori e rulli di carta', 'rulli di carta' ) ),
	array( 'en' => 'Handling Machines & Manipulators', 'it' => 'Macchine di movimentazione e manipolatori', 'not' => array( 'Macchine di gestione e manipolatori' ) ),
	array( 'en' => 'automated handling cells', 'it' => 'celle di movimentazione automatizzate', 'not' => array( 'celle di gestione automatica' ) ),
	array( 'en' => 'Automation and Drive Systems', 'it' => 'Sistemi di automazione e azionamento', 'not' => array( 'Automazione e sistemi di azionamento', 'Sistemi di automazione e guida' ) ),
	array( 'en' => 'Retrofit Modernization', 'it' => 'Retrofit e ammodernamento', 'not' => array( 'Modernizzazione di retrofit' ) ),
	array( 'en' => 'Test bay erection and modernization', 'it' => 'Allestimento e ammodernamento delle celle di prova', 'not' => array( 'Erezione e modernizzazione della baia di prova' ) ),
	array( 'en' => 'Robot application', 'it' => 'Applicazioni robotizzate', 'not' => array( 'Applicazione del robot' ) ),
	array( 'en' => 'Vibration absorbing cast', 'it' => 'Getto antivibrante', 'not' => array( 'Fusione che assorbe le vibrazioni' ) ),
	array( 'en' => 'Demagnetizing unit', 'it' => 'Smagnetizzatore', 'not' => array( 'Unità di demagnetizzazione' ) ),
	array( 'en' => 'eddy current technology', 'it' => 'tecnologia a correnti parassite', 'not' => array( 'tecnologia delle correnti vorticose', 'corrente di Eddy' ) ),
	array( 'en' => 'walking beam system', 'it' => 'sistema a travi mobili', 'not' => array( 'sistema a trave ambulante', 'sistema del raggio camminante' ) ),
	array( 'en' => 'Magnetizing system for permanent magnets', 'it' => 'Sistema di magnetizzazione per magneti permanenti', 'not' => array( 'Sistema magnetizzante di magneti fissi' ) ),
	array( 'en' => 'Brushing & Polishing Machines', 'it' => 'Macchine di spazzolatura e lucidatura', 'not' => array( 'Macchine per spazzolare e lucidare' ) ),
	array( 'en' => 'Precision Machining', 'it' => 'Lavorazioni di precisione', 'not' => array( 'Lavorazione di precisione', 'Macchinazione di precisione', 'macchinazione di precisione' ) ),
	array( 'en' => 'machine tools', 'it' => 'macchine utensili', 'not' => array( 'strumenti macchina', 'utensili da macchina' ) ),
	array( 'en' => 'Machine Tools and Special Machines', 'it' => 'Macchine utensili e macchine speciali', 'not' => array( 'Strumenti macchina e macchine speciali' ) ),
	array( 'en' => 'machining cell', 'it' => 'cella di lavorazione', 'not' => array( 'cella di macchinazione' ) ),
	array( 'en' => 'machinist', 'it' => 'operatore macchine utensili', 'not' => array( 'macchinista', 'meccanico di macchine' ) ),
	array( 'en' => 'boring', 'it' => 'alesatura', 'not' => array( 'foratura', 'noiatura' ) ),
	array( 'en' => 'horizontal boring machine', 'it' => 'alesatrice orizzontale', 'not' => array( 'macchina di alesatura orizzontale' ) ),
	array( 'en' => 'deep hole drilling', 'it' => 'foratura profonda', 'not' => array( 'trapanatura profonda', 'perforazione di buchi profondi' ) ),
	array( 'en' => 'gundrill', 'it' => 'punta a cannone', 'not' => array( 'trapano a pistola', 'punta a fucile' ) ),
	array( 'en' => 'gantry milling', 'it' => 'fresatura a portale', 'not' => array( 'fresatura gantry', 'molitura a portale' ) ),
	array( 'en' => 'gantry', 'it' => 'portale', 'not' => array( 'cavalletto', 'gantry' ) ),
	array( 'en' => '3-jaw chuck', 'it' => 'mandrino autocentrante a 3 griffe', 'not' => array( 'mandrino a 3 ganasce', 'mandrino a tre mascelle' ) ),
	array( 'en' => 'collet chuck', 'it' => 'mandrino a pinza', 'not' => array( 'mandrino a collare', 'mandrino a bussola' ) ),
	array( 'en' => 'motorized clamping', 'it' => 'bloccaggio motorizzato', 'not' => array( 'serraggio a motore' ) ),
	array( 'en' => 'custom fixturing', 'it' => 'attrezzature di bloccaggio su misura', 'not' => array( 'fissaggio personalizzato', 'attrezzaggio doganale' ) ),
	array( 'en' => 'in a single clamping', 'it' => 'in un unico serraggio', 'not' => array( 'in un singolo bloccaggio', 'in una sola morsa' ) ),
	array( 'en' => 'setup cycles', 'it' => 'cicli di attrezzaggio', 'not' => array( 'cicli di installazione', 'cicli di configurazione' ) ),
	array( 'en' => 'chip vacuum', 'it' => 'aspirazione dei trucioli', 'not' => array( 'vuoto del chip', 'aspiratore di patatine' ) ),
	array( 'en' => 'dial indicator', 'it' => 'comparatore', 'not' => array( 'indicatore a quadrante', 'indicatore di composizione' ) ),
	array( 'en' => 'gauging', 'it' => 'controllo dimensionale', 'not' => array( 'misurazione dimensionata', 'calibratura' ) ),
	array( 'en' => 'Tools and Tool Holders', 'it' => 'Utensili e portautensili', 'not' => array( 'Attrezzi e portautensili', 'Strumenti e porta strumenti' ) ),
	array( 'en' => 'Woodworking Tools and Saws', 'it' => 'Utensili per la lavorazione del legno e seghe', 'not' => array( 'Attrezzi per la lavorazione del legno e seghe' ) ),
	array( 'en' => 'Wheel Sets', 'it' => 'Sale montate', 'not' => array( 'Assali completi', 'Set di ruote' ) ),
	array( 'en' => 'Train Wheels', 'it' => 'Ruote ferroviarie', 'not' => array( 'Ruote del treno' ) ),
	array( 'en' => 'Electric Armatures', 'it' => 'Indotti elettrici', 'not' => array( 'Armature elettriche' ) ),
	array( 'en' => 'Turbine Rotors', 'it' => 'Rotori di turbina', 'not' => array( 'Rotori della turbina a vapore' ) ),
	array( 'en' => 'Pump Impellers', 'it' => 'Giranti di pompe', 'not' => array( 'Rotori di pompa', 'Eliche di pompe' ) ),
	array( 'en' => 'tapered roller bearing', 'it' => 'cuscinetto a rulli conici', 'not' => array( 'cuscinetto a rulli affusolati' ) ),
	array( 'en' => 'anchoring', 'it' => 'ancoraggio', 'not' => array( 'ancoraggio al suolo' ) ),
	array( 'en' => 'bore axis alignment', 'it' => 'allineamento dell’asse del foro', 'not' => array( 'allineamento dell’asse di alesaggio' ) ),
	array( 'en' => 'ultra-stable design', 'it' => 'struttura ultrastabile', 'not' => array( 'design ultra stabile', 'disegno ultrastabile' ) ),
	array( 'en' => 'stand-alone machine', 'it' => 'macchina indipendente', 'not' => array( 'macchina solitaria', 'macchina a sé stante' ) ),
	array( 'en' => 'single bay', 'it' => 'cella singola', 'not' => array( 'baia singola', 'campata singola' ) ),
	array( 'en' => 'single station / multi station', 'it' => 'stazione singola / multistazione', 'not' => array( 'posto singolo / posto multiplo' ) ),
	array( 'en' => 'fixed stations', 'it' => 'stazioni fisse', 'not' => array( 'postazioni fissate' ) ),
	array( 'en' => 'mobile carousels', 'it' => 'caroselli mobili', 'not' => array( 'giostre mobili' ) ),
	array( 'en' => 'Aerospace & industrials', 'it' => 'Aerospaziale e industriale', 'not' => array( 'Aeronautico e industriale', 'Aerospaziale e industrie' ) ),
	array( 'en' => 'aerospace', 'it' => 'aerospaziale', 'not' => array( 'aeronautico', 'aereo' ) ),
	array( 'en' => 'Aero, defense & space', 'it' => 'Aerospaziale, difesa e spazio', 'not' => array( 'Aereo, difesa e spazio' ) ),
	array( 'en' => 'Aerospace featuring Bauer', 'it' => 'Aerospaziale con tecnologia Bauer', 'not' => array( 'Aerospaziale con Bauer', 'Aerospaziale in primo piano Bauer' ) ),
	array( 'en' => 'Test stands featuring Bauer', 'it' => 'Banchi di prova con tecnologia Bauer', 'not' => array( 'Banchi di prova con Bauer' ) ),
	array( 'en' => 'test benches / test stands', 'it' => 'banchi di prova', 'not' => array( 'banchi di collaudo', 'banconi di prova' ) ),
	array( 'en' => 'Testing Systems', 'it' => 'Sistemi di prova', 'not' => array( 'Sistemi di collaudo', 'Sistemi di testing' ) ),
	array( 'en' => 'Test Systems', 'it' => 'Sistemi di prova', 'not' => array( 'Sistemi di test' ) ),
	array( 'en' => 'testing', 'it' => 'collaudo', 'not' => array( 'testing', 'testaggio' ) ),
	array( 'en' => 'special test facilities', 'it' => 'impianti di prova speciali', 'not' => array( 'strutture speciali di test' ) ),
	array( 'en' => 'actuation systems', 'it' => 'sistemi di attuazione', 'not' => array( 'sistemi di attivazione' ) ),
	array( 'en' => 'Actuation & landing gear test', 'it' => 'Banchi di prova per attuatori e carrelli di atterraggio', 'not' => array( 'Prova di attuazione e carrello d’atterraggio' ) ),
	array( 'en' => 'landing gear systems', 'it' => 'sistemi di carrello di atterraggio', 'not' => array( 'sistemi di atterraggio' ) ),
	array( 'en' => 'cargo loading systems', 'it' => 'sistemi di carico merci', 'not' => array( 'sistemi di caricamento del cargo' ) ),
	array( 'en' => 'power drive units', 'it' => 'unità di azionamento', 'not' => array( 'unità di potenza motrice' ) ),
	array( 'en' => 'lube & scavenge pumps', 'it' => 'pompe di mandata e recupero olio', 'not' => array( 'pompe di lubrificazione e spazzamento' ) ),
	array( 'en' => 'lubrication', 'it' => 'lubrificazione', 'not' => array( 'oliatura' ) ),
	array( 'en' => 'turbine & jet engine balancing', 'it' => 'equilibratura di turbine e motori a reazione', 'not' => array( 'bilanciamento di turbina e motore a getto' ) ),
	array( 'en' => 'fluid power', 'it' => 'oleodinamica', 'not' => array( 'fluidodinamica', 'potenza fluidica', 'potenza fluida', 'Fluidodinamica', 'Potenza fluidica' ) ),
	array( 'en' => 'Rotary Motion', 'it' => 'Movimento rotatorio', 'not' => array( 'Moto girevole' ) ),
	array( 'en' => 'Valves', 'it' => 'Valvole', 'not' => array( 'Saracinesche' ) ),
	array( 'en' => 'Multi-section gear pump test', 'it' => 'Prova di pompe a ingranaggi multisezione', 'not' => array( 'Prova di pompa a ingranaggi multi-sezione' ) ),
	array( 'en' => 'Axial piston pump test', 'it' => 'Prova di pompe a pistoni assiali', 'not' => array( 'Prova di pompa a pistoni assiale' ) ),
	array( 'en' => 'hydraulic pilot', 'it' => 'pilotaggio idraulico', 'not' => array( 'pilota idraulico' ) ),
	array( 'en' => 'load sense signal', 'it' => 'segnale load sensing', 'not' => array( 'segnale di rilevamento del carico' ) ),
	array( 'en' => 'thrust force / pullback force', 'it' => 'forza di spinta / forza di tiro', 'not' => array( 'forza di propulsione / forza di ritiro' ) ),
	array( 'en' => 'push and pull', 'it' => 'spinta e tiro', 'not' => array( 'spingi e tira' ) ),
	array( 'en' => 'drift', 'it' => 'deriva', 'not' => array( 'spostamento', 'scorrimento' ) ),
	array( 'en' => 'stem stickiness', 'it' => 'incollamento dello stelo', 'not' => array( 'appiccicosità del gambo' ) ),
	array( 'en' => 'debonding', 'it' => 'distacco', 'not' => array( 'sbonding', 'de-incollaggio' ) ),
	array( 'en' => 'snubber', 'it' => 'smorzatore', 'not' => array( 'smorzatore di urti' ) ),
	array( 'en' => 'Hydraulic & electrical test stands', 'it' => 'Banchi di prova idraulici ed elettrici', 'not' => array( 'Banchi di prova idraulico e elettrico' ) ),
	array( 'en' => 'Off-highway & mobile', 'it' => 'Macchine off-highway e mobili', 'not' => array( 'Fuoristrada e mobile', 'Macchine fuoristrada e mobili' ) ),
	array( 'en' => 'off-highway', 'it' => 'off-highway', 'not' => array( 'fuoristrada', 'fuori strada' ) ),
	array( 'en' => 'Mobile Equipment', 'it' => 'Macchine mobili', 'not' => array( 'Equipaggiamento mobile' ) ),
	array( 'en' => 'implements', 'it' => 'attrezzature', 'not' => array( 'implementi', 'implementazioni' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'it' => 'Attrezzature - Fine linea', 'not' => array( 'Implementazioni - Fine linea', 'Implementi - Fine linea' ) ),
	array( 'en' => 'excavator', 'it' => 'escavatore', 'not' => array( 'scavatrice', 'scavatore' ) ),
	array( 'en' => 'backhoe', 'it' => 'retroescavatore', 'not' => array( 'zappa posteriore', 'escavatore all’indietro' ) ),
	array( 'en' => 'motor grader', 'it' => 'motolivellatrice', 'not' => array( 'livellatrice a motore', 'grader stradale' ) ),
	array( 'en' => 'blade', 'it' => 'lama', 'not' => array( 'coltello', 'paletta' ) ),
	array( 'en' => 'wheel loader', 'it' => 'pala gommata', 'not' => array( 'caricatore a ruote', 'caricatrice a ruote' ) ),
	array( 'en' => 'Wheel Loaders', 'it' => 'Pale gommate', 'not' => array( 'Caricatori a ruote' ) ),
	array( 'en' => 'feller buncher', 'it' => 'abbattitrice-accumulatrice', 'not' => array( 'tagliatore raggruppatore' ) ),
	array( 'en' => 'combine', 'it' => 'mietitrebbia', 'not' => array( 'combinata', 'mietitrebbiatrice combinata' ) ),
	array( 'en' => 'Combine draper header', 'it' => 'Testata draper per mietitrebbie', 'not' => array( 'Testata di raccolta per mietitrebbie', 'Intestazione del drappo' ) ),
	array( 'en' => 'draper header', 'it' => 'testata draper', 'not' => array( 'testata a drappo', 'intestazione draper' ) ),
	array( 'en' => 'Combine belt', 'it' => 'Cinghia per mietitrebbia', 'not' => array( 'Cintura di mietitrebbia' ) ),
	array( 'en' => 'baler', 'it' => 'imballatrice', 'not' => array( 'imballatore', 'pressa-raccoglitrice' ) ),
	array( 'en' => 'hay mower', 'it' => 'falciatrice', 'not' => array( 'tosaerba', 'falciatrice d’erba' ) ),
	array( 'en' => 'sprayers', 'it' => 'irroratrici', 'not' => array( 'spruzzatori', 'nebulizzatori' ) ),
	array( 'en' => 'PTO (power take-off)', 'it' => 'PTO (presa di forza)', 'not' => array( 'PTO (decollo di potenza)' ) ),
	array( 'en' => 'boring drill (HDD)', 'it' => 'perforatrice orizzontale teleguidata', 'not' => array( 'trapano noioso' ) ),
	array( 'en' => 'mudding system (HDD)', 'it' => 'impianto per i fanghi di perforazione', 'not' => array( 'sistema di fangatura' ) ),
	array( 'en' => 'marine', 'it' => 'navale', 'not' => array( 'marino', 'marittimo di mare' ) ),
	array( 'en' => 'non-destructive testing', 'it' => 'controlli non distruttivi', 'not' => array( 'prove non distruttive', 'test non distruttivo' ) ),
	array( 'en' => 'NDT inspection', 'it' => 'controlli non distruttivi', 'not' => array( 'ispezione NDT', 'ispezione non distruttiva' ) ),
	array( 'en' => 'audit stations', 'it' => 'stazioni di verifica', 'not' => array( 'stazioni di revisione contabile', 'stazioni di audit' ) ),
	array( 'en' => 'health checks', 'it' => 'controlli dello stato di salute', 'not' => array( 'assegni sanitari', 'controlli di salute' ) ),
	array( 'en' => 'machine health', 'it' => 'stato di salute delle macchine', 'not' => array( 'salute della macchina', 'sanità della macchina' ) ),
	array( 'en' => 'Machine Analytics', 'it' => 'Analisi dei dati di macchina', 'not' => array( 'Analitiche macchina', 'Analisi dei dati macchina' ) ),
	array( 'en' => 'AI-driven machine analytics', 'it' => 'Analisi dei dati di macchina basata sull’IA', 'not' => array( 'Analitiche macchina basate sull’IA', 'Analisi dati macchina guidata dall’IA' ) ),
	array( 'en' => 'analytics', 'it' => 'analisi dei dati', 'not' => array( 'analitiche', 'analitica' ) ),
	array( 'en' => 'actionable insights', 'it' => 'informazioni su cui intervenire', 'not' => array( 'approfondimenti azionabili', 'intuizioni attuabili' ) ),
	array( 'en' => 'expert insights', 'it' => 'approfondimenti degli esperti', 'not' => array( 'intuizioni esperte' ) ),
	array( 'en' => 'insights', 'it' => 'approfondimenti', 'not' => array( 'intuizioni', 'intuizione', 'visioni' ) ),
	array( 'en' => 'failure rates', 'it' => 'tassi di guasto', 'not' => array( 'tassi di fallimento', 'percentuali di fallimento' ) ),
	array( 'en' => 'traceable tests', 'it' => 'prove tracciabili', 'not' => array( 'test rintracciabili' ) ),
	array( 'en' => 'validate performance', 'it' => 'validare le prestazioni', 'not' => array( 'convalidare la performance' ) ),
	array( 'en' => 'defensible', 'it' => 'difendibile', 'not' => array( 'difensibile' ) ),
	array( 'en' => 'reportable', 'it' => 'soggetto a segnalazione', 'not' => array( 'riportabile', 'rapportabile' ) ),
	array( 'en' => 'Calibration & Testing', 'it' => 'Taratura e collaudo', 'not' => array( 'Taratura e prova', 'Calibrazione e test' ) ),
	array( 'en' => 'Certification Documentation', 'it' => 'Documentazione di certificazione', 'not' => array( 'Documentazione e certificazione' ) ),
	array( 'en' => 'commissioning', 'it' => 'messa in servizio', 'not' => array( 'commissionamento', 'incarico' ) ),
	array( 'en' => 'obsolescence management', 'it' => 'gestione dell’obsolescenza', 'not' => array( 'amministrazione dell’obsolescenza' ) ),
	array( 'en' => 'maintenance contracts', 'it' => 'contratti di manutenzione', 'not' => array( 'contratti manutentivi' ) ),
	array( 'en' => 'Maintenance and Service Plan Contracts', 'it' => 'Contratti di piani di manutenzione e assistenza', 'not' => array( 'Contratti di manutenzione e assistenza' ) ),
	array( 'en' => 'extended warranties', 'it' => 'garanzie estese', 'not' => array( 'garanzie prolungate', 'garanzie allungate' ) ),
	array( 'en' => 'warranty coverage', 'it' => 'copertura in garanzia', 'not' => array( 'assicurazione della garanzia', 'copertura assicurativa' ) ),
	array( 'en' => 'field service', 'it' => 'assistenza in loco', 'not' => array( 'servizio sul campo', 'assistenza di campo' ) ),
	array( 'en' => 'Field service requests', 'it' => 'Richieste di assistenza in loco', 'not' => array( 'Richieste di servizio sul campo' ) ),
	array( 'en' => 'field agents', 'it' => 'tecnici in loco', 'not' => array( 'agenti di campo', 'agenti sul terreno' ) ),
	array( 'en' => 'service professional', 'it' => 'tecnico dell’assistenza', 'not' => array( 'professionista del servizio' ) ),
	array( 'en' => 'Support Services', 'it' => 'Servizi di assistenza', 'not' => array( 'Servizi di supporto', 'Servizi di sostegno' ) ),
	array( 'en' => 'Service & support', 'it' => 'Servizi e assistenza', 'not' => array( 'Servizio e assistenza', 'Servizio e supporto' ) ),
	array( 'en' => 'Service & Support Products', 'it' => 'Prodotti per servizi e assistenza', 'not' => array( 'Prodotti di servizio e supporto' ) ),
	array( 'en' => 'support request', 'it' => 'richiesta di assistenza', 'not' => array( 'domanda di supporto' ) ),
	array( 'en' => 'service ticket', 'it' => 'ticket di assistenza', 'not' => array( 'biglietto di servizio', 'tagliando di assistenza' ) ),
	array( 'en' => 'Spare parts marketplace', 'it' => 'Marketplace di ricambi', 'not' => array( 'Mercato dei pezzi di ricambio' ) ),
	array( 'en' => 'Spare Parts', 'it' => 'Ricambi', 'not' => array( 'Parti di ricambio staccate' ) ),
	array( 'en' => 'Engineering Services', 'it' => 'Servizi di ingegneria', 'not' => array( 'Servizi ingegneristici' ) ),
	array( 'en' => 'Engineering and OBD consulting', 'it' => 'Consulenza ingegneristica e OBD', 'not' => array( 'Consulenza di ingegneria e OBD' ) ),
	array( 'en' => 'OBD consulting & training', 'it' => 'consulenza e formazione OBD', 'not' => array( 'consulenza e addestramento OBD' ) ),
	array( 'en' => 'Training courses', 'it' => 'Corsi di formazione', 'not' => array( 'Corsi di addestramento', 'Corsi formativi' ) ),
	array( 'en' => 'learning management system (LMS)', 'it' => 'sistema di gestione dell’apprendimento (LMS)', 'not' => array( 'sistema di amministrazione dell’apprendimento' ) ),
	array( 'en' => 'Become a support partner', 'it' => 'Diventi un partner di assistenza', 'not' => array( 'Diventi partner di supporto', 'Diventa un partner di assistenza' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'it' => 'rigeneratori e ricostruttori', 'not' => array( 'rifabbricanti e ricostruttori' ) ),
	array( 'en' => 'remarketers', 'it' => 'rivenditori', 'not' => array( 'rimercatori' ) ),
	array( 'en' => 'deployment', 'it' => 'implementazione', 'not' => array( 'dispiegamento', 'schieramento' ) ),
	array( 'en' => 'uptime across systems', 'it' => 'disponibilità operativa dei sistemi', 'not' => array( 'tempo di attività attraverso i sistemi' ) ),
	array( 'en' => 'downtime', 'it' => 'tempi di fermo', 'not' => array( 'tempo morto', 'fermo macchina di inattività' ) ),
	array( 'en' => 'turnkey', 'it' => 'chiavi in mano', 'not' => array( 'chiave in mano', 'a chiave girata' ) ),
	array( 'en' => 'capital equipment', 'it' => 'beni strumentali', 'not' => array( 'equipaggiamento capitale', 'attrezzature di capitale' ) ),
	array( 'en' => 'production equipment', 'it' => 'impianti di produzione', 'not' => array( 'attrezzatura di produzione', 'equipaggiamento produttivo' ) ),
	array( 'en' => 'factory floor', 'it' => 'reparto produttivo', 'not' => array( 'pavimento della fabbrica', 'piano di fabbrica' ) ),
	array( 'en' => 'hazardous area', 'it' => 'area pericolosa', 'not' => array( 'zona rischiosa' ) ),
	array( 'en' => 'hazardous areas', 'it' => 'aree pericolose', 'not' => array( 'zone rischiose' ) ),
	array( 'en' => 'pinches & bruises', 'it' => 'schiacciamenti e contusioni', 'not' => array( 'pizzichi e lividi' ) ),
	array( 'en' => 'burst proof protection', 'it' => 'protezione antiscoppio', 'not' => array( 'protezione a prova di scoppio', 'protezione antiesplosione' ) ),
	array( 'en' => 'exhaust extraction system', 'it' => 'impianto di aspirazione dei gas di scarico', 'not' => array( 'sistema di estrazione di scarico' ) ),
	array( 'en' => 'EMC darkroom', 'it' => 'camera schermata EMC', 'not' => array( 'camera oscura EMC', 'stanza buia EMC' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'it' => 'Direttiva Macchine 2006/42/CE', 'not' => array( 'Direttiva sui macchinari 2006/42/EC' ) ),
	array( 'en' => 'higher-level control system', 'it' => 'sistema di controllo di livello superiore', 'not' => array( 'sistema di controllo di alto livello' ) ),
	array( 'en' => 'controls', 'it' => 'sistemi di controllo', 'not' => array( 'controlli', 'verifiche' ) ),
	array( 'en' => 'control', 'it' => 'controllo', 'not' => array( 'comando di processo' ) ),
	array( 'en' => 'process recipe', 'it' => 'ricetta di processo', 'not' => array( 'ricetta del procedimento' ) ),
	array( 'en' => 'adaptive speed control', 'it' => 'regolazione adattiva della velocità', 'not' => array( 'controllo di velocità adattabile' ) ),
	array( 'en' => 'infinitely variable', 'it' => 'a variazione continua', 'not' => array( 'infinitamente variabile' ) ),
	array( 'en' => 'seamless link', 'it' => 'collegamento senza interruzioni', 'not' => array( 'collegamento perfetto', 'legame impeccabile' ) ),
	array( 'en' => 'represent', 'it' => 'riprodurre', 'not' => array( 'rappresentare il processo' ) ),
	array( 'en' => 'aperture plate', 'it' => 'piastra a diaframma', 'not' => array( 'piatto di apertura' ) ),
	array( 'en' => 'Detection Focus', 'it' => 'Focus di rilevamento', 'not' => array( 'Fuoco di rilevazione' ) ),
	array( 'en' => 'fully loaded test', 'it' => 'prova a pieno carico', 'not' => array( 'test completamente caricato' ) ),
	array( 'en' => 'cushion testing', 'it' => 'prove di ammortizzamento', 'not' => array( 'test del cuscino', 'prova di cuscinetto' ) ),
	array( 'en' => 'high production / high-volume production', 'it' => 'produzione elevata / produzione ad alto volume', 'not' => array( 'produzione alta / produzione di alto volume' ) ),
	array( 'en' => 'high-mix, low-volume', 'it' => 'alta varietà, basso volume', 'not' => array( 'mix elevato, volume basso' ) ),
	array( 'en' => 'volume flexibility', 'it' => 'flessibilità produttiva', 'not' => array( 'flessibilità del volume' ) ),
	array( 'en' => 'production output', 'it' => 'volumi di produzione', 'not' => array( 'produttività', 'output di produzione' ) ),
	array( 'en' => 'throughput', 'it' => 'capacità produttiva', 'not' => array( 'produttività', 'rendimento di passaggio' ) ),
	array( 'en' => 'footprint', 'it' => 'ingombro', 'not' => array( 'impronta', 'orma' ) ),
	array( 'en' => 'discrete industries', 'it' => 'industrie manifatturiere discrete', 'not' => array( 'industrie discrete', 'settori discreti' ) ),
	array( 'en' => 'operations', 'it' => 'operations', 'not' => array( 'operazioni chirurgiche' ) ),
	array( 'en' => 'applications', 'it' => 'applicazioni', 'not' => array( 'candidature', 'domande di impiego' ) ),
	array( 'en' => 'features', 'it' => 'caratteristiche', 'not' => array( 'funzionalità del prodotto' ) ),
	array( 'en' => 'performance', 'it' => 'prestazioni', 'not' => array( 'performance aziendale' ) ),
	array( 'en' => 'responsive', 'it' => 'reattivo', 'not' => array( 'sensibile', 'responsivo' ) ),
	array( 'en' => 'tariffs', 'it' => 'dazi', 'not' => array( 'tariffe telefoniche', 'tariffari' ) ),
	array( 'en' => 'landed cost model', 'it' => 'modello del costo a destino', 'not' => array( 'modello di costo sbarcato' ) ),
	array( 'en' => 'site visit', 'it' => 'sopralluogo', 'not' => array( 'visita del sito', 'visita al sito web' ) ),
	array( 'en' => 'Labour & Travel', 'it' => 'Manodopera e trasferta', 'not' => array( 'Lavoro e viaggio', 'Manodopera e viaggi' ) ),
	array( 'en' => 'Deliverables', 'it' => 'Deliverable', 'not' => array( 'Consegnabili', 'Risultati consegnabili' ) ),
	array( 'en' => 'Standardization at scale', 'it' => 'Standardizzazione su larga scala', 'not' => array( 'Standardizzazione in scala' ) ),
	array( 'en' => 'built to last', 'it' => 'costruito per durare', 'not' => array( 'fabbricato per durare' ) ),
	array( 'en' => 'patented', 'it' => 'brevettato', 'not' => array( 'patentato' ) ),
	array( 'en' => 'About', 'it' => 'L’azienda', 'not' => array( 'Riguardo a noi', 'Informazioni' ) ),
	array( 'en' => 'Company', 'it' => 'Azienda', 'not' => array( 'Compagnia', 'Ditta' ) ),
	array( 'en' => 'Who we are', 'it' => 'Chi siamo', 'not' => array( 'Chi siamo noi' ) ),
	array( 'en' => 'Leadership', 'it' => 'Dirigenza', 'not' => array( 'Direzione di comando' ) ),
	array( 'en' => 'Leadership team', 'it' => 'Team dirigenziale', 'not' => array( 'Team di leadership', 'Squadra di leadership' ) ),
	array( 'en' => 'Board Member', 'it' => 'Membro del consiglio di amministrazione', 'not' => array( 'Membro della tavola', 'Membro di bordo' ) ),
	array( 'en' => 'President', 'it' => 'Presidente', 'not' => array( 'Preside' ) ),
	array( 'en' => 'Principal', 'it' => 'Titolare', 'not' => array( 'Principale', 'Principio' ) ),
	array( 'en' => 'Corporate Roles', 'it' => 'Ruoli aziendali', 'not' => array( 'Ruoli corporativi' ) ),
	array( 'en' => 'associate attorney', 'it' => 'avvocato associato', 'not' => array( 'procuratore associato', 'attorney associato' ) ),
	array( 'en' => 'Corporate information', 'it' => 'Informazioni aziendali', 'not' => array( 'Informazione corporativa' ) ),
	array( 'en' => 'Careers', 'it' => 'Carriere', 'not' => array( 'Lavora con noi', 'Posti di lavoro' ) ),
	array( 'en' => 'opportunities', 'it' => 'opportunità', 'not' => array( 'occasioni', 'opportunismi' ) ),
	array( 'en' => 'peers', 'it' => 'colleghi', 'not' => array( 'pari', 'paritetici' ) ),
	array( 'en' => 'high-performance teams', 'it' => 'team ad alte prestazioni', 'not' => array( 'squadre ad alta performance' ) ),
	array( 'en' => 'like-minded companies', 'it' => 'aziende con la stessa visione', 'not' => array( 'compagnie della stessa mente' ) ),
	array( 'en' => 'mental health care', 'it' => 'assistenza per la salute mentale', 'not' => array( 'cura mentale sanitaria' ) ),
	array( 'en' => 'disability insurance', 'it' => 'assicurazione per invalidità', 'not' => array( 'assicurazione di disabilità' ) ),
	array( 'en' => 'Imprint', 'it' => 'Note legali', 'not' => array( 'Impronta', 'Stampa', 'Colophon' ) ),
	array( 'en' => 'Terms', 'it' => 'Condizioni d’uso', 'not' => array( 'Termini', 'Termini e condizioni di utilizzo' ) ),
	array( 'en' => 'Privacy Policy', 'it' => 'Informativa sulla privacy', 'not' => array( 'Politica di privacy', 'Politica sulla riservatezza' ) ),
	array( 'en' => 'Trademarks', 'it' => 'Marchi registrati', 'not' => array( 'Marchi di fabbrica', 'Segni distintivi' ) ),
	array( 'en' => 'brands', 'it' => 'marchi', 'not' => array( 'marche', 'griffe' ) ),
	array( 'en' => 'Affiliates', 'it' => 'Società affiliate', 'not' => array( 'Partner', 'Affiliati commerciali' ) ),
	array( 'en' => 'branch', 'it' => 'filiale', 'not' => array( 'ramo', 'succursale di albero' ) ),
	array( 'en' => 'Registered office', 'it' => 'Sede legale', 'not' => array( 'Ufficio registrato', 'Sede registrata' ) ),
	array( 'en' => 'Register', 'it' => 'Registro', 'not' => array( 'Registrazione', 'Iscriviti' ) ),
	array( 'en' => 'Netherlands', 'it' => 'Paesi Bassi', 'not' => array( 'Olanda', 'Netherlands' ) ),
	array( 'en' => 'England', 'it' => 'Inghilterra', 'not' => array( 'England' ) ),
	array( 'en' => 'West Flanders', 'it' => 'Fiandre Occidentali', 'not' => array( 'Flandria Ovest', 'Fiandra dell’Ovest' ) ),
	array( 'en' => 'Poland', 'it' => 'Polonia', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Bristol', 'it' => 'Bristol', 'not' => array() ),
	array( 'en' => 'Locations', 'it' => 'Sedi', 'not' => array( 'Posizioni', 'Località geografiche' ) ),
	array( 'en' => 'global locations', 'it' => 'sedi nel mondo', 'not' => array( 'posizioni globali', 'località globali' ) ),
	array( 'en' => 'home countries', 'it' => 'paesi in cui abbiamo sede', 'not' => array( 'paesi di casa', 'paesi natali' ) ),
	array( 'en' => 'Industries served', 'it' => 'Settori serviti', 'not' => array( 'Industrie servite' ) ),
	array( 'en' => 'industries', 'it' => 'settori', 'not' => array( 'industrie manifatturiere' ) ),
	array( 'en' => 'Medical', 'it' => 'Medicale', 'not' => array( 'Medico', 'Sanitario' ) ),
	array( 'en' => 'Supply chain requirements', 'it' => 'Requisiti della catena di fornitura', 'not' => array( 'Requisiti della catena di approvvigionamento', 'Requisiti della filiera' ) ),
	array( 'en' => 'Supplier portal', 'it' => 'Portale fornitori', 'not' => array( 'Portale del fornitore' ) ),
	array( 'en' => 'Accessibility statement', 'it' => 'Dichiarazione di accessibilità', 'not' => array( 'Affermazione di accessibilità' ) ),
	array( 'en' => 'WCAG four principles', 'it' => 'i quattro principi WCAG', 'not' => array( 'quattro principi del WCAG' ) ),
	array( 'en' => 'Email Disclosure', 'it' => 'Informativa sulle e-mail', 'not' => array( 'Divulgazione e-mail', 'Rivelazione di posta' ) ),
	array( 'en' => 'personal information / personal data', 'it' => 'dati personali', 'not' => array( 'informazioni personali', 'dati della persona' ) ),
	array( 'en' => 'For Immediate Release', 'it' => 'Per diffusione immediata', 'not' => array( 'Per rilascio immediato', 'Per pubblicazione immediata' ) ),
	array( 'en' => 'press release', 'it' => 'comunicato stampa', 'not' => array( 'rilascio di stampa', 'comunicazione stampa' ) ),
	array( 'en' => 'Press', 'it' => 'Comunicati stampa', 'not' => array( 'Stampa', 'Pressa' ) ),
	array( 'en' => 'events & conferences', 'it' => 'eventi e conferenze', 'not' => array( 'avvenimenti e conferenze' ) ),
	array( 'en' => 'Editorial Contacts', 'it' => 'Contatti editoriali', 'not' => array( 'Contatti redazionali di stampa' ) ),
	array( 'en' => 'WHEREAS', 'it' => 'PREMESSO CHE', 'not' => array( 'LADDOVE', 'MENTRE' ) ),
	array( 'en' => 'RECITALS', 'it' => 'PREMESSE', 'not' => array( 'RECITAZIONI', 'CONSIDERANDI' ) ),
	array( 'en' => 'Exhibit', 'it' => 'Allegato', 'not' => array( 'Esibizione', 'Mostra' ) ),
	array( 'en' => 'Section', 'it' => 'Articolo', 'not' => array( 'Sezione di legge' ) ),
	array( 'en' => 'Work Product', 'it' => 'Prodotto del Lavoro', 'not' => array( 'Prodotto di lavoro', 'Opera lavorativa' ) ),
	array( 'en' => 'Ascential Indemnity', 'it' => 'Manleva di Ascential', 'not' => array( 'Indennità Ascential', 'Indennizzo di Ascential' ) ),
	array( 'en' => 'Date:', 'it' => 'Data:', 'not' => array( 'Datato:' ) ),
	array( 'en' => 'Name:', 'it' => 'Nome:', 'not' => array( 'Nome e cognome:' ) ),
	array( 'en' => 'is now', 'it' => 'ora è', 'not' => array( 'è ora', 'adesso è' ) ),
	array( 'en' => 'Introducing', 'it' => 'Presentiamo', 'not' => array( 'Presentazione', 'Introducendo' ) ),
	array( 'en' => 'Featuring:', 'it' => 'Con:', 'not' => array( 'In primo piano:', 'Caratterizzato da:' ) ),
	array( 'en' => 'Powered by', 'it' => 'Tecnologia di', 'not' => array( 'Alimentato da', 'Potenziato da' ) ),
	array( 'en' => 'Explore', 'it' => 'Esplori', 'not' => array( 'Esplora', 'Esplorare' ) ),
	array( 'en' => 'Explore the Catalog', 'it' => 'Esplori il catalogo', 'not' => array( 'Esplora il catalogo', 'Esplorazione del catalogo' ) ),
	array( 'en' => 'Browse catalog', 'it' => 'Sfogli il catalogo', 'not' => array( 'Sfoglia il catalogo', 'Naviga catalogo', 'Catalogo' ) ),
	array( 'en' => 'Browse all resources', 'it' => 'Sfogli tutte le risorse', 'not' => array( 'Sfoglia tutte le risorse', 'Naviga tutte le risorse' ) ),
	array( 'en' => 'Product catalog', 'it' => 'Catalogo prodotti', 'not' => array( 'Catalogo di prodotto' ) ),
	array( 'en' => 'Speak with an expert', 'it' => 'Parli con un esperto', 'not' => array( 'Parla con un esperto', 'Parlare con un esperto' ) ),
	array( 'en' => 'Speak to an expert now', 'it' => 'Parli subito con un esperto', 'not' => array( 'Parli con un esperto ora', 'Parla con un esperto adesso' ) ),
	array( 'en' => 'Request a demo', 'it' => 'Richieda una demo', 'not' => array( 'Richiedi una demo', 'Richiesta di demo' ) ),
	array( 'en' => 'Get a Quote', 'it' => 'Richieda un preventivo', 'not' => array( 'Richiedi un preventivo', 'Ottieni un preventivo' ) ),
	array( 'en' => 'Contact us', 'it' => 'Ci contatti', 'not' => array( 'Contattaci', 'Contatta noi' ) ),
	array( 'en' => 'Learn more', 'it' => 'Scopra di più', 'not' => array( 'Scopri di più', 'Imparare di più' ) ),
	array( 'en' => 'Read More', 'it' => 'Per saperne di più', 'not' => array( 'Leggi di più', 'Legga di più' ) ),
	array( 'en' => 'Read the article', 'it' => 'Legga l’articolo', 'not' => array( 'Leggi l’articolo', 'Leggere l’articolo' ) ),
	array( 'en' => 'Read announcement', 'it' => 'Legga l’annuncio', 'not' => array( 'Leggi l’annuncio' ) ),
	array( 'en' => 'See all press', 'it' => 'Tutti i comunicati stampa', 'not' => array( 'Vedi tutta la stampa', 'Vedi tutti i comunicati' ) ),
	array( 'en' => 'Download', 'it' => 'Scarichi', 'not' => array( 'Scarica', 'Scaricamento', 'Download del file' ) ),
	array( 'en' => 'Search', 'it' => 'Ricerca', 'not' => array( 'Cerca', 'Ricercare' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'it' => 'Ricerca su ascentialtech.com', 'not' => array( 'Ricerca in ascentialtech.com', 'Cercando ascentialtech.com' ) ),
	array( 'en' => 'Play', 'it' => 'Riproduci', 'not' => array( 'Gioca', 'Suona', 'Giocare' ) ),
	array( 'en' => 'Listen to this article', 'it' => 'Ascolti questo articolo', 'not' => array( 'Ascolta questo articolo' ) ),
	array( 'en' => 'Read or listen to the blog', 'it' => 'Legga o ascolti il blog', 'not' => array( 'Leggi o ascolta il blog' ) ),
	array( 'en' => 'N chapters', 'it' => 'capitoli', 'not' => array( 'capitolo' ) ),
	array( 'en' => 'Share / Copy link / Email', 'it' => 'Condivida / Copia link / E-mail', 'not' => array( 'Spartisci / Copia collegamento' ) ),
	array( 'en' => 'Connect on LinkedIn', 'it' => 'Si colleghi su LinkedIn', 'not' => array( 'Connettiti su LinkedIn', 'Collegati su LinkedIn' ) ),
	array( 'en' => 'Skip to content', 'it' => 'Vai al contenuto', 'not' => array( 'Salta al contenuto', 'Salta contenuto' ) ),
	array( 'en' => 'Resources', 'it' => 'Risorse', 'not' => array( 'Ricorsi', 'Mezzi' ) ),
	array( 'en' => 'Resource Hub', 'it' => 'Hub delle risorse', 'not' => array( 'Hub risorse', 'Centro risorse' ) ),
	array( 'en' => 'Resources hub', 'it' => 'Hub delle risorse', 'not' => array( 'Hub risorse', 'Polo di risorse' ) ),
	array( 'en' => 'Visit hub', 'it' => 'Visiti l’hub', 'not' => array( 'Visita l’hub' ) ),
	array( 'en' => 'Brochures', 'it' => 'Brochure', 'not' => array( 'Opuscoli', 'Dépliant' ) ),
	array( 'en' => 'eBooks', 'it' => 'eBook', 'not' => array( 'Libri elettronici', 'E-libri' ) ),
	array( 'en' => 'Webinars', 'it' => 'Webinar', 'not' => array( 'Seminari web' ) ),
	array( 'en' => 'Videos', 'it' => 'Video', 'not' => array( 'Filmati' ) ),
	array( 'en' => 'Podcasts', 'it' => 'Podcast', 'not' => array( 'Podcasts' ) ),
	array( 'en' => 'Whitepapers', 'it' => 'Whitepaper', 'not' => array( 'Libri bianchi', 'Carte bianche' ) ),
	array( 'en' => 'Certifications', 'it' => 'Certificazioni', 'not' => array( 'Certificati' ) ),
	array( 'en' => 'News', 'it' => 'Notizie', 'not' => array( 'Novità di stampa' ) ),
	array( 'en' => 'Latest news & insights', 'it' => 'Ultime notizie e approfondimenti', 'not' => array( 'Ultime notizie e intuizioni' ) ),
	array( 'en' => 'Blog', 'it' => 'Blog', 'not' => array( 'Diario web' ) ),
	array( 'en' => 'Upcoming events', 'it' => 'Prossimi eventi', 'not' => array( 'Eventi in arrivo', 'Eventi imminenti' ) ),
	array( 'en' => 'Register Now', 'it' => 'Si registri ora', 'not' => array( 'Registrati', 'Registrati ora' ) ),
	array( 'en' => 'Schedule a Meeting', 'it' => 'Fissi un incontro', 'not' => array( 'Richiedi una riunione', 'Programma un meeting' ) ),
	array( 'en' => 'Stay connected', 'it' => 'Resti in contatto', 'not' => array( 'Rimani in contatto', 'Stai connesso' ) ),
	array( 'en' => 'Overview', 'it' => 'Panoramica', 'not' => array( 'Sguardo d’insieme', 'Visione generale' ) ),
	array( 'en' => 'Gallery', 'it' => 'Galleria', 'not' => array( 'Esposizione' ) ),
	array( 'en' => 'FAQ', 'it' => 'Domande frequenti', 'not' => array( 'FAQ di domande' ) ),
	array( 'en' => 'Frequently Asked Questions', 'it' => 'Domande frequenti', 'not' => array( 'Domande poste di frequente' ) ),
	array( 'en' => 'Related Resources', 'it' => 'Risorse correlate', 'not' => array( 'Risorse relative' ) ),
	array( 'en' => 'Related Products', 'it' => 'Prodotti correlati', 'not' => array( 'Prodotti relativi' ) ),
	array( 'en' => 'Products', 'it' => 'Prodotti', 'not' => array( 'Prodotto' ) ),
	array( 'en' => 'All products', 'it' => 'Tutti i prodotti', 'not' => array( 'Prodotti tutti' ) ),
	array( 'en' => 'Categories', 'it' => 'Categorie', 'not' => array( 'Classi' ) ),
	array( 'en' => 'Filter by category', 'it' => 'Filtra per categoria', 'not' => array( 'Filtro per categoria' ) ),
	array( 'en' => 'Clear all filters', 'it' => 'Cancella tutti i filtri', 'not' => array( 'Pulisci tutti i filtri', 'Azzera filtri' ) ),
	array( 'en' => 'Sort by:', 'it' => 'Ordina per:', 'not' => array( 'Ordinato da:', 'Smista per:' ) ),
	array( 'en' => 'Popular', 'it' => 'Popolari', 'not' => array( 'Popolare' ) ),
	array( 'en' => 'Expand all', 'it' => 'Espandi tutto', 'not' => array( 'Allarga tutto' ) ),
	array( 'en' => 'Reset chat', 'it' => 'Ripristina chat', 'not' => array( 'Resetta chat', 'Azzera la chiacchierata' ) ),
	array( 'en' => 'Model', 'it' => 'Modello', 'not' => array( 'Modella' ) ),
	array( 'en' => 'Configuration', 'it' => 'Configurazione', 'not' => array( 'Impostazione' ) ),
	array( 'en' => 'Comparison', 'it' => 'Confronto', 'not' => array( 'Comparazione', 'Paragone' ) ),
	array( 'en' => 'Calendar View Unavailable', 'it' => 'Vista calendario non disponibile', 'not' => array( 'Visualizzazione del calendario indisponibile' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'it' => 'È pronto ad aggiornare la Sua infrastruttura?', 'not' => array( 'Pronto ad aggiornare la Sua infrastruttura?', 'Sei pronto ad aggiornare la tua infrastruttura?' ) ),
	array( 'en' => 'Machine down or need a hand?', 'it' => 'La macchina è ferma o ha bisogno di aiuto?', 'not' => array( 'Macchina ferma o ha bisogno di aiuto?', 'Macchina giù o serve una mano?' ) ),
	array( 'en' => 'Need help with something else?', 'it' => 'Ha bisogno di aiuto per qualcos’altro?', 'not' => array( 'Ha bisogno di aiuto con altro?', 'Serve aiuto con qualcos’altro?' ) ),
	array( 'en' => 'Need support now?', 'it' => 'Ha bisogno di assistenza ora?', 'not' => array( 'Serve supporto adesso?', 'Hai bisogno di assistenza ora?' ) ),
	array( 'en' => 'How can we help you today?', 'it' => 'Come possiamo aiutarLa oggi?', 'not' => array( 'Come possiamo aiutarti oggi?', 'Come possiamo assisterLa oggi?' ) ),
	array( 'en' => 'sales inquiry', 'it' => 'richiesta commerciale', 'not' => array( 'inchiesta di vendita', 'domanda di vendite' ) ),
	array( 'en' => 'Contact name', 'it' => 'Nome del contatto', 'not' => array( 'Nome contatto', 'Nome di contatto' ) ),
	array( 'en' => 'Country', 'it' => 'Paese', 'not' => array( 'Stato', 'Nazione' ) ),
	array( 'en' => 'State / Province', 'it' => 'Regione / Provincia', 'not' => array( 'Stato / Provincia', 'Stato / Regione' ) ),
	array( 'en' => 'County', 'it' => 'Provincia', 'not' => array( 'Contea' ) ),
	array( 'en' => 'Priority 1/2/3', 'it' => 'Priorità 1/2/3', 'not' => array( 'Precedenza 1/2/3' ) ),
	array( 'en' => 'Attach files (optional)', 'it' => 'Alleghi file (facoltativo)', 'not' => array( 'Allega file (opzionale)', 'Alleghi i file (facoltativo)' ) ),
	array( 'en' => 'Select an option', 'it' => 'Selezioni un’opzione', 'not' => array( 'Seleziona un’opzione', 'Scegli un’opzione' ) ),
	array( 'en' => 'Choose your division:', 'it' => 'Scelga la Sua divisione:', 'not' => array( 'Scegli la Tua divisione:', 'Scegli la tua divisione:' ) ),
	array( 'en' => 'Choose a different topic', 'it' => 'Scelga un altro argomento', 'not' => array( 'Scegli un altro argomento', 'Scegli un argomento diverso' ) ),
	array( 'en' => 'unbeatable deals', 'it' => 'offerte imbattibili', 'not' => array( 'affari insuperabili', 'occasioni imbattibili' ) ),
	array( 'en' => 'Assembly', 'it' => 'Assemblaggio', 'not' => array( 'Montaggio', 'Assemblea' ) ),
	array( 'en' => 'Assembly & Test Systems', 'it' => 'Sistemi di assemblaggio e collaudo', 'not' => array( 'Sistemi di montaggio e test' ) ),
	array( 'en' => 'gage-based assembly', 'it' => 'assemblaggio con controllo dimensionale', 'not' => array( 'montaggio basato su calibro' ) ),
	array( 'en' => 'and counting', 'it' => 'e non ci fermiamo', 'not' => array( 'e continuiamo', 'e in corso', 'e non è finita qui' ) ),
);
