<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * Polish term base (en -> pl). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Source: 100-page blind review, 2026-09-25.
 */
return array(
	array( 'en' => '*', 'pl' => 'Button and link labels may use the bare imperative, which is standard Polish UI ("Pobierz", "Przeglądaj katalog", "Zamów prezentację", "Więcej informacji"). In running sentences never address the reader with ty or wy forms: use Państwo ("Mogą Państwo…", "Zapraszamy do kontaktu").', 'not' => array( 'Porozmawiaj z nami', 'Skontaktuj się z nami', 'Dowiedz się więcej o', 'Twój', 'Twoja', 'Twoje', 'Twoich', 'Twoim', 'Twojej', 'Twojego', 'Twoją', 'Wasz', 'Wasza', 'Wasze', 'Waszych', 'Waszego', 'Waszej', 'możesz', 'możecie', 'chcesz', 'chcecie', 'potrzebujesz', 'potrzebujecie', 'masz', 'macie', 'jesteś', 'jesteście' ) ),
	array( 'en' => '20-high / six-high mill', 'pl' => 'walcarka 20-walcowa / 6-walcowa', 'not' => array( 'walcarka dwudziestościowa', 'walcarka sześciościowa' ) ),
	array( 'en' => '3-jaw chuck', 'pl' => 'uchwyt trójszczękowy', 'not' => array( 'uchwyt trzyczęściowy' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'pl' => 'A DESIGN / B LOGO', 'not' => array( 'PROJEKT A', 'LOGO B' ) ),
	array( 'en' => 'active part probing', 'pl' => 'aktywny pomiar detalu', 'not' => array( 'aktywne sondowanie części' ) ),
	array( 'en' => 'actuation systems', 'pl' => 'układy wykonawcze', 'not' => array( 'systemy aktywacji' ) ),
	array( 'en' => 'adaptive speed control', 'pl' => 'adaptacyjna regulacja prędkości', 'not' => array( 'adaptacyjna kontrola prędkości' ) ),
	array( 'en' => 'ADAS (advanced driver assistance systems)', 'pl' => 'systemy wspomagania kierowcy (ADAS)', 'not' => array( 'systemy wsparcia kierowcy' ) ),
	array( 'en' => 'ADAS alignment', 'pl' => 'kalibracja ADAS', 'not' => array( 'wyrównanie ADAS' ) ),
	array( 'en' => 'ADVANCING THE MACHINE (trademark)', 'pl' => 'ADVANCING THE MACHINE', 'not' => array( 'NAPĘDZAJĄC MASZYNĘ' ) ),
	array( 'en' => 'air cycle machines', 'pl' => 'turbochłodziarki powietrza', 'not' => array( 'maszyny cyklu powietrza' ) ),
	array( 'en' => 'anchoring (machine foundation)', 'pl' => 'zakotwienie', 'not' => array( 'zakotwiczenie' ) ),
	array( 'en' => 'aperture plate', 'pl' => 'płyta otworowa', 'not' => array( 'płyta otwarcia' ) ),
	array( 'en' => 'applications (use cases)', 'pl' => 'zastosowania', 'not' => array( 'aplikacje' ) ),
	array( 'en' => 'armature', 'pl' => 'twornik', 'not' => array( 'wirnik elektryczny' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES (trademark)', 'pl' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDYCYNA I NAUKI PRZYRODNICZE', 'Ascential – Medycyna i nauki przyrodnicze', 'Ascential Medycyna i nauki o życiu', 'dział medycyny i nauk przyrodniczych' ) ),
	array( 'en' => 'Ascential Test & Measurement (Systems)', 'pl' => 'Ascential Test & Measurement (Systems)', 'not' => array( 'Ascential Systemy kontrolno-pomiarowe', 'Ascential Systemów Kontrolno-Pomiarowych', 'dział Systemów Kontrolno-Pomiarowych', 'dziale Systemów Pomiarowych i Badawczych', 'systemów pomiarowych i testujących', 'systemów pomiarowych i badawczych Ascential' ) ),
	array( 'en' => 'Ask Burke Porter (page name)', 'pl' => 'Ask Burke Porter', 'not' => array( 'Zapytaj Burke Porter' ) ),
	array( 'en' => 'associate attorney', 'pl' => 'prawnik współpracujący', 'not' => array( 'asystent adwokata' ) ),
	array( 'en' => 'audit stations', 'pl' => 'stanowiska audytowe', 'not' => array( 'stanowiska kontrolne', 'stanowiska audytowe (kontrolno-pomiarowe)' ) ),
	array( 'en' => 'automated handling cells', 'pl' => 'zautomatyzowane gniazda manipulacyjne', 'not' => array( 'komórki manipulacyjne' ) ),
	array( 'en' => 'backhoe', 'pl' => 'koparko-ładowarka', 'not' => array( 'kopiarka gąsienicowa' ) ),
	array( 'en' => 'baler', 'pl' => 'prasa do belowania', 'not' => array( 'prasownica' ) ),
	array( 'en' => 'bead breaking', 'pl' => 'zrywanie stopki opony', 'not' => array( 'rozbijanie opaski' ) ),
	array( 'en' => 'bearers (balancer supports)', 'pl' => 'podpory', 'not' => array( 'łożyska' ) ),
	array( 'en' => 'bearing center lines', 'pl' => 'osie łożysk', 'not' => array( 'osie czopów' ) ),
	array( 'en' => 'bearing life', 'pl' => 'trwałość łożyska', 'not' => array( 'czas życia łożyska' ) ),
	array( 'en' => 'blade (grader)', 'pl' => 'lemiesz', 'not' => array( 'ostrze' ) ),
	array( 'en' => 'blank ECM', 'pl' => 'niezaprogramowany moduł ECM', 'not' => array( 'pusty ECM', 'nowych modułów ECM', 'nowe moduły ECM', 'pustych modułów ECM', 'niezapisanych sterowników ECM', 'niezaprogramowany sterownik ECM' ) ),
	array( 'en' => 'blast furnace', 'pl' => 'wielki piec', 'not' => array( 'piec wysoki' ) ),
	array( 'en' => 'blowers', 'pl' => 'dmuchawy', 'not' => array( 'wentylatory' ) ),
	array( 'en' => 'bore axis alignment', 'pl' => 'ustawienie osi wiązki', 'not' => array( 'wyrównanie osi otworu', 'ustawienie osi wiązki (celowania anteny)' ) ),
	array( 'en' => 'boreless compressor wheel', 'pl' => 'koło sprężarki bez otworu centralnego', 'not' => array( 'turbosprężarka bez łożysk ślizgowych' ) ),
	array( 'en' => 'boring (machining)', 'pl' => 'wytaczanie', 'not' => array( 'wiercenie' ) ),
	array( 'en' => 'boring drill (HDD)', 'pl' => 'wiertnica', 'not' => array( 'wiertło wiercące', 'wiertnica (głowica wiertnicza)' ) ),
	array( 'en' => 'branch', 'pl' => 'przestrzeń w systemie LMS', 'not' => array( 'oddział', 'przestrzeń (gałąź) w systemie LMS' ) ),
	array( 'en' => 'Bristol (city)', 'pl' => 'Bristol', 'not' => array( 'Brystol' ) ),
	array( 'en' => 'built to last', 'pl' => 'stworzone z myślą o długiej żywotności', 'not' => array( 'zbudowane na długość' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'pl' => 'Burke E. Porter Machinery', 'not' => array( 'Burke Porter – Maszyny' ) ),
	array( 'en' => 'Burke Porter Group', 'pl' => 'Burke Porter Group', 'not' => array( 'Grupa Burke Porter' ) ),
	array( 'en' => 'burst proof protection', 'pl' => 'odporność na rozerwanie wirnika', 'not' => array( 'ochrona przed wybuchem' ) ),
	array( 'en' => 'calibration target', 'pl' => 'tarcza kalibracyjna', 'not' => array( 'wieszak na cele', 'wyrównanie celu' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'pl' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Kalibracja jako usługa™', 'model Kalibracji jako Usługi™' ) ),
	array( 'en' => 'capital equipment', 'pl' => 'dobra inwestycyjne', 'not' => array( 'urządzenia kapitałowe' ) ),
	array( 'en' => 'cargo loading systems', 'pl' => 'systemy załadunku towarów', 'not' => array( 'systemy załadunku ładunku' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'pl' => 'hamownie podwoziowe 2- i 4-kołowe', 'not' => array( 'hamownie podwoziowe 2- i 4-osiowe' ) ),
	array( 'en' => 'chip vacuum', 'pl' => 'odciąg wiórów', 'not' => array( 'odkurzacz wiórów' ) ),
	array( 'en' => 'clay gun', 'pl' => 'zatykarka otworu spustowego', 'not' => array( 'maszyna do formowania gliny' ) ),
	array( 'en' => 'CMT-TR Polimer (model code)', 'pl' => 'CMT-TR Polimer', 'not' => array( 'wyważarka wirników polimerowych' ) ),
	array( 'en' => 'cold pilger mill', 'pl' => 'walcarka pielgrzymowa na zimno', 'not' => array( 'walcarka pilgerów na zimno' ) ),
	array( 'en' => 'collet chuck', 'pl' => 'uchwyt tulejowy', 'not' => array( 'uchwyt zaciskowy powietrzny', 'uchwyt pneumatyczny', 'uchwyt tulejowy (collet)' ) ),
	array( 'en' => 'combine (harvester)', 'pl' => 'kombajn', 'not' => array( 'prasa zbioru' ) ),
	array( 'en' => 'commercial vehicle', 'pl' => 'pojazd użytkowy', 'not' => array( 'pojazd handlowy', 'turbosprężarka handlowa' ) ),
	array( 'en' => 'commissioning', 'pl' => 'rozruch', 'not' => array( 'komisjonowanie', 'rozruch (uruchomienie)' ) ),
	array( 'en' => 'Connect on LinkedIn', 'pl' => 'Profil na LinkedIn', 'not' => array( 'Connect on LinkedIn' ) ),
	array( 'en' => 'control (of a process)', 'pl' => 'sterowanie', 'not' => array( 'kontrola' ) ),
	array( 'en' => 'control module', 'pl' => 'moduł sterowania', 'not' => array( 'moduł kontroli' ) ),
	array( 'en' => 'controls (control systems)', 'pl' => 'układy sterowania', 'not' => array( 'sterowniki', 'system kontrolny' ) ),
	array( 'en' => 'Core / Plus / Elite (service tiers)', 'pl' => 'Core, Plus, Elite', 'not' => array( 'Podstawowy, Plus, Elite' ) ),
	array( 'en' => 'Corporate Roles', 'pl' => 'Kierownictwo korporacyjne', 'not' => array( 'Funkcje korporacyjne' ) ),
	array( 'en' => 'correction (of unbalance)', 'pl' => 'korekcja', 'not' => array( 'korekta' ) ),
	array( 'en' => 'crankshaft lathe', 'pl' => 'tokarka do wałów korbowych', 'not' => array( 'tokarka do korbowodów' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'pl' => 'Kruispuntbank van Ondernemingen', 'not' => array( 'Krajowy Rejestr Przedsiębiorstw', 'Kruispuntbank van Ondernemingen (Crossroads Bank for Enterprises)' ) ),
	array( 'en' => 'cushion testing', 'pl' => 'badanie amortyzacji końcowej', 'not' => array( 'testowanie poduszki', 'badanie amortyzacji końcowej (dławienia)' ) ),
	array( 'en' => 'custom fixturing', 'pl' => 'oprzyrządowanie', 'not' => array( 'urządzenia pomocnicze', 'oprzyrządowanie (uchwyty obróbkowe)' ) ),
	array( 'en' => 'customer journey', 'pl' => 'etapy współpracy', 'not' => array( 'podróż klienta', 'współpraca (etapy współpracy)' ) ),
	array( 'en' => 'Date: (signature block)', 'pl' => 'Data:', 'not' => array( 'Dane:' ) ),
	array( 'en' => 'deep hole drilling', 'pl' => 'wiercenie głębokich otworów', 'not' => array( 'głębokie otwory' ) ),
	array( 'en' => 'defensible (results)', 'pl' => 'możliwe do obronienia podczas audytu', 'not' => array( 'możliwe do obrony' ) ),
	array( 'en' => 'Deliverables', 'pl' => 'Rezultaty Prac', 'not' => array( 'Dostarczane Wyniki', 'Dostarczalny', 'Dostarczenia', 'Dostarczany element', 'Rezultaty Prac (jeden niezmienny ciąg)' ) ),
	array( 'en' => 'deployment', 'pl' => 'uruchomienie', 'not' => array( 'wdrożenie', 'uruchomienie (instalacja)' ) ),
	array( 'en' => 'design (of a machine)', 'pl' => 'konstrukcja', 'not' => array( 'projekt' ) ),
	array( 'en' => 'dial indicator', 'pl' => 'czujnik zegarowy', 'not' => array( 'miernik ścieżki' ) ),
	array( 'en' => 'disability insurance', 'pl' => 'ubezpieczenie na wypadek niezdolności do pracy', 'not' => array( 'renta inwalidztwa' ) ),
	array( 'en' => 'discrete industries', 'pl' => 'sektory produkcji dyskretnej', 'not' => array( 'branże dyskretne' ) ),
	array( 'en' => 'draper header', 'pl' => 'heder taśmowy', 'not' => array( 'głowica żniwna prasy zbioru', 'rozrzutnik' ) ),
	array( 'en' => 'drift (cylinder)', 'pl' => 'opadanie tłoka', 'not' => array( 'dryfowanie' ) ),
	array( 'en' => 'drivability', 'pl' => 'właściwości jezdne', 'not' => array( 'prowadzenie' ) ),
	array( 'en' => 'dual mass flywheel', 'pl' => 'dwumasowe koło zamachowe', 'not' => array( 'dwumasowe sprzęgło bezwładności', 'sprzęgło dwumasowe', 'dwumasy' ) ),
	array( 'en' => 'dynamometer', 'pl' => 'hamownia', 'not' => array( 'dynamometr', 'dynamometr podwozia pojazdu' ) ),
	array( 'en' => 'eddy current technology', 'pl' => 'technologia prądów wirowych', 'not' => array(  ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'pl' => 'maszyny do elektroerozji (EDT)', 'not' => array( 'maszyny do elektroerozyji' ) ),
	array( 'en' => 'Email Disclosure (page name)', 'pl' => 'Klauzula poufności wiadomości e-mail', 'not' => array( 'Ujawnienie adresu e-mail' ) ),
	array( 'en' => 'EMC darkroom', 'pl' => 'komora bezodbiciowa', 'not' => array( 'ciemnia', 'komora ekranowana (bezodbiciowa)' ) ),
	array( 'en' => 'end of line testing', 'pl' => 'testy na końcu linii produkcyjnej', 'not' => array( 'testy końcowe linii produkcyjnej' ) ),
	array( 'en' => 'energy recuperation', 'pl' => 'rekuperacja energii', 'not' => array( 'regeneracja energii' ) ),
	array( 'en' => 'engine software loaders', 'pl' => 'urządzenia do wgrywania oprogramowania silników', 'not' => array( 'programy ładujące silniki' ) ),
	array( 'en' => 'eRotor (product line)', 'pl' => 'eRotor', 'not' => array( 'wirniki pojazdów elektrycznych' ) ),
	array( 'en' => 'events & conferences', 'pl' => 'wydarzenia i konferencje', 'not' => array( 'imprezy i konferencje' ) ),
	array( 'en' => 'excavator', 'pl' => 'koparka', 'not' => array( 'kopiarka' ) ),
	array( 'en' => 'exhaust extraction', 'pl' => 'odciąg spalin', 'not' => array( 'ekstrakcja spalin' ) ),
	array( 'en' => 'factory floor', 'pl' => 'hala produkcyjna', 'not' => array( 'hala produkcji' ) ),
	array( 'en' => 'failure rates (calibration)', 'pl' => 'odsetek nieprawidłowych kalibracji', 'not' => array( 'wskaźniki awarii' ) ),
	array( 'en' => 'features', 'pl' => 'cechy', 'not' => array( 'funkcje', 'cechy (wyposażenie)' ) ),
	array( 'en' => 'Featuring: <Brand>', 'pl' => 'Z udziałem: <Brand>', 'not' => array( 'Featuring: Bauer' ) ),
	array( 'en' => 'field agents', 'pl' => 'technicy terenowi', 'not' => array( 'agenci' ) ),
	array( 'en' => 'field balancing', 'pl' => 'wyważanie w miejscu zabudowy', 'not' => array( 'wyważanie w terenie', 'wyważanie w miejscu zabudowy (na obiekcie)' ) ),
	array( 'en' => 'filler', 'pl' => 'stanowisko napełniania', 'not' => array( 'napełniacz', 'stanowisko napełniania / napełniarka' ) ),
	array( 'en' => 'filler gun', 'pl' => 'pistolet napełniający', 'not' => array( 'pistolecik dozujący' ) ),
	array( 'en' => 'final discharge', 'pl' => 'końcowy zrzut gazu', 'not' => array( 'ostateczne rozładowanie' ) ),
	array( 'en' => 'fine leak', 'pl' => 'drobna nieszczelność', 'not' => array( 'szczelność precyzyjna', 'nieszczelność drobna (odwrócony szyk)' ) ),
	array( 'en' => 'flexplate', 'pl' => 'tarcza napędowa', 'not' => array( 'sprzęgło dwumasowe', 'tarcza napędowa (flexplate)' ) ),
	array( 'en' => 'fluid power', 'pl' => 'hydraulika siłowa', 'not' => array( 'napędy płynowe', 'napęd płynowy', 'napęd hydrauliczny' ) ),
	array( 'en' => 'flywheel', 'pl' => 'koło zamachowe', 'not' => array( 'sprzęgło bezwładności', 'dwumasa' ) ),
	array( 'en' => 'footprint (floor area)', 'pl' => 'powierzchnia zabudowy', 'not' => array( 'rozmiar', 'ślad montażowy', 'śladzie powierzchniowym', 'ślad powierzchniowy', 'śladem powierzchniowym', 'powierzchnia' ) ),
	array( 'en' => 'For Immediate Release', 'pl' => 'Informacja prasowa – do natychmiastowej publikacji', 'not' => array( 'Do natychmiastowego opublikowania' ) ),
	array( 'en' => 'forged rolls', 'pl' => 'walce kute', 'not' => array( 'walce kuowane' ) ),
	array( 'en' => 'front strut (suspension)', 'pl' => 'przednia kolumna zawieszenia', 'not' => array( 'przedni słupek', 'przedni zacisk', 'zaciąg hydrauliczny' ) ),
	array( 'en' => 'gantry', 'pl' => 'manipulator portalowy', 'not' => array( 'brama portalowa', 'brama portalowa typu pick-and-place', 'manipulator portalowy / portal' ) ),
	array( 'en' => 'GDPR', 'pl' => 'RODO', 'not' => array( 'GDPR' ) ),
	array( 'en' => 'gear shift calibration', 'pl' => 'kalibracja zmiany biegów', 'not' => array( 'kalibracja przesunięcia biegów' ) ),
	array( 'en' => 'grinding wheel', 'pl' => 'ściernica', 'not' => array( 'tarcza szlifierska' ) ),
	array( 'en' => 'gross leak test', 'pl' => 'test nieszczelności zgrubnych', 'not' => array( 'test nieszczelności brutto', 'testy szczelności mechanicznej i brutto', 'grubych nieszczelności' ) ),
	array( 'en' => 'gundrill', 'pl' => 'wiertło lufowe', 'not' => array( 'konfiguracje gundrillowe', 'wiertło lufowe (gundrill)' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'pl' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Sp. z o.o.' ) ),
	array( 'en' => 'half case (RDU/PTU)', 'pl' => 'obudowa dzielona', 'not' => array( 'półosiowy' ) ),
	array( 'en' => 'hay mower', 'pl' => 'kosiarka do siana', 'not' => array( 'kosarka', 'kosiarka' ) ),
	array( 'en' => 'hazardous area', 'pl' => 'strefa zagrożona wybuchem', 'not' => array( 'obszar zagrożony' ) ),
	array( 'en' => 'health checks', 'pl' => 'przeglądy stanu technicznego', 'not' => array( 'kontrole zdrowotne' ) ),
	array( 'en' => 'high production / high-volume production', 'pl' => 'produkcja wielkoseryjna', 'not' => array( 'produkcja wysokoobiegowa', 'produkcja wysokotonażowa', 'linie wysokowydajne', 'duże wolumeny produkcji', 'produkcji seryjnej' ) ),
	array( 'en' => 'high-mix, low-volume', 'pl' => 'produkcja wielowariantowa i małoseryjna', 'not' => array( 'środowiska o dużej różnorodności, niskich wolumenach' ) ),
	array( 'en' => 'high-performance teams', 'pl' => 'zespoły o wysokiej efektywności', 'not' => array( 'zespoły wysokiej wydajności' ) ),
	array( 'en' => 'higher-level control system', 'pl' => 'nadrzędny system sterowania', 'not' => array( 'wyższy system kontrolny' ) ),
	array( 'en' => 'HMU/FMU', 'pl' => 'zespoły HMU/FMU', 'not' => array( 'zespoły HMU/FMU (hydromechaniczne i dozujące paliwo)' ) ),
	array( 'en' => 'idle duration', 'pl' => 'czas pracy na biegu jałowym', 'not' => array( 'czas bezczynności' ) ),
	array( 'en' => 'implements', 'pl' => 'osprzęt', 'not' => array( 'implementy', 'maszyny (kolidujące z inną gałęzią taksonomii)', 'osprzęt (maszyny towarzyszące)', '(maszyn towarzyszących)' ) ),
	array( 'en' => 'Imprint', 'pl' => 'Nota prawna', 'not' => array( 'Imprint (pozostawione)' ) ),
	array( 'en' => 'in a single clamping', 'pl' => 'w jednym zamocowaniu', 'not' => array( 'w jednym zacisku' ) ),
	array( 'en' => 'infeed (grinding)', 'pl' => 'posuw', 'not' => array( 'infeed' ) ),
	array( 'en' => 'infinitely variable', 'pl' => 'płynnie regulowany', 'not' => array( 'nieskończenie zmienny' ) ),
	array( 'en' => 'inline crankshaft', 'pl' => 'wał rzędowy', 'not' => array( 'wał czterosuwowy' ) ),
	array( 'en' => 'inline dyno', 'pl' => 'hamownia szeregowa', 'not' => array( 'hamownia wbudowana' ) ),
	array( 'en' => 'insights', 'pl' => 'wnioski', 'not' => array( 'wglądy', 'wskazówki' ) ),
	array( 'en' => 'instrument cluster', 'pl' => 'zestaw wskaźników', 'not' => array( 'klaster instrumentów', 'zestaw przyrządów' ) ),
	array( 'en' => 'keg finger holes', 'pl' => 'otwory chwytowe', 'not' => array( 'otwory palcowe' ) ),
	array( 'en' => 'kinetostatics', 'pl' => 'kinetostatyka', 'not' => array( 'kinetyka' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'pl' => 'Izba Handlowa (KvK)', 'not' => array( 'Izba Handlowo-Przemysłowa (KvK)' ) ),
	array( 'en' => 'Labour & Travel', 'pl' => 'Robocizna i dojazdy', 'not' => array( 'Praca i podróże' ) ),
	array( 'en' => 'landed cost model', 'pl' => 'model kosztu dostarczonego', 'not' => array( 'model kosztu dostawy', 'model kosztu dostarczonego (landed cost)' ) ),
	array( 'en' => 'landing gear systems', 'pl' => 'układy podwozia', 'not' => array( 'systemy podwozia lądowania' ) ),
	array( 'en' => 'leak detection', 'pl' => 'wykrywanie nieszczelności', 'not' => array( 'detekcja wycieków', 'wykrywanie wycieków', 'detektor przecieków', 'testy szczelności' ) ),
	array( 'en' => 'learning management system (LMS)', 'pl' => 'system zarządzania szkoleniami (LMS)', 'not' => array( 'system zarządzania nauką' ) ),
	array( 'en' => 'like-minded companies', 'pl' => 'firmy o zbieżnej wizji', 'not' => array( 'firmy o podobnych poglądach' ) ),
	array( 'en' => 'load capacity', 'pl' => 'obciążalność', 'not' => array( 'pojemność' ) ),
	array( 'en' => 'LPM (litres per minute)', 'pl' => 'l/min', 'not' => array(  ) ),
	array( 'en' => 'lube & scavenge pumps', 'pl' => 'pompy smarowania i odsysania oleju', 'not' => array( 'pompy smarowania i odpowietrzania' ) ),
	array( 'en' => 'lubrication', 'pl' => 'smarowanie', 'not' => array( 'wymiana oleju' ) ),
	array( 'en' => 'machine tools', 'pl' => 'obrabiarki', 'not' => array( 'maszyny technologiczne', 'maszyny do obróbki' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'pl' => 'dyrektywa maszynowa 2006/42/WE', 'not' => array(  ) ),
	array( 'en' => 'machining cell', 'pl' => 'gniazdo obróbcze', 'not' => array( 'gniazdo produkcyjne', 'komórka manipulacyjna' ) ),
	array( 'en' => 'machinist', 'pl' => 'wykwalifikowany operator obrabiarek', 'not' => array( 'operator' ) ),
	array( 'en' => 'maintenance contracts', 'pl' => 'umowy serwisowe', 'not' => array( 'umowy konserwacyjne' ) ),
	array( 'en' => 'marine (sector)', 'pl' => 'przemysł morski', 'not' => array( 'żegluga' ) ),
	array( 'en' => 'maximum rotor diameter', 'pl' => 'maksymalna średnica wirnika', 'not' => array( 'maksymalny rozmiar wirnika' ) ),
	array( 'en' => 'mental health care', 'pl' => 'opieka w zakresie zdrowia psychicznego', 'not' => array( 'zdalna opieka zdrowotna' ) ),
	array( 'en' => 'mill roll', 'pl' => 'walec', 'not' => array(  ) ),
	array( 'en' => 'misalignment (sensors)', 'pl' => 'odchylenie w ustawieniu czujników', 'not' => array( 'niedostatki w wyrównaniu' ) ),
	array( 'en' => 'motor grader', 'pl' => 'równiarka', 'not' => array( 'kopiarka gruntowa', 'Motor Graders (pozostawione)' ) ),
	array( 'en' => 'motorized clamping', 'pl' => 'mocowanie z napędem elektrycznym', 'not' => array( 'zmotoryzowane mocowanie' ) ),
	array( 'en' => 'MRO', 'pl' => 'organizacje MRO', 'not' => array( 'serwis i części zamienne' ) ),
	array( 'en' => 'mudding system (HDD)', 'pl' => 'system płuczki wiertniczej', 'not' => array( 'system błota' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'pl' => 'naamloze vennootschap', 'not' => array( 'spółka akcyjna', 'naamloze vennootschap (bez tłumaczenia)' ) ),
	array( 'en' => 'Name: (signature block)', 'pl' => 'Imię i nazwisko:', 'not' => array( 'Nazwa:' ) ),
	array( 'en' => 'Netherlands (statutory)', 'pl' => 'Niderlandy', 'not' => array( 'Holandia' ) ),
	array( 'en' => 'non-rotating balancing machine', 'pl' => 'wyważarka bezobrotowa', 'not' => array( 'wyważarka bez wirnika' ) ),
	array( 'en' => 'obsolescence management', 'pl' => 'zarządzanie wycofywaniem komponentów', 'not' => array( 'zarządzanie przestarzałością' ) ),
	array( 'en' => 'off-highway', 'pl' => 'maszyny pozadrogowe', 'not' => array( 'maszyny budowlane', 'maszyny robocze' ) ),
	array( 'en' => 'oil drain', 'pl' => 'spust oleju', 'not' => array( 'otwór odpowietrzający' ) ),
	array( 'en' => 'operations', 'pl' => 'działalność', 'not' => array( 'operacje', 'działalność (zakład, praca zakładu)' ) ),
	array( 'en' => 'opportunities', 'pl' => 'możliwości', 'not' => array( 'oportuniści', 'możliwości (szanse)' ) ),
	array( 'en' => 'patented', 'pl' => 'opatentowany', 'not' => array( 'patentowany' ) ),
	array( 'en' => 'pedestals', 'pl' => 'podpory', 'not' => array( 'piedestały', 'podpory / stojaki' ) ),
	array( 'en' => 'peers', 'pl' => 'inni specjaliści z branży', 'not' => array( 'rówieśnicy' ) ),
	array( 'en' => 'performance', 'pl' => 'parametry', 'not' => array( 'wydajność', 'parametry (działanie, osiągi)' ) ),
	array( 'en' => 'personal information / personal data', 'pl' => 'dane osobowe', 'not' => array( 'informacje osobiste' ) ),
	array( 'en' => 'pinches & bruises', 'pl' => 'zgniecenia i wgniecenia', 'not' => array( 'ścieśnienia i stłuczenia' ) ),
	array( 'en' => 'pinion gear', 'pl' => 'zębnik', 'not' => array( 'czop' ) ),
	array( 'en' => 'pins (on pedestals)', 'pl' => 'kołki', 'not' => array( 'czopy' ) ),
	array( 'en' => 'power drive units', 'pl' => 'jednostki napędowe (PDU)', 'not' => array( 'jednostki napędu mocy' ) ),
	array( 'en' => 'Powered by', 'pl' => 'Oparte na', 'not' => array( 'Zasilana', 'Napędzane' ) ),
	array( 'en' => 'President (of a company)', 'pl' => 'prezes', 'not' => array( 'prezydent' ) ),
	array( 'en' => 'pressurization', 'pl' => 'ciśnieniowanie', 'not' => array( 'presuryzacja (mieszane z ciśnieniowaniem na jednej stronie)' ) ),
	array( 'en' => 'probe alignment', 'pl' => 'ustawienie sondy', 'not' => array( 'wyrównanie sondy', 'ustawienie (pozycjonowanie) sondy' ) ),
	array( 'en' => 'process recipe', 'pl' => 'receptura', 'not' => array( 'recepta' ) ),
	array( 'en' => 'propulsion & powertrain', 'pl' => 'napęd i układ przeniesienia napędu', 'not' => array( 'Napęd i Układ napędowy', 'napęd i napęd', 'Napęd', 'napęd i układy napędowe', 'Napęd i układy napędowe', 'układ przeniesienia mocy', 'układu przeniesienia mocy', 'przeniesienia mocy', 'napęd i układ przeniesienia mocy', 'napęd i układ napędowy', 'Napęd i układ napędowy' ) ),
	array( 'en' => 'PTO (power take-off)', 'pl' => 'wał odbioru mocy (WOM)', 'not' => array( 'wał odbiornika mocy' ) ),
	array( 'en' => 'pulley', 'pl' => 'koło pasowe', 'not' => array( 'pasek', 'koło pasków', 'pasek klinowy' ) ),
	array( 'en' => 'punching (mass correction)', 'pl' => 'wykrawanie', 'not' => array( 'przecinanie', 'przeciskanie' ) ),
	array( 'en' => 'push and pull (thrust/pullback)', 'pl' => 'napór i wyciąganie', 'not' => array( 'ciśnienie i rozciąganie' ) ),
	array( 'en' => 'reconditioning (rolls)', 'pl' => 'regeneracja walców', 'not' => array( 'renowacja' ) ),
	array( 'en' => 'refrigerant', 'pl' => 'czynnik chłodniczy', 'not' => array( 'chłodziwo', 'chłodnik', 'chłodziv' ) ),
	array( 'en' => 'refrigerant charging', 'pl' => 'napełnianie czynnikiem chłodniczym', 'not' => array( 'ładowanie chłodziwem', 'napełnianie chłodziwem', 'załadunek czynnika chłodniczego', 'ładowanie czynnika chłodniczego' ) ),
	array( 'en' => 'refrigeration (sector)', 'pl' => 'chłodnictwo', 'not' => array( 'chłodzenie' ) ),
	array( 'en' => 'Register (a legal register)', 'pl' => 'Rejestr', 'not' => array( 'Zarejestruj się' ) ),
	array( 'en' => 'Registered office', 'pl' => 'Siedziba', 'not' => array( 'Siedziba zarejestrowana', 'Adres zarejestrowany' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'pl' => 'zakłady regeneracji i naprawy', 'not' => array( 'producenci regeneracyjni i naprawcy' ) ),
	array( 'en' => 'remarketers', 'pl' => 'pośrednicy w odsprzedaży flot', 'not' => array( 'pośrednicy obrotu wtórnego' ) ),
	array( 'en' => 'reportable', 'pl' => 'udokumentowane', 'not' => array( 'raportowalne' ) ),
	array( 'en' => 'represent (model a process)', 'pl' => 'odwzorować', 'not' => array( 'reprezentować' ) ),
	array( 'en' => 'residual unbalance', 'pl' => 'niewyważenie szczątkowe', 'not' => array( 'resztkowa nierównowaga', 'minimalna pozostała nierównowaga', 'niezrównoważoność resztkowa', 'maksymalna dopuszczalna nierównowaga' ) ),
	array( 'en' => 'responsive', 'pl' => 'szybko reagujący', 'not' => array( 'responsywny' ) ),
	array( 'en' => 'restbus simulation', 'pl' => 'symulacja magistrali szczątkowej', 'not' => array( 'symulacja magistrali rezydualnej', 'symulacja magistrali szczątkowej (restbus)' ) ),
	array( 'en' => 'retaining rollers', 'pl' => 'rolki podtrzymujące', 'not' => array( 'wałki retencyjne', 'walce retencyjne' ) ),
	array( 'en' => 'right-shoring', 'pl' => 'right-shoring', 'not' => array( 'optymalizacja webinaru', 'optymalizacja łańcucha dostaw' ) ),
	array( 'en' => 'roll inspection', 'pl' => 'kontrola walców', 'not' => array( 'kontrola rolek' ) ),
	array( 'en' => 'Roll Shop Technologies (page title)', 'pl' => 'Technologie szlifierni walców', 'not' => array( 'Roll Shop Technologies', 'Technologie walcowni', 'Technologie dla walcowni', 'Broszura technologii Roll Shop' ) ),
	array( 'en' => 'roller (brake tester)', 'pl' => 'rolka', 'not' => array( 'wałek' ) ),
	array( 'en' => 'roller brake tester', 'pl' => 'rolkowe stanowisko do badania hamulców', 'not' => array( 'testery hamulców wałkowych' ) ),
	array( 'en' => 'rolling torque', 'pl' => 'moment oporowy toczenia', 'not' => array( 'moment obrotowy wału' ) ),
	array( 'en' => 'rotary diamond dressing', 'pl' => 'obciąganie diamentową rolką obrotową', 'not' => array( 'dresowanie diamentowe rotacyjne' ) ),
	array( 'en' => 'rotor wing aircraft', 'pl' => 'śmigłowce', 'not' => array( 'samoloty śmigłowcowe' ) ),
	array( 'en' => 'sealed assembly', 'pl' => 'szczelny zespół', 'not' => array( 'zapieczętowany zespół', 'szczelny (hermetyczny) zespół' ) ),
	array( 'en' => 'seamless link', 'pl' => 'płynne powiązanie', 'not' => array( 'bezpośredni łącznik' ) ),
	array( 'en' => 'service professional', 'pl' => 'specjalista serwisu', 'not' => array( 'profesjonalista serwisu' ) ),
	array( 'en' => 'setup cycles', 'pl' => 'cykle ustawiania detalu', 'not' => array( 'cykle montażu', 'cykle ustawiania (mocowania) detalu' ) ),
	array( 'en' => 'single bay', 'pl' => 'jednostanowiskowy', 'not' => array( 'jednokomorowy', 'jednokanałowy', 'jednokanałowych' ) ),
	array( 'en' => 'single cylinder crankshaft', 'pl' => 'wał jednocylindrowy', 'not' => array( 'wał jednośladowy' ) ),
	array( 'en' => 'single station / multi station', 'pl' => 'jednostanowiskowy / wielostanowiskowy', 'not' => array( 'jednokomorowy', 'wielokomorowy' ) ),
	array( 'en' => 'site visit', 'pl' => 'wizyta na miejscu', 'not' => array( 'wizyta na terenie' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'pl' => 'sonda węchowa', 'not' => array( 'szczypce do wąchania', 'sonda węchowa (sniffer)' ) ),
	array( 'en' => 'snubber', 'pl' => 'tłumik uderzeń hydraulicznych', 'not' => array( 'tłumik', 'tłumik uderzeń hydraulicznych (dławik)' ) ),
	array( 'en' => 'soak time', 'pl' => 'czas wychłodzenia', 'not' => array( 'czas przetrzymywania przed zimnym startem', 'czas wychłodzenia (soak time)' ) ),
	array( 'en' => 'spalls', 'pl' => 'odpryski', 'not' => array( 'łuszczeń' ) ),
	array( 'en' => 'special test facilities', 'pl' => 'specjalne stanowiska testowe', 'not' => array( 'specjalistyczne obiekty testowe' ) ),
	array( 'en' => 'spin testing machine', 'pl' => 'maszyna do testów wirowania', 'not' => array( 'testery obrotowe', 'maszyna do testowania wirowania' ) ),
	array( 'en' => 'sprayers', 'pl' => 'opryskiwacze', 'not' => array( 'rozpylacze', 'sprayers (pozostawione)' ) ),
	array( 'en' => 'squeak & rattle testing', 'pl' => 'badania odgłosów i skrzypnięć', 'not' => array( 'testowanie trzęsienia', 'badania odgłosów i skrzypnięć (squeak & rattle)' ) ),
	array( 'en' => 'stand-alone machine', 'pl' => 'maszyna samodzielna', 'not' => array( 'maszyna niezależna', 'maszyna autonomiczna', 'maszyny autonomiczne' ) ),
	array( 'en' => 'Standardization at scale', 'pl' => 'Standaryzacja na dużą skalę', 'not' => array( 'Standaryzacja na skalę' ) ),
	array( 'en' => 'strip', 'pl' => 'taśma', 'not' => array( 'blacha', 'pasmo' ) ),
	array( 'en' => 'Strip Lines', 'pl' => 'Linie do taśm', 'not' => array( 'Linie do taśm (linie przetwarzania taśm)', 'linie do taśm (linie przetwarzania taśm)', 'Linie paskowe' ) ),
	array( 'en' => 'superabrasives', 'pl' => 'ściernice supertwarde', 'not' => array( 'superabrazywy', 'ściernice supertwarde (diamentowe i CBN)' ) ),
	array( 'en' => 'surface separations', 'pl' => 'rozwarstwienia powierzchni', 'not' => array( 'rozwarstwiania powierzchni' ) ),
	array( 'en' => 'tap hole', 'pl' => 'otwór spustowy', 'not' => array( 'otwór odpustowy' ) ),
	array( 'en' => 'tapered roller bearing', 'pl' => 'łożysko stożkowe', 'not' => array( 'łożysko walcowe' ) ),
	array( 'en' => 'tariffs', 'pl' => 'cła', 'not' => array( 'taryfy' ) ),
	array( 'en' => 'tension (mechanical)', 'pl' => 'siła naciągu', 'not' => array( 'napięcie' ) ),
	array( 'en' => 'third member', 'pl' => 'mechanizm główny mostu napędowego', 'not' => array( 'trzeci człon', 'mechanizm główny mostu napędowego (third member)' ) ),
	array( 'en' => 'tin plating', 'pl' => 'cynowanie', 'not' => array( 'cynkowanie' ) ),
	array( 'en' => 'TIR / radial run-out', 'pl' => 'bicie promieniowe (TIR)', 'not' => array( 'bieg TIR', 'bieg promieniowy' ) ),
	array( 'en' => 'tire inflator', 'pl' => 'stanowisko napełniania opon', 'not' => array( 'pompka do opon' ) ),
	array( 'en' => 'torque vectoring', 'pl' => 'rozdział momentu obrotowego', 'not' => array( 'wektoryzacja momentu obrotowego', 'rozdział momentu obrotowego (torque vectoring)' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS (trademark)', 'pl' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'KOMPLEKSOWE ROZWIĄZANIA KOMERCJALIZACJI', 'KOMPLEKSOWE ROZWIĄZANIA KOMERCJALIZACYJNE' ) ),
	array( 'en' => 'traceable tests', 'pl' => 'testy identyfikowalne', 'not' => array( 'śledzowalne testy' ) ),
	array( 'en' => 'tracer gas', 'pl' => 'gaz znacznikowy', 'not' => array( 'śledzenie gazów' ) ),
	array( 'en' => 'traction battery (BMS)', 'pl' => 'akumulator', 'not' => array( 'bateria' ) ),
	array( 'en' => 'transmission / gearbox', 'pl' => 'skrzynia biegów', 'not' => array( 'Transmisja', 'transmisja napędowa', 'transmisja połączeniowa', 'elementy transmisji', 'wały transmisji', 'przekładnia (dla wału napędowego)', 'skrzynia biegów (przekładnia)' ) ),
	array( 'en' => 'turbo calibration', 'pl' => 'kalibracja turbosprężarek', 'not' => array( 'wyważanie turbosprężarek' ) ),
	array( 'en' => 'turbocharger flow bench', 'pl' => 'stanowisko przepływowe', 'not' => array( 'hamownia turbosprężarek', 'stanowisko pomiarowe', 'STANOWISKO PRZEPŁYWU', 'PRZEPŁYWOMIERZ', 'przepływomierz Turbo Test' ) ),
	array( 'en' => 'turbocharger frame size', 'pl' => 'rozmiar korpusu', 'not' => array( 'rozmiar ramy' ) ),
	array( 'en' => 'turnkey', 'pl' => '„pod klucz”', 'not' => array( 'turnkey', 'instalacje turnkey' ) ),
	array( 'en' => 'turret-style wheel head', 'pl' => 'rewolwerowa głowica ściernicowa', 'not' => array( 'głowica z systemem wieżyczki', 'głowica rewolwerowa', 'głowicy rewolwerowej' ) ),
	array( 'en' => 'two-wheel drive', 'pl' => 'napęd na dwa koła', 'not' => array( 'napęd na dwie koła' ) ),
	array( 'en' => 'ultra-stable design', 'pl' => 'wyjątkowo stabilna konstrukcja', 'not' => array( 'ultratrwały projekt' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'pl' => 'ultradźwiękowa myjka dysz', 'not' => array( 'ultrasoniczny czyszczacz dysz' ) ),
	array( 'en' => 'unbalance', 'pl' => 'niewyważenie', 'not' => array( 'niezrównoważenie', 'nierównowaga', 'niezrównoważoność', 'brak równowagi' ) ),
	array( 'en' => 'unbeatable deals', 'pl' => 'bezkonkurencyjne oferty', 'not' => array( 'niezawarte oferty' ) ),
	array( 'en' => 'Universal Balancing', 'pl' => 'Universal Balancing', 'not' => array( 'Wyważanie uniwersalne' ) ),
	array( 'en' => 'uptime across systems', 'pl' => 'dostępność systemów', 'not' => array( 'dostępność w całych systemach' ) ),
	array( 'en' => 'v-block support', 'pl' => 'podpora pryzm V', 'not' => array( 'podpora pryzm (bloków V)', 'bloki V' ) ),
	array( 'en' => 'vacuum evacuation', 'pl' => 'odpompowanie', 'not' => array( 'ewakuacja', 'ewakuacja próżni', 'zdolność do ewakuacji', 'odpompowanie (wytworzenie próżni)' ) ),
	array( 'en' => 'validate performance', 'pl' => 'potwierdzić parametry', 'not' => array( 'zweryfikować wydajność', 'potwierdzić parametry (działanie)' ) ),
	array( 'en' => 'valve body unit', 'pl' => 'korpus zaworowy', 'not' => array( 'zespół zaworów' ) ),
	array( 'en' => 'vibration', 'pl' => 'drgania', 'not' => array( 'wibracje', 'vibracja' ) ),
	array( 'en' => 'volume flexibility', 'pl' => 'elastyczność wielkości serii', 'not' => array( 'elastyczność wolumenów' ) ),
	array( 'en' => 'walking beam system', 'pl' => 'system belki kroczącej', 'not' => array( 'system chodzącego belki' ) ),
	array( 'en' => 'warranty coverage', 'pl' => 'zakres ochrony gwarancyjnej', 'not' => array( 'ubezpieczenie', 'elastyczne ubezpieczenie' ) ),
	array( 'en' => 'water meter', 'pl' => 'wodomierz', 'not' => array( 'licznik wody' ) ),
	array( 'en' => 'water-cooled', 'pl' => 'chłodzony wodą', 'not' => array( 'chłodzący wodą' ) ),
	array( 'en' => 'WCAG four principles', 'pl' => 'Postrzegalność, Funkcjonalność, Zrozumiałość, Rzetelność', 'not' => array( 'Dostrzegalna, Obsługiwalna, Zrozumiała, Niezawodne' ) ),
	array( 'en' => 'wheel aligner', 'pl' => 'urządzenie do ustawiania geometrii kół', 'not' => array( 'urządzenie do regulacji kąta zbieżności kół', 'urządzenie do wyrównywania' ) ),
	array( 'en' => 'wheel alignment', 'pl' => 'geometria kół', 'not' => array( 'wyrównanie', 'geometria kół (zbieżność)' ) ),
	array( 'en' => 'WHEREAS (recital)', 'pl' => 'ZWAŻYWSZY, ŻE', 'not' => array( 'NATOMIAST', 'PODCZAS GDY' ) ),
	array( 'en' => 'whistle (turbo)', 'pl' => 'świst', 'not' => array( 'hałas', 'szum', 'bezszumna precyzja' ) ),
	array( 'en' => 'Work Product (defined term)', 'pl' => 'Wynik Pracy', 'not' => array( 'Produkt Pracy', 'Wyniki Prac' ) ),
	array( 'en' => 'XL Machine', 'pl' => 'XL Machine', 'not' => array( 'Maszyna XL' ) ),

	// Round-B supplement (100-page review, 2026-09-25)


	// Round-B supplement (100-page review, 2026-09-25)
	array( 'en' => 'Marketplace', 'pl' => 'Marketplace', 'not' => array( 'Rynek', 'Giełda' ) ),
	array( 'en' => 'Medical', 'pl' => 'Medycyna', 'not' => array( 'Medyczny', 'Medyczne' ) ),
	array( 'en' => 'Non-Rotate Systems', 'pl' => 'Systemy bezobrotowe', 'not' => array( 'Systemy bez obrotu', 'Systemy nieobrotowe' ) ),
	array( 'en' => 'Spin Testing', 'pl' => 'Testy wirowania', 'not' => array( 'Badania na wirowanie' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'pl' => 'walce przenośników i walce papiernicze', 'not' => array( 'przenośnik i rolki papierowe', 'rolki papierowe' ) ),
	array( 'en' => 'stem stickiness', 'pl' => 'zacieranie trzpienia', 'not' => array( 'Lepkość trzpienia', 'zacieranie (zakleszczanie) trzpienia' ) ),
	array( 'en' => 'hydraulic pilot', 'pl' => 'hydrauliczne sterowanie pilotowe', 'not' => array( 'Hydrauliczny pilot', 'sterowanie hydrauliczne (pilotowe)' ) ),
	array( 'en' => 'load sense signal', 'pl' => 'sygnał load-sense (LS)', 'not' => array( 'Sygnał czujnika obciążenia' ) ),
	array( 'en' => 'debonding', 'pl' => 'rozwarstwienie powłoki i rdzenia', 'not' => array( 'delaminacja', 'rozwarstwiania', 'rozwarstwienie (debonding) powłoki i rdzenia' ) ),
	array( 'en' => 'movable cradle', 'pl' => 'ruchoma kołyska', 'not' => array( 'Ruchoma podstawa' ) ),
	array( 'en' => 'thrust force / pullback force', 'pl' => 'siła naporu / siła wyciągania', 'not' => array( 'Siła osiowa' ) ),
	array( 'en' => 'ring gears', 'pl' => 'wieńce zębate', 'not' => array( 'Koła zębate pierścieniowe' ) ),
	array( 'en' => 'blade timing', 'pl' => 'czas cyklu ruchu lemiesza', 'not' => array( 'czas pracy lemiesza' ) ),
	array( 'en' => 'heavy-duty', 'pl' => 'ciężki', 'not' => array( 'Ciężkie', 'wytrzymałych pojazdów', 'pojazdów wytrzymałych', 'wytrzymałe pojazdy', 'wytrzymała hamownia', 'wytrzymałej hamowni', 'wytrzymałych rdzeni', 'wersji wytrzymałej', 'o wytrzymałej konstrukcji', 'wytrzymałe serwoprasy', 'wytrzymały' ) ),
	array( 'en' => 'life sciences', 'pl' => 'nauki o życiu', 'not' => array( 'nauki przyrodnicze' ) ),
	array( 'en' => 'First Alert Monitoring System', 'pl' => 'System wczesnego ostrzegania First Alert', 'not' => array( 'System monitorowania z alertami pierwszego stopnia' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'pl' => 'Turbo Test Duo Expert', 'not' => array( 'Ekspert TURBO TEST DUO' ) ),
	array( 'en' => 'Board Member', 'pl' => 'Członek rady nadzorczej', 'not' => array( 'Członek zarządu' ) ),
	array( 'en' => 'Principal', 'pl' => 'partner', 'not' => array( 'Główny specjalista ds. inwestycji', 'był Principal', 'jest Principal', 'Principal w zespole', 'Principal' ) ),
	array( 'en' => 'Leadership', 'pl' => 'Kierownictwo', 'not' => array( 'Zespół kierowniczy', 'Kadra kierownicza wyższego szczebla' ) ),
	array( 'en' => 'Introducing', 'pl' => 'Przedstawiamy', 'not' => array( 'Nowość' ) ),
	array( 'en' => 'flammable gases', 'pl' => 'gazy palne', 'not' => array( 'gazy łatwopalne' ) ),
	array( 'en' => 'Electronic hung mass', 'pl' => 'elektroniczna kompensacja masy zawieszonej', 'not' => array( 'Elektroniczna zawieszona masa' ) ),
	array( 'en' => 'Detection Focus', 'pl' => 'Wykrywane wady', 'not' => array( 'Zakres wykrywania', 'Zakres wykrywanych defektów' ) ),
	array( 'en' => 'weight capacity', 'pl' => 'udźwig', 'not' => array( 'nośność' ) ),
	array( 'en' => 'vacuum', 'pl' => 'próżnia', 'not' => array( 'podciśnienie' ) ),
	array( 'en' => 'vacuum rise test', 'pl' => 'test narastania próżni', 'not' => array( 'test narastania podciśnienia', 'testy wzrostu próżni' ) ),
	array( 'en' => 'fixed stations', 'pl' => 'stałe stanowiska', 'not' => array( 'stacje stacjonarne' ) ),
	array( 'en' => 'mobile carousels', 'pl' => 'ruchome karuzele', 'not' => array( 'mobilne karuzele' ) ),
	array( 'en' => 'cooling units', 'pl' => 'urządzenia chłodnicze', 'not' => array( 'jednostki chłodzące', 'jednostkach chłodniczych', 'jednostki chłodnicze', 'linii montażowych układów chłodzenia', 'układy chłodzenia' ) ),
	array( 'en' => 'e-axle', 'pl' => 'e-osie', 'not' => array( 'osie elektryczne', 'e-axle' ) ),
	array( 'en' => 'keg', 'pl' => 'beczka', 'not' => array( 'kega', 'beczka (keg)' ) ),
	array( 'en' => 'horizontal boring machine', 'pl' => 'pozioma wiertnica', 'not' => array( 'pozioma wiertarka' ) ),
	array( 'en' => 'test benches / test stands', 'pl' => 'stanowiska testowe', 'not' => array( 'stanowiska badawcze', 'stanowiska badań', 'pól testowych i badawczych' ) ),
	array( 'en' => 'testing', 'pl' => 'badania', 'not' => array( 'testowanie', 'testy' ) ),
	array( 'en' => 'Aerospace & industrials', 'pl' => 'Przemysł lotniczy i kosmiczny oraz przemysł ogólny', 'not' => array( 'przemysł lotniczy i ogólny', 'Sektor lotniczo-kosmiczny i przemysłowy', 'Sektor lotniczo-kosmiczny', 'Lotnictwo i przemysł', 'lotnictwo i kosmonautyka oraz przemysł', 'przemysłu lotniczego i kosmicznego lub przemysłowego', 'zastosowaniach lotniczych i przemysłowych', 'lotnictwa i przemysłu', 'Lotnictwo i Przemysł', 'Bauer | Lotnictwo' ) ),
	array( 'en' => 'Exhibit', 'pl' => 'Załącznik', 'not' => array( 'Aneks' ) ),
	array( 'en' => 'Section', 'pl' => 'Artykuł', 'not' => array( 'Sekcja', 'zaworu artykułu', 'zaworów artykułowych', 'zaworu Artykułu', 'od 2 do 10 artykułów' ) ),
	array( 'en' => 'RECITALS', 'pl' => 'PREAMBUŁA', 'not' => array(  ) ),
	array( 'en' => 'Products', 'pl' => 'Produkty', 'not' => array( 'Produkt s' ) ),
	array( 'en' => 'Ascential Indemnity', 'pl' => 'Odszkodowanie ze strony Ascential', 'not' => array( 'Ascential Indemnity' ) ),
	array( 'en' => 'England', 'pl' => 'Anglia', 'not' => array( 'England' ) ),
	array( 'en' => 'West Flanders', 'pl' => 'Flandria Zachodnia', 'not' => array( 'West Flanders' ) ),
	array( 'en' => 'Poland', 'pl' => 'Polska', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Play', 'pl' => 'Odtwórz', 'not' => array( 'Play' ) ),
	array( 'en' => 'Listen to this article', 'pl' => 'Posłuchaj artykułu', 'not' => array( 'Listen to this article' ) ),
	array( 'en' => 'Read the article', 'pl' => 'Przeczytaj artykuł', 'not' => array( 'Read the article', 'Read', 'Czytaj' ) ),
	array( 'en' => 'N chapters', 'pl' => 'N rozdziałów', 'not' => array( '10 chapters', 'chapters' ) ),
	array( 'en' => 'Share / Copy link / Email', 'pl' => 'Udostępnij / Kopiuj link / Wyślij e-mailem', 'not' => array( 'Share', 'Copy link', 'Email' ) ),
	array( 'en' => '<Model> Refrigerant Charging Brochure', 'pl' => 'Broszura <Model> – napełnianie czynnikiem chłodniczym', 'not' => array( 'Broszura Simplex Refrigeration Charging' ) ),
	array( 'en' => 'Titan <Application> System', 'pl' => 'System Titan do <zastosowania>', 'not' => array( 'Titan System hedera taśmowego kombajnu', 'Titan System kosiarki', 'System Titan Forestry Feller Buncher', 'Titan Hay Baler' ) ),
	array( 'en' => 'Explore', 'pl' => 'Przeglądaj', 'not' => array( 'Więcej informacji', 'Przeglądaj zasoby' ) ),
	array( 'en' => 'Browse catalog', 'pl' => 'Przeglądaj katalog', 'not' => array( 'Katalog' ) ),
	array( 'en' => 'Browse all resources', 'pl' => 'Przeglądaj wszystkie zasoby', 'not' => array( 'Wszystkie zasoby' ) ),
	array( 'en' => 'Explore the Catalog', 'pl' => 'Przeglądaj katalog', 'not' => array( 'Katalog' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'pl' => 'Czy są Państwo gotowi na modernizację infrastruktury?', 'not' => array( 'Gotowi na modernizację infrastruktury?', 'Gotów do modernizacji' ) ),
	array( 'en' => 'gantry milling', 'pl' => 'frezowanie portalowe', 'not' => array( 'frezowanie bramowe' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'pl' => 'Kombinowana wysoko- i niskoobrotowa maszyna do wyważania rdzeni', 'not' => array(  ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'pl' => 'dynamiczne stanowisko przepływowe do turbosprężarek', 'not' => array( 'dynamiczne stanowisko przepływowe' ) ),
	array( 'en' => 'actionable insights', 'pl' => 'użyteczne wnioski', 'not' => array( 'praktyczne wnioski' ) ),
	array( 'en' => 'expert insights', 'pl' => 'fachowa wiedza i wskazówki', 'not' => array( 'fachowe wnioski' ) ),
	array( 'en' => 'fully loaded test', 'pl' => 'badanie przy pełnym obciążeniu', 'not' => array( 'kompleksowy test' ) ),
	array( 'en' => 'Addresses', 'pl' => 'eliminuje niedoskonałości', 'not' => array( 'Eliminacja defektów' ) ),
	array( 'en' => 'is now', 'pl' => 'to teraz', 'not' => array( 'jest teraz' ) ),
	array( 'en' => 'sales inquiry', 'pl' => 'zapytanie sprzedażowe', 'not' => array( 'Zapytanie handlowe' ) ),
	array( 'en' => 'Priority 1/2/3', 'pl' => 'Priorytet 1: wysoki / Priorytet 2: średni / Priorytet 3: niski', 'not' => array(  ) ),
	array( 'en' => 'Searching ascentialtech.com', 'pl' => 'Przeszukiwanie ascentialtech.com', 'not' => array( 'Searching ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'pl' => 'Widok kalendarza niedostępny', 'not' => array( 'Calendar View Unavailable' ) ),
	array( 'en' => 'hazardous areas', 'pl' => 'strefy niebezpieczne', 'not' => array( 'strefa zagrożona wybuchem' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'pl' => 'Osprzęt – koniec linii', 'not' => array( 'Osprzęt (maszyny towarzyszące) – koniec linii' ) ),

	// round 1 (pl)
	array( 'en' => 'Noise, Vibration and Harshness (NVH)', 'pl' => 'hałas, drgania i harshness (NVH)', 'not' => array( 'hałasu, drgań i szorstkości', 'drgań i szorstkości', 'hałasu, wibracji i szorstkości', 'badań hałasu, drgań i szorstkości', 'hałas, drgania i szorstkość', 'Hałas, drgania i szorstkość', 'hałas, drgania, szorstkość', 'drgania i szorstkość' ) ),
	array( 'en' => 'heavy-duty truck', 'pl' => 'samochód ciężarowy dużej ładowności', 'not' => array( 'wytrzymałych ciężarówek', 'wytrzymałych pojazdów ciężarowych', 'wytrzymałych pojazdach ciężarowych', 'pojazdy ciężarowe o wytrzymałej konstrukcji', 'pojazdów ciężarowych o wytrzymałej konstrukcji' ) ),
	array( 'en' => 'light-duty truck', 'pl' => 'samochód dostawczy', 'not' => array( 'wersji standardowej' ) ),
	array( 'en' => 'Automotive eRotor balancing brochure', 'pl' => 'Broszura dotycząca wyważania eRotorów w motoryzacji', 'not' => array( 'wyważania eRotorów do pojazdów elektrycznych', 'eRotorów do pojazdów elektrycznych' ) ),
	array( 'en' => 'Evacuation (refrigeration circuit)', 'pl' => 'próżniowanie', 'not' => array( 'odgazowanie' ) ),
	array( 'en' => 'Test Systems (category label)', 'pl' => 'Systemy testowe', 'not' => array( 'Systemy do badań', 'Systemy badań', 'Systemy badawcze', 'systemy badawcze', 'systemy badań' ) ),
	array( 'en' => 'test system', 'pl' => 'system testowy', 'not' => array( 'system badawczy', 'systemy badawcze' ) ),
	array( 'en' => 'transfer case', 'pl' => 'skrzynia rozdzielcza', 'not' => array( 'skrzynka rozdzielcza', 'skrzynek rozdzielczych', 'skrzynki rozdzielczej', 'skrzynkach rozdzielczych' ) ),
	array( 'en' => 'production cell', 'pl' => 'gniazdo produkcyjne', 'not' => array( 'cela produkcyjna', 'cele produkcyjne', 'komórka produkcyjna', 'komórkę produkcyjną', 'cel testowych' ) ),
	array( 'en' => 'Industry 4.0 diagnostics', 'pl' => 'Diagnostyka Przemysłu 4.0', 'not' => array( 'w duchu Przemysłu 4.0', 'zgodną z koncepcją Przemysłu 4.0', 'zgodna z Industry 4.0', 'zgodną z Industry 4.0' ) ),
	array( 'en' => 'changeover', 'pl' => 'przezbrojenie', 'not' => array( 'zmiana modelu', 'zmianę modelu' ) ),
	array( 'en' => 'weight addition', 'pl' => 'dodawanie ciężarków', 'not' => array( 'dodawanie masy', 'dodawania masy' ) ),
	array( 'en' => 'e-mobility', 'pl' => 'elektromobilność', 'not' => array( 'e-mobilność', 'e-mobilności', 'e-mobility' ) ),
	array( 'en' => 'mining truck', 'pl' => 'wozidło górnicze', 'not' => array( 'wózek górniczy', 'wózka górniczego', 'wózków górniczych' ) ),
	array( 'en' => 'roll shop', 'pl' => 'szlifiernia walców', 'not' => array( 'walcownia walców', 'walcowni walców' ) ),
	array( 'en' => 'module aligner', 'pl' => 'urządzenie do ustawiania modułów', 'not' => array( 'Wyrówniarka', 'wyrówniarka', 'wyrówniarki' ) ),
	array( 'en' => 'Tire and wheel', 'pl' => 'Opony i koła', 'not' => array( 'Opona i koło' ) ),
	array( 'en' => 'transmission components', 'pl' => 'elementy układu przeniesienia napędu', 'not' => array( 'elementy skrzyni biegów', 'elementów skrzyni biegów' ) ),
	array( 'en' => 'windage', 'pl' => 'opory aerodynamiczne', 'not' => array( 'opory powietrza', 'oporów powietrza' ) ),
	array( 'en' => 'end-of-line applications', 'pl' => 'zastosowania na końcu linii produkcyjnej', 'not' => array( 'zastosowania end-of-line', 'zastosowań end-of-line', 'końcowych aplikacji testowych', 'aplikacje końca linii' ) ),
	array( 'en' => 'Speak with an expert', 'pl' => 'Porozmawiaj z ekspertem', 'not' => array( 'Porozmawiaj teraz z ekspertem' ) ),
	array( 'en' => 'Contact our engineering team for a custom quote or technical consultation', 'pl' => 'Prosimy o kontakt z naszym zespołem inżynierów w celu uzyskania indywidualnej wyceny lub konsultacji technicznej', 'not' => array( 'Zapraszamy do kontaktu z naszym zespołem inżynierów', 'Contact our engineering team' ) ),
	array( 'en' => 'See what we do here', 'pl' => 'Czym się zajmujemy', 'not' => array( 'Zapraszamy do zapoznania się z naszą ofertą', 'Więcej informacji o naszej działalności', 'Zapraszamy do zapoznania się z naszą działalnością' ) ),
	array( 'en' => 'Specs (tab label)', 'pl' => 'Parametry', 'not' => array(  ) ),
	array( 'en' => 'Technical Specifications (table heading)', 'pl' => 'Dane techniczne', 'not' => array( 'Specyfikacje tokarki CNC', 'Specyfikacje obróbki szwajcarskiej', 'Specyfikacje techniczne' ) ),
	array( 'en' => 'hydronic units', 'pl' => 'układy hydroniczne', 'not' => array( 'jednostek hydronikowych', 'układów hydroniki' ) ),
	array( 'en' => 'Break in', 'pl' => 'docieranie', 'not' => array( 'Przerwa w pracy', 'przerwa w pracy' ) ),
	array( 'en' => 'Planes (balancing spec-table header)', 'pl' => 'Płaszczyzny', 'not' => array( 'Samoloty' ) ),
	array( 'en' => 'turbine section / compressor section', 'pl' => 'sekcja turbiny / sekcja sprężarki', 'not' => array( 'artykuł turbiny', 'artykułu turbiny', 'artykule turbiny', 'artykule sprężarki', 'artykuł sprężarki' ) ),
	array( 'en' => '2 to 6 section stacks', 'pl' => 'stosy od 2 do 6 sekcji', 'not' => array( 'od 2 do 6 artykułów' ) ),
	array( 'en' => 'large-frame turbochargers', 'pl' => 'turbosprężarki dużych rozmiarów', 'not' => array( 'maszyny wielkogabarytowe', 'maszyn wielkogabarytowych', 'maszyny o dużej ramie', 'większych obudów', 'dużych obudów' ) ),
	array( 'en' => 'core balancers', 'pl' => 'wyważarki rdzeni', 'not' => array( 'Wyważarki podstawowe', 'wyważarki podstawowe' ) ),
	array( 'en' => 'Basic Series', 'pl' => 'Seria Basic', 'not' => array( 'Seria podstawowa', 'Serii podstawowej', 'Maszyny podstawowy' ) ),
	array( 'en' => 'Twin Series', 'pl' => 'Seria Twin', 'not' => array( 'Maszyny bliźniaczy', 'maszyny bliźniacze' ) ),
	array( 'en' => 'OEM-validated', 'pl' => 'zwalidowane przez producentów OEM', 'not' => array( 'homologację producentów OEM', 'homologacja producentów OEM' ) ),
	array( 'en' => 'Workers\' Compensation (Statutory)', 'pl' => 'Ubezpieczenie od następstw wypadków przy pracy (ustawowe)', 'not' => array( 'Workers' ) ),
	array( 'en' => 'By: (signature block)', 'pl' => 'W imieniu:', 'not' => array( 'Przez:' ) ),
	array( 'en' => 'subsections (a) or (b)', 'pl' => 'punktów (a) lub (b)', 'not' => array( 'artykułów (a) lub (b)' ) ),
	array( 'en' => '2WD', 'pl' => '2WD', 'not' => array( 'dwuosiowe dynamometry', 'dwuosiowe hamownie', 'dwuosiowych dynamometrów' ) ),
	array( 'en' => 'Heavy Duty EPA chassis dynamometers', 'pl' => 'hamownie podwoziowe EPA klasy Heavy Duty', 'not' => array( 'Ciężkie podwoziowe hamownie dynamometryczne', 'ciężkie hamownie podwoziowe', 'hamownia podwoziowa EPA do pojazdów ciężkich' ) ),
	array( 'en' => 'Experts (animated stat counter)', 'pl' => 'ekspertów', 'not' => array( '+ eksperci' ) ),
	array( 'en' => 'gauging (dimensional measurement)', 'pl' => 'kontrola wymiarowa', 'not' => array( 'oparta na wzorcach', 'opartej na wzorcach', 'pomiarowanie', 'pomiarowaniem', 'dynamicznego pomiarowania', 'pomiarowania', 'pomiaru, akwizycji danych i kontroli jakości' ) ),
	array( 'en' => 'bolted cylinder', 'pl' => 'cylinder skręcany', 'not' => array( 'cylindry kołnierzowe', 'cylindrów kołnierzowych', 'cylindrów śrubowych', 'cylindry śrubowe' ) ),
	array( 'en' => 'zero clearance workholding', 'pl' => 'mocowanie przedmiotu obrabianego z zerowym luzem', 'not' => array( 'bezszczelinkowym', 'bezszczelowy', 'bezszczelowym' ) ),
	array( 'en' => 'beam axle', 'pl' => 'oś belkowa', 'not' => array( 'sztywną osią', 'sztywna oś' ) ),
	array( 'en' => 'shear operations', 'pl' => 'cięcie nożycami', 'not' => array( 'cięciem poprzecznym', 'działalność związaną z cięciem' ) ),
	array( 'en' => 'bearing carriers', 'pl' => 'oprawy łożyskowe', 'not' => array( 'koszyków łożysk', 'koszyki łożysk', 'koszyków łożyskowych' ) ),
	array( 'en' => 'assembly operations', 'pl' => 'operacje montażowe', 'not' => array( 'działalność montażowa', 'działalności montażowej', 'działalnością montażową' ) ),
	array( 'en' => 'Torque and RPM measurements', 'pl' => 'Pomiary momentu obrotowego i prędkości obrotowej', 'not' => array( 'obrotów silnika' ) ),
	array( 'en' => 'Volumetric and mechanical efficiency', 'pl' => 'Sprawność objętościowa i mechaniczna', 'not' => array( 'Wydajność objętościowa i mechaniczna', 'wydajności objętościowej i mechanicznej', 'wydajność objętościowa i/lub mechaniczna', 'wydajności objętościowej i/lub mechanicznej', 'badania wydajności objętościowej' ) ),
	array( 'en' => 'relief valve', 'pl' => 'zawór przelewowy', 'not' => array( 'zaworu bezpieczeństwa', 'zawór bezpieczeństwa', 'zaworów bezpieczeństwa' ) ),
	array( 'en' => 'case drain', 'pl' => 'kanał przecieków wewnętrznych', 'not' => array( 'drenaż obudowy', 'odwodnienia obudowy' ) ),
	array( 'en' => 'Fillers (spec-table row)', 'pl' => 'Stanowiska napełniania', 'not' => array( 'Wypełniacze' ) ),
	array( 'en' => 'priority regulator valve', 'pl' => 'zawór regulatora priorytetowego', 'not' => array( 'regulatora priorytetu' ) ),
	array( 'en' => 'division (business unit)', 'pl' => 'dział', 'not' => array( 'dywizja', 'dywizji', 'dywizjach', 'dywizjami' ) ),
	array( 'en' => 'Specialty Industrial (division name)', 'pl' => 'Specialty Industrial', 'not' => array( 'Przemysłu Specjalistycznego', 'specjalistycznego przemysłu' ) ),
	array( 'en' => 'Marketing Manager', 'pl' => 'kierownik ds. marketingu', 'not' => array( 'dyrektora ds. marketingu', 'dyrektor ds. marketingu' ) ),
	array( 'en' => 'tractor', 'pl' => 'ciągnik', 'not' => array( 'traktor', 'traktora', 'traktorów', 'traktorach' ) ),
	array( 'en' => 'mobile equipment', 'pl' => 'maszyny mobilne', 'not' => array( 'urządzenia mobilne', 'urządzeń mobilnych', 'Urządzenia mobilne', 'pojazdów z wyposażeniem mobilnym' ) ),
	array( 'en' => 'windrowers', 'pl' => 'kosiarki pokosowe', 'not' => array( 'kosiarki rzędowe', 'zgrabiarek rzędowych', 'zgrabiarki rzędowe', 'kosiarek rzędowych', 'siewnika zbożowego', 'siewnik zbożowy' ) ),
	array( 'en' => 'header (combine harvester)', 'pl' => 'heder', 'not' => array( 'głowica żniwna', 'głowice żniwne', 'głowic żniwnych', '(głowice, WOM itp.)', 'głowice, wały odbioru mocy' ) ),
	array( 'en' => 'four-wheel chassis dynamometer', 'pl' => 'czterokołowa hamownia podwoziowa', 'not' => array( 'czterokolumnowa', 'czterokolumnowej' ) ),
	array( 'en' => 'semi-anechoic chamber', 'pl' => 'komora półbezechowa', 'not' => array( 'semi-anechoiczna', 'semi-anechoicznych', 'semi-anechoicznej' ) ),
	array( 'en' => 'test field', 'pl' => 'stanowisko testowe', 'not' => array( 'pól testowych', 'pól badawczych', 'pole badawcze' ) ),
	array( 'en' => 'capital goods testing', 'pl' => 'badania dóbr inwestycyjnych', 'not' => array( 'badań maszyn i urządzeń przemysłowych' ) ),
	array( 'en' => 'diesel (engines and vehicles)', 'pl' => 'wysokoprężny', 'not' => array( 'diesla' ) ),
	array( 'en' => 'break-away torque', 'pl' => 'moment rozruchowy', 'not' => array( 'Moment obrotowy odrywania', 'momentu obrotowego odrywania' ) ),
	array( 'en' => 'running torque', 'pl' => 'moment roboczy', 'not' => array( 'Moment obrotowy biegu', 'momentu obrotowego biegu' ) ),
	array( 'en' => 'bearing preload', 'pl' => 'napięcie wstępne łożysk', 'not' => array( 'Wstępne obciążenie łożysk', 'docisku wstępnego łożysk' ) ),
	array( 'en' => 'Modular (pump model name)', 'pl' => 'Modular', 'not' => array( 'pompy modułowej', 'pompami modułowymi' ) ),
	array( 'en' => 'Pirani head', 'pl' => 'głowica Piraniego', 'not' => array( 'Piranie' ) ),
	array( 'en' => 'vacuum gauge (instrument)', 'pl' => 'próżniomierz', 'not' => array( 'Wakuometr', 'wakuometr' ) ),
	array( 'en' => 'cartridge valve', 'pl' => 'zawór kartridżowy', 'not' => array( 'zaworów kasetowych', 'zawory kasetowe' ) ),
	array( 'en' => 'visual inspection', 'pl' => 'kontrola wizyjna', 'not' => array( 'inspekcja wizujna', 'inspekcji wizujnej' ) ),
	array( 'en' => 'headlight aiming systems', 'pl' => 'systemy ustawiania reflektorów', 'not' => array( 'systemy ustawiania świateł przednich', 'systemów ustawiania świateł przednich', 'regulacji ustawienia reflektorów' ) ),
	array( 'en' => 'apply torque', 'pl' => 'przykładać moment obrotowy', 'not' => array( 'stosują moment obrotowy' ) ),
	array( 'en' => 'sink (oil catch tray)', 'pl' => 'wanna', 'not' => array( 'zlew' ) ),
	array( 'en' => 'Axle live Spin Test', 'pl' => 'próba obrotowa osi pod napędem', 'not' => array( 'Test obrotowy osi na żywo', 'osi na żywo' ) ),
	array( 'en' => 'weights (wheel balancing)', 'pl' => 'ciężarki', 'not' => array( 'odważników', 'odważniki' ) ),
	array( 'en' => 'rattle & twist', 'pl' => 'rattle & twist', 'not' => array( 'GRZECHOTANIE I SKRĘCANIE', 'grzechotanie' ) ),
	array( 'en' => 'pick-by-light weight rack', 'pl' => 'regał ciężarków z systemem pick-by-light', 'not' => array( 'regał wagowy', 'regałem wagowym' ) ),
	array( 'en' => 'bead seat optimizer', 'pl' => 'optymalizator osadzenia stopki opony', 'not' => array( 'optymalizator osadzenia na obręczy', 'optymalizatora osadzenia na obręczy' ) ),
	array( 'en' => 'CCO (Chief Commercial Officer)', 'pl' => 'dyrektor handlowy', 'not' => array( 'dyrektor ds. klientów', 'dyrektora ds. klientów' ) ),
	array( 'en' => 'Transportation (business unit name)', 'pl' => 'Transportation', 'not' => array( 'w segmencie transportowym', 'segmentu transportowego' ) ),
	array( 'en' => 'Watch Demo', 'pl' => 'Obejrzyj demonstrację', 'not' => array( 'Watch Demo' ) ),
	array( 'en' => 'near-surface defects', 'pl' => 'wady przypowierzchniowe', 'not' => array(  ) ),
	array( 'en' => 'backlash', 'pl' => 'luz międzyzębny', 'not' => array(  ) ),

	// round 2 (pl)
	array( 'en' => 'Simplex Refrigeration Charging Brochure', 'pl' => 'Broszura Simplex – napełnianie czynnikiem chłodniczym', 'not' => array( 'Broszura Simplex Refrigeration Charging', 'Simplex Refrigeration Charging' ) ),
	array( 'en' => 'custom-built (systems)', 'pl' => 'wykonany na zamówienie', 'not' => array( 'niestandardowe systemy', 'niestandardowy system', 'niestandardowe rozwiązanie', 'niestandardowych systemów' ) ),
	array( 'en' => 'ECM software revisions', 'pl' => 'wersje oprogramowania ECM', 'not' => array( 'aktualizacji oprogramowania ECM', 'aktualizacje oprogramowania ECM' ) ),
	array( 'en' => 'Non-contact wheel alignment', 'pl' => 'Bezkontaktowy pomiar geometrii kół', 'not' => array( 'Bezkontaktowa geometria kół (zbieżność)', 'Bezkontaktowa geometria kół', 'bezkontaktowej geometrii kół (zbieżność)' ) ),
	array( 'en' => 'camber', 'pl' => 'kąt pochylenia kół', 'not' => array( 'kąta camber', 'kąt camber', 'kątem camber' ) ),
	array( 'en' => 'wheel alignment system', 'pl' => 'system ustawiania geometrii kół', 'not' => array( 'system wyrównywania', 'systemu wyrównywania', 'systemem wyrównywania' ) ),
	array( 'en' => 'heavy industrial vehicles', 'pl' => 'ciężkie pojazdy przemysłowe', 'not' => array( 'wytrzymałych pojazdach przemysłowych', 'wytrzymałe pojazdy przemysłowe', 'wytrzymałych pojazdów przemysłowych' ) ),
	array( 'en' => 'Birth Certificate (end-of-line test record)', 'pl' => 'Metryka wyrobu', 'not' => array( 'Certyfikat urodzenia', 'certyfikat urodzenia', 'certyfikatu urodzenia' ) ),
	array( 'en' => 'Target Positioning (ADAS)', 'pl' => 'Pozycjonowanie tablic kalibracyjnych', 'not' => array( 'Pozycjonowanie celownika', 'celownika', 'celownik' ) ),
	array( 'en' => 'Digital logbook', 'pl' => 'cyfrowy dziennik serwisowy', 'not' => array( 'dziennik pokładowy', 'dzienniku pokładowym', 'cyfrowym dzienniku pokładowym' ) ),
	array( 'en' => 'Calculate Tolerance (button)', 'pl' => 'Oblicz tolerancję', 'not' => array( 'Obliczanie tolerancji' ) ),
	array( 'en' => 'balancing quality grade (ISO 1940/1)', 'pl' => 'klasa dokładności wyważania', 'not' => array( 'Klasa jakości' ) ),
	array( 'en' => 'shell (155 mm projectile body)', 'pl' => 'korpus pocisku', 'not' => array( 'pusta łuska', 'wyważona pusta łuska', 'pustej łuski' ) ),
	array( 'en' => 'rotating band', 'pl' => 'pas prowadzący', 'not' => array( 'pas obturacyjny', 'pasem obturacyjnym', 'pasa obturacyjnego' ) ),
	array( 'en' => 'charge pump', 'pl' => 'pompa zasilająca', 'not' => array( 'pompy ładującej', 'pompa ładująca', 'pompą ładującą' ) ),
	array( 'en' => 'Check relief pressure', 'pl' => 'Sprawdzenie ciśnienia otwarcia zaworu przelewowego', 'not' => array( 'Ciśnienie zaworu zwrotnego', 'ciśnienia zaworu zwrotnego' ) ),
	array( 'en' => 'Time versus pressure', 'pl' => 'Czas w funkcji ciśnienia', 'not' => array( 'Ciśnienie w funkcji czasu', 'Zależność czasu od ciśnienia' ) ),
	array( 'en' => 'Stroke versus pressure', 'pl' => 'Skok w funkcji ciśnienia', 'not' => array( 'Skok a ciśnienie', 'Skok w zależności od ciśnienia' ) ),
	array( 'en' => 'cast iron (valves)', 'pl' => 'żeliwo', 'not' => array( 'żeliwa szarego', 'żeliwo szare', 'żeliwie szarym', 'zaworów z żeliwa szarego' ) ),
	array( 'en' => 'Section Valve Test', 'pl' => 'Badanie zaworów sekcyjnych', 'not' => array( 'Badanie zaworu artykułu', 'Badanie zaworu Artykułu', 'systemu testowego zaworów Artykułu' ) ),
	array( 'en' => 'section (of a sectional valve)', 'pl' => 'sekcja', 'not' => array( 'wielu artykułów', 'składają się z wielu artykułów', 'każdy artykuł jest badany' ) ),
	array( 'en' => 'positive displacement pumps', 'pl' => 'pompy wyporowe', 'not' => array( 'pompami wyporczymi', 'pompy wyporcze', 'pompami wyporowym' ) ),
	array( 'en' => 'Accommodate all actuation types', 'pl' => 'Obsługa wszystkich rodzajów sterowania', 'not' => array( 'Obsługa wszystkich typów siłowników', 'wszystkich typów siłowników' ) ),
	array( 'en' => 'Rolling mill automation', 'pl' => 'Automatyka walcowni', 'not' => array( 'Automatyzacja walcowni', 'Automatyzacji walcowni' ) ),
	array( 'en' => 'Automation and drive systems', 'pl' => 'Automatyka i układy napędowe', 'not' => array( 'Systemy automatyzacji i napędów' ) ),
	array( 'en' => 'pickup (baler)', 'pl' => 'podbierak', 'not' => array( 'podbieracza', 'podbieracz', 'podbieraczem' ) ),
	array( 'en' => 'Multilingual test prompts', 'pl' => 'Wielojęzyczne komunikaty testowe', 'not' => array( 'Wielojęzyczne komunikaty testowe dla operatora', 'komunikaty testowe dla operatora' ) ),
	array( 'en' => 'sniffing (helium leak test)', 'pl' => 'sniffing', 'not' => array( 'wąchania jednostek', 'wąchanie jednostek', 'sondowania jednostek' ) ),
	array( 'en' => 'commercial refrigerator', 'pl' => 'komercyjne urządzenie chłodnicze', 'not' => array( 'lodówek komercyjnych', 'lodówki komercyjne', 'lodówka komercyjna' ) ),
	array( 'en' => 'large-scale manufacturers', 'pl' => 'producenci działający na dużą skalę', 'not' => array( 'producentów wielkogabarytowych', 'wielkogabarytowych lodówek' ) ),
	array( 'en' => 'magnetization', 'pl' => 'magnesowanie', 'not' => array( 'magnetyzacja', 'magnetyzacji', 'magnetyzowanie', 'magnetyzowania' ) ),
	array( 'en' => 'magnetizing head', 'pl' => 'głowica magnesująca', 'not' => array( 'głowica magnetyzująca', 'głowicy magnetyzującej' ) ),
	array( 'en' => 'Energy store', 'pl' => 'Zasobnik energii', 'not' => array( 'Magazyn energii', 'magazynu energii' ) ),
	array( 'en' => 'Dc Idle Voltage', 'pl' => 'Napięcie jałowe DC', 'not' => array( 'Napięcie DC w stanie bezczynności', 'w stanie bezczynności' ) ),
	array( 'en' => 'Dual drill correction', 'pl' => 'korekcja dwoma wiertłami', 'not' => array( 'dwuwiertłową korekcję', 'dwuwiertłowa korekcja', 'podwójną korekcję wierceniem' ) ),
	array( 'en' => 'automatic drilling correction', 'pl' => 'korekcja przez wiercenie', 'not' => array( 'korekcją wierceniem', 'korekcja wiercenia', 'korekcją wiertarką', 'korekcji wierceniem' ) ),
	array( 'en' => 'operator-free correction and loading', 'pl' => 'korekcja i załadunek bez udziału operatora', 'not' => array( 'bezosobową korektą', 'bezosobowa korekta', 'bezosobowym załadunkiem' ) ),
	array( 'en' => 'Tier 1 suppliers', 'pl' => 'dostawcy Tier 1', 'not' => array( 'dostawców pierwszego rzędu', 'dostawcy pierwszego rzędu' ) ),
	array( 'en' => 'Total Torque to Rotate (TTR) measurement', 'pl' => 'pomiar całkowitego momentu potrzebnego do obrotu (TTR)', 'not' => array( 'pomiar całkowitego momentu obrotowego (TTR)' ) ),
	array( 'en' => 'heavy-duty circuit breakers', 'pl' => 'wyłączniki o dużej obciążalności', 'not' => array( 'ciężkie wyłączniki automatyczne', 'Wyłączniki automatyczne do zastosowań ciężkich' ) ),
	array( 'en' => 'Transmission Drop Box', 'pl' => 'skrzynia rozdzielcza przekładni', 'not' => array( 'skrzynki odgałęźnej', 'skrzynka odgałęźna', 'skrzynki odbioru mocy przekładni', 'system Transmission Drop Box' ) ),
	array( 'en' => 'Buzz-squeak-rattle systems', 'pl' => 'systemy wykrywania drgań, pisków i stukotów', 'not' => array( 'drgań, pisków i hałasów', 'wibracji, pisków i stukotów', 'hałasów, pisków i stukań' ) ),
	array( 'en' => 'supercharger', 'pl' => 'sprężarka doładowująca', 'not' => array( 'doładowarek', 'doładowarki', 'sprężarek mechanicznych', 'sprężarki mechanicznej' ) ),
	array( 'en' => 'four-post (vehicle test rig)', 'pl' => 'czterosłupowy', 'not' => array( 'Czterosłupkowy', 'czterosłupkowy', 'czterosłupkowe' ) ),
	array( 'en' => 'driving speed', 'pl' => 'prędkość jazdy', 'not' => array( 'prędkości napędu', 'prędkość napędu' ) ),
	array( 'en' => 'Rattle force', 'pl' => 'Siła wywołująca stukoty', 'not' => array( 'Siła uderzenia', 'siły uderzenia' ) ),
	array( 'en' => 'e-axle test stand', 'pl' => 'stanowisko testowe e-osi', 'not' => array( 'Stanowisko badawcze do e-osi', 'Stanowisko badań e-osi', 'Stanowisko testowe do osi elektrycznych' ) ),
	array( 'en' => '1-4 piece driveshafts', 'pl' => 'wały napędowe 1–4-częściowe', 'not' => array( 'wałów napędowych od 1 do 4 sztuk', 'od 1 do 4 sztuk' ) ),
	array( 'en' => 'High volume OEM production', 'pl' => 'Wielkoseryjna produkcja OEM', 'not' => array( 'Wielkoseryjne wyważanie OEM' ) ),
	array( 'en' => 'part-to-part cycle time', 'pl' => 'czas cyklu detal–detal', 'not' => array( 'czasy cyklu część do części', 'część do części' ) ),
	array( 'en' => 'ultimate partial pressure', 'pl' => 'graniczne ciśnienie cząstkowe', 'not' => array( 'Maksymalne ciśnienie cząstkowe', 'maksymalnego ciśnienia cząstkowego' ) ),
	array( 'en' => 'anti-suck back', 'pl' => 'zapobieganie cofaniu się medium', 'not' => array( 'cofaniu się cieczy', 'cofania się cieczy' ) ),
	array( 'en' => 'tooling machines', 'pl' => 'obrabiarki', 'not' => array( 'maszyny narzędziowe', 'maszyn narzędziowych', 'maszyn obróbczych' ) ),
	array( 'en' => 'Automatic pickup failure detection', 'pl' => 'Automatyczne wykrywanie awarii czujnika', 'not' => array( 'wykrywanie błędów pobrania', 'błędów pobrania', 'wykrywanie błędów odczytu' ) ),
	array( 'en' => 'Cross-platform compatibility', 'pl' => 'Kompatybilność międzyplatformowa', 'not' => array( 'kompatybilność między platformami', 'Kompatybilność między platformami' ) ),
	array( 'en' => 'consulting (service)', 'pl' => 'doradztwo', 'not' => array( 'konsultingowi', 'konsulting', 'usługa Consulting', 'usługę Consulting' ) ),
	array( 'en' => 'benchmark status', 'pl' => 'status punktu odniesienia w branży', 'not' => array( 'status wzorca odniesienia', 'statusem wzorca odniesienia', 'status rozwiązań referencyjnych' ) ),
	array( 'en' => 'Machine tool control systems', 'pl' => 'Systemy sterowania obrabiarkami', 'not' => array( 'Systemy sterowania obrabiarkam', 'sterowania obrabiarkam' ) ),
	array( 'en' => 'gas engine (petrol)', 'pl' => 'silnik benzynowy', 'not' => array( 'silnika gazowego', 'silnik gazowy' ) ),
	array( 'en' => 'Launch (neutral-to-gear shift test)', 'pl' => 'Ruszanie', 'not' => array( 'Rozruch z biegu neutralnego', 'Rozruch z biegu' ) ),
	array( 'en' => 'commercial truck', 'pl' => 'samochód ciężarowy', 'not' => array( 'ciężarówkę komercyjną', 'ciężarówka komercyjna', 'ciężarówki komercyjnej' ) ),
	array( 'en' => 'gas compressor stations', 'pl' => 'tłocznie gazu', 'not' => array( 'stacje kompresorowe', 'stacja kompresorowa', 'stacji kompresorowych', 'stacje sprężarek', 'stacji sprężarek' ) ),
	array( 'en' => 'field instrumentation', 'pl' => 'aparatura kontrolno-pomiarowa', 'not' => array( 'instrumentacji polowej', 'instrumentacja polowa' ) ),
	array( 'en' => 'interface (human liaison with fleet users)', 'pl' => 'współpraca', 'not' => array( 'całościowym interfejsem', 'interfejs między użytkownikami', 'interfejsem między użytkownikami', 'interfejs do badań flotowych' ) ),
	array( 'en' => 'Swiss machining', 'pl' => 'obróbka na automatach tokarskich typu szwajcarskiego', 'not' => array( 'obróbki szwajcarskiej', 'obróbka szwajcarska' ) ),
	array( 'en' => 'mill/turn machines', 'pl' => 'centra tokarsko-frezarskie', 'not' => array( 'maszyny frezarsko-tokarskie', 'frezarsko-tokarskie' ) ),
	array( 'en' => 'Drilling Column', 'pl' => 'kolumna wiertarska', 'not' => array( 'Kolumna wiertnicza', 'kolumny wiertniczej' ) ),
	array( 'en' => 'single and dual mass flywheels', 'pl' => 'jedno- i dwumasowe koła zamachowe', 'not' => array( 'jednolitych i dwumasowych', 'jednoi dwumasowych', 'do jednolitych i dwumasowych' ) ),
	array( 'en' => 'vertical spindle', 'pl' => 'pionowe wrzeciono', 'not' => array( 'Pionowy wrzeciennik', 'wrzeciennik', 'wrzeciennika' ) ),
	array( 'en' => 'low pressure stage', 'pl' => 'stopień niskiego ciśnienia', 'not' => array( 'etapu niskiego ciśnienia', 'etap niskiego ciśnienia' ) ),
	array( 'en' => 'oil-free compressor', 'pl' => 'sprężarka bezolejowa', 'not' => array( 'kompresor', 'kompresora', 'kompresorem' ) ),
	array( 'en' => '(if equipped)', 'pl' => '(jeśli występuje)', 'not' => array( '(jeśli wyposażona)', 'jeśli wyposażona', '(jeśli dotyczy)' ) ),
	array( 'en' => 'Electric drive gearbox', 'pl' => 'przekładnia napędu elektrycznego', 'not' => array( 'Elektryczna skrzynia biegów z napędem', 'elektryczne skrzynie biegów z napędem elektrycznym', 'elektrycznej przekładni napędowej' ) ),
	array( 'en' => 'From here:', 'pl' => 'Stąd:', 'not' => array( 'Punkt wyjścia:' ) ),
	array( 'en' => 'reactions of the spurs', 'pl' => 'reakcje podpór', 'not' => array( 'reakcjami ostróg', 'reakcje ostróg' ) ),
	array( 'en' => 'Related from Balancing Textbook', 'pl' => 'Powiązane z podręcznika wyważania', 'not' => array( 'Na podstawie podręcznika wyważania' ) ),
	array( 'en' => 'high-performance culture', 'pl' => 'kultura wysokiej efektywności', 'not' => array( 'kultury wysokich parametrów', 'kultura wysokich parametrów' ) ),
	array( 'en' => 'performance-driven processes', 'pl' => 'procesy zorientowane na wyniki', 'not' => array( 'procesy zorientowane na parametry' ) ),
	array( 'en' => 'Winbal touchscreen', 'pl' => 'Winbal z ekranem dotykowym', 'not' => array( 'Winbal touchscreen' ) ),
	array( 'en' => 'Automatic grinder control', 'pl' => 'Automatyczny sterownik szlifierki', 'not' => array( 'Automatyczne sterowanie szlifierką' ) ),
	array( 'en' => 'Profile grinder control PGC9400', 'pl' => 'Sterownik szlifierki profilowej PGC9400', 'not' => array( 'Profile grinder control PGC9400', 'Sterownik szlifierki do profili' ) ),
	array( 'en' => 'Cast Iron Valve Test', 'pl' => 'Badanie zaworów żeliwnych', 'not' => array( 'systemu testowego Cast Iron Valve Test', 'Cast Iron Valve Test' ) ),
	array( 'en' => 'Universal Valve Test', 'pl' => 'Uniwersalne stanowisko do badania zaworów', 'not' => array( 'Uniwersalny test zaworów', 'uniwersalnego systemu testowego zaworów', 'system testowy Universal Valve Test' ) ),
	array( 'en' => 'GEDA (Galileo Equipment Data Acquisition)', 'pl' => 'GEDA (Galileo Equipment Data Acquisition)', 'not' => array( 'galileo equipment data acquisition' ) ),
	array( 'en' => 'legislative diagnostic documentation review', 'pl' => 'przegląd dokumentacji diagnostycznej wymaganej przepisami', 'not' => array( 'legislacyjnej dokumentacji diagnostycznej', 'legislacyjna dokumentacja diagnostyczna', 'pod kątem wymogów prawnych' ) ),
	array( 'en' => 'regulatory agency', 'pl' => 'organ regulacyjny', 'not' => array( 'agencji regulacyjnej', 'agencja regulacyjna' ) ),
	array( 'en' => 'universally applicable', 'pl' => 'uniwersalne zastosowanie', 'not' => array( 'uniwersalna stosowalność', 'stosowalność' ) ),
	array( 'en' => 'mass flow metering technology', 'pl' => 'technologia pomiaru przepływu masowego', 'not' => array( 'technologia masowego pomiaru przepływu', 'masowego pomiaru przepływu' ) ),
	array( 'en' => 'No. Dosing mass flow meter device', 'pl' => 'Liczba dozujących przepływomierzy masowych', 'not' => array( 'Liczba urządzeń dozującego przepływomierza masowego' ) ),
	array( 'en' => 'integral valves', 'pl' => 'układy zaworów zintegrowanych', 'not' => array( 'zaworów integralnych', 'zawory integralne' ) ),
	array( 'en' => 'stem stickiness / bucket-shovel pair', 'pl' => 'łyżka/łopata', 'not' => array( 'łyżki/czerpaka', 'łyżka/czerpak' ) ),
	array( 'en' => 'bed (balancing machine)', 'pl' => 'łoże', 'not' => array( 'BED 6400 MM', 'wyważarki łożyskowe', 'poziome wyważarki łożyskowe' ) ),
	array( 'en' => 'MU 60 runs @ 95%', 'pl' => 'MU 60 przebiegów przy 95%', 'not' => array( 'przebiegów @ 95%', '60 przebiegów @ 95%' ) ),
	array( 'en' => 'Functionality (table column header)', 'pl' => 'Funkcja', 'not' => array( 'Funkcje | Opis' ) ),
	array( 'en' => 'high-speed core (balancing)', 'pl' => 'wysokoobrotowy rdzeń', 'not' => array( 'szybkoobrotowego rdzenia', 'szybkoobrotowy rdzeń' ) ),
	array( 'en' => 'core assembly (turbocharger)', 'pl' => 'zespół rdzenia', 'not' => array( 'do montażu rdzeni', 'montażu rdzeni turbosprężarek' ) ),
	array( 'en' => 'steerable dyno', 'pl' => 'hamownia kierowalna', 'not' => array( 'hamowni kierowanej', 'hamownia kierowana' ) ),
	array( 'en' => 'Railway balancing brochure', 'pl' => 'Broszura dotycząca wyważania w kolejnictwie', 'not' => array( 'wyważanie kolejowe', 'wyważania kolejowego' ) ),
	array( 'en' => 'complete solutions', 'pl' => 'kompleksowe rozwiązania', 'not' => array( 'kompletne rozwiązania', 'kompletnych rozwiązań' ) ),
	array( 'en' => 'cold rolling mills / hot rolling mills', 'pl' => 'walcownie na zimno i na gorąco', 'not' => array( 'walcowni gorących i zimnych', 'walcownie gorące i zimne' ) ),
	array( 'en' => 'Custom testing applications', 'pl' => 'Niestandardowe zastosowania badawcze', 'not' => array( 'Niestandardowe aplikacje do badań', 'aplikacje do badań' ) ),
	array( 'en' => 'Complex testing process representation', 'pl' => 'Odwzorowanie złożonego procesu badań', 'not' => array( 'Reprezentacja złożonego procesu badań', 'Reprezentacja złożonych procesów' ) ),
	array( 'en' => 'assembly operations (machine)', 'pl' => 'operacje montażowe', 'not' => array( 'działalność montażowa jest sterowana', 'działalność wyważająca', 'czasu prowadzenia działalności wyważającej' ) ),
	array( 'en' => 'self-learning unbalance algorithm', 'pl' => 'algorytm samouczący się do wykrywania niewyważenia', 'not' => array( 'algorytm samouczący się niewyważenia' ) ),
	array( 'en' => 'bearer centre line', 'pl' => 'oś podpory', 'not' => array( 'Minimalna odległość między osiami łożysk' ) ),
	array( 'en' => 'Backhoe (product page name)', 'pl' => 'koparko-ładowarka', 'not' => array( 'systemu Backhoe', 'system Backhoe' ) ),
	array( 'en' => 'Bulldozer (product page name)', 'pl' => 'spycharka', 'not' => array( 'systemu Bulldozer', 'walidacji Bulldozer' ) ),
	array( 'en' => 'Windrower (product page name)', 'pl' => 'kosiarka pokosowa', 'not' => array( 'system Windrower', 'systemu Windrower', 'systemem Windrower' ) ),
	array( 'en' => 'Axle Test Stands', 'pl' => 'Stanowiska do badań osi', 'not' => array( 'NVH Axle Test Stands', 'Axle Test Stands' ) ),
	array( 'en' => 'Fan & Motor Balancing Machine', 'pl' => 'Wyważarka do wentylatorów i silników', 'not' => array( 'Maszyna do wyważania wentylatorów i silników' ) ),
	array( 'en' => 'Balancing machine for electric motor rotors', 'pl' => 'Wyważarka do wirników silników elektrycznych', 'not' => array( 'wyważania tworników silników elektrycznych', 'tworników silników elektrycznych' ) ),
);
