<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * Polish term base (en -> pl). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried
 * and never stored. Source: 100-page blind review, 2026-09-25.
 */
return array(
	array( 'en' => '20-high / six-high mill', 'pl' => 'walcarka 20-walcowa / 6-walcowa', 'not' => array( 'walcarka dwudziestościowa', 'walcarka sześciościowa' ) ),
	array( 'en' => '3-jaw chuck', 'pl' => 'uchwyt trójszczękowy', 'not' => array( 'uchwyt trzyczęściowy' ) ),
	array( 'en' => 'A DESIGN / B LOGO (trademarks)', 'pl' => 'A DESIGN / B LOGO', 'not' => array( 'PROJEKT A', 'LOGO B' ) ),
	array( 'en' => 'active part probing', 'pl' => 'aktywny pomiar detalu', 'not' => array( 'aktywne sondowanie części' ) ),
	array( 'en' => 'actuation systems', 'pl' => 'układy wykonawcze', 'not' => array( 'systemy aktywacji' ) ),
	array( 'en' => 'adaptive speed control', 'pl' => 'adaptacyjna regulacja prędkości', 'not' => array( 'adaptacyjna kontrola prędkości' ) ),
	array( 'en' => 'ADAS (advanced driver assistance systems)', 'pl' => 'systemy wspomagania kierowcy (ADAS)', 'not' => array( 'systemy wsparcia kierowcy' ) ),
	array( 'en' => 'ADAS alignment', 'pl' => 'kalibracja ADAS', 'not' => array( 'wyrównanie ADAS' ) ),
	array( 'en' => 'ADVANCING THE MACHINE (trademark)', 'pl' => 'ADVANCING THE MACHINE', 'not' => array( 'NAPĘDZAJĄC MASZYNĘ' ) ),
	array( 'en' => 'air cycle machines', 'pl' => 'turbochłodziarki powietrza', 'not' => array( 'maszyny cyklu powietrza' ) ),
	array( 'en' => 'anchoring (machine foundation)', 'pl' => 'zakotwienie', 'not' => array( 'zakotwiczenie' ) ),
	array( 'en' => 'aperture plate', 'pl' => 'płyta otworowa', 'not' => array( 'płyta otwarcia' ) ),
	array( 'en' => 'applications (use cases)', 'pl' => 'zastosowania', 'not' => array( 'aplikacje' ) ),
	array( 'en' => 'armature', 'pl' => 'twornik', 'not' => array( 'wirnik elektryczny' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES (trademark)', 'pl' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDYCYNA I NAUKI PRZYRODNICZE', 'Ascential – Medycyna i nauki przyrodnicze' ) ),
	array( 'en' => 'Ascential Test & Measurement (Systems)', 'pl' => 'Ascential Test & Measurement (Systems)', 'not' => array( 'Ascential Systemy kontrolno-pomiarowe', 'Ascential Systemów Kontrolno-Pomiarowych', 'dział Systemów Kontrolno-Pomiarowych' ) ),
	array( 'en' => 'Ask Burke Porter (page name)', 'pl' => 'Ask Burke Porter', 'not' => array( 'Zapytaj Burke Porter' ) ),
	array( 'en' => 'associate attorney', 'pl' => 'prawnik współpracujący', 'not' => array( 'asystent adwokata' ) ),
	array( 'en' => 'audit stations', 'pl' => 'stanowiska audytowe (kontrolno-pomiarowe)', 'not' => array( 'stanowiska kontrolne' ) ),
	array( 'en' => 'automated handling cells', 'pl' => 'zautomatyzowane gniazda manipulacyjne', 'not' => array( 'komórki manipulacyjne' ) ),
	array( 'en' => 'backhoe', 'pl' => 'koparko-ładowarka', 'not' => array( 'kopiarka gąsienicowa' ) ),
	array( 'en' => 'baler', 'pl' => 'prasa do belowania', 'not' => array( 'prasownica' ) ),
	array( 'en' => 'bead breaking', 'pl' => 'zrywanie stopki opony', 'not' => array( 'rozbijanie opaski' ) ),
	array( 'en' => 'bearers (balancer supports)', 'pl' => 'podpory', 'not' => array( 'łożyska' ) ),
	array( 'en' => 'bearing center lines', 'pl' => 'osie łożysk', 'not' => array( 'osie czopów' ) ),
	array( 'en' => 'bearing life', 'pl' => 'trwałość łożyska', 'not' => array( 'czas życia łożyska' ) ),
	array( 'en' => 'blade (grader)', 'pl' => 'lemiesz', 'not' => array( 'ostrze' ) ),
	array( 'en' => 'blank ECM', 'pl' => 'niezaprogramowany sterownik ECM', 'not' => array( 'pusty ECM' ) ),
	array( 'en' => 'blast furnace', 'pl' => 'wielki piec', 'not' => array( 'piec wysoki' ) ),
	array( 'en' => 'blowers', 'pl' => 'dmuchawy', 'not' => array( 'wentylatory' ) ),
	array( 'en' => 'bore axis alignment', 'pl' => 'ustawienie osi wiązki (celowania anteny)', 'not' => array( 'wyrównanie osi otworu' ) ),
	array( 'en' => 'boreless compressor wheel', 'pl' => 'koło sprężarki bez otworu centralnego', 'not' => array( 'turbosprężarka bez łożysk ślizgowych' ) ),
	array( 'en' => 'boring (machining)', 'pl' => 'wytaczanie', 'not' => array( 'wiercenie' ) ),
	array( 'en' => 'boring drill (HDD)', 'pl' => 'wiertnica (głowica wiertnicza)', 'not' => array( 'wiertło wiercące' ) ),
	array( 'en' => 'branch (in an LMS)', 'pl' => 'przestrzeń (gałąź) w systemie LMS', 'not' => array( 'oddział' ) ),
	array( 'en' => 'Bristol (city)', 'pl' => 'Bristol', 'not' => array( 'Brystol' ) ),
	array( 'en' => 'built to last', 'pl' => 'stworzone z myślą o długiej żywotności', 'not' => array( 'zbudowane na długość' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'pl' => 'Burke E. Porter Machinery', 'not' => array( 'Burke Porter – Maszyny' ) ),
	array( 'en' => 'Burke Porter Group', 'pl' => 'Burke Porter Group', 'not' => array( 'Grupa Burke Porter' ) ),
	array( 'en' => 'burst proof protection', 'pl' => 'odporność na rozerwanie wirnika', 'not' => array( 'ochrona przed wybuchem' ) ),
	array( 'en' => 'calibration target', 'pl' => 'tarcza kalibracyjna', 'not' => array( 'wieszak na cele', 'wyrównanie celu' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'pl' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Kalibracja jako usługa™', 'model Kalibracji jako Usługi™' ) ),
	array( 'en' => 'capital equipment', 'pl' => 'dobra inwestycyjne', 'not' => array( 'urządzenia kapitałowe' ) ),
	array( 'en' => 'cargo loading systems', 'pl' => 'systemy załadunku towarów', 'not' => array( 'systemy załadunku ładunku' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'pl' => 'hamownie podwoziowe 2- i 4-kołowe', 'not' => array( 'hamownie podwoziowe 2- i 4-osiowe' ) ),
	array( 'en' => 'chip vacuum', 'pl' => 'odciąg wiórów', 'not' => array( 'odkurzacz wiórów' ) ),
	array( 'en' => 'clay gun', 'pl' => 'zatykarka otworu spustowego', 'not' => array( 'maszyna do formowania gliny' ) ),
	array( 'en' => 'CMT-TR Polimer (model code)', 'pl' => 'CMT-TR Polimer', 'not' => array( 'wyważarka wirników polimerowych' ) ),
	array( 'en' => 'cold pilger mill', 'pl' => 'walcarka pielgrzymowa na zimno', 'not' => array( 'walcarka pilgerów na zimno' ) ),
	array( 'en' => 'collet chuck', 'pl' => 'uchwyt tulejowy (collet)', 'not' => array( 'uchwyt zaciskowy powietrzny', 'uchwyt pneumatyczny' ) ),
	array( 'en' => 'combine (harvester)', 'pl' => 'kombajn', 'not' => array( 'prasa zbioru' ) ),
	array( 'en' => 'commercial vehicle', 'pl' => 'pojazd użytkowy', 'not' => array( 'pojazd handlowy', 'turbosprężarka handlowa' ) ),
	array( 'en' => 'commissioning', 'pl' => 'rozruch (uruchomienie)', 'not' => array( 'komisjonowanie' ) ),
	array( 'en' => 'Connect on LinkedIn', 'pl' => 'Profil na LinkedIn', 'not' => array( 'Connect on LinkedIn' ) ),
	array( 'en' => 'control (of a process)', 'pl' => 'sterowanie', 'not' => array( 'kontrola' ) ),
	array( 'en' => 'control module', 'pl' => 'moduł sterowania', 'not' => array( 'moduł kontroli' ) ),
	array( 'en' => 'controls (control systems)', 'pl' => 'układy sterowania', 'not' => array( 'sterowniki', 'system kontrolny' ) ),
	array( 'en' => 'Core / Plus / Elite (service tiers)', 'pl' => 'Core, Plus, Elite', 'not' => array( 'Podstawowy, Plus, Elite' ) ),
	array( 'en' => 'Corporate Roles', 'pl' => 'Funkcje korporacyjne', 'not' => array( 'Role Kierownicze' ) ),
	array( 'en' => 'correction (of unbalance)', 'pl' => 'korekcja', 'not' => array( 'korekta' ) ),
	array( 'en' => 'crankshaft lathe', 'pl' => 'tokarka do wałów korbowych', 'not' => array( 'tokarka do korbowodów' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'pl' => 'Kruispuntbank van Ondernemingen (Crossroads Bank for Enterprises)', 'not' => array( 'Krajowy Rejestr Przedsiębiorstw' ) ),
	array( 'en' => 'cushion testing', 'pl' => 'badanie amortyzacji końcowej (dławienia)', 'not' => array( 'testowanie poduszki' ) ),
	array( 'en' => 'custom fixturing', 'pl' => 'oprzyrządowanie (uchwyty obróbkowe)', 'not' => array( 'urządzenia pomocnicze' ) ),
	array( 'en' => 'customer journey', 'pl' => 'współpraca (etapy współpracy)', 'not' => array( 'podróż klienta' ) ),
	array( 'en' => 'Date: (signature block)', 'pl' => 'Data:', 'not' => array( 'Dane:' ) ),
	array( 'en' => 'deep hole drilling', 'pl' => 'wiercenie głębokich otworów', 'not' => array( 'głębokie otwory' ) ),
	array( 'en' => 'defensible (results)', 'pl' => 'możliwe do obronienia podczas audytu', 'not' => array( 'możliwe do obrony' ) ),
	array( 'en' => 'Deliverables (defined term)', 'pl' => 'Rezultaty Prac (jeden niezmienny ciąg)', 'not' => array( 'Dostarczane Wyniki', 'Dostarczalny', 'Dostarczenia', 'Dostarczany element' ) ),
	array( 'en' => 'deployment (of a machine)', 'pl' => 'uruchomienie (instalacja)', 'not' => array( 'wdrożenie' ) ),
	array( 'en' => 'design (of a machine)', 'pl' => 'konstrukcja', 'not' => array( 'projekt' ) ),
	array( 'en' => 'dial indicator', 'pl' => 'czujnik zegarowy', 'not' => array( 'miernik ścieżki' ) ),
	array( 'en' => 'disability insurance', 'pl' => 'ubezpieczenie na wypadek niezdolności do pracy', 'not' => array( 'renta inwalidztwa' ) ),
	array( 'en' => 'discrete industries', 'pl' => 'sektory produkcji dyskretnej', 'not' => array( 'branże dyskretne' ) ),
	array( 'en' => 'draper header', 'pl' => 'heder taśmowy', 'not' => array( 'głowica żniwna prasy zbioru', 'rozrzutnik' ) ),
	array( 'en' => 'drift (cylinder)', 'pl' => 'opadanie tłoka', 'not' => array( 'dryfowanie' ) ),
	array( 'en' => 'drivability', 'pl' => 'właściwości jezdne', 'not' => array( 'prowadzenie' ) ),
	array( 'en' => 'dual mass flywheel', 'pl' => 'dwumasowe koło zamachowe', 'not' => array( 'dwumasowe sprzęgło bezwładności', 'sprzęgło dwumasowe', 'dwumasy' ) ),
	array( 'en' => 'dynamometer', 'pl' => 'hamownia', 'not' => array( 'dynamometr', 'dynamometr podwozia pojazdu' ) ),
	array( 'en' => 'eddy current technology', 'pl' => 'technologia prądów wirowych', 'not' => array(  ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'pl' => 'maszyny do elektroerozji (EDT)', 'not' => array( 'maszyny do elektroerozyji' ) ),
	array( 'en' => 'Email Disclosure (page name)', 'pl' => 'Klauzula poufności wiadomości e-mail', 'not' => array( 'Ujawnienie adresu e-mail' ) ),
	array( 'en' => 'EMC darkroom', 'pl' => 'komora ekranowana (bezodbiciowa)', 'not' => array( 'ciemnia' ) ),
	array( 'en' => 'end of line testing', 'pl' => 'testy na końcu linii produkcyjnej', 'not' => array( 'testy końcowe linii produkcyjnej' ) ),
	array( 'en' => 'energy recuperation', 'pl' => 'rekuperacja energii', 'not' => array( 'regeneracja energii' ) ),
	array( 'en' => 'engine software loaders', 'pl' => 'urządzenia do wgrywania oprogramowania silników', 'not' => array( 'programy ładujące silniki' ) ),
	array( 'en' => 'eRotor (product line)', 'pl' => 'eRotor', 'not' => array( 'wirniki pojazdów elektrycznych' ) ),
	array( 'en' => 'events & conferences', 'pl' => 'wydarzenia i konferencje', 'not' => array( 'imprezy i konferencje' ) ),
	array( 'en' => 'excavator', 'pl' => 'koparka', 'not' => array( 'kopiarka' ) ),
	array( 'en' => 'exhaust extraction', 'pl' => 'odciąg spalin', 'not' => array( 'ekstrakcja spalin' ) ),
	array( 'en' => 'factory floor', 'pl' => 'hala produkcyjna', 'not' => array( 'hala produkcji' ) ),
	array( 'en' => 'failure rates (calibration)', 'pl' => 'odsetek nieprawidłowych kalibracji', 'not' => array( 'wskaźniki awarii' ) ),
	array( 'en' => 'features (of a machine)', 'pl' => 'cechy (wyposażenie)', 'not' => array( 'funkcje' ) ),
	array( 'en' => 'Featuring: <Brand>', 'pl' => 'Z udziałem: <Brand>', 'not' => array( 'Featuring: Bauer' ) ),
	array( 'en' => 'field agents', 'pl' => 'technicy terenowi', 'not' => array( 'agenci' ) ),
	array( 'en' => 'field balancing', 'pl' => 'wyważanie w miejscu zabudowy (na obiekcie)', 'not' => array( 'wyważanie w terenie' ) ),
	array( 'en' => 'filler (charging station)', 'pl' => 'stanowisko napełniania / napełniarka', 'not' => array( 'napełniacz' ) ),
	array( 'en' => 'filler gun', 'pl' => 'pistolet napełniający', 'not' => array( 'pistolecik dozujący' ) ),
	array( 'en' => 'final discharge', 'pl' => 'końcowy zrzut gazu', 'not' => array( 'ostateczne rozładowanie' ) ),
	array( 'en' => 'fine leak', 'pl' => 'drobna nieszczelność', 'not' => array( 'szczelność precyzyjna', 'nieszczelność drobna (odwrócony szyk)' ) ),
	array( 'en' => 'flexplate', 'pl' => 'tarcza napędowa (flexplate)', 'not' => array( 'sprzęgło dwumasowe' ) ),
	array( 'en' => 'fluid power', 'pl' => 'hydraulika siłowa', 'not' => array( 'napędy płynowe', 'napęd płynowy', 'napęd hydrauliczny' ) ),
	array( 'en' => 'flywheel', 'pl' => 'koło zamachowe', 'not' => array( 'sprzęgło bezwładności', 'dwumasa' ) ),
	array( 'en' => 'footprint (floor area)', 'pl' => 'powierzchnia', 'not' => array( 'rozmiar' ) ),
	array( 'en' => 'For Immediate Release', 'pl' => 'Informacja prasowa – do natychmiastowej publikacji', 'not' => array( 'Do natychmiastowego opublikowania' ) ),
	array( 'en' => 'forged rolls', 'pl' => 'walce kute', 'not' => array( 'walce kuowane' ) ),
	array( 'en' => 'front strut (suspension)', 'pl' => 'przednia kolumna zawieszenia', 'not' => array( 'przedni słupek', 'przedni zacisk', 'zaciąg hydrauliczny' ) ),
	array( 'en' => 'gantry (loading)', 'pl' => 'manipulator portalowy / portal', 'not' => array( 'brama portalowa', 'brama portalowa typu pick-and-place' ) ),
	array( 'en' => 'GDPR', 'pl' => 'RODO', 'not' => array( 'GDPR' ) ),
	array( 'en' => 'gear shift calibration', 'pl' => 'kalibracja zmiany biegów', 'not' => array( 'kalibracja przesunięcia biegów' ) ),
	array( 'en' => 'grinding wheel', 'pl' => 'ściernica', 'not' => array( 'tarcza szlifierska' ) ),
	array( 'en' => 'gross leak test', 'pl' => 'test nieszczelności zgrubnych', 'not' => array( 'test nieszczelności brutto', 'testy szczelności mechanicznej i brutto' ) ),
	array( 'en' => 'gundrill', 'pl' => 'wiertło lufowe (gundrill)', 'not' => array( 'konfiguracje gundrillowe' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'pl' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Sp. z o.o.' ) ),
	array( 'en' => 'half case (RDU/PTU)', 'pl' => 'obudowa dzielona', 'not' => array( 'półosiowy' ) ),
	array( 'en' => 'hay mower', 'pl' => 'kosiarka', 'not' => array( 'kosarka' ) ),
	array( 'en' => 'hazardous area', 'pl' => 'strefa zagrożona wybuchem', 'not' => array( 'obszar zagrożony' ) ),
	array( 'en' => 'health checks', 'pl' => 'przeglądy stanu technicznego', 'not' => array( 'kontrole zdrowotne' ) ),
	array( 'en' => 'high production / high-volume production', 'pl' => 'produkcja wielkoseryjna', 'not' => array( 'produkcja wysokoobiegowa', 'produkcja wysokotonażowa', 'linie wysokowydajne', 'duże wolumeny produkcji' ) ),
	array( 'en' => 'high-mix, low-volume', 'pl' => 'produkcja wielowariantowa i małoseryjna', 'not' => array( 'środowiska o dużej różnorodności, niskich wolumenach' ) ),
	array( 'en' => 'high-performance teams', 'pl' => 'zespoły o wysokiej efektywności', 'not' => array( 'zespoły wysokiej wydajności' ) ),
	array( 'en' => 'higher-level control system', 'pl' => 'nadrzędny system sterowania', 'not' => array( 'wyższy system kontrolny' ) ),
	array( 'en' => 'HMU/FMU', 'pl' => 'zespoły HMU/FMU (hydromechaniczne i dozujące paliwo)', 'not' => array(  ) ),
	array( 'en' => 'idle duration', 'pl' => 'czas pracy na biegu jałowym', 'not' => array( 'czas bezczynności' ) ),
	array( 'en' => 'implements', 'pl' => 'osprzęt (maszyny towarzyszące)', 'not' => array( 'implementy', 'maszyny (kolidujące z inną gałęzią taksonomii)' ) ),
	array( 'en' => 'Imprint', 'pl' => 'Nota prawna', 'not' => array( 'Imprint (pozostawione)' ) ),
	array( 'en' => 'in a single clamping', 'pl' => 'w jednym zamocowaniu', 'not' => array( 'w jednym zacisku' ) ),
	array( 'en' => 'infeed (grinding)', 'pl' => 'posuw', 'not' => array( 'infeed' ) ),
	array( 'en' => 'infinitely variable', 'pl' => 'płynnie regulowany', 'not' => array( 'nieskończenie zmienny' ) ),
	array( 'en' => 'inline crankshaft', 'pl' => 'wał rzędowy', 'not' => array( 'wał czterosuwowy' ) ),
	array( 'en' => 'inline dyno', 'pl' => 'hamownia szeregowa', 'not' => array( 'hamownia wbudowana' ) ),
	array( 'en' => 'insights', 'pl' => 'wnioski', 'not' => array( 'wglądy', 'wskazówki' ) ),
	array( 'en' => 'instrument cluster', 'pl' => 'zestaw wskaźników', 'not' => array( 'klaster instrumentów', 'zestaw przyrządów' ) ),
	array( 'en' => 'keg finger holes', 'pl' => 'otwory chwytowe', 'not' => array( 'otwory palcowe' ) ),
	array( 'en' => 'kinetostatics', 'pl' => 'kinetostatyka', 'not' => array( 'kinetyka' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'pl' => 'Izba Handlowa (KvK)', 'not' => array( 'Izba Handlowo-Przemysłowa (KvK)' ) ),
	array( 'en' => 'Labour & Travel', 'pl' => 'Robocizna i dojazdy', 'not' => array( 'Praca i podróże' ) ),
	array( 'en' => 'landed cost model', 'pl' => 'model kosztu dostarczonego (landed cost)', 'not' => array( 'model kosztu dostawy' ) ),
	array( 'en' => 'landing gear systems', 'pl' => 'układy podwozia', 'not' => array( 'systemy podwozia lądowania' ) ),
	array( 'en' => 'leak detection', 'pl' => 'wykrywanie nieszczelności', 'not' => array( 'detekcja wycieków', 'wykrywanie wycieków', 'detektor przecieków', 'testy szczelności' ) ),
	array( 'en' => 'learning management system (LMS)', 'pl' => 'system zarządzania szkoleniami (LMS)', 'not' => array( 'system zarządzania nauką' ) ),
	array( 'en' => 'like-minded companies', 'pl' => 'firmy o zbieżnej wizji', 'not' => array( 'firmy o podobnych poglądach' ) ),
	array( 'en' => 'load capacity', 'pl' => 'obciążalność', 'not' => array( 'pojemność' ) ),
	array( 'en' => 'LPM (litres per minute)', 'pl' => 'l/min', 'not' => array(  ) ),
	array( 'en' => 'lube & scavenge pumps', 'pl' => 'pompy smarowania i odsysania oleju', 'not' => array( 'pompy smarowania i odpowietrzania' ) ),
	array( 'en' => 'lubrication', 'pl' => 'smarowanie', 'not' => array( 'wymiana oleju' ) ),
	array( 'en' => 'machine tools', 'pl' => 'obrabiarki', 'not' => array( 'maszyny technologiczne', 'maszyny do obróbki' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'pl' => 'dyrektywa maszynowa 2006/42/WE', 'not' => array(  ) ),
	array( 'en' => 'machining cell', 'pl' => 'gniazdo obróbcze', 'not' => array( 'gniazdo produkcyjne', 'komórka manipulacyjna' ) ),
	array( 'en' => 'machinist', 'pl' => 'wykwalifikowany operator obrabiarek', 'not' => array( 'operator' ) ),
	array( 'en' => 'maintenance contracts', 'pl' => 'umowy serwisowe', 'not' => array( 'umowy konserwacyjne' ) ),
	array( 'en' => 'marine (sector)', 'pl' => 'przemysł morski', 'not' => array( 'żegluga' ) ),
	array( 'en' => 'maximum rotor diameter', 'pl' => 'maksymalna średnica wirnika', 'not' => array( 'maksymalny rozmiar wirnika' ) ),
	array( 'en' => 'mental health care', 'pl' => 'opieka w zakresie zdrowia psychicznego', 'not' => array( 'zdalna opieka zdrowotna' ) ),
	array( 'en' => 'mill roll', 'pl' => 'walec', 'not' => array(  ) ),
	array( 'en' => 'misalignment (sensors)', 'pl' => 'odchylenie w ustawieniu czujników', 'not' => array( 'niedostatki w wyrównaniu' ) ),
	array( 'en' => 'motor grader', 'pl' => 'równiarka', 'not' => array( 'kopiarka gruntowa', 'Motor Graders (pozostawione)' ) ),
	array( 'en' => 'motorized clamping', 'pl' => 'mocowanie z napędem elektrycznym', 'not' => array( 'zmotoryzowane mocowanie' ) ),
	array( 'en' => 'MRO', 'pl' => 'organizacje MRO', 'not' => array( 'serwis i części zamienne' ) ),
	array( 'en' => 'mudding system (HDD)', 'pl' => 'system płuczki wiertniczej', 'not' => array( 'system błota' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'pl' => 'naamloze vennootschap (bez tłumaczenia)', 'not' => array( 'spółka akcyjna' ) ),
	array( 'en' => 'Name: (signature block)', 'pl' => 'Imię i nazwisko:', 'not' => array( 'Nazwa:' ) ),
	array( 'en' => 'Netherlands (statutory)', 'pl' => 'Niderlandy', 'not' => array( 'Holandia' ) ),
	array( 'en' => 'non-rotating balancing machine', 'pl' => 'wyważarka bezobrotowa', 'not' => array( 'wyważarka bez wirnika' ) ),
	array( 'en' => 'obsolescence management', 'pl' => 'zarządzanie wycofywaniem komponentów', 'not' => array( 'zarządzanie przestarzałością' ) ),
	array( 'en' => 'off-highway', 'pl' => 'maszyny pozadrogowe', 'not' => array( 'maszyny budowlane', 'maszyny robocze' ) ),
	array( 'en' => 'oil drain', 'pl' => 'spust oleju', 'not' => array( 'otwór odpowietrzający' ) ),
	array( 'en' => 'operations (business/plant)', 'pl' => 'działalność (zakład, praca zakładu)', 'not' => array( 'operacje' ) ),
	array( 'en' => 'opportunities', 'pl' => 'możliwości (szanse)', 'not' => array( 'oportuniści' ) ),
	array( 'en' => 'patented', 'pl' => 'opatentowany', 'not' => array( 'patentowany' ) ),
	array( 'en' => 'pedestals', 'pl' => 'podpory / stojaki', 'not' => array( 'piedestały' ) ),
	array( 'en' => 'peers', 'pl' => 'inni specjaliści z branży', 'not' => array( 'rówieśnicy' ) ),
	array( 'en' => 'performance (functional)', 'pl' => 'parametry (działanie, osiągi)', 'not' => array( 'wydajność' ) ),
	array( 'en' => 'personal information / personal data', 'pl' => 'dane osobowe', 'not' => array( 'informacje osobiste' ) ),
	array( 'en' => 'pinches & bruises', 'pl' => 'zgniecenia i wgniecenia', 'not' => array( 'ścieśnienia i stłuczenia' ) ),
	array( 'en' => 'pinion gear', 'pl' => 'zębnik', 'not' => array( 'czop' ) ),
	array( 'en' => 'pins (on pedestals)', 'pl' => 'kołki', 'not' => array( 'czopy' ) ),
	array( 'en' => 'power drive units', 'pl' => 'jednostki napędowe (PDU)', 'not' => array( 'jednostki napędu mocy' ) ),
	array( 'en' => 'Powered by', 'pl' => 'Oparte na', 'not' => array( 'Zasilana', 'Napędzane' ) ),
	array( 'en' => 'President (of a company)', 'pl' => 'prezes', 'not' => array( 'prezydent' ) ),
	array( 'en' => 'pressurization', 'pl' => 'ciśnieniowanie', 'not' => array( 'presuryzacja (mieszane z ciśnieniowaniem na jednej stronie)' ) ),
	array( 'en' => 'probe alignment', 'pl' => 'ustawienie (pozycjonowanie) sondy', 'not' => array( 'wyrównanie sondy' ) ),
	array( 'en' => 'process recipe', 'pl' => 'receptura', 'not' => array( 'recepta' ) ),
	array( 'en' => 'propulsion & powertrain', 'pl' => 'napęd i układ przeniesienia mocy', 'not' => array( 'Napęd i Układ napędowy', 'napęd i napęd', 'Napęd' ) ),
	array( 'en' => 'PTO (power take-off)', 'pl' => 'wał odbioru mocy (WOM)', 'not' => array( 'wał odbiornika mocy' ) ),
	array( 'en' => 'pulley', 'pl' => 'koło pasowe', 'not' => array( 'pasek', 'koło pasków', 'pasek klinowy' ) ),
	array( 'en' => 'punching (mass correction)', 'pl' => 'wykrawanie', 'not' => array( 'przecinanie', 'przeciskanie' ) ),
	array( 'en' => 'push and pull (thrust/pullback)', 'pl' => 'napór i wyciąganie', 'not' => array( 'ciśnienie i rozciąganie' ) ),
	array( 'en' => 'reconditioning (rolls)', 'pl' => 'regeneracja walców', 'not' => array( 'renowacja' ) ),
	array( 'en' => 'refrigerant', 'pl' => 'czynnik chłodniczy', 'not' => array( 'chłodziwo', 'chłodnik', 'chłodziv' ) ),
	array( 'en' => 'refrigerant charging', 'pl' => 'napełnianie czynnikiem chłodniczym', 'not' => array( 'ładowanie chłodziwem', 'napełnianie chłodziwem', 'załadunek czynnika chłodniczego', 'ładowanie czynnika chłodniczego' ) ),
	array( 'en' => 'refrigeration (sector)', 'pl' => 'chłodnictwo', 'not' => array( 'chłodzenie' ) ),
	array( 'en' => 'Register (a legal register)', 'pl' => 'Rejestr', 'not' => array( 'Zarejestruj się' ) ),
	array( 'en' => 'Registered office', 'pl' => 'Siedziba', 'not' => array( 'Siedziba zarejestrowana', 'Adres zarejestrowany' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'pl' => 'zakłady regeneracji i naprawy', 'not' => array( 'producenci regeneracyjni i naprawcy' ) ),
	array( 'en' => 'remarketers', 'pl' => 'pośrednicy w odsprzedaży flot', 'not' => array( 'pośrednicy obrotu wtórnego' ) ),
	array( 'en' => 'reportable', 'pl' => 'udokumentowane', 'not' => array( 'raportowalne' ) ),
	array( 'en' => 'represent (model a process)', 'pl' => 'odwzorować', 'not' => array( 'reprezentować' ) ),
	array( 'en' => 'residual unbalance', 'pl' => 'niewyważenie szczątkowe', 'not' => array( 'resztkowa nierównowaga', 'minimalna pozostała nierównowaga', 'niezrównoważoność resztkowa', 'maksymalna dopuszczalna nierównowaga' ) ),
	array( 'en' => 'responsive', 'pl' => 'szybko reagujący', 'not' => array( 'responsywny' ) ),
	array( 'en' => 'restbus simulation', 'pl' => 'symulacja magistrali szczątkowej (restbus)', 'not' => array( 'symulacja magistrali rezydualnej' ) ),
	array( 'en' => 'retaining rollers', 'pl' => 'rolki podtrzymujące', 'not' => array( 'wałki retencyjne', 'walce retencyjne' ) ),
	array( 'en' => 'right-shoring', 'pl' => 'right-shoring', 'not' => array( 'optymalizacja webinaru', 'optymalizacja łańcucha dostaw' ) ),
	array( 'en' => 'roll inspection', 'pl' => 'kontrola walców', 'not' => array( 'kontrola rolek' ) ),
	array( 'en' => 'Roll Shop Technologies (page title)', 'pl' => 'Technologie szlifierni walców', 'not' => array( 'Roll Shop Technologies' ) ),
	array( 'en' => 'roller (brake tester)', 'pl' => 'rolka', 'not' => array( 'wałek' ) ),
	array( 'en' => 'roller brake tester', 'pl' => 'rolkowe stanowisko do badania hamulców', 'not' => array( 'testery hamulców wałkowych' ) ),
	array( 'en' => 'rolling torque', 'pl' => 'moment oporowy toczenia', 'not' => array( 'moment obrotowy wału' ) ),
	array( 'en' => 'rotary diamond dressing', 'pl' => 'obciąganie diamentową rolką obrotową', 'not' => array( 'dresowanie diamentowe rotacyjne' ) ),
	array( 'en' => 'rotor wing aircraft', 'pl' => 'śmigłowce', 'not' => array( 'samoloty śmigłowcowe' ) ),
	array( 'en' => 'sealed assembly', 'pl' => 'szczelny (hermetyczny) zespół', 'not' => array( 'zapieczętowany zespół' ) ),
	array( 'en' => 'seamless link', 'pl' => 'płynne powiązanie', 'not' => array( 'bezpośredni łącznik' ) ),
	array( 'en' => 'service professional', 'pl' => 'specjalista serwisu', 'not' => array( 'profesjonalista serwisu' ) ),
	array( 'en' => 'setup cycles', 'pl' => 'cykle ustawiania (mocowania) detalu', 'not' => array( 'cykle montażu' ) ),
	array( 'en' => 'single bay', 'pl' => 'jednostanowiskowy', 'not' => array( 'jednokomorowy' ) ),
	array( 'en' => 'single cylinder crankshaft', 'pl' => 'wał jednocylindrowy', 'not' => array( 'wał jednośladowy' ) ),
	array( 'en' => 'single station / multi station', 'pl' => 'jednostanowiskowy / wielostanowiskowy', 'not' => array( 'jednokomorowy', 'wielokomorowy' ) ),
	array( 'en' => 'site visit', 'pl' => 'wizyta na miejscu', 'not' => array( 'wizyta na terenie' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'pl' => 'sonda węchowa (sniffer)', 'not' => array( 'szczypce do wąchania' ) ),
	array( 'en' => 'snubber (hydraulic)', 'pl' => 'tłumik uderzeń hydraulicznych (dławik)', 'not' => array( 'tłumik' ) ),
	array( 'en' => 'soak time', 'pl' => 'czas wychłodzenia (soak time)', 'not' => array( 'czas przetrzymywania przed zimnym startem' ) ),
	array( 'en' => 'spalls', 'pl' => 'odpryski', 'not' => array( 'łuszczeń' ) ),
	array( 'en' => 'special test facilities', 'pl' => 'specjalne stanowiska testowe', 'not' => array( 'specjalistyczne obiekty testowe' ) ),
	array( 'en' => 'spin testing machine', 'pl' => 'maszyna do testów wirowania', 'not' => array( 'testery obrotowe', 'maszyna do testowania wirowania' ) ),
	array( 'en' => 'sprayers', 'pl' => 'opryskiwacze', 'not' => array( 'rozpylacze', 'sprayers (pozostawione)' ) ),
	array( 'en' => 'squeak & rattle testing', 'pl' => 'badania odgłosów i skrzypnięć (squeak & rattle)', 'not' => array( 'testowanie trzęsienia' ) ),
	array( 'en' => 'stand-alone machine', 'pl' => 'maszyna autonomiczna', 'not' => array( 'maszyna niezależna' ) ),
	array( 'en' => 'Standardization at scale', 'pl' => 'Standaryzacja na dużą skalę', 'not' => array( 'Standaryzacja na skalę' ) ),
	array( 'en' => 'strip', 'pl' => 'taśma', 'not' => array( 'blacha', 'pasmo' ) ),
	array( 'en' => 'strip lines', 'pl' => 'linie do taśm (linie przetwarzania taśm)', 'not' => array( 'linie paskowe', 'linie rozwijające' ) ),
	array( 'en' => 'superabrasives', 'pl' => 'ściernice supertwarde (diamentowe i CBN)', 'not' => array( 'superabrazywy' ) ),
	array( 'en' => 'surface separations', 'pl' => 'rozwarstwienia powierzchni', 'not' => array( 'rozwarstwiania powierzchni' ) ),
	array( 'en' => 'tap hole', 'pl' => 'otwór spustowy', 'not' => array( 'otwór odpustowy' ) ),
	array( 'en' => 'tapered roller bearing', 'pl' => 'łożysko stożkowe', 'not' => array( 'łożysko walcowe' ) ),
	array( 'en' => 'tariffs', 'pl' => 'cła', 'not' => array( 'taryfy' ) ),
	array( 'en' => 'tension (mechanical)', 'pl' => 'siła naciągu', 'not' => array( 'napięcie' ) ),
	array( 'en' => 'third member', 'pl' => 'mechanizm główny mostu napędowego (third member)', 'not' => array( 'trzeci człon' ) ),
	array( 'en' => 'tin plating', 'pl' => 'cynowanie', 'not' => array( 'cynkowanie' ) ),
	array( 'en' => 'TIR / radial run-out', 'pl' => 'bicie promieniowe (TIR)', 'not' => array( 'bieg TIR', 'bieg promieniowy' ) ),
	array( 'en' => 'tire inflator', 'pl' => 'stanowisko napełniania opon', 'not' => array( 'pompka do opon' ) ),
	array( 'en' => 'torque vectoring', 'pl' => 'rozdział momentu obrotowego (torque vectoring)', 'not' => array( 'wektoryzacja momentu obrotowego' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS (trademark)', 'pl' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'KOMPLEKSOWE ROZWIĄZANIA KOMERCJALIZACJI' ) ),
	array( 'en' => 'traceable tests', 'pl' => 'testy identyfikowalne', 'not' => array( 'śledzowalne testy' ) ),
	array( 'en' => 'tracer gas', 'pl' => 'gaz znacznikowy', 'not' => array( 'śledzenie gazów' ) ),
	array( 'en' => 'traction battery (BMS)', 'pl' => 'akumulator', 'not' => array( 'bateria' ) ),
	array( 'en' => 'transmission / gearbox', 'pl' => 'skrzynia biegów (przekładnia)', 'not' => array( 'Transmisja', 'transmisja napędowa', 'transmisja połączeniowa', 'elementy transmisji', 'wały transmisji', 'przekładnia (dla wału napędowego)' ) ),
	array( 'en' => 'turbo calibration', 'pl' => 'kalibracja turbosprężarek', 'not' => array( 'wyważanie turbosprężarek' ) ),
	array( 'en' => 'turbocharger flow bench', 'pl' => 'stanowisko przepływowe', 'not' => array( 'hamownia turbosprężarek', 'stanowisko pomiarowe', 'STANOWISKO PRZEPŁYWU' ) ),
	array( 'en' => 'turbocharger frame size', 'pl' => 'rozmiar korpusu', 'not' => array( 'rozmiar ramy' ) ),
	array( 'en' => 'turnkey', 'pl' => '„pod klucz”', 'not' => array( 'turnkey', 'instalacje turnkey' ) ),
	array( 'en' => 'turret-style wheel head', 'pl' => 'głowica rewolwerowa', 'not' => array( 'głowica z systemem wieżyczki' ) ),
	array( 'en' => 'two-wheel drive', 'pl' => 'napęd na dwa koła', 'not' => array( 'napęd na dwie koła' ) ),
	array( 'en' => 'ultra-stable design', 'pl' => 'wyjątkowo stabilna konstrukcja', 'not' => array( 'ultratrwały projekt' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'pl' => 'ultradźwiękowa myjka dysz', 'not' => array( 'ultrasoniczny czyszczacz dysz' ) ),
	array( 'en' => 'unbalance', 'pl' => 'niewyważenie', 'not' => array( 'niezrównoważenie', 'nierównowaga', 'niezrównoważoność', 'brak równowagi' ) ),
	array( 'en' => 'unbeatable deals', 'pl' => 'bezkonkurencyjne oferty', 'not' => array( 'niezawarte oferty' ) ),
	array( 'en' => 'Universal Balancing', 'pl' => 'Universal Balancing', 'not' => array( 'Wyważanie uniwersalne' ) ),
	array( 'en' => 'uptime across systems', 'pl' => 'dostępność systemów', 'not' => array( 'dostępność w całych systemach' ) ),
	array( 'en' => 'v-block support', 'pl' => 'podpora pryzm (bloków V)', 'not' => array( 'wsparcie sterowane serwo' ) ),
	array( 'en' => 'vacuum evacuation', 'pl' => 'odpompowanie (wytworzenie próżni)', 'not' => array( 'ewakuacja', 'ewakuacja próżni', 'zdolność do ewakuacji' ) ),
	array( 'en' => 'validate performance', 'pl' => 'potwierdzić parametry (działanie)', 'not' => array( 'zweryfikować wydajność' ) ),
	array( 'en' => 'valve body unit', 'pl' => 'korpus zaworowy', 'not' => array( 'zespół zaworów' ) ),
	array( 'en' => 'vibration', 'pl' => 'drgania', 'not' => array( 'wibracje', 'vibracja' ) ),
	array( 'en' => 'volume flexibility', 'pl' => 'elastyczność wielkości serii', 'not' => array( 'elastyczność wolumenów' ) ),
	array( 'en' => 'walking beam system', 'pl' => 'system belki kroczącej', 'not' => array( 'system chodzącego belki' ) ),
	array( 'en' => 'warranty coverage', 'pl' => 'zakres ochrony gwarancyjnej', 'not' => array( 'ubezpieczenie', 'elastyczne ubezpieczenie' ) ),
	array( 'en' => 'water meter', 'pl' => 'wodomierz', 'not' => array( 'licznik wody' ) ),
	array( 'en' => 'water-cooled', 'pl' => 'chłodzony wodą', 'not' => array( 'chłodzący wodą' ) ),
	array( 'en' => 'WCAG four principles', 'pl' => 'Postrzegalność, Funkcjonalność, Zrozumiałość, Rzetelność', 'not' => array( 'Dostrzegalna, Obsługiwalna, Zrozumiała, Niezawodne' ) ),
	array( 'en' => 'wheel aligner', 'pl' => 'urządzenie do ustawiania geometrii kół', 'not' => array( 'urządzenie do regulacji kąta zbieżności kół', 'urządzenie do wyrównywania' ) ),
	array( 'en' => 'wheel alignment', 'pl' => 'geometria kół (zbieżność)', 'not' => array( 'wyrównanie' ) ),
	array( 'en' => 'WHEREAS (recital)', 'pl' => 'ZWAŻYWSZY, ŻE', 'not' => array( 'NATOMIAST', 'PODCZAS GDY' ) ),
	array( 'en' => 'whistle (turbo)', 'pl' => 'świst', 'not' => array( 'hałas', 'szum', 'bezszumna precyzja' ) ),
	array( 'en' => 'Work Product (defined term)', 'pl' => 'Wynik Pracy', 'not' => array( 'Produkt Pracy' ) ),
	array( 'en' => 'XL Machine', 'pl' => 'XL Machine', 'not' => array( 'Maszyna XL' ) ),
);
