<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * European Portuguese (pt-PT) term base (en -> pt) for ascentialtech.com.
 * Enforced by ACWPT_Terms: relevant rows ship with each batch and any output
 * containing a 'not' form is retried and never stored.
 * Sources: site concept list, the Polish 100-page blind review defect classes,
 * and a live sweep of 12 /pt/ pages on 2026-09-25.
 */
return array(
	array( 'en' => '*', 'pt' => 'Este site é em português europeu (pt-PT) e trata o leitor de forma formal e impessoal, na terceira pessoa do singular, com o possessivo sempre precedido de artigo: «Precisa de assistência?», «a sua máquina», «os nossos técnicos», «Pode contactar-nos». Nunca use formas de tu (tu, teu, contigo, podes, precisas) em nenhuma cadeia, nem variantes brasileiras, e mantenha o mesmo registo em títulos, metadados, alt, aria-label e formulários. Em prosa corrente dirija-se ao leitor no imperativo formal («Contacte-nos», «Abra um pedido de assistência»). Os botões e etiquetas de ligação mantêm o verbo do inglês: um CTA de verbo + objeto usa o imperativo formal («Saiba mais», «Consulte o catálogo», «Solicite uma demonstração», «Descarregue a brochura», «Obtenha um orçamento», «Registe-se») e um controlo utilitário de uma só palavra usa o infinitivo («Pesquisar», «Partilhar», «Explorar», «Filtrar»); nunca reduza uma etiqueta com verbo a um substantivo isolado.', 'not' => array( 'tu', 'teu', 'teus', 'tua', 'tuas', 'contigo', 'podes', 'queres', 'precisas', 'consegues', 'sabes', 'tens', 'estás', 'quiseres', 'precisares', 'para você', 'Fale conosco', 'Contate-nos', 'Cadastre-se', 'Registre-se', 'Acessar' ) ),
	array( 'en' => '20-high mill', 'pt' => 'laminador de 20 cilindros', 'not' => array( 'moinho de 20 alturas', 'laminador de vinte alturas' ) ),
	array( 'en' => 'six-high mill', 'pt' => 'laminador de seis cilindros', 'not' => array( 'moinho de seis alturas' ) ),
	array( 'en' => '3-jaw chuck', 'pt' => 'bucha de três garras', 'not' => array( 'bucha de três mandíbulas', 'mandril de três mordentes' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'pt' => 'A DESIGN / B LOGO', 'not' => array( 'DESENHO A', 'LOGÓTIPO B' ) ),
	array( 'en' => 'active part probing', 'pt' => 'medição ativa da peça', 'not' => array( 'sondagem ativa de peças' ) ),
	array( 'en' => 'actuation systems', 'pt' => 'sistemas de atuação', 'not' => array( 'sistemas de ativação' ) ),
	array( 'en' => 'adaptive speed control', 'pt' => 'regulação adaptativa da velocidade', 'not' => array( 'controle adaptativo de velocidade' ) ),
	array( 'en' => 'ADAS (advanced driver assistance systems)', 'pt' => 'sistemas avançados de assistência à condução (ADAS)', 'not' => array( 'sistemas de assistência ao motorista', 'sistemas avançados de auxílio ao condutor' ) ),
	array( 'en' => 'ADAS alignment', 'pt' => 'calibração ADAS', 'not' => array( 'alinhamento ADAS', 'nivelamento ADAS' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'pt' => 'ADVANCING THE MACHINE', 'not' => array( 'A AVANÇAR A MÁQUINA', 'FAZER AVANÇAR A MÁQUINA' ) ),
	array( 'en' => 'air cycle machines', 'pt' => 'máquinas de ciclo de ar', 'not' => array( 'máquinas de ciclo pneumático' ) ),
	array( 'en' => 'anchoring', 'pt' => 'ancoragem', 'not' => array( 'fundeamento', 'amarração' ) ),
	array( 'en' => 'aperture plate', 'pt' => 'placa de abertura', 'not' => array( 'chapa de apertura' ) ),
	array( 'en' => 'applications', 'pt' => 'aplicações', 'not' => array( 'candidaturas' ) ),
	array( 'en' => 'armature', 'pt' => 'armadura', 'not' => array( 'induzido elétrico' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'pt' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MÉDICA E CIÊNCIAS DA VIDA', 'Ascential Médica e Ciências da Vida' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'pt' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Ensaio e Medição', 'Ascential Teste e Medição' ) ),
	array( 'en' => 'Ask Burke Porter', 'pt' => 'Ask Burke Porter', 'not' => array( 'Pergunte à Burke Porter', 'Pergunte ao Burke Porter' ) ),
	array( 'en' => 'associate attorney', 'pt' => 'advogado associado', 'not' => array( 'procurador associado' ) ),
	array( 'en' => 'audit stations', 'pt' => 'estações de auditoria', 'not' => array( 'postos de auditoria' ) ),
	array( 'en' => 'automated handling cells', 'pt' => 'células de manipulação automatizadas', 'not' => array( 'células de manuseio automatizado' ) ),
	array( 'en' => 'backhoe', 'pt' => 'retroescavadora', 'not' => array( 'retroescavadeira', 'escavadeira traseira' ) ),
	array( 'en' => 'baler', 'pt' => 'enfardadeira', 'not' => array( 'empacotadora', 'prensa de fardos' ) ),
	array( 'en' => 'bead breaking', 'pt' => 'destalonamento', 'not' => array( 'quebra do talão', 'rebentamento do talão' ) ),
	array( 'en' => 'bearers', 'pt' => 'berços de apoio', 'not' => array( 'portadores', 'suportes de carga' ) ),
	array( 'en' => 'bearing center lines', 'pt' => 'linhas de centro das chumaceiras', 'not' => array( 'linhas centrais de rolamento' ) ),
	array( 'en' => 'bearing life', 'pt' => 'vida útil dos rolamentos', 'not' => array( 'vida do mancal' ) ),
	array( 'en' => 'blade', 'pt' => 'lâmina', 'not' => array( 'faca de nivelamento' ) ),
	array( 'en' => 'blank ECM', 'pt' => 'ECM virgem', 'not' => array( 'ECM em branco', 'ECM vazio' ) ),
	array( 'en' => 'blast furnace', 'pt' => 'alto-forno', 'not' => array( 'forno de explosão', 'fornalha de sopro' ) ),
	array( 'en' => 'blowers', 'pt' => 'insufladores', 'not' => array( 'sopradores', 'ventoinhas de sopro' ) ),
	array( 'en' => 'bore axis alignment', 'pt' => 'alinhamento do eixo de pontaria', 'not' => array( 'alinhamento do eixo de furação' ) ),
	array( 'en' => 'boreless compressor wheel', 'pt' => 'roda de compressor sem furo', 'not' => array( 'turbina de compressor sem orifício' ) ),
	array( 'en' => 'boring', 'pt' => 'mandrilagem', 'not' => array( 'aborrecimento', 'entédio' ) ),
	array( 'en' => 'boring drill', 'pt' => 'perfuradora horizontal direcional', 'not' => array( 'broca aborrecida' ) ),
	array( 'en' => 'branch', 'pt' => 'sucursal', 'not' => array( 'ramo da empresa', 'galho' ) ),
	array( 'en' => 'Bristol', 'pt' => 'Bristol', 'not' => array(  ) ),
	array( 'en' => 'built to last', 'pt' => 'concebido para durar', 'not' => array( 'construído para o último', 'feito para o fim' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'pt' => 'Burke E. Porter Machinery', 'not' => array( 'Maquinaria Burke E. Porter' ) ),
	array( 'en' => 'Burke Porter Group', 'pt' => 'Burke Porter Group', 'not' => array( 'Grupo Burke Porter' ) ),
	array( 'en' => 'burst proof protection', 'pt' => 'proteção contra rutura', 'not' => array( 'proteção à prova de explosão' ) ),
	array( 'en' => 'calibration target', 'pt' => 'alvo de calibração', 'not' => array( 'objetivo de calibração', 'meta de calibração' ) ),
	array( 'en' => 'Calibration-as-a-Service (CaaS)', 'pt' => 'Calibration-as-a-Service (CaaS)', 'not' => array( 'Calibração como Serviço' ) ),
	array( 'en' => 'capital equipment', 'pt' => 'bens de equipamento', 'not' => array( 'equipamento capital', 'equipamento de capital' ) ),
	array( 'en' => 'cargo loading systems', 'pt' => 'sistemas de carregamento de carga', 'not' => array( 'sistemas de carga de bagagem' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'pt' => 'dinamómetro de chassis de 2 e 4 rodas', 'not' => array( 'dinamômetro de chassi de duas e quatro rodas' ) ),
	array( 'en' => 'chip vacuum', 'pt' => 'aspiração de aparas', 'not' => array( 'vácuo de fichas', 'aspirador de chips' ) ),
	array( 'en' => 'clay gun', 'pt' => 'canhão de argila', 'not' => array( 'pistola de barro' ) ),
	array( 'en' => 'CMT-TR Polimer', 'pt' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR Polímero' ) ),
	array( 'en' => 'cold pilger mill', 'pt' => 'laminador pilger a frio', 'not' => array( 'moinho pilger frio' ) ),
	array( 'en' => 'collet chuck', 'pt' => 'bucha de pinça', 'not' => array( 'mandril de colar', 'bucha de colarinho' ) ),
	array( 'en' => 'combine harvester', 'pt' => 'ceifeira-debulhadora', 'not' => array( 'colheitadeira', 'combinado agrícola' ) ),
	array( 'en' => 'commercial vehicle', 'pt' => 'veículo comercial', 'not' => array( 'viatura de comércio' ) ),
	array( 'en' => 'commissioning', 'pt' => 'colocação em serviço', 'not' => array( 'comissão', 'encomenda', 'desativação' ) ),
	array( 'en' => 'Connect on LinkedIn', 'pt' => 'Contactar no LinkedIn', 'not' => array( 'Conectar no LinkedIn', 'Conecte-se no LinkedIn' ) ),
	array( 'en' => 'control', 'pt' => 'controlo', 'not' => array( 'controle' ) ),
	array( 'en' => 'control module', 'pt' => 'módulo de comando', 'not' => array( 'módulo de controle' ) ),
	array( 'en' => 'controls', 'pt' => 'controlos', 'not' => array( 'controles' ) ),
	array( 'en' => 'Core / Plus / Elite', 'pt' => 'Core / Plus / Elite', 'not' => array( 'Núcleo / Mais / Elite' ) ),
	array( 'en' => 'Corporate Roles', 'pt' => 'Funções corporativas', 'not' => array( 'Papéis corporativos' ) ),
	array( 'en' => 'correction', 'pt' => 'correção', 'not' => array( 'correcção' ) ),
	array( 'en' => 'crankshaft lathe', 'pt' => 'torno para cambotas', 'not' => array( 'torno de virabrequim' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'pt' => 'Crossroads Bank for Enterprises', 'not' => array(  ) ),
	array( 'en' => 'cushion testing', 'pt' => 'ensaio de amortecimento', 'not' => array( 'teste de almofada' ) ),
	array( 'en' => 'custom fixturing', 'pt' => 'ferramentas de fixação personalizadas', 'not' => array( 'fixação sob medida personalizada' ) ),
	array( 'en' => 'customer journey', 'pt' => 'percurso do cliente', 'not' => array( 'viagem do cliente', 'jornada do cliente' ) ),
	array( 'en' => 'Date:', 'pt' => 'Data:', 'not' => array(  ) ),
	array( 'en' => 'deep hole drilling', 'pt' => 'furação profunda', 'not' => array( 'perfuração de buracos profundos' ) ),
	array( 'en' => 'defensible', 'pt' => 'defensável', 'not' => array( 'defensível' ) ),
	array( 'en' => 'Deliverables', 'pt' => 'Entregáveis', 'not' => array( 'Entregas finais' ) ),
	array( 'en' => 'deployment', 'pt' => 'implementação', 'not' => array( 'desdobramento', 'implantação militar' ) ),
	array( 'en' => 'design', 'pt' => 'conceção', 'not' => array( 'desenho técnico', 'projecto' ) ),
	array( 'en' => 'dial indicator', 'pt' => 'comparador de quadrante', 'not' => array( 'indicador de discagem' ) ),
	array( 'en' => 'disability insurance', 'pt' => 'seguro de invalidez', 'not' => array( 'seguro de deficiência' ) ),
	array( 'en' => 'discrete industries', 'pt' => 'indústrias de produção discreta', 'not' => array( 'indústrias discretas' ) ),
	array( 'en' => 'draper header', 'pt' => 'plataforma de corte com tapete', 'not' => array( 'cabeçalho de cortina' ) ),
	array( 'en' => 'drift', 'pt' => 'deriva', 'not' => array( 'flutuação livre' ) ),
	array( 'en' => 'drivability', 'pt' => 'dirigibilidade', 'not' => array( 'conduzibilidade' ) ),
	array( 'en' => 'dual mass flywheel', 'pt' => 'volante bimassa', 'not' => array( 'volante de dupla massa', 'volante de massa dupla' ) ),
	array( 'en' => 'dynamometer', 'pt' => 'dinamómetro', 'not' => array( 'dinamômetro' ) ),
	array( 'en' => 'eddy current technology', 'pt' => 'tecnologia de correntes de Foucault', 'not' => array( 'tecnologia de corrente parasita', 'correntes turbilhonares' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'pt' => 'texturização por descarga elétrica (EDT)', 'not' => array( 'texturização por descarga eléctrica', 'texturização por descarga elétrica erosiva' ) ),
	array( 'en' => 'Email Disclosure', 'pt' => 'Aviso de correio eletrónico', 'not' => array( 'Divulgação de e-mail' ) ),
	array( 'en' => 'EMC darkroom', 'pt' => 'câmara anecoica de CEM', 'not' => array( 'câmara escura de EMC', 'sala escura de CEM' ) ),
	array( 'en' => 'end of line testing', 'pt' => 'ensaio de fim de linha', 'not' => array( 'teste de fim de linha', 'ensaio de final de linha' ) ),
	array( 'en' => 'energy recuperation', 'pt' => 'recuperação de energia', 'not' => array( 'recuperação energética de travagem' ) ),
	array( 'en' => 'engine software loaders', 'pt' => 'carregadores de software do motor', 'not' => array( 'carregadores de programa de motor' ) ),
	array( 'en' => 'eRotor', 'pt' => 'eRotor', 'not' => array( 'rotor eletrónico' ) ),
	array( 'en' => 'events & conferences', 'pt' => 'eventos e conferências', 'not' => array( 'eventos e congressos' ) ),
	array( 'en' => 'excavator', 'pt' => 'escavadora', 'not' => array( 'escavadeira' ) ),
	array( 'en' => 'exhaust extraction', 'pt' => 'extração de gases de escape', 'not' => array( 'extração de exaustão' ) ),
	array( 'en' => 'factory floor', 'pt' => 'chão de fábrica', 'not' => array( 'piso da fábrica', 'planta da fábrica' ) ),
	array( 'en' => 'failure rates', 'pt' => 'taxas de falha', 'not' => array( 'taxas de fracasso' ) ),
	array( 'en' => 'features', 'pt' => 'características', 'not' => array( 'funcionalidades técnicas' ) ),
	array( 'en' => 'Key Features', 'pt' => 'Principais características', 'not' => array( 'Principais Recursos', 'Recursos Principais', 'Características Chave' ) ),
	array( 'en' => 'Featuring', 'pt' => 'Com', 'not' => array( 'Apresentando', 'Com tecnologia' ) ),
	array( 'en' => 'field agents', 'pt' => 'técnicos de campo', 'not' => array( 'agentes de campo' ) ),
	array( 'en' => 'field balancing', 'pt' => 'equilibragem no local', 'not' => array( 'equilibragem de campo', 'balanceamento em campo' ) ),
	array( 'en' => 'filler', 'pt' => 'máquina de enchimento', 'not' => array( 'recheio', 'enchedor de massa' ) ),
	array( 'en' => 'filler gun', 'pt' => 'pistola de enchimento', 'not' => array( 'pistola de recheio' ) ),
	array( 'en' => 'final discharge', 'pt' => 'descarga final', 'not' => array( 'descarregamento final' ) ),
	array( 'en' => 'fine leak', 'pt' => 'fuga fina', 'not' => array( 'vazamento fino', 'micro vazamento' ) ),
	array( 'en' => 'flexplate', 'pt' => 'flexplate', 'not' => array( 'placa flexível' ) ),
	array( 'en' => 'fluid power', 'pt' => 'sistemas hidráulicos e pneumáticos', 'not' => array( 'Potência fluida', 'Potência de fluidos', 'Energia fluida' ) ),
	array( 'en' => 'flywheel', 'pt' => 'volante de motor', 'not' => array( 'volante de direção', 'roda volante' ) ),
	array( 'en' => 'footprint', 'pt' => 'área de implantação', 'not' => array( 'impressão no solo', 'superfície de pegada' ) ),
	array( 'en' => 'For Immediate Release', 'pt' => 'Para divulgação imediata', 'not' => array( 'Para lançamento imediato', 'Para libertação imediata' ) ),
	array( 'en' => 'forged rolls', 'pt' => 'cilindros forjados', 'not' => array( 'rolos forjados' ) ),
	array( 'en' => 'front strut', 'pt' => 'perna de suspensão dianteira', 'not' => array( 'escora frontal' ) ),
	array( 'en' => 'gantry', 'pt' => 'pórtico', 'not' => array( 'gantry', 'portal de montagem' ) ),
	array( 'en' => 'GDPR', 'pt' => 'RGPD', 'not' => array( 'GDPR' ) ),
	array( 'en' => 'gear shift calibration', 'pt' => 'calibração das mudanças', 'not' => array( 'calibração de troca de marcha' ) ),
	array( 'en' => 'grinding wheel', 'pt' => 'mó abrasiva', 'not' => array( 'roda de esmeril', 'disco de moagem' ) ),
	array( 'en' => 'gross leak test', 'pt' => 'ensaio de fuga grosseira', 'not' => array( 'teste de vazamento bruto' ) ),
	array( 'en' => 'gundrill', 'pt' => 'broca de canhão', 'not' => array( 'broca de arma', 'gundrill' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'pt' => 'H. Kleinknecht & Co. GmbH', 'not' => array(  ) ),
	array( 'en' => 'half case', 'pt' => 'meio cárter', 'not' => array( 'meia caixa', 'metade do estojo' ) ),
	array( 'en' => 'hay mower', 'pt' => 'ceifeira de forragem', 'not' => array( 'cortador de feno' ) ),
	array( 'en' => 'hazardous area', 'pt' => 'área perigosa', 'not' => array( 'área arriscada' ) ),
	array( 'en' => 'hazardous areas', 'pt' => 'áreas perigosas', 'not' => array( 'áreas arriscadas' ) ),
	array( 'en' => 'health checks', 'pt' => 'verificações do estado do equipamento', 'not' => array( 'verificações de saúde', 'exames de saúde' ) ),
	array( 'en' => 'high production', 'pt' => 'produção em grande série', 'not' => array( 'alta produção' ) ),
	array( 'en' => 'high-volume production', 'pt' => 'produção em grandes séries', 'not' => array( 'produção de alto volume' ) ),
	array( 'en' => 'high-mix, low-volume', 'pt' => 'grande variedade e pequenas séries', 'not' => array( 'alta mistura, baixo volume' ) ),
	array( 'en' => 'high-performance teams', 'pt' => 'equipas de elevado desempenho', 'not' => array( 'times de alta performance', 'equipes de alto desempenho' ) ),
	array( 'en' => 'higher-level control system', 'pt' => 'sistema de comando de nível superior', 'not' => array( 'sistema de controle de nível mais alto' ) ),
	array( 'en' => 'HMU/FMU', 'pt' => 'HMU/FMU', 'not' => array(  ) ),
	array( 'en' => 'idle duration', 'pt' => 'duração ao ralenti', 'not' => array( 'duração inativa', 'tempo de marcha lenta' ) ),
	array( 'en' => 'implements', 'pt' => 'alfaias', 'not' => array( 'implementos agrícolas', 'utensílios agrícolas' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'pt' => 'Alfaias - fim de linha', 'not' => array( 'Implementos - Fim de linha' ) ),
	array( 'en' => 'Imprint', 'pt' => 'Aviso legal', 'not' => array( 'Impressão', 'Impressum', 'Ficha técnica' ) ),
	array( 'en' => 'in a single clamping', 'pt' => 'numa única fixação', 'not' => array( 'num único aperto' ) ),
	array( 'en' => 'infeed', 'pt' => 'avanço', 'not' => array( 'entrada de alimentação' ) ),
	array( 'en' => 'infinitely variable', 'pt' => 'continuamente variável', 'not' => array( 'infinitamente variável' ) ),
	array( 'en' => 'inline crankshaft', 'pt' => 'cambota em linha', 'not' => array( 'virabrequim em linha' ) ),
	array( 'en' => 'inline dyno', 'pt' => 'dinamómetro em linha', 'not' => array( 'dinamômetro integrado na linha' ) ),
	array( 'en' => 'insights', 'pt' => 'perspetivas', 'not' => array( 'insights', 'percepções' ) ),
	array( 'en' => 'actionable insights', 'pt' => 'informações práticas', 'not' => array( 'insights acionáveis', 'perceções acionáveis' ) ),
	array( 'en' => 'expert insights', 'pt' => 'perspetivas de especialistas', 'not' => array( 'insights de especialistas' ) ),
	array( 'en' => 'instrument cluster', 'pt' => 'painel de instrumentos', 'not' => array( 'cluster de instrumentos', 'aglomerado de instrumentos' ) ),
	array( 'en' => 'keg finger holes', 'pt' => 'orifícios de pega dos barris', 'not' => array( 'buracos de dedo do barril' ) ),
	array( 'en' => 'kinetostatics', 'pt' => 'cinetostática', 'not' => array( 'cineto-estática' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'pt' => 'KvK (Kamer van Koophandel)', 'not' => array(  ) ),
	array( 'en' => 'Labour & Travel', 'pt' => 'Mão de obra e deslocações', 'not' => array( 'Trabalho e Viagem', 'Mão-de-obra e deslocações' ) ),
	array( 'en' => 'landed cost model', 'pt' => 'modelo de custo total de importação', 'not' => array( 'modelo de custo desembarcado' ) ),
	array( 'en' => 'landing gear systems', 'pt' => 'sistemas de trem de aterragem', 'not' => array( 'sistemas de trem de pouso' ) ),
	array( 'en' => 'leak detection', 'pt' => 'deteção de fugas', 'not' => array( 'detecção de fugas', 'deteção de vazamentos' ) ),
	array( 'en' => 'learning management system (LMS)', 'pt' => 'sistema de gestão da aprendizagem (LMS)', 'not' => array( 'sistema de gerenciamento de aprendizagem' ) ),
	array( 'en' => 'like-minded companies', 'pt' => 'empresas com a mesma visão', 'not' => array( 'empresas de mente semelhante' ) ),
	array( 'en' => 'load capacity', 'pt' => 'capacidade de carga', 'not' => array( 'capacidade de carregamento' ) ),
	array( 'en' => 'LPM', 'pt' => 'l/min', 'not' => array( 'litros pro minuto' ) ),
	array( 'en' => 'lube & scavenge pumps', 'pt' => 'bombas de lubrificação e de recuperação', 'not' => array( 'bombas de lubrificação e limpeza' ) ),
	array( 'en' => 'lubrication', 'pt' => 'lubrificação', 'not' => array( 'lubricação' ) ),
	array( 'en' => 'machine tools', 'pt' => 'máquinas-ferramenta', 'not' => array( 'ferramentas de máquina', 'máquinas ferramentas' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'pt' => 'Diretiva Máquinas 2006/42/CE', 'not' => array( 'Diretiva de Maquinaria 2006/42/EC' ) ),
	array( 'en' => 'machining cell', 'pt' => 'célula de maquinagem', 'not' => array( 'célula de usinagem' ) ),
	array( 'en' => 'machinist', 'pt' => 'operador de máquinas-ferramenta', 'not' => array( 'maquinista' ) ),
	array( 'en' => 'maintenance contracts', 'pt' => 'contratos de manutenção', 'not' => array( 'contratos de manutenção e conserto' ) ),
	array( 'en' => 'marine', 'pt' => 'naval', 'not' => array( 'marinho' ) ),
	array( 'en' => 'maximum rotor diameter', 'pt' => 'diâmetro máximo do rotor', 'not' => array( 'diâmetro máximo de rotação' ) ),
	array( 'en' => 'mental health care', 'pt' => 'cuidados de saúde mental', 'not' => array( 'cuidado com a saúde mental' ) ),
	array( 'en' => 'mill roll', 'pt' => 'cilindro de laminador', 'not' => array( 'rolo de moinho', 'rolo de laminação' ) ),
	array( 'en' => 'misalignment', 'pt' => 'desalinhamento', 'not' => array( 'desalinho', 'má-alinhamento' ) ),
	array( 'en' => 'motor grader', 'pt' => 'motoniveladora', 'not' => array( 'nivelador de motor', 'raspadora' ) ),
	array( 'en' => 'motorized clamping', 'pt' => 'fixação motorizada', 'not' => array( 'aperto motorizado' ) ),
	array( 'en' => 'MRO', 'pt' => 'MRO', 'not' => array( 'manutenção, reparo e operação' ) ),
	array( 'en' => 'mudding system', 'pt' => 'sistema de lamas', 'not' => array( 'sistema de lameamento' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'pt' => 'naamloze vennootschap (NV)', 'not' => array(  ) ),
	array( 'en' => 'Name:', 'pt' => 'Nome:', 'not' => array(  ) ),
	array( 'en' => 'Netherlands', 'pt' => 'Países Baixos', 'not' => array( 'Holanda', 'Netherlands' ) ),
	array( 'en' => 'non-rotating balancing machine', 'pt' => 'máquina de equilibragem sem rotação', 'not' => array( 'máquina de equilibragem não rotativa', 'equilibradora não giratória' ) ),
	array( 'en' => 'obsolescence management', 'pt' => 'gestão da obsolescência', 'not' => array( 'gerenciamento de obsolescência' ) ),
	array( 'en' => 'off-highway', 'pt' => 'fora de estrada', 'not' => array( 'fora-de-estrada', 'todo-o-terreno' ) ),
	array( 'en' => 'oil drain', 'pt' => 'dreno de óleo', 'not' => array( 'drenagem de petróleo' ) ),
	array( 'en' => 'operations', 'pt' => 'operações', 'not' => array( 'operações cirúrgicas' ) ),
	array( 'en' => 'opportunities', 'pt' => 'oportunidades', 'not' => array( 'oportunistas' ) ),
	array( 'en' => 'patented', 'pt' => 'patenteado', 'not' => array( 'patenteada por lei' ) ),
	array( 'en' => 'pedestals', 'pt' => 'pedestais', 'not' => array( 'pedestal de coluna' ) ),
	array( 'en' => 'peers', 'pt' => 'pares', 'not' => array( 'semelhantes', 'colegas de escola' ) ),
	array( 'en' => 'performance', 'pt' => 'desempenho', 'not' => array( 'performance' ) ),
	array( 'en' => 'personal information', 'pt' => 'dados pessoais', 'not' => array( 'informação pessoal' ) ),
	array( 'en' => 'personal data', 'pt' => 'dados pessoais', 'not' => array( 'dado pessoal' ) ),
	array( 'en' => 'pinches & bruises', 'pt' => 'amolgamentos e contusões', 'not' => array( 'pincadas e hematomas' ) ),
	array( 'en' => 'pinion gear', 'pt' => 'pinhão', 'not' => array( 'engrenagem de pinhão', 'roda de pinhão' ) ),
	array( 'en' => 'pins', 'pt' => 'pinos', 'not' => array( 'alfinetes' ) ),
	array( 'en' => 'power drive units', 'pt' => 'unidades de acionamento', 'not' => array( 'unidades de potência motriz' ) ),
	array( 'en' => 'Powered by', 'pt' => 'Assente em', 'not' => array( 'Alimentado por', 'Impulsionado por' ) ),
	array( 'en' => 'President', 'pt' => 'presidente', 'not' => array( 'presidente da república' ) ),
	array( 'en' => 'pressurization', 'pt' => 'pressurização', 'not' => array( 'pressionamento' ) ),
	array( 'en' => 'probe alignment', 'pt' => 'alinhamento da sonda', 'not' => array( 'alinhamento do probe' ) ),
	array( 'en' => 'process recipe', 'pt' => 'receita de processo', 'not' => array( 'fórmula de processo' ) ),
	array( 'en' => 'propulsion & powertrain', 'pt' => 'propulsão e grupo motopropulsor', 'not' => array( 'propulsão e transmissão', 'propulsão e trem de força' ) ),
	array( 'en' => 'powertrain', 'pt' => 'grupo motopropulsor', 'not' => array( 'trem de força', 'trem de potência' ) ),
	array( 'en' => 'PTO (power take-off)', 'pt' => 'tomada de força (PTO)', 'not' => array( 'saída de potência' ) ),
	array( 'en' => 'pulley', 'pt' => 'polia', 'not' => array( 'roldana' ) ),
	array( 'en' => 'punching', 'pt' => 'puncionamento', 'not' => array( 'perfuração por punção', 'socar' ) ),
	array( 'en' => 'push and pull', 'pt' => 'avanço e retração', 'not' => array( 'empurrar e puxar' ) ),
	array( 'en' => 'reconditioning', 'pt' => 'recondicionamento', 'not' => array( 'reacondicionamento' ) ),
	array( 'en' => 'refrigerant', 'pt' => 'fluido frigorigéneo', 'not' => array( 'líquido refrigerante', 'agente refrigerador' ) ),
	array( 'en' => 'refrigerant charging', 'pt' => 'carga de fluido frigorigéneo', 'not' => array( 'carregamento de refrigerante', 'enchimento de refrigerante' ) ),
	array( 'en' => 'refrigeration', 'pt' => 'refrigeração', 'not' => array( 'resfriamento' ) ),
	array( 'en' => 'Register', 'pt' => 'Registe-se', 'not' => array( 'Registre-se', 'Cadastre-se', 'Registrar' ) ),
	array( 'en' => 'Registered office', 'pt' => 'Sede social', 'not' => array( 'Escritório registado' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'pt' => 'remanufaturadores e reconstrutores', 'not' => array( 'refabricantes e reconstrutores' ) ),
	array( 'en' => 'remarketers', 'pt' => 'revendedores', 'not' => array( 'remarketers' ) ),
	array( 'en' => 'reportable', 'pt' => 'de comunicação obrigatória', 'not' => array( 'reportável' ) ),
	array( 'en' => 'represent', 'pt' => 'reproduzir', 'not' => array( 'representar cenicamente' ) ),
	array( 'en' => 'residual unbalance', 'pt' => 'desequilíbrio residual', 'not' => array( 'desbalanceamento residual', 'desequilibragem residual' ) ),
	array( 'en' => 'responsive', 'pt' => 'com capacidade de resposta', 'not' => array( 'responsivo', 'responsiva' ) ),
	array( 'en' => 'restbus simulation', 'pt' => 'simulação de restbus', 'not' => array( 'simulação de barramento de repouso' ) ),
	array( 'en' => 'retaining rollers', 'pt' => 'rolos de retenção', 'not' => array( 'roletes retentores' ) ),
	array( 'en' => 'right-shoring', 'pt' => 'right-shoring', 'not' => array( 'costa direita' ) ),
	array( 'en' => 'roll inspection', 'pt' => 'inspeção de cilindros', 'not' => array( 'inspeção de rolos', 'controlo de rolos' ) ),
	array( 'en' => 'Roll Shop Technologies', 'pt' => 'Tecnologias para oficinas de cilindros', 'not' => array( 'Tecnologias de loja de rolos' ) ),
	array( 'en' => 'roller', 'pt' => 'rolo', 'not' => array( 'rolete de estrada' ) ),
	array( 'en' => 'roller brake tester', 'pt' => 'banco de ensaio de travões de rolos', 'not' => array( 'testador de freios de rolos' ) ),
	array( 'en' => 'rolling torque', 'pt' => 'binário de rolamento', 'not' => array( 'torque de rolamento' ) ),
	array( 'en' => 'rotary diamond dressing', 'pt' => 'diamantagem rotativa', 'not' => array( 'vestir diamante rotativo' ) ),
	array( 'en' => 'rotor wing aircraft', 'pt' => 'aeronaves de asa rotativa', 'not' => array( 'avião de asa de rotor' ) ),
	array( 'en' => 'sealed assembly', 'pt' => 'conjunto vedado', 'not' => array( 'montagem selada' ) ),
	array( 'en' => 'seamless link', 'pt' => 'ligação contínua', 'not' => array( 'link sem costura', 'ligação sem emenda' ) ),
	array( 'en' => 'service professional', 'pt' => 'profissional de assistência', 'not' => array( 'profissional de serviço ao cliente' ) ),
	array( 'en' => 'setup cycles', 'pt' => 'ciclos de preparação', 'not' => array( 'ciclos de setup' ) ),
	array( 'en' => 'single bay', 'pt' => 'baia única', 'not' => array( 'baía individual' ) ),
	array( 'en' => 'single cylinder crankshaft', 'pt' => 'cambota de um cilindro', 'not' => array( 'virabrequim de cilindro único' ) ),
	array( 'en' => 'single station', 'pt' => 'estação única', 'not' => array( 'estação individual' ) ),
	array( 'en' => 'multi station', 'pt' => 'estações múltiplas', 'not' => array( 'multi estação' ) ),
	array( 'en' => 'site visit', 'pt' => 'visita às instalações', 'not' => array( 'visita ao site', 'visita do local' ) ),
	array( 'en' => 'sniffing pliers', 'pt' => 'pinça de deteção', 'not' => array( 'alicate farejador' ) ),
	array( 'en' => 'sniffer', 'pt' => 'sonda de deteção', 'not' => array( 'farejador' ) ),
	array( 'en' => 'snubber', 'pt' => 'amortecedor de pulsações', 'not' => array( 'freio de choque' ) ),
	array( 'en' => 'soak time', 'pt' => 'tempo de estabilização', 'not' => array( 'tempo de imersão', 'tempo de encharcamento' ) ),
	array( 'en' => 'spalls', 'pt' => 'escamações', 'not' => array( 'lascas de pedra' ) ),
	array( 'en' => 'special test facilities', 'pt' => 'instalações de ensaio especiais', 'not' => array( 'facilidades de teste especiais' ) ),
	array( 'en' => 'spin testing machine', 'pt' => 'máquina de ensaio de rotação', 'not' => array( 'máquina de teste de giro' ) ),
	array( 'en' => 'sprayers', 'pt' => 'pulverizadores', 'not' => array( 'borrifadores' ) ),
	array( 'en' => 'squeak & rattle testing', 'pt' => 'ensaios de rangidos e ruídos parasitas', 'not' => array( 'teste de chiado e chacoalho' ) ),
	array( 'en' => 'stand-alone machine', 'pt' => 'máquina autónoma', 'not' => array( 'máquina independente', 'máquina stand-alone' ) ),
	array( 'en' => 'Standardization at scale', 'pt' => 'Normalização em larga escala', 'not' => array( 'Padronização em escala' ) ),
	array( 'en' => 'strip', 'pt' => 'banda', 'not' => array( 'tira metálica' ) ),
	array( 'en' => 'Strip Lines', 'pt' => 'Linhas de banda', 'not' => array( 'Linhas de tiras' ) ),
	array( 'en' => 'superabrasives', 'pt' => 'superabrasivos', 'not' => array( 'super abrasivos' ) ),
	array( 'en' => 'surface separations', 'pt' => 'separações superficiais', 'not' => array( 'separações de superfície' ) ),
	array( 'en' => 'tap hole', 'pt' => 'furo de vazamento', 'not' => array( 'buraco de torneira' ) ),
	array( 'en' => 'tapered roller bearing', 'pt' => 'rolamento de rolos cónicos', 'not' => array( 'rolamento de rolos cônicos' ) ),
	array( 'en' => 'tariffs', 'pt' => 'direitos aduaneiros', 'not' => array( 'tarifários' ) ),
	array( 'en' => 'tension', 'pt' => 'tensão', 'not' => array( 'tensão nervosa' ) ),
	array( 'en' => 'third member', 'pt' => 'conjunto do diferencial', 'not' => array( 'terceiro membro' ) ),
	array( 'en' => 'tin plating', 'pt' => 'estanhagem', 'not' => array( 'revestimento de lata' ) ),
	array( 'en' => 'TIR / radial run-out', 'pt' => 'TIR / excentricidade radial', 'not' => array( 'TIR / desvio radial' ) ),
	array( 'en' => 'tire inflator', 'pt' => 'enchedor de pneus', 'not' => array( 'inflador de pneus' ) ),
	array( 'en' => 'torque vectoring', 'pt' => 'vetorização do binário', 'not' => array( 'vetorização de torque' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'pt' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'SOLUÇÕES TOTAIS DE COMERCIALIZAÇÃO' ) ),
	array( 'en' => 'traceable tests', 'pt' => 'ensaios rastreáveis', 'not' => array( 'testes traçáveis' ) ),
	array( 'en' => 'tracer gas', 'pt' => 'gás traçador', 'not' => array( 'gás de rastreio' ) ),
	array( 'en' => 'traction battery', 'pt' => 'bateria de tração', 'not' => array( 'bateria de arrasto' ) ),
	array( 'en' => 'transmission', 'pt' => 'caixa de velocidades', 'not' => array( 'câmbio', 'caixa de câmbio' ) ),
	array( 'en' => 'gearbox', 'pt' => 'caixa de velocidades', 'not' => array( 'caixa de engrenagens', 'caixa de câmbios' ) ),
	array( 'en' => 'turbo calibration', 'pt' => 'calibração de turbocompressores', 'not' => array( 'calibração de turbo sobrealimentador' ) ),
	array( 'en' => 'turbocharger', 'pt' => 'turbocompressor', 'not' => array( 'sobrealimentador', 'turbo alimentador' ) ),
	array( 'en' => 'turbocharger flow bench', 'pt' => 'banco de ensaio de caudal de turbocompressores', 'not' => array( 'banco de fluxo de sobrealimentador', 'bancada de fluxo de turbo' ) ),
	array( 'en' => 'turbocharger frame size', 'pt' => 'tamanho de carcaça do turbocompressor', 'not' => array( 'tamanho do quadro do turbo' ) ),
	array( 'en' => 'turnkey', 'pt' => 'chave na mão', 'not' => array( 'chave em mão', 'turnkey' ) ),
	array( 'en' => 'turret-style wheel head', 'pt' => 'cabeça porta-mós tipo torreta', 'not' => array( 'cabeça de roda tipo torre' ) ),
	array( 'en' => 'two-wheel drive', 'pt' => 'tração às duas rodas', 'not' => array( 'tração de duas rodas' ) ),
	array( 'en' => 'ultra-stable design', 'pt' => 'conceção ultraestável', 'not' => array( 'desenho ultra estável' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'pt' => 'limpador de injetores por ultrassons', 'not' => array( 'limpador de bico ultrassónico' ) ),
	array( 'en' => 'unbalance', 'pt' => 'desequilíbrio', 'not' => array( 'desbalanceamento', 'desequilibragem', 'não equilíbrio' ) ),
	array( 'en' => 'unbeatable deals', 'pt' => 'ofertas imbatíveis', 'not' => array( 'negócios imbatíveis', 'acordos inigualáveis' ) ),
	array( 'en' => 'Universal Balancing', 'pt' => 'Universal Balancing', 'not' => array( 'Equilibragem Universal', 'Balanceamento Universal' ) ),
	array( 'en' => 'uptime across systems', 'pt' => 'disponibilidade em todos os sistemas', 'not' => array( 'tempo de subida dos sistemas' ) ),
	array( 'en' => 'v-block support', 'pt' => 'apoio em V', 'not' => array( 'suporte de bloco V' ) ),
	array( 'en' => 'vacuum evacuation', 'pt' => 'evacuação por vácuo', 'not' => array( 'esvaziamento a vácuo' ) ),
	array( 'en' => 'validate performance', 'pt' => 'validar o desempenho', 'not' => array( 'validar a performance' ) ),
	array( 'en' => 'valve body unit', 'pt' => 'corpo de válvulas', 'not' => array( 'unidade de corpo de válvula' ) ),
	array( 'en' => 'vibration', 'pt' => 'vibração', 'not' => array( 'vibrações mecânicas' ) ),
	array( 'en' => 'volume flexibility', 'pt' => 'flexibilidade de volumes', 'not' => array( 'flexibilidade volumétrica' ) ),
	array( 'en' => 'walking beam system', 'pt' => 'sistema de viga oscilante', 'not' => array( 'sistema de feixe ambulante', 'sistema de trave caminhante' ) ),
	array( 'en' => 'warranty coverage', 'pt' => 'cobertura da garantia', 'not' => array( 'seguro de garantia' ) ),
	array( 'en' => 'water meter', 'pt' => 'contador de água', 'not' => array( 'medidor de água', 'hidrómetro' ) ),
	array( 'en' => 'water-cooled', 'pt' => 'arrefecido por água', 'not' => array( 'resfriado por água' ) ),
	array( 'en' => 'WCAG four principles', 'pt' => 'os quatro princípios das WCAG', 'not' => array( 'quatro princípios WCAG' ) ),
	array( 'en' => 'wheel aligner', 'pt' => 'alinhador de direção', 'not' => array( 'alinhador de volante' ) ),
	array( 'en' => 'wheel alignment', 'pt' => 'alinhamento de direção', 'not' => array( 'alinhamento do volante' ) ),
	array( 'en' => 'WHEREAS', 'pt' => 'CONSIDERANDO QUE', 'not' => array( 'ENQUANTO QUE', 'AO PASSO QUE' ) ),
	array( 'en' => 'whistle', 'pt' => 'assobio', 'not' => array( 'apito de turbo' ) ),
	array( 'en' => 'Work Product', 'pt' => 'Produto do Trabalho', 'not' => array( 'Trabalho Produzido' ) ),
	array( 'en' => 'XL Machine', 'pt' => 'XL Machine', 'not' => array( 'Máquina XL' ) ),
	array( 'en' => 'Marketplace', 'pt' => 'Marketplace', 'not' => array( 'Mercado de peças' ) ),
	array( 'en' => 'Medical', 'pt' => 'Medical', 'not' => array( 'Medicina' ) ),
	array( 'en' => 'Non-Rotate Systems', 'pt' => 'Sistemas sem rotação', 'not' => array( 'Sistemas Não Rotativos', 'Sistemas de Não Rotação' ) ),
	array( 'en' => 'Spin Testing', 'pt' => 'Ensaio de rotação', 'not' => array( 'Teste de Giro' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'pt' => 'Rolos de transportadores e de papel', 'not' => array( 'Cilindros de correia transportadora e papel' ) ),
	array( 'en' => 'stem stickiness', 'pt' => 'encravamento da haste', 'not' => array( 'viscosidade da haste', 'aderência do caule' ) ),
	array( 'en' => 'hydraulic pilot', 'pt' => 'pilotagem hidráulica', 'not' => array( 'piloto hidráulico' ) ),
	array( 'en' => 'load sense signal', 'pt' => 'sinal de deteção de carga', 'not' => array( 'sinal de sentido de carga' ) ),
	array( 'en' => 'debonding', 'pt' => 'descolagem', 'not' => array( 'desunião', 'desligamento adesivo' ) ),
	array( 'en' => 'movable cradle', 'pt' => 'berço móvel', 'not' => array( 'carrinho móvel de apoio' ) ),
	array( 'en' => 'thrust force', 'pt' => 'força de avanço', 'not' => array( 'força de impulso' ) ),
	array( 'en' => 'pullback force', 'pt' => 'força de retração', 'not' => array( 'força de recuo' ) ),
	array( 'en' => 'ring gears', 'pt' => 'coroas dentadas', 'not' => array( 'engrenagens de anel' ) ),
	array( 'en' => 'blade timing', 'pt' => 'sincronização das pás', 'not' => array( 'cronometragem da lâmina' ) ),
	array( 'en' => 'heavy-duty', 'pt' => 'para serviço intensivo', 'not' => array( 'dever pesado', 'de alta resistência pesada' ) ),
	array( 'en' => 'life sciences', 'pt' => 'ciências da vida', 'not' => array( 'ciências biológicas' ) ),
	array( 'en' => 'First Alert Monitoring System', 'pt' => 'Sistema de monitorização de alerta antecipado', 'not' => array( 'Sistema de Monitoramento de Primeiro Alerta' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'pt' => 'Turbo Test Duo Expert', 'not' => array( 'Turbo Test Duo Especialista', 'Especialista TURBO TEST DUO' ) ),
	array( 'en' => 'Board Member', 'pt' => 'Membro do Conselho de Administração', 'not' => array( 'Membro da Diretoria' ) ),
	array( 'en' => 'Principal', 'pt' => 'Principal', 'not' => array( 'Diretor-principal de fundo' ) ),
	array( 'en' => 'Leadership', 'pt' => 'Equipa de liderança', 'not' => array( 'Time de liderança' ) ),
	array( 'en' => 'Introducing', 'pt' => 'Apresentamos', 'not' => array( 'Introduzindo', 'Apresentando' ) ),
	array( 'en' => 'flammable gases', 'pt' => 'gases inflamáveis', 'not' => array( 'gases flamáveis' ) ),
	array( 'en' => 'Electronic hung mass', 'pt' => 'massa suspensa eletrónica', 'not' => array( 'massa pendurada eletrónica' ) ),
	array( 'en' => 'Detection Focus', 'pt' => 'Foco de deteção', 'not' => array( 'Enfoque de detecção' ) ),
	array( 'en' => 'weight capacity', 'pt' => 'capacidade de peso', 'not' => array( 'capacidade ponderal' ) ),
	array( 'en' => 'vacuum', 'pt' => 'vácuo', 'not' => array( 'aspirador' ) ),
	array( 'en' => 'vacuum rise test', 'pt' => 'ensaio de subida de vácuo', 'not' => array( 'teste de aumento de vácuo', 'ensaio de subida de pressão negativa' ) ),
	array( 'en' => 'fixed stations', 'pt' => 'estações fixas', 'not' => array( 'postos fixos' ) ),
	array( 'en' => 'mobile carousels', 'pt' => 'carrosséis móveis', 'not' => array( 'carrosséis portáteis' ) ),
	array( 'en' => 'cooling units', 'pt' => 'unidades de arrefecimento', 'not' => array( 'unidades de resfriamento' ) ),
	array( 'en' => 'e-axle', 'pt' => 'e-axle', 'not' => array( 'eixo eletrónico' ) ),
	array( 'en' => 'keg', 'pt' => 'barril', 'not' => array( 'barrica', 'vasilhame' ) ),
	array( 'en' => 'horizontal boring machine', 'pt' => 'mandriladora horizontal', 'not' => array( 'máquina de perfuração horizontal' ) ),
	array( 'en' => 'test benches', 'pt' => 'bancos de ensaio', 'not' => array( 'bancadas de ensaio', 'bancos de teste' ) ),
	array( 'en' => 'test stands', 'pt' => 'bancos de ensaio', 'not' => array( 'bancadas de teste', 'suportes de teste' ) ),
	array( 'en' => 'testing', 'pt' => 'ensaios', 'not' => array( 'testagem' ) ),
	array( 'en' => 'Aerospace & industrials', 'pt' => 'Aeroespacial e industrial', 'not' => array( 'Aeroespacial e industriais', 'Setor aeroespacial e industrial', 'Aeroespacial e indústrias' ) ),
	array( 'en' => 'Exhibit', 'pt' => 'Anexo', 'not' => array( 'Exposição', 'Exibição' ) ),
	array( 'en' => 'Section', 'pt' => 'Cláusula', 'not' => array( 'Secção' ) ),
	array( 'en' => 'RECITALS', 'pt' => 'CONSIDERANDOS', 'not' => array( 'RECITAIS' ) ),
	array( 'en' => 'Products', 'pt' => 'Produtos', 'not' => array( 'Produtos e artigos' ) ),
	array( 'en' => 'Ascential Indemnity', 'pt' => 'Indemnização da Ascential', 'not' => array( 'Indenização Ascential' ) ),
	array( 'en' => 'England', 'pt' => 'Inglaterra', 'not' => array( 'England' ) ),
	array( 'en' => 'West Flanders', 'pt' => 'Flandres Ocidental', 'not' => array( 'West Flanders', 'Flandres Oeste' ) ),
	array( 'en' => 'Poland', 'pt' => 'Polónia', 'not' => array( 'Poland', 'Polônia' ) ),
	array( 'en' => 'Play', 'pt' => 'Reproduzir', 'not' => array( 'Jogar', 'Tocar música' ) ),
	array( 'en' => 'Listen to this article', 'pt' => 'Ouvir este artigo', 'not' => array( 'Escute este artigo' ) ),
	array( 'en' => 'Read the article', 'pt' => 'Ler artigo', 'not' => array( 'Leia o artigo completo' ) ),
	array( 'en' => 'chapters', 'pt' => 'capítulos', 'not' => array( 'capítulos do livro' ) ),
	array( 'en' => 'Share', 'pt' => 'Partilhar', 'not' => array( 'Compartilhar' ) ),
	array( 'en' => 'Copy link', 'pt' => 'Copiar link', 'not' => array( 'Copiar ligação de endereço' ) ),
	array( 'en' => 'Email', 'pt' => 'Enviar por e-mail', 'not' => array( 'Correio eletrónico simples' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'pt' => 'Brochura de carga de fluido frigorigéneo', 'not' => array( 'Folheto de carregamento de refrigerante', 'Brochura de carga de refrigerante' ) ),
	array( 'en' => 'Titan', 'pt' => 'Titan', 'not' => array( 'Titã' ) ),
	array( 'en' => 'Explore', 'pt' => 'Explorar', 'not' => array( 'Explore mais', 'Descobrir tudo' ) ),
	array( 'en' => 'Browse catalog', 'pt' => 'Consulte o catálogo', 'not' => array( 'Navegar no catálogo', 'Procurar no catálogo' ) ),
	array( 'en' => 'Browse all resources', 'pt' => 'Consulte todos os recursos', 'not' => array( 'Navegar em todos os recursos', 'Todos os recursos' ) ),
	array( 'en' => 'Explore the Catalog', 'pt' => 'Explore o catálogo', 'not' => array( 'Explorar o Catálogo' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'pt' => 'Pronto para modernizar a sua infraestrutura?', 'not' => array( 'Preparado para atualizar a sua infraestrutura?' ) ),
	array( 'en' => 'gantry milling', 'pt' => 'fresagem em pórtico', 'not' => array( 'moagem de pórtico', 'fresagem de gantry' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'pt' => 'Máquina combinada de equilibragem de núcleos a alta e baixa velocidade', 'not' => array( 'Máquina de equilibragem de núcleo combinada de alta e baixa velocidade' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'pt' => 'Banco de ensaio dinâmico de caudal de turbocompressores', 'not' => array( 'Banco de fluxo dinâmico de sobrealimentador' ) ),
	array( 'en' => 'fully loaded test', 'pt' => 'ensaio com carga total', 'not' => array( 'teste totalmente carregado' ) ),
	array( 'en' => 'Addresses', 'pt' => 'Responde a', 'not' => array( 'Elimina' ) ),
	array( 'en' => 'is now', 'pt' => 'passa a ser', 'not' => array( 'está agora' ) ),
	array( 'en' => 'sales inquiry', 'pt' => 'pedido de informação comercial', 'not' => array( 'consulta de vendas', 'inquérito de vendas' ) ),
	array( 'en' => 'Priority 1: High Priority', 'pt' => 'Prioridade 1: Alta', 'not' => array( 'Prioridade 1: Prioridade alta' ) ),
	array( 'en' => 'Priority 2: Medium Priority', 'pt' => 'Prioridade 2: Média', 'not' => array( 'Prioridade 2: Prioridade média' ) ),
	array( 'en' => 'Priority 3: Low Priority / Routine', 'pt' => 'Prioridade 3: Baixa / Rotina', 'not' => array( 'Prioridade 3: Prioridade baixa / Rotina' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'pt' => 'Pesquisar em ascentialtech.com', 'not' => array( 'A pesquisar ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'pt' => 'Vista de calendário indisponível', 'not' => array( 'Visualização de calendário indisponível' ) ),
	array( 'en' => 'balancer', 'pt' => 'equilibradora', 'not' => array( 'balanceadora', 'equilibrador' ) ),
	array( 'en' => 'balancing', 'pt' => 'equilibragem', 'not' => array( 'balanceamento', 'equilibração' ) ),
	array( 'en' => 'balancing machine', 'pt' => 'máquina de equilibragem', 'not' => array( 'máquina de balanceamento' ) ),
	array( 'en' => 'Balancing Machines', 'pt' => 'Máquinas de equilibragem', 'not' => array( 'Máquinas balanceadoras' ) ),
	array( 'en' => 'Dynamic Balancing Machines', 'pt' => 'Máquinas de equilibragem dinâmica', 'not' => array( 'Máquinas de Balanceamento Dinâmico' ) ),
	array( 'en' => 'Automotive Industry Balancers', 'pt' => 'Equilibradoras para a indústria automóvel', 'not' => array( 'Equilibradoras da indústria automóvel', 'Equilibradores da indústria automotiva' ) ),
	array( 'en' => 'Industrial Balancing Machine', 'pt' => 'Máquina de equilibragem industrial', 'not' => array( 'Máquina Industrial de Balanceamento' ) ),
	array( 'en' => 'Fan Balancer', 'pt' => 'Equilibradora de ventiladores', 'not' => array( 'Equilibrador de Ventilador' ) ),
	array( 'en' => 'Brake Disc Balancer', 'pt' => 'Equilibradora de discos de travão', 'not' => array( 'Equilibrador de Travão de Disco' ) ),
	array( 'en' => 'Clutch and Flywheel Balancer', 'pt' => 'Equilibradora de embraiagens e volantes de motor', 'not' => array( 'Equilibrador de Embraiagem e Volante' ) ),
	array( 'en' => 'Differential Case Balancer', 'pt' => 'Equilibradora de cárteres de diferencial', 'not' => array( 'Equilibrador de Cárter Diferencial' ) ),
	array( 'en' => 'Pulley Balancer', 'pt' => 'Equilibradora de polias', 'not' => array( 'Equilibrador de Polia' ) ),
	array( 'en' => 'Pump Impeller Balancer', 'pt' => 'Equilibradora de impulsores de bomba', 'not' => array( 'Equilibrador de Rotor de Bomba' ) ),
	array( 'en' => 'Transmission Component Balancer', 'pt' => 'Equilibradora de componentes de caixa de velocidades', 'not' => array( 'Equilibrador de Componentes de Transmissão' ) ),
	array( 'en' => 'Aircraft Wheel Balancer', 'pt' => 'Equilibradora de rodas de aeronaves', 'not' => array( 'Equilibrador de Roda de Avião' ) ),
	array( 'en' => 'Electric Motor Balancer', 'pt' => 'Equilibradora de motores elétricos', 'not' => array( 'Equilibrador de Motor Elétrico' ) ),
	array( 'en' => 'Crankshaft Balancer', 'pt' => 'Equilibradora de cambotas', 'not' => array( 'Equilibrador de Virabrequim' ) ),
	array( 'en' => 'Turbine Component Balancer', 'pt' => 'Equilibradora de componentes de turbina', 'not' => array( 'Equilibrador de Componentes de Turbina' ) ),
	array( 'en' => 'Driveshaft balancing machine', 'pt' => 'Máquina de equilibragem de veios de transmissão', 'not' => array( 'Máquina de equilibragem de eixos de transmissão' ) ),
	array( 'en' => 'propeller balancers', 'pt' => 'equilibradoras de hélices', 'not' => array( 'equilibradores de hélices' ) ),
	array( 'en' => 'Turbocharger Balancers', 'pt' => 'Equilibradoras de turbocompressores', 'not' => array( 'Equilibradoras de sobrealimentadores' ) ),
	array( 'en' => 'Balancing as a Service (BaaS)', 'pt' => 'equilibragem como serviço (BaaS)', 'not' => array( 'Equilibragem por contrato como serviço (BaaS)' ) ),
	array( 'en' => 'Balancing Tolerance Calculator', 'pt' => 'Calculadora de tolerância de equilibragem', 'not' => array( 'Calculadora de Tolerância de Balanceamento' ) ),
	array( 'en' => 'Refrigerant Charging Machine Accessories', 'pt' => 'Acessórios para máquinas de carga de fluido frigorigéneo', 'not' => array( 'Acessórios de máquina de carregamento de refrigerante' ) ),
	array( 'en' => 'Refrigerant Fluid & Gas Charging Machines', 'pt' => 'Máquinas de carga de fluidos e gases frigorigéneos', 'not' => array( 'Máquinas de carregamento de fluido e gás refrigerante' ) ),
	array( 'en' => 'Leak Detection & Refrigeration', 'pt' => 'Deteção de fugas e refrigeração', 'not' => array( 'Detecção de vazamentos e refrigeração' ) ),
	array( 'en' => 'Leak Detection & Gas Management', 'pt' => 'Deteção de fugas e gestão de gases', 'not' => array( 'Refrigeração e gestão de gases', 'Detecção de fugas e gestão de gás' ) ),
	array( 'en' => 'Leak Detection Systems', 'pt' => 'Sistemas de deteção de fugas', 'not' => array( 'Sistemas de detecção de vazamento' ) ),
	array( 'en' => 'Helium Recovery Systems', 'pt' => 'Sistemas de recuperação de hélio', 'not' => array( 'Sistemas de recuperação de Hélio gasoso' ) ),
	array( 'en' => 'Vacuum Chamber', 'pt' => 'Câmara de vácuo', 'not' => array( 'Camera de vácuo' ) ),
	array( 'en' => 'Vacuum Gauge and Instruments', 'pt' => 'Vacuómetros e instrumentos', 'not' => array( 'Medidor de vácuo e instrumentos' ) ),
	array( 'en' => 'Rotary Vacuum Pumps', 'pt' => 'Bombas de vácuo rotativas', 'not' => array( 'Bombas rotativas de aspiração' ) ),
	array( 'en' => 'Transfer Pumps & Storage', 'pt' => 'Bombas de transferência e armazenamento', 'not' => array( 'Bombas de transferência e estocagem' ) ),
	array( 'en' => 'Ultrasonic Welding Systems', 'pt' => 'Sistemas de soldadura por ultrassons', 'not' => array( 'Sistemas de solda por ultrassom' ) ),
	array( 'en' => 'Data Acquisition Systems', 'pt' => 'Sistemas de aquisição de dados', 'not' => array( 'Sistemas de coleta de dados' ) ),
	array( 'en' => 'Electrical Safety Test', 'pt' => 'Ensaio de segurança elétrica', 'not' => array( 'Teste de segurança elétrica' ) ),
	array( 'en' => 'Performance Test Systems', 'pt' => 'Sistemas de ensaio de desempenho', 'not' => array( 'Sistemas de teste de performance' ) ),
	array( 'en' => 'Recovery Systems', 'pt' => 'Sistemas de recuperação', 'not' => array( 'Sistemas de recolha e reaproveitamento' ) ),
	array( 'en' => 'Evacuation', 'pt' => 'Evacuação', 'not' => array( 'Esvaziamento' ) ),
	array( 'en' => 'Systems and Machines', 'pt' => 'Sistemas e máquinas', 'not' => array( 'Sistemas e maquinaria' ) ),
	array( 'en' => 'Safety', 'pt' => 'Segurança', 'not' => array( 'Salvaguarda' ) ),
	array( 'en' => 'Tracer Gases', 'pt' => 'Gases traçadores', 'not' => array( 'Gases de rastreio' ) ),
	array( 'en' => 'Cold & Hot Rolling Mills', 'pt' => 'Laminadores a frio e a quente', 'not' => array( 'Moinhos de laminação a frio e a quente' ) ),
	array( 'en' => 'Furnace & Blast Furnace Technology', 'pt' => 'Tecnologia de fornos e altos-fornos', 'not' => array( 'Tecnologia de fornalhas' ) ),
	array( 'en' => 'Handling Machines & Manipulators', 'pt' => 'Máquinas de manipulação e manipuladores', 'not' => array( 'Máquinas de manuseio e manipuladores' ) ),
	array( 'en' => 'Paper & Plastic Industry', 'pt' => 'Indústria do papel e do plástico', 'not' => array( 'Indústria de papel e plástico' ) ),
	array( 'en' => 'Pipe Manufacturing', 'pt' => 'Fabrico de tubos', 'not' => array( 'Manufatura de tubos' ) ),
	array( 'en' => 'Press Technology & Hydroforming', 'pt' => 'Tecnologia de prensas e hidroconformação', 'not' => array( 'Tecnologia de imprensa e hidroformação' ) ),
	array( 'en' => 'Automation and Drive Systems', 'pt' => 'Sistemas de automação e de acionamento', 'not' => array( 'Sistemas de automatização e propulsão' ) ),
	array( 'en' => 'Linear Motion', 'pt' => 'Movimento linear', 'not' => array( 'Moção linear' ) ),
	array( 'en' => 'Rotary Motion', 'pt' => 'Movimento rotativo', 'not' => array( 'Moção rotativa' ) ),
	array( 'en' => 'Axles', 'pt' => 'Eixos', 'not' => array( 'Eixos de roda' ) ),
	array( 'en' => 'Assembly', 'pt' => 'Montagem', 'not' => array( 'Assembleia' ) ),
	array( 'en' => 'Valves', 'pt' => 'Válvulas', 'not' => array( 'Torneiras' ) ),
	array( 'en' => 'Certification Documentation', 'pt' => 'Documentação de certificação', 'not' => array( 'Documentos de certificado' ) ),
	array( 'en' => 'Consulting', 'pt' => 'Consultoria', 'not' => array(  ) ),
	array( 'en' => 'Environmental Technology', 'pt' => 'Tecnologia ambiental', 'not' => array( 'Tecnologia do meio ambiente' ) ),
	array( 'en' => 'Gas Industry & Compressor Stations', 'pt' => 'Indústria do gás e estações de compressores', 'not' => array( 'Indústria de gás e postos de compressão' ) ),
	array( 'en' => 'Water & Wastewater Systems', 'pt' => 'Sistemas de água e de águas residuais', 'not' => array( 'Sistemas de água e esgoto' ) ),
	array( 'en' => 'Grinding Technology', 'pt' => 'Tecnologia de retificação', 'not' => array( 'Tecnologia de moagem' ) ),
	array( 'en' => 'Automatic Grinder Control', 'pt' => 'Controlo automático de retificadoras', 'not' => array( 'Controle automático de retífica' ) ),
	array( 'en' => 'Profile Grinder Control', 'pt' => 'Controlo de retificadoras de perfis', 'not' => array( 'Controle de retífica de perfil' ) ),
	array( 'en' => 'Roll Grinding Machines', 'pt' => 'Retificadoras de cilindros', 'not' => array( 'Máquinas de moagem de rolos' ) ),
	array( 'en' => 'Brushing and Polishing Machines', 'pt' => 'Máquinas de escovagem e polimento', 'not' => array( 'Máquinas de escovação e lustragem' ) ),
	array( 'en' => 'Retrofit and modernization', 'pt' => 'Retrofit e modernização', 'not' => array( 'Reequipamento e modernização' ) ),
	array( 'en' => 'Robot Application', 'pt' => 'Aplicações robotizadas', 'not' => array( 'Aplicação de robôs' ) ),
	array( 'en' => 'Spare parts', 'pt' => 'Peças sobressalentes', 'not' => array( 'Peças de reposição' ) ),
	array( 'en' => 'Machine Tools and Special Machines', 'pt' => 'Máquinas-ferramenta e máquinas especiais', 'not' => array( 'Ferramentas de máquina e máquinas especiais' ) ),
	array( 'en' => 'Mobile Equipment', 'pt' => 'Equipamento móvel', 'not' => array( 'Equipamentos móveis portáteis' ) ),
	array( 'en' => 'Vehicles End-of-Line', 'pt' => 'Fim de linha de veículos', 'not' => array( 'Veículos Fim de Linha' ) ),
	array( 'en' => 'Precision Machining', 'pt' => 'Maquinagem de precisão', 'not' => array( 'Usinagem de precisão' ) ),
	array( 'en' => 'NVH Testing', 'pt' => 'Ensaios de NVH', 'not' => array( 'Teste de NVH' ) ),
	array( 'en' => 'OBD & Emissions Testing', 'pt' => 'Ensaios de OBD e de emissões', 'not' => array( 'Teste de OBD e emissões' ) ),
	array( 'en' => 'Testing Systems', 'pt' => 'Sistemas de ensaio', 'not' => array( 'Sistemas de teste' ) ),
	array( 'en' => 'Testing Technology', 'pt' => 'Tecnologia de ensaio', 'not' => array( 'Tecnologia de teste' ) ),
	array( 'en' => 'Vibration Absorbing Cast', 'pt' => 'Fundição amortecedora de vibrações', 'not' => array( 'Molde absorvente de vibração' ) ),
	array( 'en' => 'Field Balancers', 'pt' => 'Equilibradoras portáteis', 'not' => array( 'Equilibradores de campo' ) ),
	array( 'en' => 'Train Wheels', 'pt' => 'Rodas de comboio', 'not' => array( 'Rodas de trem' ) ),
	array( 'en' => 'Wheel Sets', 'pt' => 'Rodados', 'not' => array( 'Conjuntos de roda' ) ),
	array( 'en' => 'Water Meters', 'pt' => 'Contadores de água', 'not' => array( 'Medidores de água' ) ),
	array( 'en' => 'Electric Armatures', 'pt' => 'Armaduras elétricas', 'not' => array( 'Induzidos elétricos rotativos' ) ),
	array( 'en' => 'Turbine Rotors', 'pt' => 'Rotores de turbina', 'not' => array( 'Rotores de turbinas a vapor' ) ),
	array( 'en' => 'Tools and Tool Holders', 'pt' => 'Ferramentas e porta-ferramentas', 'not' => array( 'Ferramentas e suportes de ferramenta' ) ),
	array( 'en' => 'Woodworking Tools and Saws', 'pt' => 'Ferramentas de carpintaria e serras', 'not' => array( 'Ferramentas de madeira e serras' ) ),
	array( 'en' => 'Fans', 'pt' => 'Ventiladores', 'not' => array( 'Ventoinhas industriais' ) ),
	array( 'en' => 'Pump Impellers', 'pt' => 'Impulsores de bomba', 'not' => array( 'Rotores de bomba' ) ),
	array( 'en' => 'Dyno', 'pt' => 'Dinamómetro', 'not' => array( 'Dinamômetro de rolos' ) ),
	array( 'en' => 'Case Study', 'pt' => 'Estudo de caso', 'not' => array( 'Caso de estudo' ) ),
	array( 'en' => 'Certifications', 'pt' => 'Certificações', 'not' => array( 'Certificados de qualidade' ) ),
	array( 'en' => 'Technical Papers', 'pt' => 'Documentos técnicos', 'not' => array( 'Papéis técnicos' ) ),
	array( 'en' => 'Press Announcements', 'pt' => 'Comunicados de imprensa', 'not' => array( 'Anúncios de imprensa' ) ),
	array( 'en' => 'Press Announcement', 'pt' => 'Comunicado de imprensa', 'not' => array( 'Anúncio de imprensa' ) ),
	array( 'en' => 'Upcoming Events', 'pt' => 'Próximos eventos', 'not' => array( 'Eventos próximos' ) ),
	array( 'en' => 'View all press releases', 'pt' => 'Ver todos os comunicados', 'not' => array( 'Veja todos os lançamentos' ) ),
	array( 'en' => 'View all events', 'pt' => 'Ver todos os eventos', 'not' => array( 'Veja todos os acontecimentos' ) ),
	array( 'en' => 'Schedule a Meeting', 'pt' => 'Agende uma reunião', 'not' => array( 'Agendar um encontro' ) ),
	array( 'en' => 'Trending Products', 'pt' => 'Produtos em destaque', 'not' => array( 'Produtos tendência' ) ),
	array( 'en' => 'Business Unit', 'pt' => 'Unidade de negócio', 'not' => array( 'Unidade empresarial' ) ),
	array( 'en' => 'Resource Type', 'pt' => 'Tipo de recurso', 'not' => array( 'Tipo de material' ) ),
	array( 'en' => 'Resource Topic', 'pt' => 'Tema', 'not' => array( 'Tópico de recurso' ) ),
	array( 'en' => 'Brand', 'pt' => 'Marca', 'not' => array( 'Etiqueta de marca' ) ),
	array( 'en' => 'Product Category', 'pt' => 'Categoria de produto', 'not' => array( 'Categoria do artigo' ) ),
	array( 'en' => 'Filter by category', 'pt' => 'Filtrar por categoria', 'not' => array( 'Filtro por categoria' ) ),
	array( 'en' => 'Clear all filters', 'pt' => 'Limpar todos os filtros', 'not' => array( 'Apagar todos os filtros' ) ),
	array( 'en' => 'Sort by:', 'pt' => 'Ordenar por:', 'not' => array( 'Classificar por:' ) ),
	array( 'en' => 'Expand all', 'pt' => 'Expandir tudo', 'not' => array( 'Expandir todos os itens' ) ),
	array( 'en' => 'All products', 'pt' => 'Todos os produtos', 'not' => array( 'Produtos todos' ) ),
	array( 'en' => 'Loading products...', 'pt' => 'A carregar produtos...', 'not' => array( 'Carregando produtos...' ) ),
	array( 'en' => 'Overview', 'pt' => 'Visão geral', 'not' => array( 'Panorama geral' ) ),
	array( 'en' => 'Specifications', 'pt' => 'Especificações', 'not' => array( 'Ficha de especificação' ) ),
	array( 'en' => 'Technical specifications', 'pt' => 'Especificações técnicas', 'not' => array( 'Especificações de engenharia' ) ),
	array( 'en' => 'Frequently Asked Questions', 'pt' => 'Perguntas frequentes', 'not' => array( 'Questões frequentemente colocadas' ) ),
	array( 'en' => 'Related Resources', 'pt' => 'Recursos relacionados', 'not' => array( 'Materiais afins' ) ),
	array( 'en' => 'Related Products', 'pt' => 'Produtos relacionados', 'not' => array( 'Artigos afins' ) ),
	array( 'en' => 'Selected Capabilities', 'pt' => 'Capacidades selecionadas', 'not' => array( 'Capacidades escolhidas' ) ),
	array( 'en' => 'Gallery', 'pt' => 'Galeria', 'not' => array( 'Galeria de Imagens' ) ),
	array( 'en' => 'Comparison', 'pt' => 'Comparação', 'not' => array( 'Comparativo' ) ),
	array( 'en' => 'Get a quote', 'pt' => 'Obtenha um orçamento', 'not' => array( 'Peça cotação', 'Pedido de orçamento' ) ),
	array( 'en' => 'Request a quote', 'pt' => 'Solicite um orçamento', 'not' => array( 'Pedido de cotação' ) ),
	array( 'en' => 'Request a demo', 'pt' => 'Solicite uma demonstração', 'not' => array( 'Pedido de demonstração', 'Solicitação de demo' ) ),
	array( 'en' => 'Speak with an Expert', 'pt' => 'Fale com um especialista', 'not' => array( 'Converse com um Especialista' ) ),
	array( 'en' => 'Speak to an expert', 'pt' => 'Fale com um especialista', 'not' => array( 'Falar a um especialista' ) ),
	array( 'en' => 'Speak with a service professional', 'pt' => 'Fale com um profissional de assistência', 'not' => array( 'Converse com um profissional de serviço' ) ),
	array( 'en' => 'See our solutions', 'pt' => 'Veja as nossas soluções', 'not' => array( 'Ver nossas soluções' ) ),
	array( 'en' => 'Download', 'pt' => 'Descarregar', 'not' => array( 'Fazer download', 'Descarregamento' ) ),
	array( 'en' => 'Download brochure', 'pt' => 'Descarregue a brochura', 'not' => array( 'Baixar brochura', 'Download da brochura' ) ),
	array( 'en' => 'Get a service quote', 'pt' => 'Obtenha um orçamento de assistência', 'not' => array( 'Peça um orçamento de serviço' ) ),
	array( 'en' => 'Plan Levels', 'pt' => 'Níveis de plano', 'not' => array( 'Patamares do Plano' ) ),
	array( 'en' => 'Remote support', 'pt' => 'Assistência remota', 'not' => array( 'Suporte remoto' ) ),
	array( 'en' => 'Response time', 'pt' => 'Tempo de resposta', 'not' => array( 'Prazo de resposta' ) ),
	array( 'en' => 'Customer portal', 'pt' => 'Portal do cliente', 'not' => array( 'Portal de cliente' ) ),
	array( 'en' => 'Preventive maintenance', 'pt' => 'Manutenção preventiva', 'not' => array( 'Manutenção preventiva programada' ) ),
	array( 'en' => 'Instructor-led training', 'pt' => 'Formação com formador', 'not' => array( 'Treinamento com instrutor' ) ),
	array( 'en' => 'Train the trainer', 'pt' => 'Formação de formadores', 'not' => array( 'Treinar o treinador' ) ),
	array( 'en' => 'Self-service training material', 'pt' => 'Material de formação em autosserviço', 'not' => array( 'Material de treinamento self-service' ) ),
	array( 'en' => 'Shipping', 'pt' => 'Expedição', 'not' => array( 'Envio de mercadoria' ) ),
	array( 'en' => 'Next day', 'pt' => 'Dia seguinte', 'not' => array( 'Próximo dia' ) ),
	array( 'en' => 'Standard rate', 'pt' => 'Tarifa normal', 'not' => array( 'Taxa padrão' ) ),
	array( 'en' => 'Discounted rate', 'pt' => 'Tarifa com desconto', 'not' => array( 'Taxa descontada' ) ),
	array( 'en' => 'Preferred rate', 'pt' => 'Tarifa preferencial', 'not' => array( 'Taxa preferida' ) ),
	array( 'en' => 'Onsite emergency response and coverage', 'pt' => 'Resposta de emergência no local e respetiva cobertura', 'not' => array( 'Resposta de emergência no site' ) ),
	array( 'en' => 'Intervention time (in business hours)', 'pt' => 'Tempo de intervenção (em horas úteis)', 'not' => array( 'Tempo de intervenção em horário comercial' ) ),
	array( 'en' => 'Performance analysis', 'pt' => 'Análise de desempenho', 'not' => array( 'Análise de performance' ) ),
	array( 'en' => 'Spare parts eCommerce', 'pt' => 'Comércio eletrónico de peças sobressalentes', 'not' => array( 'eCommerce de peças de reposição' ) ),
	array( 'en' => 'Critical spare parts', 'pt' => 'Peças sobressalentes críticas', 'not' => array( 'Peças de reposição críticas' ) ),
	array( 'en' => 'System health check', 'pt' => 'Verificação do estado do sistema', 'not' => array( 'Verificação de saúde do sistema' ) ),
	array( 'en' => 'Open a service request', 'pt' => 'Abra um pedido de assistência', 'not' => array( 'Abrir um pedido de assistência' ) ),
	array( 'en' => 'Submit a service request', 'pt' => 'Submeta um pedido de assistência', 'not' => array( 'Enviar um pedido de serviço' ) ),
	array( 'en' => 'Become a service partner', 'pt' => 'Torne-se um parceiro de assistência', 'not' => array( 'Seja um parceiro de serviço' ) ),
	array( 'en' => 'Training courses', 'pt' => 'Cursos de formação', 'not' => array( 'Cursos de treinamento' ) ),
	array( 'en' => 'Service & Support Products', 'pt' => 'Produtos de serviço e assistência', 'not' => array( 'Produtos de serviço e suporte' ) ),
	array( 'en' => 'Support Services', 'pt' => 'Serviços de assistência', 'not' => array( 'Serviços de suporte' ) ),
	array( 'en' => 'Service & support', 'pt' => 'Serviço e assistência', 'not' => array( 'Serviço e suporte' ) ),
	array( 'en' => 'Skip to content', 'pt' => 'Saltar para o conteúdo', 'not' => array( 'Pular para o conteúdo', 'Ir para a conteúdo' ) ),
	array( 'en' => 'Search', 'pt' => 'Pesquisar', 'not' => array( 'Busca', 'Buscar', 'Pesquisa' ) ),
	array( 'en' => 'Reset chat', 'pt' => 'Reiniciar conversa', 'not' => array( 'Resetar chat' ) ),
	array( 'en' => 'Leave this field empty', 'pt' => 'Deixe este campo vazio', 'not' => array( 'Deixar este campo em branco' ) ),
	array( 'en' => 'Contact name', 'pt' => 'Nome do contacto', 'not' => array( 'Nome do contato' ) ),
	array( 'en' => 'Country', 'pt' => 'País', 'not' => array( 'Nação' ) ),
	array( 'en' => 'Choose your division:', 'pt' => 'Escolha a sua divisão:', 'not' => array( 'Selecione sua divisão:' ) ),
	array( 'en' => 'Select your support team', 'pt' => 'Selecione a sua equipa de assistência', 'not' => array( 'Selecione seu time de suporte' ) ),
	array( 'en' => 'Select an option', 'pt' => 'Selecione uma opção', 'not' => array( 'Escolher uma opção' ) ),
	array( 'en' => 'Learn more', 'pt' => 'Saiba mais', 'not' => array( 'Aprenda mais', 'Mais informação' ) ),
	array( 'en' => 'Read more', 'pt' => 'Ler mais', 'not' => array( 'Leia mais' ) ),
	array( 'en' => 'Read announcement', 'pt' => 'Ler comunicado', 'not' => array( 'Ler anúncio' ) ),
	array( 'en' => 'News and announcements', 'pt' => 'Notícias e comunicados', 'not' => array( 'Novidades e anúncios' ) ),
	array( 'en' => 'Latest news and insights', 'pt' => 'Últimas notícias e perspetivas', 'not' => array( 'Notícias recentes e insights' ) ),
	array( 'en' => 'Industries served', 'pt' => 'Setores que servimos', 'not' => array( 'Indústrias servidas' ) ),
	array( 'en' => 'Locations', 'pt' => 'Localizações', 'not' => array( 'Localidades' ) ),
	array( 'en' => 'History and brands', 'pt' => 'História e marcas', 'not' => array( 'Histórico e marcas' ) ),
	array( 'en' => 'Careers', 'pt' => 'Carreiras', 'not' => array( 'Vagas de carreira' ) ),
	array( 'en' => 'Corporate information', 'pt' => 'Informações corporativas', 'not' => array( 'Dados corporativos' ) ),
	array( 'en' => 'Supply chain requirements', 'pt' => 'Requisitos da cadeia de abastecimento', 'not' => array( 'Requisitos da cadeia de suprimentos' ) ),
	array( 'en' => 'Accessibility statement', 'pt' => 'Declaração de acessibilidade', 'not' => array( 'Declaração sobre acessibilidade' ) ),
	array( 'en' => 'Supplier portal', 'pt' => 'Portal de fornecedores', 'not' => array( 'Portal do provedor' ) ),
	array( 'en' => 'Trademarks', 'pt' => 'Marcas registadas', 'not' => array( 'Marcas registradas' ) ),
	array( 'en' => 'Terms', 'pt' => 'Termos', 'not' => array( 'Condições de termo' ) ),
	array( 'en' => 'Blog', 'pt' => 'Blogue', 'not' => array( 'Blog' ) ),
	array( 'en' => 'Resource hub', 'pt' => 'Centro de recursos', 'not' => array( 'Hub de recursos', 'Central de recursos' ) ),
	array( 'en' => 'Visit hub', 'pt' => 'Visite o centro de recursos', 'not' => array( 'Visitar hub' ) ),
	array( 'en' => 'Stay connected', 'pt' => 'Mantenha-se em contacto', 'not' => array( 'Fique conectado' ) ),
	array( 'en' => 'Partners', 'pt' => 'Parceiros', 'not' => array( 'Sócios' ) ),
	array( 'en' => 'Climate & energy', 'pt' => 'Climatização e energia', 'not' => array( 'Clima e energia' ) ),
	array( 'en' => 'Off-highway & mobile', 'pt' => 'Fora de estrada e máquinas móveis', 'not' => array( 'Fora-de-estrada e móvel' ) ),
	array( 'en' => 'Metals automation and systems integrations', 'pt' => 'Automação de metais e integração de sistemas', 'not' => array( 'Automatização de metais e integrações de sistema' ) ),
	array( 'en' => 'Utilities construction', 'pt' => 'Construção de redes de serviços públicos', 'not' => array( 'Construção de infraestruturas' ) ),
	array( 'en' => 'Transportation', 'pt' => 'Transportes', 'not' => array( 'Transporte rodoviário' ) ),
	array( 'en' => 'Vehicle end-of-line solutions', 'pt' => 'Soluções de fim de linha de veículos', 'not' => array( 'Soluções de final de linha veicular' ) ),
	array( 'en' => 'Chassis, hub and steerable dyno', 'pt' => 'Dinamómetro de chassis, de cubo e direcional', 'not' => array( 'Dinamômetro de chassi, cubo e direção' ) ),
	array( 'en' => 'Cabin HVAC and refrigerated trailers', 'pt' => 'AVAC de cabina e reboques refrigerados', 'not' => array( 'HVAC de cabine e reboques refrigerados' ) ),
	array( 'en' => 'HVAC fan and blower balancing', 'pt' => 'equilibragem de ventiladores e insufladores de AVAC', 'not' => array( 'balanceamento de ventiladores e sopradores HVAC' ) ),
	array( 'en' => 'vapor compression cooling', 'pt' => 'arrefecimento por compressão de vapor', 'not' => array( 'resfriamento por compressão de vapor' ) ),
	array( 'en' => 'turbine and jet engine balancing', 'pt' => 'equilibragem de turbinas e motores a jato', 'not' => array( 'balanceamento de turbinas e motores a jato' ) ),
	array( 'en' => 'diesel turbocharger balancing', 'pt' => 'equilibragem de turbocompressores diesel', 'not' => array( 'balanceamento de turbo diesel' ) ),
	array( 'en' => 'Hydraulic and electric test stands', 'pt' => 'Bancos de ensaio hidráulicos e elétricos', 'not' => array( 'Bancadas de teste hidráulico e elétrico' ) ),
	array( 'en' => 'Roll grinding, texturing and controls', 'pt' => 'retificação de cilindros, texturização e controlos', 'not' => array( 'moagem de rolos, texturização e controles' ) ),
	array( 'en' => 'OBD consulting and training', 'pt' => 'consultoria e formação em OBD', 'not' => array( 'consultoria e treinamento em OBD' ) ),
	array( 'en' => 'AI-driven machine analytics', 'pt' => 'análise de máquinas orientada por IA', 'not' => array( 'analítica de máquina dirigida por IA' ) ),
	array( 'en' => 'Service level agreements available', 'pt' => 'Acordos de nível de serviço disponíveis', 'not' => array( 'Contratos de nível de serviço disponíveis' ) ),
	array( 'en' => 'Real-time remote monitoring of your production equipment', 'pt' => 'Monitorização remota em tempo real do seu equipamento de produção', 'not' => array( 'Monitoramento remoto em tempo real do seu equipamento produtivo' ) ),
	array( 'en' => 'downtime', 'pt' => 'tempo de paragem', 'not' => array( 'tempo de inatividade', 'tempo de parada' ) ),
	array( 'en' => 'unplanned downtime', 'pt' => 'tempo de paragem não planeado', 'not' => array( 'tempo de inatividade não planejado' ) ),
	array( 'en' => 'throughput', 'pt' => 'débito de produção', 'not' => array( 'rendimento da produção', 'vazão de produção' ) ),
	array( 'en' => 'machine health', 'pt' => 'condição do equipamento', 'not' => array( 'saúde da máquina' ) ),
	array( 'en' => 'equipment condition', 'pt' => 'condição do equipamento', 'not' => array( 'estado de saúde do equipamento' ) ),
	array( 'en' => 'shortly', 'pt' => 'em breve', 'not' => array( 'em poucos minutos', 'dentro de minutos' ) ),
	array( 'en' => 'non-destructive testing (NDT)', 'pt' => 'ensaios não destrutivos (END)', 'not' => array( 'testes não destrutivos (NDT)' ) ),
	array( 'en' => 'NDT inspection', 'pt' => 'inspeção por END', 'not' => array( 'inspeção de END', 'inspeção NDT' ) ),
	array( 'en' => 'mission-critical', 'pt' => 'de missão crítica', 'not' => array( 'puramente crítico' ) ),
	array( 'en' => 'aftermarket', 'pt' => 'mercado de reposição', 'not' => array( 'mercado secundário', 'pós-venda de peças' ) ),
	array( 'en' => 'journals', 'pt' => 'munhões', 'not' => array( 'diários', 'jornais' ) ),
	array( 'en' => 'grinding', 'pt' => 'retificação', 'not' => array( 'moagem', 'esmerilhamento' ) ),
	array( 'en' => 'machining', 'pt' => 'maquinagem', 'not' => array( 'usinagem' ) ),
	array( 'en' => 'PLC', 'pt' => 'autómatos programáveis', 'not' => array( 'controladores lógicos programáveis CLP' ) ),
	array( 'en' => 'rotor', 'pt' => 'rotor', 'not' => array( 'induzido rotativo' ) ),
	array( 'en' => 'driveshaft', 'pt' => 'veio de transmissão', 'not' => array( 'eixo de transmissão', 'árvore de transmissão' ) ),
	array( 'en' => 'crankshaft', 'pt' => 'cambota', 'not' => array( 'virabrequim' ) ),
	array( 'en' => 'clutch', 'pt' => 'embraiagem', 'not' => array( 'embreagem' ) ),
	array( 'en' => 'bearing', 'pt' => 'chumaceira', 'not' => array( 'mancal' ) ),
	array( 'en' => 'brake disc', 'pt' => 'disco de travão', 'not' => array( 'disco de freio' ) ),
	array( 'en' => 'brake drum', 'pt' => 'tambor de travão', 'not' => array( 'tambor de freio' ) ),
	array( 'en' => 'tire and wheel', 'pt' => 'pneu e roda', 'not' => array( 'pneu e aro' ) ),
	array( 'en' => 'rim', 'pt' => 'jante', 'not' => array( 'aro de roda' ) ),
	array( 'en' => 'gauging', 'pt' => 'medição dimensional', 'not' => array( 'calibragem dimensional' ) ),
	array( 'en' => 'welding', 'pt' => 'soldadura', 'not' => array( 'solda' ) ),
	array( 'en' => 'screen', 'pt' => 'ecrã', 'not' => array( 'tela' ) ),
	array( 'en' => 'file', 'pt' => 'ficheiro', 'not' => array( 'arquivo digital' ) ),
	array( 'en' => 'training', 'pt' => 'formação', 'not' => array( 'treinamento' ) ),
	array( 'en' => 'team', 'pt' => 'equipa', 'not' => array( 'equipe', 'time' ) ),
	array( 'en' => 'reliable', 'pt' => 'fiável', 'not' => array( 'confiável' ) ),
	array( 'en' => 'monitoring', 'pt' => 'monitorização', 'not' => array( 'monitoramento' ) ),
	array( 'en' => 'manufacturing', 'pt' => 'fabrico', 'not' => array( 'manufatura' ) ),
	array( 'en' => 'subscription', 'pt' => 'subscrição', 'not' => array( 'assinatura' ) ),
	array( 'en' => 'billing', 'pt' => 'faturação', 'not' => array( 'faturamento' ) ),
	array( 'en' => 'registration', 'pt' => 'registo', 'not' => array( 'registro' ) ),
	array( 'en' => 'contact', 'pt' => 'contacto', 'not' => array( 'ponto de contato' ) ),
	array( 'en' => 'detection', 'pt' => 'deteção', 'not' => array( 'detecção' ) ),
	array( 'en' => 'planned', 'pt' => 'planeado', 'not' => array( 'planejado' ) ),
	array( 'en' => 'plant', 'pt' => 'unidade industrial', 'not' => array( 'planta industrial' ) ),
	array( 'en' => 'customer support', 'pt' => 'apoio ao cliente', 'not' => array( 'atendimento ao cliente' ) ),
	array( 'en' => 'uncompromising', 'pt' => 'sem concessões', 'not' => array( 'sem compromissos' ) ),
	array( 'en' => 'engineer', 'pt' => 'conceber', 'not' => array( 'engenhar' ) ),
	array( 'en' => 'expertise', 'pt' => 'conhecimento especializado', 'not' => array( 'expertise' ) ),
	array( 'en' => 'from scratch', 'pt' => 'de raiz', 'not' => array( 'do zero absoluto' ) ),
	array( 'en' => 'at scale', 'pt' => 'em larga escala', 'not' => array( 'em escala' ) ),
	array( 'en' => 'failure', 'pt' => 'falha', 'not' => array( 'fracasso' ) ),
	array( 'en' => 'landing gear', 'pt' => 'trem de aterragem', 'not' => array( 'trem de pouso' ) ),
	array( 'en' => 'challenging', 'pt' => 'desafiante', 'not' => array( 'desafiador' ) ),
	array( 'en' => 'area manager', 'pt' => 'gestor de zona', 'not' => array( 'gerente de área' ) ),
	array( 'en' => 'whitepaper', 'pt' => 'whitepaper', 'not' => array( 'livro branco' ) ),
	array( 'en' => 'eBooks', 'pt' => 'eBooks', 'not' => array( 'livros eletrónicos' ) ),
	array( 'en' => 'Webinars', 'pt' => 'Webinars', 'not' => array( 'Seminários online' ) ),
	array( 'en' => 'Podcasts', 'pt' => 'Podcasts', 'not' => array( 'Emissões de áudio' ) ),
	array( 'en' => 'Brochures', 'pt' => 'Brochuras', 'not' => array( 'Folhetos' ) ),
	array( 'en' => 'Videos', 'pt' => 'Vídeos', 'not' => array( 'Filmes promocionais' ) ),
	array( 'en' => 'Ascential', 'pt' => 'Ascential', 'not' => array( 'Ascensional' ) ),
	array( 'en' => 'Ascential Care', 'pt' => 'Ascential Care', 'not' => array( 'Cuidado Ascential', 'Ascential Cuidados' ) ),
	array( 'en' => 'Ascentialytics', 'pt' => 'Ascentialytics', 'not' => array( 'Analítica Ascential' ) ),
	array( 'en' => 'Sentia', 'pt' => 'Sentia', 'not' => array( 'Sentida' ) ),
	array( 'en' => 'Cimat', 'pt' => 'Cimat', 'not' => array( 'Cimato' ) ),
	array( 'en' => 'Galileo', 'pt' => 'Galileo', 'not' => array( 'Galileu' ) ),
	array( 'en' => 'Kleinknecht', 'pt' => 'Kleinknecht', 'not' => array( 'Kleinknech' ) ),
	array( 'en' => 'Lismar', 'pt' => 'Lismar', 'not' => array( 'Lismarte' ) ),
	array( 'en' => 'Burke Porter', 'pt' => 'Burke Porter', 'not' => array( 'Porto Burke', 'Burke Portador' ) ),
	array( 'en' => 'WinterPark', 'pt' => 'WinterPark', 'not' => array( 'Parque de Inverno' ) ),
	array( 'en' => 'Bauer', 'pt' => 'Bauer', 'not' => array( 'Bauero' ) ),
	array( 'en' => 'ADAS Garage', 'pt' => 'ADAS Garage', 'not' => array( 'Garagem ADAS' ) ),
	array( 'en' => 'Impossible? Done.', 'pt' => 'Impossible? Done.', 'not' => array( 'Impossível? Feito.' ) ),
	array( 'en' => 'Titan Application System', 'pt' => 'Sistema Titan', 'not' => array( 'Sistema de Aplicação Titã' ) ),
);
