<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

return array(
	array( 'en' => '*', 'ro' => 'Întreaga pagină se adresează cititorului formal, cu dumneavoastră, în fiecare slot: text curent, titluri, supratitluri, benzi scrise cu MAJUSCULE, etichete și texte substituent de formular, atributele alt și aria-label, <title>, meta description, etichetele og: și JSON-LD. Registrul este o proprietate a PAGINII, nu a segmentului: o formă de tu într-o meta description contrazice corpul cu dumneavoastră alături de care se livrează. Verbul stă la persoana a doua plural („Aveți nevoie de asistență?”, „Ne puteți suna”, „Nu știți ce vă spun datele?”), adjectivul și participiul care se acordă cu cititorul stau la plural („Sunteți pregătiți să vă modernizați infrastructura?”, „veți fi mulțumiți”), iar posesivul orientat spre cititor este „dumneavoastră” („adaptate nevoilor dumneavoastră”), scris întotdeauna întreg, niciodată abreviat „dvs.”. Nicio formă de tu (tău, ta, tine, poți, vrei, vezi, începi) nu apare nicăieri, la nicio lungime. BUTOANELE ȘI ETICHETELE DE LINK păstrează verbul din engleză și folosesc imperativul de politețe la plural, care este convenția web românească: „Browse catalog” este „Consultați catalogul”, „Request a demo” este „Solicitați o demonstrație”, „Download” este „Descărcați”, „Contact us” este „Contactați-ne”, „Search” este „Căutați”. Nu transformați niciodată o etichetă-verb în substantiv gol („Catalog”, „Descărcare”, „Căutare” sunt greșite pentru acele butoane) și nu puneți pronume sau posesiv într-o etichetă de control („Protejați-vă investiția” este greșit; „Protecția investiției” este corect). Tot ce nu este etichetă de control — proză, titluri, întrebări, metadate — se adresează cititorului numai cu dumneavoastră.', 'not' => array( 'tău', 'ta', 'tale', 'tăi', 'tine', 'ție', 'ești', 'poți', 'vrei', 'știi', 'vezi', 'faci', 'începi', 'descoperi', 'obții', 'afli', 'dumneata', 'dvs.', 'dvs' ) ),
	array( 'en' => '20-high / six-high mill', 'ro' => 'laminor cu 20 de cilindri / laminor cu șase cilindri', 'not' => array( 'laminor cu 20 de înălțime', 'laminor cu douăzeci de fețe' ) ),
	array( 'en' => '3-jaw chuck', 'ro' => 'mandrină cu trei bacuri', 'not' => array( 'mandrină cu trei fălci', 'mandrină cu trei gheare' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'ro' => 'A DESIGN / B LOGO', 'not' => array( 'UN DESIGN / LOGO B', 'PROIECT A / SIGLA B' ) ),
	array( 'en' => 'active part probing', 'ro' => 'palpare activă a piesei', 'not' => array( 'sondarea activă a piesei', 'testare activă a piesei' ) ),
	array( 'en' => 'actuation systems', 'ro' => 'sisteme de acționare', 'not' => array( 'sisteme de actuare', 'sisteme de activare' ) ),
	array( 'en' => 'adaptive speed control', 'ro' => 'reglare adaptivă a vitezei', 'not' => array( 'controlul adaptiv de viteză' ) ),
	array( 'en' => 'ADAS', 'ro' => 'ADAS', 'not' => array( 'SAAC', 'sisteme de asistență pentru drivere' ) ),
	array( 'en' => 'ADAS alignment', 'ro' => 'calibrare ADAS', 'not' => array( 'aliniere ADAS', 'alinierea ADAS' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'ro' => 'ADVANCING THE MACHINE', 'not' => array( 'AVANSAREA MAȘINII', 'PROMOVĂM MAȘINA', 'Avansăm mașina' ) ),
	array( 'en' => 'air cycle machines', 'ro' => 'mașini cu ciclu de aer', 'not' => array( 'mașini de ciclu aerian' ) ),
	array( 'en' => 'anchoring', 'ro' => 'ancorare în fundație', 'not' => array( 'ancorare navală', 'legare' ) ),
	array( 'en' => 'aperture plate', 'ro' => 'placă cu diafragmă', 'not' => array( 'placă de apertură', 'placă cu deschidere' ) ),
	array( 'en' => 'applications', 'ro' => 'aplicații', 'not' => array( 'cereri', 'solicitări', 'programe' ) ),
	array( 'en' => 'armature', 'ro' => 'armătură', 'not' => array( 'rotor electric', 'întăritură' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'ro' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL MEDICINĂ ȘI ȘTIINȚE ALE VIEȚII', 'ASCENTIAL MEDICAL ȘI ȘTIINȚELE VIEȚII' ) ),
	array( 'en' => 'Ascential Test & Measurement Systems', 'ro' => 'Ascential Test & Measurement Systems', 'not' => array( 'Ascential Sisteme de testare și măsurare', 'Sisteme Ascential de testare și măsurare' ) ),
	array( 'en' => 'Ask Burke Porter', 'ro' => 'Ask Burke Porter', 'not' => array( 'Întreabă-l pe Burke Porter', 'Întrebați Burke Porter' ) ),
	array( 'en' => 'associate attorney', 'ro' => 'avocat colaborator', 'not' => array( 'avocat asociat', 'asociat juridic' ) ),
	array( 'en' => 'audit stations', 'ro' => 'stații de audit', 'not' => array( 'posturi de control contabil' ) ),
	array( 'en' => 'automated handling cells', 'ro' => 'celule automatizate de manipulare', 'not' => array( 'celule de manevrare automatizate' ) ),
	array( 'en' => 'backhoe', 'ro' => 'buldoexcavator', 'not' => array( 'excavator cu spate', 'copiator' ) ),
	array( 'en' => 'baler', 'ro' => 'presă de balotat', 'not' => array( 'presă de fân' ) ),
	array( 'en' => 'bead breaking', 'ro' => 'dezlipirea talonului anvelopei', 'not' => array( 'spargerea perlei', 'ruperea benzii', 'desfacerea brățării' ) ),
	array( 'en' => 'bearers', 'ro' => 'role de sprijin', 'not' => array( 'rulmenți', 'purtători', 'suporturi de lagăre' ) ),
	array( 'en' => 'bearing center lines', 'ro' => 'axele lagărelor', 'not' => array( 'linii de centru ale rulmenților' ) ),
	array( 'en' => 'bearing life', 'ro' => 'durata de viață a rulmenților', 'not' => array( 'viața rulmentului', 'durata rulmentului' ) ),
	array( 'en' => 'blade', 'ro' => 'lamă', 'not' => array( 'paletă', 'cuțit de nivelare' ) ),
	array( 'en' => 'blank ECM', 'ro' => 'ECM neprogramat', 'not' => array( 'ECM gol', 'ECM alb' ) ),
	array( 'en' => 'blast furnace', 'ro' => 'furnal', 'not' => array( 'cuptor cu explozie', 'furnal cu vânt', 'cuptor de suflare' ) ),
	array( 'en' => 'blowers', 'ro' => 'suflante', 'not' => array( 'ventilatoare', 'sufleuri' ) ),
	array( 'en' => 'bore axis alignment', 'ro' => 'alinierea axei alezajului', 'not' => array( 'alinierea axei de găurire' ) ),
	array( 'en' => 'boreless compressor wheel', 'ro' => 'rotor de compresor fără alezaj', 'not' => array( 'roată de compresor fără gaură' ) ),
	array( 'en' => 'boring', 'ro' => 'alezare', 'not' => array( 'găurire', 'forare', 'plictiseală' ) ),
	array( 'en' => 'boring drill', 'ro' => 'instalație de foraj dirijat', 'not' => array( 'burghiu de alezaj', 'mașină de găurit orizontală' ) ),
	array( 'en' => 'branch', 'ro' => 'sucursală', 'not' => array( 'ramură', 'filială' ) ),
	array( 'en' => 'Bristol', 'ro' => 'Bristol', 'not' => array( 'Brystol', 'Bristolul' ) ),
	array( 'en' => 'built to last', 'ro' => 'construit pentru a dura', 'not' => array( 'construit să reziste ultimul', 'făcut să dureze ultimul' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'ro' => 'Burke E. Porter Machinery', 'not' => array( 'Burke E. Porter Mașini', 'Utilaje Burke E. Porter' ) ),
	array( 'en' => 'Burke Porter Group', 'ro' => 'Burke Porter Group', 'not' => array( 'Grupul Burke Porter' ) ),
	array( 'en' => 'burst proof protection', 'ro' => 'protecție la ruperea rotorului', 'not' => array( 'protecție la explozie', 'protecție antiexplozie', 'rezistență la spargere' ) ),
	array( 'en' => 'calibration target', 'ro' => 'panou-țintă de calibrare', 'not' => array( 'obiectiv de calibrare', 'ținta de etalonare' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'ro' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Calibrare ca serviciu™', 'Etalonare ca serviciu™' ) ),
	array( 'en' => 'capital equipment', 'ro' => 'bunuri de capital', 'not' => array( 'echipament capital', 'echipamente capitale' ) ),
	array( 'en' => 'cargo loading systems', 'ro' => 'sisteme de încărcare a mărfurilor', 'not' => array( 'sisteme de încărcare cargo' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'ro' => 'dinamometru de șasiu, cu 2 și 4 roți', 'not' => array( 'dinamometru de șasiu cu 2 și 4 axe', 'banc dinamometric de șasiu cu două și patru osii' ) ),
	array( 'en' => 'chip vacuum', 'ro' => 'aspirator de șpan', 'not' => array( 'vid de cip', 'aspirator de cipuri' ) ),
	array( 'en' => 'clay gun', 'ro' => 'mașină de astupat orificiul de evacuare', 'not' => array( 'pistol de argilă', 'mașină de modelat argilă' ) ),
	array( 'en' => 'CMT-TR Polimer', 'ro' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR din polimer', 'CMT-TR polimeric' ) ),
	array( 'en' => 'cold pilger mill', 'ro' => 'laminor pilger la rece', 'not' => array( 'moară pilger rece' ) ),
	array( 'en' => 'collet chuck', 'ro' => 'mandrină cu bucșă elastică', 'not' => array( 'mandrină cu collet', 'mandrină colet' ) ),
	array( 'en' => 'combine', 'ro' => 'combină', 'not' => array( 'mașină combinată' ) ),
	array( 'en' => 'commercial vehicle', 'ro' => 'vehicul comercial', 'not' => array( 'mașină comercială' ) ),
	array( 'en' => 'commissioning', 'ro' => 'punere în funcțiune', 'not' => array( 'comisionare', 'comisionarea' ) ),
	array( 'en' => 'Connect on LinkedIn', 'ro' => 'Conectați-vă pe LinkedIn', 'not' => array( 'Connect on LinkedIn', 'Legați-vă pe LinkedIn' ) ),
	array( 'en' => 'control', 'ro' => 'comandă', 'not' => array( 'comenzi', 'controale' ) ),
	array( 'en' => 'control module', 'ro' => 'modul de comandă', 'not' => array( 'modul de control', 'modul de comenzi' ) ),
	array( 'en' => 'controls', 'ro' => 'sisteme de comandă', 'not' => array( 'comenzi', 'controale', 'regulatoare' ) ),
	array( 'en' => 'Core / Plus / Elite', 'ro' => 'Core / Plus / Elite', 'not' => array( 'Bază / Plus / Elită', 'Nucleu / Plus / Elită' ) ),
	array( 'en' => 'Corporate Roles', 'ro' => 'Funcții administrative', 'not' => array( 'Roluri corporative', 'Roluri de corporație' ) ),
	array( 'en' => 'correction', 'ro' => 'corecția dezechilibrului', 'not' => array( 'corectare a neechilibrului' ) ),
	array( 'en' => 'crankshaft lathe', 'ro' => 'strung pentru arbori cotiți', 'not' => array( 'strung de arbore cotit' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'ro' => 'Crossroads Bank for Enterprises', 'not' => array( 'Banca Crossroads pentru Întreprinderi' ) ),
	array( 'en' => 'cushion testing', 'ro' => 'testarea amortizării', 'not' => array( 'testarea pernei', 'test de pernă' ) ),
	array( 'en' => 'custom fixturing', 'ro' => 'dispozitive de prindere personalizate', 'not' => array( 'fixare personalizată', 'fixturi personalizate' ) ),
	array( 'en' => 'customer journey', 'ro' => 'parcursul clientului', 'not' => array( 'călătoria clientului', 'drumul clientului' ) ),
	array( 'en' => 'Date:', 'ro' => 'Data:', 'not' => array( 'Datele:', 'Dată:' ) ),
	array( 'en' => 'deep hole drilling', 'ro' => 'găurire adâncă', 'not' => array( 'forare de găuri adânci', 'găurire de gaură adâncă' ) ),
	array( 'en' => 'defensible', 'ro' => 'justificabil', 'not' => array( 'defensabil', 'apărabil' ) ),
	array( 'en' => 'Deliverables', 'ro' => 'Livrabile', 'not' => array( 'Elemente livrabile', 'Produse de livrat', 'Rezultate livrabile' ) ),
	array( 'en' => 'deployment', 'ro' => 'implementare', 'not' => array( 'desfășurare', 'deplasare' ) ),
	array( 'en' => 'design', 'ro' => 'construcție', 'not' => array( 'proiect', 'designul' ) ),
	array( 'en' => 'dial indicator', 'ro' => 'ceas comparator', 'not' => array( 'indicator cu cadran', 'indicator de apel' ) ),
	array( 'en' => 'disability insurance', 'ro' => 'asigurare de invaliditate', 'not' => array( 'asigurare pentru dizabilități' ) ),
	array( 'en' => 'discrete industries', 'ro' => 'industrii de fabricație discretă', 'not' => array( 'industrii discrete' ) ),
	array( 'en' => 'draper header', 'ro' => 'header cu bandă transportoare', 'not' => array( 'capul de recoltat combine', 'cap de recoltat', 'header cu perdea' ) ),
	array( 'en' => 'drift', 'ro' => 'deriva cilindrului', 'not' => array( 'alunecare', 'plutire' ) ),
	array( 'en' => 'drivability', 'ro' => 'agrement de conducere', 'not' => array( 'conducibilitate', 'șofabilitate' ) ),
	array( 'en' => 'dual mass flywheel', 'ro' => 'volant cu masă dublă', 'not' => array( 'ambreiaj bimasă', 'placă flexibilă' ) ),
	array( 'en' => 'dynamometer', 'ro' => 'dinamometru', 'not' => array( 'dinamometru de forță' ) ),
	array( 'en' => 'eddy current technology', 'ro' => 'tehnologia curenților turbionari', 'not' => array( 'tehnologia curentului actual', 'tehnologie de curent curent', 'curenți Eddy' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'ro' => 'texturare prin descărcare electrică (EDT)', 'not' => array( 'descărcare electrică', 'eroziune electrică', 'electroeroziune' ) ),
	array( 'en' => 'Email Disclosure', 'ro' => 'Mențiuni privind e-mailul', 'not' => array( 'Divulgarea e-mailului', 'Dezvăluire prin e-mail' ) ),
	array( 'en' => 'EMC darkroom', 'ro' => 'cameră anecoică CEM', 'not' => array( 'camera obscură EMC', 'cameră întunecată CEM' ) ),
	array( 'en' => 'end of line testing', 'ro' => 'testare la capăt de linie', 'not' => array( 'testare la finalul liniei', 'testare de sfârșit de linie' ) ),
	array( 'en' => 'energy recuperation', 'ro' => 'recuperare de energie', 'not' => array( 'recuperare energetică pasivă' ) ),
	array( 'en' => 'engine software loaders', 'ro' => 'sisteme de încărcare a software-ului motorului', 'not' => array( 'încărcătoare de motoare', 'programe de încărcare a motoarelor' ) ),
	array( 'en' => 'eRotor', 'ro' => 'eRotor', 'not' => array( 'e-Rotor', 'rotor electronic' ) ),
	array( 'en' => 'events & conferences', 'ro' => 'evenimente și conferințe', 'not' => array(  ) ),
	array( 'en' => 'excavator', 'ro' => 'excavator', 'not' => array( 'copiator', 'săpător' ) ),
	array( 'en' => 'exhaust extraction', 'ro' => 'evacuarea gazelor de eșapament', 'not' => array( 'extracția eșapamentului', 'extragere de evacuare' ) ),
	array( 'en' => 'factory floor', 'ro' => 'hala de producție', 'not' => array( 'podeaua fabricii', 'etajul fabricii' ) ),
	array( 'en' => 'failure rates', 'ro' => 'rate de neconformitate', 'not' => array( 'rate de eșec', 'rate de defectare' ) ),
	array( 'en' => 'features', 'ro' => 'funcționalități', 'not' => array( 'trăsături', 'facilități' ) ),
	array( 'en' => 'Featuring: <Brand>', 'ro' => 'Marca <Brand>', 'not' => array( 'Prezentând <Brand>', 'Cu <Brand>' ) ),
	array( 'en' => 'field agents', 'ro' => 'tehnicieni de teren', 'not' => array( 'agenți de câmp', 'reprezentanți de teren' ) ),
	array( 'en' => 'field balancing', 'ro' => 'echilibrare la fața locului', 'not' => array( 'echilibrare pe teren', 'echilibrare de câmp' ) ),
	array( 'en' => 'filler', 'ro' => 'instalație de umplere', 'not' => array( 'umplutură', 'plombă' ) ),
	array( 'en' => 'filler gun', 'ro' => 'pistol de umplere', 'not' => array( 'pistol de umplutură' ) ),
	array( 'en' => 'final discharge', 'ro' => 'golire finală', 'not' => array( 'descărcare finală', 'externare finală' ) ),
	array( 'en' => 'fine leak', 'ro' => 'scurgere fină', 'not' => array( 'pierdere fină', 'fisură fină' ) ),
	array( 'en' => 'flexplate', 'ro' => 'placă flexibilă de antrenare', 'not' => array( 'placă de ambreiaj' ) ),
	array( 'en' => 'fluid power', 'ro' => 'acționări hidraulice și pneumatice', 'not' => array( 'putere fluidă', 'energie fluidă' ) ),
	array( 'en' => 'flywheel', 'ro' => 'volant', 'not' => array( 'roată de inerție', 'roată zburătoare' ) ),
	array( 'en' => 'footprint', 'ro' => 'amprenta la sol', 'not' => array( 'urmă de picior', 'suprafață de amprentă' ) ),
	array( 'en' => 'For Immediate Release', 'ro' => 'Pentru difuzare imediată', 'not' => array( 'Pentru eliberare imediată', 'Pentru lansare imediată' ) ),
	array( 'en' => 'forged rolls', 'ro' => 'cilindri forjați', 'not' => array( 'role forjate', 'rulouri forjate' ) ),
	array( 'en' => 'front strut', 'ro' => 'ansamblu amortizor față', 'not' => array( 'montant frontal', 'stâlp frontal', 'bară față' ) ),
	array( 'en' => 'gantry', 'ro' => 'portal', 'not' => array( 'pod rulant' ) ),
	array( 'en' => 'GDPR', 'ro' => 'RGPD', 'not' => array( 'Regulamentul GDPR' ) ),
	array( 'en' => 'gear shift calibration', 'ro' => 'calibrarea schimbătorului de viteze', 'not' => array( 'etalonarea schimbării treptelor' ) ),
	array( 'en' => 'grinding wheel', 'ro' => 'disc abraziv', 'not' => array( 'roată de rectificat', 'roată abrazivă', 'piatră de moară' ) ),
	array( 'en' => 'gross leak test', 'ro' => 'test de scurgeri grosiere', 'not' => array( 'test de scurgere brută', 'test brut de etanșeitate' ) ),
	array( 'en' => 'gundrill', 'ro' => 'burghiu pentru găurire adâncă', 'not' => array( 'burghiu de pistol', 'pistol de găurit' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'ro' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht & Co. SRL', 'H. Kleinknecht și Co. GmbH' ) ),
	array( 'en' => 'half case', 'ro' => 'semicarcasă', 'not' => array( 'jumătate de caz', 'carcasă pe jumătate' ) ),
	array( 'en' => 'hay mower', 'ro' => 'cositoare de fân', 'not' => array( 'mașină de cosit fânul' ) ),
	array( 'en' => 'hazardous area', 'ro' => 'zonă cu pericol de explozie', 'not' => array( 'zonă periculoasă', 'arie riscantă' ) ),
	array( 'en' => 'hazardous areas', 'ro' => 'zone cu pericol de explozie', 'not' => array( 'zone periculoase', 'arii riscante' ) ),
	array( 'en' => 'health checks', 'ro' => 'verificări ale stării tehnice', 'not' => array( 'controale de sănătate', 'verificări de sănătate' ) ),
	array( 'en' => 'high production / high-volume production', 'ro' => 'producție de serie mare', 'not' => array( 'producție înaltă', 'producție de volum mare' ) ),
	array( 'en' => 'high-mix, low-volume', 'ro' => 'gamă variată, volume mici', 'not' => array( 'mix ridicat, volum scăzut' ) ),
	array( 'en' => 'high-performance teams', 'ro' => 'echipe de înaltă performanță', 'not' => array( 'echipe cu spectacol înalt' ) ),
	array( 'en' => 'higher-level control system', 'ro' => 'sistem de comandă de nivel superior', 'not' => array( 'sistem de control mai înalt', 'sistem de comandă master' ) ),
	array( 'en' => 'HMU/FMU', 'ro' => 'unități hidromecanice și de dozare a combustibilului', 'not' => array( 'dispozitive hidraulice/pneumatice', 'unități hidraulice/pneumatice' ) ),
	array( 'en' => 'idle duration', 'ro' => 'durata mersului în gol', 'not' => array( 'durata de inactivitate', 'timp de repaus' ) ),
	array( 'en' => 'implements', 'ro' => 'utilaje atașate', 'not' => array( 'implemente', 'implementele', 'unelte de implementare' ) ),
	array( 'en' => 'Imprint', 'ro' => 'Mențiuni legale', 'not' => array( 'Amprentă', 'Imprimare', 'Tipar' ) ),
	array( 'en' => 'in a single clamping', 'ro' => 'într-o singură prindere', 'not' => array( 'într-o singură clemă', 'într-un singur clamp' ) ),
	array( 'en' => 'infeed', 'ro' => 'avans de pătrundere', 'not' => array( 'alimentare de intrare', 'intrare de material' ) ),
	array( 'en' => 'infinitely variable', 'ro' => 'reglabil continuu', 'not' => array( 'infinit variabil', 'variabil la infinit' ) ),
	array( 'en' => 'inline crankshaft', 'ro' => 'arbore cotit în linie', 'not' => array( 'arbore cotit în patru timpi' ) ),
	array( 'en' => 'inline dyno', 'ro' => 'dinamometru integrat în linie', 'not' => array( 'dinamometru inline' ) ),
	array( 'en' => 'insights', 'ro' => 'perspective', 'not' => array( 'viziuni', 'intuiții', 'pătrunderi' ) ),
	array( 'en' => 'instrument cluster', 'ro' => 'bloc de instrumente de bord', 'not' => array( 'grup de instrumente', 'ciorchine de instrumente' ) ),
	array( 'en' => 'keg finger holes', 'ro' => 'orificiile de prindere ale butoiului', 'not' => array( 'găuri pentru degete', 'orificii de deget' ) ),
	array( 'en' => 'kinetostatics', 'ro' => 'cinetostatică', 'not' => array( 'kinetostatică' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'ro' => 'KvK (Kamer van Koophandel)', 'not' => array( 'Camera de Comerț KvK' ) ),
	array( 'en' => 'Labour & Travel', 'ro' => 'Manoperă și deplasare', 'not' => array( 'Muncă și călătorie', 'Forță de muncă și transport' ) ),
	array( 'en' => 'landed cost model', 'ro' => 'model al costului total la destinație', 'not' => array( 'model de cost aterizat', 'modelul costului de debarcare' ) ),
	array( 'en' => 'landing gear systems', 'ro' => 'sisteme de tren de aterizare', 'not' => array( 'sisteme de aterizare', 'sisteme de echipament de aterizare' ) ),
	array( 'en' => 'leak detection', 'ro' => 'detecția scurgerilor', 'not' => array( 'detectarea pierderilor', 'depistarea fisurilor' ) ),
	array( 'en' => 'learning management system (LMS)', 'ro' => 'sistem de management al învățării (LMS)', 'not' => array( 'sistem de gestionare a lecțiilor' ) ),
	array( 'en' => 'like-minded companies', 'ro' => 'companii care ne împărtășesc valorile', 'not' => array( 'companii cu aceeași minte', 'firme asemănător gânditoare' ) ),
	array( 'en' => 'load capacity', 'ro' => 'capacitate de încărcare', 'not' => array( 'sarcină capabilă' ) ),
	array( 'en' => 'LPM', 'ro' => 'l/min', 'not' => array() ),
	array( 'en' => 'lube & scavenge pumps', 'ro' => 'pompe de ungere și de recuperare a uleiului', 'not' => array( 'pompe de lubrifiere și aerisire', 'pompe de ungere și evacuare a aerului' ) ),
	array( 'en' => 'lubrication', 'ro' => 'ungere', 'not' => array( 'lubrifiere cu unsoare' ) ),
	array( 'en' => 'machine tools', 'ro' => 'mașini-unelte', 'not' => array( 'mașini tehnologice', 'unelte de mașină' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'ro' => 'Directiva Mașini 2006/42/CE', 'not' => array( 'Directiva 2006/42/EC', 'Directiva privind mașinile 2006/42/EC' ) ),
	array( 'en' => 'machining cell', 'ro' => 'celulă de prelucrare', 'not' => array( 'celulă de mașinărie' ) ),
	array( 'en' => 'machinist', 'ro' => 'operator la mașini-unelte', 'not' => array( 'mașinist', 'mecanic de mașină' ) ),
	array( 'en' => 'maintenance contracts', 'ro' => 'contracte de mentenanță', 'not' => array( 'contracte de întreținere' ) ),
	array( 'en' => 'marine', 'ro' => 'sectorul naval', 'not' => array( 'sectorul marin', 'marin' ) ),
	array( 'en' => 'maximum rotor diameter', 'ro' => 'diametrul maxim al rotorului', 'not' => array( 'diametrul maxim de rotori' ) ),
	array( 'en' => 'mental health care', 'ro' => 'asistență pentru sănătatea mentală', 'not' => array( 'îngrijire medicală la distanță', 'asistență psihică' ) ),
	array( 'en' => 'mill roll', 'ro' => 'cilindru de laminor', 'not' => array( 'rolă de laminor', 'rulou de moară', 'role de laminor' ) ),
	array( 'en' => 'misalignment', 'ro' => 'dezaliniere', 'not' => array( 'aliniere greșită' ) ),
	array( 'en' => 'motor grader', 'ro' => 'autogreder', 'not' => array( 'nivelator cu motor', 'greder cu motor', 'copiator de sol' ) ),
	array( 'en' => 'motorized clamping', 'ro' => 'prindere motorizată', 'not' => array( 'clemare motorizată' ) ),
	array( 'en' => 'MRO', 'ro' => 'MRO', 'not' => array( 'întreținere, reparații și operațiuni' ) ),
	array( 'en' => 'mudding system', 'ro' => 'sistem de fluid de foraj', 'not' => array( 'sistem de nămol', 'instalație de mâl' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'ro' => 'naamloze vennootschap (NV)', 'not' => array( 'societate anonimă (NV)', 'societate pe acțiuni (NV)' ) ),
	array( 'en' => 'Name:', 'ro' => 'Nume și prenume:', 'not' => array( 'Denumire:', 'Numire:' ) ),
	array( 'en' => 'Netherlands', 'ro' => 'Țările de Jos', 'not' => array( 'Olanda', 'Netherlands' ) ),
	array( 'en' => 'non-rotating balancing machine', 'ro' => 'mașină de echilibrat fără rotație', 'not' => array( 'mașină de echilibrat fără rotor', 'mașină de echilibrat nerotativă', 'echilibrator static' ) ),
	array( 'en' => 'obsolescence management', 'ro' => 'gestionarea uzurii morale', 'not' => array( 'managementul obsolescenței', 'gestionarea obsolescenței' ) ),
	array( 'en' => 'off-highway', 'ro' => 'utilaje off-highway', 'not' => array( 'în afara autostrăzii', 'extra-rutier' ) ),
	array( 'en' => 'oil drain', 'ro' => 'orificiul de golire a uleiului', 'not' => array( 'orificiu de aerisire', 'canal de aer' ) ),
	array( 'en' => 'operations', 'ro' => 'activitate', 'not' => array( 'operații', 'intervenții chirurgicale' ) ),
	array( 'en' => 'opportunities', 'ro' => 'oportunități', 'not' => array( 'oportuniști', 'ocazii' ) ),
	array( 'en' => 'patented', 'ro' => 'brevetat', 'not' => array( 'patentat' ) ),
	array( 'en' => 'pedestals', 'ro' => 'suporți de reazem', 'not' => array( 'piedestaluri', 'postamente' ) ),
	array( 'en' => 'peers', 'ro' => 'colegi de profesie', 'not' => array( 'egali', 'semeni' ) ),
	array( 'en' => 'performance', 'ro' => 'performanță', 'not' => array( 'spectacol', 'reprezentație' ) ),
	array( 'en' => 'personal information / personal data', 'ro' => 'date cu caracter personal', 'not' => array( 'informații personale', 'date personale' ) ),
	array( 'en' => 'pinches & bruises', 'ro' => 'striviri și urme de lovire', 'not' => array( 'ciupituri și vânătăi', 'pișcături și contuzii' ) ),
	array( 'en' => 'pinion gear', 'ro' => 'pinion', 'not' => array( 'fus dințat', 'angrenaj pinion' ) ),
	array( 'en' => 'pins', 'ro' => 'bolțuri', 'not' => array( 'pini de fixare' ) ),
	array( 'en' => 'power drive units', 'ro' => 'unități de acționare', 'not' => array( 'unități de conducere a puterii', 'blocuri de putere' ) ),
	array( 'en' => 'Powered by', 'ro' => 'Susținut de', 'not' => array( 'Alimentat de', 'Propulsat de' ) ),
	array( 'en' => 'President', 'ro' => 'președinte', 'not' => array( 'prezident', 'prezidentul' ) ),
	array( 'en' => 'pressurization', 'ro' => 'presurizare', 'not' => array( 'punere la presiune' ) ),
	array( 'en' => 'probe alignment', 'ro' => 'alinierea palpatorului', 'not' => array( 'alinierea sondei', 'alinierea probei' ) ),
	array( 'en' => 'process recipe', 'ro' => 'rețetă de proces', 'not' => array( 'prescripție de proces' ) ),
	array( 'en' => 'propulsion & powertrain', 'ro' => 'propulsie și grup motopropulsor', 'not' => array( 'propulsie și tren de putere', 'propulsie și transmisie' ) ),
	array( 'en' => 'PTO', 'ro' => 'priză de putere', 'not' => array( 'arbore de preluare a puterii', 'priză de forță' ) ),
	array( 'en' => 'pulley', 'ro' => 'fulie', 'not' => array( 'scripete', 'roată de scripete' ) ),
	array( 'en' => 'punching', 'ro' => 'poansonare', 'not' => array( 'perforare', 'lovire' ) ),
	array( 'en' => 'push and pull', 'ro' => 'împingere și tracțiune', 'not' => array( 'împinge și trage' ) ),
	array( 'en' => 'reconditioning', 'ro' => 'recondiționare', 'not' => array( 'renovare', 'refacere' ) ),
	array( 'en' => 'refrigerant', 'ro' => 'agent frigorific', 'not' => array( 'refrigerant', 'lichid de răcire', 'agent de răcire' ) ),
	array( 'en' => 'refrigerant charging', 'ro' => 'încărcare cu agent frigorific', 'not' => array( 'încărcarea refrigerantului', 'alimentare cu lichid de răcire' ) ),
	array( 'en' => 'refrigeration', 'ro' => 'refrigerare', 'not' => array( 'răcire', 'climă' ) ),
	array( 'en' => 'Register', 'ro' => 'Registrul', 'not' => array( 'Înregistrați-vă', 'Înscriere' ) ),
	array( 'en' => 'Registered office', 'ro' => 'Sediul social', 'not' => array( 'Birou înregistrat', 'Oficiu înregistrat' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'ro' => 'reconstructori și reparatori de agregate', 'not' => array( 're-fabricanți', 'remanufacturieri' ) ),
	array( 'en' => 'remarketers', 'ro' => 'revânzători', 'not' => array( 'remarketeri', 're-comercianți' ) ),
	array( 'en' => 'reportable', 'ro' => 'raportabil', 'not' => array( 'reportabil' ) ),
	array( 'en' => 'represent', 'ro' => 'a reproduce', 'not' => array( 'a reprezenta scenic' ) ),
	array( 'en' => 'residual unbalance', 'ro' => 'dezechilibru rezidual', 'not' => array( 'neechilibru rezidual' ) ),
	array( 'en' => 'responsive', 'ro' => 'prompt', 'not' => array( 'responsiv', 'reactiv' ) ),
	array( 'en' => 'restbus simulation', 'ro' => 'simulare restbus', 'not' => array( 'simulare de autobuz', 'simularea magistralei de odihnă' ) ),
	array( 'en' => 'retaining rollers', 'ro' => 'role de reținere', 'not' => array( 'rulouri de menținere', 'role retentive' ) ),
	array( 'en' => 'right-shoring', 'ro' => 'right-shoring', 'not' => array( 'relocalizare corectă', 'aducere în țară' ) ),
	array( 'en' => 'roll inspection', 'ro' => 'inspecția cilindrilor', 'not' => array( 'inspecția rolelor', 'controlul rulourilor', 'inspecție role' ) ),
	array( 'en' => 'Roll Shop Technologies', 'ro' => 'Tehnologii pentru ateliere de cilindri', 'not' => array( 'Tehnologii pentru magazine de role', 'Tehnologii de atelier de rulouri' ) ),
	array( 'en' => 'roller', 'ro' => 'rolă', 'not' => array( 'rulou', 'tambur' ) ),
	array( 'en' => 'roller brake tester', 'ro' => 'stand de frânare cu role', 'not' => array( 'tester de frâne cu rulouri', 'banc de frâne cu cilindri' ) ),
	array( 'en' => 'rolling torque', 'ro' => 'moment de rulare', 'not' => array( 'torsiune de rulare' ) ),
	array( 'en' => 'rotary diamond dressing', 'ro' => 'ascuțire rotativă cu diamant', 'not' => array( 'dresare cu diamant rotativ', 'îmbrăcare rotativă cu diamant' ) ),
	array( 'en' => 'rotor wing aircraft', 'ro' => 'aeronave cu aripi rotative', 'not' => array( 'avioane cu elice', 'aeronave cu elice' ) ),
	array( 'en' => 'sealed assembly', 'ro' => 'ansamblu etanș', 'not' => array( 'asamblare sigilată', 'ansamblu sigilat' ) ),
	array( 'en' => 'seamless link', 'ro' => 'legătură fără întreruperi', 'not' => array( 'link fără cusături', 'legătură fără sudură' ) ),
	array( 'en' => 'service professional', 'ro' => 'specialist în service', 'not' => array( 'profesionist de serviciu', 'profesionist în servicii' ) ),
	array( 'en' => 'setup cycles', 'ro' => 'cicluri de reglare', 'not' => array( 'cicluri de setup', 'cicluri de configurare' ) ),
	array( 'en' => 'single bay', 'ro' => 'post unic de lucru', 'not' => array( 'golf unic', 'singur compartiment' ) ),
	array( 'en' => 'single cylinder crankshaft', 'ro' => 'arbore cotit monocilindric', 'not' => array( 'arbore cotit cu o singură pistă' ) ),
	array( 'en' => 'single station / multi station', 'ro' => 'cu o stație / cu mai multe stații', 'not' => array( 'cu o cameră / cu mai multe camere', 'monopost / multipost' ) ),
	array( 'en' => 'site visit', 'ro' => 'vizită la fața locului', 'not' => array( 'vizită pe site', 'vizită de amplasament' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'ro' => 'sondă de detecție', 'not' => array( 'clește de miros', 'pensetă de adulmecare' ) ),
	array( 'en' => 'snubber', 'ro' => 'amortizor de șoc', 'not' => array( 'strangulator', 'limitator de curse' ) ),
	array( 'en' => 'soak time', 'ro' => 'timp de menținere', 'not' => array( 'timp de înmuiere', 'timp de imersie' ) ),
	array( 'en' => 'spalls', 'ro' => 'exfolieri', 'not' => array( 'cojiri', 'vânătăi' ) ),
	array( 'en' => 'special test facilities', 'ro' => 'instalații speciale de testare', 'not' => array( 'facilități speciale de testare' ) ),
	array( 'en' => 'spin testing machine', 'ro' => 'mașină de testare prin rotație', 'not' => array( 'testator de rotație', 'mașină de testare de rotație', 'mașină de învârtire' ) ),
	array( 'en' => 'sprayers', 'ro' => 'mașini de stropit', 'not' => array( 'pulverizatoare', 'duze de stropit', 'stropitori' ) ),
	array( 'en' => 'squeak & rattle testing', 'ro' => 'testarea scârțâiturilor și a zgomotelor parazite', 'not' => array( 'testare de scârțâit și zdrăngănit' ) ),
	array( 'en' => 'stand-alone machine', 'ro' => 'mașină independentă', 'not' => array( 'mașină stand-alone', 'mașină de sine stătătoare' ) ),
	array( 'en' => 'Standardization at scale', 'ro' => 'Standardizare la scară', 'not' => array( 'Standardizare la cântar' ) ),
	array( 'en' => 'strip', 'ro' => 'bandă', 'not' => array( 'fâșie', 'panglică' ) ),
	array( 'en' => 'Strip Lines', 'ro' => 'Linii pentru bandă', 'not' => array( 'Benzi de decapare', 'Linii de fâșii' ) ),
	array( 'en' => 'superabrasives', 'ro' => 'superabrazivi', 'not' => array( 'super-abrazive' ) ),
	array( 'en' => 'surface separations', 'ro' => 'desprinderi de suprafață', 'not' => array( 'separări de suprafață' ) ),
	array( 'en' => 'tap hole', 'ro' => 'orificiu de evacuare', 'not' => array( 'gaură de robinet', 'orificiu de derivație' ) ),
	array( 'en' => 'tapered roller bearing', 'ro' => 'rulment cu role conice', 'not' => array( 'rulment cu rulouri conice', 'lagăr conic' ) ),
	array( 'en' => 'tariffs', 'ro' => 'tarife vamale', 'not' => array( 'taxe de listă' ) ),
	array( 'en' => 'tension', 'ro' => 'tensionare', 'not' => array( 'tensiune electrică', 'stres' ) ),
	array( 'en' => 'third member', 'ro' => 'grup diferențial central', 'not' => array( 'al treilea membru', 'membrul al treilea' ) ),
	array( 'en' => 'tin plating', 'ro' => 'cositorire', 'not' => array( 'zincare', 'galvanizare cu zinc', 'placare cu zinc' ) ),
	array( 'en' => 'TIR / radial run-out', 'ro' => 'bătaie radială totală', 'not' => array( 'alergare radială', 'cursă radială' ) ),
	array( 'en' => 'tire inflator', 'ro' => 'instalație de umflare a anvelopelor', 'not' => array( 'inflator de anvelope', 'pompă de cauciucuri' ) ),
	array( 'en' => 'torque vectoring', 'ro' => 'vectorizarea cuplului', 'not' => array( 'vectorizare de torsiune', 'direcționarea momentului' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'ro' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'SOLUȚII TOTALE DE COMERCIALIZARE' ) ),
	array( 'en' => 'traceable tests', 'ro' => 'teste trasabile', 'not' => array( 'teste urmăribile', 'testări de urmărire' ) ),
	array( 'en' => 'tracer gas', 'ro' => 'gaz trasor', 'not' => array( 'gaze marcatoare', 'gaz de urmărire', 'gaz marcator' ) ),
	array( 'en' => 'traction battery', 'ro' => 'baterie de tracțiune', 'not' => array( 'baterie de pornire', 'baterie uscată' ) ),
	array( 'en' => 'transmission / gearbox', 'ro' => 'cutie de viteze', 'not' => array( 'transmisiune', 'emisie' ) ),
	array( 'en' => 'turbo calibration', 'ro' => 'calibrarea turbosuflantei', 'not' => array( 'etalonare turbo' ) ),
	array( 'en' => 'turbocharger flow bench', 'ro' => 'stand de testare a debitului pentru turbosuflante', 'not' => array( 'bancă de flux', 'banc de flux turbocompressor', 'stand de flux' ) ),
	array( 'en' => 'turbocharger frame size', 'ro' => 'gabaritul turbosuflantei', 'not' => array( 'dimensiunea cadrului turbo' ) ),
	array( 'en' => 'turnkey', 'ro' => 'la cheie', 'not' => array( 'cheie în mână', 'turnkey' ) ),
	array( 'en' => 'turret-style wheel head', 'ro' => 'cap portsculă tip revolver', 'not' => array( 'cap de roată tip turelă' ) ),
	array( 'en' => 'two-wheel drive', 'ro' => 'tracțiune pe două roți', 'not' => array( 'tracțiune pe doi roți', 'antrenare cu două roate' ) ),
	array( 'en' => 'ultra-stable design', 'ro' => 'construcție ultrastabilă', 'not' => array( 'design ultra-stabil' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'ro' => 'instalație de curățare cu ultrasunete a duzelor', 'not' => array( 'curățător ultrasonic de duze' ) ),
	array( 'en' => 'unbalance', 'ro' => 'dezechilibru', 'not' => array( 'neechilibru', 'nebalansare', 'lipsă de echilibru' ) ),
	array( 'en' => 'unbeatable deals', 'ro' => 'oferte de neegalat', 'not' => array( 'afaceri nebătute', 'oferte neînvinse' ) ),
	array( 'en' => 'Universal Balancing', 'ro' => 'Universal Balancing', 'not' => array( 'Echilibrare universală', 'Echilibrarea universală' ) ),
	array( 'en' => 'uptime across systems', 'ro' => 'disponibilitatea sistemelor', 'not' => array( 'timp de funcționare între sisteme' ) ),
	array( 'en' => 'v-block support', 'ro' => 'suport în V', 'not' => array( 'bloc în V', 'sprijin de tip V' ) ),
	array( 'en' => 'vacuum evacuation', 'ro' => 'vidare', 'not' => array( 'evacuarea vidului', 'evacuare în vid' ) ),
	array( 'en' => 'validate performance', 'ro' => 'validarea performanței', 'not' => array( 'validarea spectacolului' ) ),
	array( 'en' => 'valve body unit', 'ro' => 'corp de distribuție hidraulică', 'not' => array( 'unitate de corp de supapă', 'bloc de valve' ) ),
	array( 'en' => 'vibration', 'ro' => 'vibrații', 'not' => array( 'trepidație' ) ),
	array( 'en' => 'volume flexibility', 'ro' => 'flexibilitate în volume', 'not' => array( 'flexibilitate de volum sonor' ) ),
	array( 'en' => 'walking beam system', 'ro' => 'sistem cu grinzi pășitoare', 'not' => array( 'sistem de grinzi mobile', 'sistem cu bară de mers' ) ),
	array( 'en' => 'warranty coverage', 'ro' => 'acoperire în garanție', 'not' => array( 'asigurare de garanție', 'poliță de garanție' ) ),
	array( 'en' => 'water meter', 'ro' => 'contor de apă', 'not' => array( 'măsurător de apă' ) ),
	array( 'en' => 'water-cooled', 'ro' => 'răcit cu apă', 'not' => array( 'care răcește apa', 'de răcire cu apă' ) ),
	array( 'en' => 'WCAG four principles', 'ro' => 'cele patru principii WCAG', 'not' => array( 'patru principii ale WCAG-ului' ) ),
	array( 'en' => 'wheel aligner', 'ro' => 'stand de aliniere a roților', 'not' => array( 'aliniator de roți', 'mașină de aliniat roți' ) ),
	array( 'en' => 'wheel alignment', 'ro' => 'alinierea roților', 'not' => array( 'aliniament de roți', 'aliniere de roate' ) ),
	array( 'en' => 'WHEREAS', 'ro' => 'ÎNTRUCÂT', 'not' => array( 'ÎN TIMP CE', 'PE DE ALTĂ PARTE' ) ),
	array( 'en' => 'whistle', 'ro' => 'șuierat', 'not' => array( 'fluier', 'fluierat' ) ),
	array( 'en' => 'Work Product', 'ro' => 'Rezultatul Lucrărilor', 'not' => array( 'Produsul Muncii', 'Produs de lucru' ) ),
	array( 'en' => 'XL Machine', 'ro' => 'XL Machine', 'not' => array( 'Mașina XL', 'Utilajul XL' ) ),
	array( 'en' => 'Marketplace', 'ro' => 'Magazin de piese de schimb', 'not' => array( 'Piață', 'Piața de desfacere' ) ),
	array( 'en' => 'Medical', 'ro' => 'Medicină', 'not' => array( 'Medicală', 'Medicale' ) ),
	array( 'en' => 'Non-Rotate Systems', 'ro' => 'Sisteme fără rotație', 'not' => array( 'Sisteme nerotative', 'Sisteme de non-rotație' ) ),
	array( 'en' => 'Spin Testing', 'ro' => 'Testare prin rotație', 'not' => array( 'Testare de rotație', 'Testare în rotație', 'Testare la învârtire' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'ro' => 'Cilindri de transportoare și cilindri de hârtie', 'not' => array( 'Role de transport și hârtie', 'Rulouri de transportor și de hârtie' ) ),
	array( 'en' => 'stem stickiness', 'ro' => 'griparea tijei', 'not' => array( 'vâscozitatea tijei', 'lipiciozitatea tijei' ) ),
	array( 'en' => 'hydraulic pilot', 'ro' => 'comandă hidraulică pilot', 'not' => array( 'pilot hidraulic' ) ),
	array( 'en' => 'load sense signal', 'ro' => 'semnal load-sense', 'not' => array( 'semnal de senzor de sarcină', 'semnal de detectare a încărcăturii' ) ),
	array( 'en' => 'debonding', 'ro' => 'dezlipire', 'not' => array( 'delaminare', 'desprindere de lipici' ) ),
	array( 'en' => 'movable cradle', 'ro' => 'leagăn mobil', 'not' => array( 'pat mobil', 'bază mobilă' ) ),
	array( 'en' => 'thrust force / pullback force', 'ro' => 'forță de împingere / forță de tracțiune', 'not' => array( 'forță axială', 'forță de retragere' ) ),
	array( 'en' => 'ring gears', 'ro' => 'coroane dințate', 'not' => array( 'roți dințate inelare', 'angrenaje inelare' ) ),
	array( 'en' => 'blade timing', 'ro' => 'durata ciclului lamei', 'not' => array( 'sincronizarea lamei', 'timpul de lucru al lamei' ) ),
	array( 'en' => 'heavy-duty', 'ro' => 'de mare rezistență', 'not' => array( 'de datorie grea', 'sarcină grea' ) ),
	array( 'en' => 'life sciences', 'ro' => 'științe ale vieții', 'not' => array( 'științe naturale', 'științe biologice' ) ),
	array( 'en' => 'First Alert Monitoring System', 'ro' => 'sistem de monitorizare First Alert', 'not' => array( 'sistem de monitorizare cu prima alertă' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'ro' => 'Turbo Test Duo Expert', 'not' => array( 'Expert TURBO TEST DUO', 'Turbo Test Duo Expertul' ) ),
	array( 'en' => 'Board Member', 'ro' => 'membru al consiliului de administrație', 'not' => array( 'membru al conducerii', 'membru de bord' ) ),
	array( 'en' => 'Principal', 'ro' => 'Principal', 'not' => array( 'Director principal', 'Șef de birou' ) ),
	array( 'en' => 'Leadership', 'ro' => 'Echipa de conducere', 'not' => array( 'Conducerea superioară', 'Leadership' ) ),
	array( 'en' => 'Introducing', 'ro' => 'Vă prezentăm', 'not' => array( 'Introducere', 'Noutate', 'Introducând' ) ),
	array( 'en' => 'flammable gases', 'ro' => 'gaze inflamabile', 'not' => array( 'gaze ușor inflamabile', 'gaze combustibile' ) ),
	array( 'en' => 'Electronic hung mass', 'ro' => 'compensare electronică a masei suspendate', 'not' => array( 'masă suspendată electronică', 'masă electronică agățată' ) ),
	array( 'en' => 'Detection Focus', 'ro' => 'Defecte detectate', 'not' => array( 'Focalizare de detecție', 'Domeniu de detecție' ) ),
	array( 'en' => 'weight capacity', 'ro' => 'sarcină maximă', 'not' => array( 'capacitate de greutate' ) ),
	array( 'en' => 'vacuum', 'ro' => 'vid', 'not' => array( 'subpresiune', 'depresiune', 'vacuum' ) ),
	array( 'en' => 'vacuum rise test', 'ro' => 'test de creștere a vidului', 'not' => array( 'test de creștere a subpresiunii', 'test de ridicare a vidului' ) ),
	array( 'en' => 'fixed stations', 'ro' => 'posturi fixe', 'not' => array( 'stații fixate' ) ),
	array( 'en' => 'mobile carousels', 'ro' => 'caruseluri mobile', 'not' => array( 'caruseluri de mobilă' ) ),
	array( 'en' => 'cooling units', 'ro' => 'unități de răcire', 'not' => array( 'agregate de climă' ) ),
	array( 'en' => 'e-axle', 'ro' => 'e-axle', 'not' => array( 'axă electronică', 'osie electronică' ) ),
	array( 'en' => 'keg', 'ro' => 'butoi', 'not' => array( 'baril', 'doză' ) ),
	array( 'en' => 'horizontal boring machine', 'ro' => 'mașină de alezat orizontală', 'not' => array( 'mașină de găurit orizontală', 'mașină orizontală de forat' ) ),
	array( 'en' => 'test benches / test stands', 'ro' => 'standuri de testare', 'not' => array( 'bănci de testare', 'bancuri de probă' ) ),
	array( 'en' => 'testing', 'ro' => 'testare', 'not' => array( 'probare' ) ),
	array( 'en' => 'Aerospace & industrials', 'ro' => 'Aerospațial și industrial', 'not' => array( 'Aeronautic și industrial', 'Sector aerospațial și industrie' ) ),
	array( 'en' => 'Exhibit', 'ro' => 'Anexa', 'not' => array( 'Expoziție', 'Exponat' ) ),
	array( 'en' => 'Section', 'ro' => 'Secțiunea', 'not' => array( 'Sectiunea' ) ),
	array( 'en' => 'RECITALS', 'ro' => 'PREAMBUL', 'not' => array( 'RECITALURI', 'RECITĂRI' ) ),
	array( 'en' => 'Products', 'ro' => 'Produse', 'not' => array(  ) ),
	array( 'en' => 'Ascential Indemnity', 'ro' => 'Despăgubirea acordată de Ascential', 'not' => array( 'Indemnizația Ascential', 'Indemnitatea Ascential' ) ),
	array( 'en' => 'England', 'ro' => 'Anglia', 'not' => array( 'England' ) ),
	array( 'en' => 'West Flanders', 'ro' => 'Flandra Occidentală', 'not' => array( 'West Flanders', 'Flandra de Vest' ) ),
	array( 'en' => 'Poland', 'ro' => 'Polonia', 'not' => array( 'Poland' ) ),
	array( 'en' => 'Play', 'ro' => 'Redați', 'not' => array( 'Joacă', 'Play' ) ),
	array( 'en' => 'Listen to this article', 'ro' => 'Ascultați acest articol', 'not' => array(  ) ),
	array( 'en' => 'Read the article', 'ro' => 'Citiți articolul', 'not' => array( 'Citește articolul' ) ),
	array( 'en' => 'N chapters', 'ro' => 'capitole', 'not' => array(  ) ),
	array( 'en' => 'Share / Copy link / Email', 'ro' => 'Partajați / Copiați linkul / Trimiteți pe e-mail', 'not' => array( 'Împărtășiți / Link copiat / E-mail' ) ),
	array( 'en' => '<Model> Refrigerant Charging Brochure', 'ro' => 'Broșură privind încărcarea cu agent frigorific <Model>', 'not' => array( 'Broșură de încărcare cu refrigerant' ) ),
	array( 'en' => 'Titan <Application> System', 'ro' => 'Sistemul Titan pentru <Application>', 'not' => array( 'Titan Sistemul' ) ),
	array( 'en' => 'Explore', 'ro' => 'Explorați', 'not' => array( 'Mai multe informații' ) ),
	array( 'en' => 'Browse catalog', 'ro' => 'Consultați catalogul', 'not' => array( 'Catalog', 'Răsfoire catalog' ) ),
	array( 'en' => 'Browse all resources', 'ro' => 'Consultați toate resursele', 'not' => array( 'Toate resursele', 'Răsfoiți toate resursele' ) ),
	array( 'en' => 'Explore the Catalog', 'ro' => 'Explorați catalogul', 'not' => array( 'Catalogul' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'ro' => 'Sunteți pregătiți să vă modernizați infrastructura?', 'not' => array( 'Gata de a moderniza infrastructura', 'Pregătit să îți modernizezi infrastructura' ) ),
	array( 'en' => 'gantry milling', 'ro' => 'frezare pe centru tip portal', 'not' => array( 'frezare bramată', 'frezare cu portic' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'ro' => 'Mașină combinată de echilibrat miezuri la viteză ridicată și redusă', 'not' => array( 'Mașină de echilibrat nucleu combinat la viteză mare și redusă', 'Mașină de echilibrat pentru nuclee cu viteză ridicată și redusă combinată' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'ro' => 'Stand dinamic de testare a debitului pentru turbosuflante', 'not' => array( 'Bancă de flux turbocompressor dinamică', 'Stand de flux dinamic' ) ),
	array( 'en' => 'actionable insights', 'ro' => 'informații pe baza cărora se poate acționa', 'not' => array( 'informații acționabile', 'informații utile' ) ),
	array( 'en' => 'expert insights', 'ro' => 'perspectivele experților noștri', 'not' => array( 'intuiții de expert', 'viziuni ale experților' ) ),
	array( 'en' => 'fully loaded test', 'ro' => 'test sub sarcină maximă', 'not' => array( 'test complet încărcat' ) ),
	array( 'en' => 'Addresses', 'ro' => 'Abordează', 'not' => array( 'Elimină', 'Înlătură' ) ),
	array( 'en' => 'is now', 'ro' => 'devine', 'not' => array( 'este acum' ) ),
	array( 'en' => 'sales inquiry', 'ro' => 'solicitare privind vânzările', 'not' => array( 'interogare vânzări', 'cerere de vânzări', 'anchetă de vânzări' ) ),
	array( 'en' => 'Priority 1/2/3', 'ro' => 'Prioritate 1/2/3', 'not' => array( 'Prioritatea 1 înaltă' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'ro' => 'Se caută pe ascentialtech.com', 'not' => array( 'Căutare ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'ro' => 'Vizualizarea calendarului nu este disponibilă', 'not' => array( 'Vedere calendar indisponibilă' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'ro' => 'Utilaje atașate – capăt de linie', 'not' => array( 'Implemente - Capăt de linie' ) ),
	array( 'en' => 'balancing machine', 'ro' => 'mașină de echilibrat', 'not' => array( 'echilibrator' ) ),
	array( 'en' => 'balancing machines', 'ro' => 'mașini de echilibrat', 'not' => array( 'echilibratoare', 'echilibratori' ) ),
	array( 'en' => 'balancer', 'ro' => 'mașină de echilibrat', 'not' => array( 'echilibrator', 'echilibratorul' ) ),
	array( 'en' => 'balancers', 'ro' => 'mașini de echilibrat', 'not' => array( 'echilibratori', 'echilibratoare', 'echilibratorii' ) ),
	array( 'en' => 'rotor', 'ro' => 'rotor', 'not' => array( 'rotorii', 'rotori', 'rotorilor' ) ),
	array( 'en' => 'rotors', 'ro' => 'rotoare', 'not' => array( 'rotorii' ) ),
	array( 'en' => 'journal', 'ro' => 'fus', 'not' => array( 'lagăr', 'jurnal', 'rulment' ) ),
	array( 'en' => 'journals', 'ro' => 'fusuri', 'not' => array( 'lagăre', 'jurnale' ) ),
	array( 'en' => 'Assembly', 'ro' => 'Asamblare', 'not' => array( 'Montaj', 'Montare', 'montaj' ) ),
	array( 'en' => 'pump impeller', 'ro' => 'rotor de pompă', 'not' => array( 'roată de pompă', 'palete de pompă', 'roți de pompă' ) ),
	array( 'en' => 'pump impeller balancer', 'ro' => 'mașină de echilibrat rotoare de pompă', 'not' => array( 'echilibrator de palete de pompă', 'echilibrator de roți de pompă' ) ),
	array( 'en' => 'supercharger', 'ro' => 'compresor de supraalimentare', 'not' => array( 'supraîncărcător', 'supraîncărcătoare' ) ),
	array( 'en' => 'turbocharger', 'ro' => 'turbosuflantă', 'not' => array( 'turbocompressor', 'supraîncărcător' ) ),
	array( 'en' => 'turbochargers', 'ro' => 'turbosuflante', 'not' => array( 'turbocompressoare', 'supraîncărcătoare' ) ),
	array( 'en' => 'core', 'ro' => 'miez', 'not' => array( 'nucleu', 'sâmbure' ) ),
	array( 'en' => 'cores', 'ro' => 'miezuri', 'not' => array( 'nuclee', 'nucleuri' ) ),
	array( 'en' => 'Tools', 'ro' => 'Scule', 'not' => array( 'Unelte', 'Ustensile' ) ),
	array( 'en' => 'tool holder', 'ro' => 'portsculă', 'not' => array( 'suport pentru unelte', 'suporturi de unelte' ) ),
	array( 'en' => 'vacuum gauges', 'ro' => 'vacuummetre', 'not' => array( 'manometre de vid', 'indicatoare de vid' ) ),
	array( 'en' => 'pickling line', 'ro' => 'linie de decapare', 'not' => array( 'bandă de decapare', 'benzi de decapare' ) ),
	array( 'en' => 'Pickling Lines', 'ro' => 'Linii de decapare', 'not' => array( 'Benzi de decapare' ) ),
	array( 'en' => 'cold and hot rolling mills', 'ro' => 'laminoare la rece și la cald', 'not' => array( 'laminoare cu role reci și calde', 'laminoare cu cilindri reci și calzi' ) ),
	array( 'en' => 'rotary motion', 'ro' => 'mișcare de rotație', 'not' => array( 'mișcare rotativă' ) ),
	array( 'en' => 'robotic application', 'ro' => 'aplicații robotizate', 'not' => array(  ) ),
	array( 'en' => 'vibration damping casting', 'ro' => 'turnare cu absorbția vibrațiilor', 'not' => array( 'Turnătorie cu absorbție vibrațiilor', 'turnătorie cu absorbția vibrațiilor' ) ),
	array( 'en' => 'furnace and blast furnace technology', 'ro' => 'tehnologie de cuptoare și furnale', 'not' => array( 'Tehnologie de cuptoare și furnale cu vânt' ) ),
	array( 'en' => 'paper and plastics industry', 'ro' => 'industria hârtiei și a materialelor plastice', 'not' => array( 'Industria hârtiei și plasticului', 'industria hârtiei și plasticului' ) ),
	array( 'en' => 'Kleinknecht Testing Technology', 'ro' => 'Tehnologie de testare Kleinknecht', 'not' => array( 'Kleinknecht Tehnologie de testare', 'Kleinknecht - Tehnologie de testare' ) ),
	array( 'en' => 'Vehicles - End of Line', 'ro' => 'Vehicule – capăt de linie', 'not' => array( 'Vehicule la capăt de linie' ) ),
	array( 'en' => 'Equipment - End of Line', 'ro' => 'Utilaje – capăt de linie', 'not' => array( 'Echipamente - Capăt de linie', 'Echipamente – capăt de linie' ) ),
	array( 'en' => 'LGC60XX Automatic Grinding Control', 'ro' => 'Control automat de rectificare LGC60XX', 'not' => array( 'Control automat al rectificatorului LGC60XX', 'Sistem de control automat pentru rectificatoare LGC60XX' ) ),
	array( 'en' => 'PGC9400 Profile Grinder Control', 'ro' => 'Sistem de comandă pentru rectificatoare de profil PGC9400', 'not' => array( 'Sistem de control pentru rectificatoare de profil PGC9400' ) ),
	array( 'en' => 'facilities', 'ro' => 'unități', 'not' => array( 'facilități', 'facilitați' ) ),
	array( 'en' => 'resource hub', 'ro' => 'centrul de resurse', 'not' => array( 'hub-ul de resurse', 'hub de aplicații și resurse' ) ),
	array( 'en' => 'combine belt', 'ro' => 'curea pentru combină', 'not' => array( 'Curea combine', 'curea combine' ) ),
	array( 'en' => 'combine draper header', 'ro' => 'header cu bandă transportoare pentru combine', 'not' => array( 'Capul de recoltat combine' ) ),
	array( 'en' => 'test bench assembly and retrofit', 'ro' => 'montarea și modernizarea standurilor de testare', 'not' => array( 'Montaj și modernizare de bănci de testare' ) ),
	array( 'en' => 'rotation tester', 'ro' => 'stand de testare prin rotație', 'not' => array( 'testator de rotație', 'testatori de rotație' ) ),
	array( 'en' => 'we have you covered', 'ro' => 'vă stăm alături', 'not' => array( 'vă avem acoperit' ) ),
	array( 'en' => 'Tested by time.', 'ro' => 'Verificate de timp.', 'not' => array( 'Testat de timp.', 'Testate de timp.' ) ),
	array( 'en' => 'Tuned for results.', 'ro' => 'Reglate pentru rezultate.', 'not' => array( 'Acordat pentru rezultate.' ) ),
	array( 'en' => 'Download brochure', 'ro' => 'Descărcați broșura', 'not' => array( 'Broșură de descărcat' ) ),
	array( 'en' => 'Get a service quote', 'ro' => 'Solicitați o ofertă de service', 'not' => array( 'Obțineți o ofertă de service', 'Ofertă de service' ) ),
	array( 'en' => 'Plan Levels', 'ro' => 'Niveluri de plan', 'not' => array(  ) ),
	array( 'en' => 'Speak with a service professional', 'ro' => 'Vorbiți cu un specialist în service', 'not' => array( 'Discutați cu un profesionist de service' ) ),
	array( 'en' => 'Speak to an expert', 'ro' => 'Vorbiți cu un expert', 'not' => array( 'Discutați cu un specialist', 'Vorbiți cu un specialist' ) ),
	array( 'en' => 'Speak to a solutions expert', 'ro' => 'Vorbiți cu un expert în soluții', 'not' => array( 'Discutați cu un expert în soluții' ) ),
	array( 'en' => 'Intervention time (in business hours)', 'ro' => 'Timp de intervenție (în orele de program)', 'not' => array( 'Timp de intervenție în ore de birou' ) ),
	array( 'en' => 'Not sure where to start?', 'ro' => 'Nu știți de unde să începeți?', 'not' => array( 'Nu sunteți sigur de unde să începeți?', 'Nu ești sigur de unde să începi?' ) ),
	array( 'en' => 'Describe what you need', 'ro' => 'Descrieți de ce aveți nevoie', 'not' => array( 'Descrieți ce aveți nevoie' ) ),
	array( 'en' => 'across transportation applications', 'ro' => 'în aplicații din domeniul transporturilor', 'not' => array( 'pe aplicații din domeniul transporturilor' ) ),
	array( 'en' => 'propshaft', 'ro' => 'arbore cardanic', 'not' => array( 'arbore de propulsie' ) ),
	array( 'en' => 'driveshaft', 'ro' => 'arbore cardanic', 'not' => array( 'arbore conducător' ) ),
	array( 'en' => 'measuring times', 'ro' => 'timpi de măsurare rapizi', 'not' => array(  ) ),
	array( 'en' => 'differentials', 'ro' => 'diferențiale', 'not' => array( 'diferenţiale', 'diferenţialelor' ) ),
	array( 'en' => 'crankshafts', 'ro' => 'arbori cotiți', 'not' => array( 'arbori cotiți de motor' ) ),
	array( 'en' => 'brake rotor balancer', 'ro' => 'mașină de echilibrat rotoare de frână', 'not' => array( 'Echilibrator rotor de frână' ) ),
	array( 'en' => 'differential case balancer', 'ro' => 'mașină de echilibrat carcase de diferențial', 'not' => array( 'Echilibrator carcasă diferențial' ) ),
	array( 'en' => 'clutch and flywheel balancer', 'ro' => 'mașină de echilibrat ambreiaje și volante', 'not' => array( 'Echilibrator ambreiaj și volant' ) ),
	array( 'en' => 'fan balancer', 'ro' => 'mașină de echilibrat ventilatoare', 'not' => array( 'Echilibrator de ventilator' ) ),
	array( 'en' => 'aircraft wheel balancer', 'ro' => 'mașină de echilibrat roți de aeronavă', 'not' => array( 'Echilibrator de roți de aeronavă' ) ),
	array( 'en' => 'transmission component balancer', 'ro' => 'mașină de echilibrat componente de transmisie', 'not' => array( 'Echilibrator de componente de transmisie' ) ),
	array( 'en' => 'propeller balancers', 'ro' => 'mașini de echilibrat elice', 'not' => array( 'Echilibratori de elice' ) ),
	array( 'en' => 'turbine balancing machine', 'ro' => 'mașină de echilibrat turbine', 'not' => array( 'Echilibrator de turbine' ) ),
	array( 'en' => 'Electric Armatures', 'ro' => 'Armături electrice', 'not' => array( 'Armaturi electrice' ) ),
	array( 'en' => 'ECFA and HVAC fan balancers', 'ro' => 'mașini de echilibrat ventilatoare ECFA și HVAC', 'not' => array( 'Echilibratori pentru suflante ECFA și climatizare' ) ),
	array( 'en' => 'train wheels', 'ro' => 'roți de tren', 'not' => array( 'roate de tren' ) ),
	array( 'en' => 'wheel sets', 'ro' => 'seturi de roți', 'not' => array( 'garnituri de roți' ) ),
	array( 'en' => 'woodworking tools and saws', 'ro' => 'scule de prelucrare a lemnului și ferăstraie', 'not' => array( 'Unelte de prelucrare a lemnului și ferăstraie' ) ),
	array( 'en' => 'Titan', 'ro' => 'Titan', 'not' => array( 'Titanul' ) ),
	array( 'en' => 'Cimat', 'ro' => 'Cimat', 'not' => array( 'Cimatul' ) ),
	array( 'en' => 'Lismar', 'ro' => 'Lismar', 'not' => array( 'Lismarul' ) ),
	array( 'en' => 'Galileo', 'ro' => 'Galileo', 'not' => array( 'Galileul' ) ),
	array( 'en' => 'Kleinknecht', 'ro' => 'Kleinknecht', 'not' => array( 'Kleinknechtul' ) ),
	array( 'en' => 'Bauer', 'ro' => 'Bauer', 'not' => array( 'Bauerul' ) ),
	array( 'en' => 'WinterPark', 'ro' => 'WinterPark', 'not' => array( 'Winter Park', 'Parcul de Iarnă' ) ),
	array( 'en' => 'Sentia', 'ro' => 'Sentia', 'not' => array( 'Sentiei' ) ),
	array( 'en' => 'Ascentialytics', 'ro' => 'Ascentialytics', 'not' => array( 'Analize Ascential', 'Ascential Analytics' ) ),
	array( 'en' => 'Ascential Care', 'ro' => 'Ascential Care', 'not' => array( 'Îngrijire Ascential', 'Ascential Îngrijire' ) ),
	array( 'en' => 'Ascential Technologies', 'ro' => 'Ascential Technologies', 'not' => array( 'Tehnologii Ascential' ) ),
	array( 'en' => 'ADAS Garage', 'ro' => 'ADAS Garage', 'not' => array( 'Garajul ADAS', 'Atelier ADAS' ) ),
	array( 'en' => 'Impossible? Done.', 'ro' => 'Impossible? Done.', 'not' => array( 'Imposibil? Rezolvat.', 'Imposibil? Gata.' ) ),
	array( 'en' => 'Burke Porter', 'ro' => 'Burke Porter', 'not' => array( 'Burke Porterul' ) ),
	array( 'en' => 'training', 'ro' => 'instruire', 'not' => array( 'formare', 'pregătire profesională', 'antrenament' ) ),
	array( 'en' => 'Training courses', 'ro' => 'Cursuri de instruire', 'not' => array( 'Cursuri de formare' ) ),
	array( 'en' => 'request', 'ro' => 'solicitare', 'not' => array( 'cerere', 'interogare', 'rugăminte' ) ),
	array( 'en' => 'support', 'ro' => 'asistență', 'not' => array( 'suport', 'sprijin tehnic' ) ),
	array( 'en' => 'service', 'ro' => 'service', 'not' => array( 'deservire', 'serviciu' ) ),
	array( 'en' => 'machine', 'ro' => 'utilaj', 'not' => array( 'mașinărie', 'mașina dumneavoastră' ) ),
	array( 'en' => 'machine health', 'ro' => 'starea echipamentelor', 'not' => array( 'sănătatea mașinii', 'starea de sănătate a utilajului' ) ),
	array( 'en' => 'machine down', 'ro' => 'utilaj oprit din funcțiune', 'not' => array( 'mașina este oprită', 'mașină închisă' ) ),
	array( 'en' => 'facility', 'ro' => 'unitate', 'not' => array( 'instalație', 'locație', 'facilitate' ) ),
	array( 'en' => 'downtime', 'ro' => 'timpi de nefuncționare', 'not' => array( 'timp mort', 'oprire de producție' ) ),
	array( 'en' => 'unplanned downtime', 'ro' => 'timpi de nefuncționare neplanificați', 'not' => array( 'oprire neprevăzută', 'timp mort neplanificat' ) ),
	array( 'en' => 'aftermarket', 'ro' => 'piața secundară', 'not' => array( 'după-piață', 'piața de post-vânzare' ) ),
	array( 'en' => 'end-of-line', 'ro' => 'capăt de linie', 'not' => array( 'final de linie', 'sfârșit de linie' ) ),
	array( 'en' => 'powertrain', 'ro' => 'grup motopropulsor', 'not' => array( 'tren de putere', 'lanț cinematic' ) ),
	array( 'en' => 'NDT', 'ro' => 'control nedistructiv (CND)', 'not' => array( 'testare nedistructivă', 'control non-distructiv' ) ),
	array( 'en' => 'throughput', 'ro' => 'debit de producție', 'not' => array( 'randament de trecere', 'capacitate de trecere' ) ),
	array( 'en' => 'rework', 'ro' => 'reprelucrare', 'not' => array( 'refacere', 'relucrare', 'remaniere' ) ),
	array( 'en' => 'gauging', 'ro' => 'control dimensional', 'not' => array( 'gabaritare', 'măsurătoare de calibru' ) ),
	array( 'en' => 'climate control', 'ro' => 'climatizare', 'not' => array( 'control climatic' ) ),
	array( 'en' => 'damage', 'ro' => 'deteriorări', 'not' => array( 'daune', 'avarieri', 'pagube' ) ),
	array( 'en' => 'press releases', 'ro' => 'comunicate de presă', 'not' => array( 'știri', 'comunicări de presă', 'declarații de presă' ) ),
	array( 'en' => 'transportation', 'ro' => 'Transport', 'not' => array(  ) ),
	array( 'en' => 'automotive', 'ro' => 'auto', 'not' => array(  ) ),
	array( 'en' => 'calibration', 'ro' => 'etalonare', 'not' => array( 'calibrare metrologică' ) ),
	array( 'en' => 'inquiry', 'ro' => 'solicitare', 'not' => array( 'interogare', 'interogație', 'anchetă' ) ),
	array( 'en' => 'mission-critical', 'ro' => 'de importanță critică', 'not' => array( 'critice pentru misiune', 'critic pentru misiune' ) ),
	array( 'en' => 'consistent', 'ro' => 'uniform', 'not' => array( 'consistent', 'consistentă' ) ),
	array( 'en' => 'empowered', 'ro' => 'au libertatea și mijloacele', 'not' => array( 'împuterniciți', 'împuternicit' ) ),
	array( 'en' => 'deep expertise', 'ro' => 'vasta noastră experiență', 'not' => array( 'expertiză profundă', 'expertiză adâncă' ) ),
	array( 'en' => 'responsiveness', 'ro' => 'promptitudine', 'not' => array( 'responsivitate', 'reactivitate' ) ),
	array( 'en' => 'website', 'ro' => 'site web', 'not' => array( 'website', 'pagină de internet' ) ),
	array( 'en' => 'Program Owner', 'ro' => 'responsabil de program', 'not' => array( 'Proprietar de program', 'Deținător de program' ) ),
	array( 'en' => 'proximity', 'ro' => 'proximitate', 'not' => array( 'apropiere fizică', 'vecinătate' ) ),
);
