<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

return array(
	array( 'en' => '*', 'tr' => 'The whole site addresses the reader in the formal plural (siz) in every string and every slot — body copy, headings, eyebrows, ALL-CAPS bands, buttons, form labels, placeholders, alt and aria text, the <title>, the meta description, og: tags and JSON-LD. Register is a property of the PAGE, not of the segment: an informal form in a meta description contradicts the formal body it ships with. The sen family and every second-person singular verb form are banned everywhere, at any length; the reader-facing possessive is -iniz/-ınız (ekipmanınız, ihtiyaçlarınız, tesisiniz) and the reader-facing imperative is -in/-ın/-un/-ün (okuyun, indirin, görün, seçin). BUTTONS AND LINK LABELS keep the verb of the English and take that same formal plural imperative, which is standard Turkish web UI: "Browse catalog" is "Kataloğu inceleyin", "Request a demo" is "Demo talep edin", "Download" is "İndirin", "Contact us" is "Bize ulaşın", "Read the article" is "Makaleyi okuyun". Never flatten a verb label into a bare noun ("Katalog", "İndirme", "Demo talebi" are wrong for those) and never drop to the bare stem ("incele", "indir", "oku"); the standalone search control "Ara" is the one accepted exception. Turkish is verb-final and sentence case: the verb ends the clause, and only the first word and genuine proper nouns are capitalised — in headlines, bullets and buttons too.', 'not' => array( 'senin', 'sana', 'seni', 'sende', 'senden', 'seninle', 'istiyorsun', 'istersen', 'yapabilirsin', 'edebilirsin', 'olabilirsin', 'alabilirsin', 'görebilirsin', 'bulabilirsin', 'bilebilirsin', 'görürsün', 'okursun', 'bilirsin', 'düşünüyorsun', 'hazırsın', 'değilsin', 'emin değilsen', 'ihtiyacın', 'indir', 'incele', 'keşfet', 'öğren', 'başla', 'tıkla', 'kaydol', 'doldur', 'izle', 'abone ol', 'iletişime geç', 'talep et', 'göz at' ) ),
	array( 'en' => 'unbalance', 'tr' => 'dengesizlik', 'not' => array( 'balanssızlık', 'dengelenmemişlik', 'balans bozukluğu' ) ),
	array( 'en' => 'residual unbalance', 'tr' => 'artık dengesizlik', 'not' => array( 'kalıntı dengesizlik', 'rezidüel dengesizlik' ) ),
	array( 'en' => 'unbalance correction', 'tr' => 'dengesizlik düzeltme', 'not' => array( 'dengesizlik onarımı', 'dengesizlik tamiri' ) ),
	array( 'en' => 'correction', 'tr' => 'düzeltme', 'not' => array( 'onarım', 'tashih', 'tamir' ) ),
	array( 'en' => 'balancing', 'tr' => 'balanslama', 'not' => array( 'dengeleme', 'dengeleyiş' ) ),
	array( 'en' => 'balancing machine', 'tr' => 'balans makinesi', 'not' => array( 'dengeleme makinesi', 'balans makinası', 'denge makinesi' ) ),
	array( 'en' => 'balancing machines', 'tr' => 'balans makineleri', 'not' => array( 'dengeleme makineleri', 'denge makineleri' ) ),
	array( 'en' => 'balancer', 'tr' => 'balans makinesi', 'not' => array( 'balanslaycı', 'balansleyici', 'balansçı', 'balanslayıcı', 'balanslatıcı', 'dengeleyici' ) ),
	array( 'en' => 'balancers', 'tr' => 'balans makineleri', 'not' => array( 'balanslaycılar', 'balansleyiciler', 'balanslatıcıları', 'dengeleyiciler', 'balanslaycıları' ) ),
	array( 'en' => 'non-rotating balancing machine', 'tr' => 'dönmeyen balans makinesi', 'not' => array( 'dönermeyen balanslama makinesi', 'dönen olmayan balanslama makinesi', 'döner olmayan dengeleme makinesi', 'rotorsuz balans makinesi' ) ),
	array( 'en' => 'Non-Rotate Systems', 'tr' => 'Dönmeyen sistemler', 'not' => array( 'Dönen olmayan sistemler', 'Döndürmeyen sistemler' ) ),
	array( 'en' => 'spin testing machine', 'tr' => 'döndürme test makinesi', 'not' => array( 'çevirme test makinesi', 'fırıldak test makinesi' ) ),
	array( 'en' => 'spin testing', 'tr' => 'döndürme testi', 'not' => array( 'çevirme testi', 'fırıldama testi', 'Fırıldama testi', 'Çevirme denemeleri' ) ),
	array( 'en' => 'audit station', 'tr' => 'denetim istasyonu', 'not' => array( 'teftiş istasyonu', 'audit istasyonu', 'murakabe istasyonu' ) ),
	array( 'en' => 'audit balancer', 'tr' => 'denetim balans makinesi', 'not' => array( 'audit balanslaycısı', 'teftiş dengeleyicisi' ) ),
	array( 'en' => 'single station', 'tr' => 'tek istasyonlu', 'not' => array( 'tek kabinli', 'tek odalı', 'tek duraklı' ) ),
	array( 'en' => 'multi station', 'tr' => 'çok istasyonlu', 'not' => array( 'çok kabinli', 'çok odalı', 'çoklu duraklı' ) ),
	array( 'en' => 'vertical balancing machines', 'tr' => 'dikey balans makineleri', 'not' => array( 'düşey dengeleme makineleri', 'dikey dengeleme makineleri' ) ),
	array( 'en' => 'horizontal balancing machines', 'tr' => 'yatay balans makineleri', 'not' => array( 'ufki dengeleme makineleri', 'yatay dengeleme makineleri' ) ),
	array( 'en' => 'burst proof protection', 'tr' => 'rotor parçalanmasına karşı koruma', 'not' => array( 'patlama koruması', 'patlamaya karşı koruma', 'infilak koruması' ) ),
	array( 'en' => 'balance quality grade', 'tr' => 'denge kalitesi sınıfı', 'not' => array( 'balans kalite notu', 'denge kalite derecesi' ) ),
	array( 'en' => 'rigid rotor', 'tr' => 'rijit rotor', 'not' => array( 'katı rotor', 'sert rotor' ) ),
	array( 'en' => 'field balancing', 'tr' => 'sahada balanslama', 'not' => array( 'alan balanslaması', 'arazi balanslaması', 'tarla balanslaması' ) ),
	array( 'en' => 'armature', 'tr' => 'endüvi', 'not' => array( 'zırh', 'armatür', 'elektrik rotoru' ) ),
	array( 'en' => 'journal', 'tr' => 'muylu', 'not' => array( 'jurnal', 'dergi', 'boyun' ) ),
	array( 'en' => 'shaft', 'tr' => 'mil', 'not' => array( 'şaft', 'mihver' ) ),
	array( 'en' => 'driveshaft', 'tr' => 'kardan mili', 'not' => array( 'kardanımız', 'tahrik şaftı', 'sürücü mili' ) ),
	array( 'en' => 'propshaft', 'tr' => 'kardan mili', 'not' => array( 'pervane mili', 'kardanımız', 'itici mil' ) ),
	array( 'en' => 'crankshaft', 'tr' => 'krank mili', 'not' => array( 'krank şaftı', 'manivela mili' ) ),
	array( 'en' => 'inline crankshaft', 'tr' => 'sıra tipi krank mili', 'not' => array( 'satır içi krank mili', 'dört zamanlı krank mili', 'çizgi içi krank mili' ) ),
	array( 'en' => 'single cylinder crankshaft', 'tr' => 'tek silindirli krank mili', 'not' => array( 'tek izli krank mili', 'tek tekerli krank mili' ) ),
	array( 'en' => 'mass centering machine', 'tr' => 'kütle merkezleme makinesi', 'not' => array( 'ağırlık ortalama makinesi' ) ),
	array( 'en' => 'flywheel', 'tr' => 'volant', 'not' => array( 'uçan tekerlek', 'çark tekerleği', 'sinek tekerleği' ) ),
	array( 'en' => 'dual mass flywheel', 'tr' => 'çift kütleli volant', 'not' => array( 'çift kütleli debriyaj', 'iki kütleli kavrama' ) ),
	array( 'en' => 'flexplate', 'tr' => 'esnek tahrik plakası', 'not' => array( 'esnek levha', 'esnek tabak' ) ),
	array( 'en' => 'clutch', 'tr' => 'debriyaj', 'not' => array( 'kavrama bileziği', 'tutucu', 'pençe' ) ),
	array( 'en' => 'pulley', 'tr' => 'kasnak', 'not' => array( 'kayış', 'makara kayışı' ) ),
	array( 'en' => 'impeller', 'tr' => 'çark', 'not' => array( 'pervane', 'impeler', 'itici' ) ),
	array( 'en' => 'pump impeller', 'tr' => 'pompa çarkı', 'not' => array( 'pompa impelleri', 'pompa pervanesi' ) ),
	array( 'en' => 'blowers', 'tr' => 'blower', 'not' => array( 'hava üfleyici', 'körük', 'üfleyici' ) ),
	array( 'en' => 'brake disc', 'tr' => 'fren diski', 'not' => array( 'fren plakası', 'fren tabağı' ) ),
	array( 'en' => 'brake drum', 'tr' => 'fren kampanası', 'not' => array( 'fren tamburu', 'fren davulu' ) ),
	array( 'en' => 'brake rotor', 'tr' => 'fren diski', 'not' => array( 'fren rotoru', 'fren döneri' ) ),
	array( 'en' => 'grinding wheel', 'tr' => 'taşlama taşı', 'not' => array( 'öğütme çarkı', 'öğütme tekerleği', 'taşlama tekerleği' ) ),
	array( 'en' => 'pinion gear', 'tr' => 'pinyon dişli', 'not' => array( 'muylu dişli', 'çark dişlisi', 'küçük tekerlek' ) ),
	array( 'en' => 'ring gears', 'tr' => 'ayna dişliler', 'not' => array( 'halka dişliler', 'yüzük dişliler', 'pierceli dişliler' ) ),
	array( 'en' => 'gantry', 'tr' => 'portal', 'not' => array( 'vinç kirişi', 'köprü ayağı', 'darağacı' ) ),
	array( 'en' => 'gantry milling', 'tr' => 'portal frezeleme', 'not' => array( 'bramalı frezeleme', 'kapı frezeleme', 'köprü öğütmesi' ) ),
	array( 'en' => 'gantry loading', 'tr' => 'portal yükleme', 'not' => array( 'kapı yüklemesi', 'köprü yüklemesi' ) ),
	array( 'en' => 'robot loading', 'tr' => 'robotla yükleme', 'not' => array( 'robot yüklemesi olan' ) ),
	array( 'en' => 'conveyor loading', 'tr' => 'konveyörle yükleme', 'not' => array( 'taşıyıcı bantla yükleme' ) ),
	array( 'en' => 'track loading', 'tr' => 'iz yükleme', 'not' => array( 'ray yüklemesi', 'palet yüklemesi' ) ),
	array( 'en' => 'walking beam system', 'tr' => 'yürüyen kiriş sistemi', 'not' => array( 'yürüyen ışın sistemi', 'gezici kiriş sistemi' ) ),
	array( 'en' => 'bearers', 'tr' => 'yatak mesnetleri', 'not' => array( 'rulmanlar', 'taşıyıcılar', 'hamallar' ) ),
	array( 'en' => 'pedestals', 'tr' => 'mesnet kuleleri', 'not' => array( 'piedestaller', 'kaideler', 'heykel kaideleri' ) ),
	array( 'en' => 'pins', 'tr' => 'pimler', 'not' => array( 'muylular', 'çiviler', 'iğneler' ) ),
	array( 'en' => 'v-block support', 'tr' => 'V blok mesneti', 'not' => array( 'V bloklu destek yatağı', 'V blok rulmanı' ) ),
	array( 'en' => 'bearing center lines', 'tr' => 'yatak eksen çizgileri', 'not' => array( 'rulman merkez hatları' ) ),
	array( 'en' => 'bearing life', 'tr' => 'rulman ömrü', 'not' => array( 'yatak yaşamı', 'rulman yaşamı' ) ),
	array( 'en' => 'tapered roller bearing', 'tr' => 'konik makaralı rulman', 'not' => array( 'konikleştirilmiş silindir yatağı' ) ),
	array( 'en' => 'vibration', 'tr' => 'titreşim', 'not' => array( 'vibrasyon', 'sarsıntı', 'titreme' ) ),
	array( 'en' => 'vibration analysis', 'tr' => 'titreşim analizi', 'not' => array( 'vibrasyon incelemesi', 'sarsıntı çözümlemesi' ) ),
	array( 'en' => 'run-out', 'tr' => 'salgı', 'not' => array( 'kaçış', 'dışa çıkma', 'bitiş' ) ),
	array( 'en' => 'misalignment', 'tr' => 'eksen kaçıklığı', 'not' => array( 'yanlış hizalama', 'uyumsuzluk', 'hatalı dizilim' ) ),
	array( 'en' => 'maximum rotor diameter', 'tr' => 'maksimum rotor çapı', 'not' => array( 'en büyük rotor kutru' ) ),
	array( 'en' => 'Electronic hung mass', 'tr' => 'elektronik asılı kütle telafisi', 'not' => array( 'elektronik asılı kütle', 'elektronik sarkan ağırlık' ) ),
	array( 'en' => 'punching', 'tr' => 'zımbalama', 'not' => array( 'yumruklama', 'vurma', 'yumruk atma' ) ),
	array( 'en' => 'drilling correction', 'tr' => 'delme ile düzeltme', 'not' => array( 'sondaj düzeltmesi', 'delik açma tashihi' ) ),
	array( 'en' => 'milling correction', 'tr' => 'frezeleme ile düzeltme', 'not' => array( 'değirmenci düzeltmesi', 'değirmeci düzeltmesi', 'öğütme düzeltmesi' ) ),
	array( 'en' => 'laser welding', 'tr' => 'lazer kaynağı', 'not' => array( 'lazer lehimi', 'lazer kaynaması' ) ),
	array( 'en' => 'weight capacity', 'tr' => 'taşıma kapasitesi', 'not' => array( 'ağırlık kapasitesi', 'tartı kapasitesi' ) ),
	array( 'en' => 'load capacity', 'tr' => 'yük kapasitesi', 'not' => array( 'yükleme kabiliyeti', 'taşıma yeteneği' ) ),
	array( 'en' => 'turbocharger', 'tr' => 'turboşarj', 'not' => array( 'turbo şarj cihazı', 'aşırı doldurucu' ) ),
	array( 'en' => 'supercharger', 'tr' => 'süperşarj', 'not' => array( 'süper doldurucu', 'süper şarj aleti' ) ),
	array( 'en' => 'core', 'tr' => 'kartuş', 'not' => array( 'çekirdek', 'nüve', 'tohum', 'göbek' ) ),
	array( 'en' => 'core balancing', 'tr' => 'kartuş balanslaması', 'not' => array( 'çekirdek balanslaması', 'çekirdek dengelemesi' ) ),
	array( 'en' => 'core balancing machine', 'tr' => 'kartuş balans makinesi', 'not' => array( 'çekirdek balanslama makinesi', 'çekirdek dengeleme makinesi' ) ),
	array( 'en' => 'turbocharger flow bench', 'tr' => 'turboşarj akış tezgâhı', 'not' => array( 'turboşarj akış bankı', 'turbo flow tezgâhı', 'turboşarj akış sırası' ) ),
	array( 'en' => 'flow bench', 'tr' => 'akış tezgâhı', 'not' => array( 'flow tezgâhı', 'akış bankı', 'akış sırası' ) ),
	array( 'en' => 'turbocharger frame size', 'tr' => 'turboşarj gövde ölçüsü', 'not' => array( 'turboşarj çerçeve boyutu', 'turbo kasa büyüklüğü' ) ),
	array( 'en' => 'turbo calibration', 'tr' => 'turbo kalibrasyonu', 'not' => array( 'turbo ayarı', 'turbo düzeltmesi' ) ),
	array( 'en' => 'whistle', 'tr' => 'ıslık sesi', 'not' => array( 'düdük', 'düdük sesi' ) ),
	array( 'en' => 'compressor wheel', 'tr' => 'kompresör çarkı', 'not' => array( 'kompresör tekerleği', 'kompresör jantı' ) ),
	array( 'en' => 'turbine wheel', 'tr' => 'türbin çarkı', 'not' => array( 'türbin tekerleği', 'türbin jantı' ) ),
	array( 'en' => 'boreless compressor wheel', 'tr' => 'deliksiz kompresör çarkı', 'not' => array( 'delik kompresör tekerleği' ) ),
	array( 'en' => 'turbine component balancer', 'tr' => 'türbin bileşeni balans makinesi', 'not' => array( 'türbin bileşen balanslaycısı' ) ),
	array( 'en' => 'leak', 'tr' => 'kaçak', 'not' => array( 'sızıntı', 'akıntı', 'damlama' ) ),
	array( 'en' => 'leak detection', 'tr' => 'kaçak tespiti', 'not' => array( 'sızıntı tespiti', 'sızıntı algılama', 'kaçak algılaması' ) ),
	array( 'en' => 'leak detection systems', 'tr' => 'kaçak tespit sistemleri', 'not' => array( 'sızıntı tespit sistemleri', 'sızıntı algılama sistemleri' ) ),
	array( 'en' => 'leak test', 'tr' => 'kaçak testi', 'not' => array( 'sızıntı testi', 'sızdırmazlık denemesi' ) ),
	array( 'en' => 'leak detector', 'tr' => 'kaçak dedektörü', 'not' => array( 'sızıntı dedektörü', 'kaçak bulucu' ) ),
	array( 'en' => 'gross leak test', 'tr' => 'kaba kaçak testi', 'not' => array( 'brüt sızıntı testi', 'büyük kaçak testi' ) ),
	array( 'en' => 'fine leak', 'tr' => 'ince kaçak', 'not' => array( 'hassas sızıntı', 'narin kaçak' ) ),
	array( 'en' => 'tracer gas', 'tr' => 'izleyici gaz', 'not' => array( 'iz gazı', 'takip gazı' ) ),
	array( 'en' => 'sniffing pliers / sniffer', 'tr' => 'koklama probu', 'not' => array( 'koklama pensesi', 'koklayıcı kerpeten', 'burun probu' ) ),
	array( 'en' => 'helium', 'tr' => 'helyum', 'not' => array( 'Helium' ) ),
	array( 'en' => 'helium leak detection', 'tr' => 'helyum kaçak tespiti', 'not' => array( 'helyum sızıntı tespiti', 'helyum sızıntı algılaması' ) ),
	array( 'en' => 'helium recovery systems', 'tr' => 'helyum geri kazanım sistemleri', 'not' => array( 'helyum kurtarma sistemleri', 'helyum iyileştirme sistemleri' ) ),
	array( 'en' => 'Recovery Systems', 'tr' => 'Geri kazanım sistemleri', 'not' => array( 'Kurtarma sistemleri', 'İyileşme sistemleri' ) ),
	array( 'en' => 'refrigerant', 'tr' => 'soğutucu akışkan', 'not' => array( 'soğutucu sıvı', 'soğutma suyu', 'soğutkan', 'antifriz' ) ),
	array( 'en' => 'refrigerant charging', 'tr' => 'soğutucu akışkan dolumu', 'not' => array( 'soğutucu şarjı', 'soğutucu yüklemesi', 'soğutucu akışkan şarjı' ) ),
	array( 'en' => 'refrigerant charging machines', 'tr' => 'soğutucu akışkan dolum makineleri', 'not' => array( 'soğutucu şarj makineleri', 'soğutma dolum makineleri' ) ),
	array( 'en' => 'refrigerant variants', 'tr' => 'soğutucu akışkan çeşitleri', 'not' => array( 'soğutucu varyasyonları' ) ),
	array( 'en' => 'vacuum', 'tr' => 'vakum', 'not' => array( 'boşluk', 'emme', 'süpürge' ) ),
	array( 'en' => 'vacuum evacuation', 'tr' => 'vakumlama', 'not' => array( 'vakum tahliyesi', 'vakum boşaltma', 'vakum ewakuasyonu' ) ),
	array( 'en' => 'evacuation', 'tr' => 'vakumlama', 'not' => array( 'tahliye', 'boşaltma', 'kaçış' ) ),
	array( 'en' => 'vacuum rise test', 'tr' => 'vakum artış testi', 'not' => array( 'vakum yükselme denemesi', 'vakum kalkma testi' ) ),
	array( 'en' => 'Vacuum Chamber', 'tr' => 'Vakum odası', 'not' => array( 'Vakum haznesi', 'Vakum kabini' ) ),
	array( 'en' => 'vacuum gauge', 'tr' => 'vakum manometresi', 'not' => array( 'vakum ölçer', 'vakum saati' ) ),
	array( 'en' => 'Rotational Vacuum Pumps', 'tr' => 'Döner vakum pompaları', 'not' => array( 'Rotasyonel vakum pompaları', 'Dönel emme pompaları' ) ),
	array( 'en' => 'transfer pumps', 'tr' => 'transfer pompaları', 'not' => array( 'aktarma pompaları', 'nakil pompaları' ) ),
	array( 'en' => 'pressurization', 'tr' => 'basınçlandırma', 'not' => array( 'basınç verme', 'presleme' ) ),
	array( 'en' => 'pressure decay test', 'tr' => 'basınç düşüş testi', 'not' => array( 'basınç çürüme testi', 'basınç bozunma denemesi' ) ),
	array( 'en' => 'filler gun', 'tr' => 'dolum tabancası', 'not' => array( 'dolgu tabancası', 'tabancacık', 'pistoletçik' ) ),
	array( 'en' => 'filler', 'tr' => 'dolum ünitesi', 'not' => array( 'dolgu maddesi', 'doldurucu madde' ) ),
	array( 'en' => 'final discharge', 'tr' => 'son boşaltma', 'not' => array( 'nihai deşarj', 'son tahliye' ) ),
	array( 'en' => 'flammable gases', 'tr' => 'yanıcı gazlar', 'not' => array( 'alev alabilir gazlar', 'tutuşucu gazlar' ) ),
	array( 'en' => 'hazardous area', 'tr' => 'tehlikeli bölge', 'not' => array( 'riskli alan', 'tehlikeli saha' ) ),
	array( 'en' => 'safety valves', 'tr' => 'emniyet valfleri', 'not' => array( 'güvenlik vanaları', 'emniyet supapları' ) ),
	array( 'en' => 'end-course switches', 'tr' => 'son konum şalterleri', 'not' => array( 'ders sonu anahtarları', 'yol sonu düğmeleri', 'kurs sonu şalterleri' ) ),
	array( 'en' => 'protection fences', 'tr' => 'koruma çitleri', 'not' => array( 'koruyucu parmaklıklar', 'savunma çitleri' ) ),
	array( 'en' => 'ventilation systems', 'tr' => 'havalandırma sistemleri', 'not' => array( 'vantilasyon sistemleri', 'hava verme sistemleri' ) ),
	array( 'en' => 'sealed assembly', 'tr' => 'sızdırmaz montaj grubu', 'not' => array( 'kapalı montaj', 'mühürlü tertibat' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'tr' => 'ultrasonik nozul temizleyici', 'not' => array( 'ultrases meme yıkayıcı' ) ),
	array( 'en' => 'air handling unit', 'tr' => 'klima santrali', 'not' => array( 'hava işleme ünitesi', 'hava taşıma birimi' ) ),
	array( 'en' => 'refrigerated trailer', 'tr' => 'frigorifik treyler', 'not' => array( 'soğutmalı römork', 'buzdolabı treyleri' ) ),
	array( 'en' => 'cooling units', 'tr' => 'soğutma üniteleri', 'not' => array( 'soğutucu birimler', 'serinletme üniteleri' ) ),
	array( 'en' => 'refrigeration', 'tr' => 'soğutma', 'not' => array( 'buzdolabı', 'frijider', 'dondurma' ) ),
	array( 'en' => 'transmission', 'tr' => 'şanzıman', 'not' => array( 'transmisyon', 'aktarım', 'iletim' ) ),
	array( 'en' => 'transmission shafts', 'tr' => 'şanzıman milleri', 'not' => array( 'transmisyon milleri', 'aktarma şaftları' ) ),
	array( 'en' => 'powertrain', 'tr' => 'güç aktarma organları', 'not' => array( 'güç treni', 'güç aktarması', 'motor treni' ) ),
	array( 'en' => 'propulsion', 'tr' => 'tahrik', 'not' => array( 'itki', 'sevk', 'ilerletme' ) ),
	array( 'en' => 'propulsion & powertrain', 'tr' => 'tahrik ve güç aktarma organları', 'not' => array( 'itki ve güç aktarma organları', 'itki ve güç treni' ) ),
	array( 'en' => 'e-axle', 'tr' => 'e-aks', 'not' => array( 'elektrikli dingil', 'e-dingil' ) ),
	array( 'en' => 'axle', 'tr' => 'aks', 'not' => array( 'dingil', 'mihver' ) ),
	array( 'en' => 'axle balancing machine', 'tr' => 'aks balans makinesi', 'not' => array( 'dingil dengeleme makinesi', 'aks dengeleme makinesi' ) ),
	array( 'en' => 'third member', 'tr' => 'diferansiyel gövdesi', 'not' => array( 'üçüncü üye', 'üçüncü eleman', 'üçüncü aza' ) ),
	array( 'en' => 'half case', 'tr' => 'yarım gövde', 'not' => array( 'yarım kasa', 'yarım dava', 'yarım kutu' ) ),
	array( 'en' => 'differential case', 'tr' => 'diferansiyel gövdesi', 'not' => array( 'diferansiyel kasası', 'diferansiyel davası' ) ),
	array( 'en' => 'beam axle', 'tr' => 'tek parça aks', 'not' => array( 'ışın aks', 'kiriş dingili', 'ışın dingili' ) ),
	array( 'en' => 'front strut', 'tr' => 'ön amortisör kolonu', 'not' => array( 'ön direk', 'ön kelepçe', 'ön sütun' ) ),
	array( 'en' => 'hub', 'tr' => 'poyra', 'not' => array( 'göbek', 'merkez yuvası', 'kapı' ) ),
	array( 'en' => 'wheel aligner', 'tr' => 'ön düzen ayar cihazı', 'not' => array( 'tekerlek hizalayıcı', 'jant ayarlayıcı' ) ),
	array( 'en' => 'wheel alignment', 'tr' => 'ön düzen ayarı', 'not' => array( 'tekerlek hizalaması', 'jant hizalama' ) ),
	array( 'en' => 'headlight aiming', 'tr' => 'far ayarı', 'not' => array( 'far nişan alma', 'projektör hedefleme' ) ),
	array( 'en' => 'ADAS alignment', 'tr' => 'ADAS kalibrasyonu', 'not' => array( 'ADAS hizalaması', 'ADAS ayarlaması', 'ADAS düzenlemesi' ) ),
	array( 'en' => 'advanced driver assistance systems', 'tr' => 'gelişmiş sürücü destek sistemleri', 'not' => array( 'ileri sürücü yardım sistemleri', 'gelişmiş şoför destek sistemleri', 'ileri sürüş yardımcıları' ) ),
	array( 'en' => 'Adaptive Cruise Control', 'tr' => 'adaptif hız sabitleyici', 'not' => array( 'uyarlanabilir seyir kontrolü', 'adaptif yolculuk denetimi' ) ),
	array( 'en' => 'Lane Departure Warning', 'tr' => 'şerit ihlal uyarısı', 'not' => array( 'şerit ayrılma uyarısı', 'hat çıkış ikazı' ) ),
	array( 'en' => 'Head Up Display', 'tr' => 'ön cam bilgi ekranı', 'not' => array( 'baş yukarı gösterge', 'kafa üstü ekran' ) ),
	array( 'en' => 'Corner radar', 'tr' => 'Köşe radarı', 'not' => array( 'Viraj radarı', 'Dönüş radarı' ) ),
	array( 'en' => 'Night vision', 'tr' => 'Gece görüşü', 'not' => array( 'Gece vizyonu', 'Karanlık görüntüsü' ) ),
	array( 'en' => 'Area view camera', 'tr' => 'Çevre görüş kamerası', 'not' => array( 'Alan görüntü kamerası', 'Bölge izleme kamerası' ) ),
	array( 'en' => 'control module', 'tr' => 'kontrol ünitesi', 'not' => array( 'denetim modülü', 'kumanda kutusu' ) ),
	array( 'en' => 'control', 'tr' => 'kontrol', 'not' => array( 'denetleme', 'teftiş', 'murakabe' ) ),
	array( 'en' => 'controls', 'tr' => 'kontrol sistemleri', 'not' => array( 'denetimler', 'kumandalar', 'kontroller' ) ),
	array( 'en' => 'blank ECM', 'tr' => 'boş ECM', 'not' => array( 'kör ECM', 'beyaz ECM' ) ),
	array( 'en' => 'restbus simulation', 'tr' => 'artık veri yolu simülasyonu', 'not' => array( 'dinlenme otobüsü simülasyonu', 'rest bus benzetimi' ) ),
	array( 'en' => 'drivability', 'tr' => 'sürüş kalitesi', 'not' => array( 'sürülebilirlik', 'araba kullanılabilirliği' ) ),
	array( 'en' => 'gear shift calibration', 'tr' => 'vites geçiş kalibrasyonu', 'not' => array( 'dişli kaydırma ayarı', 'vites değiştirme düzeltmesi' ) ),
	array( 'en' => 'traction battery', 'tr' => 'traksiyon akü paketi', 'not' => array( 'çekiş pili', 'çekiş bataryası', 'traksiyon pili' ) ),
	array( 'en' => 'dynamometer', 'tr' => 'dinamometre', 'not' => array( 'güç ölçer', 'dinamo' ) ),
	array( 'en' => 'chassis dynamometer', 'tr' => '2 ve 4 tekerlekli şasi dinamometresi', 'not' => array( '2 ve 4 akslı şasi dinamometresi', 'iki ve dört dingilli dinamometre' ) ),
	array( 'en' => 'inline dyno', 'tr' => 'hat içi dinamometre', 'not' => array( 'satır içi dinamometre', 'çizgi içi dinamometre' ) ),
	array( 'en' => 'two-wheel drive', 'tr' => 'iki tekerlekten çekişli', 'not' => array( 'çift tekerlek tahriki', 'iki koldan çekiş' ) ),
	array( 'en' => 'roller brake tester', 'tr' => 'rulolu fren test cihazı', 'not' => array( 'silindir fren testeri', 'merdaneli fren testeri', 'çubuklu fren testeri' ) ),
	array( 'en' => 'roller', 'tr' => 'rulo', 'not' => array( 'merdane', 'silindir', 'çubuk', 'oklava' ) ),
	array( 'en' => 'Side roller', 'tr' => 'Yan rulo', 'not' => array( 'Yan merdane', 'Yan silindir', 'Yan çubuk' ) ),
	array( 'en' => 'retaining rollers', 'tr' => 'tutucu rulolar', 'not' => array( 'tutma merdaneleri', 'alıkoyucu silindirler' ) ),
	array( 'en' => 'safety rollers', 'tr' => 'emniyet ruloları', 'not' => array( 'güvenlik merdaneleri', 'emniyet silindirleri' ) ),
	array( 'en' => 'Sensor roller', 'tr' => 'Sensör rulosu', 'not' => array( 'Algılayıcı merdane' ) ),
	array( 'en' => 'Twin roller machines', 'tr' => 'Çift rulolu makineler', 'not' => array( 'İkiz merdane makineleri', 'Çift silindirli makineler' ) ),
	array( 'en' => 'rattle and twist testing', 'tr' => 'gıcırtı ve burulma testi', 'not' => array( 'takırtı ve döndürme testi', 'çıngırak ve büküm testi', 'tıngırtı ve çevirme testi' ) ),
	array( 'en' => 'squeak & rattle testing', 'tr' => 'gıcırtı ve takırtı testi', 'not' => array( 'ötme ve çıngırak testi', 'cıyaklama ve tıngırtı testi' ) ),
	array( 'en' => 'cobblestone pattern', 'tr' => 'arnavut kaldırımı deseni', 'not' => array( 'kaldırım taşı örüntüsü', 'parke taşı şekli' ) ),
	array( 'en' => 'exhaust extraction', 'tr' => 'egzoz emişi', 'not' => array( 'egzoz çıkarma', 'egzoz çekme', 'egzoz ihracı' ) ),
	array( 'en' => 'Exhaust flap', 'tr' => 'Egzoz kapağı', 'not' => array( 'Egzoz kanadı', 'Egzoz perdesi' ) ),
	array( 'en' => 'end of line', 'tr' => 'hat sonu', 'not' => array( 'hattın sonu', 'üretim sonu', 'çizgi sonu', 'satır sonu' ) ),
	array( 'en' => 'end of line testing', 'tr' => 'hat sonu testi', 'not' => array( 'hattın sonu testi', 'üretim sonu denemesi' ) ),
	array( 'en' => 'end-of-line automation', 'tr' => 'hat sonu otomasyonu', 'not' => array( 'hattın sonu otomasyonu', 'üretim sonu otomasyonu' ) ),
	array( 'en' => 'bead seat optimizer', 'tr' => 'lastik topuk yatağı optimizasyonu', 'not' => array( 'boncuk koltuk eniyileyici', 'bijon yatağı ayarlayıcı' ) ),
	array( 'en' => 'bead breaking', 'tr' => 'lastik topuğu sökme', 'not' => array( 'boncuk kırma', 'kordon kırma', 'opaska kırma' ) ),
	array( 'en' => 'tire inflator', 'tr' => 'lastik şişirme ünitesi', 'not' => array( 'teker pompası', 'lastik havalandırıcı' ) ),
	array( 'en' => 'wheel assembly', 'tr' => 'tekerlek montajı', 'not' => array( 'jant düzeneği', 'çark toplama' ) ),
	array( 'en' => 'valve angles', 'tr' => 'sibop açıları', 'not' => array( 'valf açıları', 'supap köşeleri', 'vana açısı' ) ),
	array( 'en' => 'uniformity evaluation', 'tr' => 'düzgünlük değerlendirmesi', 'not' => array( 'üniformite tahmini', 'tekdüzelik sınaması' ) ),
	array( 'en' => 'force variation measurement', 'tr' => 'kuvvet değişimi ölçümü', 'not' => array( 'güç varyasyonu ölçümü' ) ),
	array( 'en' => 'adhesive weights', 'tr' => 'yapışkanlı balans ağırlıkları', 'not' => array( 'tutkal ağırlıkları', 'yapıştırıcı tartıları' ) ),
	array( 'en' => 'instrument cluster', 'tr' => 'gösterge paneli', 'not' => array( 'enstrüman paneli', 'alet kümesi', 'çalgı kümesi' ) ),
	array( 'en' => 'torque vectoring', 'tr' => 'tork vektörleme', 'not' => array( 'moment yönlendirme', 'burulma vektörü' ) ),
	array( 'en' => 'rolling torque', 'tr' => 'yuvarlanma torku', 'not' => array( 'döner moment', 'haddeleme momenti' ) ),
	array( 'en' => 'valve body unit', 'tr' => 'valf gövdesi ünitesi', 'not' => array( 'supap bedeni birimi', 'vana vücudu ünitesi' ) ),
	array( 'en' => 'power drive units', 'tr' => 'güç tahrik üniteleri', 'not' => array( 'güç sürücü birimleri', 'kuvvet sürüş üniteleri' ) ),
	array( 'en' => 'actuation systems', 'tr' => 'aktüatör sistemleri', 'not' => array( 'aktüasyon sistemleri', 'harekete geçirme sistemleri' ) ),
	array( 'en' => 'commercial vehicle', 'tr' => 'ticari araç', 'not' => array( 'tecim taşıtı', 'ticaret arabası' ) ),
	array( 'en' => 'off-highway', 'tr' => 'karayolu dışı', 'not' => array( 'otoyol dışı', 'şose dışı' ) ),
	array( 'en' => 'Vehicle guiding', 'tr' => 'Araç yönlendirme', 'not' => array( 'Taşıt kılavuzlama', 'Araba güdümü' ) ),
	array( 'en' => 'Vehicle detection', 'tr' => 'Araç algılama', 'not' => array( 'Taşıt tespiti', 'Araba keşfi' ) ),
	array( 'en' => 'energy recuperation', 'tr' => 'enerji geri kazanımı', 'not' => array( 'enerji rekuperasyonu', 'enerji iyileştirme' ) ),
	array( 'en' => 'mill roll', 'tr' => 'hadde merdanesi', 'not' => array( 'değirmen rulosu', 'fabrika silindiri', 'değirmen merdanesi' ) ),
	array( 'en' => 'roll shop technologies', 'tr' => 'merdane atölyesi teknolojileri', 'not' => array( 'merdane işleme teknolojileri', 'merdane dükkânı teknolojileri', 'rulo mağazası teknolojileri' ) ),
	array( 'en' => 'roll inspection', 'tr' => 'merdane muayenesi', 'not' => array( 'rulo denetimi', 'merdane incelemesi', 'silindir kontrolü' ) ),
	array( 'en' => 'roll grinding machines', 'tr' => 'merdane taşlama makineleri', 'not' => array( 'merdane öğütme makineleri', 'rulo bileme makineleri' ) ),
	array( 'en' => 'roll grinder', 'tr' => 'merdane taşlama makinesi', 'not' => array( 'merdane öğütücüsü', 'rulo bileyicisi' ) ),
	array( 'en' => 'grinding', 'tr' => 'taşlama', 'not' => array( 'öğütme', 'değirmenleme', 'bileme' ) ),
	array( 'en' => 'grinder control', 'tr' => 'taşlama makinesi kontrolü', 'not' => array( 'öğütücü kontrolü', 'öğütme denetimi' ) ),
	array( 'en' => 'automatic grinder control', 'tr' => 'otomatik taşlama makinesi kontrolü', 'not' => array( 'otomatik öğütücü kontrolü', 'otomatik öğütme denetimi' ) ),
	array( 'en' => 'profile grinder control', 'tr' => 'profil taşlama makinesi kontrolü', 'not' => array( 'profil öğütücü kontrolü' ) ),
	array( 'en' => 'Grinding Technology', 'tr' => 'Taşlama teknolojisi', 'not' => array( 'Öğütme teknolojisi', 'Bileme teknolojisi' ) ),
	array( 'en' => 'infeed', 'tr' => 'dalma ilerlemesi', 'not' => array( 'besleme içi', 'iç akış', 'giriş beslemesi' ) ),
	array( 'en' => 'rotary diamond dressing', 'tr' => 'döner elmasla bileme', 'not' => array( 'dönel elmas giydirme', 'rotatif elmas terbiyesi' ) ),
	array( 'en' => 'reconditioning', 'tr' => 'yenileme', 'not' => array( 'şartlandırma', 'iyileştirme', 'yeniden düzenleme' ) ),
	array( 'en' => 'roll texturing', 'tr' => 'merdane tekstürleme', 'not' => array( 'merdane doku işleme', 'rulo dokulama' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'tr' => 'elektro erozyonla tekstürleme (EDT)', 'not' => array( 'elektriksel deşarj dokulama', 'elektriksel erozyon teknolojisi', 'elektrik boşalma dokuması' ) ),
	array( 'en' => 'rolling mill', 'tr' => 'hadde tezgâhı', 'not' => array( 'haddeleme değirmeni', 'yuvarlama fabrikası', 'silindir değirmeni' ) ),
	array( 'en' => 'Cold and Hot Rolling Mills', 'tr' => 'Soğuk ve sıcak hadde tezgâhları', 'not' => array( 'Soğuk ve Sıcak Haddeleme Değirmenleri', 'Soğuk ve sıcak yuvarlama fabrikaları' ) ),
	array( 'en' => '20-high / six-high mill', 'tr' => '20 merdaneli / altı merdaneli hadde tezgâhı', 'not' => array( 'yirmi yüzlü değirmen', 'altı yükseklikli fabrika' ) ),
	array( 'en' => 'cold pilger mill', 'tr' => 'soğuk pilger tezgâhı', 'not' => array( 'soğuk hacı değirmeni' ) ),
	array( 'en' => 'strip', 'tr' => 'şerit', 'not' => array( 'bant', 'kuşak', 'soyma' ) ),
	array( 'en' => 'Strip Lines', 'tr' => 'Şerit hatları', 'not' => array( 'Bant çizgileri', 'Sac hatları', 'Şerit çizgileri' ) ),
	array( 'en' => 'blast furnace', 'tr' => 'yüksek fırın', 'not' => array( 'patlama fırını', 'üfleme ocağı' ) ),
	array( 'en' => 'tap hole', 'tr' => 'döküm deliği', 'not' => array( 'musluk deliği', 'çeşme ağzı', 'vana deliği' ) ),
	array( 'en' => 'clay gun', 'tr' => 'döküm deliği tıkama makinesi', 'not' => array( 'kil tabancası', 'balçık silahı', 'çamur şekillendirme makinesi' ) ),
	array( 'en' => 'mudding system (HDD)', 'tr' => 'çamur besleme sistemi', 'not' => array( 'bulaştırma sistemi', 'çamurlama düzeni' ) ),
	array( 'en' => 'tin plating', 'tr' => 'kalaylama', 'not' => array( 'çinko kaplama', 'teneke kaplama', 'galvanizleme' ) ),
	array( 'en' => 'spalls', 'tr' => 'yüzey dökülmeleri', 'not' => array( 'kabuklanmalar', 'soyulmalar', 'yontular' ) ),
	array( 'en' => 'pinches & bruises', 'tr' => 'sıkışma ve ezik izleri', 'not' => array( 'çimdikler ve morluklar', 'sıkıştırmalar ve berelenmeler' ) ),
	array( 'en' => 'surface separations', 'tr' => 'yüzey ayrılmaları', 'not' => array( 'satıh bölünmeleri', 'yüzey boşanmaları' ) ),
	array( 'en' => 'eddy current technology', 'tr' => 'girdap akımı teknolojisi', 'not' => array( 'burgaç akımı teknolojisi', 'anafor akımı teknolojisi', 'güncel teknoloji' ) ),
	array( 'en' => 'debonding', 'tr' => 'yapışma kaybı (debonding)', 'not' => array( 'delaminasyon', 'bağ kopması', 'ayrışma' ) ),
	array( 'en' => 'probe alignment', 'tr' => 'prob hizalaması', 'not' => array( 'sonda ayarı', 'iğne dizilimi' ) ),
	array( 'en' => 'Detection Focus', 'tr' => 'Tespit edilen kusur türleri', 'not' => array( 'Tespit Odağı', 'Algılama Merkezi' ) ),
	array( 'en' => 'forged rolls', 'tr' => 'dövme merdaneler', 'not' => array( 'sahte rulolar', 'dövülmüş silindirler', 'taklit merdaneler' ) ),
	array( 'en' => 'Conveyor and Paper Rolls', 'tr' => 'Konveyör ve kâğıt merdaneleri', 'not' => array( 'Taşıyıcı ve kâğıt ruloları', 'Konveyör ve kâğıt tomarları' ) ),
	array( 'en' => 'water meter', 'tr' => 'su sayacı', 'not' => array( 'su ölçer', 'su metresi' ) ),
	array( 'en' => 'machine tools', 'tr' => 'takım tezgâhları', 'not' => array( 'makine araçları', 'makine takımları', 'makine aletleri', 'makine edevatı' ) ),
	array( 'en' => 'machining cell', 'tr' => 'işleme hücresi', 'not' => array( 'makineleme kabini', 'talaş hücresi' ) ),
	array( 'en' => 'boring', 'tr' => 'delik büyütme', 'not' => array( 'delme', 'sondaj', 'sıkma', 'can sıkıntısı' ) ),
	array( 'en' => 'horizontal boring machine', 'tr' => 'yatay borverk tezgâhı', 'not' => array( 'yatay delme makinesi', 'yatay sondaj makinesi', 'yatay sıkıcı makine' ) ),
	array( 'en' => 'boring drill (HDD)', 'tr' => 'yatay yönlü sondaj makinesi', 'not' => array( 'sıkıcı matkap', 'delme matkabı' ) ),
	array( 'en' => 'deep hole drilling', 'tr' => 'derin delik delme', 'not' => array( 'derin çukur sondajı', 'derin oyuk açma' ) ),
	array( 'en' => 'gundrill', 'tr' => 'tabanca matkabı', 'not' => array( 'silah matkabı', 'tüfek delici' ) ),
	array( 'en' => 'crankshaft lathe', 'tr' => 'krank mili tornası', 'not' => array( 'krank mili çarkı', 'krank tezgâhı' ) ),
	array( 'en' => 'collet chuck', 'tr' => 'pens mandren', 'not' => array( 'bilezik ayna', 'halka kavrama' ) ),
	array( 'en' => '3-jaw chuck', 'tr' => 'üç ayaklı ayna', 'not' => array( 'üç çeneli mandren', 'üç ağızlı kavrama' ) ),
	array( 'en' => 'motorized clamping', 'tr' => 'motorlu bağlama', 'not' => array( 'motorize kelepçeleme', 'motorlu sıkıştırma' ) ),
	array( 'en' => 'in a single clamping', 'tr' => 'tek bağlamada', 'not' => array( 'tek kelepçede', 'tek sıkıştırmada', 'tek pensede' ) ),
	array( 'en' => 'custom fixturing', 'tr' => 'özel bağlama aparatı', 'not' => array( 'özel tutturma', 'özel sabitleme' ) ),
	array( 'en' => 'turret-style wheel head', 'tr' => 'taretli taşlama kafası', 'not' => array( 'kule tipi tekerlek başı' ) ),
	array( 'en' => 'superabrasives', 'tr' => 'süper abrazifler', 'not' => array( 'süperaşındırıcılar', 'üstün zımparalar' ) ),
	array( 'en' => 'chip vacuum', 'tr' => 'talaş emiş ünitesi', 'not' => array( 'çip vakumu', 'fiş süpürgesi', 'cips emicisi' ) ),
	array( 'en' => 'brushing-polishing machines', 'tr' => 'fırçalama ve parlatma makineleri', 'not' => array( 'fırçalama ve polisaj makineleri', 'süpürme ve cilalama makineleri' ) ),
	array( 'en' => 'keg', 'tr' => 'fıçı', 'not' => array( 'varil', 'kova', 'bidon' ) ),
	array( 'en' => 'keg finger holes', 'tr' => 'fıçı tutamak delikleri', 'not' => array( 'fıçı parmak boşlukları', 'varil parmak oyukları' ) ),
	array( 'en' => 'consumables', 'tr' => 'sarf malzemeleri', 'not' => array( 'tüketim malzemeleri', 'tüketilebilirler' ) ),
	array( 'en' => 'CMM quality', 'tr' => 'CMM kalite kontrolü', 'not' => array( 'CMM kalitesi', 'CMM niteliği' ) ),
	array( 'en' => 'motor grader', 'tr' => 'greyder', 'not' => array( 'motorlu düzleyici', 'toprak kopyalayıcı', 'yol düzleyici motoru' ) ),
	array( 'en' => 'excavator', 'tr' => 'ekskavatör', 'not' => array( 'kazıcı kopyalayıcı', 'hafriyatçı' ) ),
	array( 'en' => 'backhoe', 'tr' => 'kazıcı yükleyici', 'not' => array( 'arka kazma', 'geri çapa', 'arka kürek' ) ),
	array( 'en' => 'wheel loader', 'tr' => 'lastikli yükleyici', 'not' => array( 'tekerlek yükleyici', 'jant yükleyicisi' ) ),
	array( 'en' => 'baler', 'tr' => 'balya makinesi', 'not' => array( 'pres makinesi', 'presleyici', 'balyacı' ) ),
	array( 'en' => 'hay mower', 'tr' => 'ot biçme makinesi', 'not' => array( 'otçu makine', 'çayır kesici' ) ),
	array( 'en' => 'combine', 'tr' => 'biçerdöver', 'not' => array( 'kombine', 'birleştirici makine', 'birleşik hasatçı' ) ),
	array( 'en' => 'draper header', 'tr' => 'bantlı hasat başlığı', 'not' => array( 'draper başlığı', 'perde başlığı', 'gübre dağıtıcı' ) ),
	array( 'en' => 'sprayers', 'tr' => 'pülverizatörler', 'not' => array( 'püskürtücüler', 'spreyleyiciler', 'sprey makineleri' ) ),
	array( 'en' => 'implements', 'tr' => 'iş makinesi ekipmanları', 'not' => array( 'aletler ve ekipmanlar', 'icra araçları' ) ),
	array( 'en' => 'PTO', 'tr' => 'kuyruk mili (PTO)', 'not' => array( 'güç alıcı mili', 'güç çıkış alıcısı' ) ),
	array( 'en' => 'blade', 'tr' => 'greyder bıçağı', 'not' => array( 'lemiz', 'kanat', 'pala' ) ),
	array( 'en' => 'blade timing', 'tr' => 'bıçak hareket süresi', 'not' => array( 'bıçak zamanlaması', 'kanat zamanı' ) ),
	array( 'en' => 'movable cradle', 'tr' => 'hareketli kızak', 'not' => array( 'taşınabilir beşik', 'hareketli taban' ) ),
	array( 'en' => 'utilities construction', 'tr' => 'enerji ve altyapı tesisleri inşaatı', 'not' => array( 'kamu hizmetleri inşaatı', 'altyapı inşaatı' ) ),
	array( 'en' => 'aerospace', 'tr' => 'havacılık ve uzay', 'not' => array( 'hava boşluğu', 'uzay havacılığı' ) ),
	array( 'en' => 'Aerospace & industrials', 'tr' => 'Havacılık ve uzay ile sanayi', 'not' => array( 'Havacılık ve sanayi', 'Uzay ve endüstriyel', 'Havacılık ve endüstriyel', 'Lotarya ve sanayi' ) ),
	array( 'en' => 'rotor wing aircraft', 'tr' => 'döner kanatlı hava aracı', 'not' => array( 'pervaneli uçaklar', 'rotor kanatlı uçak', 'helikopter uçakları' ) ),
	array( 'en' => 'air cycle machines', 'tr' => 'hava devirdaim makineleri', 'not' => array( 'hava çevrim makineleri', 'hava döngü aletleri' ) ),
	array( 'en' => 'HMU/FMU', 'tr' => 'HMU/FMU', 'not' => array( 'hidrolik/pnömatik cihazlar', 'hidrolik ve pnömatik üniteler' ) ),
	array( 'en' => 'engine software loaders', 'tr' => 'motor yazılımı yükleyicileri', 'not' => array( 'motor yükleyen programlar', 'motorları yükleyen yazılımlar' ) ),
	array( 'en' => 'lube & scavenge pumps', 'tr' => 'yağlama ve yağ tahliye pompaları', 'not' => array( 'yağlama ve havalandırma pompaları', 'yağlama ve süpürme pompaları' ) ),
	array( 'en' => 'landing gear systems', 'tr' => 'iniş takımı sistemleri', 'not' => array( 'iniş dişli sistemleri', 'iniş vitesi sistemleri' ) ),
	array( 'en' => 'cargo loading systems', 'tr' => 'kargo yükleme sistemleri', 'not' => array( 'yük yükleme düzenekleri' ) ),
	array( 'en' => 'EMC darkroom', 'tr' => 'EMC karanlık odası', 'not' => array( 'EMC fotoğraf odası' ) ),
	array( 'en' => 'Ascential', 'tr' => 'Ascential', 'not' => array( 'Asansiyel' ) ),
	array( 'en' => 'Ascential Technologies', 'tr' => 'Ascential Technologies', 'not' => array( 'Ascential Teknolojileri', 'Ascential Teknoloji' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'tr' => 'Ascential Test & Measurement', 'not' => array( 'Ascential Test ve Ölçüm', 'Ascential Test ve Ölçüm Sistemleri', 'Ascential Ölçüm Sistemleri' ) ),
	array( 'en' => 'Ascential Care', 'tr' => 'Ascential Care', 'not' => array( 'Ascential Bakım', 'Ascential Destek', 'Ascential Özen' ) ),
	array( 'en' => 'Ascentialytics', 'tr' => 'Ascentialytics', 'not' => array( 'Ascential Analitik', 'Ascential Analiz' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'tr' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL TIP VE YAŞAM BİLİMLERİ', 'ASCENTIAL MEDİKAL VE YAŞAM BİLİMLERİ' ) ),
	array( 'en' => 'Burke Porter', 'tr' => 'Burke Porter', 'not' => array( 'Burke Hamal', 'Burke Taşıyıcı' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'tr' => 'Burke E. Porter Machinery', 'not' => array( 'Burke E. Porter Makineleri', 'Burke Porter Makineleri', 'Burke Porter makineleri' ) ),
	array( 'en' => 'Burke Porter Group', 'tr' => 'Burke Porter Group', 'not' => array( 'Burke Porter Grubu' ) ),
	array( 'en' => 'Universal Balancing', 'tr' => 'Universal Balancing', 'not' => array( 'Evrensel Balanslama', 'Evrensel balanslama', 'Universal Balanslama' ) ),
	array( 'en' => 'XL Machine', 'tr' => 'XL Machine', 'not' => array( 'XL Makine', 'XL Makinesi' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'tr' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht ve Ortakları Ltd.', 'H. Kleinknecht ve Şirketi A.Ş.' ) ),
	array( 'en' => 'Cimat', 'tr' => 'Cimat', 'not' => array( 'Çimat' ) ),
	array( 'en' => 'Lismar', 'tr' => 'Lismar', 'not' => array( 'Lişmar' ) ),
	array( 'en' => 'Titan', 'tr' => 'Titan', 'not' => array( 'Titan Devi' ) ),
	array( 'en' => 'Galileo', 'tr' => 'Galileo', 'not' => array( 'Galile' ) ),
	array( 'en' => 'Sentia', 'tr' => 'Sentia', 'not' => array( 'Sentya' ) ),
	array( 'en' => 'WinterPark', 'tr' => 'WinterPark', 'not' => array( 'Kış Parkı', 'Winter Park', 'Kışpark' ) ),
	array( 'en' => 'Bauer', 'tr' => 'Bauer', 'not' => array( 'Bauer\'li' ) ),
	array( 'en' => 'ADAS Garage', 'tr' => 'ADAS Garage', 'not' => array( 'ADAS Garajı', 'ADAS garajı' ) ),
	array( 'en' => 'Ask Burke Porter', 'tr' => 'Ask Burke Porter', 'not' => array( 'Burke Porter\'a Sorun', 'Burke Porter\'a Sor' ) ),
	array( 'en' => 'eRotor', 'tr' => 'eRotor', 'not' => array( 'e-Rotor', 'elektrikli rotor' ) ),
	array( 'en' => 'CMT-TR Polimer', 'tr' => 'CMT-TR Polimer', 'not' => array( 'CMT-TR polimer rotorları', 'polimer rotor CMT-TR' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'tr' => 'Turbo Test Duo Expert', 'not' => array( 'Turbo Test Duo Uzmanı', 'Uzman TURBO TEST DUO', 'TURBO TEST DUO Uzman' ) ),
	array( 'en' => 'First Alert Monitoring System', 'tr' => 'First Alert izleme sistemi', 'not' => array( 'İlk Uyarı İzleme Sistemi', 'birinci alarm gözetim sistemi' ) ),
	array( 'en' => 'Calibration-as-a-Service™ (CaaS™)', 'tr' => 'Calibration-as-a-Service™ (CaaS™)', 'not' => array( 'Hizmet Olarak Kalibrasyon™', 'Kalibrasyon Hizmeti™' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'tr' => 'ADVANCING THE MACHINE', 'not' => array( 'MAKİNEYİ İLERLETMEK', 'MAKİNEYİ GELİŞTİRMEK' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'tr' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( 'TOPLAM TİCARİLEŞTİRME ÇÖZÜMLERİ', 'TAM TİCARİLEŞME ÇÖZÜMLERİ' ) ),
	array( 'en' => 'A DESIGN / B LOGO', 'tr' => 'A DESIGN / B LOGO', 'not' => array( 'A TASARIM / B LOGO', 'TASARIM A / LOGO B' ) ),
	array( 'en' => 'Marketplace', 'tr' => 'Marketplace', 'not' => array( 'Pazar', 'Pazar yeri', 'Pazaryeri', 'Piyasa' ) ),
	array( 'en' => 'Medical', 'tr' => 'Medikal', 'not' => array( 'Tıbbi', 'Medikal olan' ) ),
	array( 'en' => 'life sciences', 'tr' => 'yaşam bilimleri', 'not' => array( 'doğa bilimleri', 'hayat bilimi', 'tabiat bilimleri' ) ),
	array( 'en' => 'Bristol', 'tr' => 'Bristol', 'not' => array( 'Bristol şehri', 'Bristol kenti' ) ),
	array( 'en' => 'Poland', 'tr' => 'Polonya', 'not' => array( 'Poland', 'Lehistan' ) ),
	array( 'en' => 'England', 'tr' => 'İngiltere', 'not' => array( 'England', 'Britanya adası' ) ),
	array( 'en' => 'West Flanders', 'tr' => 'Batı Flandre', 'not' => array( 'West Flanders', 'Batı Flanders' ) ),
	array( 'en' => 'Netherlands', 'tr' => 'Hollanda', 'not' => array( 'Netherlands', 'Nederland', 'Aşağı Ülkeler' ) ),
	array( 'en' => 'Americas', 'tr' => 'Amerika kıtası', 'not' => array( 'Amerika', 'Amerikalar' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'tr' => 'naamloze vennootschap (NV)', 'not' => array( 'anonim şirket (NV)', 'isimsiz ortaklık' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'tr' => 'Crossroads Bank for Enterprises', 'not' => array( 'İşletmeler için Kavşak Bankası', 'Girişimler Kesişim Bankası' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'tr' => 'KvK (Kamer van Koophandel)', 'not' => array( 'KvK (Ticaret Odası)' ) ),
	array( 'en' => 'applications', 'tr' => 'uygulamalar', 'not' => array( 'aplikasyonlar', 'başvurular', 'müracaatlar' ) ),
	array( 'en' => 'design', 'tr' => 'tasarım', 'not' => array( 'proje', 'dizayn', 'çizim' ) ),
	array( 'en' => 'operations', 'tr' => 'operasyonlar', 'not' => array( 'ameliyatlar', 'cerrahi işlemler' ) ),
	array( 'en' => 'responsive', 'tr' => 'hızlı yanıt veren', 'not' => array( 'duyarlı', 'responsive', 'tepkisel' ) ),
	array( 'en' => 'asset', 'tr' => 'ekipman', 'not' => array( 'varlık', 'aktif', 'kıymet' ) ),
	array( 'en' => 'embedded', 'tr' => 'hat içi', 'not' => array( 'gömülü', 'yerleşik', 'saplanmış' ) ),
	array( 'en' => 'performance', 'tr' => 'performans', 'not' => array( 'icra', 'gösteri', 'temsil' ) ),
	array( 'en' => 'insights', 'tr' => 'içgörüler', 'not' => array( 'kavrayışlar', 'anlayışlar', 'sezgiler' ) ),
	array( 'en' => 'actionable insights', 'tr' => 'eyleme dönüştürülebilir içgörüler', 'not' => array( 'uygulanabilir analizler', 'faydalı fikirler', 'işlenebilir görüşler' ) ),
	array( 'en' => 'expert insights', 'tr' => 'uzman içgörüleri', 'not' => array( 'uzman analizleri', 'bilirkişi kavrayışları' ) ),
	array( 'en' => 'analytics', 'tr' => 'analitik', 'not' => array( 'analizler', 'çözümlemeler', 'tahliller' ) ),
	array( 'en' => 'throughput', 'tr' => 'üretim hızı', 'not' => array( 'verim', 'geçiş', 'iş çıkarma' ) ),
	array( 'en' => 'uptime across systems', 'tr' => 'sistemler genelinde çalışma süresi', 'not' => array( 'sistemlerde ayakta kalma', 'sistemler boyunca açık kalma' ) ),
	array( 'en' => 'cycle time', 'tr' => 'çevrim süresi', 'not' => array( 'döngü süresi', 'devir zamanı' ) ),
	array( 'en' => 'setup cycles', 'tr' => 'kurulum çevrimleri', 'not' => array( 'ayar döngüleri', 'kuruluş devirleri' ) ),
	array( 'en' => 'soak time', 'tr' => 'bekletme süresi', 'not' => array( 'ıslatma zamanı', 'emdirme süresi' ) ),
	array( 'en' => 'idle duration', 'tr' => 'rölanti süresi', 'not' => array( 'boş kalma süresi', 'tembellik süresi' ) ),
	array( 'en' => 'footprint', 'tr' => 'yer kaplama alanı', 'not' => array( 'ayak izi', 'ayak basımı' ) ),
	array( 'en' => 'factory floor', 'tr' => 'üretim sahası', 'not' => array( 'fabrika zemini', 'fabrika katı' ) ),
	array( 'en' => 'field agents', 'tr' => 'saha ekipleri', 'not' => array( 'alan ajanları', 'tarla temsilcileri' ) ),
	array( 'en' => 'site visit', 'tr' => 'saha ziyareti', 'not' => array( 'site ziyareti', 'yer gezisi' ) ),
	array( 'en' => 'failure rates', 'tr' => 'arıza oranları', 'not' => array( 'başarısızlık oranları', 'çöküş hızları' ) ),
	array( 'en' => 'health checks', 'tr' => 'durum kontrolleri', 'not' => array( 'sağlık muayeneleri', 'sıhhat testleri' ) ),
	array( 'en' => 'maintenance contracts', 'tr' => 'bakım sözleşmeleri', 'not' => array( 'tamir mukaveleleri', 'idame kontratları' ) ),
	array( 'en' => 'MRO', 'tr' => 'MRO', 'not' => array( 'bakım, tamir ve çalıştırma' ) ),
	array( 'en' => 'obsolescence management', 'tr' => 'eskime yönetimi', 'not' => array( 'demode olma idaresi', 'modası geçme yönetimi' ) ),
	array( 'en' => 'commissioning', 'tr' => 'devreye alma', 'not' => array( 'komisyonlama', 'görevlendirme', 'sipariş etme' ) ),
	array( 'en' => 'turnkey', 'tr' => 'anahtar teslim', 'not' => array( 'döner anahtar', 'anahtarlı' ) ),
	array( 'en' => 'stand-alone machine', 'tr' => 'bağımsız makine', 'not' => array( 'tek başına duran makine', 'müstakil aygıt' ) ),
	array( 'en' => 'capital equipment', 'tr' => 'yatırım malı ekipman', 'not' => array( 'sermaye donanımı', 'başkent ekipmanı' ) ),
	array( 'en' => 'warranty coverage', 'tr' => 'garanti kapsamı', 'not' => array( 'garanti sigortası', 'teminat örtüsü' ) ),
	array( 'en' => 'sales inquiry', 'tr' => 'satış talebi', 'not' => array( 'satış sorgulaması', 'satış soruşturması' ) ),
	array( 'en' => 'opportunities', 'tr' => 'fırsatlar', 'not' => array( 'oportünistler', 'şanslar' ) ),
	array( 'en' => 'peers', 'tr' => 'emsal kuruluşlar', 'not' => array( 'akranlar', 'eşitler', 'lortlar' ) ),
	array( 'en' => 'like-minded companies', 'tr' => 'benzer vizyona sahip şirketler', 'not' => array( 'aynı fikirli firmalar', 'benzer zihinli kumpanyalar' ) ),
	array( 'en' => 'Leadership', 'tr' => 'Yönetim ekibi', 'not' => array( 'Liderlik', 'Önderlik', 'Kadro' ) ),
	array( 'en' => 'President', 'tr' => 'Başkan', 'not' => array( 'Cumhurbaşkanı', 'Reis', 'Devlet Başkanı' ) ),
	array( 'en' => 'Board Member', 'tr' => 'Yönetim kurulu üyesi', 'not' => array( 'Tahta üyesi', 'Kurul azası', 'Pano üyesi' ) ),
	array( 'en' => 'Principal', 'tr' => 'Principal', 'not' => array( 'Müdür', 'Baş yetkili', 'Prensip', 'Okul müdürü' ) ),
	array( 'en' => 'associate attorney', 'tr' => 'avukat yardımcısı', 'not' => array( 'ortak avukat', 'vekil yardımcı' ) ),
	array( 'en' => 'Corporate Roles', 'tr' => 'Kurumsal görevler', 'not' => array( 'Şirket rolleri', 'Kurumsal roller' ) ),
	array( 'en' => 'machinist', 'tr' => 'tornacı', 'not' => array( 'makinist', 'makine mühendisi' ) ),
	array( 'en' => 'service professional', 'tr' => 'servis uzmanı', 'not' => array( 'hizmet profesyoneli', 'servis mesleği' ) ),
	array( 'en' => 'high-performance teams', 'tr' => 'yüksek performanslı ekipler', 'not' => array( 'yüksek başarım takımları' ) ),
	array( 'en' => 'right-shoring', 'tr' => 'right-shoring', 'not' => array( 'doğru kıyıya taşıma', 'sağ kıyılama' ) ),
	array( 'en' => 'tariffs', 'tr' => 'gümrük vergileri', 'not' => array( 'tarifeler', 'ücret listeleri' ) ),
	array( 'en' => 'landed cost model', 'tr' => 'toplam ithalat maliyeti modeli', 'not' => array( 'iniş maliyeti modeli', 'konmuş maliyet modeli' ) ),
	array( 'en' => 'customer journey', 'tr' => 'müşteri yolculuğu', 'not' => array( 'müşteri seyahati', 'müşteri gezisi' ) ),
	array( 'en' => 'deployment', 'tr' => 'devreye alma', 'not' => array( 'konuşlandırma', 'dağıtım', 'yayılma' ) ),
	array( 'en' => 'Standardization at scale', 'tr' => 'Büyük ölçekte standartlaşma', 'not' => array( 'Ölçekte standardizasyon', 'Terazide standartlaştırma' ) ),
	array( 'en' => 'volume flexibility', 'tr' => 'hacim esnekliği', 'not' => array( 'ses esnekliği', 'cilt esnekliği' ) ),
	array( 'en' => 'high-mix, low-volume', 'tr' => 'çok çeşitli, düşük hacimli', 'not' => array( 'yüksek karışım, düşük ses' ) ),
	array( 'en' => 'high production / high-volume production', 'tr' => 'yüksek hacimli üretim', 'not' => array( 'yüksek imalat', 'yüksek sesli üretim' ) ),
	array( 'en' => 'discrete industries', 'tr' => 'parça imalat sektörleri', 'not' => array( 'ayrık endüstriler', 'kesikli sanayiler', 'gizli sektörler' ) ),
	array( 'en' => 'marine', 'tr' => 'denizcilik', 'not' => array( 'deniz piyade', 'bahriye' ) ),
	array( 'en' => 'validate performance', 'tr' => 'performansı doğrulamak', 'not' => array( 'performansı geçerli kılmak', 'başarımı tasdik etmek' ) ),
	array( 'en' => 'defensible', 'tr' => 'savunulabilir', 'not' => array( 'müdafaalı', 'korunaklı' ) ),
	array( 'en' => 'traceable tests', 'tr' => 'izlenebilir testler', 'not' => array( 'takip edilebilir denemeler', 'sürülebilir testler' ) ),
	array( 'en' => 'reportable', 'tr' => 'raporlanabilir', 'not' => array( 'ihbar edilebilir', 'bildirimli' ) ),
	array( 'en' => 'patented', 'tr' => 'patentli', 'not' => array( 'patentlenmiş olan', 'beratlı' ) ),
	array( 'en' => 'infinitely variable', 'tr' => 'kademesiz ayarlanabilir', 'not' => array( 'sonsuz değişken', 'sınırsız oynak' ) ),
	array( 'en' => 'ultra-stable design', 'tr' => 'ultra kararlı tasarım', 'not' => array( 'aşırı dengeli proje', 'ultra sabit dizayn' ) ),
	array( 'en' => 'represent', 'tr' => 'modellemek', 'not' => array( 'temsil etmek', 'vekâlet etmek' ) ),
	array( 'en' => 'mental health care', 'tr' => 'ruh sağlığı hizmeti', 'not' => array( 'zihinsel sağlık', 'uzaktan sağlık hizmeti', 'akıl bakımı' ) ),
	array( 'en' => 'disability insurance', 'tr' => 'engellilik sigortası', 'not' => array( 'sakatlık teminatı', 'maluliyet örtüsü' ) ),
	array( 'en' => 'fluid power', 'tr' => 'akışkan güç', 'not' => array( 'sıvı kuvvet', 'hidrolik enerji' ) ),
	array( 'en' => 'hydraulic pilot', 'tr' => 'hidrolik pilot kumanda', 'not' => array( 'hidrolik pilot kişisi', 'hidrolik uzaktan kumanda' ) ),
	array( 'en' => 'load sense signal', 'tr' => 'load-sense sinyali', 'not' => array( 'yük duyarga işareti', 'yük hissi sinyali' ) ),
	array( 'en' => 'stem stickiness', 'tr' => 'supap mili sıkışması', 'not' => array( 'gövde viskozitesi', 'mil yapışkanlığı', 'sap kıvamı' ) ),
	array( 'en' => 'thrust force / pullback force', 'tr' => 'itme kuvveti / geri çekme kuvveti', 'not' => array( 'eksenel kuvvet', 'sevk gücü' ) ),
	array( 'en' => 'heavy-duty', 'tr' => 'ağır hizmet tipi', 'not' => array( 'ağır görevli', 'ağır vazifeli' ) ),
	array( 'en' => 'kinetostatics', 'tr' => 'kinetostatik', 'not' => array( 'hareket durağanlığı' ) ),
	array( 'en' => 'drift', 'tr' => 'kayma', 'not' => array( 'sürüklenme', 'rüzgâr kayması' ) ),
	array( 'en' => 'snubber', 'tr' => 'sönümleyici', 'not' => array( 'burun kıvırıcı', 'azarlayıcı' ) ),
	array( 'en' => 'cushion testing', 'tr' => 'yastıklama testi', 'not' => array( 'minder denemesi', 'koltuk testi' ) ),
	array( 'en' => 'active part probing', 'tr' => 'aktif parça yoklaması', 'not' => array( 'etkin kısım sondalaması' ) ),
	array( 'en' => 'aperture plate', 'tr' => 'diyafram plakası', 'not' => array( 'açıklık tabağı', 'delik levhası' ) ),
	array( 'en' => 'anchoring', 'tr' => 'temel ankrajı', 'not' => array( 'çapalama', 'demirleme' ) ),
	array( 'en' => 'bore axis alignment', 'tr' => 'delik ekseni hizalaması', 'not' => array( 'sıkıcı eksen ayarı' ) ),
	array( 'en' => 'automated handling cells', 'tr' => 'otomatik taşıma hücreleri', 'not' => array( 'otomatikleştirilmiş elleçleme kabinleri' ) ),
	array( 'en' => 'process recipe', 'tr' => 'proses reçetesi', 'not' => array( 'işlem yemek tarifi', 'süreç tarifi' ) ),
	array( 'en' => 'higher-level control system', 'tr' => 'üst seviye kontrol sistemi', 'not' => array( 'daha yüksek denetim sistemi' ) ),
	array( 'en' => 'special test facilities', 'tr' => 'özel test tesisleri', 'not' => array( 'hususi deneme kolaylıkları' ) ),
	array( 'en' => 'single bay', 'tr' => 'tek gözlü bölme', 'not' => array( 'tek koy', 'tek defne' ) ),
	array( 'en' => 'tension', 'tr' => 'gerginlik', 'not' => array( 'stres', 'tansiyon', 'gerilim hattı' ) ),
	array( 'en' => 'lubrication', 'tr' => 'yağlama', 'not' => array( 'kayganlaştırma', 'gresleme' ) ),
	array( 'en' => 'oil drain', 'tr' => 'yağ tahliyesi', 'not' => array( 'yağ havalandırması', 'yağ lavabosu' ) ),
	array( 'en' => 'LPM', 'tr' => 'l/dk', 'not' => array( 'dakikada litreler' ) ),
	array( 'en' => 'WCAG four principles', 'tr' => 'WCAG dört ilkesi', 'not' => array( 'WCAG dört prensibi' ) ),
	array( 'en' => 'Browse catalog', 'tr' => 'Kataloğu inceleyin', 'not' => array( 'Katalog', 'Kataloğu keşfedin', 'Kataloğa göz atın' ) ),
	array( 'en' => 'Explore the Catalog', 'tr' => 'Kataloğu inceleyin', 'not' => array( 'Kataloğu Keşfedin', 'Katalog' ) ),
	array( 'en' => 'Explore Our Product Catalog', 'tr' => 'Ürün kataloğumuzu inceleyin', 'not' => array( 'Ürün Kataloğumuzu Keşfedin', 'Ürün kataloğu' ) ),
	array( 'en' => 'View full catalog', 'tr' => 'Tüm kataloğu görün', 'not' => array( 'Tam katalog', 'Bütün kataloğa bakın' ) ),
	array( 'en' => 'Browse all resources', 'tr' => 'Tüm kaynakları inceleyin', 'not' => array( 'Tüm kaynaklar', 'Bütün kaynaklara göz atın' ) ),
	array( 'en' => 'Explore', 'tr' => 'İnceleyin', 'not' => array( 'Keşfedin', 'Araştırın' ) ),
	array( 'en' => 'Download', 'tr' => 'İndirin', 'not' => array( 'İndirme', 'Yükleyin', 'Yükleme' ) ),
	array( 'en' => 'Download brochure', 'tr' => 'Broşürü indirin', 'not' => array( 'Broşür indirme', 'Broşür yüklemesi' ) ),
	array( 'en' => 'Learn more', 'tr' => 'Daha fazla bilgi', 'not' => array( 'Daha fazla öğrenin', 'Daha çok öğrenin' ) ),
	array( 'en' => 'Read more', 'tr' => 'Devamını okuyun', 'not' => array( 'Daha fazla okuyun', 'Devamı' ) ),
	array( 'en' => 'Read the article', 'tr' => 'Makaleyi okuyun', 'not' => array( 'Makale okuma', 'Yazıyı okuyun' ) ),
	array( 'en' => 'Read announcement', 'tr' => 'Duyuruyu okuyun', 'not' => array( 'Duyuru okuma', 'İlanı okuyun' ) ),
	array( 'en' => 'View all press releases', 'tr' => 'Tüm basın bültenlerini görün', 'not' => array( 'Bütün basın bültenleri', 'Tüm basın açıklamaları' ) ),
	array( 'en' => 'Request a quote', 'tr' => 'Teklif isteyin', 'not' => array( 'Teklif talebi', 'Teklif istemek', 'Fiyat sorma' ) ),
	array( 'en' => 'Get a quote', 'tr' => 'Teklif alın', 'not' => array( 'Teklif alma', 'Fiyat alımı' ) ),
	array( 'en' => 'Request a demo', 'tr' => 'Demo talep edin', 'not' => array( 'Demo talebi', 'Demo isteme', 'Gösterim talebi' ) ),
	array( 'en' => 'Book a demo', 'tr' => 'Demo talep edin', 'not' => array( 'Demo rezervasyonu', 'Demo ayırtma' ) ),
	array( 'en' => 'Contact us', 'tr' => 'Bize ulaşın', 'not' => array( 'İletişim', 'Bizimle temas', 'İrtibat' ) ),
	array( 'en' => 'Speak to an expert', 'tr' => 'Bir uzmanla görüşün', 'not' => array( 'Uzmanla konuşma', 'Bir uzmana danışma' ) ),
	array( 'en' => 'Speak to a solutions expert', 'tr' => 'Bir çözüm uzmanıyla görüşün', 'not' => array( 'Çözüm uzmanıyla konuşma' ) ),
	array( 'en' => 'Submit a support request', 'tr' => 'Destek talebi gönderin', 'not' => array( 'Destek talebini gönderin', 'Destek isteği yollama' ) ),
	array( 'en' => 'Sign up', 'tr' => 'Kayıt olun', 'not' => array( 'Kayıt', 'İşaret edin', 'Üyelik' ) ),
	array( 'en' => 'Register', 'tr' => 'Sicil', 'not' => array( 'Kaydolun' ) ),
	array( 'en' => 'Log in', 'tr' => 'Giriş yapın', 'not' => array( 'Giriş', 'Oturum açma' ) ),
	array( 'en' => 'Search', 'tr' => 'Ara', 'not' => array( 'Arama', 'Araştırın', 'Arayın' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'tr' => 'ascentialtech.com\'da arama yapılıyor', 'not' => array( 'ascentialtech.com araştırılıyor', 'Ara ascentialtech.com' ) ),
	array( 'en' => 'Skip to content', 'tr' => 'İçeriğe geçin', 'not' => array( 'İçeriğe atlayın', 'Muhteviyata geçin' ) ),
	array( 'en' => 'Close Menu', 'tr' => 'Menüyü kapatın', 'not' => array( 'Menü kapatma', 'Menüyü kapama' ) ),
	array( 'en' => 'Stay connected', 'tr' => 'Bizi takip edin', 'not' => array( 'Bağlantıda kalın', 'Bağlı kalın', 'Hatta kalın' ) ),
	array( 'en' => 'Connect on LinkedIn', 'tr' => 'LinkedIn\'de takip edin', 'not' => array( 'LinkedIn\'de bağlanın', 'LinkedIn\'de bağlantı kurun' ) ),
	array( 'en' => 'Play', 'tr' => 'Oynat', 'not' => array( 'Oyna', 'Oyun' ) ),
	array( 'en' => 'Listen to this article', 'tr' => 'Bu makaleyi dinleyin', 'not' => array( 'Bu yazıyı dinleme' ) ),
	array( 'en' => 'Unsubscribe', 'tr' => 'Abonelikten çıkın', 'not' => array( 'Abonelikten çıkma', 'Üyelikten ayrılma' ) ),
	array( 'en' => 'Overview', 'tr' => 'Genel Bakış', 'not' => array( 'Genel görünüm', 'Özet bakış' ) ),
	array( 'en' => 'features', 'tr' => 'özellikler', 'not' => array( 'nitelikler', 'hususiyetler' ) ),
	array( 'en' => 'Key Features', 'tr' => 'Temel Özellikler', 'not' => array( 'Anahtar özellikler', 'Kilit nitelikler' ) ),
	array( 'en' => 'Specifications', 'tr' => 'Teknik özellikler', 'not' => array( 'Spesifikasyonlar', 'Şartnameler' ) ),
	array( 'en' => 'Gallery', 'tr' => 'Galeri', 'not' => array( 'Sergi', 'Resimlik' ) ),
	array( 'en' => 'Resources', 'tr' => 'Kaynaklar', 'not' => array( 'Kaynakça', 'Varlıklar' ) ),
	array( 'en' => 'Resource hub', 'tr' => 'Kaynak merkezi', 'not' => array( 'Kaynaklar merkezi', 'Kaynak yuvası' ) ),
	array( 'en' => 'Related Resources', 'tr' => 'İlgili Kaynaklar', 'not' => array( 'Alakalı kaynakça', 'Bağlantılı varlıklar' ) ),
	array( 'en' => 'Related Products', 'tr' => 'İlgili Ürünler', 'not' => array( 'Alakalı ürünler', 'Bağlantılı mamuller' ) ),
	array( 'en' => 'Frequently asked questions', 'tr' => 'Sık sorulan sorular', 'not' => array( 'Sıkça sorulan sorular', 'Çok sorulan sorular' ) ),
	array( 'en' => 'Popular products', 'tr' => 'Popüler ürünler', 'not' => array( 'Sevilen ürünler', 'Rağbet gören ürünler' ) ),
	array( 'en' => 'Trending products', 'tr' => 'Öne çıkan ürünler', 'not' => array( 'Trend ürünler', 'Moda ürünler' ) ),
	array( 'en' => 'News and announcements', 'tr' => 'Haberler ve duyurular', 'not' => array( 'Haber ve ilanlar', 'Havadis ve tebliğler' ) ),
	array( 'en' => 'press release', 'tr' => 'basın bülteni', 'not' => array( 'basın duyurusu', 'basın ilanı', 'basın açıklaması' ) ),
	array( 'en' => 'events & conferences', 'tr' => 'etkinlikler ve konferanslar', 'not' => array( 'olaylar ve toplantılar', 'vakalar ve kongreler' ) ),
	array( 'en' => 'Schedule a meeting', 'tr' => 'Toplantı planlayın', 'not' => array( 'Toplantı planlama', 'Randevu ayarlama' ) ),
	array( 'en' => 'whitepaper', 'tr' => 'teknik rapor', 'not' => array( 'beyaz kâğıt', 'beyaz kitap', 'beyaz rapor' ) ),
	array( 'en' => 'case study', 'tr' => 'vaka çalışması', 'not' => array( 'örnek olay incelemesi', 'dava çalışması' ) ),
	array( 'en' => 'eBooks', 'tr' => 'E-kitaplar', 'not' => array( 'e-Kitap', 'elektronik kitaplar' ) ),
	array( 'en' => 'Webinars', 'tr' => 'Web seminerleri', 'not' => array( 'Webinarlar', 'İnternet seminerleri' ) ),
	array( 'en' => 'Certificates', 'tr' => 'Sertifikalar', 'not' => array( 'Belgeler', 'Şahadetnameler' ) ),
	array( 'en' => 'Brochures', 'tr' => 'Broşürler', 'not' => array( 'Kitapçıklar', 'Prospektüsler' ) ),
	array( 'en' => 'Filter by category', 'tr' => 'Kategoriye göre filtreleyin', 'not' => array( 'Kategoriye göre filtreleme', 'Kategori süzgeci' ) ),
	array( 'en' => 'Clear all filters', 'tr' => 'Tüm filtreleri temizleyin', 'not' => array( 'Tüm filtreleri temizleme', 'Süzgeçleri silme' ) ),
	array( 'en' => 'Expand all', 'tr' => 'Tümünü genişletin', 'not' => array( 'Tümünü genişletme', 'Hepsini açma' ) ),
	array( 'en' => 'Select an option', 'tr' => 'Bir seçenek belirleyin', 'not' => array( 'Bir seçenek belirleme', 'Seçenek seçimi' ) ),
	array( 'en' => 'Select your support team', 'tr' => 'Destek ekibinizi seçin', 'not' => array( 'Destek takımı seçimi', 'Destek ekibini seçme' ) ),
	array( 'en' => 'Attach files (optional)', 'tr' => 'Dosya ekleyin (isteğe bağlı)', 'not' => array( 'Dosya ekleme (opsiyonel)', 'Dosya iliştirme (seçmeli)' ) ),
	array( 'en' => 'Contact name', 'tr' => 'Ad Soyad', 'not' => array( 'İletişim adı', 'Temas ismi', 'Kontak adı' ) ),
	array( 'en' => 'Country', 'tr' => 'Ülke', 'not' => array( 'Memleket', 'Diyar' ) ),
	array( 'en' => 'Intervention time (in business hours)', 'tr' => 'Müdahale süresi (iş saatleri içinde)', 'not' => array( 'Girişim zamanı', 'Araya girme süresi' ) ),
	array( 'en' => 'Remote support', 'tr' => 'Uzaktan destek', 'not' => array( 'Mesafeli destek', 'Uzak yardım' ) ),
	array( 'en' => 'Labour & Travel', 'tr' => 'İşçilik ve seyahat', 'not' => array( 'Emek ve gezi', 'İş gücü ve yolculuk' ) ),
	array( 'en' => 'Material / parts', 'tr' => 'Malzeme / parça', 'not' => array( 'Madde / kısımlar', 'Materyal / adetler' ) ),
	array( 'en' => 'Customer portal', 'tr' => 'Müşteri portalı', 'not' => array( 'Müşteri kapısı', 'Alıcı portalı' ) ),
	array( 'en' => 'Instructor-led training', 'tr' => 'Eğitmenli eğitim', 'not' => array( 'Öğretmen liderliğinde eğitim', 'Hoca güdümlü kurs' ) ),
	array( 'en' => 'Core / Plus / Elite', 'tr' => 'Core / Plus / Elite', 'not' => array( 'Çekirdek / Artı / Seçkin', 'Çekirdek / Plus / Elite' ) ),
	array( 'en' => 'learning management system (LMS)', 'tr' => 'öğrenme yönetim sistemi (LMS)', 'not' => array( 'ders idare sistemi', 'öğrenim müdürlük sistemi' ) ),
	array( 'en' => 'Terms', 'tr' => 'Kullanım koşulları', 'not' => array( 'Koşullar', 'Şartlar', 'Vadeler' ) ),
	array( 'en' => 'privacy policy', 'tr' => 'Gizlilik politikası', 'not' => array( 'Mahremiyet siyaseti', 'Özel hayat politikası' ) ),
	array( 'en' => 'Imprint', 'tr' => 'Künye', 'not' => array( 'Yasal uyarı', 'Damga', 'Baskı' ) ),
	array( 'en' => 'corporate information', 'tr' => 'Kurumsal bilgiler', 'not' => array( 'Şirket enformasyonu', 'Tüzel bilgiler' ) ),
	array( 'en' => 'Email Disclosure', 'tr' => 'E-posta bildirimi', 'not' => array( 'E-posta İfşası', 'Elektronik mektup açıklaması' ) ),
	array( 'en' => 'Trademarks', 'tr' => 'Ticari markalar', 'not' => array( 'Alameti farikalar', 'Tescilli işaretler' ) ),
	array( 'en' => 'Deliverables', 'tr' => 'Teslim edilecek işler', 'not' => array( 'Teslimatlar', 'Dağıtılabilirler', 'Teslim edilebilirler' ) ),
	array( 'en' => 'Work Product', 'tr' => 'İş Ürünü', 'not' => array( 'Çalışma Mahsulü', 'Emek Ürünü', 'Çalışma Sonucu' ) ),
	array( 'en' => 'WHEREAS', 'tr' => 'ŞÖYLE Kİ', 'not' => array( 'OYSA Kİ', 'BUNA KARŞILIK', 'İKEN' ) ),
	array( 'en' => 'RECITALS', 'tr' => 'GİRİŞ HÜKÜMLERİ', 'not' => array( 'NAKİLLER', 'OKUMALAR', 'ANLATIMLAR' ) ),
	array( 'en' => 'Exhibit', 'tr' => 'Ek', 'not' => array( 'Sergi', 'Teşhir', 'Delil' ) ),
	array( 'en' => 'Section', 'tr' => 'Madde', 'not' => array( 'Kısım', 'Kesit' ) ),
	array( 'en' => 'Name:', 'tr' => 'Ad Soyad:', 'not' => array( 'İsim:', 'Nam:', 'Unvan:' ) ),
	array( 'en' => 'Date:', 'tr' => 'Tarih:', 'not' => array( 'Veriler:', 'Hurma:', 'Bilgiler:' ) ),
	array( 'en' => 'Registered office', 'tr' => 'Kayıtlı merkez', 'not' => array( 'Tescilli ofis', 'Kaydolmuş büro' ) ),
	array( 'en' => 'Ascential Indemnity', 'tr' => 'Ascential Tazminat Taahhüdü', 'not' => array( 'Ascential Sigortası', 'Ascential Garantisi' ) ),
	array( 'en' => 'For Immediate Release', 'tr' => 'Yayın için', 'not' => array( 'Acil Yayın İçin', 'Derhal Serbest Bırakma' ) ),
	array( 'en' => 'Introducing', 'tr' => 'Tanıtıyoruz', 'not' => array( 'Yenilik', 'Takdim', 'Tanıştırma' ) ),
	array( 'en' => 'is now', 'tr' => 'yeni adıyla', 'not' => array( 'artık', 'şu anda', 'şimdi' ) ),
	array( 'en' => 'Powered by', 'tr' => '... tarafından desteklenmektedir', 'not' => array( '... ile güçlendirilmiştir', '... tarafından beslenir' ) ),
	array( 'en' => 'Addresses', 'tr' => 'ele alır', 'not' => array( 'ortadan kaldırır', 'yok eder', 'giderir', 'eleminasyon' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'tr' => 'Altyapınızı yükseltmeye hazır mısınız?', 'not' => array( 'Altyapını yükseltmeye hazır mısın?', 'Altyapı yükseltmesine hazır mı?' ) ),
	array( 'en' => 'Calendar View Unavailable', 'tr' => 'Takvim görünümü kullanılamıyor', 'not' => array( 'Takvim Görünümü Mevcut Değil', 'Takvim bakışı erişilemez' ) ),
	array( 'en' => 'and more', 'tr' => 've daha fazlası', 'not' => array( 've daha çok', 've fazlası' ) ),
	array( 'en' => 'and counting', 'tr' => 've artmaya devam ediyor', 'not' => array( 've sayısı artıyor', 've sayılıyor' ) ),
	array( 'en' => 'a wide range of', 'tr' => 'çok çeşitli', 'not' => array( 'geniş bir yelpazede', 'geniş bir aralıkta' ) ),
	array( 'en' => 'end-to-end', 'tr' => 'uçtan uca', 'not' => array( 'kapsamlı', 'baştan sona' ) ),
	array( 'en' => 'real-time', 'tr' => 'gerçek zamanlı', 'not' => array( 'reel zamanlı', 'anlık vakitli' ) ),
	array( 'en' => 'built to last', 'tr' => 'uzun ömürlü olacak şekilde üretilmiş', 'not' => array( 'son sürmek için inşa edilmiş', 'dayanmak için yapılmış' ) ),
	array( 'en' => 'seamless link', 'tr' => 'kesintisiz bağlantı', 'not' => array( 'dikişsiz link', 'pürüzsüz halka' ) ),
	array( 'en' => 'unbeatable deals', 'tr' => 'kaçırılmayacak fırsatlar', 'not' => array( 'yenilmez anlaşmalar', 'dövülemez teklifler' ) ),
	array( 'en' => 'fully loaded test', 'tr' => 'tam yüklü test', 'not' => array( 'tamamen dolu deneme', 'bütünüyle yüklenmiş test' ) ),
	array( 'en' => 'fixed stations', 'tr' => 'sabit istasyonlar', 'not' => array( 'tespit edilmiş duraklar', 'onarılmış istasyonlar' ) ),
	array( 'en' => 'mobile carousels', 'tr' => 'hareketli karuseller', 'not' => array( 'gezici atlıkarıncalar', 'mobil dönme dolaplar' ) ),
	array( 'en' => 'testing', 'tr' => 'test', 'not' => array( 'deneme', 'sınama', 'tecrübe' ) ),
	array( 'en' => 'Products', 'tr' => 'Ürünler', 'not' => array( 'Mamuller', 'Mahsuller' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'tr' => 'Dinamik turboşarj akış tezgâhı', 'not' => array( 'Dinamik akış tezgâhı', 'Dinamik turbo flow bankı' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'tr' => 'Birleşik yüksek hızlı ve düşük hızlı kartuş balans makinesi', 'not' => array( 'Yüksek hızlı ve düşük hızlı çekirdek dengeleme makinesi kombinasyonu' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'tr' => 'İş makinesi ekipmanları - hat sonu', 'not' => array( 'Aletler ve ekipmanlar - hat sonu', 'Uygulamalar - üretim hattı sonu' ) ),
	array( 'en' => 'Share', 'tr' => 'Paylaşın', 'not' => array( 'Paylaşım', 'Paylaş' ) ),
	array( 'en' => 'Copy link', 'tr' => 'Bağlantıyı kopyalayın', 'not' => array( 'Bağlantı kopyalama', 'Linki kopyala' ) ),
	array( 'en' => 'chapters', 'tr' => 'bölüm', 'not' => array( 'fasıl', 'kısımlar' ) ),
	array( 'en' => 'radial run-out', 'tr' => 'radyal salgı', 'not' => array( 'radyal kaçış', 'yarıçap bitişi' ) ),
	array( 'en' => 'test stands', 'tr' => 'test tezgâhları', 'not' => array( 'test bankları', 'deneme sıraları', 'test tribünleri' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'tr' => 'soğutucu akışkan dolum broşürü', 'not' => array( 'Soğutma Dolum Broşürü', 'soğutucu şarj kitapçığı' ) ),
	array( 'en' => 'Priority 1: High priority', 'tr' => 'Öncelik 1: Yüksek öncelik', 'not' => array( '1. Öncelik: Yüksek', 'Birinci sıra: yüksek' ) ),
	array( 'en' => 'Priority 2: Medium priority', 'tr' => 'Öncelik 2: Orta öncelik', 'not' => array( '2. Öncelik: Orta', 'İkinci sıra: orta' ) ),
	array( 'en' => 'Priority 3: Low priority / routine', 'tr' => 'Öncelik 3: Düşük öncelik / rutin', 'not' => array( '3. Öncelik: Alçak', 'Üçüncü sıra: düşük' ) ),
);
