<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/*
 * Simplified Chinese term base (en -> zh). Enforced by ACWPT_Terms: relevant rows are
 * sent with each batch, and any output containing a 'not' form is retried and never
 * stored. Sources: the English concept list this site uses, plus a live sample of 19
 * /zh/ pages (catalog index, precision balancing, turbo balancers, gas management &
 * refrigeration, metals automation, roll shop, NDT, end-of-line automation,
 * propulsion & powertrain, care, resource hub, leadership, press releases, trademarks,
 * sprayers, motor graders, cerberus-x1, rotor balancing machines), 2026-09-25.
 */
return array(
	array( 'en' => '*', 'zh' => '全站使用正式的商务书面语，以第二人称敬称「您」称呼读者，并在每一个字符串中保持一致：正文、标题、眉题、通栏大写标语、按钮、表单标签、占位符、alt 与 aria 文本、<title>、meta 描述、og: 标签与 JSON-LD 一律如此。语域是整个页面的属性，而不是单个片段的属性——meta 描述里出现随意的第二人称，就与它一起发布的敬称正文自相矛盾。多位读者仍用单数敬称，不得生造复数敬称形式。按钮与链接标签遵循中文网页惯例：保留英文的动词，写成简短的动宾式，不加句号，且不含人称代词——Browse catalog 是「浏览产品目录」，Download 是「下载」，Request a demo 是「申请演示」，Contact us 是「联系我们」；绝不把动词标签压缩成光秃秃的名词（「产品目录」「下载中心」不能用作上述标签）。敬辞「垂询」只出现在公司口吻的邀请句中，绝不出现在可点击的标签、标签页或选项值上。', 'not' => array( '你的', '你们', '你可以', '你需要', '你将', '你能', '你是', '你有', '为你', '给你', '帮你', '让你', '跟你', '对你', '你自己', '您们', '咱们' ) ),
	array( 'en' => 'Ascential Technologies', 'zh' => 'Ascential Technologies', 'not' => array( 'Ascential 科技公司', '阿森蒂尔' ) ),
	array( 'en' => 'Ascential Test & Measurement', 'zh' => 'Ascential Test & Measurement', 'not' => array( 'Ascential 测试与测量公司', 'Ascential 测量系统公司' ) ),
	array( 'en' => 'Ascential Care', 'zh' => 'Ascential Care', 'not' => array( 'Ascential 关怀', 'Ascential 客户关怀服务' ) ),
	array( 'en' => 'Ascentialytics', 'zh' => 'Ascentialytics', 'not' => array( 'Ascential 分析平台', 'Ascential 数据分析' ) ),
	array( 'en' => 'Burke E. Porter Machinery', 'zh' => 'Burke E. Porter Machinery', 'not' => array( 'Burke E. Porter 机械公司', 'Burke Porter 机械' ) ),
	array( 'en' => 'Burke Porter Group', 'zh' => 'Burke Porter Group', 'not' => array( 'Burke Porter 集团', 'Burke Porter 公司集团' ) ),
	array( 'en' => 'Burke Porter', 'zh' => 'Burke Porter', 'not' => array( '伯克波特', '伯克·波特' ) ),
	array( 'en' => 'H. Kleinknecht & Co. GmbH', 'zh' => 'H. Kleinknecht & Co. GmbH', 'not' => array( 'H. Kleinknecht 有限公司', 'Kleinknecht 有限责任公司' ) ),
	array( 'en' => 'Universal Balancing', 'zh' => 'Universal Balancing', 'not' => array( '通用动平衡', '万能动平衡', '通用平衡公司' ) ),
	array( 'en' => 'XL Machine', 'zh' => 'XL Machine', 'not' => array( 'XL 机器', 'XL 机床', 'XL 机械' ) ),
	array( 'en' => 'WinterPark', 'zh' => 'WinterPark', 'not' => array( '冬季公园', '温特帕克' ) ),
	array( 'en' => 'ADAS Garage', 'zh' => 'ADAS Garage', 'not' => array( 'ADAS 车库', 'ADAS 维修间' ) ),
	array( 'en' => 'Titan', 'zh' => 'Titan', 'not' => array( '泰坦系统', '巨人系统' ) ),
	array( 'en' => 'Sentia', 'zh' => 'Sentia', 'not' => array() ),
	array( 'en' => 'Galileo', 'zh' => 'Galileo', 'not' => array() ),
	array( 'en' => 'Cimat', 'zh' => 'Cimat', 'not' => array() ),
	array( 'en' => 'Lismar', 'zh' => 'Lismar', 'not' => array() ),
	array( 'en' => 'Kleinknecht', 'zh' => 'Kleinknecht', 'not' => array( '克莱内克特' ) ),
	array( 'en' => 'Bauer', 'zh' => 'Bauer', 'not' => array( '鲍尔公司' ) ),
	array( 'en' => 'eRotor', 'zh' => 'eRotor', 'not' => array( '电动转子', '电动车转子系列' ) ),
	array( 'en' => 'CMT-TR Polimer', 'zh' => 'CMT-TR Polimer', 'not' => array( '聚合物转子动平衡机', 'CMT-TR 聚合物' ) ),
	array( 'en' => 'Turbo Test Duo Expert', 'zh' => 'Turbo Test Duo Expert', 'not' => array( 'Turbo Test Duo 专家', '涡轮测试双专家' ) ),
	array( 'en' => 'Cerberus X1', 'zh' => 'Cerberus X1', 'not' => array( '刻耳柏洛斯 X1' ) ),
	array( 'en' => 'ProbHe', 'zh' => 'ProbHe', 'not' => array( '氦气探测仪', '氦气检漏仪' ) ),
	array( 'en' => 'datames', 'zh' => 'datames', 'not' => array( '达特梅斯' ) ),
	array( 'en' => 'First Alert Monitoring System', 'zh' => 'First Alert 预警监测系统', 'not' => array( '一级警报监控系统', '首次警报监测系统' ) ),
	array( 'en' => 'Calibration-as-a-Service (CaaS)', 'zh' => 'Calibration-as-a-Service（CaaS）', 'not' => array( '校准即服务', '校准作为服务' ) ),
	array( 'en' => 'ADVANCING THE MACHINE', 'zh' => 'ADVANCING THE MACHINE', 'not' => array( '推动机器前进', '让机器更先进' ) ),
	array( 'en' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'zh' => 'ASCENTIAL MEDICAL & LIFE SCIENCES', 'not' => array( 'ASCENTIAL 医疗与生命科学', 'Ascential 医疗与生命科学部' ) ),
	array( 'en' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'zh' => 'TOTAL COMMERCIALIZATION SOLUTIONS', 'not' => array( '全面商业化解决方案', '整体商业化方案' ) ),
	array( 'en' => 'A DESIGN', 'zh' => 'A DESIGN', 'not' => array( 'A 设计', 'A 图样' ) ),
	array( 'en' => 'B LOGO', 'zh' => 'B LOGO', 'not' => array( 'B 标识', 'B 徽标' ) ),
	array( 'en' => 'Impossible? Done.', 'zh' => 'Impossible? Done.', 'not' => array( '不可能？已完成。', '不可能？做到了。' ) ),
	array( 'en' => 'Ask Burke Porter', 'zh' => 'Ask Burke Porter', 'not' => array( '询问 Burke Porter', '问问 Burke Porter' ) ),
	array( 'en' => 'Marketplace', 'zh' => '备件商城', 'not' => array( '备件市场', '在线市场', '交易市场' ) ),
	array( 'en' => 'Explore', 'zh' => '探索', 'not' => array() ),
	array( 'en' => 'Browse catalog', 'zh' => '浏览产品目录', 'not' => array( '查看目录', '产品目录一览' ) ),
	array( 'en' => 'Explore the Catalog', 'zh' => '浏览产品目录', 'not' => array( '探索目录', '目录一览' ) ),
	array( 'en' => 'Browse all resources', 'zh' => '浏览全部资源', 'not' => array( '所有资源一览' ) ),
	array( 'en' => 'Read the article', 'zh' => '阅读全文', 'not' => array( '阅读这篇文章', '读一读文章' ) ),
	array( 'en' => 'Listen to this article', 'zh' => '收听本文', 'not' => array( '听这篇文章', '收听这篇文章' ) ),
	array( 'en' => 'Play', 'zh' => '播放', 'not' => array( '开始游戏' ) ),
	array( 'en' => 'Share', 'zh' => '分享', 'not' => array( '共享出去' ) ),
	array( 'en' => 'Copy link', 'zh' => '复制链接', 'not' => array( '拷贝链接', '复制网址' ) ),
	array( 'en' => 'Searching ascentialtech.com', 'zh' => '在 ascentialtech.com 中搜索', 'not' => array( '正在搜索 ascentialtech.com', '搜索中 ascentialtech.com' ) ),
	array( 'en' => 'Calendar View Unavailable', 'zh' => '日历视图不可用', 'not' => array( '日程视图无法使用', '日历检视不可用' ) ),
	array( 'en' => 'Ready to upgrade your infrastructure?', 'zh' => '是否准备升级您的基础设施？', 'not' => array( '准备升级你的基础设施吗？', '准备好升级基础架构了吗？' ) ),
	array( 'en' => 'sales inquiry', 'zh' => '销售咨询', 'not' => array( '销售垂询', '销售询价', '业务垂询' ) ),
	array( 'en' => 'Priority 1', 'zh' => '优先级 1：高', 'not' => array( '第一优先级' ) ),
	array( 'en' => 'Priority 2', 'zh' => '优先级 2：中', 'not' => array( '第二优先级' ) ),
	array( 'en' => 'Priority 3', 'zh' => '优先级 3：低', 'not' => array( '第三优先级' ) ),
	array( 'en' => 'For Immediate Release', 'zh' => '即日发布', 'not' => array( '立即发布', '立即释放', '即刻发布' ) ),
	array( 'en' => 'Introducing', 'zh' => '全新推出', 'not' => array( '介绍一下', '引入介绍' ) ),
	array( 'en' => 'is now', 'zh' => '现已更名为', 'not' => array( '现已推出', '现已上市' ) ),
	array( 'en' => 'Addresses', 'zh' => '应对', 'not' => array( '彻底消除', '全面消除' ) ),
	array( 'en' => 'Leadership', 'zh' => '领导团队', 'not' => array( '高层管理者队伍', '管理层人员' ) ),
	array( 'en' => 'Board Member', 'zh' => '董事会成员', 'not' => array( '董事会会员', '理事会成员' ) ),
	array( 'en' => 'Principal', 'zh' => 'Principal', 'not' => array( '主要负责人', '首席投资负责人' ) ),
	array( 'en' => 'President', 'zh' => '总裁', 'not' => array( '公司总统', '总统先生' ) ),
	array( 'en' => 'Corporate Roles', 'zh' => '集团职能岗位', 'not' => array( '公司角色', '企业角色' ) ),
	array( 'en' => 'Connect on LinkedIn', 'zh' => '在 LinkedIn 上联系', 'not' => array( 'Connect on LinkedIn', 'LinkedIn 连接' ) ),
	array( 'en' => 'Deliverables', 'zh' => '交付成果', 'not' => array( '可交付物', '应交付项目', '交付物件' ) ),
	array( 'en' => 'Work Product', 'zh' => '工作成果', 'not' => array( '劳动产品', '工作产品' ) ),
	array( 'en' => 'WHEREAS', 'zh' => '鉴于', 'not' => array() ),
	array( 'en' => 'RECITALS', 'zh' => '鉴于条款', 'not' => array( '朗诵部分', '陈述朗读' ) ),
	array( 'en' => 'Section', 'zh' => '条款', 'not' => array( '章节部分', '小节内容' ) ),
	array( 'en' => 'Exhibit', 'zh' => '附件', 'not' => array() ),
	array( 'en' => 'Name:', 'zh' => '姓名：', 'not' => array( '公司名称：', '名字叫作：' ) ),
	array( 'en' => 'Date:', 'zh' => '日期：', 'not' => array() ),
	array( 'en' => 'Registered office', 'zh' => '注册地址', 'not' => array( '已注册办公室', '登记办公处' ) ),
	array( 'en' => 'Register', 'zh' => '登记机关', 'not' => array( '立即注册', '注册账户' ) ),
	array( 'en' => 'Crossroads Bank for Enterprises', 'zh' => '比利时企业注册登记库', 'not' => array( '十字路口银行', '企业十字路口银行' ) ),
	array( 'en' => 'KvK (Kamer van Koophandel)', 'zh' => '荷兰商会（KvK）', 'not' => array( '荷兰贸易局', '荷兰工商登记局' ) ),
	array( 'en' => 'naamloze vennootschap (NV)', 'zh' => 'naamloze vennootschap（NV）', 'not' => array( '股份有限公司', '无名合伙企业' ) ),
	array( 'en' => 'Imprint', 'zh' => '法律声明', 'not' => array( '印记页面', '印刷信息', '版本说明' ) ),
	array( 'en' => 'Email Disclosure', 'zh' => '电子邮件免责声明', 'not' => array( '邮箱地址公开' ) ),
	array( 'en' => 'GDPR', 'zh' => 'GDPR', 'not' => array( '通用数据条例' ) ),
	array( 'en' => 'personal information', 'zh' => '个人信息', 'not' => array( '私人资料', '个人隐私资料' ) ),
	array( 'en' => 'WCAG four principles', 'zh' => '可感知、可操作、可理解、稳健', 'not' => array( '可察觉、可运作、可理解、稳定' ) ),
	array( 'en' => 'England', 'zh' => '英格兰', 'not' => array( '英国地区', '英伦地区' ) ),
	array( 'en' => 'West Flanders', 'zh' => '西佛兰德省', 'not' => array( '西弗兰德斯', '西部佛兰芒' ) ),
	array( 'en' => 'Poland', 'zh' => '波兰', 'not' => array(  ) ),
	array( 'en' => 'Netherlands', 'zh' => '荷兰', 'not' => array( '尼德兰王国' ) ),
	array( 'en' => 'Bristol', 'zh' => '布里斯托尔', 'not' => array( '布利斯托' ) ),
	array( 'en' => 'Labour & Travel', 'zh' => '工时与差旅', 'not' => array( '劳动与旅行', '劳务与旅游' ) ),
	array( 'en' => 'associate attorney', 'zh' => '助理律师', 'not' => array( '律师助理', '联合检察官' ) ),
	array( 'en' => 'disability insurance', 'zh' => '伤残保险', 'not' => array( '残疾人保险', '残障补助' ) ),
	array( 'en' => 'mental health care', 'zh' => '心理健康保障', 'not' => array( '远程医疗保健', '精神病治疗' ) ),
	array( 'en' => 'tariffs', 'zh' => '关税', 'not' => array( '资费标准', '费率表格' ) ),
	array( 'en' => 'warranty coverage', 'zh' => '保修范围', 'not' => array( '保险范围', '保险覆盖' ) ),
	array( 'en' => 'maintenance contracts', 'zh' => '维保合同', 'not' => array( '维护契约', '保养合约' ) ),
	array( 'en' => 'unbeatable deals', 'zh' => '超值优惠', 'not' => array( '无法击败的交易', '打不败的优惠' ) ),
	array( 'en' => 'like-minded companies', 'zh' => '志同道合的企业', 'not' => array( '想法相似的公司', '志趣相投的公司们' ) ),
	array( 'en' => 'peers', 'zh' => '同行', 'not' => array( '同龄人士', '同辈人员' ) ),
	array( 'en' => 'insights', 'zh' => '洞察', 'not' => array( '内窥视角', '深刻见地' ) ),
	array( 'en' => 'actionable insights', 'zh' => '可落地的洞察', 'not' => array( '可操作的见解', '可行动的洞见' ) ),
	array( 'en' => 'expert insights', 'zh' => '专家洞察', 'not' => array( '专家见解', '行家意见' ) ),
	array( 'en' => 'opportunities', 'zh' => '机遇', 'not' => array( '机会主义者', '投机人士' ) ),
	array( 'en' => 'operations', 'zh' => '运营', 'not' => array( '手术操作', '外科手术' ) ),
	array( 'en' => 'high-performance teams', 'zh' => '高绩效团队', 'not' => array( '高性能团队', '高效能机器团队' ) ),
	array( 'en' => 'customer journey', 'zh' => '合作历程', 'not' => array( '客户旅行', '顾客旅游' ) ),
	array( 'en' => 'events & conferences', 'zh' => '活动与会议', 'not' => array( '事件与会议', '事故与大会' ) ),
	array( 'en' => 'capital equipment', 'zh' => '资本设备', 'not' => array( '大写设备', '首都设备' ) ),
	array( 'en' => 'landed cost model', 'zh' => '到岸成本模型', 'not' => array( '落地成本模型', '着陆成本模型' ) ),
	array( 'en' => 'right-shoring', 'zh' => 'right-shoring', 'not' => array( '网络研讨会优化', '正确海岸化' ) ),
	array( 'en' => 'discrete industries', 'zh' => '离散制造行业', 'not' => array( '分散的行业', '谨慎行业' ) ),
	array( 'en' => 'defensible', 'zh' => '经得起审核的', 'not' => array( '可防御的', '可以辩护的' ) ),
	array( 'en' => 'reportable', 'zh' => '可归档备查的', 'not' => array( '可报告性的', '值得上报的' ) ),
	array( 'en' => 'traceable tests', 'zh' => '可溯源测试', 'not' => array( '可跟踪测试', '可追踪的考试' ) ),
	array( 'en' => 'validate performance', 'zh' => '验证性能', 'not' => array( '确认效率', '核实业绩' ) ),
	array( 'en' => 'fully loaded test', 'zh' => '满载试验', 'not' => array( '全面加载测试', '完整装载考核' ) ),
	array( 'en' => 'Standardization at scale', 'zh' => '规模化标准化', 'not' => array( '按比例标准化', '大小标准化' ) ),
	array( 'en' => 'volume flexibility', 'zh' => '批量柔性', 'not' => array( '音量灵活性', '体积弹性' ) ),
	array( 'en' => 'high-volume production', 'zh' => '大批量生产', 'not' => array( '高产量生产', '大量生产作业' ) ),
	array( 'en' => 'high-mix, low-volume', 'zh' => '多品种小批量', 'not' => array( '高混合低产量', '高混低量' ) ),
	array( 'en' => 'factory floor', 'zh' => '车间现场', 'not' => array( '工厂地板', '厂房地面' ) ),
	array( 'en' => 'footprint', 'zh' => '占地面积', 'not' => array( '脚印面积', '足迹大小' ) ),
	array( 'en' => 'built to last', 'zh' => '经久耐用', 'not' => array( '为持久而建造', '建造持久' ) ),
	array( 'en' => 'turnkey', 'zh' => '交钥匙', 'not' => array( '转动钥匙', '钥匙交付式' ) ),
	array( 'en' => 'stand-alone machine', 'zh' => '独立式机器', 'not' => array( '单独站立机器', '孤立机器' ) ),
	array( 'en' => 'site visit', 'zh' => '现场走访', 'not' => array( '网站访问', '站点浏览' ) ),
	array( 'en' => 'health checks', 'zh' => '设备状态检查', 'not' => array( '健康体检', '身体检查' ) ),
	array( 'en' => 'field agents', 'zh' => '现场服务工程师', 'not' => array( '现场代理人', '特工人员' ) ),
	array( 'en' => 'service professional', 'zh' => '服务技术专家', 'not' => array( '专业服务员', '服务专业人士' ) ),
	array( 'en' => 'machinist', 'zh' => '机加工技师', 'not' => array( '机器操作员', '机械操作工' ) ),
	array( 'en' => 'remanufacturers & rebuilders', 'zh' => '再制造与修复企业', 'not' => array( '再生产商与重建商', '重制造者与重建者' ) ),
	array( 'en' => 'remarketers', 'zh' => '二手设备经销商', 'not' => array( '再营销商', '重新营销者' ) ),
	array( 'en' => 'MRO', 'zh' => 'MRO', 'not' => array( '维修与备件业务' ) ),
	array( 'en' => 'learning management system (LMS)', 'zh' => '学习管理系统（LMS）', 'not' => array( '学习经营系统', '教学控制系统' ) ),
	array( 'en' => 'branch', 'zh' => '学习空间', 'not' => array( '分支店铺', '树枝节点' ) ),
	array( 'en' => 'obsolescence management', 'zh' => '元器件停产管理', 'not' => array( '过时管理', '老化管理', '陈旧过时处理' ) ),
	array( 'en' => 'deployment', 'zh' => '部署', 'not' => array( '布署上线', '调遣派出' ) ),
	array( 'en' => 'commissioning', 'zh' => '调试', 'not' => array( '委托调试', '佣金安排', '委任启动' ) ),
	array( 'en' => 'Machinery Directive 2006/42/EC', 'zh' => '机械指令 2006/42/EC', 'not' => array( '机器指令 2006/42/EC' ) ),
	array( 'en' => 'unbalance', 'zh' => '不平衡量', 'not' => array( '失衡数值', '非平衡量', '不均衡量' ) ),
	array( 'en' => 'residual unbalance', 'zh' => '残余不平衡量', 'not' => array( '剩余不平衡', '残留失衡' ) ),
	array( 'en' => 'unbalance correction', 'zh' => '不平衡量修正', 'not' => array( '不平衡纠正', '失衡校正' ) ),
	array( 'en' => 'balance quality grade', 'zh' => '平衡品质等级', 'not' => array( '动平衡质量等级', '平衡质量级别' ) ),
	array( 'en' => 'balancing machine', 'zh' => '动平衡机', 'not' => array( '平衡器械', '找平衡的机器' ) ),
	array( 'en' => 'non-rotating balancing machine', 'zh' => '非旋转式动平衡机', 'not' => array( '无转子动平衡机', '不旋转动平衡机' ) ),
	array( 'en' => 'Non-Rotate Systems', 'zh' => '非旋转式系统', 'not' => array( '不旋转系统', '无旋转系统' ) ),
	array( 'en' => 'Core Balancing Machine', 'zh' => '芯体动平衡机', 'not' => array( '芯轴动平衡机', '铁芯动平衡机', '核心动平衡机' ) ),
	array( 'en' => 'Combined High-Speed and Low-Speed Core Balancing Machine', 'zh' => '高速与低速芯体动平衡一体机', 'not' => array( '高速和低速芯轴动平衡机组合', '高低速核心动平衡组合机' ) ),
	array( 'en' => 'High-Speed Core Balancing Machine', 'zh' => '高速芯体动平衡机', 'not' => array( '高速芯轴动平衡机', '高速核心动平衡机' ) ),
	array( 'en' => 'Low-Speed Core Balancing Machine', 'zh' => '低速芯体动平衡机', 'not' => array( '低速芯轴动平衡机', '低速核心动平衡机' ) ),
	array( 'en' => 'Axle balancing machine', 'zh' => '车桥动平衡机', 'not' => array( '轴承动平衡机', '车轴平衡器' ) ),
	array( 'en' => 'beam axle', 'zh' => '整体式车桥', 'not' => array( '梁式轴承', '横梁车轴' ) ),
	array( 'en' => 'third member', 'zh' => '主减速器总成', 'not' => array( '第三成员', '第三部件', '第三构件' ) ),
	array( 'en' => 'half case', 'zh' => '半壳体', 'not' => array( '半个箱体', '半个外壳' ) ),
	array( 'en' => 'Electric motor balancing machines', 'zh' => '电机转子动平衡机', 'not' => array( '电动马达动平衡机', '马达动平衡机' ) ),
	array( 'en' => 'electric motor', 'zh' => '电机', 'not' => array( '电动马达', '马达装置' ) ),
	array( 'en' => 'Brake Rotor Balancer', 'zh' => '制动盘动平衡机', 'not' => array( '制动平衡机', '刹车转子平衡器' ) ),
	array( 'en' => 'Pulley Balancer', 'zh' => '皮带轮动平衡机', 'not' => array( '皮带轮平衡机', '滑轮平衡器' ) ),
	array( 'en' => 'Propeller Balancers', 'zh' => '螺旋桨动平衡机', 'not' => array( '螺旋桨平衡机', '推进器平衡器' ) ),
	array( 'en' => 'Vertical', 'zh' => '立式', 'not' => array( '竖直旋转式', '垂直样式' ) ),
	array( 'en' => 'Horizontal', 'zh' => '卧式', 'not' => array() ),
	array( 'en' => 'horizontal cradle', 'zh' => '卧式摇架型', 'not' => array( '水平摇篮式' ) ),
	array( 'en' => 'horizontal spindle', 'zh' => '卧式主轴型', 'not' => array( '水平主轴式' ) ),
	array( 'en' => 'Horizontal Manual', 'zh' => '卧式手动型', 'not' => array( '水平手动式', '横向手动型' ) ),
	array( 'en' => 'pulley', 'zh' => '皮带轮', 'not' => array( '传动皮带' ) ),
	array( 'en' => 'flywheel', 'zh' => '飞轮', 'not' => array( '惯性轮盘', '飞行轮盘' ) ),
	array( 'en' => 'dual mass flywheel', 'zh' => '双质量飞轮', 'not' => array( '双质量离合器', '双重质量飞轮' ) ),
	array( 'en' => 'flexplate', 'zh' => '柔性盘', 'not' => array( '弹性板件', '挠性板块' ) ),
	array( 'en' => 'armature', 'zh' => '电枢', 'not' => array( '衔铁部件', '电动机转子' ) ),
	array( 'en' => 'bearers', 'zh' => '支承滚轮', 'not' => array( '承载零件', '托架零件' ) ),
	array( 'en' => 'pedestals', 'zh' => '支承座', 'not' => array( '底座平台', '基座立柱' ) ),
	array( 'en' => 'pins', 'zh' => '定位销', 'not' => array( '别针零件' ) ),
	array( 'en' => 'bearing center lines', 'zh' => '轴承中心线', 'not' => array( '轴颈中心线', '承载中线' ) ),
	array( 'en' => 'bearing life', 'zh' => '轴承寿命', 'not' => array( '轴承生命', '轴承使用生命' ) ),
	array( 'en' => 'tapered roller bearing', 'zh' => '圆锥滚子轴承', 'not' => array( '圆柱滚子轴承', '锥形滚珠轴承' ) ),
	array( 'en' => 'maximum rotor diameter', 'zh' => '最大转子直径', 'not' => array( '转子最大规格' ) ),
	array( 'en' => 'v-block support', 'zh' => 'V 型块支承', 'not' => array( 'V 形积木支撑', 'V 型砖块支架' ) ),
	array( 'en' => 'movable cradle', 'zh' => '可移动摇架', 'not' => array( '可移动底座', '活动摇篮' ) ),
	array( 'en' => 'retaining rollers', 'zh' => '压紧滚轮', 'not' => array( '保持辊子', '滞留滚筒' ) ),
	array( 'en' => 'walking beam system', 'zh' => '步进梁系统', 'not' => array( '行走梁系统', '走动横梁系统' ) ),
	array( 'en' => 'single station / multi station', 'zh' => '单工位／多工位', 'not' => array( '单室／多室', '单站／多站' ) ),
	array( 'en' => 'single bay', 'zh' => '单工位', 'not' => array( '单个舱位', '单个隔间' ) ),
	array( 'en' => 'fixed stations', 'zh' => '固定工位', 'not' => array( '固定车站', '固定站台' ) ),
	array( 'en' => 'mobile carousels', 'zh' => '移动式回转台', 'not' => array( '旋转木马', '移动木马' ) ),
	array( 'en' => 'burst proof protection', 'zh' => '防爆裂保护', 'not' => array( '防爆炸保护', '防止爆炸防护' ) ),
	array( 'en' => 'spin testing machine', 'zh' => '超速旋转试验机', 'not' => array( '旋转测试仪', '自旋试验机' ) ),
	array( 'en' => 'Spin Testing', 'zh' => '超速旋转试验', 'not' => array( '自旋测试', '旋转考核' ) ),
	array( 'en' => 'Electronic hung mass', 'zh' => '电子悬挂质量补偿', 'not' => array( '电子吊挂质量', '电子挂载质量' ) ),
	array( 'en' => 'field balancing', 'zh' => '现场动平衡', 'not' => array( '田间动平衡', '野外找平衡' ) ),
	array( 'en' => 'kinetostatics', 'zh' => '运动静力学', 'not' => array( '运动动力学', '静态运动学' ) ),
	array( 'en' => 'vibration', 'zh' => '振动', 'not' => array( '震动现象', '颤动现象' ) ),
	array( 'en' => 'punching', 'zh' => '冲孔去重', 'not' => array( '打孔机加工', '穿孔作业' ) ),
	array( 'en' => 'boreless compressor wheel', 'zh' => '无中心孔压气机叶轮', 'not' => array( '无轴承压气机叶轮', '无孔压缩机轮' ) ),
	array( 'en' => 'bore axis alignment', 'zh' => '内孔轴线对中', 'not' => array( '孔径对齐', '镗孔轴对准' ) ),
	array( 'en' => 'motorized clamping', 'zh' => '电动夹紧', 'not' => array( '机动化夹紧', '摩托化夹持' ) ),
	array( 'en' => 'in a single clamping', 'zh' => '一次装夹', 'not' => array( '单次夹紧', '一个夹钳内' ) ),
	array( 'en' => 'custom fixturing', 'zh' => '定制工装夹具', 'not' => array( '定制固定装置', '客制固定件' ) ),
	array( 'en' => 'setup cycles', 'zh' => '装夹调整周期', 'not' => array( '安装周期', '设置循环次数' ) ),
	array( 'en' => 'turbo calibration', 'zh' => '涡轮增压器校准', 'not' => array(  ) ),
	array( 'en' => 'turbocharger flow bench', 'zh' => '涡轮增压器流量试验台', 'not' => array( '涡轮增压器测功机' ) ),
	array( 'en' => 'Dynamic Turbocharger Flow Bench', 'zh' => '动态涡轮增压器流量试验台', 'not' => array( '动态流量台架', '动态涡轮流量长凳' ) ),
	array( 'en' => 'turbocharger frame size', 'zh' => '涡轮增压器壳体尺寸', 'not' => array( '框架尺寸', '机架大小' ) ),
	array( 'en' => 'whistle', 'zh' => '啸叫', 'not' => array( '哨子声响', '吹口哨声' ) ),
	array( 'en' => 'reconditioning', 'zh' => '翻新修复', 'not' => array( '翻新装修', '重新调理' ) ),
	array( 'en' => 'refrigerant', 'zh' => '制冷剂', 'not' => array( '冷媒介质' ) ),
	array( 'en' => 'refrigerant charging machines', 'zh' => '制冷剂充注机', 'not' => array( '冷却剂充注机', '制冷充注机器' ) ),
	array( 'en' => 'refrigerant charging', 'zh' => '制冷剂充注', 'not' => array( '制冷充注', '冷媒充填' ) ),
	array( 'en' => 'Refrigerant Charging Brochure', 'zh' => '制冷剂充注产品手册', 'not' => array( '制冷充注手册', '制冷剂充电手册' ) ),
	array( 'en' => 'refrigeration', 'zh' => '制冷', 'not' => array( '冷藏冷冻业' ) ),
	array( 'en' => 'leak detection', 'zh' => '泄漏检测', 'not' => array( '泄露检测', '漏泄侦测' ) ),
	array( 'en' => 'fine leak', 'zh' => '细检漏', 'not' => array( '精细泄漏', '细微渗漏' ) ),
	array( 'en' => 'gross leak test', 'zh' => '粗检漏测试', 'not' => array( '总泄漏测试', '毛泄漏测试' ) ),
	array( 'en' => 'sniffer', 'zh' => '吸枪', 'not' => array( '嗅探钳子', '闻探装置' ) ),
	array( 'en' => 'tracer gas', 'zh' => '示踪气体', 'not' => array( '追踪气体', '跟踪气体' ) ),
	array( 'en' => 'vacuum', 'zh' => '真空', 'not' => array( '负压状态' ) ),
	array( 'en' => 'vacuum evacuation', 'zh' => '抽真空', 'not' => array( '真空疏散', '真空撤离', '排空真空' ) ),
	array( 'en' => 'Evacuation', 'zh' => '抽真空', 'not' => array( '疏散撤离', '排空作业' ) ),
	array( 'en' => 'vacuum rise test', 'zh' => '真空升压试验', 'not' => array( '负压上升测试', '真空上升考核' ) ),
	array( 'en' => 'pressurization', 'zh' => '加压', 'not' => array( '压力化处理' ) ),
	array( 'en' => 'final discharge', 'zh' => '最终排气', 'not' => array( '最终放电', '末端卸载' ) ),
	array( 'en' => 'filler', 'zh' => '充注工位', 'not' => array( '填充物料', '腻子填料' ) ),
	array( 'en' => 'filler gun', 'zh' => '充注枪', 'not' => array( '填充枪支', '加料手枪' ) ),
	array( 'en' => 'flammable gases', 'zh' => '易燃气体', 'not' => array( '燃烧气体', '着火气体' ) ),
	array( 'en' => 'sealed assembly', 'zh' => '密封总成', 'not' => array( '盖章总成', '封印组件' ) ),
	array( 'en' => 'cooling units', 'zh' => '冷却装置', 'not' => array( '冷却单元格', '降温单位' ) ),
	array( 'en' => 'air cycle machines', 'zh' => '空气循环机', 'not' => array( '空气周期机器', '气体循环装置' ) ),
	array( 'en' => 'water-cooled', 'zh' => '水冷', 'not' => array( '冷却水的', '用水降温的' ) ),
	array( 'en' => 'energy recuperation', 'zh' => '能量回收', 'not' => array( '能量康复', '能源痊愈' ) ),
	array( 'en' => 'hazardous area', 'zh' => '危险区域', 'not' => array( '有害区域', '危害地带' ) ),
	array( 'en' => 'keg', 'zh' => '啤酒桶', 'not' => array( '小桶包装', '木桶容器' ) ),
	array( 'en' => 'keg finger holes', 'zh' => '桶身抓握孔', 'not' => array( '手指孔洞', '指头孔洞' ) ),
	array( 'en' => 'ADAS', 'zh' => 'ADAS', 'not' => array( '高级驾驶员辅助系统', '先进驾驶辅助系统' ) ),
	array( 'en' => 'ADAS alignment', 'zh' => 'ADAS 校准', 'not' => array( 'ADAS 对准', 'ADAS 车轮定位', 'ADAS 找正' ) ),
	array( 'en' => 'OBD', 'zh' => 'OBD', 'not' => array( '车载诊断系统', '车载自诊断' ) ),
	array( 'en' => 'transmission', 'zh' => '变速箱', 'not' => array( '传动装置', '传输装置', '变速传输' ) ),
	array( 'en' => 'gearbox', 'zh' => '变速箱', 'not' => array( '齿轮盒体', '齿轮机箱' ) ),
	array( 'en' => 'crankshaft lathe', 'zh' => '曲轴车床', 'not' => array( '连杆车床', '曲柄旋床' ) ),
	array( 'en' => 'inline crankshaft', 'zh' => '直列曲轴', 'not' => array( '四冲程曲轴', '在线曲轴' ) ),
	array( 'en' => 'single cylinder crankshaft', 'zh' => '单缸曲轴', 'not' => array( '单轨曲轴', '独缸曲柄轴' ) ),
	array( 'en' => 'pinion gear', 'zh' => '主动齿轮', 'not' => array( '轴颈齿轮', '销子齿轮' ) ),
	array( 'en' => 'ring gears', 'zh' => '齿圈', 'not' => array( '环形齿轮', '圆环齿轮' ) ),
	array( 'en' => 'front strut', 'zh' => '前悬架支柱', 'not' => array( '前保险杠支柱', '前制动卡钳', '前部立柱' ) ),
	array( 'en' => 'dynamometer', 'zh' => '测功机', 'not' => array( '动力计量仪', '测力计装置' ) ),
	array( 'en' => 'chassis dynamometer, 2- and 4-wheel', 'zh' => '双轮与四轮底盘测功机', 'not' => array( '二轴和四轴底盘测功机', '双轴四轴底盘测功机' ) ),
	array( 'en' => 'inline dyno', 'zh' => '线内测功机', 'not' => array( '在线动力计', '串联测力计' ) ),
	array( 'en' => 'roller brake tester', 'zh' => '滚筒式制动检验台', 'not' => array( '滚轮制动测试仪', '辊式刹车检测器' ) ),
	array( 'en' => 'roller', 'zh' => '滚筒', 'not' => array( '辊子部件', '滚轴部件' ) ),
	array( 'en' => 'rolling torque', 'zh' => '滚动阻力矩', 'not' => array( '轴扭矩数值', '滚压转矩' ) ),
	array( 'en' => 'wheel aligner', 'zh' => '四轮定位仪', 'not' => array( '车轮对准器', '轮胎校直机' ) ),
	array( 'en' => 'wheel alignment', 'zh' => '四轮定位', 'not' => array( '车轮对齐', '轮胎校准', '车轮找正' ) ),
	array( 'en' => 'tire inflator', 'zh' => '轮胎充气机', 'not' => array( '打气筒具', '轮胎膨胀器' ) ),
	array( 'en' => 'bead breaking', 'zh' => '胎圈分离', 'not' => array( '断珠处理', '破碎胎面', '打破珠子' ) ),
	array( 'en' => 'drivability', 'zh' => '驾驶性能', 'not' => array( '可驾驶性', '能开动性' ) ),
	array( 'en' => 'instrument cluster', 'zh' => '组合仪表', 'not' => array( '仪表集群', '仪器簇群' ) ),
	array( 'en' => 'control module', 'zh' => '控制模块', 'not' => array( '管制模块', '检查模块' ) ),
	array( 'en' => 'blank ECM', 'zh' => '未刷写 ECM', 'not' => array( '空白 ECM', '空的 ECM' ) ),
	array( 'en' => 'engine software loaders', 'zh' => '发动机程序刷写设备', 'not' => array( '发动机加载程序', '引擎软件装载器' ) ),
	array( 'en' => 'gear shift calibration', 'zh' => '换挡校准', 'not' => array( '齿轮移位校准', '换挡标定' ) ),
	array( 'en' => 'restbus simulation', 'zh' => '剩余总线仿真', 'not' => array( '静态总线仿真', '休息总线模拟' ) ),
	array( 'en' => 'torque vectoring', 'zh' => '扭矩矢量分配', 'not' => array( '转矩向量化' ) ),
	array( 'en' => 'traction battery', 'zh' => '动力电池', 'not' => array( '牵引电池', '电瓶组件' ) ),
	array( 'en' => 'e-axle', 'zh' => '电驱桥', 'not' => array( '电动车轴', '电子轴桥' ) ),
	array( 'en' => 'two-wheel drive', 'zh' => '两轮驱动', 'not' => array( '二轮传动', '双轮传输' ) ),
	array( 'en' => 'squeak & rattle testing', 'zh' => '异响测试', 'not' => array( '吱吱声与咔哒声测试', '尖叫与咯咯声试验' ) ),
	array( 'en' => 'EMC darkroom', 'zh' => '电磁兼容暗室', 'not' => array( '电磁暗房' ) ),
	array( 'en' => 'end of line testing', 'zh' => '生产线末端测试', 'not' => array( '线路末端测试', '线尾考试' ) ),
	array( 'en' => 'audit stations', 'zh' => '抽检工位', 'not' => array( '审计站点', '审核车站' ) ),
	array( 'en' => 'automated handling cells', 'zh' => '自动化上下料单元', 'not' => array( '自动处理单元格', '自动搬运细胞' ) ),
	array( 'en' => 'machining cell', 'zh' => '加工单元', 'not' => array( '机加工细胞' ) ),
	array( 'en' => 'gantry', 'zh' => '龙门机械手', 'not' => array( '高架桥架', '门户支架' ) ),
	array( 'en' => 'gantry milling', 'zh' => '龙门铣削', 'not' => array( '门式铣削', '桥式研磨' ) ),
	array( 'en' => 'commercial vehicle', 'zh' => '商用车', 'not' => array( '商业车辆', '贸易汽车' ) ),
	array( 'en' => 'off-highway', 'zh' => '非公路', 'not' => array( '离开公路', '越野公路' ) ),
	array( 'en' => 'actuation systems', 'zh' => '作动系统', 'not' => array( '执行机构系统', '激活系统' ) ),
	array( 'en' => 'landing gear systems', 'zh' => '起落架系统', 'not' => array( '着陆装置系统', '降落齿轮系统' ) ),
	array( 'en' => 'rotor wing aircraft', 'zh' => '旋翼机', 'not' => array( '螺旋桨飞机', '转子翼飞机' ) ),
	array( 'en' => 'HMU/FMU', 'zh' => 'HMU/FMU', 'not' => array( '液压与气动装置', '液压气动单元' ) ),
	array( 'en' => 'lube & scavenge pumps', 'zh' => '滑油与回油泵', 'not' => array( '润滑与排气泵', '润滑与清扫泵' ) ),
	array( 'en' => 'oil drain', 'zh' => '放油口', 'not' => array( '排气孔道', '通气孔口' ) ),
	array( 'en' => 'power drive units', 'zh' => '动力驱动装置', 'not' => array( '电源驱动单元', '功率传动单位' ) ),
	array( 'en' => 'cargo loading systems', 'zh' => '货物装载系统', 'not' => array( '集装箱装载系统', '船货装运系统' ) ),
	array( 'en' => 'blowers', 'zh' => '鼓风机', 'not' => array( '吹风机具', '吹气装置' ) ),
	array( 'en' => 'HVAC Blowers', 'zh' => 'HVAC 鼓风机', 'not' => array( '暖通空调鼓风机', '空调吹风机' ) ),
	array( 'en' => 'special test facilities', 'zh' => '专用试验设施', 'not' => array( '专业测试设施', '特别考试设备' ) ),
	array( 'en' => 'test stands', 'zh' => '试验台', 'not' => array( '测试台架', '测试平台架' ) ),
	array( 'en' => 'test benches', 'zh' => '试验台', 'not' => array( '测试长凳', '检测板凳' ) ),
	array( 'en' => 'aperture plate', 'zh' => '孔板', 'not' => array( '光圈板件', '孔径薄片' ) ),
	array( 'en' => 'snubber', 'zh' => '液压缓冲器', 'not' => array( '消音器件', '减震橡胶块' ) ),
	array( 'en' => 'cushion testing', 'zh' => '终端缓冲试验', 'not' => array( '坐垫测试', '靠垫检验' ) ),
	array( 'en' => 'soak time', 'zh' => '静置时间', 'not' => array( '浸泡时间', '泡水时长' ) ),
	array( 'en' => 'valve body unit', 'zh' => '阀体总成', 'not' => array( '阀门主体单元', '阀身单位' ) ),
	array( 'en' => 'valve stacks', 'zh' => '阀组', 'not' => array( '阀门堆栈', '阀门叠层' ) ),
	array( 'en' => 'stem stickiness', 'zh' => '阀杆卡滞', 'not' => array( '阀杆粘度', '阀杆黏性' ) ),
	array( 'en' => 'hydraulic pilot', 'zh' => '液压先导控制', 'not' => array( '液压飞行员', '液压导航' ) ),
	array( 'en' => 'load sense signal', 'zh' => '负载敏感信号', 'not' => array( '载荷传感器信号', '负荷感觉信号' ) ),
	array( 'en' => 'fluid power', 'zh' => '流体动力', 'not' => array( '流质力量', '液体功率' ) ),
	array( 'en' => 'drift', 'zh' => '沉降量', 'not' => array( '漂移现象', '飘移数值' ) ),
	array( 'en' => 'push and pull', 'zh' => '推进与回拖', 'not' => array( '压力与拉伸', '推动和拉动' ) ),
	array( 'en' => 'thrust force / pullback force', 'zh' => '推进力／回拖力', 'not' => array( '轴向力数值', '推力与拉回力量' ) ),
	array( 'en' => 'debonding', 'zh' => '脱粘', 'not' => array( '解除粘合', '去除黏结' ) ),
	array( 'en' => 'surface separations', 'zh' => '表面分层', 'not' => array( '表面分离动作', '表层隔离' ) ),
	array( 'en' => 'mill roll', 'zh' => '轧辊', 'not' => array( '磨辊零件', '辊筒零件', '辊轴零件' ) ),
	array( 'en' => 'Roll Inspection', 'zh' => '轧辊检测', 'not' => array( '辊轴检测', '辊筒检测', '滚子检查' ) ),
	array( 'en' => 'Roll Grinding Machines', 'zh' => '轧辊磨床', 'not' => array( '辊磨机床', '轧辊研磨机', '滚磨机床' ) ),
	array( 'en' => 'roll grinding', 'zh' => '轧辊磨削', 'not' => array( '辊磨加工', '滚子研磨' ) ),
	array( 'en' => 'Roll Shop Technologies', 'zh' => '轧辊车间技术', 'not' => array( 'Roll Shop Technologies', '轧辊商店技术' ) ),
	array( 'en' => 'roll shop', 'zh' => '轧辊车间', 'not' => array( '轧辊商店', '辊子店铺' ) ),
	array( 'en' => 'forged rolls', 'zh' => '锻钢轧辊', 'not' => array( '伪造轧辊', '锻造滚子' ) ),
	array( 'en' => 'grinding wheel', 'zh' => '砂轮', 'not' => array( '磨轮盘片', '研磨盘片' ) ),
	array( 'en' => 'superabrasives', 'zh' => '超硬磨料', 'not' => array( '超级研磨剂', '超级砂纸' ) ),
	array( 'en' => 'rotary diamond dressing', 'zh' => '金刚石滚轮修整', 'not' => array( '旋转金刚石纹理化', '回转钻石修饰' ) ),
	array( 'en' => 'turret-style wheel head', 'zh' => '转塔式砂轮架', 'not' => array( '炮塔式砂轮头', '塔楼式轮头' ) ),
	array( 'en' => 'infeed', 'zh' => '进给', 'not' => array( '输入进给', '喂入动作' ) ),
	array( 'en' => 'electrical discharge texturing (EDT)', 'zh' => '电火花毛化（EDT）', 'not' => array( '电放电纹理化', '放电织构化' ) ),
	array( 'en' => '20-high rolling mills', 'zh' => '二十辊轧机', 'not' => array( '二十高轧机', '20 层轧机' ) ),
	array( 'en' => 'six-high rolling mills', 'zh' => '六辊轧机', 'not' => array( '六高轧机', '六层轧机' ) ),
	array( 'en' => 'Tandem rolling mills', 'zh' => '连轧机组', 'not' => array( '串联轧机', '双联轧机' ) ),
	array( 'en' => 'cold pilger mill', 'zh' => '冷轧管机', 'not' => array( '冷朝圣轧机', '冷皮尔格磨机' ) ),
	array( 'en' => 'strip', 'zh' => '带钢', 'not' => array( '板材条料', '条带材料', '剥离物料' ) ),
	array( 'en' => 'Strip Lines', 'zh' => '带钢生产线', 'not' => array( '条带线路', '剥离生产线' ) ),
	array( 'en' => 'blast furnace', 'zh' => '高炉', 'not' => array( '鼓风炉膛', '爆破炉膛' ) ),
	array( 'en' => 'tap hole', 'zh' => '出铁口', 'not' => array( '炉口位置', '水龙头孔' ) ),
	array( 'en' => 'tap hole drilling', 'zh' => '出铁口钻孔', 'not' => array( '炉口钻孔', '龙头打孔' ) ),
	array( 'en' => 'clay gun', 'zh' => '泥炮', 'not' => array( '粘土枪械', '黏土手枪', '泥土枪支' ) ),
	array( 'en' => 'tin plating', 'zh' => '镀锡', 'not' => array( '镀锌处理', '锡皮涂层' ) ),
	array( 'en' => 'spalls', 'zh' => '剥落', 'not' => array( '脱皮现象', '起皮薄片' ) ),
	array( 'en' => 'pinches & bruises', 'zh' => '挤伤与碰伤', 'not' => array( '捏痛与瘀伤', '夹痛和擦伤' ) ),
	array( 'en' => 'Detection Focus', 'zh' => '检测缺陷范围', 'not' => array( '检测焦点', '侦测重点' ) ),
	array( 'en' => 'eddy current technology', 'zh' => '涡流技术', 'not' => array( '漩涡电流技术', '现今电流技术' ) ),
	array( 'en' => 'non-destructive testing (NDT)', 'zh' => '无损检测（NDT）', 'not' => array( '非破坏性测试' ) ),
	array( 'en' => 'probe alignment', 'zh' => '探头对中', 'not' => array( '探头对齐', '探头校准', '探针对准' ) ),
	array( 'en' => 'misalignment', 'zh' => '对中偏差', 'not' => array( '未对齐状态', '错位情况' ) ),
	array( 'en' => 'dial indicator', 'zh' => '百分表', 'not' => array( '拨号指示器', '刻度盘指示灯' ) ),
	array( 'en' => 'TIR / radial run-out', 'zh' => '径向跳动（TIR）', 'not' => array( 'TIR 运行量', '径向运转量' ) ),
	array( 'en' => 'machine tools', 'zh' => '机床', 'not' => array( '机器工具', '加工机器', '机械工具' ) ),
	array( 'en' => 'boring', 'zh' => '镗削', 'not' => array( '钻孔加工' ) ),
	array( 'en' => 'deep hole drilling', 'zh' => '深孔钻削', 'not' => array( '深洞钻孔', '深坑打孔' ) ),
	array( 'en' => 'gundrill', 'zh' => '枪钻', 'not' => array( '枪支钻孔', '火枪钻头' ) ),
	array( 'en' => 'boring drill', 'zh' => '水平定向钻机', 'not' => array( '镗孔钻头', '无聊的钻头' ) ),
	array( 'en' => 'horizontal boring machine', 'zh' => '卧式镗床', 'not' => array( '水平钻孔机', '卧式钻床' ) ),
	array( 'en' => '3-jaw chuck', 'zh' => '三爪卡盘', 'not' => array( '三颚夹头', '三个下巴卡盘' ) ),
	array( 'en' => 'collet chuck', 'zh' => '弹簧夹头', 'not' => array( '气动夹头', '项圈卡盘' ) ),
	array( 'en' => 'chip vacuum', 'zh' => '切屑抽吸装置', 'not' => array( '芯片吸尘器', '薯片真空' ) ),
	array( 'en' => 'ultrasonic nozzle cleaner', 'zh' => '超声波喷嘴清洗机', 'not' => array( '超音波清洁器', '超声喷管清洗' ) ),
	array( 'en' => 'brushing and polishing machines', 'zh' => '刷光与抛光机', 'not' => array( '刷牙抛光机', '涂刷打磨机' ) ),
	array( 'en' => 'active part probing', 'zh' => '工件主动测量', 'not' => array( '主动零件探测', '活跃部件探针' ) ),
	array( 'en' => 'lubrication', 'zh' => '润滑', 'not' => array( '换油作业' ) ),
	array( 'en' => 'anchoring', 'zh' => '地脚锚固', 'not' => array( '抛锚固定', '锚定抛下' ) ),
	array( 'en' => 'ultra-stable design', 'zh' => '超高稳定性结构', 'not' => array( '超耐用设计', '极稳定项目' ) ),
	array( 'en' => 'infinitely variable', 'zh' => '无级可调', 'not' => array( '无限可变', '无穷变化' ) ),
	array( 'en' => 'adaptive speed control', 'zh' => '自适应转速控制', 'not' => array( '适应性速度管制', '自适应速率检查' ) ),
	array( 'en' => 'higher-level control system', 'zh' => '上位控制系统', 'not' => array( '更高级别控制系统', '较高层检查系统' ) ),
	array( 'en' => 'controls', 'zh' => '控制系统', 'not' => array( '管制系统', '检查系统' ) ),
	array( 'en' => 'process recipe', 'zh' => '工艺配方', 'not' => array( '处方单据', '菜谱食谱' ) ),
	array( 'en' => 'tension', 'zh' => '张力', 'not' => array( '紧张情绪', '电压数值' ) ),
	array( 'en' => 'load capacity', 'zh' => '承载能力', 'not' => array( '负载容量', '装载体积' ) ),
	array( 'en' => 'weight capacity', 'zh' => '承重能力', 'not' => array( '重量容量', '体重容积' ) ),
	array( 'en' => 'seamless link', 'zh' => '无缝衔接', 'not' => array( '无缝连接器', '无缝链接件' ) ),
	array( 'en' => 'implements', 'zh' => '机具', 'not' => array( '实施器具', '实现工具', '履行器具' ) ),
	array( 'en' => 'Implements - End-Of-Line', 'zh' => '机具 – 生产线末端', 'not' => array( '实施器 – 生产线末端', '实现工具 – 线末' ) ),
	array( 'en' => 'implement position verification', 'zh' => '机具位置验证', 'not' => array( '实施器定位验证', '实现工具位置核实' ) ),
	array( 'en' => 'motor grader', 'zh' => '平地机', 'not' => array( '电动平地机', '马达分级机', '汽车平地机' ) ),
	array( 'en' => 'Motor Graders', 'zh' => '平地机', 'not' => array( 'Motor Graders', '马达评分器' ) ),
	array( 'en' => 'excavator', 'zh' => '挖掘机', 'not' => array( '开挖机具', '挖土器具' ) ),
	array( 'en' => 'backhoe', 'zh' => '挖掘装载机', 'not' => array( '后铲机械', '背锄机械' ) ),
	array( 'en' => 'baler', 'zh' => '打捆机', 'not' => array( '压包机具', '打包器械' ) ),
	array( 'en' => 'combine', 'zh' => '联合收割机', 'not' => array( '组合机具', '联合机器' ) ),
	array( 'en' => 'draper header', 'zh' => '输送带式割台', 'not' => array( '布帘割台', '拖拉机割台' ) ),
	array( 'en' => 'hay mower', 'zh' => '割草机', 'not' => array( '干草切割器', '牧草剪刀' ) ),
	array( 'en' => 'sprayers', 'zh' => '喷雾机', 'not' => array( '喷头装置', '喷嘴组件', 'Sprayers', '喷洒器具' ) ),
	array( 'en' => 'blade', 'zh' => '铲刀', 'not' => array( '平地机刀片', '平地机叶片' ) ),
	array( 'en' => 'blade timing', 'zh' => '铲刀动作时序', 'not' => array( '刀片计时', '叶片定时' ) ),
	array( 'en' => 'PTO', 'zh' => '动力输出轴', 'not' => array( '功率输出装置', '动力取出器' ) ),
	array( 'en' => 'mudding system', 'zh' => '泥浆系统', 'not' => array( '泥土系统', '烂泥装置' ) ),
	array( 'en' => 'heavy-duty', 'zh' => '重载型', 'not' => array( '沉重型号', '笨重型号' ) ),
	array( 'en' => 'water meter', 'zh' => '水表', 'not' => array( '水米计量', '水计量器' ) ),
	array( 'en' => 'Transportation', 'zh' => '交通运输', 'not' => array( '物流部门', '货运部门' ) ),
	array( 'en' => 'Aerospace & industrials', 'zh' => '航空航天与工业', 'not' => array( '航空与工业', '航天与工业部门', '宇航及产业' ) ),
	array( 'en' => 'Medical', 'zh' => '医疗', 'not' => array( '医学性的' ) ),
	array( 'en' => 'life sciences', 'zh' => '生命科学', 'not' => array( '生物科学', '生活科学' ) ),
	array( 'en' => 'marine', 'zh' => '船舶行业', 'not' => array( '海洋行业', '海军领域' ) ),
	array( 'en' => 'applications', 'zh' => '应用领域', 'not' => array( '应用程序', '软件应用' ) ),
	array( 'en' => 'Products', 'zh' => '产品', 'not' => array(  ) ),
	array( 'en' => 'Core / Plus / Elite', 'zh' => 'Core、Plus、Elite', 'not' => array( '核心版、增强版、精英版', '基础版、加强版、旗舰版' ) ),
	array( 'en' => 'Ascential Indemnity', 'zh' => 'Ascential 的赔偿责任', 'not' => array( 'Ascential 赔款', 'Ascential 补偿金' ) ),
	array( 'en' => 'uptime', 'zh' => '正常运行时间', 'not' => array( '上线时间', '上传时间' ) ),
	array( 'en' => 'failure rates', 'zh' => '校准不合格率', 'not' => array( '故障发生率', '失败比率' ) ),
	array( 'en' => 'Featuring', 'zh' => '搭载', 'not' => array( '以此为特色', '特色在于' ) ),
	array( 'en' => 'Powered by', 'zh' => '技术支持：', 'not' => array( '由此供电', '动力来自于' ) ),
	array( 'en' => 'patented', 'zh' => '已获专利', 'not' => array( '待批专利', '专利申请中' ) ),
	array( 'en' => 'responsive', 'zh' => '快速响应', 'not' => array( '响应式设计', '自适应网页' ) ),
	array( 'en' => 'represent', 'zh' => '复现', 'not' => array( '代表出席', '代理表示' ) ),
	array( 'en' => 'testing', 'zh' => '测试', 'not' => array() ),
);
